### ISSUE TITLE
Clarity Request: Unexpected "Not Authorized" with IAM and Transformer v2

### ISSUE THREAD

**Issue by danrivett** [aws-amplify/amplify-category-api#100]
### Which Category is your question related to?

[GraphQL Transformer v2](https://aws.amazon.com/blogs/mobile/aws-amplify-announces-the-new-graphql-transformer-v2-more-feature-rich-flexible-and-extensible/)

### Amplify CLI Version

7.6.22

### Summary of Problem

Since moving to the v2 Transformer we're now seeing our Lambdas which use IAM to access the AppSync API fail with:

```
Not Authorized to access XXX on type Mutation
```

It appears unrelated to the documented [deny-by-default](https://docs.amplify.aws/cli/migration/transformer-migration/#authorization-rule-changes) change.

### Description of Problem

I'm in the process of migrating our existing Amplify GraphQL API (AppSync) over to use the [GraphQL Transformer v2](https://aws.amazon.com/blogs/mobile/aws-amplify-announces-the-new-graphql-transformer-v2-more-feature-rich-flexible-and-extensible/) however I'm running into an unexpected change in IAM authorization rules that do not appear to be related (or at least adequately explained) by the new general deny-by-default authorization change.

Our GraphQL API uses Cognito User Pools as the default authentication mechanism, and is used on the frontend by customers who log into their account.

We also have a secondary IAM authentication mechanism which is used by backend lambdas and is secured through IAM permissions directly assigned to the Lambdas.

We have several GraphQL models such as the following:

```graphql
type User
  @model
  @auth(
    rules: [
      { allow: owner, ownerField: "cognitoUserId" }
      { allow: private, provider: iam } # Allow CRUD access from the backend
    ]
  ) {
  id: ID!
  cognitoUserId: ID!
  cognitoIdentityId: ID!
  firstName: String!
  lastName: String!
  phone: AWSPhone!
  email: AWSEmail!
  ...
}
```

On v1 of the GraphQL Transformer, this works great. However on v2, we're seeing:

```json
{
  "path": [
    "updateUser"
  ],
  "data": null,
  "errorType": "Unauthorized",
  "errorInfo": null,
  "locations": [{
    "line": 2,
    "column": 3,
    "sourceName": null
  }],
  "message": "Not Authorized to access updateUser on type Mutation"
}
```

I don't believe this is explained by the new [deny-by-default](https://docs.amplify.aws/cli/migration/transformer-migration/#authorization-rule-changes) change, and I verified this by also explicitly listing the operations:

```js
{ allow: private, provider: iam, operations: [create, read, update, delete] } # Allow CRUD access from the backend
```

What I am seeing is the generated `Mutation.updateUser.auth.1.res.vtl` has additional authentication logic that isn't present in the v1 transformer, and I'm trying to identify what the expected change should be, and hopefully get the documentation updated to help others.

### Comparison of v1 Transformer to v2

The key change I've observed is that in v1's `Mutation.updateUser.req.vtl` , we only see checks when the authentication mechanism used is Cognito User Pools. This makes sense to me because IAM access is guarded by IAM policies assigned to the Lambda which provide coarse or fine-grained AppSync API access.

In v1's `Mutation.updateUser.req.vtl`, we only see:
```
#if( $authMode == "userPools" )
```

We do not see any logic with:

```
#if( $authMode == "iam" )
```

However in v2's `Mutation.updateUser.auth.1.res.vtl`, I'm now seeing a separate block for when IAM is being used:

```vtl
#if( $util.authType() == "IAM Authorization" )
  #set( $adminRoles = ["AdminQueriesxxxxx-dan"] )
  #foreach( $adminRole in $adminRoles )
    #if( $ctx.identity.userArn.contains($adminRole) && $ctx.identity.userArn != $ctx.stash.authRole && $ctx.identity.userArn != $ctx.stash.unauthRole )
      #return($util.toJson({}))
    #end
  #end
  #if( ($ctx.identity.userArn == $ctx.stash.authRole) || ($ctx.identity.cognitoIdentityPoolId == "us-west-2:xxxxx" && $ctx.identity.cognitoIdentityAuthType == "authenticated") )
    #set( $isAuthorized = true )
  #end
#end
```

It's this block in particular that is interesting to me:

```vtl
  #if( ($ctx.identity.userArn == $ctx.stash.authRole) || ($ctx.identity.cognitoIdentityPoolId == "us-west-2:xxxxx" && $ctx.identity.cognitoIdentityAuthType == "authenticated") )
    #set( $isAuthorized = true )
  #end
```

This is doesn't evaluate to `true` and so `isAuthorized` isn't set to `true` and so the error above is returned.

Looking at the `context.identity` object being created the for the IAM access from the lambda I see something like:

```json
{
  "accountId": "XXX",
  "cognitoIdentityAuthProvider": null,
  "cognitoIdentityAuthType": null,
  "cognitoIdentityId": null,
  "cognitoIdentityPoolId": null,
  "sourceIp": ["XXX"],
  "userArn": "arn:aws:sts::XXX:assumed-role/appsync-user-created-handler-dan-us-west-2-lambdaRole/appsync-user-created-handler",
  "username": "XXX:appsync-user-created-handler"
}
```

Notice that `userArn` value which is the role assumed by the Lambda that was generated by our IaC framework - the Serverless Framework in our case - which defined the IAM permission to invoke this AppSync GraphQL endpoint. It doesn't match `$ctx.stash.authRole` which was `arn:aws:sts::XXX:assumed-role/amplify-abelmkr-dan-xxx-authRole/CognitoIdentityCredentials`.

Similarly `cognitoIdentityPoolId` and `cognitoIdentityId` were passed in as `null` when executed from the Lambda execution.

### Understanding the Change and What Migration Steps are Required

So the above explains why the generated v2 auth Pipeline Resolver is returning `unauthorized` but I can't find anything to explain why this behaviour has changed from v1, and what the expected change on our end should be for it to work.

It seems like the Resolver is requiring all the Lambdas using IAM to assume that `authRole`, but I'm not sure the best way to do that. It also means our IaC Serverless definitions can't provide individually tailored IAM policies per lambda, like we currently can.

### Desired Outcome

Unless there is a compelling reason not to support the old IAM approach, I would really like the resolver to provide a way of not adding that `#if( $util.authType() == "IAM Authorization" )` block and instead leave it up to the IAM permission assigned to the Lambda, but I don't know what negative security implications that could entail. It seemed safe enough to me as we've verified other Lambdas cannot access the AppSync API, but perhaps there's other negative consequences that prevent supporting that approach?

Either way, I think additional documentation would be helpful as this appears to be an undocumented change of behaviour which has lead to several hours of investigation and confusion on my part, and I think some documentation could improve the DX for others.

**Comment by hisham** [comment]
+1 - also ran into this when upgrading my project. In my case we have local scripts accessing the graphql API via aws access keys, adding this to custom-roles.json resolved the issue: 

```
{
  "adminRoleNames": ["arn:aws:iam::<AccountId>:user"]
}
```

**Comment by vincent38wargnier** [comment]
Hi,
I had the same issue in transformer v1, and now I have it with transformer v2 too. I removed pushed, and recreated y table and it worked. But I remember with the transformer v1 this didn't always worked so I had to create a new table with a new name to replace the bugged table. :/

**Comment by sundersc** [comment]
@DanieleMoschiniMac Do you see the issue even after adding the IAM role to `adminRoleNames` on `custom-roles.json` file as mentioned [here](https://github.com/aws-amplify/amplify-category-api/issues/100#issuecomment-1129353040)?

**Comment by DanieleMoschiniMac** [comment]
It worked, but the problem still there

**Comment by ErhardScampi** [comment]
I have an productions env which is now down because of that......
So I think amplify is not production ready. If I see how long such a Hughe error for so many use cases is open.....My fault that a did not test that and migrated from 5 to 10.....
Can anybody tell me which version worked last ?
Do I have to copy the custom-roles.json to backend/api. or to backend/api/<myprojectName>. ? 
Do I have create this role adminRoleNames in IAM in the was console ?

**Comment by hoan-pham-duy** [comment]
Got the same problem, 

> accessing

Hi, I got the same problem, but after add: {
  "adminRoleNames": ["arn:aws:iam::<AccountId>:user"]
}
I can't run query at both console and CLI. Can you check that it stills work?

**Comment by Lekha30** [comment]
> here

Is there way to do this with AWS-sdk V3?

**Comment by renebrandel** [comment]
Hi folks - just to close the loop on this. We've since added additional documentation on how to enable access to the GraphQL API from a Lambda function or the AWS AppSync:
- https://docs.amplify.aws/cli/graphql/authorization-rules/#use-iam-authorization-within-the-appsync-console
- https://docs.amplify.aws/cli/graphql/authorization-rules/#grant-lambda-function-access-to-graphql-api 

For future, we've also now brought the [Amplify GraphQL API to CDK as a construct](https://aws.amazon.com/blogs/mobile/announcing-aws-amplifys-graphql-api-cdk-construct-deploy-real-time-graphql-api-and-data-stack-on-aws/), in which you can explicitly pass in the Lambda execution to programmatically ensure access stays "in sync" between different environments.

**Comment by samueldominguez** [comment]
Using CDK v3 and I tried adding `custom-roles.json` to no avail. Turns out the issue was not adding a `/*` to the ARN, that seems to fix it:
```
lambdaAppSyncRole.addToPolicy(new PolicyStatement({
      actions: ['appsync:GraphQL'],
      resources: [`${config.APPSYNC_API_ARN}/*`],
}));
```

**Comment by stemwinder** [comment]
> @danrivett - Thanks for the details. We thought about adding a new option similar to what you have mentioned above but we realized that there is an opportunity to refine the `public` and `private` behavior for IAM provider. We will have more details in the coming weeks.
> 
> However I just realized that there is an escape hatch which may solve the problem in your scenario. Set the `adminRoleNames` in `custom-roles.json` as shown below. This will make sure that the VTL allow access to all the Lambda execution roles for the given accountId.
> 
> ```json
> {
>   "adminRoleNames": ["arn:aws:sts::<AccountIdHere>:assumed-role"]
> }
> ```

Is there any strategy to add custom roles per environment? We have dev and prod environments in separate accounts.

**Comment by stemwinder** [comment]
> > @danrivett - Thanks for the details. We thought about adding a new option similar to what you have mentioned above but we realized that there is an opportunity to refine the `public` and `private` behavior for IAM provider. We will have more details in the coming weeks.
> > However I just realized that there is an escape hatch which may solve the problem in your scenario. Set the `adminRoleNames` in `custom-roles.json` as shown below. This will make sure that the VTL allow access to all the Lambda execution roles for the given accountId.
> > ```json
> > {
> >   "adminRoleNames": ["arn:aws:sts::<AccountIdHere>:assumed-role"]
> > }
> > ```
> 
> Is there any strategy to add custom roles per environment? We have dev and prod environments in separate accounts.

Update: The VTL resolver context appears to include the current AWS Account ID. Initial testing with `arn:aws:sts::${context.identity.accountId}:assumed-role` appears to work as expected.

**Comment by sundersc** [comment]
With Amplify Gen2, you can use IAM authorization using the below snippet. Your API access will be completely controlled by IAM, no additional configuration is needed.

```ts
// amplify/data/resources.ts
import { defineData } from '@aws-amplify/backend';
import { schema } from './schema';

export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: 'iam',    // <--- IAM Authorization mode
  },
});
```
