### ISSUE TITLE
amplify-dev not working after yarn setup-dev

### ISSUE THREAD

**Issue by ncarvajalc** [aws-amplify/amplify-category-api#1005]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.18.0

### Amplify CLI Version

10.4.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

Since 2022-11-11 the `amplify-dev` command is not working after running `yarn setup-dev`. The command runs as if no changes where being made to the local amplify-category-api repo.

### Expected behavior

The `amplify-dev` command should work with the local changes made in amplify-category-api after running `yarn setup-dev` 

### Reproduction steps

1. Clone the amplify-category-api repo
2. Make a change in one of the packages
3. Run `yarn setup-dev`
4. Run `amplify-dev` in a frontend project 

Changes in the packages don't take effect.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

A temporary work around is to change the `"add-cli-no-save"` script in the root's `package.json` to `"yarn add @aws-amplify/cli-internal@10.4.0 -W  && git checkout -- package.json",`. This just seems to be an issue with the new @aws-amplify/cli-internal@10.4.1

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by alharris-at** [comment]
Confirmed that this is due to a patch version of the CLI being released, and should be mitigated when the next mainline release goes out next week. Until then, the mitigation steps provided are sane.
