### ISSUE TITLE
CLI 10.50 amplify mock fails to load

### ISSUE THREAD

**Issue by troylslalom** [aws-amplify/amplify-category-api#1014]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

10.5.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

After installing the latest Amplify CLI 10.5.0, we tried to start up the mock using the "amplify mock" command and got the following:

`
Failed to start API Mocking. Running cleanup tasks.
:octagonal_sign: Failed to start API Mocking.. Reason: Could not get resource ConstructionStageSubContractor

SubContractors: [SubContractor] @manyToMany(relationName: "ConstructionStageSubContractor")
ConstructionStages: [ConstructionStage] @manyToMany(relationName: "ConstructionStageSubContractor"
`

The two entities have a manyToMany relationship that seems to be breaking the mock. This was confirmed on a Mac and a Window box with CLI 10.5.0.

We've reverted back to 10.4.1 for now.

### Expected behavior

The mock should start up with proper relationships specified. This data model has been working consistently in a remote environment for the past several CLI versions now.

### Reproduction steps

1. Create a project with two entities in the Graphql schema that share a many to many relationship.
2. Try to start the mock using  Amplify CLI 10.5.0.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

We reverted back to 10.4.1 which works fine.

**Comment by Choquenizer** [comment]
Hi,

I'm facing a similar issues after upgrading.

Got:
Failed to start API Mocking. Running cleanup tasks.
🛑 Failed to start API Mocking.. Reason: Could not get resource SearchableStack

After removing @searchable annotations I got the same issue as @troylslalom but with @hasOne relationship.

I'm using Ubuntu, btw.

Regards,
--
Matías

**Comment by Choquenizer** [comment]
By the way,... How do you downgrade amplify cli?

**Comment by rajczi** [comment]
@Choquenizer this is how we did it:

```
npm remove -g @aws-amplify/cli
npm i -g @aws-amplify/cli@10.4.1
```

**Comment by rajczi** [comment]
@josefaidt Here are the specific 2 models we are working with.  Both were created some time ago and we have been mocking our api with them all along until the update to 10.5.  Replicated on multiple computers (windows, mac) using several versions of node and going back to 10.4.1 resolved the issue in all cases.  We have submitted the diagnostic report and our app Id is dazoutc7gx3vp.

```
type SubContractor @model @auth(rules: [{ allow: public }]) {
  id: ID! @primaryKey
  name: String
  ConstructionStages: [ConstructionStage] @manyToMany(relationName: "ConstructionStageSubContractor")
  BuildSchedules: [BuildSchedule] @hasMany(indexName: "bySubContractor", fields: ["id"])
  subContractorType: SubContractorType
}

type ConstructionStage @model @auth(rules: [{ allow: public }]) {
  id: ID! @primaryKey
  name: String!
  duration: Int!
  sequence: Int!
  recompute: Boolean!
  Properties: [Property] @hasMany(indexName: "byConstructionStage", fields: ["id"])
  stageType: StageType!
  SubContractors: [SubContractor] @manyToMany(relationName: "ConstructionStageSubContractor")
}
```

**Comment by phani-srikar** [comment]
Hi @rajczi. Thanks for reporting this issue. We cannot get your full schema details from the app ID that you shared. Can you please share the project identifier that gets generated when you run `amplify diagnose --send-report`?
I tried to reproduce the issue using the schema snippet you shared and following the below steps, but did not run into the error you've mentioned.

- Add a GraphQL API with below schema. There are no `@searchable` models yet.
```
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type SubContractor @model @auth(rules: [{ allow: public }]) {
  id: ID! @primaryKey
  name: String
  ConstructionStages: [ConstructionStage] @manyToMany(relationName: "ConstructionStageSubContractor")
  subContractorType: SubContractorType
}

type ConstructionStage @model @auth(rules: [{ allow: public }]) {
  id: ID! @primaryKey
  name: String!
  duration: Int!
  sequence: Int!
  recompute: Boolean!
  stageType: StageType!
  SubContractors: [SubContractor] @manyToMany(relationName: "ConstructionStageSubContractor")
}

enum SubContractorType {
  FULL_TIME
  PART_TIME
}

enum StageType {
  ALPHA
  BETA
  GAMMA
}
```
- Run `amplify mock` and verify that no searchable artifacts are created. Mock process starts successfully.
- Restart the mock process after adding the below `@searchable` models to the schema.
```
type OtherSearchableModel @model @searchable @auth(rules: [{ allow: public }]) {
  id: ID! @primaryKey
  name: String!
}

type OtherSearchableConnectedModel @model @searchable @auth(rules: [{ allow: public }]) {
  id: ID! @primaryKey
  name: String!
  SubContractors: [SubContractor] @hasMany
}
```
- Run `amplify mock` and verify that searchable artifacts are created. Mock process starts successfully.
- Now, in order to reproduce the scenario that @Choquenizer described, I removed both the `@searchable` models from the schema.
- Run `amplify mock` and verify that the Mock process starts successfully.

I however ran into an unrelated issue in setting up the searchable lambda trigger, that this PR aims to fix. It also includes a minor change to how AppSync CFN resource constructs are processed during mocking.
Can you please install the test CLI tag with this fix and see if it resolves your issue? Here are the steps to do so:
- Install the CLI tag version using `npm i -g @aws-amplify/cli@searchable-mocking-test`.
- Verify that the tagged release version is successfully installed using `amplify -v` which should give `10.5.2-searchable-mocking-test.<some number>`.
- From the root of your app, run `amplify api gql-compile` followed by `amplify mock`. Check if the mock process is successfully started.
- You can uninstall the test tag version of CLI and reinstall your previous version.

Can you also please let me know if:
- You have any `@searchable` annotated models in your schema?
- There is a `ConstructionStageSubContractor.json` file in `amplify/backend/api/<api name>/build/stacks` directory before you run `amplify mock`.

**Comment by rajczi** [comment]
For the moment, there are no `@searchable` annotated models in the schema but there will be.

Yes, There is a `ConstructionStageSubContractor.json` in the build/stacks directory.

I updated to 10.5.1, forced a full build and attempted `amplify mock` again to the same error.  I have generated the error report and sent it with the following identifier `55a68b1e5e23dd3cbfa9dc4b85af1b2d`.

```
eh-data % amplify mock
Mock Storage endpoint is running at http://localhost:20005

⚠️  WARNING: your GraphQL API currently allows public create, read, update, and delete access to all models via an API Key. To configure PRODUCTION-READY authorization rules, review: https://docs.amplify.aws/cli/graphql/authorization-rules

✅ GraphQL schema compiled successfully.

Edit your schema at /Users/crajczi/repos/eh/eh-data-monorepo/eh-data/amplify/backend/api/ehdata/schema.graphql or place .graphql files in a directory at /Users/crajczi/repos/eh/eh-data-monorepo/eh-data/amplify/backend/api/ehdata/schema
Failed to start API Mocking. Running cleanup tasks.
🛑 Failed to start API Mocking.. Reason: Could not get resource ConstructionStageSubContractor

Learn more at: https://docs.amplify.aws/cli/graphql/troubleshooting/

Session Identifier: 40674a0d-4aab-4750-836e-ae5359488de3
^C
eh-data % ^Aborted!

eh-data % amplify diagnose --send-report

Learn more at https://docs.amplify.aws/cli/reference/diagnose/

✅ Report saved: /var/folders/wr/dl7wd40s7pdbx2r1bxxpj0_w0000gn/T/ehdata/report-1669649663266.zip

✔ Done

Project Identifier: 55a68b1e5e23dd3cbfa9dc4b85af1b2d
```

**Comment by rajczi** [comment]
@phani-srikar were you able to get the diagnostic report from the above project identifier?

**Comment by phani-srikar** [comment]
Hi @rajczi. I was able to get your schema and was able to reproduce the issue. From @josefaidt 's [comment on this other duplicate issue](https://github.com/aws-amplify/amplify-category-api/issues/1032#issuecomment-1331249524), this looks like a previously known issue. The behavior that I observed which might have caused this issue in the mock plugin is that the nested stack parameters get generated differently when you run `amplify api gql-compile` versus `amplify push`.

**Comment by rajczi** [comment]
We have multiple front ends to our project and run the the local `amplify api gql-compile` in a script before distributing the config/generated files to the other projects.

In our case, we never run `amplify push` as our push commands are run by the build pipeline and then each of the developers runs a push on occasion to stay in sync.

Anything else you need from us or additional tests we can run to help you isolate the resolution?  For now we're running 10.4.1 with some custom sync scripts which has mostly unblocked us.

**Comment by phani-srikar** [comment]
Hi @rajczi , @dwamianm. We have a development binary of Amplify CLI that could solve this issue of circular dependencies. Can you please install it and verify if it addresses your issue? Please remember to uninstall once done, since it's not a production binary. Here are the steps:

- Installing the tagged release:
`npm i -g @aws-amplify/cli@10.5.3-circular-dep-fix.0`

- Verify correct version is installed:
`amplify version` should print "10.5.3-circular-dep-fix.0".

- Now run `amplify mock`

**Comment by dwamianm** [comment]
@phani-srikar . I was **unable** to Mock with `10.5.3-circular-dep-fix.0` with the error `Failed to start API Mocking.. Reason: Unable to start the local OpenSearch Instance.`

**Comment by tmli3b3rm4n** [comment]
v10.6.1, mac m1 silicon.  The patch didn't resolve my issue.  #1014 

```
✅ GraphQL schema compiled successfully.

Edit your schema at /Users/macmac/go/src/github.com/ThatLeague/battlegit/amplify/backend/api/battlegit/schema.graphql or place .graphql files in a directory at /Users/macmac/go/src/github.com/ThatLeague/battlegit/amplify/backend/api/battlegit/schema

Failed to start API Mocking. Running cleanup tasks.
🛑 Failed to start API Mocking.. Reason: Could not get resource Team


Session Identifier: caa04b26-6018-446f-a246-5e2329cd6a29

✅ Report saved: /var/folders/r1/bfypxjrn4c56t1qppzqlgg780000gn/T/battlegit/report-1673390064252.zip

✔ Done

Project Identifier: 333a9cfc635640cfaec2a93c7b0bbe98
```

**Comment by jbreemhaar** [comment]
I don't recall updating Amplify, but this suddenly started happening since yesterday after adding a new @manyToMany connection.

**Comment by dwamianm** [comment]
@phani-srikar v10.6.1, mac m1 silicon. The problem still exists. Downgrading to 10.4.1 fixed the issue. I would love to be able to keep up-to-date for other fixes and security benefits.

**Comment by eettaa** [comment]
+1 I am having related issues.

**Comment by cjsilva-umich** [comment]
Would someone please be able to comment on the status of this?

**Comment by dwamianm** [comment]
@phani-srikar @josefaidt @troylslalom ... can anyone provide a status on this? I have been using amplify for a long time now, and I have never been stuck on a version this long. Any insight into where this is would be greatly appreciated

**Comment by phani-srikar** [comment]
There is a fix that is in-flight for this issue https://github.com/aws-amplify/amplify-cli/pull/11642. Please upvote that PR.

**Comment by cjsilva-umich** [comment]
I'm getting the same behavior after updating the CLI to the latest version. Anyone else? Did I fail to do something else required after updating the cli?

**Comment by rajczi** [comment]
They sent me a amplify cli based on a 10.5 build that was able to mock my schema which I confirmed to them.  However, I just verified that fix hasn't made it into the main code branch as of 10.7.

**Comment by cjsilva-umich** [comment]
> They sent me a amplify cli based on a 10.5 build that was able to mock my schema which I confirmed to them. However, I just verified that fix hasn't made it into the main code branch as of 10.7.

Thanks for the confirmation. Thought I had messed up somehow. Back down to 10.4.1 it is for me!

**Comment by eettaa** [comment]
@cjsilva-umich be warned that amplify hooks do not work in hosting before 10.5--- if your production pipeline relies on hooks + hosting, reverting to 10.4.1 introduces a regression

**Comment by cjsilva-umich** [comment]
@eettaa So currently it's: decide between being able to mock the db/api and having hooks/other new features, right?

**Comment by phani-srikar** [comment]
A fix for this issue is released in Amplify CLI `10.8.x`. Please upgrade and check. Thanks.

**Comment by jbreemhaar** [comment]
> A fix for this issue is released in Amplify CLI `10.8.x`. Please upgrade and check. Thanks.

Can confirm it works for me.  

First run threw a weird `MockProcessFault: Failed to start API Mocking.. Reason: Failed to get AWS credentials` error though, could be a coincidence. Just to be sure I removed the existing mock-data. Since then no more problems, yay 🥳

**Comment by jvaczcorporation** [comment]
Version 12.0.0  still not working

```
Installing dependencies from Pipfile.lock (c9b232)...
Failed to start API Mocking. Running cleanup tasks.
Reason: Unable to start the local OpenSearch Instance.
```

**Comment by jvaczcorporation** [comment]
Alguém pode me dizer se precisa instalar alguma versão específica do python para o mock OpenSearch funcionar? Estou na versão 3.8.16.
