### ISSUE TITLE
Many to many relationship between a table and itself

### ISSUE THREAD

**Issue by leonardocfor** [aws-amplify/amplify-category-api#1026]
### Amplify CLI Version

10.13.1

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

Hi guys, 

Hope you are doing great.

I'm trying to create a many-to-many relationship between a table and itself. Specifically, the idea is that an User can have pair-based relationships with many other Users. Moreover, that relatioship has an status and potentially other fields. This is my current approach:

```
type User 
  @model
  @auth(rules: [{ allow: owner }]) {
  username: String! @primaryKey
  relationships: [Relationship] @hasMany(indexName: "byPersonOne", fields: ["username"])
    @auth(
      rules: [
        { allow: owner }
        { allow: private, operations: [create]}
      ]
    )
}

type Relationship
  @model
  @auth(
    rules: [
      { allow: owner, ownerField: "people"}
    ]
  ){
  id: ID!
  personOneID: String! @index(name: "byPersonOne",sortKeyFields:["personTwoID"])
  personTwoID: String! @index(name: "byPersonTwo",sortKeyFields:["personOneID"])
  personOne: User! @belongsTo(fields: ["personOneID"])
  personTwo: User! @belongsTo(fields: ["personTwoID"])
  people: [String]
  status: String
}
```

I have tried many approaches but there are some issues with the fact the the indexes point to the same table. For example, I can't be sure if this will work: 

` relationships: [Relationship] @hasMany(indexName: "byPersonOne", fields: ["username"])
`

For the user who receives the invitation to become a partner to the first user. Moreover, when I run the command

`amplify status api -acm User`

I'm getting the error: InvalidDirectiveError: username field is not of type ID, which I find odd.

Note: I'm not using the directive `ManyToMany` as this will not allow me to create the `status` field in the Relationship table.

### Expected behavior

I want to find a way to create the many-to-many relationship between User table and itself.

### Reproduction steps

Does not apply

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by alharris-at** [comment]
hi @leonardocfor - thanks for reaching out. Would you mind double checking the Amplify CLI version? at this time we don't have a version as high as `10.13.1`, so that version would help us out.

Could you also check your `amplify/cli.json` file and if there's a feature flag for `respectprimarykeyattributesonconnectionfield` which is set to true? This is a relatively new flag which was added in CLI version 10.4.1, which enables first-class support for custom primary keys, which may be why you're getting some complaints about the `ID` field type.

**Comment by leonardocfor** [comment]
Hi @alharris-at, yes, typo in there, I meant version 10.3.1. The flag respectprimarykeyattributesonconnectionfield does not exist in the amplify/cli.json file. Disregarding the error I'm having, could you provide an approach to create a many-to-many relationship between User table and itself.

**Comment by leonardocfor** [comment]
Hi guys, can you provide assistance with this? As I mentioned, I would like an example on how to create a many-to-many relationship between User table and itself. I appreciate it

**Comment by AnilMaktala** [comment]
Hi @leonardocfor , can you please add the feature flag "respectprimarykeyattributesonconnectionfield" and set the value to true in the cli.json file.
what you please provide us the exact error you are getting with the status field?

can you try updating the Relationship model auth rules like below,
type Relationship
  @model
  @auth(
    rules: [
      { allow: owner, ownerField: "people"},
     { allow: private, operations: [create]}
    ]
  ){

**Comment by leonardocfor** [comment]
Hi @AnilMaktala, thanks for your reply. I perform the changes you suggested adding the line `"respectprimarykeyattributesonconnectionfield": true` in the cli.json file (`features.graphqltransformer`) plus I added the autentication directive` { allow: private, operations: [create]}` to the `Relationship` model. The error I'm getting is the same: `InvalidDirectiveError: username field is not of type ID`
