### ISSUE TITLE
GraphQl @function generated request resolver invalid.

### ISSUE THREAD

**Issue by gbacskai** [aws-amplify/amplify-category-api#1029]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.x

### Amplify CLI Version

10.x

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I have been asked at AWS Premium support to open a ticket her

```
This side Eshwar
again from AWS Premium Support.

Thank you very much for your patience, while I was actively working with the service team and forwarded your use-case along with the manual step that you have kindly provided which mitigates the issue. I have received an update from them and I would like to convey the same to you.

The internal service team has requested you to kindly open a new Github issue here [+] along with description of the issue and also update it with the manual intervention step that you have followed.
```

This issue has not been solved:
https://github.com/aws-amplify/amplify-cli/issues/6419

I use mac I have the same issue as well when I use amplify CD/CI to deploy api I have the same.

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

It has been described here:
https://github.com/aws-amplify/amplify-cli/issues/6419

### Expected behavior

Instead of 

      "typeName": "$ctx.stash.get("typeName")",
      "fieldName": "$ctx.stash.get("fieldName")",

create 

      "typeName": "$ctx.stash.get('typeName')",
      "fieldName": "$ctx.stash.get('fieldName')",

in the @function resolver

### Reproduction steps

create a simple @function in the graphql schema pointed to a function

### GraphQL schema(s)

<details>

```
	getStats(
		id: ID!,
		owner: String,
		type: String,
		timestamp: Int,
		filter: ModelXYZFilterInput
	): Stats @function(name: "FunctionStats-${env}") 


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @gbacskai :wave: thanks for raising this! What version of the CLI are you using? Running a quick test using Amplify CLI 10.5.1 yielded different results in the Invoke* template. Do you have any overridden resolvers in `amplify/backend/api/<api-name>/resolvers/`?

```
## [Start] Invoke AWS Lambda data source: MycoolfunctionLambdaDataSource. **
{
  "version": "2018-05-29",
  "operation": "Invoke",
  "payload": {
      "typeName": $util.toJson($ctx.stash.get("typeName")),
      "fieldName": $util.toJson($ctx.stash.get("fieldName")),
      "arguments": $util.toJson($ctx.arguments),
      "identity": $util.toJson($ctx.identity),
      "source": $util.toJson($ctx.source),
      "request": $util.toJson($ctx.request),
      "prev": $util.toJson($ctx.prev)
  }
}
## [End] Invoke AWS Lambda data source: MycoolfunctionLambdaDataSource. **
```

**Comment by gbacskai** [comment]
Using the latest Amplify client (in the aws amplify pipeline) : 10.5.1

There are a lot of resolvers in the amplify/backend/api/<api-name>/resolvers/ but none of them are apply to the current one what is having the issue.

This is how it looks like:
```
## [Start] Invoke AWS Lambda data source: GeotrackerDeviceStatsLambdaDataSource. **
{
  "version": "2018-05-29",
  "operation": "Invoke",
  "payload": {
      "typeName": "$ctx.stash.get("typeName")",
      "fieldName": "$ctx.stash.get("fieldName")",
      "arguments": $util.toJson($ctx.arguments),
      "identity": $util.toJson($ctx.identity),
      "source": $util.toJson($ctx.source),
      "request": $util.toJson($ctx.request),
      "prev": $util.toJson($ctx.prev)
  }
}
## [End] Invoke AWS Lambda data source: GeotrackerDeviceStatsLambdaDataSource. **
```

**Comment by josefaidt** [comment]
Hey @gbacskai if the resolvers in `api/resolvers` were not intentionally created perhaps they are an artifact of a failed mock shutdown. Can you try deleting these in the directory that are unused and re-attempt the push? `amplify api gql-compile` should also regenerate the resolvers in the `build/` directory which you can verify before pushing

**Comment by gbacskai** [comment]
amplify api gql-compile
GraphQL schema compiled successfully.

It does not change anything.

**Comment by josefaidt** [comment]
Hey @gbacskai apologies for the delay here! Are you still experiencing this? Are you able to override the resolver without the additional quotes as shown [here](https://github.com/aws-amplify/amplify-category-api/issues/1029#issuecomment-1331176097)? Additionally, can you post the contents of your `amplify/cli.json` file?

**Comment by AnilMaktala** [comment]
Hi 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment and provide us with the information our team had previously asked for. This way, we can reopen the issue and provide you with better assistance.

Thank you!
