### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by rezab777** [aws-amplify/amplify-category-api#1036]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

10.4.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

When having a large number of connections and indexes, Amplify seems to be unable to push

![image](https://user-images.githubusercontent.com/82418505/204392318-864dcfd5-dba7-4e1d-9d59-c1b8a86888aa.png)

### Expected behavior

Amplify should be able to update relevant IAM roles.

### Reproduction steps

n/a

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @rezab777 :wave: thanks for raising this! While we begin to look at this, can you describe the type of changes applied prior to receiving this issue? Can you post the project ID output of `amplify diagnose --send-report`?

**Comment by rezab777** [comment]
Thanks for the swift response. This is preventing us from updating our production API.
The issue seems to only arise after I try to add an index to a newly created table.
The only major change to the schema was adding a new model with indexes and connections to other models.
I was able to push the same schema in the staging environment.
Sure it's **Project Identifier: 07c8e35fe317d8408a2ace295f0abb96**

**Comment by josefaidt** [comment]
Hey @rezab777 thanks for clarifying and for sending that project ID over! Would you mind checking the AWS CloudFormation console to see if it has a more specific/helpful error for these roles?

**Comment by rezab777** [comment]
The CloudFormation log is 
```
apiportal (api)
UPDATE_FAILED
```
`Embedded stack arn:aws:cloudformation:us-west-2:XXXXXXXXXXXX:stack/amplify-portal-production-102511-apiportal-1XZFAIKKO20FB/80792bd0-852d-11ec-9a1f-026757c08eb3 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to create: [AuthRolePolicy07AAC61DDD, UnauthRolePolicy077D61CA7A]. The following resource(s) failed to update: [UnauthRolePolicy06454E96FB, AuthRolePolicy03DA271F4C, UnauthRolePolicy0519A4E6AB, AuthRolePolicy0552AC47CD, AuthRolePolicy02A05DD8DC, AuthRolePolicy049E37F651, UnauthRolePolicy03CF5BBA32, UnauthRolePolicy019D4A6CE4, GraphQLAPITransformerSchema3CB2AE18, UnauthRolePolicy02676D2ED4, AuthRolePolicy01921FC820, AuthRolePolicy06CEB1E51C, UnauthRolePolicy0437882B47].`

**Comment by josefaidt** [comment]
Hey @rezab777 apologies, are you able to see any additional details in the CloudFormation console https://us-east-1.console.aws.amazon.com/cloudformation/home? From there in the "events" tab you should see a few errors on the failed updates, which out to the right side of this table will be a message. Keep in mind your Amplify project will contain several nested stacks for various resources, where you will need to identify the nested API stack
