### ISSUE TITLE
How do enable cloudwatch logs for API gateway

### ISSUE THREAD

**Issue by digzapcg** [aws-amplify/amplify-category-api#1051]
### Amplify CLI Version

10.5.1

### Question

What I have tried : 

![image](https://user-images.githubusercontent.com/59307746/204744848-f01a27d9-aca1-403a-8dbc-7826a2d586e4.png)

results in :
![image](https://user-images.githubusercontent.com/59307746/204779296-a1af0b48-8446-4d4a-b5f6-38e9cdd91d94.png)

what am i doing wrong here ? Thank you

**Comment by AnilMaktala** [comment]
Hi @digzapcg, Thank you for raising this. Can you try below script and let me know if it works for you?

export function override(resources: AmplifyApiRestResourceStackTemplate) {
   
    resources.deploymentResource.stageDescription = {
        methodSettings: [{loggingLevel:"INFO"}]
      };

}

**Comment by yanlin96** [comment]
Hi team, 

Test above settings, got an error
![Screen Shot 2022-12-14 at 10 58 12 am](https://user-images.githubusercontent.com/71164436/207472249-d4cc0231-bff6-4500-98a0-0385b9eb46d2.png)

**Comment by AnilMaktala** [comment]
Hi Yanlin 👋 , unfortunately this feature has to be set during the initial deployment.

As a workaround, you can try removing the API first by using the command "Amplify remove api" and amplify add api.

Please make sure you take a backup of current "override.ts" file in the amplify/backend/API/resourcename/ folder.

**Comment by AnilMaktala** [comment]
Hi @digzapcg  👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment. This way, we can reopen the issue and provide you with better assistance.

Thank you!
