### ISSUE TITLE
Unable to get fargate API option

### ISSUE THREAD

**Issue by digzapcg** [aws-amplify/amplify-category-api#1052]
### Amplify CLI Version

10.5.1

### Question

**No option** for fargate API when following this guide https://docs.amplify.aws/cli/usage/containers/#getting-started

![image](https://user-images.githubusercontent.com/59307746/204729586-0c96f810-2a41-4bd6-9933-d9d7806da778.png)

![image](https://user-images.githubusercontent.com/59307746/204729870-db27aee4-3480-4370-b036-0952492e0982.png)

**Comment by josefaidt** [comment]
Hey @digzapcg :wave: thanks for raising this! From the documentation you will need to select one of the available GraphQL/REST API options to select the container deployment for the API.

```
➜  amplify add api
? Select from one of the below mentioned services: REST
? Which service would you like to use 
  API Gateway + Lambda 
❯ API Gateway + AWS Fargate (Container-based) 
```
