### ISSUE TITLE
Opensearch mock not working

### ISSUE THREAD

**Issue by mstoyanovv** [aws-amplify/amplify-category-api#1053]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

10.5.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No changes

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

Searchable mocking was recently added but it seems like it does not work and it cannot start the process. 
When the command _amplify mock api_ is executed it creates a folder _/mock-api-resources/searchable_ with Pipfile inside that is referencing to non existing directory ./src. This therefore breaks the build process.

Even if the missing files are added from this [pr](https://github.com/aws-amplify/amplify-cli/pull/11326/files#diff-e51d2862264c556e2e258467387519f7f931acf9074fd451bee34f85a23243cd) the build passes but it won't start successfully without giving a specific error. 

### Expected behavior

Amplify mock api should work with opensearch 

### Reproduction steps

1.Create sample amplify project with appsync + searchable graphql type
2.Run amplify mock/amplify mock api

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by phani-srikar** [comment]
Hi @mstoyanovv. Thanks for reporting this. We are aware of this and have a PR https://github.com/aws-amplify/amplify-cli/pull/11472 in flight to fix it. Look out for next CLI release when we will also be releasing the documentation to support this feature.

**Comment by mstoyanovv** [comment]
Hey @phani-srikar, I have tried to run the logic with the latest changed in dev which includes the pr you mentioned. 

The result is: "Failed to start API Mocking.. Reason: Unable to start the local OpenSearch Instance." with bunch of retries before that. I was also thinking if this could be related to the macbook M1 chip?

**Comment by phani-srikar** [comment]
Hi @mstoyanovv, I'm curious how you installed the changes in `dev` branch of CLI? Can you please follow the below steps:

1. Install the CLI tag version using npm i -g @aws-amplify/cli@searchable-mocking-test.
2. Verify that the tagged release version is successfully installed using amplify -v which should give 10.5.2-searchable-mocking-test.<some number>.
3. From the root of your app, run amplify api gql-compile followed by amplify mock. Check if the mock process is successfully started.

- If you run into error, can you verify if the opensearch binary is successfully downloaded using `ls ~/.amplify/lib/aws-amplify-amplify-opensearch-simulator/opensearch/1.3.0/`. This folder should be empty when you first install CLI and should be populated with downloaded binary once you run `amplify mock`. 
- If you see the downloaded files, can you just run the binary outside of the mock process using `~/.amplify/lib/aws-amplify-amplify-opensearch-simulator/opensearch/1.3.0/opensearchLib/bin/opensearch` and see if it creates a default cluster on your M1 Mac?
- When you run `amplify mock`, do you see any information like `Spawning OpenSearch Simulator with options: <something>` etc being printed on your console?

5. You can uninstall the test tag version of CLI and reinstall your previous version.

**Comment by mstoyanovv** [comment]
I am running latest changes by forking the cli repo and then building it locally with yarn setup-dev. 

The issue with opensearch not starting was because JAVA_HOME was not correctly set on my machine. In this case opensearch defaults to bundled jdk which is also missing and just stops after that. 

I think If there is a way to catch that in the cli and alert the user that there is something wrong it would help a lot. 

After setting the path correctly I got to see this message "Successfully launched OpenSearch Simulator on{"port":9201,"time":4078}" but then shortly followed by "Failed to start API Mocking.. Reason: Stream Arn must be specified". 

Seems like the issue comes from this part: 
`      const tableStreamArns: {[index: string]: TableDescription;} = await describeTables(this.ddbClient, allTablesWithTriggers);
      const allListeners = [];
      Object.entries(allLambdaTriggers)?.forEach(([tableName, lambdaTriggers]) => {
        if(!(_.isEmpty(lambdaTriggers))) {
          lambdaTriggers.forEach( (lambdaTrigger: LambdaTrigger) => {
            printer.info(`tableStreamArns[tableName].LatestStreamArn, ${JSON.stringify(tableStreamArns[tableName])}`);
            allListeners.push(
              ddbLambdaTriggerHandler(
                context, 
                tableStreamArns[tableName].LatestStreamArn, 
                lambdaTrigger, 
                this.ddbEmulator.url
              )
            );
          });
        }
      });`

where describeTable is not returning streamArn for tables with @searchable. 

I am still debugging it further..

**Comment by phani-srikar** [comment]
Hi @mstoyanovv, Thanks for the feedback. I've added an additional check for `JAVA_HOME` before starting up the opensearch simulator that prints useful warning message. [PR Link](https://github.com/aws-amplify/amplify-cli/pull/11528).
About the error you're facing about the `streamARN`:

- The DynamoDB tables that are provisioned for searchable models have the following property set: `"StreamSpecification": { "StreamViewType": "NEW_AND_OLD_IMAGES" }`, if you look at the `amplify/build/api/<apiName>/stacks/<ModelName>.json` contents. Can you check if that's true?

- The low level function that creates the tables is found [here](https://github.com/aws-amplify/amplify-cli/blob/1ee69a4dba4adb1264ddec513ba9888c1296d7b4/packages/amplify-util-mock/src/utils/dynamo-db/utils.ts#L6) in case you want to examine the table properties and check for `StreamSpecification` property being set.

**Comment by mstoyanovv** [comment]
Thanks for that @phani-srikar. 
The tables that were being created were without stream enabled but after deleting the "mock-data" folder in my project and runing "amplify mock api" the issue was fixed. Maybe there was a corrupted file interfering with the process. I am going to close this ticket now. 

Thanks for the support and fast response!

**Comment by qndrey** [comment]
> * If you run into error, can you verify if the opensearch binary is successfully downloaded using `ls ~/.amplify/lib/aws-amplify-amplify-opensearch-simulator/opensearch/1.3.0/`. This folder should be empty when you first install CLI and should be populated with downloaded binary once you run `amplify mock`.

after amplify mock the folder is still empty
