### ISSUE TITLE
Error processing @hasMany directive

### ISSUE THREAD

**Issue by cbirkenstock** [aws-amplify/amplify-category-api#1065]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2jt69v2lj0akj

### Region

us-east-1

### What operating system are you using?

Mac

### Browser type?

Google Chrome

### Describe the bug

receiving this error: 

Error processing @hasMany directive on User.chats, @index directive with name chatUserByUser was not found in connected model ChatUser. 

However, chatUserByUser is actually in the ChatUser Table. 

### Expected behavior

Expected that DataStore will see that ChatUser does contain chatUserByUser index

### Reproduction steps

Here are my two tables that are causing this problem: 

```graphql
type ChatUser @model @auth(rules: [{ allow: public }]) {
  id: ID!
  userID: ID! @index(name: "chatUserByUser")
  chatID: ID! @index(name: "customByChat")
  user: User! @belongsTo(fields: ["userID"])
  chat: Chat! @belongsTo(fields: ["chatID"])
  notificationsEnabled: Boolean!
  nickname: String
  hasUnreadMessage: Boolean
  unreadMessagesCount: Int
  isAdmin: Boolean
  writtenMessages: [Message] @hasMany(indexName: "byChatUser", fields: ["id"])
  messages: [Message] @manyToMany(relationName: "ChatUserMessage")
}

type User @model @auth(rules: [{ allow: public }]) {
  id: ID!
  name: String
  email: String
  profileImageUrl: String
  notificationToken: String
  venmoHandle: String
  badgeCount: String
  chats: [ChatUser] @hasMany(indexName: "chatUserByUser", fields: ["id"])
}
```

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
