### ISSUE TITLE
Unstable @hasone functionality

### ISSUE THREAD

**Issue by harukaxq** [aws-amplify/amplify-category-api#1084]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v16.10.0

### Amplify CLI Version

10.5.2

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

The following Schema is set up for Amplify.

```

type Review
  @model(subscriptions: null)
  @auth(
    rules: [
      {
        allow: owner
        ownerField: "userId"
        operations: [read, update, delete, create]
      }
      { allow: public, operations: [read] }
    ]
  ) {
  id: ID!
  userId: ID
  user: PublicUser @hasOne(fields: ["userId"])
  campSiteId: ID!
  campSite: CampSite @hasOne(fields: ["campSiteId"])
}
type PublicUser
  @model(subscriptions: null)
  @auth(
    rules: [
      { allow: public, operations: [read] }
    ]
  ) {
  id: ID!
  displayName: String
  fullId: ID! @primaryKey
  updatedAt: AWSDateTime!
  createdAt: AWSDateTime!
}
type CampSite
  @model(mutations: { create: null, delete: null })
  @auth(
    rules: [
      { allow: public, operations: [read] }
    ]
  ) {
  id: ID!
  name: String!
}

```

I would expect the @hasone directive to return a PublicUser matching by userId set to user, but it seems to work erratically.
The following query from Queries in AppSync was executed with API_KEY.

```

query MyQuery {
  listReviews(limit: 10) {
    items {
      userId
      user {
        id
        key
      }
      campSite {
        id
      }
    }
  }
}


```

This response has been returned

```

{
  "data": {
    "listReviews": {
      "items": [
        {
          "userId": "15535375-157c-4e57-ab38-ebd260085f39",
          "user": null,
          "campSite": {
            "id": "A010099"
          }
        },
        {
          "userId": "15535375-157c-4e57-ab38-ebd260085f39",
          "user": null,
          "campSite": {
            "id": "A010099"
          }
        },
        {
          "userId": "google_---",
          "user": {
            "id": "d8d58d10-adad-43af-8a84-0641a4d058b7",
            "key": "d8d58d10-adad-43af-8a84-0641a4d058b7"
          },
          "campSite": {
            "id": "A010103"
          }
        },
        {
          "userId": "15535375-157c-4e57-ab38-ebd260085f39",
          "user": {
            "id": "15535375-157c-4e57-ab38-ebd260085f39",
            "key": "15535375-157c-4e57-ab38-ebd260085f39"
          },
          "campSite": {
            "id": "A010099"
          }
        },
        {
          "userId": "15535375-157c-4e57-ab38-ebd260085f39",
          "user": {
            "id": "15535375-157c-4e57-ab38-ebd260085f39",
            "key": "15535375-157c-4e57-ab38-ebd260085f39"
          },
          "campSite": {
            "id": "A010099"
          }
        },
        {
          "userId": "2e08635d-b713-433b-a8c2-3e82fc591015",
          "user": null,
          "campSite": {
            "id": "A010103"
          }
        },
        {
          "userId": "15535375-157c-4e57-ab38-ebd260085f39",
          "user": {
            "id": "15535375-157c-4e57-ab38-ebd260085f39",
            "key": "15535375-157c-4e57-ab38-ebd260085f39"
          },
          "campSite": {
            "id": "A010099"
          }
        },
        {
          "userId": "2e08635d-b713-433b-a8c2-3e82fc591015",
          "user": {
            "id": "2e08635d-b713-433b-a8c2-3e82fc591015",
            "key": "2e08635d-b713-433b-a8c2-3e82fc591015"
          },
          "campSite": {
            "id": "A010103"
          }
        },
        {
          "userId": "2e08635d-b713-433b-a8c2-3e82fc591015",
          "user": {
            "id": "2e08635d-b713-433b-a8c2-3e82fc591015",
            "key": "2e08635d-b713-433b-a8c2-3e82fc591015"
          },
          "campSite": {
            "id": "A010103"
          }
        },
        {
          "userId": "15535375-157c-4e57-ab38-ebd260085f39",
          "user": {
            "id": "15535375-157c-4e57-ab38-ebd260085f39",
            "key": "15535375-157c-4e57-ab38-ebd260085f39"
          },
          "campSite": {
            "id": "A010099"
          }
        }
      ]
    }
  }
}

```

Looking at the response, some items are successfully retrieved while others are not, even though the user has the same ID.

Strangely enough, it works fine in CampSite.
However, in User, it is sometimes possible to get it and sometimes not.
Is this due to the owner provider setting?

### Expected behavior

The @hasone directive works correctly.

### Reproduction steps

1. amplify init and add auth , add api
2. set schema 
3. push
4. Reproduced from appsync and client

### Project Identifier

Project Identifier: 1d5a354d265724cd448c8f0ad94c2a90

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hey @harukaxq ,Thank you for raising the issue. Can you please let us know-how are you creating the user? are you getting this issue for only one user "15535375-157c-4e57-ab38-ebd260085f39"?

**Comment by AnilMaktala** [comment]
Hey @harukaxq, Are you still experiencing this issue?

**Comment by harukaxq** [comment]
Sorry for the delay.
This is occurring for all users, not just this user.

**Comment by AnilMaktala** [comment]
Hey @harukaxq, Sorry for the delay. Look like current project identifier report is expired. Could you please re-send us the new identifer by running the amplify diagnose command?

**Comment by AnilMaktala** [comment]
Hi @harukaxq 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment and provide us with the information our team had previously asked for. This way, we can reopen the issue and provide you with better assistance.

Thank you!
