### ISSUE TITLE
@searchable directive fails to create SearchableStack in cloudformation

### ISSUE THREAD

**Issue by littlefeatheradmin** [aws-amplify/amplify-category-api#1092]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16

### Amplify CLI Version

10.5.2

### What operating system are you using?

wsl

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Yes. Created a GSI on the table which the @searchable directive is applied on.

### Describe the bug

Adding the directive @searchable on a table results in Amplify CLI failing with the error "_SearchableStack                AWS::CloudFormation::Stac_" and "_Resource is not in the state stackUpdateComplete_". The error message/status for SearchableStack in Cloudformation is "_The following resource(s) failed to create: [OpenSearchDomain]._". 

### Expected behavior

ElasticSearch to be created for the table

### Reproduction steps

1. Add @searchable directive to a table
2. amplify push -y

### Project Identifier

ID: b2353618301d205d8907e350f0837d6f

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi  @littlefeatheradmin 👋, we are working on reproducing the issue. Could you please run below command and send us the report amplify diagnose --send-report

**Comment by littlefeatheradmin** [comment]
@AnilMaktala Thank you, very glad to hear that! I have now run the command you mentioned. The report "report-1671105597431" was generated. Will that be enough for you to identify the report? Let me know if you want us to try anything else.

**Comment by AnilMaktala** [comment]
@littlefeatheradmin, Thank you. can you please add the Project identifier to the ticket?

**Comment by littlefeatheradmin** [comment]
@AnilMaktala Done!

**Comment by littlefeatheradmin** [comment]
@AnilMaktala any news on this?

**Comment by littlefeatheradmin** [comment]
@AnilMaktala @josefaidt  Do you have an estimated timeframe for a fix on this or a suggestion for a work around?

**Comment by josefaidt** [comment]
Hey @littlefeatheradmin :wave: apologies for the delay here! If you visit the AWS CloudFormation Console, navigate to your project's root stack, and use the "stack actions" dropdown to "detect drift" do you see any drift items pertaining to the manually-created GSI? If so we will want to revert this drift/GSI creation and use the `@index` directive in your `schema.graphql` to create the GSI

**Comment by littlefeatheradmin** [comment]
@josefaidt No worries, I know you guys have a lot on your plate. I have already removed the previous project I had and re-deployed again creating a new project with the intention of removing/minimizing manual configuration. The issue with @searchable still persists. I've even tried creating an Amplify project from scratch and I get the same issue. Could there be a problem connected to the region (eu-north-1)?

**Comment by littlefeatheradmin** [comment]
@josefaidt @AnilMaktala Any thoughts?

**Comment by AnilMaktala** [comment]
Hi 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment. This way, we can reopen the issue and provide you with better assistance.

Thank you!
