### ISSUE TITLE
Amplify RDS-Auora-Usage 

### ISSUE THREAD

**Issue by wintunmmocc** [aws-amplify/amplify-category-api#1094]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

Does the amplify support with Auora-Postgres compatible engine natively? 

### AWS Region

ap-northeast-1

### Amplify Hosting feature

Backend builds

### Question

Does the amplify support with Auora-Postgres compatible engine natively? I'm looking for some documentation about using Auora serverless on amplify.But,the documentation I found the link https://docs.amplify.aws/cli-legacy/graphql-transformer/relational/ is totally out-of-date. Anyone can support updated documentation?

**Comment by josefaidt** [comment]
Hey @wintunmmocc :wave: thanks for raising this! The linked documentation points to legacy docs for GraphQL API's (i.e. using GraphQL Transformer v1 with `@key`, `@connection`, etc.), however there is an active RFC for RDS with GraphQL API's using GraphQL Transformer v2 https://github.com/aws-amplify/amplify-category-api/issues/815

**Comment by josefaidt** [comment]
Closing in favor of the RFC
