### ISSUE TITLE
Unable to use @auth directive with @hasMany relationship

### ISSUE THREAD

**Issue by BrianHHough** [aws-amplify/amplify-category-api#1115]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.16.0

### Amplify CLI Version

10.2.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

Hi AWS Amplify API GitHub community,

I am trying to access a specific pattern with GraphQL where there are `Items` as the "parent" data type which have public read enabled (everyone can see the data of all the Items)...but then there can be a child owner-only one-to-many relationship to `Items` called `SubItems` with a @hasMany array appended as a  "child" or "children" to that parent type `Item`.

For reference, I am using the AWS Amplify framework to work with AppSync, but all the normal rules should still apply.

What I want to be able to do is the following — there are `Items`, and `Items` have a one-to-many relationship with `SubItems`. But only the person who created the `SubItem` could see this. Also, if I were to `listItemsByTimestamp` such as in a feed...the `SubItems` wouldn't be accessible in something like this type of feed:

[Item #1: "hi there 1st Item"] — anyone can see this
[Item #2: "testing this again"] — anyone can see this
     [SubItem #1] — ONLY seeable from DynamoDB or the creator
     [SubItem #2] — ONLY seeable from DynamoDB or the creator
     [SubItem #3] — ONLY seeable from DynamoDB or the creator
[Item #3: "yup, I'm a 3rd Item"] — anyone can see this

In graphql, is this pattern valid below where the `type Item` has public-read data EXCEPT for the references to the SubItems which would only be viewable by the owner who created them? I tried to mess around with the @auth directives for types but then it makes the public read error by having fields that are trying to be rendered but can't because of the directives: [https://docs.amplify.aws/cli/graphql/authorization-rules/#signed-in-user-data-access ](https://docs.amplify.aws/cli/graphql/authorization-rules/#signed-in-user-data-access) 

This is why I want to see if I can securely do it this way? Although, my concern is that the children would inherit the parent auth roles by default even if the children have owner-only read/create.

```graphql
#PARENT ITEM
type Item 
    @model
    @auth(rules: [
        { allow: owner, ownerField: "owner", provider: userPools, operations: [create, read, update, delete] }
        { allow: private, provider: userPools, operations: [read] }
        { allow: public, operations: [read] }
    ])
{
    id: ID!
    text: String!
    type: String! 
        @index(
            name: "SortItemsByTimestamp"
            queryField: "listItemsSortedByTimestamp"
            sortKeyFields: ["timestamp"] # sort items by time overall
        )
    timestamp: Int!
    owner: String!
    subitems: [SubItem]
        @hasMany(indexName: "SubItemsOfItem", fields: ["owner"])
        @auth(rules: [{ allow: owner }])
}


type SubItem 
    @model
    @auth(rules: [
        { allow: owner, ownerField: "owner", provider: userPools, operations: [create, read] }
    ])
{
    id: ID!
    text: String!
    timestamp: ID!
    owner: String!
    type: String! 
        @index(
            name: "SortSubItemsByTimestamp"
            queryField: "listSubItemsSortedByTimestamp"
            sortKeyFields: ["timestamp"] # sort subitems by time overall
        )
    timestamp: Int!

    item: String
        @index(
            name: "SubItemsOfItem",
            queryField: "listSubItemsOfItem",
            sortKeyFields: ["timestamp"]
    }
    itemPointer: Item @belongsTo(fields: ["item"])
```

### Expected behavior

I want to be able to run the `listItemsByTimestamp` graphql query and have it list all of the items, but not with the "UNAUTHORIZED" errors where it says `Not Authorized to access subitems on type ModelItemConnection`.

It's because the SubItem has owner-only read/create....so I want to be able to connect it to the Item parent....but this in graphql generates queries that include SubItems by default...which causes my list query to error out and not load the data without rendering errors in my react app.

### Reproduction steps

1. Create the GraphQL schema as shown above
2. Push to amplify/appsync
3. Use the amplify SDK in react to run a list query for the parent element and then try to list them in react.js

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by marcvberg** [comment]
Hi @BrianHHough,

The problem you're running into is that when you use field level authorization, it will override model level authorization. So when the `subitems` field is using owner auth, it only uses the owner of the `Item` to determine access, while the authorization information from `SubItem` is not used.

From the sound of it you only want to return the `SubItem`s that a user has access to, but you're not trying to block access to the field any differently than the rest of the model. So in that case you want to remove the field level authorization

**Comment by AnilMaktala** [comment]
Hi @BrianHHough 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment. This way, we can reopen the issue and provide you with better assistance.

Thank you!
