### ISSUE TITLE
ResolverExecutionLimitReached error when call api

### ISSUE THREAD

**Issue by GitHubPhongNguyen** [aws-amplify/amplify-category-api#1118]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.17.1

### Amplify CLI Version

10.5.1

### What operating system are you using?

Mac, Windows, Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Call graphQL use appSync

### Describe the bug

my table have a lot of data. i used list Items with appSync have an error when i have limit > 4999 or limit bigger

### Expected behavior

I want list items.

### Reproduction steps

1. my schema
```
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @hasMany
}

type Post @model {
  id: ID!
  title: String!
  blog: Blog @belongsTo
  comments: [Comment] @hasMany
}

type Comment @model {
  id: ID!
  post: Post @belongsTo
  content: String!
}
```
2. call graphQL with limit default query from ./graphql/queries and used limit 5000
```
useEffect(() => {
    fetchPosts();
  }, []);

  async function fetchPosts() {
    try {
      const postData = await API.graphql(
        graphqlOperation(listPosts, {
          limit: 5000,
        })
      );
      const posts = postData.data.listPosts.items;
      setPosts(posts);
    } catch (err) {
      console.log("error fetching posts");
    }
  }
```
_note: i have 10000 item in table post_

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hey @GitHubPhongNguyen 👋 , are you able to replicate this issue consistently? can you try changing the limit to 1000 records and see if you still get this error?

**Comment by GitHubPhongNguyen** [comment]
> Hey @GitHubPhongNguyen 👋 , are you able to replicate this issue consistently? can you try changing the limit to 1000 records and see if you still get this error?

this error just happened when limit large

**Comment by AnilMaktala** [comment]
Hey @GitHubPhongNguyen 👋 , Please refer the current limitation limits [here](https://docs.aws.amazon.com/general/latest/gr/appsync.html#limits_appsync). we will recommend getting  1k records at once to work through this limitation.

**Comment by GitHubPhongNguyen** [comment]
> Please refer the current limitation limits [here](https://docs.aws.amazon.com/general/latest/gr/appsync.html#limits_appsync). we will recommend getting 1k records at once to work through this limitation.

Can you elaborate more on the problem I'm having? i was read Service quotas but i don't know what my detail problem. I used limit smaller for working but i want to know more detail

**Comment by GitHubPhongNguyen** [comment]
I can't explain it to my clients, they don't accept such generic answers

**Comment by chrisbonifacio** [comment]
Hi @GitHubPhongNguyen 👋 apologies for the delay here. Just wanted to follow up and offer a more detailed explanation.

The limits relevant to this issue are the "Iterations in a foreach loop in mapping templates" which is limited to 1,000. This means that the VTL resolvers cannot iterate more than 1,000 times and this can easily occur when nested relationship data is included in graphql queries on large datasets. As mentioned before, this is typically mitigated by pagination and lowering the number of records returned on each call.

Keep in mind, there also limits to DynamoDB Scans of 1MB max response size. When DynamoDB hits that limit, a token is provided to fetch the next set of data.

For more info on DynamoDB limits, please visit: 
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ServiceQuotas.html#default-limits-throughput-capacity-modes:~:text=to%2020%20subnets.-,API%2Dspecific%20limits,-CreateTable/UpdateTable
