### ISSUE TITLE
Not understanding how to modify the join table created through the '@manyToMany'

### ISSUE THREAD

**Issue by YonathanTE** [aws-amplify/amplify-category-api#1122]
### Amplify CLI Version

10.5.2

### Question

# Current syntax implemented
### Issue lies specifically with the many-to-many relationship between the user & order. From this, the join table is created and I have been unable to modify the table with additional attributes as well as global secondary indexes. 
- Already attempted to change the 'OrderUsers.json' file and it did not work.
- Is there any way for me to bring the table into syntax on the schema.graphql file or modify it with additional attributes that can have their own GSI?

```
type Club @model {
 id: ID!
 name: String!
 orders: [Order] @hasMany(indexName: "byClub", fields: ["id"]) # Unsure of whether this will be needed **
}

type Product @model {
  id: ID!
  name: String!
  orders: [Order] @hasMany(indexName: "byProductOrder", fields: ["id"])
  inventories: [Inventory] @hasMany(fields: ["id"])
 }

type User @model {
  id: ID! 
  fName: String!
  lName: String!
  phoneNumber: String!
  email: String!
  DOB: String!
  orders: [Order] @manyToMany(relationName: "OrderUsers")
  ordersByDate: [Order] @hasMany(indexName: "byOrderByDate", fields: ["id"])
  ordersByStatusDate: [Order] @hasMany(indexName: "byOrderStatusByDate", fields: ["id"])
}

type Order @model {
  id: ID!
  userId: ID! @index(name: "byOrderStatusByDate", sortKeyFields: ["status", "date"]) @index(name: "byOrderByDate", sortKeyFields: ["date"])
  status: String!
  amount: Int
  date: String!
  users: [User] @manyToMany(relationName: "OrderUsers")  # Test to see if I can tinker w/ the 'OrderUsers' tbl
  productId: ID! @index(name: "byProductOrder", sortKeyFields: ["id"])
  clubId: ID! @index(name: "byClub", sortKeyFields: ["id"])
}

type Inventory @model {
    productId: ID! @primaryKey(sortKeyFields: ["clubId"]) # Uses the 'clubId' because this is the PK 
    clubId: ID! @index(name: "byClubId", queryField: "itemsByClubId")
    inventoryAmount: Int!
  }
```

Thank you in advance,

Yonathan

**Comment by mkumail1** [comment]
I want to add a few more attributes to the many-to-many join table such as `status`. Can someone help me with how can I do that since I don't see any answer to this question yet.

**Comment by mkumail1** [comment]
Hey @YonathanTE, I spotted a similar issue concerning to this might help you fix it. [manyToMany autogenerated table with extra fields](https://github.com/aws-amplify/amplify-category-api/issues/698#issuecomment-1217202492).

Please note that in creating indexes for the join table add index names respectively. As I landed on schema validation issue when index names weren't added likeso: 
`userID: ID! @index(name: 'byUser', sortKeyFields:["organizationID"])`

**Comment by AnilMaktala** [comment]
Hi @YonathanTE 👋, Please refer to the comment provided in the ticket [here](https://github.com/aws-amplify/amplify-category-api/issues/698#issuecomment-1217202492). We are closing this ticket, please feel free to add a comment if you need any other information to reopen the ticket.

**Comment by juri-diener** [comment]
> Hey @YonathanTE, I spotted a similar issue concerning to this might help you fix it. [manyToMany autogenerated table with extra fields](https://github.com/aws-amplify/amplify-category-api/issues/698#issuecomment-1217202492).
> 
> Please note that in creating indexes for the join table add index names respectively. As I landed on schema validation issue when index names weren't added likeso: `userID: ID! @index(name: 'byUser', sortKeyFields:["organizationID"])`

How you solved it? I get this error: Index byUser does not exist for model UserOrganization
