### ISSUE TITLE
alternate primaryKey generating invalid client code

### ISSUE THREAD

**Issue by rajczi** [aws-amplify/amplify-category-api#1125]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

Confirmed in `10.4.2`, `10.5.2` and `10.5.3-circular-dep-fix.0`

### What operating system are you using?

Mac OS (confirmed on intel and apple silicon)

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None

### Describe the bug

When generating a model that has an alternate primary key

```
type UserProfile @model @auth(rules: [{ allow: owner }]) {
  userProfileId: ID! @primaryKey
  owner: String
  settings: AWSJSON
}
```
The generated code files still contain the `id` field instead of the expected `CustomIdentifier`

WRONG codegen:
```
type EagerUserProfile = {
  readonly id: string;
  readonly userProfileId: string;
  readonly owner?: string | null;
  readonly settings?: string | null;
  readonly createdAt?: string | null;
  readonly updatedAt?: string | null;
}

type LazyUserProfile = {
  readonly id: string;
  readonly userProfileId: string;
  readonly owner?: string | null;
  readonly settings?: string | null;
  readonly createdAt?: string | null;
  readonly updatedAt?: string | null;
}

export declare type UserProfile = LazyLoading extends LazyLoadingDisabled ? EagerUserProfile : LazyUserProfile

export declare const UserProfile: (new (init: ModelInit<UserProfile, UserProfileMetaData>) => UserProfile) & {
  copyOf(source: UserProfile, mutator: (draft: MutableModel<UserProfile, UserProfileMetaData>) => MutableModel<UserProfile, UserProfileMetaData> | void): UserProfile;
}
```

### Expected behavior

The code should be generated without an `id` field and use the `CustomIdentifier` instead

**RIGHT** codegen
```
type EagerUserProfile = {
  readonly [__modelMeta__]: {
    identifier: CustomIdentifier<UserProfile, 'userProfileId'>;
    readOnlyFields: 'createdAt' | 'updatedAt';
  };
  readonly userProfileId: string;
  readonly owner?: string | null;
  readonly settings?: string | null;
  readonly createdAt?: string | null;
  readonly updatedAt?: string | null;
}

type LazyUserProfile = {
  readonly [__modelMeta__]: {
    identifier: CustomIdentifier<UserProfile, 'userProfileId'>;
    readOnlyFields: 'createdAt' | 'updatedAt';
  };
  readonly userProfileId: string;
  readonly owner?: string | null;
  readonly settings?: string | null;
  readonly createdAt?: string | null;
  readonly updatedAt?: string | null;
}

export declare type UserProfile = LazyLoading extends LazyLoadingDisabled ? EagerUserProfile : LazyUserProfile

export declare const UserProfile: (new (init: ModelInit<UserProfile>) => UserProfile) & {
  copyOf(source: UserProfile, mutator: (draft: MutableModel<UserProfile>) => MutableModel<UserProfile> | void): UserProfile;
}
```

### Reproduction steps

I was able to work-around the issue by starting a new amplify project, putting the schema file in it and running the codegen using 

`amplify api gql-compile && amplify codegen && amplify codegen models`

However, when I run the same command (or a push) using the main project folder, I get the old models which don't run.  We have repeated this behavior on multiple machines and versions of amplify.  I have blown away the entire stack by environment for the backend and redeployed to the same problem.

### Project Identifier

55a68b1e5e23dd3cbfa9dc4b85af1b2d

### Log output

<details>

```
# Put your logs below this line



```

</details>

### Additional information

I have included the full set of logs from today.  The project that is generating correctly (new amplify project, add api, paste in schema, run codegen) is called `id-test`.  The existing project we've been working from for months which isn't working is `eh-data`.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by rajczi** [comment]
I just attempted to start with a branch new folder and pull the backend using

`amplify pull --appId <my-app-id> --envName dev`

The code that comes down has the invalid codegen in it.

**Comment by AnilMaktala** [comment]
Hi @rajczi 👋, Thank you for raising this issue. We found that "respectprimarykeyattributesonconnectionfield" field is set to false in cli.json file. can you please re-try after setting it to true and let us know?
<img width="525" alt="Screen Shot 2023-01-06 at 10 36 47 AM" src="https://user-images.githubusercontent.com/3206171/211046000-718d40df-aebd-425a-89e7-29786eb3b6aa.png">

**Comment by rajczi** [comment]
that seems to clear my issue and now the codegen matches between projects.  It still reverts the changes when I pull it into another project front end (that isn't editing the backend) but I can copy the codegen files from the master project for now.
