### ISSUE TITLE
Custom query/mutation with VTL resolver

### ISSUE THREAD

**Issue by nikname** [aws-amplify/amplify-category-api#113]
It is not clear to me what I have to do to create custom query/mutation and use VTL resolver. Consider the following schema

```
type Post @model {
  title: String
}
```

I want to add the following custom mutations (please note that this is a very simple example)

```
type Mutations {
  promotePost(): Post
}
```

After manually add Mutation.promotePost.req.vtl and Mutation.promotePost.res.vtl inside resolvers directory (not build/resolvers directory) if I try to invoke the mutation I get the following error

> resolve is not a function

I am using transformation v2. Looking at the [documentation](https://docs.amplify.aws/cli/graphql/custom-business-logic/#vtl-resolver) I understand that I have to create a custom VTL resolver for each custom query/mutation but for me this is an expensive operation (that I have to repeat for each custom query/mutation I want).

Is this the only way? Am I missing something? Thanks in advice

**Comment by josefaidt** [comment]
Hey @nikname :wave: apologies for the delay here! We now recommend creating custom resolvers from a custom CDK resource, which circumvents the issue you are seeing with the [VMError](https://github.com/aws-amplify/amplify-cli/issues/10066), https://docs.amplify.aws/cli/graphql/custom-business-logic/#vtl-resolver

If you are still experiencing this issue please reply back to this thread or create a new issue and we can investigate further 🙂
