### ISSUE TITLE
Issues in migrating from graphql transformer v1 to v2

### ISSUE THREAD

**Issue by jstocks-trelly** [aws-amplify/amplify-category-api#1140]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v16.19.0

### Amplify CLI Version

10.5.2

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made.

### Describe the bug

I am attempting to migrate from graphql transformer v1 to v2. `amplify migrate api` compiles successfully and I get the following warnings / notes.
```
The following project state(s) were detected which may need additional attention to ensure they continue to work as expected with the new GraphQL transformer
- You have defined custom Queries, Mutations, and/or Subscriptions in your GraphQL schema
- You have overridden an Amplify generated resolver
- You are using the following directives which are not handled by the transformer:
	aws_iam, aws_cognito_user_pools, searchable
- You do not have the "improvePluralization" Feature Flag enabled
```
Then I do `amplify push` and i get `Object type extension 'Query' cannot redeclare field searchProperties`.

### Expected behavior

The expected behavior would be for the graphql transformer to compile to the v2 code style and amplify push successfully.

### Reproduction steps

I put my steps in the "Describe the bug" section.

### Project Identifier

Project Identifier: 374cd2014176d0ef9272fcc7dd1fdc84

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

Thank you for your help. And please let me know if there is any other information that would be helpful to troubleshoot.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by chrisbonifacio** [comment]
Hi @jstocks-trelly 👋 thanks for raising this issue. Can you please share your schema before the migration?

**Comment by jstocks-trelly** [comment]
[schema.graphql.txt](https://github.com/aws-amplify/amplify-category-api/files/10484478/schema.graphql.txt)

Here is a txt version of my 'schema.graphql'.

**Comment by jstocks-trelly** [comment]
I started a ticket with AWS Support  - my case ID is 11755866031. I shared my schema, cli.json, and custom resolvers there.

**Comment by alharris-at** [comment]
In that case I'd suggest we use the internal case to track resolution. Closing this issue.
