### ISSUE TITLE
Amplify push failed with GraphQLSchema schema update and Resource is not in the state stackUpdateComplete.

### ISSUE THREAD

**Issue by rahulnainwal107** [aws-amplify/amplify-category-api#1141]
### Amplify CLI Version

8.5.0

### Question

I am trying to update our existing schema with some new fields but ended up with The following resource(s) failed to update: [GraphQLSchema] and Resource is not in the state stackUpdateComplete error.

I am using cloudformation to update existing backend. This is the process which I followed -
1 - Pull existing amplify backend using - amplify pull --appId ************ --envName testapp
2- Make changes for adding new fields in one of our models.
3- amplify api gql-compile
4- amplify push

I am using SSO user and aws_access_key_id, aws_secret_access_key and aws_session_token.

Every time I tried, It failed and status of cloudformation stack change in to UPDATE_ROLLBACK_FAILED state. In order to make subsequent push we needed to perform continuous roll back which breaks our environment and we are not able to use it.

<img width="1034" alt="Screenshot 2022-12-26 at 12 26 38 PM" src="https://user-images.githubusercontent.com/36499090/209520712-e894a238-5e84-4293-beb7-0232f08ecaec.png">

**Comment by rahulnainwal107** [comment]
Is there any update on this?

**Comment by AnilMaktala** [comment]
Hey @rahulnainwal107, Apologies for the delay.we are working on reproducing the issue. Could you please run below command and send us the project identifier.
```
amplify diagnose --send-report. please refer [here](https://docs.amplify.aws/cli/reference/diagnose/)
```

**Comment by AnilMaktala** [comment]
Hi 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment and provide us with the information our team had previously asked for. This way, we can reopen the issue and provide you with better assistance.

Thank you!
