### ISSUE TITLE
amplify add codegen failed with Downloading schema failed / Internal server error.

### ISSUE THREAD

**Issue by rahulnainwal107** [aws-amplify/amplify-category-api#1142]
### Amplify CLI Version

10.5.2

### Question

When we are trying to add amplify codegen (Using this command `amplify add codegen --apiId **************`) in a amplify project that we pulled using this command `amplify pull --appId ************** --envName testapp` it is getting failed with this error.

<img width="768" alt="Screenshot 2023-01-06 at 2 33 38 PM" src="https://user-images.githubusercontent.com/36499090/210968599-9ce3f34c-78cc-4c2b-8fac-105524a0c9dd.png">

**Comment by josefaidt** [comment]
Hey @rahulnainwal107 :wave: thanks for raising this! As we begin to look at this in more depth I wanted to clarify something. Is the API added with `amplify add codegen --apiId xxx` the same API that is attached to the Amplify project with `amplify pull`

**Comment by rahulnainwal107** [comment]
Hi @josefaidt, thanks for response. I am not clear with your question but if you are talking about apiId then yes we are using  different appId. For `amplify pull --appId ************** --envName testapp` we used amplify appId but for `amplify add codegen --apiId **************` appsync appId.

**Comment by AnilMaktala** [comment]
Hi @rahulnainwal107 👋, Apologies for the delay. Could you please execute this command 'amplify add codegen --appId xxx --debug' and share us the logs?

**Comment by AnilMaktala** [comment]
Hi @rahulnainwal107  👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment and provide us with the information our team had previously asked for. This way, we can reopen the issue and provide you with better assistance.

Thank you!
