### ISSUE TITLE
10.6 api gql-compile reports error in schema comments when it finds any of the ')]}' characters

### ISSUE THREAD

**Issue by vgribok** [aws-amplify/amplify-category-api#1143]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.3.0

### Amplify CLI Version

10.6

### What operating system are you using?

MacOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

After upgrading CLI from 10.5.x to 10.6 most `amplify` started complaining on my API graphql schema, reporting errors like "Syntax Error: mismatched brackets found in the schema. Unexpected ]". Other characters it didn't like were ) and }. All of these places were in commented out parts of the schema and had no problem before 10.6.

### Expected behavior

Ignore ),],} chars in comments as pre 10.6 cli did.

### Reproduction steps

1. Use amplify 10.6.
2. Add a comment to the api .graphql file and put one of the ),],} chars to the comment.
3. Run `amplify api gql-compile`, see errors.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ggcespia** [comment]
This happens as of yesterday on cli@10.2.3 as well, so it must be a component that is called.
 # Executing command: npm i -g @aws-amplify/cli@10.2.3
2023-01-07T01:57:56.983Z [INFO]: 🛑 Syntax Error: mismatched brackets found in the schema. Unexpected ] at line 7 in the schema.

schema shows this in comments (you'll see square brackets on line 7):

# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
#input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

# "group" groupsField is an attribute in cognito? like (email, etc.?)
#type Projects @model @auth(rules: [
#   {allow: groups, groups: ["Admins"] },
#   {allow: groups, groups: ["Readers"], operations: [read]}
#  ]) 
#  {
#  id: ID!
#  title: String
#}

**Comment by AnilMaktala** [comment]
Hi @vgribok @ggcespia, Thank you for reporting the issue. We can reproduce this issue and marked this as a bug for the team to evaluate further.

<img width="490" alt="image" src="https://user-images.githubusercontent.com/3206171/211335078-831e9c2d-40d0-44b3-8a84-0cf94d0e0cdd.png">

**Comment by alharris-at** [comment]
We have a draft PR that should be able to address this, but will require additional testing and refactoring before we can accept it. https://github.com/aws-amplify/amplify-category-api/pull/1138

**Comment by alharris-at** [comment]
This bracket check has been removed in Amplify CLI v10.6.2, and upgrading to the latest version should resolve the issue you're running into. Thank you.
