### ISSUE TITLE
Amplify migrate api not working

### ISSUE THREAD

**Issue by ldaudet** [aws-amplify/amplify-category-api#1145]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.12.1

### Amplify CLI Version

10.6.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None

### Describe the bug

When I run amplify migrate api, I get the message "You are using the deprecated parameterization of @connection which cannot be automatically migrated."

I then go into the schema, and update all the @connection directive, and replace them by the appropriate @hasOne, @hasMany...

When I then run amplify upgrade api, I now get the message: 'Your GraphQL Schema is using "@belongsTo", "@hasMany", "@hasOne", "@index" directives from the newer version of the GraphQL Transformer. Visit https://docs.amplify.aws/cli/migration/transformer-migration/ to learn how to migrate your GraphQL schema.'

So I then updated amplify/cli.json to read:

{
  "features": {
    "graphQLTransformer": {
      "addMissingOwnerFields": false,
      "validateTypeNameReservedWords": true,
      "useExperimentalPipelinedTransformer": true,
      "enableIterativeGSIUpdates": true,
      "secondaryKeyAsGSI": true,
      "transformerVersion": 2,
      "skipOverrideMutationInputTypes": true,
      "suppressSchemaMigrationPrompt": true
    }, [...]

But when I then run amplify upgrade api, I get the same message: 'Your GraphQL Schema is using "@belongsTo", "@hasMany", "@hasOne", "@index" directives from the newer version of the GraphQL Transformer. Visit https://docs.amplify.aws/cli/migration/transformer-migration/ to learn how to migrate your GraphQL schema.'

I get the same message when I try to run amplify push.

### Expected behavior

After updating the graphql schema to not have any @connection directive, amplify upgrade api should work rather than telling me that I have directive tied to the new V2 version

### Reproduction steps

1. run amplify migrate api
2. have amplify tell you that you need to replace the @connection directive with their new counterpart
1. update your schema file to not contain any @connection directive, and instead the requested replacement (@hasOne, @hasMany, ...)
3. run amplify migrate api again
4. have amplify say that you can't use these new directive since you are using V2 directives

### Log output

<details>

```
# Put your logs below this line
BEFORE REMOVING @connection:

ldaudet@pc:~/janus_envs/v2update$ amplify migrate api
⚠️ Your instance type for OpenSearch is t2.small.elasticsearch, you may experience performance issues or data loss. Consider reconfiguring with the instructions here https://docs.amplify.aws/cli-legacy/graphql-transformer/searchable/
GraphQL schema compiled successfully.

Edit your schema at /home/ldaudet/janus_envs/v2update/amplify/backend/api/gen2/schema.graphql or place .graphql files in a directory at /home/ldaudet/janus_envs/v2update/amplify/backend/api/gen2/schema
You are using the deprecated parameterization of @connection which cannot be automatically migrated.

AFTER REMOVING @connection and replacing them with the new directives @hasOne, @hasMany, ...


ldaudet@pc:~/janus_envs/v2update$ amplify migrate api
⚠️ Your instance type for OpenSearch is t2.small.elasticsearch, you may experience performance issues or data loss. Consider reconfiguring with the instructions here https://docs.amplify.aws/cli-legacy/graphql-transformer/searchable/
🛑 Your GraphQL Schema is using "@belongsTo", "@hasMany", "@hasOne", "@index" directives from the newer version of the GraphQL Transformer. Visit https://docs.amplify.aws/cli/migration/transformer-migration/ to learn how to migrate your GraphQL schema.

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi  @ldaudet 👋, thanks for raising this issue.we are working on reproducing the issue. Could you please run below command and send us the report amplify diagnose --send-report. please refer [here](https://docs.amplify.aws/cli/reference/diagnose/)

**Comment by ldaudet** [comment]
Hi @AnilMaktala , thanks for getting back to me. Which command do you want me to run before sending you the report? If you mean 'amplify migrate api', do you want me to run it before I update the schema to V2 directive, when amplify then tells me I need to remove @connection for example, or after I update the schema, when amplify then tell me that I can't use V2 directives

**Comment by AnilMaktala** [comment]
Hey @ldaudet, amplify diagnose --send-report command is sufficient for now.

**Comment by ldaudet** [comment]
Hi @AnilMaktala , just ran the command. Let me know if there is anything I can do.

**Comment by AnilMaktala** [comment]
Hey @ldaudet, Please add the generated Project identifier to the ticket. Please refer the instructions [here](https://docs.amplify.aws/cli/reference/diagnose/)

**Comment by ldaudet** [comment]
Hi @AnilMaktala, unlike what is being shown in the doc you shared, the command does not print out a project identifier. Here is the full output of the command when I ran it:

![image](https://user-images.githubusercontent.com/12766547/216688956-60a28ac2-4501-4065-a33b-1bc1eb68449a.png)

**Comment by AnilMaktala** [comment]
Hi @ldaudet, Are you executing the command from the root directory of the project?

**Comment by ldaudet** [comment]
@AnilMaktala yes I am

**Comment by josefaidt** [comment]
Hey @ldaudet :wave: were you able to migrate all instances of `@connection` and similar v1 directives in your schema manually? If you have done so and have also updated the feature flags (as posted in your original post), you will not need to run the migration tool. Are you able to push after the manual migration?

**Comment by ldaudet** [comment]
Hi @josefaidt . I am not able to push after doing the manual migration. I get the same error that I get when doing amplify api upgrade:  'Your GraphQL Schema is using "@belongsTo", "@hasmany", "@hasone", "https://github.com/Index" directives from the newer version of the GraphQL Transformer. Visit https://docs.amplify.aws/cli/migration/transformer-migration/ to learn how to migrate your GraphQL schema.'

**Comment by ldaudet** [comment]
My guess is that once I have updated all the schema to be V2 compliant, I then needs to have amplify understand that I am now using the V2 transformer. Right now, it still thinks I am using the V1, and thus won't be allowing me to run any amplify operations. I am not sure what the procedure is to manually update the transformer version so that amplify understands that it now needs to use the V2 to compile the schema.

**Comment by ldaudet** [comment]
Also, I attempted to let amplify know of the upgrade to V2 by setting the cli.json in the amplify folder the following values:

  "features": {
    "graphqltransformer": {
      ...
      "useexperimentalpipelinedtransformer": true,
      "transformerversion": 2,
      ...
    },

**Comment by josefaidt** [comment]
Hey @ldaudet those are the correct feature flags to change. Do you have a `cli-inputs.json` file in your API's directory? With contents like the following:

```json
{
  "version": 1,
  "serviceConfiguration": {
    "apiName": "a11942",
    "serviceName": "AppSync",
    "defaultAuthType": {
      "mode": "API_KEY",
      "expirationTime": 7
    }
  }
}
```

**Comment by ldaudet** [comment]
Hi @josefaidt , I have a cli-inputs.json in the folder of my REST API, but no in the graphql API. Is there a command to run to create this file for the graphql API, or should I create it manually?

**Comment by josefaidt** [comment]
Hey @ldaudet since you have migrated the schema manually and have updated the corresponding feature flags I think it's easiest to create this manually, but we can help! In general it should follow the structure above, but do you have any other auth mechanisms applied like Cognito User Pools for owner auth?

**Comment by ldaudet** [comment]
Hi, thanks @josefaidt , the missing file was indeed the issue. I was able to recreate it, and that allowed the upgrade to go through. Unfortunately, the push itself was a failure because of the GSI. With the upgrade, all of them more or less have been changed, so a push would mean more than one GSI operation per table. I found a flag that allows for incremental GSI push and set it to true. This brought issue with the limit of files being opened, but after raising the limit, the app was able to create a push with 13 steps to deploy all the changes. Unfortunately, during step 4/13, the push stopped entirely. After over an hour with no updates, I had to terminate the process. This left the dev backend I was attempting the push in a completely unstable state, and after 3 days of working on nothing but this, I still haven't find a way to get the push to go through, on this backend or a new one I created since then. Finally, all these attempts to deploy means that I am apparently hitting some rate limit of some kind, as I get 'InternalFailureException: Oops, something went wrong. Please try again later.', with no clear explanation as to what the root cause is, that block progress until the next day...

**Comment by ldaudet** [comment]
Do you know of any way I can check on the actual progress of an iterative deployment? I can see nothing happening on cloudformation, and the deployment state file has been stuck like this for over an hour:

`{
  "version": "1",
  "startedAt": "2023-02-21T14:21:04.738Z",
  "status": "DEPLOYING",
  "currentStepIndex": 2,
  "steps": [
    {
      "status": "DEPLOYED",
      "previousMetaKey": "amplify-appsync-files/73816dc2b29d89f655e0f22ab0394aac2a9fe9ff/states/initial-stack/deployment-meta.json"
    },
    {
      "status": "DEPLOYED",
      "previousMetaKey": "amplify-appsync-files/73816dc2b29d89f655e0f22ab0394aac2a9fe9ff/states/01/deployment-meta.json"
    },
    {
      "status": "DEPLOYING",
      "previousMetaKey": "amplify-appsync-files/73816dc2b29d89f655e0f22ab0394aac2a9fe9ff/states/02/deployment-meta.json"
    },
    {
      "status": "WAITING_FOR_DEPLOYMENT"
    },
    {
      "status": "WAITING_FOR_DEPLOYMENT"
    },
    {
      "status": "WAITING_FOR_DEPLOYMENT"
    },
    {
      "status": "WAITING_FOR_DEPLOYMENT"
    },
    {
      "status": "WAITING_FOR_DEPLOYMENT"
    },
    {
      "status": "WAITING_FOR_DEPLOYMENT"
    },
    {
      "status": "WAITING_FOR_DEPLOYMENT"
    },
    {
      "status": "WAITING_FOR_DEPLOYMENT"
    },
    {
      "status": "WAITING_FOR_DEPLOYMENT"
    },
    {
      "status": "WAITING_FOR_DEPLOYMENT"
    }
  ]
}`

**Comment by ldaudet** [comment]
My concern is that the deployment hits a rate limit a stalls silently. I am trying to find a way to check whether or not that is the case, or what other issue might be happening that causes the deployment to stall.

**Comment by josefaidt** [comment]
Hey @ldaudet glad to hear you were able to create the file and pass that speedbump, but sorry to hear of the rough experience past that! For what it's worth, CLI logs are captured in `~/.amplify/logs`, which should log a RateException if you were experiencing a rate limit exception. Can you try deleting the leftover `deployment-state.json` file and re-attempt the push?

**Comment by ldaudet** [comment]
Hi @josefaidt , thanks for letting me know, I didn't know logs file were available there. Unfortunately, no luck on the rate limit exception, here is the log for the error I had yesterday:

`2023-02-21T01:36:42.281Z|info : amplify init core  
2023-02-21T01:36:42.301Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-02-21T01:36:51.695Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["profile"])
2023-02-21T01:36:51.696Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2023-02-21T01:36:51.696Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["profile"])
2023-02-21T01:36:51.702Z|info : amplify-provider-awscloudformation.amplify-service-permission-check.checkAmplifyServiceIAMPermission.amplifyClient.listApps([])
2023-02-21T01:36:52.370Z|info : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.listApps([{"maxResults":25}])
2023-02-21T01:36:52.509Z|info : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.getBackendEnvironment([{"appId":"[***]8lk7qq","environmentName":"[***]test"}])
2023-02-21T01:36:52.725Z|error : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.getBackendEnvironment([{"appId":"[***]8lk7qq","environmentName":"[***]test"}])
NotFoundException: BackendEnvironment lasttest does not exist.
2023-02-21T01:36:52.725Z|info : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.getBackendEnvironment([{"appId":"[***]8lk7qq","environmentName":"[***]test","stackName":"[***]ify-[***]us-[***]test-[***]651","deploymentArtifacts":"amplify-janus-lasttest-203651-deployment"}])
2023-02-21T01:36:54.142Z|error : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.getBackendEnvironment([{"appId":"[***]8lk7qq","environmentName":"[***]test","stackName":"[***]ify-[***]us-[***]test-[***]651","deploymentArtifacts":"amplify-janus-lasttest-203651-deployment"}])
InternalFailureException: Oops, something went wrong. Please try again later.`

I am not sure what was going on, and assumed it was a rate issue because then this morning, I just got on the same cli, pressed up and enter to run the same command and got the deployment of the initial state of the app (pre-V2 resolver upgrade), to go through.

As far as trying the V2 upgrade to deploy, I removed the deployment-state.json file and re attempted the push, but got the error:

`DeploymentError: ["Index: 0 State: {\"deploy\":\"waitingForDeployment\"} Message: Resource is not in the state stackUpdateComplete"]
`
I then tried running amplify `api push --iterative-rollback`, and got the error:

`DeploymentError: ["Index: 0 State: {\"deploy\":\"waitingForDeployment\"} Message: Resource is not in the state stackUpdateComplete"]
`
This is the same thing that happened on our dev environment, where we are gonna have to scrap it because it has been left in an unstable state where push are now failing. When checking on CloudFormation, I see that the graphql api deployment crashed because a lot of the tables went from status `UPDATE_IN_PROGRESS` to status `UPDATE_FAILED` with the reason being, in the case of the Education table for example:

`Embedded stack arn:aws:cloudformation:us-east-1:441488514709:stack/amplify-janus-lasttest-64029-apigen2-SVFMODO692ZH-Education-1H55F4SIRPKV3/8a74f780-b1e2-11ed-9327-0ab450570d63 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [EducationTable]. `

**Comment by ldaudet** [comment]
For other tables, the error might be involving the resolver as well, such as the Application table:

`Embedded stack arn:aws:cloudformation:us-east-1:441488514709:stack/amplify-janus-lasttest-64029-apigen2-SVFMODO692ZH-Application-IHG6RCSWIUJ3/8ab97a90-b1e2-11ed-b4a2-0ee6615464f1 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [CreateApplicationResolver, GetApplicationResolver, ApplicationTable]. `

No matter what though, the error on the tables themselves is always the same:

`Resource handler returned message: "Cannot perform more than one GSI creation or deletion in a single update" (RequestToken: be2ae932-20bc-7ff9-6f41-fc36319e967c, HandlerErrorCode: InvalidRequest)`

I just don't understand why this error is being thrown. I assumed that maybe the table had had some modifications done from the initial attempt to push, and amplify not being aware of it somehow is sending updates that conflict with the ones that have already been applied. But when I check the tables for drift, none is detected. I am at a complete loss as to what could amplify be doing to cause that error to trigger when doing an incremental update specifically to prevent it from happening. At this point though, as far as I can tell, the backend is in a locked state where all push will fail.

**Comment by ldaudet** [comment]
Going further down, I compared the current template for the Education table as defined on CloudFormation, and compared it with the template on the S3 from .../states/initial-stack/stacks/Education.json. On the current template, the AttributeDefinition for the GSI looks like this:

`        "AttributeDefinitions": [
          {
            "AttributeName": "id",
            "AttributeType": "S"
          },
          {
            "AttributeName": "memberEducationId",
            "AttributeType": "S"
          },
          {
            "AttributeName": "menteeEducationId",
            "AttributeType": "S"
          },
          {
            "AttributeName": "mentorEducationId",
            "AttributeType": "S"
          }
        ],`

While on the S3, the template for the initial step looks like this:

`                "AttributeDefinitions": [
                    {
                        "AttributeName": "id",
                        "AttributeType": "S"
                    },
                    {
                        "AttributeName": "educationSchoolId",
                        "AttributeType": "S"
                    },
                    {
                        "AttributeName": "educationMentorId",
                        "AttributeType": "S"
                    },
                    {
                        "AttributeName": "educationMenteeId",
                        "AttributeType": "S"
                    },
                    {
                        "AttributeName": "memberEducationId",
                        "AttributeType": "S"
                    },
                    {
                        "AttributeName": "menteeEducationId",
                        "AttributeType": "S"
                    },
                    {
                        "AttributeName": "mentorEducationId",
                        "AttributeType": "S"
                    }
                ],`

So indeed, amplify is trying to add three new attributes at once, though I have no idea as to why, let alone how to resolve the issue. Any help would be greatly appreciated.

**Comment by ldaudet** [comment]
Any ideas as to what might be the root cause of the issue described above where the first template of the 13 steps update has 3 different GSI at once? We have been working on upgrading our backend to V2 for almost two months now. We went from an update script that is unusable as it doesn't work with basic V1 keywords such as @connect, and then because amplify didn't generate a key file for our graphql api. Finally we are now able to compile our schema to V2, and we are unable to push it as amplify cannot generate a multistep push that do not attempt more than on GSI change at a time. This is causing massive issues with our dev cycle, throwing us massively behind in our schedule.

**Comment by ldaudet** [comment]
@josefaidt @AnilMaktala  @alharris-at, please see three comments above. The amplify issues are completely destroying our schedule, and we are in dire need of help to get the issue resolved. We have been fighting bugs for the past two months, and still haven't been able to update and push a V2 version of our backend.

**Comment by AnilMaktala** [comment]
Hi @ldaudet, Could you please check if "respectprimarykeyattributesonconnectionfield" is set to true or false in cli.json file. 

Please set it to false and re-try the migration and let us know. 

<img width="529" alt="image" src="https://user-images.githubusercontent.com/3206171/221962356-1e620590-f028-41b9-b6f1-1d16ebd76451.png">

**Comment by ldaudet** [comment]
Hi @AnilMaktala , I didn't have that key set in my cli.json, but checking into it, it seems to be false by default. I did add it just in case, and then run the amplify api push command. The command went ahead and failed like the previous ones, and for the same reason: "Cannot perform more than one GSI creation or deletion in a single update" 

I am going to recap the issue here, in the hope that it might help you find a solution:

1) I update the schema of my application manually to be using version 2 of the graphql transformer (as the amplify update script didn't work)
2) I set the cli.json file to have enableIterativeGSIUpdates set to true
3) I ran amplify api push
4) this command created 13 different step for the push, and uploaded the files to the deployment bucket for the app
5) the push went through the initial step, step 1, step 2, step 3, and then stopped. No errors, no crashes, just nothing happening for over an hour, both on the command line window where amplify api push was running, and checking the deployment-state.json file on the S3
6) I stopped the amplify api push command
7) I ran amplify api push command again and got an error that a push was already in progress
8) I stopped working for the day, to let some time for whatever process to finish
9) tried amplify api push again the next day, and got the same error. I then realized that was because of the deployment-state.json file on S3
10) I deleted the deployment-state.json file on S3 and tried amplify api push again. It crashed because "Cannot perform more than one GSI creation or deletion in a single update" 
11) after a lot of searching, I figured that the issue is that the initial push did went through for the first 4 steps. Now the problem is that the amplify pull command does not actually pull the state of the backend but instead pull the #current-cloud-backend.zip file from the deployment bucket. BUT that file only gets updated at the end of a push, not after each step. So now, I have a backend that is SEEN by amplify as being in its original, V1 state, a backend that is ACTUALLY 4 steps into a V2 migration, and now way to connect the two...

So, from there, I am not sure where to go. As I see it, there are two possible ways to fix this, neither of which I know how to get done:

Solution 1: I somehow revert the backend to its original state and attempt the push again. There are two problems with that solution. First, I don't know how to revert the backend to its original state as amplify push --iterative-rollback didn't work. Second, if the iterative push stalled on the fourth step last time, I am not sure why it would work any differently this time.

Solution 2: I have amplify push the ACTUAL state of the backend, from the actual resources in cloud formation, so it knows what the state of the backend truly is, so that I can try amplify api push again, but skipping the first 4 states that have already been deployed. 

If I can provide any other details on the issue, please don't hesitate to ask. Thank you for your help.

**Comment by AnilMaktala** [comment]
Hi @ldaudet, I'm sorry to hear that the recommendation we provided did not solve the issue. Would it be possible for you to share the schema or the diagnose report.zip file with me through the [community Discord server](https://discord.gg/invite/amplify)?
