### ISSUE TITLE
Getting new Elastic Search Domain error in CI complaining about an even number of "Availability Zone" but I've changed nothing

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-category-api#1146]
### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

10.4.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Nope

### Describe the bug

My build has started failing when I deploy to the CI with the following error:

``` UPDATE_FAILED      OpenSearchDomain                                                                                      AWS::Elasticsearch::Domain          Sun Jan 08 2023 19:24:48 GMT+0000 (Coordinated Universal Time) You must choose an even number of data nodes for a two Availability Zone deployment (Service: AWSElasticsearch; Status Code: 400; Error Code: ValidationException; Request ID: 6245992c-af82-40b4-b5e2-3444fbd00b21; Proxy: null)```

I've not changed anything that I can see yet its complaining about ElasticSearch.

Found this issues which seems to be the same error https://github.com/hashicorp/terraform-provider-aws/issues/22059

Doing some searching I've found in my ```\amplify\backend\api\franchisemanager\build\cloudformation-template.json``` file I found that it says it should be expecting to only use 1 instance, not sure if I can/should change this to 2? Do I even need 2???

<img width="527" alt="image" src="https://user-images.githubusercontent.com/1674590/211216628-7346e165-5168-47b5-8f5f-3cc50d24220f.png">

Not sure what I've done but currently can't deploy. Any pointers?

### Expected behavior

I hate this bit..."that it doesn't break when I haven't changed anything?"

### Reproduction steps

Erm...again. Not really sure, happy to share anything. I'm hoping its an error that has cropped before or caused by a recent change or something. I've not changed anything that I can see in my commit history so unknown as to what it is.

### Project Identifier

Ahh this failed again, never have any luck with these...

<img width="671" alt="image" src="https://user-images.githubusercontent.com/1674590/211216743-637d1e30-f2c4-4169-82ae-48cfa1e6fd38.png">

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hey @PeteDuncanson, Were there any manual changes made in the AWS console where perhaps an availability zone was added? Would you be able to provide the screenshot of domain config section?

**Comment by PeteDuncanson** [comment]
None that I'm aware off. Didn't even know about availability zones until this error (so some good came out of it!)

**Comment by alharris-at** [comment]
@PeteDuncanson - taking a look, the only thing that looks like it should have triggered this would be if ZoneAwarenessEnabled or the ZoneAwarenessConfig were configured, but looking at the code it appears we explicitly don't do that today: https://github.com/aws-amplify/amplify-category-api/blame/4a1c36091cff6162b4803651b72ed03c594c01dc/packages/amplify-graphql-searchable-transformer/src/cdk/create-searchable-domain.ts#L27-L29

Could you confirm in your `/amplify/backend/api/build/stacks/SearchableStack.json` (or similar) file if `ZoneAwarenessEnabled` is set to true or if that `ZoneAwarenessConfig` is set?

**Comment by PeteDuncanson** [comment]
@alharris-at no mention of either of those keys in that file.

If it helps this is an old project in Amplify timelines, about 2+ years old so might be we had a left over from a version long since dead?

**Comment by PeteDuncanson** [comment]
Annoyingly just had this appear again tonight.

**Comment by PeteDuncanson** [comment]
I've done an `amplify env checkout prod` to ensure I've got the right team-provider-info file, seems it didn't have the `OpenSearchInstanceCount` I mentioned above. I added that in and still it fails.

Only thing I have noticed is that the instance type I have set is no longer on the ideal list of types, I'm using a `t2.medium.elasticsearch` one but that is not ideal from what I've read on here https://docs.aws.amazon.com/opensearch-service/latest/developerguide/supported-instance-types.html

Tempted to change it but then I fear I'd have to get it to reindex again and got enough on my plate with getting this release up.

How is it that a release CI setup can rot this much in 2 months (been that long since our last release)?

I'm currently blocked from releasing and unsure how to unstick myself.

**Comment by AnilMaktala** [comment]
Hey @PeteDuncanson,  We apologize for the inconvenience you are experiencing. To assist you further, could you please provide the following information:

1. The current instance type and version of your PROD Opensearch instance.
2. Please run the following command and send us the report and project identifier.
    `amplify diagnose --send-report`

     This will help us investigate the issue more effectively.

**Comment by PeteDuncanson** [comment]
So in the OpenSearch UI its actually showing up as a "t3.medium.search", prod has 2 nodes too which I hadn't noticed before. this differs from what is in the config. Doesn't the config out trump what is up in the cloud?

I've now adjusted the config to match the names that are showing in the UI and will have another go at pushing that up monday night GMT (earliest time we can release).

I've emailed over download links to the zips you requested.

**Comment by AnilMaktala** [comment]
Thank you for providing us with the additional information and sending us the requested folders. We will thoroughly investigate the issue and keep you informed of our findings.

**Comment by PeteDuncanson** [comment]
Well tried again tonight with the updated team-provider-info.json file and hit that same error. Any pointers of what to try or where to check/look? totally blocked from releasing currently.

**Comment by PeteDuncanson** [comment]
It worked!

So seemingly just not using the feature it was complaining about was enough. As usual no idea how it got into this state or how to get out of it "offically" rather than just "trying stuff out" but here we are.
