### ISSUE TITLE
Custom resolvers fail to build in one environment and not the other after update

### ISSUE THREAD

**Issue by adcanis** [aws-amplify/amplify-category-api#1147]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

19.0.1

### Amplify CLI Version

10.6.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

After re-deploying as per aws-amplify/amplify-cli#11714, Dev environment builds and deploys without issue, but QA throws error for custom resolvers: 

```
🛑 The following resources failed to deploy:
🛑 Resource is not in the state stackUpdateComplete
```

### Expected behavior

deploy without issue

### Reproduction steps

1. amplify upgrade
2. amplify push -y 

### Project Identifier

d5de26ddbcf48705a4962c21df0d58a2

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hey @adcanis, can you please provide the detail error logs from the local terminal? or from the cloudformation console?

**Comment by adcanis** [comment]
ive since fixed this issue. cheers
