### ISSUE TITLE
Conflict detection for one object (for one DynamoDB table)

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-category-api#1148]
### Is this feature request related to a new or existing Amplify category?

api

### Describe the feature you'd like to request

Hi,
Is it possible to set Conflict Detection just for one object (for one DynamoDB table) ?
Because currently it is ON / OFF for the whole schema.

### Describe the solution you'd like

Custom configuration.

### Describe alternatives you've considered

Manual DynamoDB configuration modification.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by rudyhadoux** [comment]
I just realized that we can set a _version member to a GraphQL object and use this to query or update with _version equality checking.

**Comment by AnilMaktala** [comment]
Hey @rudyhadoux, we recommend using the Datastore API for updates and can you please let us know your exact use case so that we can recommend you the better approach? 
Also, please call the Get operation before the update operation.

**Comment by rudyhadoux** [comment]
GraphQL API suits me. But the conflict detection is ON / OFF for all objects. Why all objects ?

**Comment by AnilMaktala** [comment]
Hi @rudyhadoux, We offer the capability to sync one model through selective sync feature. Could you please refer to the selective sync [feature](https://docs.amplify.aws/lib/datastore/sync/q/platform/js/#selectively-syncing-a-subset-of-your-data
) and let us know if it works for your scenario.

**Comment by rudyhadoux** [comment]
Yes but with DataStore. I have to continue with GraphQL API.
Why is this feature not available for GraphQL API ?

**Comment by phani-srikar** [comment]
Hi @rudyhadoux, we currently only provide out-of-the-box conflict detection and resolution for all the `@model` objects in the schema which is meant to be used together with Amplify DataStore.
