### ISSUE TITLE
API GraphQL queries & mutations suddenly started resulting in Unauthorized responses

### ISSUE THREAD

**Issue by Arnav7501** [aws-amplify/amplify-category-api#1150]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v16.17.0

### Amplify CLI Version

10.5.2

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

My code used to work perfectly fine, until it just stopped working without me making any changes. when i try to make a mutation, delete a post, create a post, or do anything, I get the error:
GraphQLError: Request failed with status code 401 and thats it. Additionally, i made some instances of a model that show up in the app but somehow don't show up in the server.

### Expected behavior

i expected amplify to execute the problems.

### Reproduction steps

I'm not sure how you can replicate it, I can't do anything involving amplify anymore.

### Project Identifier

 Identifier: 8741d2665676fac5a5554da0cf079d3b

### Log output

<details>

```
# Put your logs below this line

zsh: no such file or directory: issue-date
```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @Arnav7501 :wave: thanks for raising this! As we begin to look at this in more depth I had a few follow-up questions in order to better understand the context:

- is this 401 unauthorized error coming from calling GraphQL within your app? or from within a Lambda function?
- how are you authenticating to your GraphQL API? IAM, API key, Cognito, etc.
- if the above is API Key, did the API key expire by chance?

**Comment by Arnav7501** [comment]
Thanks a lot for the quick response,

The exact error i get is from calling GraphQl from within my app:
Possible Unhandled Promise Rejection (id: 1):
Object {
  "data": Object {},
  "errors": Array [
    [GraphQLError: Request failed with status code 401],
  ],
}

I believe i'm authenticating using Cognito

**Comment by chrisbonifacio** [comment]
@Arnav7501 can you share your schema and code snippets of how you're trying to query/mutate data? It's unusual to start getting 401 codes for all operations unless the requests are not being authorized correctly, possibly an expired API Key if the requests are being made with a public auth mode. Your user may be authenticated but you could be making the request with the wrong authMode based on your API resource's configuration of default and additional auth modes.

**Comment by Arnav7501** [comment]
Hello, I ended up creating a new environment with the same models and it ultimately just ended up working, i'm still not sure what the issue was in the previous environment. Sorry to waste your time

**Comment by chrisbonifacio** [comment]
@Arnav7501 no worries! If it happens again, try looking into the things we mentioned. Thanks for following up 🙏
