### ISSUE TITLE
Enhanced implementation of amplify push with EnableIterativeGSIUpdates set to true

### ISSUE THREAD

**Issue by RoyBS** [aws-amplify/amplify-category-api#1171]
### Describe the feature you'd like to request

In case of amplify push with EnableIterativeGSIUpdates set to true, with multiple changes to the graphql schema, the deployment process can take more then an hour. The session of the amplify push process is limited to an hour so the process may timeout.

### Describe the solution you'd like

Create a new session for every automatic iteration of the deployment to prevent a timeout while indexing all iteration in one session

### Describe alternatives you've considered

None

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by AnilMaktala** [comment]
Hey @RoyBS,Thank you for raising this. are you experiencing this timeout on CLI side or on Hosting? if it is on CLI, you can increase the timeout limit in AWS IAM console.

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/3206171/214930845-53e4737e-949b-40dd-8035-bb6b6c5d145f.png">

**Comment by RoyBS** [comment]
Hi, thanks for your reply.
I'm experiencing it in the cli, I use assume role with a role that is
suppose to have a session of 4 hours, but the timeout is always an hour. Or
am I doing something wrong?

**Comment by AnilMaktala** [comment]
Hi @RoyBS, Thank you for confirming. Current default session duration limit is 3600 seconds as documented [here](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html)

_duration_seconds - The duration, in seconds, of the role session. The value can range from 900 seconds (15 minutes) up to the maximum session duration setting for the role. This is an optional parameter and by default, the value is set to 3600 seconds._

you can increase the limit in your aws profile as shown below,

``` javascript
# In ~/.aws/config
[profile crossaccount]
role_arn=arn:aws:iam:...
source_profile=development
duration_seconds=3600 -- increase the session duration here
```
