### ISSUE TITLE
Applying @auth directive for auto-generated @manyToMany model

### ISSUE THREAD

**Issue by safal07** [aws-amplify/amplify-category-api#1189]
### Amplify CLI Version

10.6.1

### Question

I have two models with `@auth(rules: [{ allow: private }]` authorization. When I create a manyToMany relationship, a new model is auto-generated. The new model is missing @auth directive. 

```
type User @model @auth(rules: [{ allow: private }]) {
	id: ID!
	email: String
	roles: [Role] @manyToMany(relationName: "UserRole")
}

type Role @model @auth(rules: [{allow: private}]) {
	id: ID!
	name: String
        users: [User] @manyToMany(relationName: "UserRole")
}
```

Is it possible to pass auth rule to the pivot model? Something like   `users: [User] @manyToMany(relationName: "UserRole", rules: [{allow: private}])`

**Comment by AnilMaktala** [comment]
Hey @safal07 :wave, Thank you for raising the question. i tried using below schema and could see the authentication for PostTags in the generated resolvers. Please let us know if you need any further clarification.

```
type Post @model @auth(rules: [{ allow: private, provider: iam }]){
  id: ID!
  title: String!
  content: String
  tags: [Tag] @manyToMany(relationName: "PostTags")
}

type Tag @model @auth(rules: [{ allow: private, provider: iam }]){
  id: ID!
  label: String!
  posts: [Post] @manyToMany(relationName: "PostTags")
}
```
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/3206171/217916260-0b47ba2c-3069-4152-bbd2-259331d47df5.png">

**Comment by AnilMaktala** [comment]
Hi @safal07 👋 ,Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
