### ISSUE TITLE
List of non-model types are mapped as dictionaries

### ISSUE THREAD

**Issue by leonardocfor** [aws-amplify/amplify-category-api#1210]
### Amplify CLI Version

10.3.1

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

Hi guys, 

I have set the following schema

```
type User @model{
  username: String! @primaryKey
  name: String!
  lastname: String!
  email: String!
  phoneNumbers: [PHONE_NUMBER]
}
type PHONE_NUMBER {
  countryCode: String!
  number: String!
  extension: String
}
```
The API is generated but incorrectly. For example the mutation `createUser` does not allow the actual list of PHONE_NUMBER but rather it takes  it as it was a JSON or a dictionary despite the fact that the User model's field is defined as a list `[PHONE_NUMBER]`

```
mutation MyMutation {
  createUser(input: {
    username: "xxxx", 
    name: "xxxx", lastname: "xxxx", 
    email: "xxxx", 
    phoneNumber: {
      countryCode: "xxx",
      number:"xxxxxx"
      }})
}
```

### Expected behavior

As it was with the Resolver v.1, the mutation should allow a list of PHONE_NUMBER, as follows:

```
mutation MyMutation {
  createUser(input: {
    username: "xxxx", 
    name: "xxxx", lastname: "xxxx", 
    email: "xxxx", 
    phoneNumbers: [
      { 
      countryCode: "xxx",
      number:"xxxxxx"
      },
     { 
      countryCode: "yyy",
      number:"yyyyyy"
      }
]})
}
```

### Reproduction steps

Does not apply

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi @leonardocfor 👋 , Thank you for raising this issue. Are you getting any error when you pass the phone numbers input as array?  i have tried below and was able to get the expected response.
```javascript
mutation MyMutation {
  createUser(input: {phoneNumbers: [{countryCode: "1", extension: "10", number: "1234567"}, {countryCode: "1", extension: "10", number: "1234567"}], email: "test1@test.com", lastname: "test1", name: "test", username: "test1@test.com"}) {
    email
    createdAt
  }
}
```

<img width="944" alt="image" src="https://user-images.githubusercontent.com/3206171/215595070-866eac30-6820-496c-8b8d-6028393fc69d.png">

**Comment by leonardocfor** [comment]
Thanks for your quick reply @AnilMaktala. I just tested your suggestion and it worked but I had the issue with the autogenerated mutations when using React. I'll keep digging and add more info once I have it.

**Comment by alharris-at** [comment]
@leonardocfor - Are you using the appsync console to generate these queries? If so, I believe what you're seeing is actually a shortcoming of the form builder UI today. As mentioned by @AnilMaktala I confirmed that using your query on Amplify CLI v 10.7.3 generates an input type that expects a list, not a map.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
