### ISSUE TITLE
Mock Appsync Subscription Url "/graphql/realtime" doesn't work

### ISSUE THREAD

**Issue by mgarabedian** [aws-amplify/amplify-category-api#122]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

7.6.5

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

Appsync mock subscriptions have not been working for me for some time. I have been trying to understand why.  Doing some debugging, it appears that [amplify-js is calling](https://github.com/aws-amplify/amplify-js/blob/ee83e7375c32c8804cbf9a0e21cc6fd1ef662358/packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts#L147) the URL '/graphql/realtime' to initiate the websocket connection, but the [mock server is not setup to handle that URL](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-appsync-simulator/src/server/websocket-subscription.ts).  

If I use a nginx proxy to rewrite that url from '/graphql/realtime' to '/graphql' , or manually alter the amplify-js code to call '/graphql', then everything is fine.

Have I missed something in the configuration, or is this a bug?

### Expected behavior

the url that amplify js calls works with mock. 

### Reproduction steps

Run a subscription on mock.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by lysachok** [comment]
The proxying workaround doesn't work for me.

**Comment by LaurensBrinker** [comment]
For anyone else running into this issue with Create React App, I got it working with the help of @josefaidt 's proposed solution:

setupProxy.js file ([create proxy in create-react-app](https://create-react-app.dev/docs/proxying-api-requests-in-development/#configuring-the-proxy-manually)):


```
const { createProxyMiddleware } = require('http-proxy-middleware');

module.exports = (app) => {
  app.use(
    '/graphql',
    createProxyMiddleware({
      target: 'http://localhost:20002/graphql',
      changeOrigin: true,
    })
  );
  app.use(
    '/graphql/realtime',
    createProxyMiddleware({
      target: 'ws://localhost:20002/graphql',
      changeOrigin: true,
      ws: true
    })
  );
};
```

App.js file:
```
import React from 'react'

import './App.css';

import { Amplify } from 'aws-amplify';

import awsExports from "./aws-exports";

if (process.env.REACT_APP_LOCAL === 'true'){ // Can be better, but for testing this is how I switch for now.
  awsExports.aws_appsync_authenticationType = 'API_KEY'
  awsExports.aws_appsync_graphqlEndpoint = 'http://localhost:3000/graphql' // override to :3000
}

Amplify.configure(awsExports);
```

**Comment by phani-srikar** [comment]
Hi @mgarabedian @alexNerazim @LaurensBrinker @lysachok. Thanks for reporting this issue. We've recently released a fix for this one, can you please upgrade your Amplify CLI to version `10.3.0` and try it out? Please re-open if the issue persists.

**Comment by jansila** [comment]
Works for me now, thanks!

> Hi @mgarabedian @alexNerazim @LaurensBrinker @lysachok. Thanks for reporting this issue. We've recently released a fix for this one, can you please upgrade your Amplify CLI to version `10.3.0` and try it out? Please re-open if the issue persists.

**Comment by lysachok** [comment]
Works for me as well. Thank you!
