### ISSUE TITLE
How to refer to unauthRole arn in custom resolver created by aws-cdk

### ISSUE THREAD

**Issue by mstoyanovv** [aws-amplify/amplify-category-api#1221]
### Amplify CLI Version

10.5.1

### Question

I have created a custom vtl pipeline with aws cdk. The issue is that I cannot refer to 'unauhtRole' because there is no such variable in $ctx.stash.
So the question is, when you create a custom vtl resolver/pipeline as described [here](https://docs.amplify.aws/cli/graphql/custom-business-logic/#vtl-resolver) how do you access the unauth/authRole arn in order to use it in auth function same way amplify does in the auto generated resolvers?

**Comment by AnilMaktala** [comment]
Hey @mstoyanovv,Thank you for asking the question. as of now the workaround you did is best way to move forward. if you find any issues with the approach you followed please do let us know we will see if you make sense for us to create a future request.
