### ISSUE TITLE
How to make manyToMany searchable?

### ISSUE THREAD

**Issue by mithun35h** [aws-amplify/amplify-category-api#1229]
### Amplify CLI Version

10.7.0

### Question

@manyToMany(relationName: "name")

create a dynamodb table with the given name, how to make this searchable? or sync it with opensearch

writing post script to create trigger for the table and also create functions in appsync with VTL i think is a complicated customization

**Comment by josefaidt** [comment]
Hey @mithun35h :wave: thanks for raising this! Unfortunately we will not be able to add `@searchable` on a field itself, however we can use `@hasMany` to manually create the join table (similar to how `@manyToMany` creates a join table behind the scenes). From here we can add `@searchable` to the join table

```graphql
type Class
  @model
  @auth(rules: [{ allow: owner }, { allow: groups, groupsField: "cohorts" }]) {
  id: ID!
  name: String!
  cohorts: [String]
  students: [ClassStudent] @hasMany
}

type Student
  @model
  @auth(rules: [{ allow: owner }, { allow: private, operations: [read] }]) {
  id: ID!
  name: String!
  classes: [ClassStudent] @hasMany
  owner: String! @auth(rules: [{ allow: owner, operations: [create, read] }])
}

type ClassStudent
  @model
  @searchable
  @auth(
    rules: [{ allow: owner }, { allow: groups, groupsField: "classCohorts" }]
  ) {
  id: ID!
  class: Class! @belongsTo
  student: Student! @belongsTo
  classCohorts: [String] # this will be the cohorts of the class, we need to carry this field onto the join model in order to apply
}
```

**Comment by tarunv69** [comment]
Hello @josefaidt , I did try out the solution that you have provided here but there was this error ` EMFILE: too many open files, open` 

To explain my issue better, let me refer it with the same table as your solution. 

The schema before : 

`type Class
  @model
  @auth(rules: [{ allow: owner }, { allow: groups}]) {
  id: ID!
  name: String!
  student: [Student] @manyToMany(relationName: "classStudent")
}

type Student
  @model
  @auth(rules: [{ allow: owner }, { allow: private, operations: [read] }]) {
  id: ID!
  name: String!
  class: [Class] @manyToMany(relationName: "classStudent")
  owner: String! @auth(rules: [{ allow: owner, operations: [create, read] }])
}`

After the changes, the schema looked like this: 

`type Class
  @model
  @auth(rules: [{ allow: owner }, { allow: groups, groupsField: "cohorts" }]) {
  id: ID!
  name: String!
  students: [ClassStudent] @hasMany
}

type Student
  @model
  @auth(rules: [{ allow: owner }, { allow: private, operations: [read] }]) {
  id: ID!
  name: String!
  classes: [ClassStudent] @hasMany
  owner: String! @auth(rules: [{ allow: owner, operations: [create, read] }])
}

type ClassStudent
  @model
  @searchable
  @auth(
    rules: [{ allow: owner }, { allow: groups }]
  ) {
  id: ID!
  class: Class! @belongsTo
  student: Student! @belongsTo
}`


So I got the error "EMFILE: too many open files, open" after pushing the latter schema. Tried it several times only to  get the same issue at the end. 

**Region**
eu-central-1

**Amplify CLI Version**
10.7.2

**OS**
Mac

**Node version**
Node.js v18.13.0

**Comment by phani-srikar** [comment]
Hi @mithun35h, I've tried to deploy your schema and had to make some minor changes shown below:
```
type Class
  @model
  @auth(rules: [{ allow: owner }, { allow: groups, groupsField: "cohorts" }]) {
  id: ID!
  name: String!
  students: [ClassStudent] @hasMany
}

type Student
  @model
  @auth(rules: [{ allow: owner }, { allow: private, operations: [read] }]) {
  id: ID!
  name: String!
  classes: [ClassStudent] @hasMany
  owner: String!
}

type ClassStudent
  @model
  @searchable
  @auth(
    rules: [{ allow: owner }]
  ) {
  id: ID!
  class: Class! @belongsTo
  student: Student! @belongsTo
}
```
With the above schema,  I am able to deploy successfully and did not run into the File limit error you've mentioned.
However, I've found a [similar issue](https://github.com/aws-amplify/amplify-studio/issues/414) when using the Amplify Studio. Do you use Amplify Studio for your App deployments?

**Comment by AnilMaktala** [comment]
Hi 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment and provide us with the information our team had previously asked for. This way, we can reopen the issue and provide you with better assistance.

Thank you!
