### ISSUE TITLE
Use amplify-appsync-simulator standalone?

### ISSUE THREAD

**Issue by dylanfprice** [aws-amplify/amplify-category-api#1231]
### Amplify CLI Version

10.7.1

### Question

I am wondering if it is possible to use the [`amplify-appsync-simulator`](https://github.com/aws-amplify/amplify-cli/tree/dev/packages/amplify-appsync-simulator) in a standalone manner. We have an AWS AppSync API built out of CloudFormation templates and Python, not using the Amplify framework. It would be a big benefit in terms of cheap integration testing if we could run the AppSync API locally. We have a docker-compose based local environment with dynamodb-local where we already run basic integration tests with dynamodb.

So my question is would such a use case be something you are seeking to support with the `amplify-appsync-simulator` package? And if so, perhaps there could be some lightweight documentation on how to do so in a stable/supported way.

**Comment by AnilMaktala** [comment]
Hi @dylanfprice 👋 ,Thank you for asking this question. In order to provide better support, we have created a ticket in the Appsync repository. To stay updated, please subscribe to this [issue](https://github.com/aws/aws-appsync-community/issues/262).
