### ISSUE TITLE
`amplify build` swallows GraphQL compilation errors

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-category-api#1246]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

10.7.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

When building a amplify project using `amplify build ` the API does not build. Running `amplify api gql-compile` works as expected. 

### Expected behavior

Build API on `amplify build`

### Reproduction steps

1. add the following schema
```
type User @model @auth(rules: [{ allow: public }]) {
  id: ID!
  status: AWSJSON
  email: String!
  name: String
  config: AWSJSON
  settings: AWSJSON
  entries: [Entry] @hasMany
}

type Entry @model @auth(rules: [{ allow: public }]) {
  id: ID!
  status: String
  type: AWSJSON
  date: AWSDateTime!
  notes: String
  conditions: AWSJSON
  treatments: AWSJSON
  meta: AWSJSON
  userId: ID!
  user: User @belongsTo
  images: [Image] @hasMany
}

type Image @model @auth(rules: [{ allow: public }]) {
  id: ID!
  status: String
  view: AWSJSON
  path: AWSJSON
  date: AWSDateTime
  notes: String
  meta: AWSJSON
  userId: ID!
  entryId: ID!
  entry: Entry @belongsTo
}

```
3. run `amplify build` and `amplify api gql-compile`. observes both show building api resource
4. next comment out the following
```
# type User @model @auth(rules: [{ allow: public }]) {
#   id: ID!
#   status: AWSJSON
#   email: String!
#   name: String
#   config: AWSJSON
#   settings: AWSJSON
#   entries: [Entry] @hasMany
# }

type Entry @model @auth(rules: [{ allow: public }]) {
  id: ID!
  status: String
  type: AWSJSON
  date: AWSDateTime!
  notes: String
  conditions: AWSJSON
  treatments: AWSJSON
  meta: AWSJSON
  userId: ID!
  user: User @belongsTo
  images: [Image] @hasMany
}

type Image @model @auth(rules: [{ allow: public }]) {
  id: ID!
  status: String
  view: AWSJSON
  path: AWSJSON
  date: AWSDateTime
  notes: String
  meta: AWSJSON
  userId: ID!
  entryId: ID!
  entry: Entry @belongsTo
}
```
this should fail as entry model has a belongsTo for user model 
5. run `amplify build` and `amplify api gql-compile`. observe compile work and throws an error as expected but build just ends.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
I was able to reproduce this only if I'm expecting a compilation error. After making the change from the repro steps to cause the error I see the following:

```
aws-amplify/reproductions/a12032 
➜  amplify build

aws-amplify/reproductions/a12032 
➜  amplify api gql-compile
🛑 Schema validation failed.

Unknown type "User".

GraphQL request:68:9
67 |   userId: ID!
68 |   user: User @belongsTo
   |         ^
69 |   images: [Image] @hasMany 
```

It appears build might be running the compilation but swallowing the error
