### ISSUE TITLE
Bypass @auth rules with lambda accessing api through appsync gql 

### ISSUE THREAD

**Issue by unknown1337** [aws-amplify/amplify-category-api#1266]
### Amplify CLI Version

10.7.2

### Question

Goal: cognito trigger to add some item do a DDB that normaly is only accessable by the owner (cognito user) according the graphql schema (amplify)
steps
1. cli-> add function -> resource access permissions -> api -> Query & mutation
2. open function's custom.js, do a fetch using the x-api-key (env var) provided by step 1

Questions, 
A. what does step 2 do? does it create an IAM role with dynamodb access? (I see one in IAM, but dont know if that role belong to the lambda func or if it belongs to the appsync instance) or does it only create 'a authorization function tied to appsync'?.
B. can the above WoW bypass the appsync authorization rules?  (I think it can't based on some tests). If you could give some context that would be great :)
C. What is the proper WoW to achieve my goal? perform step 1 & 2 and then use the 
C.i = JS lib or 
C.ii = directly use the dynamodb low level [api](https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/DynamoDB/Client.html) and set secret_access_key to the env var generated in step 2?
C.iii = other?

Thanks!!!!

**Comment by AnilMaktala** [comment]
Hi @unknown1337, Thank you for asking the question. You can implement your usecase by following the approach mentioned in the doc [here](https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/js/#using-amplify-graphql-client) and you need to implement this to use cognito auth for the API mentioned [here](https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js/#sign-in)

**Comment by unknown1337** [comment]
Thanks, though I think my question was not that clear. How can I execute a lambda function, while bypassing the GQL scheme authorization  rules while assuming:
1) I want the function IAM roles to be auto generated s.t. when amplify changes a resource name I dont need to manually create a new IAM role

Given 1, I assume I need to I create the function through the amplify CLI? if so, how can I grant the function access to the dynamodb table and/or appsync api with 'service role access' on a given table

Thanks!

**Comment by unknown1337** [comment]
updated

**Comment by renebrandel** [comment]
Hi we've implemented this feature here: https://docs.amplify.aws/cli/graphql/authorization-rules/#grant-lambda-function-access-to-graphql-api
