### ISSUE TITLE
How to bypass build error when backend schema is broken down into files

### ISSUE THREAD

**Issue by ErnestDaDev** [aws-amplify/amplify-category-api#1268]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1tc3nbeqxqpjy

### AWS Region

us-west-2

### Amplify Hosting feature

Backend builds, Build settings, Deployments

### Question

Hello ,

i have a schema which we have broken down into files meaning we are not using schema.graphql file, so when i tried connecting the repo and it attempts building the bakcend it throws this error: 
`ENOENT: no such file or directory, open '/codebuild/output/src081075594/src/crig-cms/amplify/backend/api/appname/schema.graphql'`

So how do i get past this?

**Comment by josefaidt** [comment]
Hey @ErnestDaDev :wave: thanks for raising this! At what point in the build step are you experiencing this issue? Do you have Conflict detection for DataStore enabled? I'm wondering if you may be experiencing this active bug https://github.com/aws-amplify/amplify-category-api/issues/711

**Comment by AnilMaktala** [comment]
Hi 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment and provide us with the information our team had previously asked for. This way, we can reopen the issue and provide you with better assistance.

Thank you!
