### ISSUE TITLE
Lambda function generated execution role IAM understanding

### ISSUE THREAD

**Issue by unknown1337** [aws-amplify/amplify-category-api#1298]
### Amplify CLI Version

10.7.2

### Question

**Goal**: enable a lambda function to mutation a graphql schema `Company`
### Method 1, NOK: 
- amplify add function test (incl resource access permissions->api allow)
- graphql schema 1:
``` type Company
  @model
  @auth(rules: [{ allow: owner }]) {
  id: ID!
  name: String!
  owner: String @auth(rules: [{ allow: owner, operations: [read, delete] }])
} 
```
- amplify mock function test

Result NOK: "Not Authorized to access listCompanies on type Model"

### Method 2, OK, but not understood & documentation mismatch?

- amplify add function test (incl resource access permissions->api allow)
- graphql schema 1:
```type Company
  @model
  @auth(rules: [{ allow: owner,**{ provider: iam, allow: private }** }]) {
  id: ID!
  name: String!
  owner: String @auth(rules: [{ allow: owner, operations: [read, delete] }])
}
```
- amplify mock function test

Result OK: 'list of companies'

### Questions
1. When the amplify CLI generates the IAM policies for the lambda execution policies, is it still required to add `{ provider: iam, allow: private }` in the @auth gql scheme? According my tests, yes, but this is contradicting the documentation ["...these functions have special access privileges that are scoped **based on their IAM policy instead of any particular @auth rule**."](https://docs.amplify.aws/cli/graphql/authorization-rules/#grant-lambda-function-access-to-graphql-api)
2. What is meant with [The function can only be added when the GraphQL API with IAM authorization exists](https://docs.amplify.aws/cli/function/#utilizing-lambda-function-template-iam-authorization)."". Does this imply that when running the `amplify add api` IAM needs to be selected as Auth mechanism?
3. in order to mock the function, am I correct that my IAM USER selected when running `amplify init` is 'used'? Thus I have to add the correct policies to that IAM user to allow GQL permissions? For now I added `administrator access` (not really the least priviledge WoW).
4. if I only allow regular users (=app visitors) to register through cognito, is there than a risk that they are allowed to update the resource `company` due to `{ provider: iam, allow: private }` (private =  [any signed-in user has access](https://docs.amplify.aws/cli/graphql/authorization-rules/#authorization-strategies).) IFF possible some context (or suggested reading material) would help me understand and learn.
5. update: after some more testing I got again the error when running `amplify mock function`: `Not Authorized to access listCompanies on type ModelCompanyConnection`. I have no clue what could be wrong as the model contains { provider: iam, allow: private } & my local IAM user (local-aws-info.json) has the `AdministratorAccess` policy assigned. Any tips?

THANKS A LOT!

**Comment by unknown1337** [comment]
WOW, thanks for the response. Gained some great insights already :)

> I do not believe IAM is authorized in amplify mock function, however the policies will be generated automatically for you in the Function's CloudFormation template.

Thanks, I will try to see if I can find this in the cloudformation code

> Specifying the following auth rules will ensure the model's records are only accessible by their respective owners and **private IAM calls**

Could you elaborate a bit on the definition of a private IAM call?

> Were the resources pushed prior to running amplify mock api?
Yes, thanks, but it was already pushed. I managed to get it **working** :) by adding 
``` custom-roles.json
{
  "adminRoleNames": ["amplify-CR"]
}

```
though I don't understand why this fixes the lambda function mock authorization error  (or shouldnt I need to do this)? Is this because my project amplify IAM user 'amplify-CR' is not created by amplify and thus the @auth {provider:iam} does not have affect [(based on this doc)](https://docs.amplify.aws/cli/graphql/authorization-rules/#use-iam-authorization-within-the-appsync-console)?

Thanks :)

**Comment by unknown1337** [comment]
@josefaidt , could you maybe help me a bit further, I REALLY value your feedback. Thanks!

**Comment by josefaidt** [comment]
Hey :wave: apologies for the delay!

> am I correct that generating a function without configuring Do you want to access other resources in this project from your Lambda function? Yes that the IAM role that is generated for the function does not allow access to my graphql api yet?

Correct, you can inspect the generated IAM policy in the Function's CloudFormation template, however it will not be created until you push.

> When do I need to allow api access to the function using the CLI? And do I need to add a @Auth directive with IAM to the corresponding model?

If you want to interact with the GraphQL API in that function. For instance, if you have a PostConfirmation Cognito Trigger that creates a `UserProfile` record after a user confirms signup.

> Could you elaborate a bit on the definition of a private IAM call and the difference between executing a cognito userpool call? please see 2a and 2b

Private IAM will call using the role's credentials, where calling via Cognito User Pool (from a Lambda) will require you to pass the user's JWT. In the case of a PostConfirmation trigger you can call the GraphQL API on the user's behalf by constructing and passing their ID token -- if you are using `owner` auth you will not need to construct the `owner` argument as the user's [`sub::username`](https://docs.amplify.aws/cli/migration/identity-claim-changes/#what-is-changing). Both are achievable with either auth mechanism.

**Comment by unknown1337** [comment]
Thanks a lot @josefaidt , most of it is clear! 
> in the case of a PostConfirmation trigger you can call the GraphQL API on the user's behalf by constructing and passing their ID token

Where will the token be verified (if e.g. the claims were not altered by the user? I think answer 2a and b are correct?)
1. the lambda function receives a verified token  thus I can check the claims directly and perform a dynamodb insert using the function's IAM role.
2. the lambda function receives an UNverified token, so I either:
a) need to verify the token `(how to get the publicKey?)`
```
 const result = await jwt.verify(authorizationToken, publicKey);
const   isAuthorized = result && result.fooClaim && result.fooClaim=== 'bar'
```
b) or needs to call the graphql api as that api will perform the authorization (correct?)

Thanks!

**Comment by josefaidt** [comment]
Hey @unknown1337 apologies for the delay!

> Where will the token be verified

In the `Company` model's auth resolver. However you can instead use `allow: private, provider: iam` and pass the model's `owner` information manually using the convention `<sub>::<username>`

> or needs to call the graphql api as that api will perform the authorization (correct alternative?)

Yes, calls directly to your GraphQL API will perform the authorization, and enables streaming the mutations in the event you have subscriptions running.

If you are looking to insert data directly to the underlying `Company` DynamoDB table you can do so by passing the required information including the `owner` value (if "owner" auth is used)

**Comment by unknown1337** [comment]
Thanks, so does this imply that the tokens passed to a lambda function are 'never'  checked for validity. This implies that I 
1. have to check the token & claim validity in that lambda function if  I perform direct dynamodb table mutations 
2. I dont need to check token & claim validity if I call the Gql api endpoint from that lambda function (as the gql resolver will then check validity).

correct?
