### ISSUE TITLE
Upgrading Transformer v2 fails to deploy from CICD

### ISSUE THREAD

**Issue by daniellorenzin** [aws-amplify/amplify-category-api#1314]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

 npm

### Amplify CLI Version

7.6.15

### What operating system are you using?

Linux

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

api

### Amplify Commands

init, publish, push

### Describe the bug

Updating the graphql api from V1 to V2, but fails to deploy via Amplify CI/CD with the following error:

```
SchemaValidationError: Your GraphQL Schema is using "@index", "@hasMany", "@belongsTo", "@manyToMany", "@hasOne" directives from the newer version of the GraphQL Transformer. Visit https://docs.amplify.aws/cli/migration/transformer-migration/ to learn how to migrate your GraphQL schema.
```

CLI.json is as follows:

```json
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": false,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": false,
      "skipoverridemutationinputtypes": false,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true,
      "showfieldauthnotification": false
    },
    "frontend-ios": {
      "enablexcodeintegration": false
    },
    "auth": {
      "enablecaseinsensitivity": false,
      "useinclusiveterminology": false,
      "breakcirculardependency": false,
      "forcealiasattributes": false,
      "useenabledmfas": false
    },
    "codegen": {
      "useappsyncmodelgenplugin": false,
      "usedocsgeneratorplugin": false,
      "usetypesgeneratorplugin": false,
      "cleangeneratedmodelsdirectory": false,
      "retaincasestyle": false,
      "addtimestampfields": false,
      "handlelistnullabilitytransparently": false,
      "emitauthprovider": false,
      "generateindexrules": false,
      "enabledartnullsafety": false
    },
    "appsync": {
      "generategraphqlpermissions": false
    },
    "latestregionsupport": {
      "pinpoint": 0,
      "translate": 0,
      "transcribe": 0,
      "rekognition": 0,
      "textract": 0,
      "comprehend": 0
    },
    "project": {
      "overrides": true
    }
  }
}
```

### Expected behavior

Should deploy and upgrade the GraphQL to the V2 transformation.

### Reproduction steps

Use the amplify build ci/cd with a v1 graphql schema.
Migrate the graphql schema to v2 and commit for cicd to build and deploy

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by amitchaudhary140** [comment]
Same issue. Not able to build the environment. I have a dev branch and I created new branch called "test" from dev. My dev env is working fine. But the test env never builds although it has all the data it needs. I am not able to do 'amplify push' because it doesn't list the environment in my local machine. 

<img width="1328" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/119692506/a682dc96-891f-441e-af8c-5468fbc49cea">
