### ISSUE TITLE
Please reopen #1197

### ISSUE THREAD

**Issue by tartachyov** [aws-amplify/amplify-category-api#1320]
### Amplify CLI Version

-

### What operating system are you using?

-

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

-

### Describe the bug

-

### Expected behavior

-

### Reproduction steps

-

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by tartachyov** [comment]
#1197

**Comment by AnilMaktala** [comment]
Hey @tartachyov, As the 1197 issue has been reopened, we will be closing this duplicate issue..
