### ISSUE TITLE
How to define a local secondary index instead of a global for DynamoDB using graphql

### ISSUE THREAD

**Issue by ok-martin** [aws-amplify/amplify-category-api#1321]
### Amplify CLI Version

10.7.3

### Question

Hello, I am trying to define a **global secondary index** using graphql.

When I use @index on the @primaryKey it creates a global secondary index on my table. 

I defined my schema to be:

```
type TestModel @model {
hashKey: String! 
    @primaryKey(sortKeyFields: ["rangeKey"])
    @index(name: "bySecondaryValue", sortKeyFields: ["secondaryValue"], queryField: "getTestModelBySecondaryValue")
rangeKey: String!
secondaryValue: String!
}
```

After doing ```amplify push``` (or ```amplify api gql-compile```) I see it creates the gis in the CloudFormation file TestModel.json:

```
"GlobalSecondaryIndexes": [
	{
		"IndexName": "bySecondaryValue",
		"KeySchema": [
			{
				"AttributeName": "hashKey",
				"KeyType": "HASH"
			},
			{
				"AttributeName": "secondaryValue",
				"KeyType": "RANGE"
			}
		],
	}
],
```

I would like to create a local secondary index instead. How can I achieve that?

**Comment by josefaidt** [comment]
Hey @ok-martin :wave: you can set the [`secondaryKeyAsGSI`](https://docs.amplify.aws/cli/reference/feature-flags/#secondaryKeyAsGSI) feature flag to `false` in `amplify/cli.json` to generate LSI's

**Comment by ok-martin** [comment]
Great, that's what I needed, thank you.
