### ISSUE TITLE
Failure to add paths using update api

### ISSUE THREAD

**Issue by orome** [aws-amplify/amplify-category-api#1335]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.15.0

### Amplify CLI Version

10.8.1

### What operating system are you using?

macOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

(In truth, it's hard to know given the bugs with push, but I'm 90% sure, which is a pretty high confidence level for anything Amplify.)

### Describe the bug

Amplify does not add paths added with 'update api' once 'override api' has been executed.

### Expected behavior

No current expectations regarding Amplify.

### Reproduction steps

```
amplify add api
amplify push  # API works as expected
amplify override api
amplify push # API works as expected
amplify update api
amplify push # added paths do not appear in API Gateway and are not accessible
```

### Project Identifier

3863987f00fb7935a93679dd30c7e0f9

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by chrisbonifacio** [comment]
Hi @orome 👋 thanks for raising this issue. I tried reproducing the issue described with the provided steps but so far I have not been able to reproduce the issue. I created a REST API, pushed, used `api override`, pushed, updated the API to add another path, pushed one more time. The result at the moment is I can see and make successful requests to both paths.

path 1 function

```js
/**
 * @type {import('@types/aws-lambda').APIGatewayProxyHandler}
 */
exports.handler = async (event) => {
  console.log(`EVENT: ${JSON.stringify(event)}`);
  return {
    statusCode: 200,
    //  Uncomment below to enable CORS requests
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Headers": "*",
    },
    body: JSON.stringify({
      items: [
        { title: "Item 1", content: "Content for item 1" },
        { title: "Item 2", content: "Content for item 2" },
        { title: "Item 3", content: "Content for item 3" },
      ],
    }),
  };
};

```

path 2 function

```js
/**
 * @type {import('@types/aws-lambda').APIGatewayProxyHandler}
 */
exports.handler = async (event) => {
  console.log(`EVENT: ${JSON.stringify(event)}`);
  return {
    statusCode: 200,
    //  Uncomment below to enable CORS requests
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Headers": "*",
    },
    body: JSON.stringify("Hello from second route!"),
  };
};

```

Result:
<img width="659" alt="Screenshot 2023-03-08 at 3 33 59 PM" src="https://user-images.githubusercontent.com/16952986/223843947-a00dc135-9cf0-44c4-b56d-a5274c4399eb.png">

API Gateway Console:
<img width="220" alt="Screenshot 2023-03-08 at 3 39 07 PM" src="https://user-images.githubusercontent.com/16952986/223844457-58852db3-4d56-4e76-8ca2-188e1534356b.png">


Can you share what you might've changed in the override? That might help me more accurately reproduce the issue. 

All I did was change the description of the API.

```js
// This file is used to override the REST API resources configuration
import { AmplifyApiRestResourceStackTemplate } from "@aws-amplify/cli-extensibility-helper";

export function override(resources: AmplifyApiRestResourceStackTemplate) {
  resources.restApi.description = "test description";
}

```

**Comment by orome** [comment]
@chrisbonifacio  I followed the instructions in [the documentation](https://docs.amplify.aws/cli/restapi/override/#add-a-cognito-user-pool-authorizer-to-your-rest-api).

**Comment by orome** [comment]
@chrisbonifacio I've repeated this (backing up to no REST API and then adding one, adding paths, overriding, and then attempting to add an additional path) several times now with the same result: no paths add following the override. I've done it also with exactly the code you have above.

**Comment by orome** [comment]
@chrisbonifacio Now I've done this enough that I can no longer push or pull.

**Comment by chrisbonifacio** [comment]
@orome apologies for the delay. Unfortunately, I still haven't been able to reproduce this behavior. I went through the documentation and added the cognito authorizer as it instructs so this is my override.ts file now:

```js
// This file is used to override the REST API resources configuration
import { AmplifyApiRestResourceStackTemplate } from "@aws-amplify/cli-extensibility-helper";

export function override(resources: AmplifyApiRestResourceStackTemplate) {
  resources.restApi.description = "Custom description";
  resources.restApi.minimumCompressionSize = 1024;

  // Replace the following with your Auth resource name
  const authResourceName = "dsnext13a5733ef3";
  const userPoolArnParameter = "AuthCognitoUserPoolArn";

  // Add a parameter to your Cloud Formation Template for the User Pool's ID
  resources.addCfnParameter(
    {
      type: "String",
      description:
        "The ARN of an existing Cognito User Pool to authorize requests",
      default: "NONE",
    },
    userPoolArnParameter,
    { "Fn::GetAtt": [`auth${authResourceName}`, "Outputs.UserPoolArn"] }
  );

  // Create the authorizer using the AuthCognitoUserPoolArn parameter defined above
  resources.restApi.addPropertyOverride("Body.securityDefinitions", {
    Cognito: {
      type: "apiKey",
      name: "Authorization",
      in: "header",
      "x-amazon-apigateway-authtype": "cognito_user_pools",
      "x-amazon-apigateway-authorizer": {
        type: "cognito_user_pools",
        providerARNs: [
          {
            "Fn::Join": ["", [{ Ref: userPoolArnParameter }]],
          },
        ],
      },
    },
  });

  // For every path in your REST API
  for (const path in resources.restApi.body.paths) {
    // Add the Authorization header as a parameter to requests
    resources.restApi.addPropertyOverride(
      `Body.paths.${path}.x-amazon-apigateway-any-method.parameters`,
      [
        ...resources.restApi.body.paths[path]["x-amazon-apigateway-any-method"]
          .parameters,
        {
          name: "Authorization",
          in: "header",
          required: false,
          type: "string",
        },
      ]
    );
    // Use your new Cognito User Pool authorizer for security
    resources.restApi.addPropertyOverride(
      `Body.paths.${path}.x-amazon-apigateway-any-method.security`,
      [{ Cognito: [] }]
    );
  }
}
```

However, after pushing I have been able to add more paths and successfully authorize the requests with a Cognito ID Token in the Authorization header

<img width="651" alt="CleanShot 2023-03-24 at 14 58 41@2x" src="https://user-images.githubusercontent.com/16952986/227615689-b5f8432b-dabb-4035-9102-508cf1e7dc11.png">

**Comment by chrisbonifacio** [comment]
A few things to help us reproduce:
- Can you please share your `override.ts` file?
- Please run `amplify diagnose --send-report` in your terminal and share the output project identifier

This will give us the same backend and override to push and try adding paths to as your environment
