### ISSUE TITLE
Pre token generation claim ARRAY or MULTIPLE custom groups

### ISSUE THREAD

**Issue by unknown1337** [aws-amplify/amplify-category-api#1337]
### Amplify CLI Version

10.7.2

### Goal
create multiple access levels (simplified) on multiple resource levels
1. companyAdmin=[companyIds] provides CRUD access, 
2. companycollaborator=[companyIds] provides RU, 
3. locationAdmin =[locationIds] provides RU access
4. locationGuest=[locationIds] provides R access 

### Method 
Dynamic group authorization + jwt token claims set by pre token gen trigger

**Model**
```
type Company
  @model
  @auth(
         {
        # allow CRUD if company Admin
        allow: groups
        groupsField: "id"
        groupClaim: "adminOfCompanies"
      },
       {
        # allow CRUD if company Admin
        allow: groups
        groupsField: "id"
        groupClaim: "collaboratorOfCompanies ",
        operations: ["read,update"]
      }
      }
    ]
  ) {
  id: ID!
  name:String!,
  ....
```
**Pre token gen**
```
const customClaims={}
customClaims.adminOfCompanies = getIdsFromDb....  (returns array of strings)
customClaims.collaboratorOfCompanies = getIdsFromDb... (returns array of strings)
customClaims.adminOfLocations= getFromIdsDb... (returns array of strings)
customClaims.guestOfLocations= getFromIdsDb... (returns array of strings)

...
event.response = {
    claimsOverrideDetails: {
      claimsToAddOrOverride: customClaims
    },
  };

```
###Problem
1. I cannot set an array to a custom claim field value `Unrecognizable lambda output in red in the @aws-amplify/ui-vue Authenticator login screen`, any workaround (note, assigning a string i.s.o. an array to the custom claim works)? 

If no workaround

2. I cannot override the groups as then I cannot have different access levels (admin & collaborator) for different entities (Company and Location). So I need custom group*S*, CompanyAdmins, companyCollaborators, LocationAdmins, companyLocationCollaborators, how can i create multiple groups using the pre token gen trigger?

if not possible

 3.then I think I need to pass a stringified array as custom claim `customClaims.guestOfLocations= getFromIdsDb(...).toSting()` and create custom lambda authorizers that converts the string claim to an array an checks if thatarray contains the locationId, somethinglike `guestOfLocationsArray.includes(event.variables.locationId)`, one per role, that parses the . Do I need to verify if the JWT claims received by the lambda event handler are valid? and if so, how should I do this?

THANKS!

**Comment by phani-srikar** [comment]
Hi @unknown1337, please refer to my comment in this [other similar issue](https://github.com/aws-amplify/amplify-category-api/issues/1345#issuecomment-1469184247) and let us know if that works. Closing this in favor of the other linked issue.

**Comment by unknown1337** [comment]
Thanks @phani-srikar  for the link. I think [your comment ](https://github.com/aws-amplify/amplify-category-api/issues/1345#issuecomment-1469184247) will not solve my issue as I need **dynamic group** based auth. 
1. @ login I set the IDs of the companies the user has access to + access level
`customClaims.adminOfCompanies = getIdsFromDb....  (returns array of strings)
customClaims.collaboratorOfCompanies = getIdsFromDb... (returns array of strings)`
3. in the model I check for a given ID if the appropiate permissions are present:
```
type Company
  @model
  @auth({
        # allow RU if company collaborator access
        allow: groups
        groupsField: "id"
        groupClaim: "collaboratorOfCompanies ",
        operations: ["read,update"]
      } } ] )
```
So unfortunately the linked comment wont help me (dynamic vs static groups) if im correct. Could you with this note take a look again at the questions in the openingspost.

Thanks!

**Comment by unknown1337** [comment]
@phani-srikar , friendly reminder as we're still having the issue of assigning an array to a custom claim and validating if a groupsField is in that groupclaim array using @auth
