### ISSUE TITLE
Breaking changes to the `ModelConnection` schema after making `items` array a required property

### ISSUE THREAD

**Issue by sebekz** [aws-amplify/amplify-category-api#1344]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.17.0

### Amplify CLI Version

10.8.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made. Amplify CLI used only to generate types, models and statements.

### Describe the bug

**Breaking changes were introduced to the `ModelConnection` schema after making `items` array a required property in aws-amplify/amplify-cli#8166**

When using `@model` directive on a type, model connection type is generated in the compiled schema after running `amplify api gql-compile`. For example. the compiled `\api\amplify\backend\api\...\build\schema.graphql` schema for this basic input

```graphql
type AmplifyCliAtModelTest @model {
  id: ID!
}
```

will result in `ModelAmplifyCliAtModelTestConnection` model connection type being generated (CLI **6.1.1** output below)

```graphql
type ModelAmplifyCliAtModelTestConnection {
  items: [AmplifyCliAtModelTest]
  nextToken: String
  startedAt: AWSTimestamp
}
```

At some point between **6.1.1** and **10.8.1** CLI versions, the `items` optional property became a required one, i.e. `items: [AmplifyCliAtModelTest]` became `items: [AmplifyCliAtModelTest]!`. This seems to be related to these two particular changes in the CLI:

- First `[]` became `[!]!` with [amplify-cli: //github feat: generate list types as non-null](https://github.com/aws-amplify/amplify-cli/commit/66a07f97ac0c607a38e6bce7258cf394e6f4fc88)
- Later it was partially reverted it and `[!]!` became `[]!` in [fix: generate list types will nullable elements by edwardfoyle · Pull Request aws-amplify/amplify-cli#9310 · aws-amplify/amplify-cli](https://github.com/aws-amplify/amplify-cli/pull/9310#issue-1080117016)

### Problem 
Our code relies on not introducing breaking changes to the schema and `[]` becoming `[]!` is considered to be a breaking change. There is no way that I can see to instruct `gql-compile` to leave `items` as it was, which is optional. 

### Expected behavior

Using the latest CLI versions I want to be able to configure the `amplify api gql-compile` output so that `ModelConnection` generated types have items array set as not required.

In other words I would like to be able to override code generation behavior so that instead of producing
```graphql
items: [AmplifyCliAtModelTest]
```
I can get
```graphql
items: [AmplifyCliAtModelTest]!
```

### Reproduction steps

A simple test `@model` type is useful to reproduce the problem

```graphql
type AmplifyCliAtModelTest @model {
  id: ID!
}
```

### Run `api gql-compile` using CLI prior to [amplify-cli: //github feat: generate list types as non-null](https://github.com/aws-amplify/amplify-cli/commit/66a07f97ac0c607a38e6bce7258cf394e6f4fc88)
1. Use Amplify CLI prior to introducing [this change](https://github.com/aws-amplify/amplify-cli/commit/66a07f97ac0c607a38e6bce7258cf394e6f4fc88) - **6.1.1** was used to test
3. Using the test schema, run `amplify api gql-compile`
4. Inspect generated `\api\amplify\backend\api\...\build\schema.graphql` file and find the `ModelAmplifyCliAtModelTestConnection` type.
It will look like this:

```graphql
type ModelAmplifyCliAtModelTestConnection {
  items: [AmplifyCliAtModelTest]
  nextToken: String
  startedAt: AWSTimestamp
}
```

### Run `api gql-compile` using CLI **10.8.1**
1. Using the test schema, run `amplify api gql-compile` 
2. Inspect generated \api\amplify\backend\api\...\build\schema.graphql` file and look for the `ModelAmplifyCliAtModelTestConnection` type

```graphql
type ModelAmplifyCliAtModelTestConnection {
  items: [AmplifyCliAtModelTest]!
  nextToken: String
  startedAt: AWSTimestamp
}
```

### Notice the difference

was
```graphql
items: [AmplifyCliAtModelTest]
```
is
```graphql
items: [AmplifyCliAtModelTest]!
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by phani-srikar** [comment]
Hi @sebekz, thanks for creating this issue. Like you've mentioned, this is an intentional change since if the user has access to the list query, then the `items` field will exist and can be empty if no records are present. 
Since you're upgrading from v`6.1.1`, few breaking changes like this are expected. I could not find any corresponding [feature flag](https://docs.amplify.aws/cli/reference/feature-flags/) that you could use to retain the previous behavior. 
I would recommend to try to update your Application code with stronger type definition for list query results.

**Comment by sebekz** [comment]
I was looking in many places for documentation/release notes with an unified list of breaking changes between major releases, best accompanied with recommended approach for addressing such changes. I failed finding such information.

The [Migration & Backwards compatibility](https://docs.amplify.aws/cli/) section of the official docs contains information about some for the changes, but it looks to be incomplete and can be pretty vague - for example saying _"With the latest Amplify library for Swift (...)"_ without mentioning the version number.

I was expecting to find an outline of changes between major releases for each of such releases (i.e. 6.x->7.x, ..., 10.x - 11.x) with an emphasis on breaking changes. [Github releases](https://github.com/aws-amplify/amplify-cli/releases) section has some information, but it's very high level. 

I am thinking it must be buried somewhere where I have not looked yet. Can you please point me in the right direction? Trial and error approach has been working so far in my **6.1.1** -> **10.8.1** journey, but it is very slow and not the most efficient way for approaching major upgrades.

**Comment by phani-srikar** [comment]
Hi @sebekz, like you've already mentioned, we only document few popular use-cases in the [CLI migration guide](https://docs.amplify.aws/cli/migration/lazy-load-custom-selection-set/) and the other source is the Changelog that's published for releases, which can be complicated to understand the commit descriptions. I will bring this up with the team to push for better documentation updates for every major version bump in CLI. Thanks for reporting.
