### ISSUE TITLE
Limit and Next Token are not working in a javascript resolver function.

### ISSUE THREAD

**Issue by LeoReubelt** [aws-amplify/amplify-category-api#1348]
### Amplify CLI Version

11.0.0

### Question

I am not sure this is the correct repo for this issue. But I put it here because this is where the request was made for javascript resolvers.

I have an Amplify application. It has a dynamo table. 
I created a custom query.... 

`fetchObjectsWithNextToken(nextToken: String): AWSJSON`

And in the amplify console, I created a resolver pipeline for this query.  I then added a function to the pipeline made the dynamo table its data source.

```
import { util } from '@aws-appsync/utils';

export function request(ctx) {
    return { 
        operation: 'Scan',
        limit: 1,
        nextToken: ctx.arguments.nextToken,
     }
}

export function response(ctx) {
    return ctx.result;
}
```

It returns the correct objects, but neither limit nor nextToken do anything. I've tried different capitalizations of the keys. But always get the same objects back regardless of what I put for limit or next token.

**Comment by phani-srikar** [comment]
Hi @LeoReubelt, thanks for reporting this. Can you try wrapping the limit and nextToken with `util.toJson` and see if that works?

**Comment by LeoReubelt** [comment]
Thanks for the response @phani-srikar. When I try that, I get the following... 

`error TS2339: Property 'toJson' does not exist on type 'Util'.`

**Comment by LeoReubelt** [comment]
JSON.stringify() does work.

I've tried the following....

const limit = JSON.stringify({limit: 1});
replace 'limit: 1' with 'limit'

const limit = JSON.stringify({limit: {N: 1}});
replace 'limit: 1' with 'limit'

replace 'limit: 1' with 'limit: JSON.stringify({N: 1})'
replace 'limit: 1' with 'limit: JSON.stringify({"N": 1})'
replace 'limit: 1' with 'limit: {N: 1}'

**Comment by phani-srikar** [comment]
Hi @LeoReubelt, thanks for reverting back. Can you tell me a little more about how you've attached this pipeline resolver to the custom query? Amplify CLI does not yet support using JS runtime functions. However, just to verify that `limit` and `nextToken` are working, I've done the following:
- Using Amplify CLI v`11.0.0`, create a JS app and initialized Amplify.
- Added a GraphQL API with the below schema and pushed the changes to cloud:
```
type MyModel @model {
  id: ID!
  description: String!
}

type Query {
  testScanOperation(nextToken: String): AWSJSON
}
```
- From the AppSync console and `functions` tab, added the below function, named `testSyncFunction` and set the Data Source to the DynamoDB table created for `MyModel`:
```
export function request(ctx) {
    return { 
        operation: 'Scan',
        limit: 1,
        nextToken: ctx.args.nextToken
     };
}

export function response(ctx) {
    return ctx.result;
}
```
- From the AppSync console, attached a pipeline resolver with JS runtime to the `testScanOperation` query:
```
export function request(ctx) {
    return {};
}
export function response(ctx) {
    return ctx.result;
}
```
- Attach the resolver function `testSyncFunction` to the pipeline resolver using `Add Function` drop-down and save.
- Created 3 `MyModel` records from the `Queries` tab.
- Ran the `testScanOperation` custom query and observed that only 1 item is returned. 
- Passed the `nextToken` received into the query and ran it again to get another item.

Can you please check if you misconfigured any of the above steps?

**Comment by LeoReubelt** [comment]
@phani-srikar - thanks for the work. I don't know what the issue was. But it is working this morning. Maybe it was the user that I was using or some other mistake that I was making that was fixed by a new week. But it is working now. Thanks for all the time you spent. 

While you are here... You brought up deployment. My schema and query were made with the cli. But the resolver pipeline, and data source assignment, and function creation were all done in the console. But we have several environments in this application. And I need this pipeline and all its functions to deploy when the git branch is merged. So if the cli does not support javascript resolvers, how can I accomplish that? Or where can I enter an issue to find that out?

**Comment by phani-srikar** [comment]
Hi @LeoReubelt. Thanks for reverting back and good to know that your issue has been fixed. 
We are tracking this feature request for JS runtime support for AppSync resolvers [here](https://github.com/aws-amplify/amplify-category-api/issues/1015). Stay tuned.
