### ISSUE TITLE
OpenSearch upgrade on Transformer v1

### ISSUE THREAD

**Issue by parvusville** [aws-amplify/amplify-category-api#1349]
### Amplify CLI Version

10.8.1

### Question

Currently I am running Elasticsearch 6.8 instances, and noticed that there is an upgrade available. I can choose either Elasticsearch 7.10, or OpenSearch 1.3. If I upgrade to OpenSearch, will it work on my Amplify app using GraphQL Transformer v1? I know there are instructions when migrating to v2, but do they also work on v1? https://docs.amplify.aws/cli/migration/transformer-migration/#changes-that-amplify-cli-requires-you-to-manually-migrate

**Comment by AnilMaktala** [comment]
Hi @parvusville, Thanks for raising this. 

We will currently support patches for security-related problems or availability-impacting issues in V1. Therefore, we advise migrating to the v2 Transformer before updating the Opensearch version.
Instructions to migrate V2 can be found [here](https://docs.amplify.aws/cli/migration/transformer-migration/)

Steps to upgrade the Opensearch version:
1. Run amplify override api command at the root of the project. It will create the override.ts file.
2. Add below script to override.ts file
```
import { AmplifyApiGraphQlResourceStackTemplate } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyApiGraphQlResourceStackTemplate) {
  resources.opensearch.OpenSearchDomain.elasticsearchVersion = 'OpenSearch_1.3';
}

```
4. Run 'Amplify push'
5. Finally, please follow the steps outlined [here](https://docs.amplify.aws/cli-legacy/graphql-transformer/searchable/#configure-environment-opensearch-instance-type) to backfill the indexes from the DynamoDB table.

We recommend trying these steps in a lower environment before attempting them in a production environment. If you have any questions or concerns, please do not hesitate to let us know.

**Comment by parvusville** [comment]
Hi @AnilMaktala , thanks for getting back to me. I have tried to move onto v2 Transformer, but faced some problems listed here. https://github.com/aws-amplify/amplify-category-api/issues/1350#issuecomment-1478993784. 

At some point I will have to deal with them, but cannot allocate the time for it now. So it is probably a good idea to also postpone the OpenSearch upgrade until then.

**Comment by parvusville** [comment]
Hey @AnilMaktala , just getting back to this: ElasticSearch upgrade to 7.10 should be safe, right? I see that it was actually automatically used, when I created a new environment.

**Comment by AnilMaktala** [comment]
Hey @parvusville, Yes, ElasticSearch 7.10 should be fine.

**Comment by AnilMaktala** [comment]
Hi 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment. This way, we can reopen the issue and provide you with better help.

Thank you!
