### ISSUE TITLE
Dynamic Group Auth Not Being Respected by Subscription

### ISSUE THREAD

**Issue by chrisbonifacio** [aws-amplify/amplify-category-api#1350]
### How did you install the Amplify CLI?

pnpm

### Amplify CLI Version

11.0.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

This blog post (https://aws.amazon.com/blogs/mobile/build-real-time-multi-user-experiences-using-graphql-on-aws-amplify/) made me think that Subscriptions might respect dynamic group authorization, but based on my testing my onCreate subscription does receive every notification no matter which group it belongs to (my user only belongs to one group).

If this is the case, doesn't this allow an user to modify the frontend code, create subscriptions and receive updates of anything, no matter if the user is in the same group or not? Unless Subscriptions are explicitly disabled of course, which is not by default.

### Expected behavior

Subscription respects group auth rule

### Reproduction steps

1. Create and deploy schema

```graphql
type Notification
  @model
  @auth(
    rules: [
      { allow: private, provider: iam }
      { allow: groups, groupsField: "group" }
      { allow: public, operations: [] }
    ]
  )
  @key(
    name: "byGroupByStatus"
    fields: ["group", "status"]
    queryField: "listNotificationsByGroupByStatus"
  )
  @key(
    name: "byGroupByCreatedAt"
    fields: ["group", "createdAt"]
    queryField: "listNotificationsByGroupByCreatedAt"
  ) {
  id: ID!
  type: NotificationType!
  status: NotificationStatus
  group: String!
  reservationId: ID!
  createdAt: AWSDateTime! # Put here to use as a index (Amplify auto-generates this field too)
}

enum NotificationStatus {
  UNREAD
  READ
}
enum NotificationType {
  EXTERNAL_NOTE
}
```

2. subscribe to data as user that belongs to group
3. create record from another user
4. observe update

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by chrisbonifacio** [comment]
Hi @parvusville 👋 can you check the network tab for the onCreate subscription you mentioned in #1338? You can find it by inspecting the page > Network > look for and open the `graphql/?header` request. From there, check the headers to see if the subscription was authorized with IAM (signed request) vs Cognito (access token in Authorization header).

**Comment by parvusville** [comment]
Hi @chrisbonifacio . 

Here are the headers for the mentioned request:
![image](https://user-images.githubusercontent.com/85674677/226272124-7edcee5f-a42d-4518-bcc7-85885e7b07d6.png)

And here is the initial `onUpdateNotification` message on the WS, which appears to have some access token.  Is this enough to confirm Cognito was used? 
![image](https://user-images.githubusercontent.com/85674677/226273833-f8809370-cb43-4fa7-bab3-ad517fca102a.png)


Also when I'm logging the subscriptions, `provider` here has Cognito in the _config listed as authentication type.
```
    const subscription = API.graphql(
      graphqlOperation(subscriptions.onUpdateNotification)
    ).subscribe({
      next: ({ provider, value }) => console.log({ provider, value }),
      error: (error) => console.warn(error),
    });
    
// provider._config: aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS"
```

**Comment by chrisbonifacio** [comment]
@parvusville still in the process of reproducing this issue. From the schema it looks like you're using the V1 GraphQL transformer. Is there a reason why you haven't upgraded to V2?

**Comment by parvusville** [comment]
Hello @chrisbonifacio . In short I did try to upgrade, but there still seem to be some problems with it. Currently I am working on implementing a true multi-tenancy, and I couldn't use more time on figuring out the problems with the new version. 

Some examples of why I have not upgraded:
My initial issues:  https://github.com/aws-amplify/amplify-category-api/issues/789
Later I have also seen that quite a few other problems exist, that seem to be at least somewhat related to dynamic group authentication. 
This one in particular worries me: https://github.com/aws-amplify/amplify-category-api/issues/110
Probably related: https://github.com/aws-amplify/amplify-category-api/issues/82
Another one with a workaround causing more technical debt: https://github.com/aws-amplify/amplify-category-api/issues/61

**Comment by alharris-at** [comment]
HI @parvusville, as mentioned by @chrisbonifacio, the functionality for dynamic subscription filtering (as documented in that blog post) is only available for GraphQLv2 Backends, and there are no plans to back-port functionality to V1. I'd suggest migrating to V2 to continue receiving new functionality as it is released, as the only changes we're making to V1 moving forward will be security fixes. Resolving this ticket as question answered.
