### ISSUE TITLE
Resolvers not creating necessary parameters in table when running locally

### ISSUE THREAD

**Issue by ZacMelendez** [aws-amplify/amplify-category-api#1355]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

16.15.0

### Amplify CLI Version

11.0.2

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

When running amplify mock api for GraphQL, using the normal method of creating an object: 

```typescript
const result = await API.graphql<GraphQLQuery<CreatePostMutation>>(
                graphqlOperation(CreatePost, {
                    input: post,
                })
            );
```

Produces an error with the following message: `Cannot return null for non-nullable field Post._lastChangedAt.`

Here is how I defined Post:

```graphql
type Post
    @model
    @auth(
        rules: [
            { allow: public }
            # { allow: owner, ownerField: "userID" }
        ]
    ) {
    id: ID!
    content: String!
    title: String!
    image: String
    createdAt: String
    userID: ID! @index(name: "byUser")
    Comments: [Comment] @hasMany(indexName: "byPost", fields: ["id"])
}
```

### Expected behavior

If using the AWS AppSync, it does not produce this error. Also, I can create a custom mutation where I remove the `_lastChangedAt` from the return, and it works.

For some reason, I believe the resolvers are not adding this field to the dynamodb entry when creating these queries. Any ideas on how to fix this?

### Reproduction steps

1. Create an amplify project
2. Create a GraphQL API
3. Run amplify codegen
4. Use [AWS Docs](https://docs.amplify.aws/lib/graphqlapi/mutate-data/q/platform/js/) to write function to create item
5. Run code, get error similar to above.

I have also noticed that when searching for "_lastChangedAt" in the project, I see it in the resolvers for "updatePost", but it seems like it is not being done for "createPost".

### Project Identifier

b78c812837b77d1f489bc402b367f107

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ZacMelendez** [comment]
> * do you have Conflict Resolution enabled for your GraphQL API (to use with DataStore)?
> * are you only experiencing this when using `amplify mock`

Hi @josefaidt, I have not specifically configured anything resembling Conflict Resolution, so I will say no to that. As for your second point I am only experiencing it using amplify mock with the default mutations that `amplify codegen` produces. Here is an example of a mutation that is produced by amplify:

```typescript
export const createPost = /* GraphQL */ `
  mutation CreatePost(
    $input: CreatePostInput!
    $condition: ModelPostConditionInput
  ) {
    createPost(input: $input, condition: $condition) {
      id
      content
      title
      image
      createdAt
      userID
      Comments {
        nextToken
        startedAt
      }
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`
```

And here is a custom one:

```typescript
export const CreatePost = /* GraphQL */ `
    mutation CustomCreatePost(
        $input: CreatePostInput!
        $condition: ModelPostConditionInput
    ) {
        createPost(input: $input, condition: $condition) {
            id
            content
            title
            image
            createdAt
            userID
            Comments {
                nextToken
                startedAt
            }
            updatedAt
            _version
        }
    }
`
```

The latter works, as I have removed the `_lastChangedAt` and `_deleted` variables from the return item fields, so it doesn't need to look for a field that doesn't exist. 

However, when I push to AppSync, and look in my DynamoDB tables, there are these two variables, yet I am still using the custom queries & mutations so I am not sure if it is specifically a result of my amplify cli.

**Comment by ZacMelendez** [comment]
@josefaidt Apologies for the double response, but I did just test the original mutation, with `_lastChangedAt` and `_deleted` still there, and it did not give me any issues. So it seems to be an issue with just `amplify mock api`

**Comment by josefaidt** [comment]
Hey @ZacMelendez those fields are unique to conflict resolution and [DataStore](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js/) in that when we call our GraphQL API _without_ using DataStore we will need to pass the associated `_version`, otherwise you will see the calls going through successfully without updating the model.

If you use Amplify Studio, DataStore is automatically enabled when you click "save and deploy"

Despite this, this is a duplicate of https://github.com/aws-amplify/amplify-category-api/issues/1070 and https://github.com/aws-amplify/amplify-category-api/issues/322. To mitigate, you can disable Conflict Resolution (if it is not needed)

**Comment by ZacMelendez** [comment]
@josefaidt, Thank you for your help, disabling conflict detection worked for me!
