### ISSUE TITLE
The removal of @versioned

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-category-api#138]
With @versioned it was simple to achieve **conditional writes**.

I have read the v2 documentation but cannot find the equivalent.

How to set up conditional writes for a single object (not for all) ?
And what is the equivalent of **exptectedversion** ?

A concrete example would be very nice.

**Comment by josefaidt** [comment]
Hey @rudyhadoux :wave: thanks for raising this and apologies for the delay here!! Are you still experiencing this? This sounds like a great use case to leverage DataStore, which versions each of our records

**Comment by rudyhadoux** [comment]
Hi,
I have found a GraphQL solution. Not elegant, but it works.
When you create an object with same ID at same time, juste one object is created.
