### ISSUE TITLE
Pre token generation claim ARRAY

### ISSUE THREAD

**Issue by unknown1337** [aws-amplify/amplify-category-api#1381]
### Amplify CLI Version

10.7.2

### Question

Note, issue created as issue 1337 was closed without solution and re-opening was impossible for me

### Amplify CLI Version

10.7.2

### Goal
create multiple access levels (simplified) on multiple resource levels
1. companyAdmin=[companyIds] provides CRUD access, 
2. companycollaborator=[companyIds] provides RU, 
3. locationAdmin =[locationIds] provides RU access
4. locationGuest=[locationIds] provides R access 

### Method 
Dynamic group authorization + jwt token claims set by pre token gen trigger

**Model**
```
type Company
  @model
  @auth(
         {
        # allow CRUD if company Admin
        allow: groups
        groupsField: "id"
        groupClaim: "adminOfCompanies"
      },
       {
        # allow CRUD if company Admin
        allow: groups
        groupsField: "id"
        groupClaim: "collaboratorOfCompanies ",
        operations: ["read,update"]
      }
      }
    ]
  ) {
  id: ID!
  name:String!,
  ....
```
**Pre token gen**
```
const customClaims={}
customClaims.adminOfCompanies = getIdsFromDb....  (returns array of strings)
customClaims.collaboratorOfCompanies = getIdsFromDb... (returns array of strings)
customClaims.adminOfLocations= getFromIdsDb... (returns array of strings)
customClaims.guestOfLocations= getFromIdsDb... (returns array of strings)

...
event.response = {
    claimsOverrideDetails: {
      claimsToAddOrOverride: customClaims
    },
  };

```
###Problem
1. How to set an array to a custom claim field value without getting the `Unrecognizable lambda output in red in the @aws-amplify/ui-vue Authenticator login screen` error?

If no workaround

2. I cannot just override the groups array claim as then I cannot have different access levels (admin & collaborator) for different entity ID's (Company and Location). So I need custom group*S*, CompanyAdmins, companyCollaborators, LocationAdmins, companyLocationCollaborators, how can i create multiple groups using the pre token gen trigger?

if not possible

 3.then I think I need to pass a stringified array as custom claim `customClaims.guestOfLocations= getFromIdsDb(...).toSting()` and create custom lambda authorizers that converts the string claim to an array an checks if thatarray contains the locationId, somethinglike `guestOfLocationsArray.includes(event.variables.locationId)`, one per role, that parses the . Do I need to verify if the JWT claims received by the lambda event handler are valid? and if so, how should I do this?

THANKS!

**Comment by AnilMaktala** [comment]
Hi @unknown1337, Thankyou for creating this issue. We already have a similar issue #1345. Please subscribe to #1345 for future updates.
