### ISSUE TITLE
"construct does not have an associated node. All constructs must extend the "Construct" base class" error when pushing with Amplify v11

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-category-api#1404]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.19.0

### Amplify CLI Version

11.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

After upgrading to amplify cli v11, I get error on pushing as follows: 

"🛑 construct does not have an associated node. All constructs must extend the "Construct" base class"

I reported this 3 weeks ago at https://github.com/aws-amplify/amplify-cli/issues/12221#issuecomment-1470885867, and was asked to create new issue. The issue remains with latest version of amplify cli. @ykethan was working on a repro and asked me to create new issue. 

### Expected behavior

amplify push should work. 

reverting to v10.8.1 resolves the issue. 

### Reproduction steps

Upgrade to amplify v11 and do a push. I sent more details on my environment to amplify-cli@amazon.com  on March 14. 

### Project Identifier

3def1a2bd59d61900f734d59f169a578

### Log output

<details>

```
# Put your logs below this line

🛑 construct does not have an associated node. All constructs must extend the "Construct" base class
```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by flogy** [comment]
Thank you two for debugging this. I have now released the required changes in https://github.com/flogy/graphql-ttl-transformer/releases/tag/2.0.1

Thank you very much for your contribution! 🥳️
