### ISSUE TITLE
Pipeline resolver function response limits.

### ISSUE THREAD

**Issue by LeoReubelt** [aws-amplify/amplify-category-api#1405]
### Amplify CLI Version

11.0.0

### Question

I have a pipeline resolver function that has filters associated with it. And if Understand correctly, there is a limit of 1 mb on the response size of this type of function. My question is, is that 1 mb limit on the size of the response after the filters are applied or before? For example, before the filter is applied, the response is basically the entire table which is > 1 mb. But after the filter is applies, the response is only a few objects, which is < 1 mb. 

```
export function request(ctx) {
    let expression = `userId = :userId`;
    let expressionValues = {
        ':userId': { S: ctx.identity.claims.sub },
    };
    return {
        operation: 'Scan',
        filter: {
            expression: expression,
            expressionValues: expressionValues,
        },
        projection: {
            expression: 'associatedUsersId, roleId',
        },
    };
}
```

**Comment by phani-srikar** [comment]
Hey, assuming you're connected to a DynamoDB data source from your resolver, yes the 1MB limit applies to the size of the payload you receive from the DDB which in turn will be the result of this `Scan` operation with the filter included.

**Comment by AnilMaktala** [comment]
Hi @LeoReubelt 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment. This way, we can reopen the issue and provide you with better assistance.

Thank you!
