### ISSUE TITLE
AppSync GraphQL list operations not scaling - only querying a fraction of my data

### ISSUE THREAD

**Issue by justinjaeger** [aws-amplify/amplify-category-api#1408]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v16.15.1

### Amplify CLI Version

10.0.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

I just launched my app yesterday and unexpectedly went from just my small fleet of testers (5 users) to about 1000 users.

I discovered that at scale, the "listSomething" AppSync query only pull from a fraction of the total data in that table. So if I have 1000 users, and I filter for users with X email, I'm only searching 100 or so of the total users, so it's not going to find that user. This results in issues such as account duplication because I can't enforce uniqueness.

I know I should probably enforce uniqueness on the tables themselves, but this still seems odd that AppSync would by default not query your entire dataset in a filtered listing. Is it mandatory that I implement "@searchable" on any table where I want to search the entire dataset? Do I need to manually increase the limit, or paginate every time I want to scan the whole table? There are certain tables where it's necessary for me to return thousands of results.

"Get" operations are okay, as well as "search" for the tables that are using open search.

Seems like there's a default limit in AppSync queries of 100. Is this correct?

I am not using DataStore.

### Expected behavior

AppSync "list" operations should search my entire dataset. 

### Reproduction steps

Create any table
Create 1000 entries in that table
Query for all entries, observe that only a fraction of the 1000 total are returned

### Project Identifier

[report-1681584503593.zip](https://github.com/aws-amplify/amplify-cli/files/11240376/report-1681584503593.zip)

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by phani-srikar** [comment]
Hi @justinjaeger, when using a DynamoDB data source with AppSync, the list operation is implemented using the Scan operation in DynamoDB. The Scan operation reads every item in the table or index and can be inefficient and expensive when working with large data sets.

To optimize your list operations and ensure that you are searching your entire data set, you can consider using a Global Secondary Index (GSI) to support your list operation with a filter. A GSI allows you to create a secondary index on one or more attributes other than the primary key. By defining the right GSI, you can optimize your list operations and ensure that you are searching the entire data set. Refer [our docs](https://docs.amplify.aws/cli/graphql/data-modeling/#configure-a-secondary-index).

In terms of enforcing uniqueness, you can use the `@primaryKey` directive as mentioned [here](https://docs.amplify.aws/cli/graphql/data-modeling/#configure-a-primary-key).

You don't necessarily need to use the "@searchable" directive to search your entire data set, but it can help optimize your search operations by creating a search index on the specified fields. If you want to return thousands of results, you can use the Paginated List pattern or increase the scan limit for your DynamoDB table. However, keep in mind that increasing the scan limit can increase the time and cost of your queries, so it's important to use pagination or other optimization techniques where possible.

**Comment by justinjaeger** [comment]
Hi there, I fixed this issue by implementing GSIs wherever I was using the list operation with a filter. I see how it's much more efficient and is closer to the intended structure for DynamoDB operations. I definitely wasn't utilizing GSIs to the fullest extent.

So as a general rule for anyone encountering this post, wherever you WOULD use a "scan and filter" operation in SQL ("get all posts where userId is X"), you should be using a GSI. "List" operations are really best used with pagination like scrolling through ALL posts and lazy loading them as you scroll.

Crucially, as @rvtraveller explained, there's a default limit of 100 on any list query. And, filtering does NOT happen on the server side as with SQL. Instead, it returns all data, then filters on the client side, making any "scan and filter" operation extremely inefficient.

I definitely could have done more digging to understand this but I also think it's easy to overlook if your expectation is, as serverless architecture likes to promise, to be frontend focused. It would be great to have the Amplify docs get a little more under the hood or to link to some essential DynamoDB documentation so it's not as easy to overlook.

I'm happy to keep this closed and appreciate the help. Thanks!

**Comment by fistofzen** [comment]
Another option can be;

      do {
        const listOfItems= await client.graphql({
          query: listItems,
          variables: { 
            filter: filter,
            limit: 1000,
            nextToken: nextToken 
          }
        });
        
        const items = listOfItems.data.listItems.items;
        nextToken = listOfItems.data.listItems.nextToken;
        
        allExerciseOrders = [...listOfItems, ...items];
        
      } while (nextToken);
