### ISSUE TITLE
sync expression has no effect on model

### ISSUE THREAD

**Issue by veeramneni** [aws-amplify/amplify-category-api#1413]
### Description

**Schema:**

```graphql
type WatchUser @model @auth(rules: [{allow: owner}]) {
  pk: String! @primaryKey(sortKeyFields: ["sk"]) @index(name: "pk-index-ds")
  sk: String!
  id: ID
  userInfo: AWSJSON
}
```

**Datastore config:**

```flutter
AmplifyDataStore(modelProvider: ModelProvider.instance,
          syncExpressions: [
            DataStoreSyncExpression(WatchUser.classType, () => WatchUser.PK.eq(pk_id)),
          ],);
```

However, sync still take over 20 seconds for returning around 10 rows. Does owner based auth has anything to do with full table scan? As a result of this we are getting timeout exception on android while doing initial sync. So there are two issues here:

- sync expression seems to have no effect 
- Android is timing out while iOS seems to be retrying until full sync.

Additional context - we have around a GB of data on DataStore table, but we’re only trying to sync a few KB’s of data with owner-based auth.  When we start DataStore, it seems to do a full scan rather than using the sync expression we added.  Android is timing out and the sync is failing with a socket timeout error after a few seconds.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

0.6.12

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type WatchUser @model @auth(rules: [{allow: owner}]) {
  pk: String! @primaryKey(sortKeyFields: ["sk"]) @index(name: "pk-index-ds")
  sk: String!
  id: ID
  userInfo: AWSJSON
}
```

**Comment by chrisbonifacio** [comment]
Hi @veeramneni 👋 thanks for raising this issue.

Can you share what the outgoing request to AppSync looks like? Sync Expressions with filters that map to a GSI should be performing a Query in DynamoDB so I'm curious to see how the graphql query is being generated by DataStore.

**Comment by veeramneni** [comment]
Hi @chrisbonifacio 

Take a look at this: 
https://docs.amplify.aws/lib/datastore/sync/q/platform/flutter/#selectively-syncing-a-subset-of-your-data

"Note that selective sync is applied on top of authorization rules you’ve defined on your schema with the @auth directive."

Does this mean selective sync is applied after pulling everything based on @auth directive? In doing so, it's scanning entire table to get owner specific records and then applying index? But by this point, they are already filtered. 

The outgoing request to appsync is initiated by Datastore.start() which rebuilds sync expression based on the pk at the time of starting datastore. Let me know if you were looking for anything specific.

**Comment by chrisbonifacio** [comment]
Hi @veeramneni sorry for the confusion.

When using owner auth, only records the user has access to will be retrieved from a DynamoDB scan and the selective sync filter expression will be applied on the resulting records. So, I believe you are correct. 

In order to make the base sync perform a Query instead, the owner field has to be made a [GSI](https://docs.amplify.aws/lib/datastore/sync/q/platform/flutter/#advanced-use-case---query-instead-of-scan) and the syncExpression has to map to a query expression filtering the records by the owner field value. Have you tried adding a `@index` directive to the `owner` field on the model schema?

Lastly, I meant if you could share the mutation that DataStore generated as it would be helpful to see the input variables and filter expression.

**Comment by veeramneni** [comment]
Just gave this a try - earlier owner field was being created automatically. Now specifically included in schema like so:

type WatchUser @model @auth(rules: [{ allow: owner}]) {
  pk: String! @primaryKey(sortKeyFields: ["sk"]) @index(name: "pk-index-ds")
  sk: String!
  owner: String! @index(name: "owner-index")
  id: ID
  userInfo: AWSJSON
}

Did amplify push and it created owner-index on base table.

I now have sync expression to include owner like this. I just hardcoded owner field to keep it simple:

AmplifyDataStore(modelProvider: ModelProvider.instance,
      syncExpressions: [
        DataStoreSyncExpression(WatchUser.classType, () => WatchUser.OWNER.eq("xxxxxxxxxxx::xxxxxxxxxxx")),
      ],
    );

It still did a full scan as evident from table monitoring on AWS. Also confirmed the time it took use dev tools.

Here is the mutation on appsync. Let me know if you want to see more:

type WatchUser @aws_iam
@aws_cognito_user_pools {
	pk: String!
	sk: String!
	owner: String!
	id: ID
	userInfo: AWSJSON
        createdAt: AWSDateTime!
	updatedAt: AWSDateTime!
	_version: Int!
	_deleted: Boolean
	_lastChangedAt: AWSTimestamp!
}

type Query {
	getWatchUser(pk: String!, sk: String!): WatchUser
		@aws_iam
@aws_cognito_user_pools
	listWatchUsers(
		pk: String,
		sk: ModelStringKeyConditionInput,
		filter: ModelWatchUserFilterInput,
		limit: Int,
		nextToken: String,
		sortDirection: ModelSortDirection
	): ModelWatchUserConnection
		@aws_iam
@aws_cognito_user_pools
	syncWatchUsers(
		filter: ModelWatchUserFilterInput,
		limit: Int,
		nextToken: String,
		lastSync: AWSTimestamp
	): ModelWatchUserConnection
		@aws_iam
@aws_cognito_user_pools
}

**Comment by veeramneni** [comment]
@chrisbonifacio 

I tried using no auth and/or owner as primary key which still seem to be using scan vs query. I created dummy data and tried with sync expression on owner and/or sk. Please give this a try and you should be able to see the time it's taking for initial sync.

`type WatchUser @model {
  owner: String! @primaryKey(sortKeyFields: ["sk"]) @index(name: "owner-index")
  sk: String!
  userInfo: AWSJSON
  }`

**Comment by veeramneni** [comment]
Do you guys have any update on this? Were you able to reproduce the issue?

**Comment by veeramneni** [comment]
Will this be included in next release? Do you have a timeline?
