### ISSUE TITLE
🛑 ENOENT: no such file or directory, stat '.../schema.graphql'

### ISSUE THREAD

**Issue by rafaelfaria** [aws-amplify/amplify-category-api#1431]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.18.1

### Amplify CLI Version

16.18.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

For my schema, I organised all of them in different files, so I have users.graphql, courses.graphql, etc... I don't have a "schema.graphql".

I have just recently updated the amplify version, and I started getting the following message When I finish pushing my changes:

🛑 ENOENT: no such file or directory, open '/Users/..../myproject/amplify/backend/api/GraphQLAPI/schema.graphql'

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
🛑 ENOENT: no such file or directory, stat '/Users/..../myproject/amplify/backend/api/GraphQLAPI/schema.graphql'

### Expected behavior

I shouldn't get this message. The schema is there, just separately in different files.

### Reproduction steps

1. Create schema for your models without the default "schema.graphl"

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi @rafaelfaria and @johnf, The engineering team is actively investigating the specific #1074 issue as we have been able to reproduce it in the latest CLI version.

**Comment by rafaelfaria** [comment]
@josefaidt what does it mean "as not planned"? As in, not going to fix this?
