### ISSUE TITLE
Combine two sort keys in single query

### ISSUE THREAD

**Issue by mnikolic10** [aws-amplify/amplify-category-api#1435]
### Amplify CLI Version

10.5.2

### Question

Given the below schema:

```javascript
type GlobalCuisine implements Cuisine
  @model
  @auth(rules: [{allow: public}])
  @searchable {
  globalID: ID
    @index(name: "globalCuisinesByRank", sortKeyFields: ["rating", "type"])
  global: Global @belongsTo(fields: ["globalID"])
  id: ID!
  name: String!
  type: ItemType
  cuisineColor: String
  locations: [Float]
  allRatings: [Int]
  rating: Float @default(value: "70.00")
}
```

I'm wanting to know if it is possible to perform a query with two distinct sort keys? I know this is available via OpenSearch but wanting to see if it is achievable via DynamoDB (due to cost). I'm happy to restructure the schema to make it work if necessary.

Example query would ideally be something like

```javascript
query GlobalCuisinesOfTypeByRank {
  globalCuisinesOfTypeByRank(
    globalID: "123". 
    ratingType: {
      eq: {
        type: Dish
      },
      le: {
        ranking: 100
      }
    })
}
``` 

Let me know if this is possible or not :)

**Comment by AnilMaktala** [comment]
Hey @mnikolic10, Thanks for bringing this up. At present, we only allow a single condition for composite sort keys. You can find more information on this topic in the documentation section [here](https://docs.amplify.aws/cli/graphql/examples-and-solutions/#5-get-orders-for-a-given-customer-within-a-given-date-range).

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/3206171/235951319-8e5edc12-1c3f-4fd9-8395-5bdb8c753094.png">

**Comment by mnikolic10** [comment]
Thanks for clarifying!
