### ISSUE TITLE
Multiple sort key fields on index (GSI) breaks AppSync queries

### ISSUE THREAD

**Issue by justinjaeger** [aws-amplify/amplify-category-api#1438]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v16.15.1

### Amplify CLI Version

10.0.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

I added a global secondary index to one of my schema.graphql models. It contained two sortKeyFields `sortKeyFields: ["name", "username"]`. Noticed that the query wasn't working in AppSync when testing. No matter what inputs I used, it returned zero items. It didn't matter whether I provided the sort key fields or not.

I eliminated the second field in my GSI (`sortKeyFields: ["name"]`) and now it works as it's supposed to. Therefore the problem is related to there being multiple fields passed to "sortKeyFields".

This is happening with every index in my schema.graphql that uses multiple sort key fields. 

Example below:

`
BREAKS:
eventId: ID! @index(name: "getEntry", sortKeyFields: ["movieId", "personId", "songId"], queryField: "getEntry")
WORKS:
eventId: ID! @index(name: "getEntry", sortKeyFields: ["movieId"], queryField: "getEntry")

`

### Expected behavior

When using multiple sort key fields, it shouldn't break the query

### Reproduction steps

Using any model in schema.graphql:
Create a GSI with one sortKeyFields
Create a GSI with two sortKeyFields
Test each in AppSync

### Project Identifier

b8d65120b18181dc43f4d8a2ad24c4f7

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi @justinjaeger, Could you please let us know whether backfill indexes resolved your issue?

**Comment by AnilMaktala** [comment]
Hi @justinjaeger 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment. This way, we can reopen the issue and provide you with better assistance.

Thank you!
