### ISSUE TITLE
Failed to grant access a DynamoDB table to api container

### ISSUE THREAD

**Issue by fossamagna** [aws-amplify/amplify-category-api#1445]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.15.0

### Amplify CLI Version

11.1.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

An error occurs when I follow the steps to grant access to DynamoDB following the instructions written at https://docs.amplify.aws/cli/usage/containers/#getting-started by running `amplify add api`. No access rights are granted.

### Expected behavior

That `amplify add api` will give the container access to DynamoDB.

### Reproduction steps

<img width="882" alt="スクリーンショット 2023-05-06 23 42 42" src="https://user-images.githubusercontent.com/1638848/236632098-45e418e1-8a90-4d6b-ac2e-5a3b572d31b3.png">

### Project Identifier

Project Identifier: a2b1a21124c9682206af329de433af89

### Log output

<details>

```
🛑 There was an error adding the API resource
🛑 statement.freeze is not a function
```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @fossamagna :wave: thanks for raising this! I was able to reproduce this during the `add` flow:

```
➜  amplify add api
? Select from one of the below mentioned services: REST
? Which service would you like to use API Gateway + AWS Fargate (Container-based)
? Provide a friendly name for your resource to be used as a label for this category in th
e project: container29f1a8b8
? What image would you like to use ExpressJS - REST template
? When do you want to build & deploy the Fargate task On every "amplify push" (Fully mana
ged container source)
? Do you want to access other resources in this project from your api? Yes
? Select the categories you want this function to have access to. storage
? Select the operations you want to permit on dynamo84adf994 create, read, update, delete



You can access the following resource attributes as environment variables from your Lambda function
        STORAGE_DYNAMO84ADF994_ARN
        STORAGE_DYNAMO84ADF994_NAME
        STORAGE_DYNAMO84ADF994_STREAMARN
? Do you want to restrict API access No
🛑 There was an error adding the API resource
🛑 statement.freeze is not a function
```

Marking as a bug 🙂 

As a workaround, I was able to grant access to a storage resource in `amplify update api`:

```
➜  amplify update api
? Select from one of the below mentioned services: REST
✅ Successfully updated resource
? Please select the API you would want to update container32aaa072
? Do you want to access other resources in this project from your api? Yes
? Select the categories you want this function to have access to. storage
? Select the operations you want to permit on dynamo84adf994 create, read, update, delete



You can access the following resource attributes as environment variables from your Lambda function
        STORAGE_DYNAMO84ADF994_ARN
        STORAGE_DYNAMO84ADF994_NAME
        STORAGE_DYNAMO84ADF994_STREAMARN
? Do you want to restrict API access No
```

**Comment by fossamagna** [comment]
@josefaidt 
Thank you for your reply. I tried a workaround. But an error occurs when run `amplify push`.
<img width="829" alt="スクリーンショット 2023-05-26 15 55 46" src="https://github.com/aws-amplify/amplify-category-api/assets/1638848/0a5ea39e-34fe-4188-b5e0-8270dc11a3d7">

**Comment by zandieh** [comment]
I also have pretty much the same error. my case is a graphql api and I get following error with rebuild command:

amplify version: 12.0.1

```
$ amplify api rebuild
⚠️ This will recreate all tables backing models in your GraphQL API paymenthub.
⚠️ ALL EXISTING DATA IN THESE TABLES WILL BE LOST.
✔ Type the name of the API to confirm you want to continue · paymenthub
🛑 statement.freeze is not a function
```

**Comment by alastairayliffe** [comment]
Hi, i also have this is issue (when trying the work around). thanks

**Comment by alastairayliffe** [comment]
Hey, the following worked for me (while Amplify sort the issue)... 

1) create a lambda in amplify and add access to the other resources needed, so details can be accessed via process.env within the lambda.
2) update the custom-policies in the container to be able to access this lambda (either directly or via api) and along with any other services (dynambo db etc).
3) call the lambda within the container and have it send back the process.env variables needed.

Happy to provide more details if needed.

Thanks,

**Comment by alastairayliffe** [comment]
Has this now been fixed? thanks :)
