### ISSUE TITLE
error on push: "extraneous key [body] is not permitted"

### ISSUE THREAD

**Issue by alexhouse** [aws-amplify/amplify-category-api#1455]
### How did you install the Amplify CLI?

npm install --global

### If applicable, what version of Node.js are you using?

16.20.0

### Amplify CLI Version

12.0.0

### What operating system are you using?

Mac 13.3.1

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

After upgrading Amplify (from version 10.x.x) I've been unable to push any changes to any category or environment due to the following error;

```
🛑 The following resources failed to deploy:
Resource Name: restApi (AWS::ApiGateway::RestApi)
Event Type: update
Reason: Properties validation failed for resource restApi with message:
#: extraneous key [body] is not permitted
URL: https://console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks/[stackid]/events


🛑 Resource is not in the state stackUpdateComplete
Name: restApi (AWS::ApiGateway::RestApi), Event Type: update, Reason: Properties validation failed for resource restApi with message:
#: extraneous key [body] is not permitted
```

In my `amplify/backend/api/restApi/build/restApi-cloudformation-template.json` I can see a property called `"body"` (lowercase) which I assume should be `"Body"`..? I've tried updating the property name to `"Body"` before confirming the amplify push command, but it seems like this isn't the only place it gets generated before uploading to CloudFormation as it still errors out 😦 I've tried downgrading @aws-amplify/cli but end up with various other errors as a result.

Running `amplify pull -y` and then `amplify push -y` also errors, bizarrely, and I'm just falling into madness attempting to work out what's going on. Any ideas massively appreciated!

### Expected behavior

Amplify push should update successfully

### Reproduction steps

I've not been able to reproduce this using a new project, nor do I know explicitly what's caused it in my own... It only started appearing after upgrading Amplify CLI.

I've tried the following;
* `amplify pull` the current environment, then immediately `amplify push` without making any changes (no change, process exits)
* Modifying `schema.graphql` only and running a push; restApi still fails
* `amplify init` in a new directory, followed by a pull, changing a file in a standalone function and running a push; restApi fails
* Various combinations of pulls, pushes, category changes and updates

### Project Identifier

305d9e06dc750149c600d79902d2f146

### Log output

<details>

```
Deploying api restApi [ ---------------------------------------- ] 0/17
	restApi                   AWS::ApiGateway::RestApi       UPDATE_FAILED                  Fri May 12 2023 13:11:00…

[...snip...]

🛑 The following resources failed to deploy:
Resource Name: restApi (AWS::ApiGateway::RestApi)
Event Type: update
Reason: Properties validation failed for resource restApi with message:
#: extraneous key [body] is not permitted
URL: https://console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks/[snip]/events


🛑 Resource is not in the state stackUpdateComplete
Name: restApi (AWS::ApiGateway::RestApi), Event Type: update, Reason: Properties validation failed for resource restApi with message:
#: extraneous key [body] is not permitted, IsCustomResource: false


Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: e8794f96-4b27-4999-b989-5f2095aee7dc
```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi @alexhouse, Thank you raising this. Do you have any overrides configured for the REST API and also can you please run the diff on cli-inputs.json file and let us know if you see any changes.
