### ISSUE TITLE
Data destroyed when changing model locally to add a field to a model and then pushing schema to aws

### ISSUE THREAD

**Issue by nithianandan90** [aws-amplify/amplify-category-api#1471]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1gaqy4ft4hhov

### Region

us-east-2

### Environment name

chat-app

### Amplify CLI Version

11.1.0

### What operating system are you using?

Windows

### Describe the bug

I add a field to the model User locally as below:

```graphql
type User @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String
  username: String
  email: AWSEmail
  telephone: AWSPhone
  status: String
  image: Attachment @hasOne
  ChatRooms: [ChatRoom] @manyToMany(relationName: "UserChatRoom")
  userType: UserType
  taskID: ID @index(name: "byTask")
  propertiesID: ID @index(name: "byProperties")
  notificationsID: ID @index(name: "byNotifications")
}
```

And then I run amplify push, other model's one to many relationship data gets destroyed. (even though I am not adding flag --allow-destructive-graphql-schema-updates to amplify push)

For example, Properties model has many Users. Once I run amplify push after making change to User model, the Users in all the Properties data gets destroyed.

```graphql
type Properties @model @auth(rules: [{allow: public}]) {
  id: ID!
  title: String!
  streetAddress: String!
  postcode: Int!
  city: String!
  state: String!
  headerPic: String
  type: String!
  physicalAccess: String!
  status: String!
  Users: [User] @hasMany(indexName: "byProperties", fields: ["id"])
  Tasks: [Task] @hasMany(indexName: "byProperties", fields: ["id"])
  Attachments: [Attachment] @hasMany(indexName: "byTask", fields: ["id"])
}
```

### Expected behavior

Data should not get destroyed

### Reproduction steps

1. Make change to a certain model locally
2. Run amplify push (without allowing destructive updates)
3. One-to-many relationship between another model and the changed model gets destroyed

**Comment by AnilMaktala** [comment]
Hi @nithianandan90👋 , Thanks for raising this issue.We are working on reproducing the issue. Could you please run below command and send us the report `amplify diagnose --send-report`. 
please refer [here](https://docs.amplify.aws/cli/reference/diagnose/) for more info on diagnose

**Comment by AnilMaktala** [comment]
Hey @nithianandan90, We have attempted to replicate the issue by following the steps provided in the description, but we were unsuccessful. To further investigate the matter, could you please share the diagnostic report with us? 

Here are the steps we followed:

1. Initialized Amplify by running amplify init.
2. Added an API using the provided schema:

 ``` javascript 
  type User @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String
  username: String
  email: AWSEmail
  telephone: AWSPhone
  status: String
  ChatRooms: [ChatRoom] @manyToMany(relationName: "UserChatRoom")
  userType: UserType
  propertiesID: ID @index(name: "byProperties")
  notificationsID: ID @index(name: "byNotifications")

}
type Properties @model @auth(rules: [{allow: public}]) {
  id: ID!
  title: String!
  streetAddress: String!
  postcode: Int!
  city: String!
  state: String!
  headerPic: String
  type: String!
  physicalAccess: String!
  status: String!
  Users: [User] @hasMany(indexName: "byProperties", fields: ["id"])
  Tasks: [Task] @hasMany(indexName: "byProperties", fields: ["id"])

}

enum UserType{
user
admin
}

type Task @model @auth(rules: [{allow: public}]){
id: ID!
name: String
propertiesID:ID! @index(name: "byProperties", sortKeyFields: ["id"])
properties: Properties @belongsTo(fields: ["propertiesID"])

}

type ChatRoom @model @auth(rules:[{allow:public}]){
id:ID!
name:String
Users: [User] @manyToMany(relationName: "UserChatRoom")
} 
```

3. Added data to the tables using the AppSync console.
4. Modified the User model by adding a new property and ran amplify push:

```javascript
type User @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String
  username: String
  email: AWSEmail
  telephone: AWSPhone
  status: String
  ChatRooms: [ChatRoom] @manyToMany(relationName: "UserChatRoom")
  userType: UserType
  taskID: ID @index(name: "byTask")
  propertiesID: ID @index(name: "byProperties")
  notificationsID: ID @index(name: "byNotifications")
}
```
5. it was noticed that the previously existing data still persists in the tables.

**Comment by nithianandan90** [comment]
I have sent the diagnostic report

Project identifier: e6e119f1430f5b635ab6d62f89a67444

**Comment by nithianandan90** [comment]
Hi @AnilMaktala I noticed that the data isnt destroyed when I update the schema of the table. It is still accessible via my API.graphql calls. However, the AWS Amplify interface shows that there is not data. See attached image

![image](https://github.com/aws-amplify/amplify-category-api/assets/4743418/726ed69c-18f5-451a-bcea-6a85331d71dd)

**Comment by nithianandan90** [comment]
However, via the API.graphql calls, the added property 'PushToken' does not show up

**Comment by AnilMaktala** [comment]
Hi @nithianandan90, Thank you for providing further details. Based on the screenshot, it seems that you are currently performing the verification in the staging environment. To ensure accuracy, could you please confirm that you are making the changes in the staging environment?

**Comment by AnilMaktala** [comment]
Hey @nithianandan90, Are you still experiencing this issue?  if yes, could you please confirm that you are making and verifying the changes in the staging environment?

**Comment by AnilMaktala** [comment]
Hi 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment and provide us with the information our team had previously asked for. This way, we can reopen the issue and provide you with better assistance.

Thank you!
