### ISSUE TITLE
@Searchable with nested filters

### ISSUE THREAD

**Issue by hackmajoris** [aws-amplify/amplify-category-api#1473]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16*

### Amplify CLI Version

11.0.3

### What operating system are you using?

linux

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

Nested filtering within @Searchable query returns  an empty array.

### Expected behavior

Nested filters are taken in consideration and aggregated data is returned.

### Reproduction steps

Schema

```JS
type User @searchable
  {
      id: ID!     
      country: String!
      firstName: String!
  }
```

Example

**Filtering data by 'GB' country** returns expected data.
![Screenshot 2023-05-16 at 17 06 43](https://github.com/aws-amplify/amplify-cli/assets/3758212/0e3e79a0-de99-47b9-ac4d-5704cc452430)

**Filtering data by 'RO' country** returns expected data.
![Screenshot 2023-05-16 at 17 07 06](https://github.com/aws-amplify/amplify-cli/assets/3758212/9ea3c219-754c-420f-9e33-eb7374e41537)

**Filtering data by  both 'GB'  and 'RO' countries** returns unexpected empty array.
![Screenshot 2023-05-16 at 17 07 26](https://github.com/aws-amplify/amplify-cli/assets/3758212/4b15dfc3-f7f4-41c5-99c7-d0917c12e4af)

### Log output

<details>

```
# No logs


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi @hackmajoris, Thank you for bringing this up. Kindly adjust the query as demonstrated below in order to retrieve users from two countries.
```
query MyQuery {
  searchUsers(filter: {or: [{country: {eq: "USA"}},{country: {eq: "UK"}}]}) {
    items {
      firstName
      createdAt
      id
      country
    }
  }
}
```
<img width="983" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/22c58d63-3335-41f4-8e97-a0724442def0">
