### ISSUE TITLE
Using Existing OpenSearch Cluster w/Escape Hatches?

### ISSUE THREAD

**Issue by 24601** [aws-amplify/amplify-category-api#1493]
### Amplify CLI Version

12.0.0

### Question

Before we venture out to try it/experiment, is there any official word (or even unofficial word/anecdotes) on using the escape hatches/overrides to point the @searchable directive to an existing OpenSearch instance (e.g. using methods described in here https://docs.amplify.aws/cli/graphql/override/#customize-amplify-generated-resources-for-searchable-opensearch-directive).

I ask because we have multi-year commits on an existing instance (which are not applicable to new instances, just this reservation) that we'd like to use that are non-trivial in terms of financial value...and this would replace the workload that those are running now.

Bringing up new, small OS clusters for dev/staging is fine, but for production, at scale, pointing to our existing "paid-for" OS cluster is critical to make the business case work here, and I can't envision a technical reason that this cluster cannot be reused (amplify/appsync will have exclusive use of it), but AWS' business rules tie the commit to the cluster, not "X amount of spend on OS".

**Comment by AnilMaktala** [comment]
Hi @24601, Thank you for raising this. Unfortunately, The current functionality does not support the utilization of the existing search instance at this time.
