### ISSUE TITLE
Owner field never populated

### ISSUE THREAD

**Issue by Meerkov** [aws-amplify/amplify-category-api#1498]
### Amplify CLI Version

Newest

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Describe the bug

Create this schema (with or without "owner" field)
```js
type Todo @model @auth(rules: [{allow: public, operations: [read]}, {allow: owner}]) {
  id: ID!
  name: String!
  description: String
  owner: String
}
```

BUGS:
1) you are unable to create TODOs (no permission)
`{"data":{"createTodo":null},"errors":[{"path":["createTodo"],"data":null,"errorType":"Unauthorized","errorInfo":null,"locations":[{"line":2,"column":3,"sourceName":null}],"message":"Not Authorized to access createTodo on type Mutation"}]}`
2) You are unable to delete TODOs that you previously created (no permission)

Check the database:
```js
{
  "data": {
    "getTodo": {
      "owner": null,
      "id": "4590946a-bdf9-4a63-aa93-385db89e81a1",
      "description": "5",
      "name": "5"
    }
  }
}
```

Notice that the owner field is NULL.

Change to this schema:
```js
type Todo @model @auth(rules: [{allow: public, operations: [create, read]}, {allow: owner}]) {
  id: ID!
  name: String!
  description: String
  owner: String!
}
```

BUGS:
3) You are unable to create TODOs (owner is null)
`{"data":null,"errors":[{"path":null,"locations":[{"line":1,"column":21,"sourceName":null}],"message":"Variable 'input' has coerced Null value for NonNull type 'String!'"}]}`
4) Unable to delete TODOs (owner is null)
etc etc.

The owner field will not fill in, no matter how you change the schema. Since there is no owner, you can't use owner auth.

### Expected behavior

The owner field would be populated.

### Reproduction steps

See above

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by Meerkov** [comment]
This is using Federated login with Google, if that matters. I'm guessing it does.

**Comment by AnilMaktala** [comment]
Hi @Meerkov👋, Thanks for raising this issue. We are working on reproducing the issue. Could you please run below command and send us the report `amplify diagnose --send-report`. 
Please refer [here](https://docs.amplify.aws/cli/reference/diagnose/)

**Comment by Meerkov** [comment]
Done, project ID c4878930dffc2e3668cebac77bb8bff9

**Comment by AnilMaktala** [comment]
Hey @Meerkov, We appreciate your prompt response and for providing the diagnosis report. We will thoroughly investigate the matter and keep you informed of our findings.

**Comment by Meerkov** [comment]
[files.zip](https://github.com/aws-amplify/amplify-category-api/files/11545026/files.zip)
Here's the relevant project files. It's basically just the result after the tutorial, except I followed a variation of the tutorial from a 3P for some steps.

**Comment by chrisbonifacio** [comment]
@Meerkov thank you for sharing!

Taking a look at your aws-exports file, it seems you only have API_KEY as an authentication type.

I would recommend running the command `amplify update api` > GraphQL > Update authorization modes and from there select API KEY again but also make sure to say `yes` to `add additional authorization modes` and select Cognito User Pools. Then make sure run `amplify push`.

When the push finishes, your aws-exports file should be updated with the additional auth mode.

Finally,in your front end code make sure that the user is authenticated and pass an `authMode` to the API.graphql call like so:

```js
API.graphql({
  query: createTodo,
  variables: {
    input: {
      //...data
    }
  },
  authMode: "AMAZON_COGNITO_USER_POOLS"    
})
```

**Comment by Meerkov** [comment]
Why do I need to do that? That isn't in the tutorial. https://docs.amplify.aws/start/getting-started/auth/q/integration/react/#add-the-amplify-ui-authenticator-component

Can I just remove the API key Auth mode?

**Comment by Meerkov** [comment]
Deleting the schema which allowed public read, and then using `amplify update api` to set the only API auth mode to Cognito, and then `push` and commiting worked.

I'm not sure why the default auth would be API key. That needs to be added to the tutorial. Currently, the auth tutorial obfuscates this security flaw, because it seems to imply that the logged in user would have objects attributed to them. But seemingly, it doesn't without further modification.
