### ISSUE TITLE
Unable to Access Amplify API-Generated Table via AppSync

### ISSUE THREAD

**Issue by ianfmc** [aws-amplify/amplify-category-api#1499]
### Amplify CLI Version

12.0.0

### Question

Hello:

**TL;DR: how can I troubleshoot access to and API-generated table**

I'm currently unable to access a table that I created using an API category. I created the category, which in turn created an auth category. I selected the option to use Cognito User Pools for authentication. The table is defined as below in the schema.graphql file

```
type Event @model @auth(rules: [{ allow: public }]){
  id: ID!
  company: ID
  body: String
  start: String 
  end: String
  item: String
  item_id: String
  status: String
}
```
When I try to use the AppSync console to see the data in the Event Table, I get the following error:
```
{
  "data": {
    "listEvents": null
  },
  "errors": [
    {
      "path": [
        "listEvents"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access listEvents on type Query"
    }
  ]
}
```
Please advise. Thanks!

**Comment by ianfmc** [comment]
OK...little bit of an update. 

I used the API key option in the AppSync Console, and can see all of the data returned by the query. My follow-on question is why do I have to use the API key, and how would I use that in my front-end application? The generated queries all assume the use of the Cognito User pool. Finally, does this change if I use 'private' instead of 'public'?

**Comment by AnilMaktala** [comment]
Hi @desert-digital, Thank you for confirming. For more information on authentication, please refer to the relevant section in the documentation, which can be found [here](https://docs.amplify.aws/cli/graphql/authorization-rules/).
