### ISSUE TITLE
Not able to give separate permissions to queries that call lambdas

### ISSUE THREAD

**Issue by mguja-fcc** [aws-amplify/amplify-category-api#150]
Not able to give separate permissions to queries that call lambdas. For example, I have two queries and want to give separate permissions to. Query `invokeLambda`  any logged in user should get access to but access to `invokeGetGroups` should be access only by Admins group. How can I accomplish this ? Now only `Admins` group gets access to both queries.

```
type Query {
  invokeLambda: String @function(name: "pythonLambda-${env}") 
  invokeGetGroups: String @function(name: "getGroups-${env}")
  @auth(
      rules: [
        { allow: groups, groups: ["Admins"] }
        ])
}
```

Amplify CLI version: 6.2.1

**Comment by josefaidt** [comment]
Closing due to age, @mguja-fcc if you are still experiencing this issue please reply back to this thread and we can re-open to investigate further 🙂
