### ISSUE TITLE
Deployment error when changing DynamoDB model and force --allow-destructive-graphql-schema-updates

### ISSUE THREAD

**Issue by Rafael-Gomez-Hernando** [aws-amplify/amplify-category-api#1536]
After make a change on the DynamoDB model by adding a sort key:

type Vote @model {  
  id: ID! @primaryKey(**sortKeyFields: ["owner"]**) 
  rating: Int!
  owner: String!
}

I pushed the changes using the following recommended command : 
_amplify publish --allow-destructive-graphql-schema-updates_

And I always receive this error:

_["Index: 1 State: {\"deploy\":\"waitingForDeployment\"} Message: Resource is not in the state stackUpdateComplete","Index: 0 State: {\"rollback\":\"waitingForRollback\"} Message: Resource is not in the state stackUpdateComplete"]_

Once I got it is impossible deploy de environment again and I need to create a new environment an redeploy it again on the new env.

**Comment by AnilMaktala** [comment]
Hey @Rafael-Gomez-Hernando, Thank you for bringing this to our attention. A similar issue has already been reported and can be found at [this link](https://github.com/aws-amplify/amplify-category-api/issues/940). We recommend subscribing to that link for future updates regarding this issue.
Additionally, we suggest trying the workaround provided [here](https://github.com/aws-amplify/amplify-category-api/issues/92#issuecomment-1555861411) and informing us if it resolves the issue you're facing.

**Comment by AnilMaktala** [comment]
This issue is being closed. For future updates, please subscribe to #940.
