### ISSUE TITLE
@index with multiple sorkeys not filling

### ISSUE THREAD

**Issue by Dennis-Dekker** [aws-amplify/amplify-category-api#1551]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16

### Amplify CLI Version

11.1.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

When creating a new index on an existing model, the GSI created does not backfill and new entries are also not filled. We didn't investigate the issue fully, but it seems to be related to the type of fields being used for making the GSI. For example, we have indexes that work correctly on primary and sort keys of fields with String type, and indexes that use multiple sort keys that have different types (string and int). We are now trying to make an index using a string and AWSDateTime type as sort keys. This index does not get backfilled and new entries are not filled in this index. As said, we suspect the clause of this problem to be the AWSDateTime in combination with the String type, however, we have another model that does use an AWSDateTime (createdAt) as a sort key. Another point this could be related to is that the model field in the schema is not required in this model (in the other model this is required). Something to note, the model field is new in this History model, so the vast amount of entries in this table does not have this field (but the recent ones do). See the schema of the problematic model below, the index that is not filling is called "ByModelAndTimestamp":

```
type History @model @auth(rules: [{ allow: private, provider: iam }, { allow: private }]) {
  id: ID
  organisationId: String!
    @primaryKey(sortKeyFields: ["refId", "timestamp"])
    @index(name: "ByModelAndTimestamp", sortKeyFields: ["model", "timestamp"],queryField: "HistoryByModelAndTimestamp")
  refId: String! @index(name: "ByRefId", sortKeyFields: ["organisationId"], queryField: "HistoryByRefId")
  timestamp: AWSDateTime!
  fullJSON: String!
  newData: String
  oldData: String
  eventType: String!
  model: String
  diffContainingOldValue: String
  userId: String!
  itemIdRef: String @index(name: "ByItemIdRef", queryField: "HistoryByItemIdRef")
  locationIdRef: String
  orderIdRef: String
  transactionId: String
}
```

### Expected behavior

We expected the index to be backfilled with some recent entries and filled with newly created entries.

### Reproduction steps

1. Deploy the schema
2. Wait for DDB to create the schema
3. Add some entries
4. Check the index in the DDB console

### Project Identifier

63481edb2161f5e855c34c6596619527

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

We tried to build the index in the DDB console, however, we were not able to do this as we were not allowed to build an index with multiple indexes (as # was not allowed, but maybe this is not the correct way to do this).

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by nadetastic** [comment]
Hi @Dennis-Dekker thank you for opening this issue.

To confirm are you seeing that your newly created items after creating the index key are not working?

Also, please note that for existing items, you would need to update/backfill them with the appropriate values.

**Comment by Dennis-Dekker** [comment]
Hi @nadetastic,

Thank you for reaching out. What you describe is indeed what is happening. I started backfilling the table's index when the entries did not have the model field, so the expected result was that the index would be empty. However, when we started using the new model field, the index was not filling. The first thing I then tried was to recreate the index, and at that time some of the earlier created entries did have the model field filled. As described the second backfilling did not take in these new entries or entries created/modified after the backfilling was complete.

**Comment by nadetastic** [comment]
@Dennis-Dekker I see, did you try back filling through DynamoDB directly, or did you perform a mutation through the API?

**Comment by Dennis-Dekker** [comment]
@nadetastic I have created the index from both the amplify CLI (by defining it in the schema) and the dynamodb console (manually), but the backfilling with both options does not seem to work. I have just tried your suggestion, and I now have an entry on the index. I found that the appsync query now generates a new field, model#timestamp. I did not specify this field when creating the entry, so it seems to be added automatically. It this normal behaviour? This would mean that in order to backfill the index, I have to go through the whole table and add this field to every entry. Both model and timestamp fields are available for only some of the entries, so we would prefer not to do this.

**Comment by nadetastic** [comment]
@Dennis-Dekker Thanks for the clarification. The steps to update the schema as you mentioned are correct. Running `amplify push` should update the DynamoDB table fields but not backfill with the values.

However, as you mentioned the `model#timestamp` field values will be empty on all previous items. In order to backfill, the recommendation is to run an UpdateMutation on the existing items and making sure that you include the values for `model` and `timestamp` as well as all other required fields.

```gql
mutation MyMutation {
  updateHistory (input: {
  		...
  		timeStamp: "<value>",
  		model: "<value>"
		...
  }) {
    id
    ...
  }
}
```
This will make sure that the `model#timestamp` field is updated/backfilled with the necessary value.

**Comment by Dennis-Dekker** [comment]
@nadetastic Thank you for your time, this clarifies the problem. I still have some questions regarding this issue. Does this backfilling always have to be performed manually if you make an index using multiple index keys? Also, whenever we create a new index we have to wait a long time for the backfilling to complete. Knowing that, in the case of multiple index keys, this will not result in any filled fields, is there a way to skip the backfilling?

**Comment by nadetastic** [comment]
@Dennis-Dekker glad to be of help!

Regarding your additional questions:
- Currently, the backfilling does need to be done manually, if you update an existing model with a new index with multiple index keys.
- Ideally, you should not skip the backfill of models updated with a new index, especially in cases of required fields/index keys. Without the backfill, you may encounter errors with your queries along the lines of `Cannot return null for non-nullable type` - which is essentially a complaint that a field with an expected value was empty

**Comment by nadetastic** [comment]
@Dennis-Dekker following up here - let me know if you have any more questions. If not, I'll go ahead and close out this issue. Thanks!

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
