### ISSUE TITLE
AWS Amplify Deployment Get Stuck for a very long time

### ISSUE THREAD

**Issue by kiostudio** [aws-amplify/amplify-category-api#1552]
### Amplify CLI Version

12.0.0

### What operating system are you using?

Max OS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Merge dev environment into prod environment and  get stuck after deployment.

### Describe the bug

Merge dev environment into prod environment and  get stuck after deployment.

### Expected behavior

Merge dev environment into prod environment and  get stuck after deployment.

### Reproduction steps

1. amplify push

### Project Identifier

fc6dc4e9ea053ce09153b3b82155928c

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hello @kiostudio, Thank you for bringing this up. Are you currently trying to delete the existing table? Additionally, could you provide details about the changes you made in the schema?

**Comment by AnilMaktala** [comment]
Hey @kiostudio, Thank you for providing additional information. I noticed that the Machine model is currently commented out. Could you please try again after uncommenting it in the schema?

```
# type Machine @model {
#   id: ID!
#   uuid: ID! @index(name: "getMachineByUUID",  queryField: "getMachineByUUID")
#   osInfo: AWSJSON
#   status: String! @index(name: "getMachineByStatus", queryField: "getMachineByStatus")
#   tasks: [Task] @hasMany
# }

```

**Comment by kiostudio** [comment]
I have tried, but it didn't work.
There will be an error showing that the resources has been in
DELETE_COMPLETED State and as a result it cannot be updated.

**Comment by AnilMaktala** [comment]
Hey @kiostudio, Could you please provide me the schema file from the S3 deployment bucket?

**Comment by kiostudio** [comment]
> 

Thanks fro the reply again.

This is the schema file that I found in the production S3 bucket.
![Screenshot 2023-06-10 at 5 25 50 PM](https://github.com/aws-amplify/amplify-category-api/assets/63901064/89bbbcac-88ad-4da6-8fec-45aa84276220)
[](url)
`# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type Profile @model {
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  userId: ID @index(name: "getProfileByUserId",  queryField: "getProfileByUserId")
  email: String @index(name: "getProfileByEmail", queryField: "getProfileByEmail")
  phone: String @index(name: "getProfileByPhone", sortKeyFields:["createdAt"], queryField: "getProfileByPhone")
  data: AWSJSON
  settings: AWSJSON
  oauth: AWSJSON
  tgId: String @index(name: "getProfileByTgId", sortKeyFields:["createdAt"], queryField: "getProfileByTgId")
  servants: [Servant] @hasMany
  conversations: [Conversation] @manyToMany(relationName: "ProfileConversation")
  stripeId: String
}

type Job @model {
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  title: String
  status: String!
  type: String!
  cronInterval: String! @index(name: "getJobByCronInterval", queryField: "getJobByCronInterval")
  profileId: ID @index(name: "getJobByProfileId", sortKeyFields:["createdAt"], queryField: "getJobByProfileId")
  tasks: [Task] @hasMany
  input: AWSJSON
  config: AWSJSON
  workflow: Workflow @belongsTo
  resources: [Resource] @manyToMany(relationName: "JobResource")
  mockUpTemplate: [MockUpTemplate] @manyToMany(relationName: "JobMockUpTemplate")
}

type Task @model {
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  status: String
  runtime: String
  request: AWSJSON
  response: AWSJSON
  retry: AWSJSON
  jobTasksId: ID @index(name: "getTaskByJobTasksId", sortKeyFields:["createdAt"], queryField: "getTaskByJobTasksId")
  servantTasksId: ID @index(name: "getTaskByServantTasksId", sortKeyFields:["createdAt"], queryField: "getTaskByServantTasksId")
  machineTasksId: ID @index(name: "getTaskByMachineTasksId", sortKeyFields:["createdAt"], queryField: "getTaskByMachineTasksId")
  job: Job @belongsTo
  servant: Servant @belongsTo
  machine: Machine @belongsTo
  triggerBy: [TaskTrigger] @hasMany
  triggerTo: [TaskTrigger] @hasMany
}

type TaskTrigger @model {
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  triggerById: ID! @index(name: "getTaskTriggerRecordByTriggerById", queryField: "getTaskTriggerRecordByTriggerById")
  triggerBy: Task @belongsTo(fields: ["triggerById"])
  triggerToId: ID! @index(name: "getTaskTriggerRecordByTriggerToId")
  triggerTo: Task @belongsTo(fields: ["triggerToId"])
}

type Servant @model {
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  profileServantsId: ID @index(name: "getServantByProfileServantsId", sortKeyFields:["createdAt"], queryField: "getServantByProfileServantsId")
  title: String
  status: String!
  config: AWSJSON
  tgBotTokenPrefix: String @index(name: "getServantByTgBotTokenPrefix", queryField: "getServantByTgBotTokenPrefix")
  whatsAppPhoneId: String @index(name: "getServantByWhatsAppPhoneId", queryField: "getServantByWhatsAppPhoneId")
  conversations: [Conversation] @hasMany
  tasks: [Task] @hasMany
  profile: Profile @belongsTo
  workflow: Workflow @belongsTo
}

type Conversation @model {
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  config: AWSJSON
  servant: Servant @belongsTo
  servantConversationsId: ID @index(name: "getConversationByServantConversationsId", sortKeyFields:["createdAt"], queryField: "getConversationByServantConversationsId")
  profiles: [Profile] @manyToMany(relationName: "ProfileConversation")
  tgChatId: String @index(name: "getConversationByTgChatId", sortKeyFields:["createdAt"], queryField: "getConversationByTgChatId")
  whatsAppPhoneNum: String @index(name: "getConversationByWhatsAppPhoneNum", sortKeyFields:["createdAt"], queryField: "getConversationByWhatsAppPhoneNum")
}

type Workflow @model {
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  config: AWSJSON
  metadata: AWSJSON
  permission: String!
  profileId: ID @index(name: "getWorkflowByProfileId", sortKeyFields:["createdAt"], queryField: "getWorkflowByProfileId")
  jobs: [Job] @hasMany
  servants: [Servant] @hasMany
}

type Resource @model{
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  platform: String @index(name: "getResourceByPlatform", sortKeyFields:["createdAt"], queryField: "getResourceByPlatform")
  externalId: String @index(name: "getResourceByExternalId", sortKeyFields:["createdAt"], queryField: "getResourceByExternalId")
  metadata: AWSJSON
  credentials: AWSJSON
  statistic: AWSJSON
  profileId: ID @index(name: "getResourceByProfileId", sortKeyFields:["createdAt"], queryField: "getResourceByProfileId")
  jobs: [Job] @manyToMany(relationName: "JobResource")
}

type MockUpTemplate @model {
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  name: String!
  config: AWSJSON
  origin: AWSJSON
  thumbnail: AWSJSON
  jobs: [Job] @manyToMany(relationName: "JobMockUpTemplate")
}

type Logging @model{
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  taskId: ID @index(name: "getLoggingByTaskId", sortKeyFields:["createdAt"], queryField: "getLoggingByTaskId")
  workflowId: ID @index(name: "getLoggingByWorkflowId", sortKeyFields:["createdAt"], queryField: "getLoggingByWorkflowId")
  nodeId: ID @index(name: "getLoggingByNodeId", sortKeyFields:["createdAt"], queryField: "getLoggingByNodeId")
  billingId: ID @index(name: "getLoggingByBillingId", sortKeyFields:["createdAt"], queryField: "getLoggingByBillingId")
  type: String
  data: AWSJSON
}

type Billing @model{
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  type: String
  profileId: ID @index(name: "getBillingByProfileId", sortKeyFields:["createdAt"], queryField: "getBillingByProfileId")
  stripeId: String @index(name: "getBillingByStripeId", queryField: "getBillingByStripeId")
  status: String! @index(name: "getBillingByStatus", queryField: "getBillingByStatus")
  breakdown: AWSJSON
  total: String
}

type Machine @model {
  id: ID!
  uuid: ID! @index(name: "getMachineByUUID",  queryField: "getMachineByUUID")
  osInfo: AWSJSON
  status: String! @index(name: "getMachineByStatus", queryField: "getMachineByStatus")
  tasks: [Task] @hasMany
}

type Query {
  ieGoogleOAuth(params: String): String @function(name: "ieGoogleOAuth-${env}")
  ieGoogleRevokeOAuth(params: String): String @function(name: "ieGoogleRevokeOAuth-${env}")
  ieGoogleSheetAction(params: String): String @function(name: "ieGoogleSheetAction-${env}")
  ieServantDeleteMemory(params: String): String @function(name: "ieServantDeleteMemory-${env}")
  ieTwitterOAuth(params: String): String @function(name: "ieTwitterOAuth-${env}")
  ieTwitterRevokeOAuth(params: String): String @function(name: "ieTwitterRevokeOAuth-${env}")
  iePinterestOAuth(params: String): String @function(name: "iePinterestOAuth-${env}")
  iePinterestRevokeOAuth(params: String): String @function(name: "iePinterestRevokeOAuth-${env}")
  ieStripeSetup(params: String): String @function(name: "ieStripeSetup-${env}")
  ieStripeDeleteCard(params: String): String @function(name: "ieStripeDeleteCard-${env}")
  ieServantBrowser(params: String): String @function(name: "ieServantBrowser-${env}")
  ieInstagramOAuth(params: String): String @function(name: "ieInstagramOAuth-${env}")
  ieInstagramRevokeOAuth(params: String): String @function(name: "ieInstagramRevokeOAuth-${env}")
  ieMidjourneyWebhook(params: String): String @function(name: "ieMidjourneyWebhook-${env}")
}`

**Comment by AnilMaktala** [comment]
Hi @kiostudio, Thank you for sharing the schema from S3. Please follow the steps mentioned in this [link](https://github.com/aws-amplify/amplify-category-api/issues/88#issuecomment-1129352642) and inform us if it resolves the issue.

**Comment by kiostudio** [comment]
[](url)
![Screenshot 2023-06-13 at 10 37 07 AM](https://github.com/aws-amplify/amplify-category-api/assets/63901064/8e867152-e4fa-4952-8008-2a311dfc5696)
It doesn't work. However, I have start a new environment and migrate everything back to the new environment (include the data). Thanks anyway.
