### ISSUE TITLE
GraphQL doesn't reflect recent changes in schema for listItems query

### ISSUE THREAD

**Issue by atef-abdellatif** [aws-amplify/amplify-category-api#1563]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v19.5.0

### Amplify CLI Version

12.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Nope

### Describe the bug

After updating one of the tables in the schema.graphql file and running amplify push, the changes haven't been reflected in the listItems query. However, the new changes have been successfully reflected on the getItem query for the same table. I deleted the changes and made new changes and ran amplify push but the problem still exists. I ran amplify codegen to regenerate a clean code, but nothing changes. I checked the queries file and noticed that the getItem is fully reflecting the recent changes in the schema, while the listItems query for the same table still shows the old version of the schema.

### Expected behavior

The graphql should update the queries for both getItem and listItems for the same table after pushing the new changes to Amplify. 

### Reproduction steps

1. Not sure how this bug can be reproduced!

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi @atef-abdellatif, Thank you for bringing this up. Could you please verify the generated schema file located in the /backend/api/build folder? Please check if your changes are reflected in that file. If not, I recommend deleting the schema file and running the command `amplify api gql-compile` again to regenerate it. Afterward, please verify if your changes are now correctly reflected in the schema file.

**Comment by atef-abdellatif** [comment]
Hi, I checked the schema file in the build folder and the changes are correctly and fully reflected in that file. However, the changes are not reflected in graphql/queries file. As I said, I deleted the table in question and ran amplify push, then I recreated it in a different name and ran amplify push, but the issue still exists— the table is correctly reflected in the queries file EXCEPT two attributes. I mean, the listItems query in the queries file doesn’t show all attributes  of the table. It misses two attributes. The getItem query, however, shows the whole table with all attributes.Best,AtefOn Jun 15, 2023, at 21:29, Anil Maktala ***@***.***> wrote:﻿
Hi @atef-abdellatif, Thank you for bringing this up. Could you please verify the generated schema file located in the /backend/api/build folder? Please check if your changes are reflected in that file. If not, I recommend deleting the schema file and running the command amplify api gql-compile again to regenerate it. Afterward, please verify if your changes are now correctly reflected in the schema file.

**Comment by AnilMaktala** [comment]
Hey @atef-abdellatif, Thank you for the response.

Would you be willing to attempt the following steps to see if they resolve the issue?
1. Rename the queries.js file to queries_old.js in the src/graphql folder.
2. Open the schema.gql file and add a blank space.
3. Execute amplify push.
4. Observe if a new queries.js file is created in the graphql/ folder.

**Comment by atef-abdellatif** [comment]
Hi Anil,

Thanks for your reply!
I followed the steps and a new queries file was generated but the issue still exists! Can you think of any other way around?

Best,
Atef

**Comment by AnilMaktala** [comment]
Hi @atef-abdellatif, I'm sorry to hear that the workaround didn't solve the issue. Could you please run the following command and share the report with us: `amplify diagnose --send-report`.
please refer [here](https://docs.amplify.aws/cli/reference/diagnose/)

**Comment by AnilMaktala** [comment]
Hey @atef-abdellatif, Thank you for providing the diagnosis report. Could you please share the name of the model that is causing this issue?

**Comment by atef-abdellatif** [comment]
The model name is “Intercity”.On Jun 16, 2023, at 18:08, Anil Maktala ***@***.***> wrote:﻿
Hey @atef-abdellatif, Thank you for providing the diagnosis report. Could you please share the name of the model that is causing this issue?

**Comment by AnilMaktala** [comment]
Hey @atef-abdellatif, Thank you for sharing the model name. I have attempted to reproduce the issue using the provided schema and I can see all the intercity model properties in the listIntercities query. Could you please review the screen below and let me know which property is missing in your queries.js file?

<img width="706" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/6086eb22-1ce0-4b7a-80dc-7d01520d078a">

**Comment by atef-abdellatif** [comment]
Hey Anil,

The two properties that are missing are: fares and carFares. You can see these two properties under getIntercity query.

**Comment by AnilMaktala** [comment]
Hey @atef-abdellatif, Thank you for providing the clarification. The issue is related to the maximum statement depth, which is set to 2 by default. The nested types within these two types are causing the problem. You have two options to address this issue.

Option 1: Increase the maximum statement depth to 4:

1. Run the command `amplify update codegen`.
2. Choose 4 when prompted to `enter the maximum statement depth`.
3. Run `amplify codegen` and verify that the carfare and fares properties are populated in the listIntercities query.

![image](https://github.com/aws-amplify/amplify-category-api/assets/3206171/0c11fa8c-ea92-4b64-84b0-e0b1224f9b1b)
<img width="704" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/5b5943d9-a704-43dc-b9d2-7737d9ad4ec8">

Option 2: Create a custom query page:

1. Develop a separate custom query page specifically for this query.
2. Import the custom query page into your app.

let us know if it resolves your issue.

**Comment by atef-abdellatif** [comment]
Hey,
That worked! Thank you so much:)
