### ISSUE TITLE
Using @index with the cli generated get resolvers

### ISSUE THREAD

**Issue by millerdk12** [aws-amplify/amplify-category-api#1564]
### Amplify CLI Version

12.0.0

### Question

Hello!

I am trying to add a secondary index to a model using the `@index` directive. Specifically for my use case, I need a friendly external ID to look up a `Company` record. Further, I want to restrict public / guest users to be able to only query a single company by this external ID via the `@auth(rules: [{ allow: public, operations: [get], provider: iam } ])` directive. I do not want them to have list / search access.

However it seems the `@index` will only generate a query that will return the list of results. Is it possible to have the `@index` directive generate a query to get a single record by the index?

For example the schema:
```
type Company @model @auth(
  rules: [
    { allow: public, operations: [get], provider: iam },
    { allow: groups, groups: ["Admin"] }
  ]) {
  id: ID!
  name: String!
  externalId: String! @index(name: "byExternalId", queryField: "companyByExternalId", sortKeyFields: ["id"])
}
```

Would generate the following queries (in addition to the other CRUD operations):
```
type Query {
  getCompany(id: ID!): Company @aws_iam @aws_cognito_user_pools
  getCompanyByExternalId(externalId: ID!): Company @aws_iam @aws_cognito_user_pools
}
```

My current workaround has been to add a second model with a user provide primary key, and then relate that model to target model. This will generate the queries I need without requiring list access to be granted to the public, however I don't prefer adding a second model just for this reason alone when it should be possible to use a secondary index directly on the target model.
```
type CompanyLookup @model @auth(
  rules: [
    { allow: public, operations: [get], provider: iam },
    { allow: groups, groups: ["Admin"] }
  ]) {
  externalId: String! @primaryKey
  company: Company @hasOne
}

type Company @model @auth(
  rules: [
    { allow: public, operations: [get], provider: iam },
    { allow: groups, groups: ["Admin"] }
  ]) {
  id: ID!
  name: String!
}
```

**Comment by AnilMaktala** [comment]
Hi @millerdk12, Thank you for asking the question. Based on your use case, we can recommend using the dynamic ownerField access to restrict the access to one company. The Admin who ever is creating the record needs to set the owner field to the username of the person who needs the access. This would require user needs to authenticated via congnito userpool. Please refer to [this](https://docs.amplify.aws/cli/graphql/authorization-rules/#per-user--owner-based-data-access) section and let us know if it resolves your issue.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
