### ISSUE TITLE
No public IAM access at all with transformer v2

### ISSUE THREAD

**Issue by ErhardScampi** [aws-amplify/amplify-category-api#1566]
### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v16.18.0

### Amplify CLI Version

12.0.3

### What operating system are you using?

MAC M1

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

No public access at all.
Here the auth snipped  

 @auth(
    rules: [
      { allow: public, provider: iam, operations: [read] },
      {allow: owner}
    ]
  )

This is essential for me. In Transformer V1 my application worked very well with public access. 

[schema.graphql.txt](https://github.com/aws-amplify/amplify-category-api/files/11728253/schema.graphql.txt)
<img width="1446" alt="amplifyAppsyncListBlogs" src="https://github.com/aws-amplify/amplify-category-api/assets/69878278/bb141
<img width="1351" alt="ConsoleOutput" src="https://github.com/aws-amplify/amplify-category-api/assets/69878278/9532e22b-83ae-4ceb-a004-a1a6bbc8ed07">
8ce-9f0a-4d3d-a3b6-b23434618af5">

### Expected behavior

Public IAM access should work as mentioned in the output of amplify status api -acm Blog

### Reproduction steps

1. Install amplify/Cli
2. Install the example project from the amplify doc (It is generated as example graphql)
3. add the auth snippet to all tables (auth snippet mentioned in details)
4. Go to appsync console. Fire a query listBlogs with IAM access.
5. See error message in output. (Screenshots in details section)
6. Run : amplify status api -acm Blog to see what should be

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I need a solution urgent because I deployed it yet....So I shutdown the site for maintenance at the moment. (I forgot to test public access - owner access works) Should I migrate back to the transformer version 1 ?

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ErhardScampi** [comment]
Here the output of the Appsync
<img width="1446" alt="amplifyAppsyncListBlogs" src="https://github.com/aws-amplify/amplify-category-api/assets/69878278/d173060a-741b-42a3-9f2d-3f3066b40210">

**Comment by ErhardScampi** [comment]
I have read in the docs that the best way to gain public access is to use the API key access. But the problem is that I can't force the user to reinstall a progressive web app every time period (The api key expires after a certain time) . Is there a possibility to use the api key access without reinstalling the app ? 
Perhaps I have to change the auth mode at all....

**Comment by ErhardScampi** [comment]
I updated to amplify/cli 12.1.0
Now the access works of my main application in the VUE frontend but not in the query of the aws console.
Amplify.configure  is  marked depreciated. What to use instead ?

The example (Blog Post) schema mentioned above does not work in the aws console either. (access via IAM). 
When should I use IAM and when the api_key access for public access ?

**Comment by phani-srikar** [comment]
Hi @ErhardScampi, If you're referring to [this JS method](https://docs.amplify.aws/lib/client-configuration/configuring-amplify-categories/q/platform/js/), that shouldn't be deprecated. Can you share the version of library you're using and logs that indicate that the method is deprecated?

The `public` access using the `IAM` provider for `read` operations means that the un-authenticated users will be able to do those operations. What role are you assuming before running these operations from the console?

**Comment by ErhardScampi** [comment]
<img width="923" alt="_depreciatedAmplify" src="https://github.com/aws-amplify/amplify-category-api/assets/69878278/c792995a-39bf-478d-9fa0-1ad49eca6016">

**Comment by ErhardScampi** [comment]
@phani-srikar
Thanks for Your answer.
As you can see in the screenshot above it is in VS Code where it is marked as deprecated.
To make it more clear in my mainApplikation that what is working is API_KEY auth now as a workaround. IAM does not work up to now in both apps Test and main.
Where do I see in the aws console which role I am assumed to ?

**Comment by phani-srikar** [comment]
Hey @ErhardScampi, what version of the JS library are you using? If you're on the latest version, according to [this section](https://github.com/aws-amplify/amplify-js#amplify-5xx-has-breaking-changes-please-see-the-breaking-changes-below), you need to use `import { Amplify } from 'aws-amplify'` instead.
In order to use the public IAM auth, your project should have cognito resource and API is configured to use IAM auth, then
- if user is signed out, it uses un-auth role.
- if user is signed in, it uses auth role.

**Comment by phani-srikar** [comment]
Hi @ErhardScampi. Thanks for sharing your code snippet. 
When using AWS_IAM for public API access, unauthenticated logins must be enabled. To enable unauthenticated logins, run `amplify update auth` from the command line and follow the prompts as shown below: 
```
> What do you want to do? 
    Walkthrough all the auth configurations

> Select the authentication/authorization services that you want to use: 
   User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or other content, 
   Analytics, and more)

> Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) 
   Yes

... other questions based on your app's use-case or choose defaults
```
Can you confirm if you followed the above steps? [Refer this part of the Amplify JS doc](https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/js/#using-amplify-graphql-client)

**Comment by ErhardScampi** [comment]
Hi @phani-srikar 
Thanks for Your advice. It works.
You can close this ticket was my fault in configuration.
