### ISSUE TITLE
Custom GraphQL query using incorrect ARN 

### ISSUE THREAD

**Issue by cbirkenstock** [aws-amplify/amplify-category-api#1569]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.17.0

### Amplify CLI Version

12.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

changed logging policies on AppSync to test custom VTL files

### Describe the bug

I've created a custom pipeline resolver with VTL. The first function lists users returned from the user table and the second function performs a batch request on a chat's table. There is no internal error with the VTL files but I get this error with authorization:

 "message": "User: arn:aws:sts::177777110084:assumed-role/<specific-role>-staging/APPSYNC_ASSUME_ROLE is not authorized to perform: dynamodb:BatchGetItem on resource: arn:aws:dynamodb:us-east-1:177777110084:table/ChatTable because no identity-based policy allows the dynamodb:BatchGetItem action (Service: DynamoDb, Status Code: 400, Request ID: PEI8N39EK2PEUK5HHN52JPSP6VVV4KQNSO5AEMVJF66Q9ASUAAJG)"
 

it appears that the second function is being given an arn that is incorrect as is ends with /ChatTable instead of /Chat-<RANDOM BLURB>-staging

### Expected behavior

the correct arn should be assigned since it correctly found the ChatTable and when I check the function in appsync it is attached to the correct database. 

### Reproduction steps

1. create a table with items
2. download custom - and copy and paste code for cdk-stack.js
3. modify the files to get to v2 of cdk 
4. create a getbatchitems function with both .req and .res VTL files 
5. put them all together and try to run 

### Log output

<details>

```
Object {
  "data": Object {
    "getBatchChats": null,
  },
  "errors": Array [
    Object {
      "data": null,
      "errorInfo": null,
      "errorType": "DynamoDB:DynamoDbException",
      "locations": Array [
        Object {
          "column": 3,
          "line": 2,
          "sourceName": null,
        },
      ],
      "message": "User: arn:aws:sts::177777110084:assumed-role/<specific role>-staging/APPSYNC_ASSUME_ROLE is not authorized to perform: dynamodb:BatchGetItem on resource: arn:aws:dynamodb:us-east-1:177777110084:table/ChatTable because no identity-based policy allows the dynamodb:BatchGetItem action (Service: DynamoDb, Status Code: 400, Request ID: PEI8N39EK2PEUK5HHN52JPSP6VVV4KQNSO5AEMVJF66Q9ASUAAJG)",
      "path": Array [
        "getBatchChats",
      ],
    },
  ],
}
 


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi @cbirkenstock, Thank you for bringing this up. Would it be possible for you to share the cdk-stacks.js and vtl files with us?

**Comment by cbirkenstock** [comment]
Sure no problem!

Here is the cdk-stacks.js file 

<img width="872" alt="Screenshot 2023-06-13 at 7 39 29 PM" src="https://github.com/aws-amplify/amplify-category-api/assets/78714473/5247cf3b-b236-40f4-a8ee-9511590b8413">

<img width="874" alt="Screenshot 2023-06-13 at 7 40 08 PM" src="https://github.com/aws-amplify/amplify-category-api/assets/78714473/47622382-e21c-4fe5-ae73-137db4913806">

<img width="647" alt="Screenshot 2023-06-13 at 7 40 26 PM" src="https://github.com/aws-amplify/amplify-category-api/assets/78714473/d11325d9-7a2f-4284-982d-6b94149524e5">

I have 6 files that contain VTL files:

beforeMapping:

<img width="452" alt="Screenshot 2023-06-13 at 7 43 01 PM" src="https://github.com/aws-amplify/amplify-category-api/assets/78714473/c9c0f446-c2b5-4f35-b8c3-8ea6da776c42">

function 1 req

<img width="451" alt="Screenshot 2023-06-13 at 7 43 35 PM" src="https://github.com/aws-amplify/amplify-category-api/assets/78714473/d4cb0ae0-dab9-438e-94de-eb4a3a782cfb">

function 1 res

<img width="519" alt="Screenshot 2023-06-13 at 7 43 42 PM" src="https://github.com/aws-amplify/amplify-category-api/assets/78714473/643ee1a3-adee-43f9-8aa2-227b4e87199c">

function 2 req

<img width="500" alt="Screenshot 2023-06-13 at 7 44 47 PM" src="https://github.com/aws-amplify/amplify-category-api/assets/78714473/5efb5563-8d9d-419a-8a01-9575c1038983">

function 2 res

<img width="486" alt="Screenshot 2023-06-13 at 7 44 54 PM" src="https://github.com/aws-amplify/amplify-category-api/assets/78714473/85479212-eb56-4d94-8390-efbb404eedb7">

**Comment by AnilMaktala** [comment]
Hi @cbirkenstock, Thank you for providing the VTL files. Would you mind making a modification to the BatchGet request template? Please update the "ChatTable" name as demonstrated in the example below and let us know if it resolves the issue.

```
 const envRef = cdk.Fn.ref('env');
 const apiIdRef = cdk.Fn.ref(retVal.api["<YOUR-API-NAME>"].GraphQLAPIIdOutput);
 const tableName = `${'<YOUR-MODEL-NAME>'}-${apiIdRef}-${envRef}`;

{
        "version": "2018-05-29",
        "operation": "BatchGetItem",
        "tables": {
          "${tableName}": $todosArray
        }
  }

```

**Comment by AnilMaktala** [comment]
Hey @cbirkenstock, Have you been able to resolve the issue by following the suggestion to change the ChatTable name as mentioned in the previous comment?

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
