### ISSUE TITLE
How to Add @hasmany using APIService method

### ISSUE THREAD

**Issue by desert-digital** [aws-amplify/amplify-category-api#1580]
### Amplify CLI Version

12.1.1

### Question

Hello: 

I am creating a variation of the classic To Do application, using a list of available ActionModels that can be part of part of one or more Checklists. While technically many-to-many, I only care relationship between the Checklist and ActionModels so I am defining a one-to-many relationship (see below).

```
type ActionModel @model @auth(rules: [{ allow: private }]){
  id: ID!
  company: ID
  name: String
  status: String
  notes: String 
  duration: Int
}

type Checklist @model @auth(rules: [{ allow: private }]){
  id: ID!
  company: ID
  owner: String @hasOne
  steps: [ActionModel] @hasMany
  start: AWSDate
  end: AWSDate 
}
```
In the UI, I create an ordered list of actions, and want then to save that list (i.e., array) in the steps field. **My question is: how do I add _steps_ to the _Checklist_** using the Amplify Javascript libraries created by codegen? I've read the documentation [here](https://docs.amplify.aws/cli/graphql/data-modeling/#has-many-relationship). Do I need to create a backward link to the parent table? Or is it the leading practice to use the @belongsTo directive instead? 

Thanks in advance, Ian.

**Comment by AnilMaktala** [comment]
Hey @desert-digital, Thank you for bringing up this issue. The choice between uni-directional and bi-directional relationships depends on your specific use case. If you need to fetch the Checklist Model along with the Action model when performing a get or list query, using a bi-directional relationship is recommended to avoid multiple fetch calls. However, if that is not a requirement, you can opt for a uni-directional relationship.

**Comment by desert-digital** [comment]
@AnilMaktala: thanks so much for the reply. 

So, if I understand the documentation correctly, I need to create the parent object first (i.e., the Checklist), get the ID from that and add it to the newly created ActionModel with object. When I get the Checklist, will the steps member be array of ActionModels?

Cheers...

**Comment by AnilMaktala** [comment]
Hey @desert-digital, Yes, you have understood the documentation correctly. The process involves creating the parent object (Checklist) first and obtaining its ID. Then, you can use this ID to associate the newly created ActionModel with the Checklist as a step.When you retrieve the Checklist, the "steps" member will indeed be an array of ActionModels, representing the actions associated with that Checklist.

**Comment by desert-digital** [comment]
Cool. Hopefully this will help some other folks looking for the same information.

Appreciate your guidance @AnilMaktala!
