### ISSUE TITLE
Can't update API KEY Datastore/GraphQL

### ISSUE THREAD

**Issue by armandwegnez** [aws-amplify/amplify-category-api#1583]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.16.0

### Amplify CLI Version

12.1.1

### What operating system are you using?

MacOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I ran into an issue while working with AWS. I wanted to make changes to the API, so I tried two approaches. First, I modified the AWS configuration in the "aws-export" file. However, things didn't go as planned, and I encountered an error or faced some difficulties. Frustrated but determined, I decided to take a different approach and directly modify the API within my AppSync application. Unfortunately, that didn't work out either, and I hit another roadblock. It's been a bit frustrating trying to make these changes, and I could really use some assistance in resolving this issue.

### Describe the bug

This morning, I decided to pick up a project that I had put on hold for the past four months. The project was built using Expo SDK46, so I thought it would be a good idea to upgrade it to SDK48. I made a backup before proceeding, with the first backup containing SDK46.

As I started working on it again, I encountered multiple errors, such as the deprecation of "expo-random" and issues with AWS Amplify. While investigating why I couldn't send messages in my messaging app project, I discovered that my API key was different from the one specified in the project. This inconsistency was causing the messaging functionality to fail.

In an attempt to resolve the issue, I directly changed the endpoint and API key. Surprisingly, I was able to retrieve some information from my DynamoDB, specifically user data that was required for searching and initiating conversations. However, the message sending function still didn't work.

I tried using `amplify push`, but it didn't push any changes and returned the error:

🛑 The following resources failed to deploy:
Resource Name: GraphQLAPIDefaultApiKeyxxxxxxxxx

At this point, I decided to revert to the earlier backup I created using the command `amplify pull --appId <theid> --envName <theenv>`. However, even that backup didn't work as expected. In an attempt to fix the issue, I deleted all the nodes and the Amplify folder, and then executed the following commands: `npm install` followed by `amplify pull --appId <theid> --envName <theenv>`. Finally, the backup worked, but I encountered a new problem—I couldn't find my users.

Desperately seeking a solution, I turned to Google and found a suggestion to use "import '@azure/core-asynciterator-polyfill';", but it didn't solve the issue. Then, I came across a solution provided by ejmiller2 on GitHub (link provided), but I couldn't find anything similar in my files.

I noticed that the AWS configuration had the following sections:

{
  "AppSyncApiName": "APPNAME",
  "DynamoDBBillingMode": "PAY_PER_REQUEST",
  "DynamoDBEnableServerSideEncryption": false
}

and

{
  "api": {
    "APPNAME": {
      "dependsOn": [],
      "output": {
        "authConfig": {
          "additionalAuthenticationProviders": [
            {
              "authenticationType": "AWS_IAM"
            }
          ],
          "defaultAuthentication": {
            "apiKeyConfig": {
              "apiKeyExpirationDate": "2023-07-19T13:37:59.672Z",
              "apiKeyExpirationDays": 30,
              "description": "api key description"
            },
            "authenticationType": "API_KEY"
          }
        }
      },
      "providerPlugin": "awscloudformation",
      "service": "AppSync"
    }
  },
  "auth": {
    "APPNAME": {
      "customAuth": false,
      "dependsOn": [
        {
          "attributes": [
            "Arn",
            "Name"
          ],
          "category": "function",
          "resourceName": "APPNAMEPostConfirmation",
          "triggerProvider": "Cognito"
        }
      ],
      "frontendAuthConfig": {
        "mfaConfiguration": "OFF",
        "mfaTypes": [
          "SMS"
        ],
        "passwordProtectionSettings": {
          "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
          ],
          "passwordPolicyMinLength": 8
        },
        "signupAttributes": [],
        "socialProviders": [],
        "usernameAttributes": [
          "EMAIL"
        ],
        "verificationMechanisms": [
          "EMAIL"
        ]
      },
      "providerPlugin": "awscloudformation",
      "service": "Cognito"
    }
  },
  "function": {
    "APPNAMEPostConfirmation": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda"
    }
  },
  "parameters": {
    "AMPLIFY_function_APPNAMEConfirmation_deploymentBucketName": {
      "usedBy": [
        {
          "category": "function",
          "resourceName": "APPNAMEPostConfirmation"
        }
      ]
    },
    "AMPLIFY_function_APPNAMEPostConfirmation_s3Key": {
      "usedBy": [
        {
          "category": "function",
          "resourceName": "APPNAMEPostConfirmation"
        }
      ]
    }
  },
  "storage": {
    "s3appnamestorage98238953": {
      "dependsOn": [],
      "providerPlugin": "awscloudformation",
      "service": "S3"
    }
  }
}

I speculated that this might be the cause of the problem, but I'm not entirely sure.

Despite extensive searching on Google, I couldn't find much relevant information or solutions to address the ongoing issues.

### Expected behavior

The expected behavior of my Lambda function, which is currently functioning correctly, is that it continues to work seamlessly without introducing any new issues.

In the context of the datastore/graphql, the expected behavior is that the GraphQL API, powered by AWS AppSync, efficiently handles the retrieval of user data, chatroom information, and user-chatroom associations.

The GraphQL API should be able to fetch user data, including details such as usernames, profiles, and any relevant user-related information. It should also provide access to chatroom information, including the chatroom's name, participants, and any associated metadata. Additionally, the API should enable the retrieval of user-chatroom associations, allowing users to access the chatrooms they are part of or have permissions to view.

Furthermore, the GraphQL API should facilitate the sending of messages within the chat application. Users should be able to create and send messages, ensuring smooth communication and interaction within the chatrooms.

Overall, the expected behavior is that the datastore/graphql layer, specifically the GraphQL API powered by AWS AppSync, effectively handles these operations, ensuring reliable retrieval of data and seamless messaging capabilities within the chat application.

### Reproduction steps

1. Started by reviving a project that had been on standby for four months. The project was using Expo SDK46, so you decided to upgrade it to SDK48.
2. Changing the endpoint and API key directly.
3. Attempted to use `amplify push`.
4. suggesting to import "@azure/core-asynciterator-polyfill"???
5. 

### Project Identifier

Project Identifier: 49b7df2c2e52a3cddd349de49e6debe1

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi @armandwegnez, Thank you for bringing up this issue and providing an explanation. We have a follow-up question for you:
1. Have you noticed any exceptions in the logs when invoking the lambda function? If so, would you be able to share the logs with us?
2. Were you able to successfully push the changes after the rollback?

**Comment by armandwegnez** [comment]
I haven’t noticed any exceptions specifically related to the lambda function in the logs while invoking it. However, I did come across some unhandled promises in my console.log, but they don’t seem to be directly linked to the lambda function. Nevertheless, I’m willing to trigger those scenarios again to gather more information and provide you with detailed logs to help troubleshoot the issue.


Although I didn't directly use the `amplify rollback` command, I was able to achieve the desired result through the following steps:

1. First, I deleted both the `amplify` folder and the `node_modules` folder associated with my project.
2. Then, I performed a fresh installation by running `npm install` to ensure all dependencies were properly installed.
3. Next, I used the command `amplify pull --app-id <id> --env <env>` to retrieve the latest backend configuration and resources associated with my Amplify project.
4. After completing these steps, I was able to successfully push the changes to my Amplify backend.

However, it's important to note that I encountered an error when attempting to manually modify the `amplify` folder, such as making changes to the API configuration. Touching any files within the `amplify` folder resulted in an error. Therefore, it seems that making manual changes to the `amplify` folder may disrupt the push process.
If I modified it directly in the console, let’s say `amplify update api` it says success, but sadly nothing changed much, it was still the wrong APIKey.

**Comment by armandwegnez** [comment]
```json
 WARN  Possible Unhandled Promise Rejection (id: 0):
Object {
  "data": Object {},
  "errors": Array [
    [GraphQLError: Request failed with status code 401],
  ],
}
```


or 

```json
 ERROR  [ERROR] 45:22.117 DataStore - Sync processor retry error: {"data": {}, "errors": [[GraphQLError: Request failed with status code 401]]}
 WARN  [WARN] 45:22.135 DataStore - User is unauthorized to query syncUsers with auth mode API_KEY. No data could be returned.
 ```
 
 there's also
 
 ```json 
  WARN  [WARN] 45:22.368 DataStore {"cause": {"error": {"errors": [Array]}, "provider": {"_config": [Object], "awsRealTimeSocket": undefined, "connectionState": "ConnectionDisrupted", "connectionStateMonitor": [ConnectionStateMonitor], "connectionStateMonitorSubscription": [Subscription], "keepAliveTimeout": 300000, "promiseArray": [Array], "reconnectionMonitor": [ReconnectionMonitor], "socketStatus": 0, "subscriptionObserverMap": [Map]}}, "errorType": "Unauthorized", "localModel": null, "message": "Connection failed: UnauthorizedException", "model": "ChatRoom", "operation": "Create", "process": "subscribe", "recoverySuggestion": "Ensure app code is up to date, auth directives exist and are correct on each model, and that server-side data has not been invalidated by a schema change. If the problem persists, search for or create an issue: https://github.com/aws-amplify/amplify-js/issues", "remoteModel": null}
  ```
  
 these are example but depending on the feature, it shows different Errors.

**Comment by AnilMaktala** [comment]
Hey @armandwegnez, Thank you for sharing the logs. Could you please follow the steps below to verify the status of the API key in the AWS AppSync console:

1. Run the command `amplify api console` and select the GraphQL option.
2. In the AppSync console, navigate to API and then go to Settings.
3. Verify the validity of the API keys.

Please let us know if you find any issues or discrepancies in the API key status.

<img width="1319" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/695f3862-c486-4cb4-9406-05dbc9d6f6cf">

**Comment by armandwegnez** [comment]
I did I made new ones valid for 365, and it didn’t helped much

**Comment by AnilMaktala** [comment]
Hey @armandwegnez, Thank you for verifying api key validity in API console. Could you please follow the steps mention [here](https://github.com/aws-amplify/amplify-category-api/issues/636#issuecomment-1288164584) and let us know if it resolves the issue?

**Comment by armandwegnez** [comment]
It still didn't. however I started everything back to 0 because i will not wait until some random find out the solution.
Thank you for your time, but I'll get through this.
