### ISSUE TITLE
Following docs for configuring OpenSearch environment type produces Cloudformation error

### ISSUE THREAD

**Issue by davidtwomey** [aws-amplify/amplify-category-api#1585]
### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli@latest

### If applicable, what version of Node.js are you using?

v19.5.0

### Amplify CLI Version

12.1.1

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

Following the documentation here: https://docs.amplify.aws/cli-legacy/graphql-transformer/searchable/#configure-environment-opensearch-instance-type

I updated my `team-provider-info.json` file as specified and receive the following error after `amplify push`

```
Name:  (AWS::CloudFormation::Stack), Event Type: update, Reason: Parameters: [ElasticSearchInstanceCount, ElasticSearchInstanceType] do not exist in the template, IsCustomResource: false
```

### Expected behavior

I would expect this to update the opensearch instance type for `prod` to be `ElasticSearchInstanceType: "t2.medium.elasticsearch"` (see below)

Looking at other open issues, it appears that I may have to use `parameters.json` instead?
But this does not allow for environment-specific settings (i.e. `prod` using a larger instance than `dev`)

The `team-provider-info.json` should not be included in the docs if it is not supported:
(https://docs.amplify.aws/cli-legacy/graphql-transformer/searchable/#configure-environment-opensearch-instance-type)

### Reproduction steps

I updated my `amplify/team-provider-info.json` configuration: 
```json
{
    "dev": {
      "categories": {
        "api": {
          "<my-api-name>" : {}
        }
      }
    },
    "prod": {
      "categories": {
        "api": {
          "<my-api-name>" : {
            "ElasticSearchInstanceType": "t2.medium.elasticsearch",
            "ElasticSearchInstanceCount": 2
          }
        }
      }
    }
  }
```

and attempted to run the push command (on prod env)

`amplify push`

I then get a cloudformation `UPDATE_FAILED` operation

### Log output

<details>

```
# Put your logs below this line
Deployment failed.
Deploying root stack XXXXXX [ ====================-------------------- ] 1/2
        amplify-XXXXXX-p… AWS::CloudFormation::Stack     UPDATE_ROLLBACK_COMPLETE       Mon Jun 19 2023 13:10:09…     
        XXXXXXXX         AWS::CloudFormation::Stack     UPDATE_FAILED                  Mon Jun 19 2023 13:10:03…     
Deployed api XXXXXXXX [ ======================================== ] 12/12

🛑 The following resources failed to deploy:
Resource Name: XXXXX (AWS::CloudFormation::Stack)
Event Type: update
Reason: Parameters: [ElasticSearchInstanceCount, ElasticSearchInstanceType] do not exist in the template
URL: <XXXXXX>


🛑 Resource is not in the state stackUpdateComplete
Name: XXXXXX (AWS::CloudFormation::Stack), Event Type: update, Reason: Parameters: [ElasticSearchInstanceCount, ElasticSearchInstanceType] do not exist in the template, IsCustomResource: false
```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi @davidtwomey,Thank you for bringing this up. We suggest utilizing the override functionality to make changes to the search instance type. You can refer to [this documentation](https://docs.amplify.aws/cli/graphql/override/#example---configure-opensearch-instance-type) for detailed instructions on how to modify the search instance type.

**Comment by davidtwomey** [comment]
Hi @AnilMaktala - thanks for the suggestion - I will look into the link you provided.

Can I confirm that the original [documentation](https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#set-up-opensearch-for-production-environments) I linked to when creating this ticket is incorrect then?

**Comment by AnilMaktala** [comment]
Hey @davidtwomey, Thank you for sharing the additional information. The documentation regarding the search instance type remains valid. However, please note that the team-provider-info.json file only supports updating the instance type. To modify the number of search instances, we need to utilize the override functionality. We have successfully updated the search instance type by incorporating the following code snippet in the team-provider-info.json file.
```
"categories": {
      "api": {
        "test": {
          "OpenSearchInstanceType": "t2.small.elasticsearch"
        }
      },

**Comment by davidtwomey** [comment]
Hey @AnilMaktala 
I can also confirm that the "OpenSearchInstanceType" parameter does work - thanks!
You appear to have a discrepancy in your docs then

This documentation is correct:
https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#set-up-opensearch-for-production-environments

But this documentation remains incorrect? (Although i note the `cli-legacy` part of the url?)
https://docs.amplify.aws/cli-legacy/graphql-transformer/searchable/#configure-environment-opensearch-instance-type
As it shows up as this:
```
{
    "dev": {
      "categories": {
        "api": {
          "<your-api-name>" : {
            "ElasticSearchInstanceType": "t2.small.elasticsearch"
          }
        }
      }
    },
    "prod": {
      "categories": {
        "api": {
          "<your-api-name>" : {
            "ElasticSearchInstanceType": "t2.medium.elasticsearch"
          }
        }
      }
    }
  }
 ```

**Comment by ishapiro** [comment]
In a related question. Is there any plan to update the OpenSearch capabilities in Amplify to bring them up to date with the current OpenSearch functionality, including serverless configurations?

**Comment by AnilMaktala** [comment]
Hey @davidtwomey, Thank you for the confirmation. We are actively working on updating the documentation and plan to deprecate the legacy section once the updates are completed.

@ishapiro ,Thank you for inquiring. Would you kindly submit a feature request outlining your requirements? We will collaborate with the engineering team to prioritize it accordingly.
