### ISSUE TITLE
GraphQl API authorization configuration doesn't reflect recent changes

### ISSUE THREAD

**Issue by atef-abdellatif** [aws-amplify/amplify-category-api#1586]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d365ce6y79hx7o

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Describe the bug

I have configured the GraphQL API authentication to only use Cognito, but I always get the below warning after I run amplify push and the build FAILS because of this warning. I made sure that there's no any additional authentication added to the api authentication configuration, HOWEVER, when I remove the "AdditionalAuthenticationProviders" property in the cloudformation-template.json file it get re-added after running amplify push. 
the warning that I receive when I run amplify push is: GraphQL API is configured to use API_KEY authentication, but API Key deployment is disabled, don't forget to create one.

<img width="762" alt="Screenshot 2023-06-17 at 12 14 21 PM" src="https://github.com/aws-amplify/amplify-hosting/assets/110037539/f98b2ef8-932c-48dd-8efc-8d047df764dd">

### Expected behavior

GraphQL API-KEY warning disappear and the api authentication provider to be only Cognito 

### Reproduction steps

Running amplify push

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by AnilMaktala** [comment]
Hey @atef-abdellatif, Are you still experiencing this issue?

**Comment by AnilMaktala** [comment]
Hey @atef-abdellatif, Thank you for the response. Have you attempted including the `createAPIKey:1` property in the parameters.json file as indicated in [this](https://docs.amplify.aws/cli-legacy/graphql-transformer/config-params/#createapikey) reference?

**Comment by atef-abdellatif** [comment]
Hello Nil,Thanks for getting back to me on this issue!Setting the createAPIKey to 1 will CREATE an api key which is NOT what I want. I want to configure the graphql api NOT to have an api key. Appreciate any help!Best,AtefOn Jun 26, 2023, at 15:15, Anil Maktala ***@***.***> wrote:﻿
Hey @atef-abdellatif, Thank you for the response. Have you attempted including the createAPIKey:1 property in the parameters.json file as indicated in this reference?

**Comment by AnilMaktala** [comment]
Hey @atef-abdellatif,Thank you for providing the clarification. Have you attempted using the `amplify update api` command and selecting only the Cognito authorization mode? Afterward, you can proceed by running `amplify push`.

Additionally, would you be able to share the logs with us?

<img width="896" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/7d3d4745-5809-4bc0-a651-93f01a8b8a43">

**Comment by atef-abdellatif** [comment]
Hi Anil,
Thank you for trying to help me resolve he issue!

I already did what you suggested and I even made sure that the "aws_appsync_authenticationType" property (located in the aws-exports.js file) doesn't include API_KEY. But the API_KEY still shows in the Authorization modes as shown in the attached screenshots. The problem is, I can't deploy my without removing the API_KEY authentication. As shown in the attached screenshots, the follwoing message appears after the amplify push is complete "GraphQL API is configured to use API_KEY authentication, but API Key deployment is disabled, don't forget to create one".

<img width="883" alt="Screenshot 2023-06-30 at 7 43 43 PM" src="https://github.com/aws-amplify/amplify-category-api/assets/110037539/d3e8f5eb-e93e-4dca-ba40-8379987a1995">
<img width="716" alt="Screenshot 2023-06-30 at 6 27 47 PM" src="https://github.com/aws-amplify/amplify-category-api/assets/110037539/52ae0f79-00a9-454f-beef-ab60fbae701d">
<img width="888" alt="Screenshot 2023-06-30 at 6 14 44 PM" src="https://github.com/aws-amplify/amplify-category-api/assets/110037539/504491af-afa7-4f19-8793-5f64b5c7691f">

**Comment by chrisbonifacio** [comment]
Hi @atef-abdellatif can you share your GraphQL schema? It's possible you might have a lingering public auth rule that is causing this message to appear. When we generate the schema, there is a global auth rule near the top that enables public access on all models which requires an API_KEY. Make sure to remove that if no longer needed as well.

**Comment by atef-abdellatif** [comment]
My schema is pretty long. As for the global auth rule, I removed it when I first created the schema. Let me know if there's a way to share with you the schema, maybe my app id or something like that.

i've attached a screenshot of the top of my schema file just to give you an idea of how my schema file looks like. 

<img width="931" alt="Screenshot 2023-07-04 at 2 04 30 PM" src="https://github.com/aws-amplify/amplify-category-api/assets/110037539/592fd4df-d614-4771-b7c8-ed931765b5a3">

**Comment by atef-abdellatif** [comment]
I removed the additionalAuthTypes array from the cli-inputs.json and ran amplify push but the deployment failed. Hope the project identifier will help you figure out what's causing the issue. 

Project Identifier: fa62b31536a55f4721b023a1da51ce62

**Comment by AnilMaktala** [comment]
Hey @atef-abdellatif, are you still experiencing this issue?

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
