### ISSUE TITLE
Lambda GraphQL resolver results in UPDATE_FAILED

### ISSUE THREAD

**Issue by Choquenizer** [aws-amplify/amplify-category-api#1606]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.12.1

### Amplify CLI Version

12.1.1

### What operating system are you using?

Ubuntu (WSL)

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Just one manual change: I've attached a policy to the function excecution role and a trigger that is currently disabled.

### Describe the bug

In a currently working schema I add a Lambda Graphql resolver but fails to deploy using amplify push.

`
type Mutation {
  saveModel(object: MyModelType): String @function(name:"DoStuff-${env}")
}`

Note: MyModelType its an @model. Don't know if this might be an issue.

Error:
🛑 The following resources failed to deploy:
Resource Name: GraphQLAPITransformerSchema3CB2AE18 (AWS::AppSync::GraphQLSchema)
Event Type: update
Reason: Schema Creation Status is FAILED with details: Internal Failure while saving the schema.

🛑 Resource is not in the state stackUpdateComplete
Name: GraphQLAPITransformerSchema3CB2AE18 (AWS::AppSync::GraphQLSchema), Event Type: update, Reason: Schema Creation Status is FAILED with details: Internal Failure while saving the schema., IsCustomResource: false

In cloudformation stack I find an event stating:
Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to create: [FunctionDirectiveStack]

### Expected behavior

Lambda resolver is deployed

### Reproduction steps

Add a lambda resolver to schema.graphql
run amplify push with amplify cli

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I'm working with us-east-1

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi @Choquenizer 👋, Thanks for raising this issue. We are working on reproducing the issue. Could you please run below command and send us the report `amplify diagnose --send-report` and share the project identifier with us? 

Please refer [here](https://docs.amplify.aws/cli/reference/diagnose/)

**Comment by Choquenizer** [comment]
Hi Anil,

This is the project identifier: e27dc722521eba84f90adcd5ec5b3297

Thank you for you interest

**Comment by chrisbonifacio** [comment]
@Choquenizer can you also check in the cloudformation logs in the AWS console for that failed lambda resolver update? There is a tab in that console called `Events` that should provide a more helpful error message that leads us to the cause of the issue.

**Comment by Choquenizer** [comment]
Hi Chris,

The complete event message is:
Embedded stack arn:aws:cloudformation:us-east-1:722223182257:stack/amplify-tramitesamplify-dev-153653-apitramitesamplify-1ARUYWOY0EYCC/0fe2d390-8878-11ed-ac66-0e2e23c1a04f was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to create: [FunctionDirectiveStack]. The following resource(s) failed to update: [CodigoFormulaSearch, GraphQLAPIDefaultApiKey215A6DD7].

**Comment by Choquenizer** [comment]
Hi,

The problem is fixed.

I had a few stacks in DELETE_FAILED status since some time ago I've deleted some functions but forgot to delete custom permission policies to they're respective roles.

I've deleted those stacks (manually removed the permission policies before) and now amplify push works fine.

Thanks!
