### ISSUE TITLE
Custom graphql resolver to set default values

### ISSUE THREAD

**Issue by callmekatootie** [aws-amplify/amplify-category-api#161]
**Which Category is your question related to?**
graphql / api

**Amplify CLI Version** 
6.0.0

I have a model like this:

```
type Foo @model {
  id: ID!
  ...
  createdBy: String
  updatedBy: String
}
```

I wanted to auto populate the `createdBy` and `updatedBy` fields to the username that is associated with the request (I am using Cognito to authorize the requests). My question is, just like the audit timestamp fields, `createdAt` and `updatedAt`, can these also be set automatically?

Right now, what I am doing is

- I generated the custom resolver vtl code using `amplify mock api`
- I deleted all the generated files except the create and update mutation ones
- and then added a single line to it (just below the statement where the createdAt and updatedAt are set:

```
## Automatically set the createdBy string. **
$util.qr($context.args.input.put("createdBy", $ctx.identity.username))
```

ditto for the updatedBy field.

I am not sure if this is the right approach though so decided to check in

**Comment by josefaidt** [comment]
Closing in favor of [`@default`](https://docs.amplify.aws/cli/graphql/data-modeling/#assign-default-values-for-fields) and [custom owner fields with `@auth`](https://docs.amplify.aws/cli/graphql/authorization-rules/#per-user--owner-based-data-access)
