### ISSUE TITLE
Multi-User data access with different permissions than owner

### ISSUE THREAD

**Issue by jo2** [aws-amplify/amplify-category-api#1642]
### Is this feature request related to a new or existing Amplify category?

auth, api

### Describe the feature you'd like to request

According to the [Auth documentation](https://docs.amplify.aws/cli/graphql/authorization-rules/#multi-user-data-access) it is possible to have a list of users as owner of a data set in the api schema. This is a pretty neat feature but not working for my use case because I want the owner field to be fix and the owner to have more permission than a set of users. I want to do something like this:
```
type Todo @model @auth(rules: [
  { allow: owner },
  { allow: customGroups, groupField: 'readers', operations: [read] },
]) {
  content: String
  readers: [String]
  owner: String @auth(rules: [{ allow: owner, operations: [read, delete] }]))
}
```
The owner should be allowed to do everything except updating the `owner` field. The `readers` should be allowed to see the Todo but they shouldn't be allowed to do anything else with it. I want the owner to be able to specify the set of users who can see the Todo.

### Describe the solution you'd like

As described above, something like this could work:
```
type Todo @model @auth(rules: [
  { allow: owner },
  { allow: customGroups, groupField: 'readers', operations: [read] },
]) {
  content: String
  readers: [String]
  owner: String @auth(rules: [{ allow: owner, operations: [read, delete] }]))
}
```

### Describe alternatives you've considered

It might also be possible to implement this using a custom resolver or a lambda function but I'd rather want to avoid this because of the additional resources that would need to be created manually and I think this might be a rather common use case regarding data sovereignty laws, bacause you can't create a cognito group for every subset of users you want to allow because of the [Cognito Quotas](https://docs.aws.amazon.com/cognito/latest/developerguide/limits.html#resource-quotas)

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by jo2** [comment]
Is it possible to have multiple "owner" allow rules that act differently? Also, how will the resolvers differentiate in the field-level owner rule between the two owner allows? 
If you move this issue, please reference the new issue location so I can keep track of the discussion.

**Comment by chrisbonifacio** [comment]
Hi @jo2, the reason there are multiple owner rules on the schema @josefaidt shared as an example is to demonstrate a few different auth scenarios. All of the rules being included in this schema are valid and can be used at the same time.

Here are the different behaviors for each rule:

{ allow: owner } - Allows the owner (Cognito User) of the record to perform all operations (read,update,delete)
{ allow: owner, ownerField: 'readers', operations: [read] } - Allows any Cognito Users listed in the `readers` field array to read the record

owner: String @auth(rules: [{ allow: owner, operations: [read, delete] }])) - This is a field level auth rule that only allows the owner of the record to read the value of `owner` and/or delete it.

It appears in the resolver that if you are a reader, you are able to retrieve a Todo and read the `content` and `readers`, but not the `owner` field.

For reference, this is the generated VTL for the auth resolver after compiling the schema above

```
## [Start] Authorization Steps. **
$util.qr($ctx.stash.put("hasAuth", true))
#set( $isAuthorized = false )
#set( $primaryFieldMap = {} )
#if( $util.authType() == "API Key Authorization" )

#end
#if( $util.authType() == "IAM Authorization" )
$util.unauthorized()
#end
#if( $util.authType() == "User Pool Authorization" )
  #if( !$isAuthorized )
    #set( $authFilter = [] )
    #set( $ownerClaim0 = $util.defaultIfNull($ctx.identity.claims.get("sub"), null) )
    #set( $currentClaim1 = $util.defaultIfNull($ctx.identity.claims.get("username"), $util.defaultIfNull($ctx.identity.claims.get("cognito:username"), null)) )
    #if( !$util.isNull($ownerClaim0) && !$util.isNull($currentClaim1) )
      #set( $ownerClaim0 = "$ownerClaim0::$currentClaim1" )
      #if( !$util.isNull($ownerClaim0) )
        $util.qr($authFilter.add({"owner": { "eq": $ownerClaim0 }}))
      #end
    #end
    #set( $role0_0 = $util.defaultIfNull($ctx.identity.claims.get("sub"), null) )
    #if( !$util.isNull($role0_0) )
      $util.qr($authFilter.add({"owner": { "eq": $role0_0 }}))
    #end
    #set( $role0_1 = $util.defaultIfNull($ctx.identity.claims.get("username"), $util.defaultIfNull($ctx.identity.claims.get("cognito:username"), null)) )
    #if( !$util.isNull($role0_1) )
      $util.qr($authFilter.add({"owner": { "eq": $role0_1 }}))
    #end
    #set( $ownerClaim1 = $util.defaultIfNull($ctx.identity.claims.get("sub"), null) )
    #set( $currentClaim1 = $util.defaultIfNull($ctx.identity.claims.get("username"), $util.defaultIfNull($ctx.identity.claims.get("cognito:username"), null)) )
    #if( !$util.isNull($ownerClaim1) && !$util.isNull($currentClaim1) )
      #set( $ownerClaim1 = "$ownerClaim1::$currentClaim1" )
      #if( !$util.isNull($ownerClaim1) )
        $util.qr($authFilter.add({"readers": { "contains": $ownerClaim1 }}))
      #end
    #end
    #set( $role1_0 = $util.defaultIfNull($ctx.identity.claims.get("sub"), null) )
    #if( !$util.isNull($role1_0) )
      $util.qr($authFilter.add({"readers": { "contains": $role1_0 }}))
    #end
    #set( $role1_1 = $util.defaultIfNull($ctx.identity.claims.get("username"), $util.defaultIfNull($ctx.identity.claims.get("cognito:username"), null)) )
    #if( !$util.isNull($role1_1) )
      $util.qr($authFilter.add({"readers": { "contains": $role1_1 }}))
    #end
    #if( !$authFilter.isEmpty() )
      $util.qr($ctx.stash.put("authFilter", { "or": $authFilter }))
    #end
  #end
#end
#if( !$isAuthorized && $util.isNull($ctx.stash.authFilter) )
$util.unauthorized()
#end
$util.toJson({"version":"2018-05-29","payload":{}})
## [End] Authorization Steps. **
```

**Comment by jo2** [comment]
ok, thanks! I'll try it out! It may take some days though, because I'm having some issues with the amplify cli.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
