### ISSUE TITLE
Field-level authorization rules with custom ownerField

### ISSUE THREAD

**Issue by r-thefork** [aws-amplify/amplify-category-api#1648]
### Amplify CLI Version

12.1.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

Given this schema:
```graphql
type Order 
@model 
@auth(rules: [{allow: owner, ownerField: "userID"}])
{
  id: ID! @auth(rules: [{allow: owner, operations: [read, update, delete]}])
  userID: String! @auth(rules: [{allow: owner, operations: [read]}])
  products: [String]
}
```

Running `amplify push`,  an error occurs after confirming the changes:
**When using field-level authorization rules you need to add rules to all of the model's required fields with at least read permissions. Found model "DraftOrder" with required fields ["id","userID"] missing field-level authorization rules.**

The field-level authorization rules have already been added, unless I am missing something.

### Expected behavior

The schema should be valid.

### Reproduction steps

1. Create the provided schema.
2. Run `amplify push`

### Log output

<details>

```
# Put your logs below this line
When using field-level authorization rules you need to add rules to all of the model's required fields with at least read permissions. Found model "DraftOrder" with required fields ["id","userID"] missing field-level authorization rules.

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hey @r-thefork, Have you had a chance to try out the suggestion provided by Josef earlier?

**Comment by alharris-at** [comment]
The comment by Josef is accurate, technically `owner` auth and `owner with ownerField` auth are managed as two different auth modes, since `owner` defaults with `owner with ownerField "owner"` internally, which won't align w/ your field level `owner with ownerField "uerID"`.

**Comment by AnilMaktala** [comment]
Hi 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment. This way, we can reopen the issue and provide you with better assistance.

Thank you!
