### ISSUE TITLE
Different authorization for GET and UPDATE

### ISSUE THREAD

**Issue by biller-aivy** [aws-amplify/amplify-category-api#1652]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.6.0

### Amplify CLI Version

12.1.1

### What operating system are you using?

macOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

- 

### Describe the bug

When I use: 

```
query MyQuery {
  getCareer(id: "f8489c8f-b45a-4c09-8e33-fe755f6b8346") {
    id
    career_analyse
  }
}

mutation MyMutation {
  updateCareer(input: {id: "f8489c8f-b45a-4c09-8e33-fe755f6b8346", name: "change"}) {
    authorized
    career_analyse
  }
}
```

With this Schema: 

```
type Career
  @model
  @auth(
    rules: [
      { allow: groups, groups: ["__admin"] }
      { allow: private, provider: iam }
      { allow: private, operations: [read, create] }
      { allow: public, provider: iam, operations: [read] }
      { allow: groups, groupsField: "partner_id" }
      { allow: groups, groupsField: "authorized" }
    ]
  ) {
  id: ID!
  name: String
  career_analyse: AWSJSON
    @auth(
      rules: [
        { allow: groups, groups: ["__admin"] }
        { allow: groups, groupsField: "partner_id" }
        { allow: groups, groupsField: "authorized" }
      ]
    )
  createdAt: String
  updatedAt: String
}
```

The Response is: 

```
{
  "data": {
    "updateCareer": {
      "id": "f8489c8f-b45a-4c09-8e33-fe755f6b8346",
      "career_analyse": null
    }
  }
}
```

```
{
  "data": {
    "getCareer": {
      "id": "f8489c8f-b45a-4c09-8e33-fe755f6b8346",
      "career_analyse": "{\"icc....
    }
  }
}
```

### Expected behavior

The same rules should apply for an update. 

### Reproduction steps

Try out the Auth Rules 

### Project Identifier

⠹ Sending zip
DiagnoseReportUploadError
✖ Sending zip

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hey @biller-aivy, Thank you for bringing this to our attention. We are currently working on reproducing the issue. Could you kindly inform us about the authorization method you used for the read and update operations?

**Comment by biller-aivy** [comment]
It's cognito auth users.

**Comment by biller-aivy** [comment]
@AnilMaktala do you need more information? Or the complete Schema? For the career?

**Comment by AnilMaktala** [comment]
Hey @biller-aivy, We appreciate the additional information you have provided. We will make an effort to replicate the issue and will reach out to you if further details are required.

**Comment by AnilMaktala** [comment]
Hey @biller-aivy, By following the steps outlined in the description, we have successfully replicated the issue. Therefore, we are categorizing it as a bug for the team to conduct further evaluation.

<img width="1374" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/9dff88a2-2344-4e7a-b0bc-6594caec156f">

**Comment by biller-aivy** [comment]
any news here? its important because we can't open our system for all users to get the data.

**Comment by biller-aivy** [comment]
Any news here @sundersc @AnilMaktala 

I could help here if needed.

**Comment by sundersc** [comment]
Hey @biller-aivy, The field `career_analyse` is intentionally set to `null` to protect the data from subscribed clients. The way subscriptions work is they listen to mutations and directly forward the results of a mutation to the subscribed clients using different authorization modes. The individual messages are not validated against the auth rules.

The auth rules on the field `career_analyse` is restrictive than what is defined in the model-level. With the provided schema, if a client is connecting with `iam::public` rule, we shouldn't allow this user to view the field `career_analyse`. Currently, it is not possible to redact a field in AppSync for subscriptions based on authorization mode. That's why we over-redact the restricted fields.

If you are not using subscriptions, you turn off the subscriptions in the `@model(subscriptions: null)` directive. Then the mutation response will display the restrictive field.

```graphql
type Career
  @model
  @auth(
    rules: [
      { allow: groups, groups: ["__admin"] }
      { allow: private, provider: iam }
      { allow: private, operations: [read, create] }
      { allow: public, provider: iam, operations: [read] }
      { allow: groups, groupsField: "partner_id" }
      { allow: groups, groupsField: "authorized" }
    ]
  ) {
  id: ID!
  name: String
  career_analyse: AWSJSON
    @auth(
      rules: [
        { allow: groups, groups: ["__admin"] }
        { allow: groups, groupsField: "partner_id" }
        { allow: groups, groupsField: "authorized" }
      ]
    )
  createdAt: String
  updatedAt: String
}
```

The behavior is called out in the docs.
https://docs.amplify.aws/gen1/react/build-a-backend/graphqlapi/customize-authorization-rules/#field-level-authorization-rules

**Comment by biller-aivy** [comment]
> Hey @biller-aivy, The field `career_analyse` is intentionally set to `null` to protect the data from subscribed clients. The way subscriptions work is they listen to mutations and directly forward the results of a mutation to the subscribed clients using different authorization modes. The individual messages are not validated against the auth rules.
> 
> The auth rules on the field `career_analyse` is restrictive than what is defined in the model-level. With the provided schema, if a client is connecting with `iam::public` rule, we shouldn't allow this user to view the field `career_analyse`. Currently, it is not possible to redact a field in AppSync for subscriptions based on authorization mode. That's why we over-redact the restricted fields.
> 
> If you are not using subscriptions, you turn off the subscriptions in the `@model(subscriptions: null)` directive. Then the mutation response will display the restrictive field.
> 
> ```graphql
> type Career
>   @model
>   @auth(
>     rules: [
>       { allow: groups, groups: ["__admin"] }
>       { allow: private, provider: iam }
>       { allow: private, operations: [read, create] }
>       { allow: public, provider: iam, operations: [read] }
>       { allow: groups, groupsField: "partner_id" }
>       { allow: groups, groupsField: "authorized" }
>     ]
>   ) {
>   id: ID!
>   name: String
>   career_analyse: AWSJSON
>     @auth(
>       rules: [
>         { allow: groups, groups: ["__admin"] }
>         { allow: groups, groupsField: "partner_id" }
>         { allow: groups, groupsField: "authorized" }
>       ]
>     )
>   createdAt: String
>   updatedAt: String
> }
> ```
> 
> The behavior is called out in the docs. https://docs.amplify.aws/gen1/react/build-a-backend/graphqlapi/customize-authorization-rules/#field-level-authorization-rules

But I don't use subscription. The diff comes from a simple update call?!

**Comment by sundersc** [comment]
Though you are not using subscriptions, it is enabled on the model. You can disable subscriptions using one of the below options.

```graphql
type Career
  @model(subscriptions: null) ## or subscriptions: { level: off }
  @auth(
    rules: [
       ...
       ...
    ]
  ) {
       ...
       ...
}
```

**Comment by biller-aivy** [comment]
> Though you are not using subscriptions, it is enabled on the model. You can disable subscriptions using one of the below options.
> 
> 
> 
> ```graphql
> 
> type Career
> 
>   @model(subscriptions: null) ## or subscriptions: { level: off }
> 
>   @auth(
> 
>     rules: [
> 
>        ...
> 
>        ...
> 
>     ]
> 
>   ) {
> 
>        ...
> 
>        ...
> 
> }
> 
> ```

Mhhh, and than the res of the update mutation is the same like the get?

**Comment by dpilch** [comment]
Correct, if you disable subscriptions for this model the `career_analyse` will no longer be redacted in the update mutation result.
