### ISSUE TITLE
Issue with mock api when using @searchable and python 3.9

### ISSUE THREAD

**Issue by esteban-serfe** [aws-amplify/amplify-category-api#1668]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18

### Amplify CLI Version

12.1.1

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No Manual changes made

### Describe the bug

When trying to run the mock on the API using an entity that as the @searchable feature (in this case Message), the following error appears.
```bash
$ amplify mock api
⚠️ Your instance type for OpenSearch is t2.small.elasticsearch, you may experience performance issues or data loss. Consider reconfiguring with the instructions here https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#set-up-opensearch-for-production-environments
✅ GraphQL schema compiled successfully.

Edit your schema at /home/node/app/amplify/backend/api/test/schema.graphql or place .graphql files in a directory at /home/node/app/amplify/backend/api/test/schema
Creating index gsi-Conversation.messages on MessageTable
Building the searchable lambda trigger
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Building requirements...
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'egg_info'
Failed to start API Mocking. Running cleanup tasks.
Reason: Unable to start the local OpenSearch Instance.
```
Based on my research, the problem is that on python 3.9 the setup.py file used for the mock searchable lambda is not up to date . The file contais an old version of the setup.py that needs to be updated to:

```python
from setuptools import setup, find_packages

setup(
    name="src",
    version="1.0",
    packages=find_packages(where="src", exclude="index"),
)
```

Original file: https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-util-mock/resources/mock-searchable-lambda-trigger/source-files/setup.py

### Expected behavior

The mock should build the lambda without issue after the proposed change.

### Reproduction steps

1. Create a sample project with an entity with searchable directive.
2. using python 3.9 on the system
3. run the amplicy mock command

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi @esteban-serfe, Thank you for bringing this to our attention. We have tried to replicate the issue using Python 3.9.11 version, but we were not successful. It appears to be a setup issue with Python. Can you please verify and confirm if the setup for Python 3.9 version was successful?

<img width="458" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/486caed2-57ef-42d2-b580-f5793354d630">

**Comment by esteban-serfe** [comment]
Hi @AnilMaktala 
My current project is a Javascript project which uses Python for some lambdas.

Currently I'm using:
python 3.9.2
pip 23.1.2
inside a docker container based on node 18 which also have venv all the other dependencies of the system (venv for example)

The issue mentione with the setup.py file was present on the lambdas using python that were added into the project, but in this case, the setup.py is generated each time the mock is run so we cannot "overwrite" it.

**Comment by esteban-serfe** [comment]
Update here. The python installed was actually 3.8.17.
Adding manually the 3.9.17 not works as expected, but got stuck on @qndrey comment when trying to run the mock.

**Comment by qndrey** [comment]
I have tried with3.8.17 and 3.9 python. I checked it in our CI pipeline and it works there fine. I have M1 Apple laptop.

Maybe there is some way to debug it and try to find some errors?

**Comment by esteban-serfe** [comment]
Yesterday I downgraded to version 12.0.0 of aws-amplify/cli and got your error. Unsure how to debug this as amplify command is binary.

**Comment by phani-srikar** [comment]
Hi 👋 , can you check if your `JAVA_HOME` is set to a valid path to JDK? Some of the [previous issues](https://github.com/aws-amplify/amplify-category-api/issues/1243#issuecomment-1494902885) we've seen were missing this. In addition, can you also run `~/.amplify/lib/aws-amplify-amplify-opensearch-simulator/opensearch/1.3.0/opensearchLib/bin/opensearch` from your system directly and see if the logs indicate the specifc reason for failure?

**Comment by qndrey** [comment]
@phani-srikar 
Must be something wrong with it.
```
export JAVA_HOME=/usr/bin/java
java --version
openjdk 20.0.1 2023-04-18
OpenJDK Runtime Environment Homebrew (build 20.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 20.0.1, mixed mode, sharing)

~/.amplify/lib/aws-amplify-amplify-opensearch-simulator/opensearch/1.3.0/opensearchLib/bin/opensearch
could not find java in JAVA_HOME at /usr/bin/java/bin/java
```

As you can see  JAVA_HOME at /usr/bin/java/bin/java is a wrong path

**Comment by esteban-serfe** [comment]
Hi @phani-srikar 
after doing some testing found the issue.

The JAVA_HOME had the /bin at the end, but it should not have it as the command add it automatically. With the correct path, running the command alone works as expected.

I have another issue after that is not related to this ticket.

**Comment by AnilMaktala** [comment]
Hi @esteban-serfe and @qndrey, Thank you for the confirmation. We will now proceed to close this issue, as the problem has been resolved by setting the correct Java path.
