### ISSUE TITLE
Custom 'Sort By' Query not working

### ISSUE THREAD

**Issue by dan-codes1** [aws-amplify/amplify-category-api#1675]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

12.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

Hey. I am trying to sort my queries by date as suggested here https://docs.amplify.aws/guides/api-graphql/query-with-sorting/q/platform/js/#implementation buy I keep running into an error in CLI when I edit my schema and run `amplify push`.

The error I get is similar to that in https://github.com/aws-amplify/amplify-cli/issues/2797 but the solution is not clear.

Here is my schema:

```graphql
query ListMessages(
  $filter: ModelMessageFilterInput
  $limit: Int
  $nextToken: String
) {
  listMessages(filter: $filter, limit: $limit, nextToken: $nextToken) {
    items {
      id
      type
      text
      sentAt
      isRead
      editedAt
      createdAt
      updatedAt
      messageSenderId
      messageSpaceId
      owner
    }
    nextToken
  }
}

type Message @model @auth(rules: [{allow: private, operations: [read]}, {allow: owner}]) {
  id: ID! @index(name: "listMessages", queryField: "listMessages", sortKeyFields: ["sentAt"])
  type: MessageType!
  text: String
  sentAt: AWSDateTime!
  isRead: Boolean!
  sender: User! @hasOne
  space: MessageSpace! @hasOne
  editedAt: AWSDateTime
}
```

Here is the error message:
```
🛑 Object type extension 'Query' cannot redeclare field listMessages
```

### Expected behavior

I expect it to work.

### Reproduction steps

Try to follow the description

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by dan-codes1** [comment]
@josefaidt I understand that, thanks for letting me know. Just to clarify btw, I use amplify-swift. I just saw it wasn't mentioned in the initial description.

**Comment by josefaidt** [comment]
Hey @dan-codes1 , no worries! Is the code block from the original post in your schema? Or are you having issues overriding this query?

**Comment by dan-codes1** [comment]
@josefaidt  yes it is in my schema

**Comment by josefaidt** [comment]
@dan-codes1 this query will be automatically generated for you when defining the `Messages` model with `@model`. It is safe to remove from your schema, run `amplify codegen`, and begin using it in your Swift application

**Comment by dan-codes1** [comment]
@josefaidt the error still occurs after this. Is the initial description of the bug clear enough?

**Comment by chrisbonifacio** [comment]
@dan-codes1 I think it might help if you gave the steps you took to reproduce the error.

We'd need to know what your `amplify/backend/api/<apiName>/schema.graphql` looks like. It isn't clear whether or not `query ListMessages...` mentioned in the description is in that file or somewhere else in your app code.

It is possible to define custom queries and mutation in the schema but if you are trying to change the implementation of the auto-generated `listMessages` query, you'll have to nest it in a `type Query` in the schema.graphql similar to the documentation here:

https://docs.amplify.aws/cli/graphql/custom-business-logic/#query-string

**Comment by dan-codes1** [comment]
@chrisbonifacio,  I now get what @josefaidt  was trying to say; that the query is supposed to be a custom query and not meant to be a modified version of the generated one. I tried to make it a custom query and it runs without errors but returns no data.

Here is the custom Query:

        """
        query messagesByDate {
        messagesByDate(modelName: "Messages"
                       sortDirection: DESC
        ) {
            items {
              id
              type
              text
              sentAt
              isRead
              editedAt
              createdAt
              updatedAt
              messageSenderId
              messageSpaceId
              owner
              __typename
            }
            nextToken
            __typename
          }
        }
        """

Here is how it is called:

`let test = GraphQLRequest<Message>.list(Message.self, where: predicate, limit: limit)
   let req = GraphQLRequest(document: GraphQlDocuments.messagesByDate(limit: limit, spaceId: spaceId),
                                     variables: test.variables,
                                     responseType: List<Message>.self)
     let request = try await Amplify.API.query(request: req)
     let messages = try request.get() `
`messages` returns an empty list; it shouldn't

this is my model schema

type Message @model @auth(rules: [{allow: private, operations: [read]}, {allow: owner}]) {
  id: ID!
  type: MessageType!
  modelName: String! @index(name: "messagesByDate", queryField: "messagesByDate", sortKeyFields: ["sentAt"])
  text: String
  sentAt: AWSDateTime!
  isRead: Boolean!
  sender: User! @hasOne
  space: MessageSpace! @hasOne
  editedAt: AWSDateTime
}


Steps to reproduce:
Create a model and try to sort it with a custom query as done here: https://docs.amplify.aws/guides/api-graphql/query-with-sorting/q/platform/ios/#implementation
You can also try to use my exact query and approach.

**Comment by dan-codes1** [comment]
@josefaidt @chrisbonifacio any updates on this? Been 2 weeks.
