### ISSUE TITLE
populateownerfieldforstaticgroupauth flag has zero effect when app is deployed via CI/CD

### ISSUE THREAD

**Issue by jk171505** [aws-amplify/amplify-category-api#1679]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.4.0

### Amplify CLI Version

12.1.1

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

The flag `populateownerfieldforstaticgroupauth` has no effect when the app is deployed in other environments via ci/cd. Looks like expected behaviour isn't replicated in other environments.

### Expected behavior

The auto-population of owner field if the user is already authorized by static user pool authorization rules is replicated across all environments to which the source environment was merged in and are deployed via auto-build & ci/cd.

### Reproduction steps

1. Set the `populateownerfieldforstaticgroupauth` to true.
2. Push the changes  using `amplify push`
3. Test the behaviour on the feature environment (works as expected in my case)
4. Commit and push the changes via git.
5. Create PR then merge the feature branch into production branch, that has Auto-build enabled.
6. Test the behaviour on production environment (the owner field is not populated, which in turn causes subscription on that model to not fire when the owner was specified)

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi @jk171505, Thank you for bringing this up. Would it be possible for you to share the VTL for both the Production and lower environments?

**Comment by AnilMaktala** [comment]
Hey @jk171505, Are you still experiencing this issue?

**Comment by AnilMaktala** [comment]
Hi 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment and provide us with the information our team had previously asked for. This way, we can reopen the issue and provide you with better assistance.

Thank you!
