### ISSUE TITLE
Question about architecture with custom VTL (via slot)

### ISSUE THREAD

**Issue by OperationalFallacy** [aws-amplify/amplify-category-api#1682]
### Amplify CLI Version

12.1.1

### Question

Hi,

We're just starting with AppSync. Is this workflow possible to achieve?

The architecture is for a chat app (with AI on the other end), we're looking to run Lambda functions to get additional data and enrich messages sent to AI API. The reason we're looking at VTL is to avoid adding mutations outside of AppSync "core", e.g. in Lambda functions.

This is the workflow:

1. **Client creates a mutation:** The client sends a mutation request to create a new `ChatMessage`.

2. **AppSync triggers the pipeline resolver:** The mutation request is received by AWS AppSync. Given that we defined a custom pipeline resolver, it gets triggered.

3. **Mutation stores the `ChatMessage`**: Before invoking the Lambda function, the mutation request is processed normally, and the new `ChatMessage` from the user is added to the `Chat`.

4. **Invoke the Lambda function via the VTL script:** The VTL script is executed, which includes a call to invoke our Lambda function. The newly created `ChatMessage` is passed as an argument to the function.

5. **Lambda function processes the message and sends it to the GPT model:** The Lambda function receives the `ChatMessage`, amends it, and sends it to the GPT model.

6. **Lambda function returns the GPT model's response:** The GPT model processes the message and sends a response back to the Lambda function. The function then returns this response.

7. **VTL script processes the Lambda function's response:** The VTL script receives the response from the Lambda function. If the function returned a `ChatMessage`, the script constructs a new `ChatMessage` with the GPT model's response.

8. **VTL script initiates another mutation request:** The script sends another mutation request to create a new `ChatMessage` in the chat's history. This request is handled by the default AppSync resolvers, which use the auto-generated GraphQL mutations to add the new message to the `ChatMessage` DynamoDB table.

9. **Client receives the response:** Once the mutation is successful, the response is sent back to the client. The client receives the updated `Chat` object, including the new `ChatMessage` added by the GPT model.

**Comment by AaronZyLee** [comment]
I think it is achievable. One thing to note is that step 4 is not strictly correct. The lambda cannot be invoked directly by VTL script. The way to do it is to add a new slot in the pipeline resolver and set the datasource to lambda function. The VTL script will generate the request object for invoking the lambdas. 

The same as the mutation step afterwards. Just add a new slot with datasource as the dynamoDB table and have the VTL script generate the dynamoDB request.

**Comment by OperationalFallacy** [comment]
Thank you, @AaronZyLee
We've realized that the VTL route will require a significant amount of cognitive load from the developers, and its much easier to have Lambda functions defined by models of the scheme.graphql and perform requests massaging.

We've also managed to make generated GraphQL queries and interfaces available in Amplify Lambda functions, which simplified development even further.
