### ISSUE TITLE
Removal of API Key authorisation mode - unclear procedure, ticking time bomb, have had to rebuild prod

### ISSUE THREAD

**Issue by johnemcbride** [aws-amplify/amplify-category-api#1691]
### Amplify CLI Version

12.1.1

### Question

I just got burned this weekend by an expired API key in apps-sync, that I don't even use.  Took a couple of days to recover production environment, which practically had to be rebuilt.

I noticed the expiry is in one week so another ticking time bomb.

I tried deleting api key from the additional auth modes in backend-config.js and pushing, but still the key is there.
I also tried amplify update api, and unchecked the api key auth mode and pushed, but now I get errors:

Now I get errors:
```
Resource Name: functioneventFactory (AWS::CloudFormation::Stack)
Event Type: update
Reason: Output 'GraphQLAPIKeyOutput' not found in stack 'arn:aws:cloudformation:eu-west-2:228447865234:stack/amplify-amplifyapp-dev-230900-apiamplifyapp-PJIMCMWIT2DT/e13b8590-b3cf-11ed-8254-0ae24c717924'
URL: https://console.aws.amazon.com/cloudformation/home?region=eu-west-2#/stacks/arn%3Aaws%3Acloudformation%3Aeu-west-2%3A228447865234%3Astack%2Famplify-amplifyapp-dev-230900%2F10ffdfc0-b3cf-11ed-a158-0af30e681a10/events
```

Please what is the procedure to get rid of these api keys.

**Comment by phani-srikar** [comment]
Hi @johnemcbride, the right way to remove API key auth is via `amplify update api`.
- Change the default Authorization mode to something other than API Key Auth
- Choose `yes` for `Configure additional auth types?` and make sure to un-check the API key Auth

In your next `amplify push`, the key should be deleted from your AppSync backend.
I've tested the above steps and was able to remove it. You might be running into the error above since you've made some manual changes to the backend config file. I would suggest reverting those changes and re-trying. You might want to peek into the backend config file inside `#current-cloud-backend` folder to get an idea of how the file was before you made those changes.

**Comment by johnemcbride** [comment]
OK, I re-cloned a fresh repo.  Made a dummy change in schema graphql and tested an amplify push - all fine.

Then I followed the procedure above to update api, unticking API key.

The next Amplify push resulted in the same tirade of errors:

Every lambda function complain as follows:

Name: functionregisterNewUser (AWS::CloudFormation::Stack), Event Type: update, Reason: Output 'GraphQLAPIKeyOutput' not found in stack 'arn:aws:cloudformation:eu-west-2:228447865234:stack/amplify-amplifyapp-dev-230900-apiamplifyapp-PJIMCMWIT2DT/e13b8590-b3cf-11ed-8254-0ae24c717924', IsCustomResource: false

I am sure I've screwed it up with all my attempts at removing the API Key - setting various permutations of the  "CreateAPIKey" flag in parameters.json.

Is there a manual workaround I need to apply to get round this error on all my lambdas?

**Comment by johnemcbride** [comment]
Cloudformation forene of the functions below:

`{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "{\"createdOn\":\"Mac\",\"createdBy\":\"Amplify\",\"createdWith\":\"12.1.1\",\"stackType\":\"function-Lambda\",\"metadata\":{}}",
  "Parameters": {
    "CloudWatchRule": {
      "Type": "String",
      "Default": "NONE",
      "Description": " Schedule Expression"
    },
    "deploymentBucketName": {
      "Type": "String"
    },
    "env": {
      "Type": "String"
    },
    "s3Key": {
      "Type": "String"
    },
    "apiamplifyappGraphQLAPIIdOutput": {
      "Type": "String",
      "Default": "apiamplifyappGraphQLAPIIdOutput"
    },
    "apiamplifyappGraphQLAPIEndpointOutput": {
      "Type": "String",
      "Default": "apiamplifyappGraphQLAPIEndpointOutput"
    },
    "apiamplifyappGraphQLAPIKeyOutput": {
      "Type": "String",
      "Default": "apiamplifyappGraphQLAPIKeyOutput"
    },
    "authamplifyapp0cb91442UserPoolId": {
      "Type": "String",
      "Default": "authamplifyapp0cb91442UserPoolId"
    }
  },
  "Conditions": {
    "ShouldNotCreateEnvResources": {
      "Fn::Equals": [
        {
          "Ref": "env"
        },
        "NONE"
      ]
    }
  },
  "Resources": {
    "LambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Metadata": {
        "aws:asset:path": "./src",
        "aws:asset:property": "Code"
      },
      "Properties": {
        "Code": {
          "S3Bucket": {
            "Ref": "deploymentBucketName"
          },
          "S3Key": {
            "Ref": "s3Key"
          }
        },
        "Handler": "index.handler",
        "FunctionName": {
          "Fn::If": [
            "ShouldNotCreateEnvResources",
            "bulkMigrateCognitoToDDB",
            {
              "Fn::Join": [
                "",
                [
                  "bulkMigrateCognitoToDDB",
                  "-",
                  {
                    "Ref": "env"
                  }
                ]
              ]
            }
          ]
        },
        "Environment": {
          "Variables": {
            "ENV": {
              "Ref": "env"
            },
            "REGION": {
              "Ref": "AWS::Region"
            },
            "API_AMPLIFYAPP_GRAPHQLAPIIDOUTPUT": {
              "Ref": "apiamplifyappGraphQLAPIIdOutput"
            },
            "API_AMPLIFYAPP_GRAPHQLAPIENDPOINTOUTPUT": {
              "Ref": "apiamplifyappGraphQLAPIEndpointOutput"
            },
            "API_AMPLIFYAPP_GRAPHQLAPIKEYOUTPUT": {
              "Ref": "apiamplifyappGraphQLAPIKeyOutput"
            },
            "AUTH_AMPLIFYAPP0CB91442_USERPOOLID": {
              "Ref": "authamplifyapp0cb91442UserPoolId"
            }
          }
        },
        "Role": {
          "Fn::GetAtt": [
            "LambdaExecutionRole",
            "Arn"
          ]
        },
        "Runtime": "nodejs18.x",
        "Layers": [],
        "Timeout": 25
      }
    },
    "LambdaExecutionRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "RoleName": {
          "Fn::If": [
            "ShouldNotCreateEnvResources",
            "amplifyappLambdaRole4a7498f3",
            {
              "Fn::Join": [
                "",
                [
                  "amplifyappLambdaRole4a7498f3",
                  "-",
                  {
                    "Ref": "env"
                  }
                ]
              ]
            }
          ]
        },
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        }
      }
    },
    "lambdaexecutionpolicy": {
      "DependsOn": [
        "LambdaExecutionRole"
      ],
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "lambda-execution-policy",
        "Roles": [
          {
            "Ref": "LambdaExecutionRole"
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": {
                "Fn::Sub": [
                  "arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*",
                  {
                    "region": {
                      "Ref": "AWS::Region"
                    },
                    "account": {
                      "Ref": "AWS::AccountId"
                    },
                    "lambda": {
                      "Ref": "LambdaFunction"
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    },
    "AmplifyResourcesPolicy": {
      "DependsOn": [
        "LambdaExecutionRole"
      ],
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "amplify-lambda-execution-policy",
        "Roles": [
          {
            "Ref": "LambdaExecutionRole"
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "appsync:GraphQL"
              ],
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:appsync:",
                      {
                        "Ref": "AWS::Region"
                      },
                      ":",
                      {
                        "Ref": "AWS::AccountId"
                      },
                      ":apis/",
                      {
                        "Ref": "apiamplifyappGraphQLAPIIdOutput"
                      },
                      "/types/Query/*"
                    ]
                  ]
                },
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:appsync:",
                      {
                        "Ref": "AWS::Region"
                      },
                      ":",
                      {
                        "Ref": "AWS::AccountId"
                      },
                      ":apis/",
                      {
                        "Ref": "apiamplifyappGraphQLAPIIdOutput"
                      },
                      "/types/Mutation/*"
                    ]
                  ]
                }
              ]
            },
            {
              "Effect": "Allow",
              "Action": [
                "cognito-identity:Describe*",
                "cognito-identity:Get*",
                "cognito-identity:List*",
                "cognito-idp:Describe*",
                "cognito-idp:AdminGetDevice",
                "cognito-idp:AdminGetUser",
                "cognito-idp:AdminList*",
                "cognito-idp:List*",
                "cognito-sync:Describe*",
                "cognito-sync:Get*",
                "cognito-sync:List*",
                "iam:ListOpenIdConnectProviders",
                "iam:ListRoles",
                "sns:ListPlatformApplications",
                "cognito-idp:ForgotPassword",
                "cognito-idp:UpdateAuthEventFeedback",
                "cognito-idp:UpdateResourceServer",
                "cognito-idp:UpdateUserPoolClient",
                "cognito-idp:AdminUpdateUserAttributes",
                "cognito-idp:UpdateUserAttributes",
                "cognito-idp:UpdateUserPoolDomain",
                "cognito-idp:UpdateIdentityProvider",
                "cognito-idp:UpdateGroup",
                "cognito-idp:AdminUpdateAuthEventFeedback",
                "cognito-idp:UpdateDeviceStatus",
                "cognito-idp:UpdateUserPool"
              ],
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:cognito-idp:",
                      {
                        "Ref": "AWS::Region"
                      },
                      ":",
                      {
                        "Ref": "AWS::AccountId"
                      },
                      ":userpool/",
                      {
                        "Ref": "authamplifyapp0cb91442UserPoolId"
                      }
                    ]
                  ]
                }
              ]
            }
          ]
        }
      }
    }
  },
  "Outputs": {
    "Name": {
      "Value": {
        "Ref": "LambdaFunction"
      }
    },
    "Arn": {
      "Value": {
        "Fn::GetAtt": [
          "LambdaFunction",
          "Arn"
        ]
      }
    },
    "Region": {
      "Value": {
        "Ref": "AWS::Region"
      }
    },
    "LambdaExecutionRole": {
      "Value": {
        "Ref": "LambdaExecutionRole"
      }
    },
    "LambdaExecutionRoleArn": {
      "Value": {
        "Fn::GetAtt": [
          "LambdaExecutionRole",
          "Arn"
        ]
      }
    }
  }
}`

Should I manually remove the GraphQLAPIKeyOutput bits?

**Comment by johnemcbride** [comment]
I have readied the key, got everything working and then a clean removal as per above.

Removal does not work - everything dies with this message:


`
🛑 The following resources failed to deploy:
Resource Name: functionmailChimpEventListener (AWS::CloudFormation::Stack)
Event Type: update
Reason: Output 'GraphQLAPIKeyOutput' not found in stack 'arn:aws:cloudformation:eu-west-2:228447865234:stack/amplify-amplifyapp-dev-230900-apiamplifyapp-PJIMCMWIT2DT/e13b8590-b3cf-11ed-8254-0ae24c717924'
URL: https://console.aws.amazon.com/cloudformation/home?region=eu-west-2#/stacks/arn%3Aaws%3Acloudformation%3Aeu-west-2%3A228447865234%3Astack%2Famplify-amplifyapp-dev-230900%2F10ffdfc0-b3cf-11ed-a158-0af30e681a10/events


Resource Name: functionbulkMigrateCognitoToDDB (AWS::CloudFormation::Stack)
Event Type: update
Reason: Output 'GraphQLAPIKeyOutput' not found in stack 'arn:aws:cloudformation:eu-west-2:228447865234:stack/amplify-amplifyapp-dev-230900-apiamplifyapp-PJIMCMWIT2DT/e13b8590-b3cf-11ed-8254-0ae24c717924'
URL: https://console.aws.amazon.com/cloudformation/home?region=eu-west-2#/stacks/arn%3Aaws%3Acloudformation%3Aeu-west-2%3A228447865234%3Astack%2Famplify-amplifyapp-dev-230900%2F10ffdfc0-b3cf-11ed-a158-0af30e681a10/events


Resource Name: functionstripeHandler (AWS::CloudFormation::Stack)
Event Type: update
Reason: Output 'GraphQLAPIKeyOutput' not found in stack 'arn:aws:cloudformation:eu-west-2:228447865234:stack/amplify-amplifyapp-dev-230900-apiamplifyapp-PJIMCMWIT2DT/e13b8590-b3cf-11ed-8254-0ae24c717924'
URL: https://console.aws.amazon.com/cloudformation/home?region=eu-west-2#/stacks/arn%3Aaws%3Acloudformation%3Aeu-west-2%3A228447865234%3Astack%2Famplify-amplifyapp-dev-230900%2F10ffdfc0-b3cf-11ed-a158-0af30e681a10/events


Resource Name: functionincomingwebhooks (AWS::CloudFormation::Stack)
Event Type: update
Reason: Output 'GraphQLAPIKeyOutput' not found in stack 'arn:aws:cloudformation:eu-west-2:228447865234:stack/amplify-amplifyapp-dev-230900-apiamplifyapp-PJIMCMWIT2DT/e13b8590-b3cf-11ed-8254-0ae24c717924'
URL: https://console.aws.amazon.com/cloudformation/home?region=eu-west-2#/stacks/arn%3Aaws%3Acloudformation%3Aeu-west-2%3A228447865234%3Astack%2Famplify-amplifyapp-dev-230900%2F10ffdfc0-b3cf-11ed-a158-0af30e681a10/events


Resource Name: functionregisterNewUser (AWS::CloudFormation::Stack)
Event Type: update
Reason: Output 'GraphQLAPIKeyOutput' not found in stack 'arn:aws:cloudformation:eu-west-2:228447865234:stack/amplify-amplifyapp-dev-230900-apiamplifyapp-PJIMCMWIT2DT/e13b8590-b3cf-11ed-8254-0ae24c717924'
URL: https://console.aws.amazon.com/cloudformation/home?region=eu-west-2#/stacks/arn%3Aaws%3Acloudformation%3Aeu-west-2%3A228447865234%3Astack%2Famplify-amplifyapp-dev-230900%2F10ffdfc0-b3cf-11ed-a158-0af30e681a10/events


Resource Name: functionenrolmentmanager (AWS::CloudFormation::Stack)
Event Type: update
Reason: Output 'GraphQLAPIKeyOutput' not found in stack 'arn:aws:cloudformation:eu-west-2:228447865234:stack/amplify-amplifyapp-dev-230900-apiamplifyapp-PJIMCMWIT2DT/e13b8590-b3cf-11ed-8254-0ae24c717924'
URL: https://console.aws.amazon.com/cloudformation/home?region=eu-west-2#/stacks/arn%3Aaws%3Acloudformation%3Aeu-west-2%3A228447865234%3Astack%2Famplify-amplifyapp-dev-230900%2F10ffdfc0-b3cf-11ed-a158-0af30e681a10/events


Resource Name: functioneventFactory (AWS::CloudFormation::Stack)
Event Type: update
Reason: Output 'GraphQLAPIKeyOutput' not found in stack 'arn:aws:cloudformation:eu-west-2:228447865234:stack/amplify-amplifyapp-dev-230900-apiamplifyapp-PJIMCMWIT2DT/e13b8590-b3cf-11ed-8254-0ae24c717924'
URL: https://console.aws.amazon.com/cloudformation/home?region=eu-west-2#/stacks/arn%3Aaws%3Acloudformation%3Aeu-west-2%3A228447865234%3Astack%2Famplify-amplifyapp-dev-230900%2F10ffdfc0-b3cf-11ed-a158-0af30e681a10/events`


Seems the dependency is removed too soon?

**Comment by johnemcbride** [comment]
⚠️ If other resources depend on this API, run "amplify update <category>" and reselect this API to remove the dependency on the API key.


OK ^^. will do that.

**Comment by johnemcbride** [comment]
Now I know.  Thx.
