### ISSUE TITLE
GraphQL API change failed due to blank comment

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-category-api#173]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

15.7

### Amplify CLI Version

5.0.1

### What operating system are you using?

Windows 10 / Ubuntu 20.04 WSL

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I'd recently made some updates to my schema.graphql file but failed to fill in a comment for a field. E.g

```graphql

	"""
	"""
	videoId: String
	"""
	An array of S3 UrLs
	"""
	publications: [String] @function(name: "getPublicationSignedUrl-${env}")
```

Running `amplify api gql-compile` returned a succesful compilation, but upon pushing the changes, the stack failed in Cloudformation with:

```
Reason: Schema Creation Status is FAILED with details: Failed to parse schema document - ensure it's a valid SDL-formatted document.
```

Updating the schema.graphql file with a valid comment fixed the issue.

### Expected behavior

Validate for blank comments on compilation of the GraphQL schema.

### Reproduction steps

1. Create a schema with a blank comment above a field.
2. Run `amplify api gql-compile` to check the schema is valid (which it isn't according to AppSync.
2. Try to push the changes
3. See that the push fails
4. Add a comment
5. Push again and see that it pushes the changes succesfully.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by renebrandel** [comment]
I'm closing this from the Amplify end as the tracking ticket as this requires changes on the AppSync service. (Tracked in the ticket above)
