### ISSUE TITLE
Not Authorized to access listEntries on type Query - Can't run amplify mock function

### ISSUE THREAD

**Issue by islalr** [aws-amplify/amplify-category-api#1769]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

12.2.3

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I've been trying to run the amplify mock function command in VS code so that I can test a lambda function I'm creating without having to deploy it each time. I created this function using the add option so roles etc. have been autogenerated. I'm building a flutter app so i can't do the amplify codegen, only amplify codegen models, if that makes any difference. 

I'm getting the following error:   
```
"statusCode": 400,
  "body": "{\"data\":{\"listUserEntries\":null},\"errors\":[{\"path\":[\"listUserEntries\"],\"data\":null,\"errorType\":\"Unauthorized\",\"errorInfo\":null,\"locations\":[{\"line\":3,\"column\":3,\"sourceName\":null}],\"message\":\"Not Authorized to access listUserEntries on type Query\"}]}"
```

I've seen several threads on GitHub talking about this issue, which suggest I redeploy my schema file to update the resolvers and prevent this from happening, but those aren't working. I've also tried **amplify api gql-compile**

If I look in the resolver for this type, i can see the authorisation for cognito and api key but not IAM. I have IAM configuration defined as an additional option through the **update api** command. I've checked in cloudformation to see what roles amplify creates to execute lambdas, and i've also added those to my local access. Still getting unauthorized. Please help, I don't want this error message to haunt my dreams anymore. 

```
type UserEntry
  @model
  @auth(
    rules: [
      { allow: owner, operations: [read, update, create] }
      { allow: private, provider: userPools,  operations: [create]}
      { allow: private, provider: iam, operations: [read, create, update]}
    ] .....
```

```

{
  "version": 1,
  "serviceConfiguration": {
    "apiName": "xxxxxxxx",
    "serviceName": "AppSync",
    "defaultAuthType": {
      "mode": "AMAZON_COGNITO_USER_POOLS",
      "cognitoUserPoolId": "xxxxxxxxxx"
    },
    "conflictResolution": {},
    "additionalAuthTypes": [
      {
        "mode": "API_KEY",
        "expirationTime": 7,
        "apiKeyExpirationDate": "2023-08-10T19:12:13.872Z",
        "keyDescription": ""
      },
      {
        "mode": "AWS_IAM"
      }
    ]
  }
}
```

```
## [Start] Authorization Steps. **
$util.qr($ctx.stash.put("hasAuth", true))
#set( $isAuthorized = false )
#set( $primaryFieldMap = {} )
#if( $util.authType() == "API Key Authorization" )

#end
#if( $util.authType() == "User Pool Authorization" )
  #if( !$isAuthorized )
    #set( $authFilter = [] )
    #set( $ownerClaim0 = $util.defaultIfNull($ctx.identity.claims.get("sub"), null) )
    #set( $currentClaim1 = $util.defaultIfNull($ctx.identity.claims.get("username"), $util.defaultIfNull($ctx.identity.claims.get("cognito:username"), null)) )
    #if( !$util.isNull($ownerClaim0) && !$util.isNull($currentClaim1) )
      #set( $ownerClaim0 = "$ownerClaim0::$currentClaim1" )
      #if( !$util.isNull($ownerClaim0) )
        $util.qr($authFilter.add({"owner": { "eq": $ownerClaim0 }}))
      #end
    #end
    #set( $role0_0 = $util.defaultIfNull($ctx.identity.claims.get("sub"), null) )
    #if( !$util.isNull($role0_0) )
      $util.qr($authFilter.add({"owner": { "eq": $role0_0 }}))
    #end
    #set( $role0_1 = $util.defaultIfNull($ctx.identity.claims.get("username"), $util.defaultIfNull($ctx.identity.claims.get("cognito:username"), null)) )
    #if( !$util.isNull($role0_1) )
      $util.qr($authFilter.add({"owner": { "eq": $role0_1 }}))
    #end
    #if( !$authFilter.isEmpty() )
      $util.qr($ctx.stash.put("authFilter", { "or": $authFilter }))
    #end
  #end
#end
#if( !$isAuthorized && $util.isNull($ctx.stash.authFilter) )
$util.unauthorized()
#end
$util.toJson({"version":"2018-05-29","payload":{}})
## [End] Authorization Steps. **

```

### Expected behavior

It authorises! 

### Reproduction steps

1. amplify add function
2. amplify push
3. adjust schema, amplify push
4. amplify mock function x
5. mock should authorize.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by islalr** [comment]
not using function option anymore.

**Comment by cjsilva-umich** [comment]
Can anyone give insight into this? I'm experiencing the same exact problem.
