### ISSUE TITLE
How do I extend Query using when using multiple files in schema/*.graphql?

### ISSUE THREAD

**Issue by Zamithal** [aws-amplify/amplify-category-api#1808]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d5wysh8nju8x2

### AWS Region

us-west-2

### Amplify Hosting feature

Backend builds

### Question

I have reached the point in my amplify project where having a single `schema.graphql` file is becoming unwieldy. I would like to divide my schema up into multiple files, and have done so:

`<project>/amplify/backend/api/<myApi>/schema/a.graphql` (name is non-ideal name but this causes it to be joined first.)

This contains only a single empty definition for Query:
```graphql
type Query
```
`<project>/amplify/backend/api/<myApi>/schema/post.graphql`

This contains a type and extends Query.
```graphql
enum PostType {
  TYPE_A,
  TYPE_B
}

extend type Query {
  createPost(
    sender: String!,
    subject: String!,
    body: String!,
    type: PostType!
  ): String!
  @auth( rules: [
    { allow: public }
  ])
  @function(name: "createPost-${env}")
```
`<project>/amplify/backend/api/<myApi>/schema/contact.graphql`

 This also contains a type and extends Query.
```graphql
enum ContactReasonType {
  CONTACT_US,
  BETA_SIGN_UP
}

extend type Query {
  sendContactEmail(
    sender: String!,
    subject: String!,
    body: String!,
    type: ContactReasonType!
  ): String!
  @auth( rules: [
    { allow: public }
  ])
  @function(name: "sendContactEmail-${env}")
}
```

Running `amplify api gql-compile` and Including just one of these will successfully compile. Including both of these will result in the following:

`🛑 Object type extension 'Query' cannot redeclare field sendContactEmail`

Using `Query` instead of `extend type Query`results in the following:

`There can be only one type named "Query".`

How can I define Queries when using multiple graphql files?

**Comment by phani-srikar** [comment]
Hi @Zamithal, here's what worked for me: Remove the redundant `a.graphql` file. In your `post.graphql`, just use `type Query`. Keep `contact.graphql` as-is with type extension defined for `Query`. Re-run `amplify api gql-compile` and it should work.

**Comment by Zamithal** [comment]
Hi @phani-srikar, I've gone ahead and tried these changes, and while this does work I believe it is only because there is one definition for `extend type Query` at this point. I've replicated the issue with this simple set of schemas. Note that it appears amplify combines the schemas in alphabetical order, hence the `a.graphql, b.graphql, c.graphql` naming.

Define the query type in `a.graphql`. Note that it is necessary for the definition of Query to occur before extending the type.
`<project>/amplify/backend/api/<myApi>/schema/a.graphql`
```graphql
type Query {
    queryA: String!
}
```

Define an extension in `b.graphql`. This will work fine because there is only a single extension so far.
`<project>/amplify/backend/api/<myApi>/schema/b.graphql`
```graphql
extend type Query {
    queryB: String!
}
```

Define a third file in `c.graphql`. This will no longer allow `amplify api gql-compile` to succeed, with an error about redefining the query field.
`<project>/amplify/backend/api/<myApi>/schema/c.graphql`
```graphql
extend type Query {
    queryC: String!
}
```

Error produced is:
`🛑 Object type extension 'Query' cannot redeclare field queryB`

This example is a very simple one for replication purposes. Ideally I would like to divide these files along responsibilities which may include types, models, queries, and mutations. If any beyond 2 attempt to define a Query, the compile will fail due to a redeclaration.

**Comment by phani-srikar** [comment]
Hi @Zamithal, that's a bug in how we merge these schemas. I've seen patterns where customers use `queries.graphql`, `mutations.graphql`, `subscriptions.graphql` files and define types separately in different files. Could you use that pattern while we get this fixed? Thanks for reporting.

**Comment by Zamithal** [comment]
@phani-srikar Yes, I can. I will modify my files to match this pattern. Thank you for the support, I appreciate it.
