### ISSUE TITLE
@hasOne and @belongsto is NOT bidirectional

### ISSUE THREAD

**Issue by redjonzaci** [aws-amplify/amplify-category-api#1811]
@edwardfoyle  wanted to follow up here in case it got buried, is the documentation misleading or is there a way to set up a bidirectional 1:1 relationship where you can create model B and be able to query from model A without having to update A?

_Originally posted by @SaileshKumar in https://github.com/aws-amplify/amplify-cli/issues/10133#issuecomment-1271865529_

Can this be done?

**Comment by redjonzaci** [comment]
Let's say I have a `Student` and `Mentor`. If I create a `Student` with a `mentorId`, then it should appear when I query for `Mentor` without updating `Mentor`'s `studentId`.

**Comment by phani-srikar** [comment]
Hi @redjonzaci, like explained in the comment that you linked in your description, the behavior is expected, but marking this as a feature-request since we would want to re-visit this issue to close the gap in future. Thanks.

**Comment by renebrandel** [comment]
Hi @redjonzaci - thanks for resurfacing this issue. I've added documentation to make this explicit: https://github.com/aws-amplify/docs/pull/6004
