### ISSUE TITLE
Amplify Push With More Than 20 GSI

### ISSUE THREAD

**Issue by akaiser443** [aws-amplify/amplify-category-api#1812]
### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

16.13.1

### Amplify CLI Version

11.0.3

### What operating system are you using?

Mac OS 13.4

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

We recently had a project's GSI quota increase from 20 to 25. When attempting to add a 21st GSI with `amplify push`, we receive an error that a DynmaoDB table can have a max of 20 GSIs.

```
DynamoDB [object Object] can have max of 20 GSIs
```

### Expected behavior

The Amplify push should be able to add the 21st GSI. 

### Reproduction steps

1. Have the DynamoDB GSI quota limit increased to more than 20. 
2. Define a model with more than 20 GSI.
3. Run `amplify push`

### Project Identifier

238e384d30dd713d4ff52a149b4d36ee

### Log output

<details>

```
# Put your logs below this line
2023-08-22T18:56:05.954Z|info : amplify push core  {"force":true,"yes":true}
...
2023-08-22T18:56:27.732Z|error : DynamoDB [object Object] can have max of 20 GSIs
ConfigurationError: DynamoDB [object Object] can have max of 20 GSIs

```

</details>

### Additional information

I have tried adding the GSI manually through the DynamoDB console, which succeeded without error, so the quota limit of 25 is being correctly applied in DynamoDB.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by akaiser443** [comment]
it looks like the limit is set to 20 in `packages/amplify-provider-awscloudformation/src/graphql-resource-manager/dynamodb-gsi-helpers.ts` Is there any workaround to this?
![Screenshot 2023-08-24 at 9 54 07 AM](https://github.com/aws-amplify/amplify-category-api/assets/69975617/8033f2f9-6b94-404d-909d-02418b03f1b6)
![Screenshot 2023-08-24 at 9 54 16 AM](https://github.com/aws-amplify/amplify-category-api/assets/69975617/8a3d4ea6-2066-4e6b-b870-d5b2306abf17)

**Comment by phani-srikar** [comment]
Hi @akaiser443, this limit is not imposed by Amplify but DynamoDB itself according to [this doc](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-indexes-general.html). We don't have an alternative to circumvent this limit.

**Comment by alharris-at** [comment]
Hi @akaiser443, I'm currently looking into adding a parameter to allow you to circumvent this check. In the short-term I'll cut a tagged release of the CLI for you to use while we get a change merged into the main release process.

**Comment by alharris-at** [comment]
The tagged release process is kicked off, and once complete, a pre-release version of the cli can be installed via `npm i -g @aws-amplify/cli@disable-gsi-limit-check`, then the limit check can be disabled on a push by running `amplify push --disable-gsi-limit-check`.

**Comment by alharris-at** [comment]
Confirming the tagged release is now live on npm https://www.npmjs.com/package/@aws-amplify/cli/v/12.4.0-disable-gsi-limit-check.0.

**Comment by alharris-at** [comment]
PR to add this feature has been merged, and I would expect it to be available in the standard CLi release beginning with the next version >12.4.0.
