### ISSUE TITLE
How to resume/continue opensearch backfill ?

### ISSUE THREAD

**Issue by bcs-gbl** [aws-amplify/amplify-category-api#1817]
### Amplify CLI Version

12.2.3

### Question

I use this script: **packages/graphql-elasticsearch-transformer/scripts/ddb_to_es.py** to backfill opensearch database from dynamodb. (because Amplify kills my whole production opensearch cluster with all data)

The backfill runs 1.5 days when my internet connection lost, so the script ended with network error. 
4.5M data successfully bacfilled. 

- So, is there a solutin without restart the whole process from zero?
- will it duplicate the already backfilled data if i run it again?
- How can i resume from 4.5M?

**Comment by phani-srikar** [comment]
Hi @bcs-gbl, the script does not offer any retry from failure as-is. You would need to update it with some custom logic to start the DDB scan process by setting the appropriate value for `LastEvaluatedKey`.

**Comment by bcs-gbl** [comment]
> Hi @bcs-gbl, the script does not offer any retry from failure as-is. You would need to update it with some custom logic to start the DDB scan process by setting the appropriate value for `LastEvaluatedKey`.

Thank you.
