### ISSUE TITLE
How to add a new datasource to AppSync API with override.ts ? 

### ISSUE THREAD

**Issue by ggorge-etiqa** [aws-amplify/amplify-category-api#1851]
### Amplify CLI Version

12.3.0

### Question

I'm trying to add a new lambda datasource in my AppSync API. This is my `override.ts`:
```
import { AmplifyApiGraphQlResourceStackTemplate, AmplifyProjectInfo } from '@aws-amplify/cli-extensibility-helper';
import * as cdk from 'aws-cdk-lib';

export function override(resources: AmplifyApiGraphQlResourceStackTemplate, amplifyProjectInfo: AmplifyProjectInfo) {
    const DS_NAME = "userLambdaDataSource"

    const lambdaDataSource = new cdk.aws_appsync.CfnDataSource(this, 'userLambdaDataSource', {
        apiId: resources.api.GraphQLAPI.attrApiId,
        description: "A lambda datasource for validating input on createUser",
        lambdaConfig: {
            lambdaFunctionArn: 'lambdaFunctionArn',
        },
        name: DS_NAME,
        serviceRoleArn: "arn:aws:iam::0123456789012:role/Role3a6fdff8",
        type: "AWS_LAMBDA"
    })


    const model = resources.models["User"];
    model.appsyncFunctions["MutationcreateUserpreUpdate0FunctionMutationcreateUserpreUpdate0Function.AppSyncFunction"].dataSourceName = lambdaDataSource.name;
}
```

When running `amplify push` I get this error:
```
Cannot read properties of undefined (reading 'addChild')
```
Any help would be appreciated!

**Comment by AnilMaktala** [comment]
Hi @ggorge-etiqa, Thank you for raising this. To update the model Datasource, please refer to the samples provided in the documentation linked [here](https://docs.amplify.aws/cli/graphql/override/#customize-amplify-generated-resources-for-model-directive).

**Comment by ggorge-etiqa** [comment]
Hi @AnilMaktala , going further with my researches I found out that the problem here is the creation of a new AppSync Datasource resource within the `override.ts`.
```
const lambdaDataSource = new cdk.aws_appsync.CfnDataSource(this, 'userLambdaDataSource', {
[...]
})
```
Can you confirm that it's not possible to add new resources with that file? 

To me it seems that it's not possible so I ended up creating a custom resource for the datasource (and all related stuff like IAM Role and policy) with `amplify add custom`.

But my approach was leading to a kind of circular dependency, as AppSync API must exists in order to create a new AppSync API Datasource customResource. And the model function Datasource override needs the customResource in order to be created.

Although is possible to achieve this with running `amplify push` manually without the `override.ts` file, then add the file and run again `amplify push`, the same can't be done in a single run.

At the moment I'm using a post-push hook to fix the model function Datasource configuration with `aws` cli commands, but I'm open to try a more *amplify-ish* approach.

**Comment by renebrandel** [comment]
Hi @ggorge-etiqa yeah the route via custom is the correct one, here's a sample: https://docs.amplify.aws/cli/graphql/custom-business-logic/#vtl-resolver

Separately, we recently brought Amplify's API category to CDK as an L3 construct. If you operate within a CDK environment already, it'll likely offer you a more integrated developer experience for creating additional resolvers and data sources. Here's the walkthrough blog post: https://aws.amazon.com/blogs/mobile/announcing-aws-amplifys-graphql-api-cdk-construct-deploy-real-time-graphql-api-and-data-stack-on-aws

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
