### ISSUE TITLE
AppSync delta table is missing the base table index 

### ISSUE THREAD

**Issue by ridakaddir** [aws-amplify/amplify-category-api#1853]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v19.6.0

### Amplify CLI Version

12.1.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

In my GraphQL schema, I have this model with an indexed attribute zone. all AppSync queries/Mutations/subscriptions are generated by the cli. 
when I run the query to get data by zone all the queries work as expected, except when I try to get the delta data ( lastSync on or after current - DeltaSyncTTL) I get this error `The table does not have the specified index byZone`.
after checking the delta table, I found that the CLI didn't create the index automatically. I had to create it manually.

```
type Collections @model  @auth(rules: [{ allow: private }, { allow: public }]) {
  id: ID!
  *****
  zone: ID! @index(name: "byZone", sortKeyFields: ["timestamp"])
  *****
  *****
  *****
  *****
  *****
  timestamp: AWSDateTime!
}
```

### Expected behavior

amplify cli should create the index in the delta table

### Reproduction steps

1. create graphql api using the cli, with a model like 

```
type Collections @model  @auth(rules: [{ allow: private }, { allow: public }]) {
  id: ID!
  *****
  zone: ID! @index(name: "byZone", sortKeyFields: ["timestamp"])
  *****
  *****
  *****
  *****
  *****
  timestamp: AWSDateTime!
}
```

2. run this query 

```
query SyncCollections(
    $filter: ModelCollectionsFilterInput, 
    $lastSync: AWSTimestamp, 
    $limit: Int) 
    {  
        syncCollections(filter: $filter, lastSync: $lastSync, limit: $limit) {    items {
                __typename
                _deleted
                _lastChangedAt
                _version
                createdAt
                id
                zone
                timestamp
                updatedAt
            }
            nextToken
            startedAt  
        }
    }
```
VARIABLES    
 ```
{
    "filter": {
      "and": [
        {
          "zone": {
            "eq": "zoneID"
          }
        }
      ]
    },
    "limit": 500,
    "lastSync": 1694111707600
}
```
    
3. If the lastSync is null or is before current - DeltaSyncTTL the the query works because it runs the query on the Base table
4. If the lastSync on or after current - DeltaSyncTTL the query returns an error `The table does not have the specified index: byZone` because it runs the query on the Delta table and the delta table is missing the index 

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by sundersc** [comment]
Amplify do not create index on the custom fields on the delta table. LastSync argument is meant to specify the time the data was last synced on the device, so it is expected to be less than (or before) the current timestamp. Is there a reason why lastSync is greater (or after) the current timestamp in your use case?

**Comment by ridakaddir** [comment]
lastSync is after current - DeltaSyncTTL. it could never be greater then current.

if Amplify does not create the index on the delta table, how can we do that? manually? this index is essential, as without it, the synchronization query won't function properly.

please checkout the original bug
https://github.com/aws-amplify/amplify-flutter/issues/3658#issuecomment-1710462091

**Comment by ridakaddir** [comment]
@sundersc 

this is not a datastore bug, it's an Amplify cli issue. as the cli didn't create the index in the delta table. creating the index manually solved the issue.

**Comment by stevegaunt** [comment]
This is also happening with the sync expressions queries against the delta table.
amplify cli version 12.2.3 and  higher..  It works on amplify cli version 12.1.1 . I'm not sure when this started to happen, but somewhere between 12.1.1. and 12.2.3. 

we have sync expressions against all our models ( user_id) so we sync against that instead of full base table scans.
we have around 10ish models at the moment.

**Comment by dpilch** [comment]
Can you share your feature flags? `amplify/cli.json`.

**Comment by wojciechzahradnikdeviniti** [comment]
```
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true,
      "securityenhancementnotification": false,
      "showfieldauthnotification": false,
      "usesubusernamefordefaultidentityclaim": true,
      "usefieldnameforprimarykeyconnectionfield": false,
      "enableautoindexquerynames": true,
      "respectprimarykeyattributesonconnectionfield": true,
      "shoulddeepmergedirectiveconfigdefaults": false,
      "populateownerfieldforstaticgroupauth": true
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true,
      "forcealiasattributes": false,
      "useenabledmfas": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "latestregionsupport": {
      "pinpoint": 1,
      "translate": 1,
      "transcribe": 1,
      "rekognition": 1,
      "textract": 1,
      "comprehend": 1
    },
    "project": {
      "overrides": true
    }
  },
  "debug": {
    "shareProjectConfig": true
  }
}
```

**Comment by ridakaddir** [comment]
```
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true,
      "securityenhancementnotification": false,
      "showfieldauthnotification": false,
      "usesubusernamefordefaultidentityclaim": true,
      "usefieldnameforprimarykeyconnectionfield": false,
      "enableautoindexquerynames": true,
      "respectprimarykeyattributesonconnectionfield": true,
      "shoulddeepmergedirectiveconfigdefaults": false,
      "populateownerfieldforstaticgroupauth": true
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true,
      "forcealiasattributes": false,
      "useenabledmfas": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true,
      "generatemodelsforlazyloadandcustomselectionset": false
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "latestregionsupport": {
      "pinpoint": 1,
      "translate": 1,
      "transcribe": 1,
      "rekognition": 1,
      "textract": 1,
      "comprehend": 1
    },
    "project": {
      "overrides": true
    }
  },
  "debug": {
    "shareProjectConfig": true
  }
}
```

**Comment by wojciechzahradnikdeviniti** [comment]
Hi, any updates? It's critical issue on my side.

**Comment by AaronZyLee** [comment]
I tried to repro the issue in the AppSync console but cannot succeed. Do you have the same error returned if running the query in AppSync? Or is it only thrown in the datastore app?

**Comment by wojciechzahradnikdeviniti** [comment]
Only on the android side, on ios it seems to work well.

**Comment by antoineberthelin** [comment]
Hello @AaronZyLee 

To reproduce, just checkout amplify example https://docs.amplify.aws/lib/datastore/sync/q/platform/android/#advanced-use-case---query-instead-of-scan

And set lastSync to now - 30 minutes to query delta table
I open this bug since one month on it https://github.com/aws-amplify/amplify-android/issues/2564 with all details to reproduce

Thanks

**Comment by wojciechzahradnikdeviniti** [comment]
I also found that on Android in the AmplifyDatabase.db if 2 models have the same index name then only one index will be added and second will be ignored.

**Comment by sundersc** [comment]
@ridakaddir Could you share the code block that computes the value of `current - DeltaSyncTTL`?

**Comment by wojciechzahradnikdeviniti** [comment]
@sundersc 
Android datastore prepares lastSync and pass it to GraphQLRequest
![image](https://github.com/aws-amplify/amplify-category-api/assets/95854648/f4e5edb1-b718-4f35-aa06-2158a255551c)
![image](https://github.com/aws-amplify/amplify-category-api/assets/95854648/19e56822-b2ba-44fc-b94a-18b1bfa2cc4a)
![image](https://github.com/aws-amplify/amplify-category-api/assets/95854648/6f5a90d5-df5c-4461-a67e-6ead7a9c26d2)
![image](https://github.com/aws-amplify/amplify-category-api/assets/95854648/91b546a5-84aa-4ab4-a03e-07caf4339a52)
![image](https://github.com/aws-amplify/amplify-category-api/assets/95854648/16862ef9-8b32-4de7-af84-a2bbb8413324)

after that 
GraphQLResponse data is null - thats why we are getting IrRecoverableException

**Comment by wojciechzahradnikdeviniti** [comment]
Hi, any updates?

**Comment by wojciechzahradnikdeviniti** [comment]
@AaronZyLee @sundersc Do you have any updates?

**Comment by AaronZyLee** [comment]
@wojciechzahradnikdeviniti Could you send a report by running the following command and provide your project identifier? It would be helpful to examine the backend config directly to repro the issue.
```
amplify diagnose --send-report
```

**Comment by phani-srikar** [comment]
We have identified the root cause for this issue. While we fix this, a workaround is to override the Sync Query preAuth resolvers to properly specify the `deltaSyncTableTtl`. For example, if you have a model named `Users`,
1. Copy the contents of `Query.SyncUsers.preAuth.1.req.vtl` from `amplify/backend/api/<api_name>/build/resolvers` to the resolver overrides directory which is `amplify/backend/api/<api_name>/resolvers`.
2. Update the resolver override to include the following statement at the beginning: `#set( $ctx.stash.deltaSyncTableTtl = <my-delta-sync-ttl> )`. The value of `<my-delta-sync-ttl>` defaults to `30`. This value is in minutes.
3.  Push your changes using `amplify push`.

**Comment by wojciechzahradnikdeviniti** [comment]
hi, @phani-srikar 
Thanks! Will amplify-cli lib be also updated?

**Comment by wojciechzahradnikdeviniti** [comment]
hi @phani-srikar 
I didn't do the workaround but I updated amplify-cli to **12.5.2** with the fix you provided.
I pulled all using `amplify pull` and I still have that issue with IrRecoverableException. 
I can't see any changes in preAuth file.
<img width="839" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/95854648/667b0dc9-efa1-440f-a4e3-8803774cd7ba">

Could you please help me?

**Comment by dpilch** [comment]
You will probably need to `amplify push` to update the AppSync API. If you see `No changes detected` when pushing you can add a newline to your `schema.graphql` and then push again to force an update.

**Comment by wojciechzahradnikdeviniti** [comment]
Ok after next pull it seems to working fine, thanks :)
