### ISSUE TITLE
Manual changes not overwritten by 'amplify push --force' for AppSync GraphQL resolver

### ISSUE THREAD

**Issue by ggorge-etiqa** [aws-amplify/amplify-category-api#1857]
### Amplify CLI Version

12.3.0

### Question

I have been extending my AppSync GraphQL resolver by incorporating VTL files into the `amplify/backend/api/myapi/resolvers` directory. Following this, for testing purpose, I made manually adjustments to the AppSync function generated.

I assumed that executing the `amplify push --force` command would automatically overwrite any manual modifications made to the AWS resources. However, it appears that this command does not behave as expected.

Is my expectation incorrect?

**Comment by dpilch** [comment]
Amplify generates CloudFormation templates to manage resources. `amplify push --force` is updating the CloudFormation templates, then the resource updates are handled by CloudFormation. CloudFormation does not automatically detect drift on a deploy/update. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift.html

**Comment by ggorge-etiqa** [comment]
Thanks @dpilch , that make sense. I found a feat request that is probably related here: https://github.com/aws-amplify/amplify-cli/issues/1681
