### ISSUE TITLE
How do I separate functions into custom stacks.

### ISSUE THREAD

**Issue by LeoReubelt** [aws-amplify/amplify-category-api#1859]
### Amplify CLI Version

12.0.3

### Question

When I run `amplify api gql-compile` I got the following error.
`The FunctionDirectiveStack.json stack defines more than 500 resources.`

I tried to break up the functions into multiple stack by adding to the transform.conf.json stack mapping as follows...

```
{
    "Version": 5,
    "ElasticsearchWarning": true,
    "StackMapping": {
        "ListItemResolver": "CustomStack",
        "SyncItemResolver": "CustomStack",
        "CreateItemResolver": "CustomStack",
        "UpdateItemResolver": "CustomStack",
        "DeleteItemResolver": "CustomStack",
        "GetItemResolver": "CustomStack",
        "QueryTokenResolver": "CustomFunctionStack",
        "QueryTokenRTMResolver": "CustomFunctionStack",
        "QueryDataResolver": "CustomFunctionStack",
    },
    "ResolverConfig": {
        "project": {
            "ConflictHandler": "AUTOMERGE",
            "ConflictDetection": "VERSION"
        },
    }
}
```
And that fixes the error, but when I perform `amplify push` it fails with `["Index: 1 State: {\"deploy\":\"waitingForDeployment\"} Message: Resource is not in the state stackUpdateComplete"]`.

When I do a git push, and the backend tries to deploy it fails with the following...

`Embedded stack arn:aws:cloudformation:us-east-... was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to create: [CustomStack, CustomFunctionStack].`

Do I have to do anything to deploy the custom stacks beyond populating the stack mapping?

**Comment by AnilMaktala** [comment]
Hi @LeoReubelt, Are you still experiencing this cloud formation issue?

**Comment by AnilMaktala** [comment]
Hey @LeoReubelt, if you are still experiencing this issue, would you able to provide the actual error from cloud-formation console?

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
