### ISSUE TITLE
Secondary index on ManyToMany relations

### ISSUE THREAD

**Issue by lozinska** [aws-amplify/amplify-category-api#1882]
### Amplify CLI Version

12.0.3

### Question

Hello there
I have a many-to-many relationship and I want to know if there is any workaround to add a secondary index. I am trying to achieve sorting data by posted date.

These are my schemas.

```
type Seedlot
  @model
 {
  id: ID!
 postedAt: AWSDateTime
  species:[PlantSpecies] @manyToMany(relationName: "SeedlotPlantSpecies") @index(
      name: "bySpeciesSeedlot"
      sortKeyFields: ["postedAt"]
      queryField: "seedlotsByPlantSpecies"
    )

type PlantSpecies
  @model
 id: ID!
 seeds:[Seedlot] @manyToMany(relationName: "SeedlotPlantSpecies")
```

**Comment by phani-srikar** [comment]
Hi @lozinska, when you have a `many-to-many` relationship, we inherently create a join table that actually stores the foreign keys from both tables. I have shown this relation below:

```
type Seedlot @model
 {
  id: ID!
 postedAt: AWSDateTime
 species:[SeedLotPlantSpecies] @hasMany
 }

type PlantSpecies @model
{
 id: ID!
 seeds:[SeedLotPlantSpecies] @hasMany
}

type SeedLotPlantSpecies @model
{
  id: ID!
  seedLot: SeedLot! @belongsTo
  plantSpecies: PlantSpecies! @belongsTo
}
```
You can use the above relationships instead and add indices wherever needed. I did not fully comprehend what records you want to sort by `postedAt`. If this doesn't help, can you give some example query with inputs and expected outputs?

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
