### ISSUE TITLE
Difficulty changing the model, deployment rollback without details

### ISSUE THREAD

**Issue by shopizer-ecommerce** [aws-amplify/amplify-category-api#1893]
### Amplify CLI Version

latest 12.4.0

### Question

I can't update an existing model after amplify upgrade from 7.X to latest 12.4.0

amplify <app> <backend> pull

From there  can publish application changes

Modify my schema
compille the schema
amplify publish

Deploying iterative update 3 of 3 into upgrade environment. This will take a few minutes. ⠼
Deploying api tipgov2 [ =======--------------------------------- ] 1/6
	GraphQLAPITransformerSchema3C… AWS::AppSync::GraphQLSchema    UPDATE_COMPLETE                Wed Sep 27 2023 12:42:32…  
	
After 20 minutes it fails

["Index: 2 State: {\"deploy\":\"waitingForDeployment\"} Message: Resource is not in the state stackUpdateComplete"]

_Previous model_
type Hotel @model
  @auth(rules: [{ allow: owner, operations: [read] }]) {
  id: ID! @primaryKey
  hotelID: ID! @index(name: "byCodeByLocale", sortKeyFields: ["code","locale"])
  locale: String! @index(name: "byLocale", queryField: "locale")
  code: String!
  name: String!
  address: String
  city: String
  postalCode: String
  province: String
  country: String
  phone: String
  image: String,
  _version: String
  
  _new model_

type Hotel @model {
  id: ID! @primaryKey
  code: String!
  name: String! @index(name: "byName", queryField: "hotelByName")
  address: String
  city: String
  postalCode: String
  province: String
  country: String
  phone: String
  _version: String
}

Cloudwatch event

was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [Hotel].

Tried

amplify push --iterative-rollback
amplify push --force

deleted s2 deployment-state.json

- Can i simply delete dynamo db table ?
- Should i modify src/graphql and src/api
- Any hint would be much appreciated

**Comment by AnilMaktala** [comment]
Hey @shopizer-ecommerce, Would you kindly revert the recent changes and attempt running `amplify push`? Please inform us of the outcome.

**Comment by shopizer-ecommerce** [comment]
Thanks for your reply

As asked i reverted back to the original model by pulling from amplify

amplify pull tipgov2 upgrade
amplify push

    Current Environment: upgrade
    
┌──────────┬──────────────────────┬───────────┬───────────────────┐
│ Category │ Resource name        │ Operation │ Provider plugin   │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Api      │ tipgov2              │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Auth     │ tipgov2              │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Function │ tipgov2CustomMessage │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Hosting  │ amplifyhosting       │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Storage  │ tipngov2profile      │ No Change │ awscloudformation │
└──────────┴──────────────────────┴───────────┴───────────────────┘

No changes detected

No problems with push or publish at this point

**Comment by shopizer-ecommerce** [comment]
If i edit my model

compile graphql

amplify push

stalled

Deploying iterative update 3 of 4 into upgrade environment. This will take a few minutes. ⠏
Deploying api tipgov2 [ =======--------------------------------- ] 1/6
	GraphQLAPITransformerSchema3C… AWS::AppSync::GraphQLSchema    UPDATE_IN_PROGRESS             Wed Sep 27 2023 17:22:56… 

Still

Rolled back (5 of 4)
🛑 ["Index: 3 State: {\"deploy\":\"waitingForDeployment\"} Message: Resource is not in the state stackUpdateComplete"]

**Comment by shopizer-ecommerce** [comment]
During the update i can see
dynamo db table is updated with GSI created
App Sync is **not** updated 

It ends up by rolling back the dynamo db table

This is a uat environment, i am worried for our production environment. Please advice

**Comment by AnilMaktala** [comment]
> Thanks for your reply
> 
> As asked i reverted back to the original model by pulling from amplify
> 
> amplify pull tipgov2 upgrade amplify push
> 
> ```
> Current Environment: upgrade
> ```
> 
> ┌──────────┬──────────────────────┬───────────┬───────────────────┐ │ Category │ Resource name │ Operation │ Provider plugin │ ├──────────┼──────────────────────┼───────────┼───────────────────┤ │ Api │ tipgov2 │ No Change │ awscloudformation │ ├──────────┼──────────────────────┼───────────┼───────────────────┤ │ Auth │ tipgov2 │ No Change │ awscloudformation │ ├──────────┼──────────────────────┼───────────┼───────────────────┤ │ Function │ tipgov2CustomMessage │ No Change │ awscloudformation │ ├──────────┼──────────────────────┼───────────┼───────────────────┤ │ Hosting │ amplifyhosting │ No Change │ awscloudformation │ ├──────────┼──────────────────────┼───────────┼───────────────────┤ │ Storage │ tipngov2profile │ No Change │ awscloudformation │ └──────────┴──────────────────────┴───────────┴───────────────────┘
> 
> No changes detected
> 
> No problems with push or publish at this point

If, after rolling back your changes, you observe no detected changes, consider inserting a blank space or adding a comment in the schema. This action will update the hash and enable you to proceed with the push.

if above step is successful, please add one change at a time and run `amplify push`.

**Comment by shopizer-ecommerce** [comment]
It does not work

I removed the model from schema.graphql
compiled the schema

amplify push

**Sucessfully removed Hotel table**

I add again Hotel table and it still fails !!!

I removed the Hotel table

Created a new table that is not named Hotel

type Contract @model
  @auth(rules: [
    { allow: private }
  ]) {
  id: ID! @primaryKey
  code: String!
  name: String!
  address: String
  city: String
  postalCode: String
  province: String
  country: String
  phone: String
  _version: String
}




Deployment failed.
Deploying root stack tipgov2 [ ===========================------------- ] 4/6
	amplify-tipgov2-upgrade-222112 AWS::CloudFormation::Stack     UPDATE_ROLLBACK_COMPLETE_CLEA… Thu Sep 28 2023 09:24:47…     
	hostingamplifyhosting          AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Sep 28 2023 09:24:35…     
	functiontipgov2CustomMessage   AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Sep 28 2023 09:24:35…     
	storagetipngov2profile         AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Sep 28 2023 09:24:35…     
	authtipgov2                    AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Sep 28 2023 09:24:35…     
	apitipgov2                     AWS::CloudFormation::Stack     UPDATE_FAILED                  Thu Sep 28 2023 09:24:32…     
Deploying api tipgov2 [ =======--------------------------------- ] 1/6
	User                           AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Sep 28 2023 09:24:26…     
	Contract                       AWS::CloudFormation::Stack     CREATE_FAILED                  Thu Sep 28 2023 09:24:27…     

🛑 The following resources failed to deploy:
Resource Name: Contract (AWS::CloudFormation::Stack)
Event Type: create
Reason: S3 error: Access Denied
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

My user has



AdministratorAccess | AWS managed - job function | Directly
AdministratorAccess-Amplify | AWS managed | Directly
AmazonDynamoDBFullAccess | AWS managed | Directly
CloudFrontInlinePolicy

Please Advise i have no clue !!!

**Comment by AnilMaktala** [comment]
Hey @shopizer-ecommerce , Thank you for following the steps. Just to confirm, did the `amplify push` command execute successfully after rolling back the changes?

**Comment by shopizer-ecommerce** [comment]
Just as a recap i had 2 tables before the upgrade of the cli

Can not update second table
I was able to remove the second table
I can do amplify push

Add a simple model to amplify/api/<app>/schema.graphql
type Post @model @auth(rules: [{ allow: public }]) {
  id: ID!
  title: String!
}
run compile schema

amplify push -> fail

Edit your schema at /Users/carlsamson/Documents/dev/workspace/tipngoSept2023/onboarding/amplify/backend/api/tipgov2/schema.graphql or place .graphql files in a directory at /Users/carlsamson/Documents/dev/workspace/tipngoSept2023/onboarding/amplify/backend/api/tipgov2/schema
? Do you want to update code for your updated GraphQL API Yes
? Do you want to generate GraphQL statements (queries, mutations and subscription) based on your schema types?
This will overwrite your current graphql queries, mutations and subscriptions Yes

Deployment failed.
Deploying root stack tipgov2 [ ===========================------------- ] 4/6
	amplify-tipgov2-upgrade-222112 AWS::CloudFormation::Stack     UPDATE_ROLLBACK_COMPLETE_CLEA… Thu Sep 28 2023 23:35:25…     
	hostingamplifyhosting          AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Sep 28 2023 23:35:14…     
	functiontipgov2CustomMessage   AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Sep 28 2023 23:35:14…     
	storagetipngov2profile         AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Sep 28 2023 23:35:14…     
	authtipgov2                    AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Sep 28 2023 23:35:14…     
	apitipgov2                     AWS::CloudFormation::Stack     UPDATE_FAILED                  Thu Sep 28 2023 23:35:10…     
Deploying api tipgov2 [ =======--------------------------------- ] 1/6
	User                           AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Sep 28 2023 23:35:04…     
	Post                           AWS::CloudFormation::Stack     CREATE_FAILED                  Thu Sep 28 2023 23:35:05…     

🛑 The following resources failed to deploy:
Resource Name: Post (AWS::CloudFormation::Stack)
Event Type: create
Reason: S3 error: Access Denied
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html


🛑 Resource is not in the state stackUpdateComplete
Name: Post (AWS::CloudFormation::Stack), Event Type: create, Reason: S3 error: Access Denied
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html, IsCustomResource: false

Still clue less

**Comment by shopizer-ecommerce** [comment]
There is an issue with CFN

- amplify pull project backend

Get the old 6 month back graphql tables

I remove the table that i need to fix (no data in it)

compile api gql-compile

amplify push --allow-destructive-graphql-schema-updates

Update fail

I observe that what i pushed
 "S3DeploymentRootKey": "amplify-appsync-files/fc675c8ae8c68568ef72748cbf042400319cdac1"

Is not what CFN tries to use, as i can see in stack parameters
 "S3DeploymentRootKey": "amplify-appsync-files/fafe213e07f79d17258aa99ae14aad4aa1fceafe/states/initial-stack"
 
It keeps failing

If i go in CFN update and manually change the root key it still rolls back 

Is there anything that can be done, my source project and CFN are constantly out of sync

**Comment by shopizer-ecommerce** [comment]
So far no success

as soon as i touch schema.graphql
build and then push it fails


So i pull an existing bckend
recompile graphql
amplify status -> no changes
amplify push --force

Still fails 
apitipgov2                     AWS::CloudFormation::Stack     UPDATE_FAILED                  Fri Sep 29 2023 14:27:48…    

CFN tries to use the wrong content 

(Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; 

Parameters in CFN 



S3DeploymentRootKey | amplify-appsync-files/fafe213e07f79d17258aa99ae14aad4aa1fceafe/states/initial-stack
-- | --

This folder does not exist

What i just pushed 

"S3DeploymentRootKey": "amplify-appsync-files/b4bba8675e0e6b691557f48f0c572e10b6b330a2"

** Can this stack be deleted ?
** The stack cannot be updated with the good S3DeploymentRootKey

**Comment by shopizer-ecommerce** [comment]
Same issue as this one https://github.com/aws-amplify/amplify-category-api/issues/1425

**Comment by AnilMaktala** [comment]
Hey @shopizer-ecommerce, could you please create a Discord thread [here](https://discord.com/channels/705853757799399426/1019643921137139772).

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
