### ISSUE TITLE
Configure OpenSearch Dashboards via CDK

### ISSUE THREAD

**Issue by redjonzaci** [aws-amplify/amplify-category-api#1909]
### Amplify CLI Version

12.2.3

### Question

We are having a hard time configuring Cognito authentication for OpenSearch Dashboards via the `override.ts` of our AppSync API.
We need the `IdentityPoolId` and `UserPoolId` that are output by the auth stack,
but adding a Cfn parameters that refer to them didn't work.
It returned "undefined stack" error, which might be caused by order of deployment (?).

What would you suggest?

We might be getting to a solution, but posting this for the benefit of the community too.
I will update this issue if we find a solution before you answer.

**Comment by AnilMaktala** [comment]
Hey @redjonzaci, Thank you for raising this. Could you share the `override.ts`  code snippet, along with complete error log?

**Comment by redjonzaci** [comment]
We moved past the error and it would take some time to reproduce it again, but the solution we found is:
export `IdentityPoolId` and `UserPoolId` from `auth`'s `override.ts` and use `Fn::ImportValue` in `api`'s `override.ts`.

`auth/override.ts`
```js
    resources.addCfnOutput({
      value: resources.userPool.ref,
      exportName: `XXX-${amplifyProjectInfo.envName}-UserPoolId`,
    }, 'ExportUserPoolId');


    resources.addCfnOutput({
      value: resources.identityPool.ref,
      exportName: `XXX-${amplifyProjectInfo.envName}-IdentityPoolId`,
    }, 'ExportIdentityPoolId');
```
    
  `api/XXX/override.ts`
```js
const importedUserPoolId = { "Fn::ImportValue" : `XXX-${amplifyProjectInfo.envName}-UserPoolId` };
const importedIdentityPoolId = { "Fn::ImportValue" : `XXX-${amplifyProjectInfo.envName}-IdentityPoolId` };
```

XXX stands for the project name.

**Comment by renebrandel** [comment]
Thanks for posting your resolution. Closing this out.
