### ISSUE TITLE
AWS Amplify authorization based on db field value or relationship

### ISSUE THREAD

**Issue by zzBrunoBrito** [aws-amplify/amplify-category-api#192]
**Which Category is your question related to?**
Graphql api

**Amplify CLI Version** 
4.32.1

**What AWS Services are you utilizing?**
Aws amplify and cognito

I'm trying to implement authorization based on a field value of a graphql type. Basically I have a user, community and post type where a community can have multiple users and posts. The posts has an attribute called "visibility", if the visibility value is "private" only the users of that community can see the posts. If the visibility is "public" any user can see the post.

I think I can use cognito groups to control which users has access to which communities and posts, but cognito has a limit of 
10k groups and this is very bad for scalability. So, maybe I could implement this feature on application level but the only way I can think is disable all generated queries and mutations and implement my owns with the authorization rules I need based on database values. I really don't want to this because this way I'd lose the auto generated operations by amplify and would have to rewrite every query or mutation. 

It seems to be a very common problem, can someone give some guidance on what's the best way to solve this?

**Comment by josefaidt** [comment]
Closing due to age, @zzBrunoBrito if you are still experiencing this issue please reply back to this thread or create a new request and we can investigate further 🙂

**Comment by jaredatdannyronsrescue** [comment]
I have the same issue.  I would like to be able to create drafts of posts that only admins can see, but to be able to change a value in a field like setting isPublic = true. and have those posts be visible to the public.  Like @zzBrunoBrito explained, having groupsCanAccess gets us close, but doesn't completely satisfy this need because only logged in users would be able to see the post.
