### ISSUE TITLE
Unable to push or pull changes.

### ISSUE THREAD

**Issue by MARCTELLY** [aws-amplify/amplify-category-api#1929]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.1.0

### Amplify CLI Version

12.5.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Yes I push change by setting default value with `=`

### Describe the bug

[report-1696522050966.zip](https://github.com/aws-amplify/amplify-cli/files/12820770/report-1696522050966.zip)

### Expected behavior

I got this error `🛑 Syntax Error: Expected Name, found "=".` when I pull or push graphQL models change

### Reproduction steps

1. add = in model like  this :
type User
  @model
  @auth(rules: [{allow: public}, {allow: private, operations: [read]}]) {
  id: ID!
  isFavorite: Boolean
  logo: String
  status: String = "active" # the issue line
}
2. push change with amplify push

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by MARCTELLY** [comment]
Tanks you @josefaidt and @AnilMaktala but I already change `=` to `@default` but I cannot push my change I still have `🛑 Syntax Error: Expected Name, found "=".` when I run `amplify push`

**Comment by AnilMaktala** [comment]
Hi @MARCTELLY, Thank you for the response. Could you please run below command and send us the report?
 `amplify diagnose --send-report`.
 please refer [here](https://docs.amplify.aws/cli/reference/diagnose/)

**Comment by MARCTELLY** [comment]
you can fin the report on #Describe the bug here https://github.com/aws-amplify/amplify-category-api/issues/1929#issue-1930369173

**Comment by AnilMaktala** [comment]
Hey @MARCTELLY, Thank you. It appears that the problem lies within the `CapitalPool` model. Would you please try removing `= UNSPECIFIED` and test it again?
<img width="626" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/06fd2594-4a3c-483f-9a0a-98ace590740b">

**Comment by MARCTELLY** [comment]
hey @AnilMaktala. Thank you for the response. I already tried that, but did not work so I removed the env and I created the new one

**Comment by AnilMaktala** [comment]
Hey @MARCTELLY, Thank you for the response. Have you created the new schema model as recommend in the comment above?

**Comment by MARCTELLY** [comment]
Hey @AnilMaktala thank you. Yes I created as you recommande
