### ISSUE TITLE
graphQL @connection fields should accept specific values

### ISSUE THREAD

**Issue by alissaVrk** [aws-amplify/amplify-category-api#194]
**Is your feature request related to a problem? Please describe.**
I would like to have something like

```
type Post @model{
  id: ID!,
  comments: @connection(keyName:"byProjectAndState", fields:["id", byVal(false)]
}

type Comment @model
@key(name: "byProjectAndState", fields: ["postId", "isDeleted"] ) {
  id: ID!,
  postId: ID!,
  isDeleted: Boolean
}
```
so I can get all non deleted comments for a post

**Describe the solution you'd like**
enable boolean values to be sort keys and
maybe adding some syntax to the fields of a connection directive that will indicate that this is a value and not a field name

or allow for queries in the connection, to enable gt, sm filters as well

**Comment by renebrandel** [comment]
Hi - this issue didn't get much traction but wanted to update you that it might be better to use a custom query/mutation to handle this use case. The proposed format is (AFAIK) not compliant with the GraphQL SDL, so it'll be difficult to provide this use case via the given approach. Using a custom query/mutation, you can continue to use Amplify for managing the DB table but also fine-tune your request to handle the soft delete.
