### ISSUE TITLE
Definitive api key

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-category-api#1941]
### Is this feature request related to a new or existing Amplify category?

auth

### Describe the feature you'd like to request

It is very simple. For production I want a definitive api key without end of life.

### Describe the solution you'd like

It is very simple. For production I want a definitive api key without end of life.

### Describe alternatives you've considered

No alternatives.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by rudyhadoux** [comment]
Why one year ?
It does not make sense at all.

**Comment by AnilMaktala** [comment]
Hey @rudyhadoux, Thank you for bringing this to our attention. Currently, API keys on the AWS AppSync service are valid for a maximum of 365 days. Therefore, we will mark this as a feature request for the team to evaluate.

**Comment by rudyhadoux** [comment]
Ok thanks. 
Imagine that secure connections with Cognito user pools are valid for up to 365 days. The applications would therefore be invalid afterwards. it wouldn't make any sense.

**Comment by rudyhadoux** [comment]
So, in production : how to extend the validity date ?

**Comment by renebrandel** [comment]
Hi @rudyhadoux for unauthenticated user access to data we recommend using the "unauthRole" from Amplify. See the linked documentation and scroll down to the content regarding "provider: iam"

https://docs.amplify.aws/cli/graphql/authorization-rules/#public-data-access

**Comment by rudyhadoux** [comment]
Ok thanks. 
With AWS_IAM.
You teach me.
