### ISSUE TITLE
Do some data computations with extending postDataLoad resolver

### ISSUE THREAD

**Issue by ggorge-etiqa** [aws-amplify/amplify-category-api#1948]
### Amplify CLI Version

12.6.0

### Question

In my model I have a field `ExpDate` that is an iso timestamp.
I want that when I list my model a computated field `isExpired` is set to true if `ExpDate > current timestamp`.
Following https://docs.amplify.aws/cli/graphql/custom-business-logic/#extend-amplify-generated-resolvers I'm assuming I can create a `postDataLoad` VTL for accomplish the job and do a simple `if` statement inside it.
I'm also assuming that I need to implement this logic inside the `res` VTL, but I'm not sure how the `req` VTL should be.
Any hints?

**Comment by ggorge-etiqa** [comment]
I probably managed it to work without using a Lambda. This is the `req` VTL as we use a NONE_DS datasource as documented here: https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-none.html
```
{
    "version": "2018-05-29",
    "payload": $util.toJson($context.prev.result)
}
```
This is my `res` VTL with custom logic:

```
## [Start] ResponseTemplate. **

#set($currentMillis = $util.time.nowEpochMilliSeconds())

#foreach($item in $ctx.result.items)
    #set($item.isExpired = false)

    #if($item.expirationDate)
        #set($expirationDateMillis = $util.time.parseISO8601ToEpochMilliSeconds($item.expirationDate))
        #if($expirationDateMillis < $currentMillis)
          #set($item.isExpired = true)
        #end    
    #else
        ## Handle missing expiration date
        $util.error("An error occurred: Missing expiration date for item: $item")
    #end

#end

$util.toJson($ctx.result)

## [End] ResponseTemplate. **
```
If you have any other suggestion I'm open to try, otherwise I can consider the issue closed.

**Comment by AnilMaktala** [comment]
Hey @ggorge-etiqa, I apologize for the delay. I have consulted with the Engineering team, and they have confirmed that this is the recommended approach to fulfill your use case.
