### ISSUE TITLE
How to update/ sync schema changes or remove RDS data source added through add-graphql-datasource?

### ISSUE THREAD

**Issue by sakhunzai** [aws-amplify/amplify-category-api#195]
**Which Category is your question related to?**
Graphql API / RDS Aurora 

**Amplify CLI Version** 
 4.46.1

**What AWS Services are you utilizing?**
Auth, Storage, Graphql , Video 

I have added a RDD data source using `amplify api add-graphql-datasource` , which has successfully generated schema and respective resolvers. After that I modified the RDS mysql database running sql statements through aws console and ran `amplify api add-graphql-datasource`  and `amplify push` gives me following error, If I undo the changes `amplify push` works fine otherwise timeout as seen below:

>⠼ Uploading files...✖ An error occurred when pushing the resources to the cloud

>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
>An error occurred during the push operation: Your socket connection to the server was not read from or written to within the 
 >timeout period. Idle connections will be closed.

So right now I am struggling to find out how to 
*  Delete RDS datasource , since I am using Dynamodb  already and dont want to delete that.
*  Sync changes either from RDS database or update RDS database through changes to models in rds.graphql

thanks

**Comment by renebrandel** [comment]
Hi - I'm closing this issue as we've addressed it in our latest MySQL / PostgreSQL support in the new GraphQL Transformer. https://docs.amplify.aws/react/build-a-backend/graphqlapi/connect-api-to-existing-database/#apply-iterative-changes-from-the-database-definition
