### ISSUE TITLE
How to run gql-compile with existing API without amplify init?

### ISSUE THREAD

**Issue by JeffreyWardman** [aws-amplify/amplify-category-api#1952]
### Amplify CLI Version

12.7.0

### Question

I'm using SST for serverless deployment and so am trying to use an existing stack with Amplify. I want to use Datastore and this requires converting graphql schemas which have directives such as @model @auth via `amplify api gql-compile`. Is this possible? I basically want an offline version of `amplify api gql-compile` or some direction on how to use Datastore without `amplify init`.

**Comment by renebrandel** [comment]
Hi - we've actually just launched a CDK construct for Amplify. You can check it out here: https://aws.amazon.com/blogs/mobile/announcing-aws-amplifys-graphql-api-cdk-construct-deploy-real-time-graphql-api-and-data-stack-on-aws/ 

To enable DataStore, you need to setup following configurations:
1. Enable conflict detection on the API
```ts
    const amplifyApi = new AmplifyGraphqlApi(this, "MyNewApi", {
      definition: AmplifyGraphqlDefinition.fromFiles(
        path.join(__dirname, "schema.graphql")
      ),
      authorizationModes: {
        defaultAuthorizationMode: 'API_KEY',
        apiKeyConfig: {
          expires: cdk.Duration.days(30)
        },
      },
      conflictResolution: {
        project: {
          handlerType: 'AUTOMERGE',
          detectionType: 'VERSION'
        }
      }
    });
```
2. Once you've deployed your API you can set the client configuration based on the stack outputs. This allows the Amplify client library to "know" your API endpoint.
```
✨  Deployment time: 62.86s

Outputs:
BackendStack.amplifyApiModelSchemaS3Uri = s3://backendstack-mynewapiamplifycodegenassetsamplifyc-1u3xykyhe309m/model-schema.graphql
BackendStack.awsAppsyncApiEndpoint = https://wy5mtp7jzfctxc5w5pzkcoktbi.appsync-api.us-east-1.amazonaws.com/graphql
BackendStack.awsAppsyncApiId = eci46vifpvbvhno55uo2ovtoqm
BackendStack.awsAppsyncApiKey = da2-XXXX
BackendStack.awsAppsyncAuthenticationType = API_KEY
BackendStack.awsAppsyncRegion = us-east-1
```
In your frontend code’s index.js file, import the Amplify Library and configure them with the corresponding information:
```ts
import { Amplify } from 'aws-amplify'

Amplify.configure({
  aws_appsync_graphqlEndpoint: 'https://wy5mtp7jzfctxc5w5pzkcoktbi.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-XXXX'
})
```
3. Finally, you need to generate the "models" that'll be used by the DataStore client library. [Documentation](https://docs.amplify.aws/cli/graphql/client-code-generation/#generate-models-for-android-swift-flutter-and-javascript-datastore). You can do so by running the following command based on your platform:
```
npx @aws-amplify/cli codegen models \
  --model-schema <path-to-schema.graphql> \
  --target [android|ios|flutter|javascript|typescript] \
  --output-dir ./
```

**Comment by JeffreyWardman** [comment]
That's amazing timing! I've referenced this issue in SST to get it available through it as well.

**Comment by renebrandel** [comment]
Sounds good. I'll be closing out this issue! Please @-mention me if this doesn't fully address everything from our end.

**Comment by JeffreyWardman** [comment]
Hi @renebrandel! Is there a way I can use directives such as @model, @auth without `amplify init`?

**Comment by renebrandel** [comment]
Hey @JeffreyWardman If you follow these CDK instructions, you shouldn't need to use the Amplify CLI beyond for client code generation (which works without "amplify init").  https://github.com/aws-amplify/amplify-category-api/issues/1952#issuecomment-1761996214

Trying to understand your use case further though, what's your setup and what are your requirements in more detail?
