### ISSUE TITLE
When I try to push graphql I get the error "subscriptions.onCreate.forEach" is not a function.

### ISSUE THREAD

**Issue by taro-nagano** [aws-amplify/amplify-category-api#1956]
### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v18.18.1

### Amplify CLI Version

12.7.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I did not perform any work other than what was listed on the Hands-on Seminar website.

### Describe the bug

It would be helpful if you could refer to No. 4 of the hands-on seminar on the following site.
"https://pages.awscloud.com/JAPAN-event-OE-Hands-on-for-Beginners-amplify-2022-confirmation-774.html"

When creating a GraphQL API in this hands-on seminar, we used the command "amplify add api" to create Grapfql.
Therefore, I edited "schema.graphql" as shown below and executed "amplify push".

```
type Message
  @model (
    mutations: {create: "createMessage"}
    subscriptions:  {onCreate: "onCreateMessage"}
  )
  @auth(rules: [
    {allow: owner, operations:[read, create, delete]}
    {allow: private,  operations:[read]}
  ])
{
  id: ID!
  content: String!
}
```

Then, an error like the following will occur:
`subscriptions.onCreate.forEach is not a function`

I don't know the cause, so please let me know

### Expected behavior

We aim for the "amplify push" to be successful.

### Reproduction steps

It would be helpful if you could refer to No. 4 of the hands-on seminar on the following site.
"https://pages.awscloud.com/JAPAN-event-OE-Hands-on-for-Beginners-amplify-2022-confirmation-774.html"

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by sundersc** [comment]
@taro-nagano - Looking at the model directive definition, I see that the subscription names is an array. Could you try the below?

```graphql
type Message
  @model (
    mutations: {create: "createMessage"}
    subscriptions:  {onCreate: ["onCreateMessage"]}
  )
  @auth(rules: [
    {allow: owner, operations:[read, create, delete]}
    {allow: private,  operations:[read]}
  ])
{
  id: ID!
  content: String!
}
```

**Comment by AnilMaktala** [comment]
Hi @taro-nagano, Are you still experiencing this issue?

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
