### ISSUE TITLE
Amplify creates relationship between models even though schema.graphql doesnt specify any

### ISSUE THREAD

**Issue by ckgupta** [aws-amplify/amplify-category-api#1969]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.3

### Amplify CLI Version

12.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Not yet

### Describe the bug

0

I am facing a weird issue where the amplify-cli creates a relationship stack between Foo and Bar model eventhough I have not specified any as you can see in the screenshot

```
type Foo @model (queries: null, mutations: null, subscriptions: null) {
  id: ID! @primaryKey
  name: String! @index(name: "byName", queryField: "fooByName")
  description: String
}

type Bar @model (queries: null, mutations: null, subscriptions: null) {
  id: ID! @primaryKey
  name: String! @index(name: "byName", queryField: "barByName")
  description: String
}
```
in build/cloudformation-template.json, I see that the Resources.Bar.Parameters has an entry which doesnt make sense

```
"referencetotransformerrootstackFooNestedStackFooNestedStackResource8AC2D3F9OutputstransformerrootstackFooQueryfooByNamepostAuth0FunctionQueryfooByNamepostAuth0FunctionAppSyncFunction82371669FunctionId": {
                    "Fn::GetAtt": [
                        "Foo",
                        "Outputs.transformerrootstackFooQueryfooByNamepostAuth0FunctionQueryfooByNamepostAuth0FunctionAppSyncFunction82371669FunctionId"
                    ]
                }
```
I created 2 different models Foo and Bar without any relationship so I am not expecting any relationship to exist between Foo and Bar in cloudformation-template.json

### Expected behavior

There should not be any relationship to the Foo stack in Bar stack. This is happening only if there is an index added for Bar model

### Reproduction steps

1. amplify init
2. amplify add api
3. Add below code to generated schema.graphql   `type Foo @model (queries: null, mutations: null, subscriptions: null) {
  id: ID! @primaryKey
  name: String! @index(name: "byName", queryField: "fooByName")
  description: String
}

type Bar @model (queries: null, mutations: null, subscriptions: null) {
  id: ID! @primaryKey
  name: String! @index(name: "byName", queryField: "barByName")
  description: String
}`
4. Verify in the build/cloudformation-template.json file, the the Resources.Bar.Parameters has an entry for `referencetotransformerrootstackFooNestedStackFooNestedStackResource8AC2D3F9OutputstransformerrootstackFooQueryfooByNamepostAuth0FunctionQueryfooByNamepostAuth0FunctionAppSyncFunction82371669FunctionId` which doesnt make sense

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ckgupta** [comment]
@ykethan thanks for your response. Meanwhile, Can you please help me with any documentation on amplify to customize the default resolver created using amplify command like adding more functions to the pipeline resolvers . Should the custom pipeline resolvers be placed in customResources.json or modify in the modal.json files only

**Comment by AnilMaktala** [comment]
Hey @ckgupta, "As we work on replicating this issue, please refer [this](https://docs.amplify.aws/cli/graphql/custom-business-logic/#vtl-resolver) section in the documentation for information on custom resolvers."

**Comment by ckgupta** [comment]
Hi @AnilMaktala thanks for the link! 
Please note that the issue I described happens only if the `Bar` model has an index defined. If there is no index then there is no relationship created.
As I am planning to write the resolvers in Javascript, I had to move the resources from Foo.json and Bar.json from `amplify/backend/api/<api_name>/**build**/stacks/<model>.json` to `amplify/backend/api/<api_name>/stacks/customResources.json` and in doing so this extra relationship being created fails with an error saying that the stack doesn't exist

**Comment by AnilMaktala** [comment]
Hey @ckgupta, Thank you for raising this. I've successfully reproduced the issue by following the steps outlined in the description. Therefore, I'm classifying this as a bug for the team to investigate further.

<img width="1011" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/d2076ce9-d2a6-4809-9d79-5d5ed88d2a64">

**Comment by sundersc** [comment]
This is not establishing a relationship between the data models. Some of the generated resolvers are identical, in such cases amplify generates one resource and reference it other child stacks whenever possible.
