### ISSUE TITLE
Not Authorized to access objects list 

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-category-api#1975]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.17.1

### Amplify CLI Version

12.7.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No.

### Describe the bug

Hi, I do not understand at all.
With this object : 

```
type Todo
  @model
  @auth(
    rules: [
      { allow: public, operations: [read], provider: iam }
      { allow: owner }
    ]
  ) {
  id: ID!
  text: String!
}

```
Unauthenticated users can't get todos list. 401. ???

### Expected behavior

Unauthenticated users can get todos list. 200.

### Reproduction steps

ok.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by rudyhadoux** [comment]
My Amplify folder is here : 
https://github.com/rudyhadoux/amplify
Thanks.
I am going to see.

**Comment by rudyhadoux** [comment]
I do not understand because for this project i have no #currrent-cloud-backend folder...

**Comment by rudyhadoux** [comment]
There is : 

```
#if( $util.authType() == "IAM Authorization" )
  #if( !$isAuthorized )
    #if( $ctx.identity.userArn == $ctx.stash.unauthRole )
      #set( $isAuthorized = true )
    #end
  #end
#end

```
But it fails : Unauthorized.

**Comment by rudyhadoux** [comment]
I do not understand why UnauthRole can do
<img width="1522" alt="Capture d’écran 2023-10-20 à 15 59 10" src="https://github.com/aws-amplify/amplify-category-api/assets/45458482/a9a16954-85d9-4d3a-af7d-c6136a609a5f">
 mutations...

**Comment by ykethan** [comment]
Hey @rudyhadoux, Thank you for the information. The setup does appears to have the correct configuration. Additionally, tried reproducing the issue in a sample application but did not observe this behaviour.

To test the IAM auth from the AppSync console, you will need to allow list the user account or the role in your `custom-roles.json`. The information is currently documented [here](https://docs.amplify.aws/cli/graphql/authorization-rules/#use-iam-authorization-within-the-appsync-console)
On adding this, do let us know if you observe a similar issue.

Additionally, curious does this application have a any configuration on the frontend that may be causing this issue. How is Amplify library configured does this have configuration similar to the example [here](https://docs.amplify.aws/start/getting-started/data-model/q/integration/js/#connect-frontend-to-api)

**Comment by rudyhadoux** [comment]
Absolutely strange.... It works.
The reason : Angular 16 changes the configuration with AWS Amplify.
This Angular Amplify project works : 
https://github.com/rudyhadoux/amplify3

**Comment by rudyhadoux** [comment]
In the Appsync console when I select IAM and the query i remains UNAUTHORIZED.
But it works with Angular.
Absolutely strange....

**Comment by ykethan** [comment]
@rudyhadoux glad to hear you were able to get the application working. to note, in order for us to make a query on AppSync console using IAM auth, we need to add the `custom-roles.json` as in https://docs.amplify.aws/cli/graphql/authorization-rules/#use-iam-authorization-within-the-appsync-console
as i did not observe here: https://github.com/rudyhadoux/amplify3/tree/main/amplify/backend/api/essai

**Comment by rudyhadoux** [comment]
So that is the reason ok.
Thanks.

**Comment by rudyhadoux** [comment]
I don't understand.
Now I have this error.
The security token included in the request is invalid. (Service: DynamoDb, Status Code: 400, Request ID: CTL7OOMSTB4JI4SSFLHI9RI14RVV4KQNSO5AEMVJF66Q9ASUAAJG).

**Comment by rudyhadoux** [comment]
The second try works.

**Comment by rudyhadoux** [comment]
I don't understand. If i ask for List with no objects it works.
If a user creates an object.
The public access to the list of objects is unauthorized.
Very painful....

**Comment by rudyhadoux** [comment]
<img width="523" alt="Capture d’écran 2023-10-23 à 18 42 48" src="https://github.com/aws-amplify/amplify-category-api/assets/45458482/1d6625f7-ada4-4581-863a-65464c87c80c">

**Comment by rudyhadoux** [comment]
```
type Informationspubliques
  @model
  @auth(
    rules: [
      { allow: public, operations: [read], provider: iam }
      { allow: owner }
    ]
  ) {
****
}
```

**Comment by rudyhadoux** [comment]
```
const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_cognito_identity_pool_id": "eu-west-3:5eab86a-48f8-9f2a-2d4aeed7efbb",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_4105i",
    "aws_user_pools_web_client_id": "2763i5v0cn38vggm39c",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://eqalkphquxfszula.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "essai23b12167ebea1fd768125b996153843-dev",
    "aws_user_files_s3_bucket_region": "eu-west-3"
};


export default awsmobile;
```

**Comment by rudyhadoux** [comment]
When I use Cognito + API KEY there is absolutely no problem.

**Comment by rudyhadoux** [comment]
It seems that the problem AWS_IAM + COGNITO is old.
https://github.com/aws-amplify/amplify-js/issues/4636

**Comment by rudyhadoux** [comment]
I think I will go back to a custom api key.

**Comment by sundersc** [comment]
'IAM::public' auth rule is strictly for unauthenticated users. If you would like to use IAM with authenticated and unauthenticated users, add both 'IAM::public' and 'IAM::private' auth rules on the model.

**Comment by rudyhadoux** [comment]
Hi,
Absolutely not.
All models are like this : 

```
type Informationspubliques
  @model
  @auth(
    rules: [
      { allow: public, operations: [read], provider: iam }
      { allow: owner }
    ]
  ) {
****
}
```
AWS_IAM only for public access.
COGNITO only for private access.

**Comment by AnilMaktala** [comment]
Hey @rudyhadoux, We have a follow-up question for you. Could you please confirm whether the `Guest` access is enabled in the `Cognito console` under the `Identity pool` in the 'User access' section?

![image](https://github.com/aws-amplify/amplify-category-api/assets/3206171/0c844f37-ae94-4ebe-b1cc-c90091b27867)

**Comment by rudyhadoux** [comment]
I am back with an API_KEY but i will do an other test with AWS_IAM and I will tell you.

**Comment by rudyhadoux** [comment]
With a test, the answer is yes.
Guest access is active.

**Comment by AnilMaktala** [comment]
Hey @rudyhadoux, Thank you for the confirmation. One last question before our call tomorrow: are you making this API call after logging into the app or before logging in?

**Comment by rudyhadoux** [comment]
Hi, 
I am in the process of putting a test project, which you can deploy, on Github.
Public queries are always "without logging in".

**Comment by rudyhadoux** [comment]
I do not understand at all. Because The test works. 
If I do a test with a single object in the folder of an Angular application it works. 
If I take the aws-exports.js file from another Amplify branch it doesn't work... 
Really strange.

**Comment by rudyhadoux** [comment]
I think that the best thing to do is I run my web app live to show you.

**Comment by AnilMaktala** [comment]
Hey @rudyhadoux, Thank you for your time during our call and for walking me through the issue. Could you please attempt to include the configuration in the `component.ts` file where you're making the GraphQL API call and inform me of the outcome? You can refer to the example below for guidance.

```
import { Component } from '@angular/core';

import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { APIService, Todo } from '../API.service';

import { Amplify } from 'aws-amplify';

const myAppConfig = {
  // ...
  aws_appsync_graphqlEndpoint:
    'https://xxxxxxx.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AWS_IAM',
  aws_cognito_identity_pool_id:
    'us-east-1:xxxxx',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_xxxxxx',
  aws_user_pools_web_client_id: 'xxxxxxxxx',
  // ...
};

Amplify.configure(myAppConfig);

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css'],
})
export class TodoComponent {
  public createForm: FormGroup;
  public todos: Array<Todo> = [];
  constructor(private api: APIService, private fb: FormBuilder) {
    this.createForm = this.fb.group({
      name: ['', Validators.required],
      description: ['', Validators.required],
   
    });
  }
  async ngOnInit() {
    /* fetch restaurants when app loads */
    this.api.ListTodos().then((event) => {
      this.todos = event.items as Todo[];
    });
  }
}
```

**Comment by rudyhadoux** [comment]
Hi,

I do not use api.ListTodos() but : 
const result = await API.graphql({ query: listTodos });

With API.graphql I can set the auth mode.

**Comment by rudyhadoux** [comment]
Is it possible to set the duration to infinite ?
Without end ?
If it is possible I will not use AWS_IAM.

**Comment by rudyhadoux** [comment]
I do not choose Angular but Typescript. 
I don't think this is the source of the problem.

**Comment by rudyhadoux** [comment]
I changed the backend and chose Angular. I used this.api.ListTodos() and it works.

There is no need to put the auth mode with the API.ts CRUD functions?

**Comment by AnilMaktala** [comment]
> Is it possible to set the duration of an API KEY to infinite ? Without end ? If it is possible I will not use AWS_IAM.

The current maximum allowable expiration period is 365 days.

**Comment by rudyhadoux** [comment]
In the example code that you recommended to me, what is new ?
With amplify update auth can the duration of an API KEY be extended ?
I do some test again today. I will put my tests on Github.

**Comment by rudyhadoux** [comment]
It does not work at all but I am giving up.

**Comment by AnilMaktala** [comment]
Hey @rudyhadoux, It seems the suggested workaround didn't solve your problem. Would you be able to create a help thread on Discord at this https://discord.com/channels/705853757799399426/1019643921137139772

**Comment by rudyhadoux** [comment]
In the example code that you recommended to me, what is new ?

With amplify update api, can the duration of an API_KEY be extended ?

APIService CRUD functions adapt to authentication mode ? Because by example this.api.ListTodos() has no auth argument. Instead of await API.graphql({
query: queries.listTodos,
variables: {
},
authMode: 'AWS_IAM',
});

**Comment by rudyhadoux** [comment]
@AnilMaktala I asked you for a complete Angular example with IAM and Cognito but nothing.

**Comment by rudyhadoux** [comment]
A basic working example with all the lines of amplify-cli to generate project. That is what I need.

**Comment by AnilMaktala** [comment]
@rudyhadoux,In the sample I'm providing, I included the API configuration within the same file.

**Comment by rudyhadoux** [comment]
For the amplify update auth, you chose sign in with IAM ?
Because I sign in with Cognito.

**Comment by AnilMaktala** [comment]
Here is the git repo https://github.com/AnilMaktala/amplify-app-iam

**Comment by AnilMaktala** [comment]
run `amplify update api` and you can select IAM as the default authentication method .

**Comment by rudyhadoux** [comment]
I must do `amplify update auth` to allow unauthenticated users with IAM.
Thanks for your repo but there is no Auth service to sign in. The creation of todos needs to be authenticated.

**Comment by rudyhadoux** [comment]
"aws_appsync_authenticationType": "AWS_IAM",
    "aws_appsync_apiKey": "da2-amsbt7776je6lbxp7cnl35vzry"
???

With IAM there is no api key...

**Comment by AnilMaktala** [comment]
I've created the API in a different Amplify app and imported it into this app.

**Comment by AnilMaktala** [comment]
Here is the app where i created the API https://github.com/AnilMaktala/iampublictest

**Comment by rudyhadoux** [comment]
There is no need to do `amplify update auth` for IAM + COGNITO ?

**Comment by AnilMaktala** [comment]
Did you remove the previously configured IAM authentication in the app after our meeting? if yes, Please add the IAM auth using `amplify update auth` and also run `amplify udpate api` and configure the IAM as default auth.

**Comment by rudyhadoux** [comment]
I will put on Github a full example with amplify-ui. 
Helped with https://github.com/gsans/aws-amplify-workshop-ui-angular-solution
I will put all the amplify-cli lines too.
So you can tell me if there is an error.

**Comment by rudyhadoux** [comment]
It does not work.
https://github.com/rudyhadoux/site2

**Comment by rudyhadoux** [comment]
https://github.com/rudyhadoux/site2
It does not work at all.

**Comment by AnilMaktala** [comment]
@rudyhadoux, I appreciate you sharing the repository. I've cloned your repository and successfully deployed it in my AWS account, and I can view the results for `/public`. Are you encountering any specific errors, and if so, could you please provide me with the details of the issue you're facing?

<img width="609" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/1c8b41cf-262f-4a8f-958f-2542b57d513f">

**Comment by rudyhadoux** [comment]
Hi @AnilMaktala,
Did you just clone and do ng serve ? 
It is so strange...
See my result.
<img width="1910" alt="Capture d’écran 2023-11-03 à 14 24 48" src="https://github.com/aws-amplify/amplify-category-api/assets/45458482/0afca3a4-2802-4ff0-a666-7cc1b630c382">

**Comment by rudyhadoux** [comment]
Your result is absolutely IMPOSSIBLE.
Because I checked. There is no todo in the DynamoDB table.
<img width="1044" alt="Capture d’écran 2023-11-03 à 14 32 17" src="https://github.com/aws-amplify/amplify-category-api/assets/45458482/493c4ffa-2e90-47bb-a01c-cf01b0fab008">

**Comment by rudyhadoux** [comment]
You have to clone Amplify too. The same project. The same aws-exports.js.
Otherwise you can't compare...

**Comment by AnilMaktala** [comment]
Here are the steps i followed,
<img width="852" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/d04dfd68-ed9e-4a5c-9e6e-75df83d1e625">
<img width="1039" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/0da1ab24-9f04-4fad-a667-63f5a5b4fe74">
<img width="1084" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/a04ae38b-1bba-43f8-8d0a-f2ab25fba212">
<img width="917" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/4c0d7f4d-7f17-469e-9650-4aa719239b29">
<img width="1069" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/ea2d15c7-34c6-4ba3-a044-54f87d1e3ea5">
<img width="1081" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/dbe57927-096c-4c0a-b62b-cd955641b108">

**Comment by rudyhadoux** [comment]
Last night I thought a lot about this endless problem. 
And when launched, the application can connect to a "public" account and make requests privately.

With this schema : 
  ```
@auth(
    rules: [
      { allow: private, operations: [read] }
      { allow: owner }
    ]
  )
```

And connect after when authentication is required.

**Comment by rudyhadoux** [comment]
If I understand well, you clone my Amplify folder and you just did **amplify push**... 
So is there a problem with my AWS account ? Is that possible ?

**Comment by AnilMaktala** [comment]
> You have to clone Amplify too. The same project. The same aws-exports.js. Otherwise you can't compare...

"By default, git ignores aws-export.js. I've utilized the one generated after running 'amplify init,' which is configured for my AWS account."

**Comment by AnilMaktala** [comment]
Have you got a chance to create a thread in Discord? it will help me to connect to you.

**Comment by rudyhadoux** [comment]
I do not use Discord. For ? What is the goal ?
Instead of cloning my amplify folder, could you please create a new one and give me your amply-cli lines...

**Comment by rudyhadoux** [comment]
I have a Discord account sorry.
rudy6476

**Comment by AnilMaktala** [comment]
> I have a Discord account. @rudy6476

Could you please create help thread here https://discord.com/channels/705853757799399426/1019643921137139772

**Comment by rudyhadoux** [comment]
When I click your link there is nothing...
<img width="1565" alt="Capture d’écran 2023-11-03 à 15 08 29" src="https://github.com/aws-amplify/amplify-category-api/assets/45458482/112edc3b-f023-473c-91f2-ca5ee27aabb9">

**Comment by AnilMaktala** [comment]
you should see this Amplify help channel

<img width="1141" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/ce4bebd8-40fe-44ec-961c-3da1746d322f">

**Comment by rudyhadoux** [comment]
Thanks to Anil.
The solution is : 
```
{ allow: public, operations: [read], provider: iam }
{ allow: private, operations: [read], provider: iam }
```

**Comment by rudyhadoux** [comment]
I think something is wrong. Because public queries do not require private access...
