### ISSUE TITLE
Modifying the default resolver created by @Model directive still has reference to not required parameters

### ISSUE THREAD

**Issue by ckgupta** [aws-amplify/amplify-category-api#1980]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.16.0

### Amplify CLI Version

12.7.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I moved the appsync resolvers and appsync functions to amplify/backend/api/<api_name>/stacks/CustomResources.json and replaced parameters as listed below since these values are by default passed to customResources as per this link https://docs.amplify.aws/cli-legacy/graphql-transformer/resolvers/#custom-resolvers

  "referencetotransformerrootstackGraphQLAPI20497F53ApiId" -> "AppSyncApiId",
  "referencetotransformerrootstackS3DeploymentBucket7592718ARef" -> "S3DeploymentBucket",
  "referencetotransformerrootstackS3DeploymentRootKeyA71EA735Ref" -> "S3DeploymentRootKey",
  "referencetotransformerrootstackenv10C5A902Ref": "env",

Still I see that the amplify/backend/api/<api_name>/build/cloudformation-template.json contains the the unused parameters and it gives an error on amplify push saying parameters are not present.

As a workaround, I added the parameters to amplify/backend/api/<api_name>/parameters.json with some default value and then the amplify push passed.

Expectation: I was expecting cloudformation-template.json file to be modified as per the changes in customResources.json.

### Describe the bug

I see that the amplify/backend/api/<api_name>/build/cloudformation-template.json contains the the unused parameters and it gives an error on amplify push saying parameters are not present.

Only when, I added the parameters to amplify/backend/api/<api_name>/parameters.json with some default value, the amplify push passed.

### Expected behavior

 I was expecting cloudformation-template.json file to be modified as per the changes in customResources.json.

### Reproduction steps

1. amplify init
2. amplify add api - select graphql to create appsync resource
3. Update the generated schema.graphql with the basic schema as below `type Foo @model (queries: null, mutations: null, subscriptions: null) @auth(rules: [{ allow: public }]) {
  id: ID! @primaryKey
  name: String! @index(name: "byName", queryField: "fooByName")
  description: String
}`
4. amplify api gql-compile
5. Move the generated appsync function, resolvers, parameters, outputs from `amplify/backend/api/<api_name>/build/stacks/Foo.json` file to `amplify/backend/api/<api_name>/stacks/customResources.json`
6. Move the `amplify/backend/api/<api_name>/build/stacks/Foo.json` file to `amplify/backend/api/<api_name>/stacks/Foo.json` file and make the resources as Empty Resource
7. Update the parameters in `amplify/backend/api/<api_name>/stacks/customResources.json` to `  "referencetotransformerrootstackGraphQLAPI20497F53ApiId" -> "AppSyncApiId",
  "referencetotransformerrootstackS3DeploymentBucket7592718ARef" -> "S3DeploymentBucket",
  "referencetotransformerrootstackS3DeploymentRootKeyA71EA735Ref" -> "S3DeploymentRootKey",
  "referencetotransformerrootstackenv10C5A902Ref": "env"`
8. amplify push -y
10. Getting error that the parameters are not present `referencetotransformerrootstackGraphQLAPI20497F53ApiId, referencetotransformerrootstackS3DeploymentBucket7592718ARef, referencetotransformerrootstackS3DeploymentRootKeyA71EA735Ref`

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by phani-srikar** [comment]
Hey @ckgupta, I didn't quite get the idea of what you're trying to do from your steps listed. The documentation you linked pertains to older version of transformers but you're using the latest CLI version. If you want to override the generated resolvers for your schema, you can do so by following this latest documentation: https://docs.amplify.aws/cli/graphql/custom-business-logic/#override-amplify-generated-resolvers

**Comment by ckgupta** [comment]
@phani-srikar I am trying to add more pipeline functions to the default pipeline config of the generated resolvers. As I plan to make use of APPSYNC_JS runtime (i.e., Javascript) not seeing anyway to achieve it using the link as it talks only about VTLs
https://docs.amplify.aws/cli/graphql/custom-business-logic/#override-amplify-generated-resolvers

So, I moved the resolvers and the stacks as defined in the my steps (similar to older version of transformers) and it works. But I dont understand the fact that the cloudformation-template.json still contains the parameters which is not used in the custom stacks, 

As you can see, all of the default generated parameters can be very well be replaced by the [parameters](https://docs.amplify.aws/cli-legacy/graphql-transformer/resolvers/#custom-resolvers) available to the custom stack as mentioned below

"referencetotransformerrootstackGraphQLAPI20497F53ApiId" -> "AppSyncApiId",   "referencetotransformerrootstackS3DeploymentBucket7592718ARef" -> "S3DeploymentBucket",   "referencetotransformerrootstackS3DeploymentRootKeyA71EA735Ref" -> "S3DeploymentRootKey",   "referencetotransformerrootstackenv10C5A902Ref": "env"

For this, also there is a workaround to add these parameters in the `amplify/backend/api/<api_name>/parameters.json`. But this error should have not come ideally since the parameters are not being used.

**Comment by phani-srikar** [comment]
Hi @ckgupta, the way CLI constructs the nested stacks and their dependencies would have caused you to have a copy of the parameters in your custom stacks. However, you would not need to copy any of the parameters or stacks if you just want to add resolver slots to existing pipeline resolvers. That's covered in this section https://docs.amplify.aws/cli/graphql/custom-business-logic/#extend-amplify-generated-resolvers.

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
