### ISSUE TITLE
Question: Modelling schema for social app

### ISSUE THREAD

**Issue by itechevo** [aws-amplify/amplify-category-api#1981]
### Description

This is question on how to achieve the following requirements:

I have a user and they can friends:

```
type UserFriend @model @auth(rules: [ {allow: owner, ownerField: "userId" }, {allow: private}]) {
    id: ID!
    userId: ID! @index (name : "byUserId")
    friendId: ID 
    friend: User @hasOne (fields:["friendId"])
    user: User @hasOne (fields:["userId"])
}
```

In user model, I will have this link:

```
    userFriends: [UserFriend] @hasMany (indexName: "byUserId", fields: ["userId"])
```

This setup means, I need to have 2 entries for each friends, if `User A` is friend with `User B`, `UserFriend` model with have 2 entries for this. This is ok, I can list all `User A` friends in one query and apply pagination.

Now if User A wants to access all his friends posts and apply paginations, we can't do it, because we can only access nested posts of each friends and not query the whole post model.

How to model this relationship to get all post of USER A friends and apply paginations?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

0.6.12

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @itechevo - Since this question isn't specific to Flutter, I have transferred it to the amplify-category-api repo.

**Comment by AnilMaktala** [comment]
Hey @itechevo, Thank you for bringing this up. Would it be possible for you to share the current model schema so that we can better grasp the existing relationships and offer recommendations?

**Comment by itechevo** [comment]
This what I have now:

```
type User @model @auth(rules: [{allow: owner}]) {
    userId: ID! @primaryKey
    name: String
    userPosts: [UserPost] @hasMany(indexName: "byUserId", fields: ["userId"])
}

type UserPost @model @auth(rules: [{allow: owner}, {allow: private, provider: userPools, operations: [read]}]){
    feedId: ID! @primaryKey
    userId: ID! @index (name: "byUserId")
    content: String
    mediaUrl: String
    categories: [String]
    user: User @hasOne(fields: ["userId"])
}

type UserFriend @model @auth(rules: [{allow: owner}, {allow: private, provider: userPools, operations: [read]}]) {
    id: ID!
    userId: ID! @index(name: "byUserId")
    friendUserId: ID!
    user: User @hasOne(fields :["userId"])
    friendUser: User @hasOne(fields: ["friendUserId"])
}
```

How to access all post of all my friend with **pagination**?

I can query **UserFriend** and get nested **friendUser** and from there access **userPosts**. Thats what most examples show to do. But that is a list of posts per users, which means I need query all posts per friend and sort on client side to display. This is not efficient, I need to query  **UserPost** directly with pagination. It this possible at all?

**Comment by dpilch** [comment]
Sorry for the slow response @itechevo. Were you able to resolve this?
