### ISSUE TITLE
Elastic search guessed field type wrong in one env and right in another env

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-category-api#199]
**Which Category is your question related to?**
api, `@searchable`

**Amplify CLI Version** 
4.44.0

**What AWS Services are you utilizing?**
appsync, ddb, lambdas, amplify console, cognito, s3

**Provide additional details e.g. code snippets**
Noticed something very strange the other day. we're storing a date field as a string because it comes from a third party and not in an iso format so we keep on our side for auditing. in one env, elastic search treated it as string. in another it treated it as a date. probably because one env we were creating manually for some tests. so to fix i dropped all the searchable directives in the problem environment (prod!) and recreated it, and sent a few mutations with strings in them for good measure. all good. but here's the problem, elastic search was failing to injest new records (in prod!) and so list and search results were not surfacing the records we were expecting but we could see them on details pages. very frustrating. one of us found the issue by opening the logs for the lambda that does the streaming of the data and found the error. i guessed how to fix and it luckily that worked. is there anyway to manage es better and get a better sense of how it makes assumptions about data?

The issue here is one command `@searchable` does a lot for the user but there doesn't seem to be a way to dig deeper beyond modifying the function. 

Internally, we're talking about the tradeoffs between amplify/dynamodb/elasticsearch and thinking about moving to a relational db since when you add ES the costs go up big time. And we can always switch back when we need to scale.

**Comment by josefaidt** [comment]
Closing due to age and inactivity
