### ISSUE TITLE
beginsWith not working as expected

### ISSUE THREAD

**Issue by ryanSoftwareEngineer** [aws-amplify/amplify-category-api#1993]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.16.1

### Amplify CLI Version

12.4.0

### What operating system are you using?

windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no manual changes to api.

### Describe the bug

I have this model 

```
type User
  @model
  @auth(
    rules: [
      { allow: owner }
      { allow: private, operations: [read, update, delete, create] }
    ]
  )
  @aws_cognito_user_pools {
  id: ID!
  preferred_username: String
  aa: Float
  bb: Float
  version: Int
    @index(
      name: "getUsersName"
      sortKeyFields: ["preferred_username", "updatedAt"]
    )
    @index(
      name: "getUsersByAB"
      sortKeyFields: ["aa", "bb", "updatedAt"]
    )
  updatedAt: String
}
```

i'm trying to query for users who's name `beginsWith` "ryan" and sorted by updatedAt. is this possible?

I'm able to query for users using` betweens` correctly and sorted by updatedAt. 

When I try with beginsWith 
```

  API.graphql({
      query: usersByVersionAndPreferred_usernameAndUpdatedAt,
      variables:    {
        version: 1,
        preferred_usernameUpdatedAt: {
          beginsWith: { preferred_username: "ryan" },
        },
        sortDirection: "DESC",
      },
    })

```

throws an error "Query condition missed key schema element" ( i also tried adding updatedAt: "2023" it threw same error)

but when I use 
```
   variables: {
              version: 1,
              aaBbUpdatedAt: {
                between: [
                  {
                    aa: minAA,
                    bb: minBB,
                  },
                  {
                    aa: maxAA,
                    bb: maxBB,
                  },
                ],
              },
              sortDirection: "DESC",
            },

```
this works great. 

is there a reason beginsWith doesn't work here and between does? I would like to avoid filter or scans and use index if possible

### Expected behavior

results should return users that beginWith entered phrase

### Reproduction steps

1. Create user model,

```
type User
  @model
  @auth(
    rules: [
      { allow: owner }
      { allow: private, operations: [read, update, delete, create] }
    ]
  )
  @aws_cognito_user_pools {
  id: ID!
  preferred_username: String
  aa: Float
  bb: Float
  version: Int
    @index(
      name: "getUsersName"
      sortKeyFields: ["preferred_username", "updatedAt"]
    )
    @index(
      name: "getUsersByAB"
      sortKeyFields: ["aa", "bb", "updatedAt"]
    )
  updatedAt: String
}
```
2. create mock users with version and preferred_username and createUser mutation
3. write query to use beginsWith to query for users who's name starts with a phrase and sorted by last updatedAt 

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

{"data": {"usersByVersionAndPreferred_usernameAndUpdatedAt": null}, "errors": [{"data": null, "errorInfo": null, "errorType": "DynamoDB:ValidationException", "locations": [Array], "message": "Query condition missed key schema element", "path": [Array]}]}

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi @ryanSoftwareEngineer, Thank you for raising this. I am unable to replicate the problem using the schema described in the description. Have you encountered the same issue when using the AppSync console?

![image](https://github.com/aws-amplify/amplify-category-api/assets/3206171/c8e8c32f-47a0-41c8-a489-810bbe1af0fe)

**Comment by ryanSoftwareEngineer** [comment]
> Hi @ryanSoftwareEngineer, Thank you for raising this. I am unable to replicate the problem using the schema described in the description. Have you encountered the same issue when using the AppSync console?
> 
> ![image](https://user-images.githubusercontent.com/3206171/278516483-c8e8c32f-47a0-41c8-a489-810bbe1af0fe.png)

My apologies I should have mentioned i'm using `amplify mock api ` and connecting to a local endpoint. I haven't updated resources in the cloud yet. I was hoping to validate my access patterns with locally first. I was trying to be frugal with pushes. Is it working for you on local? If it doesn't work on local I'll test it on live thank you!

**Comment by AnilMaktala** [comment]
Thank you for the prompt response and the additional details. I haven't had the chance to test it using a mock yet. I will validate it using `amplify mock api` and keep you informed.

**Comment by ryanSoftwareEngineer** [comment]
> I created a second table and it seems to work. Perhaps it's something on my end, my apologies. I'll look into it more. Thank you for verifying!
