### ISSUE TITLE
Fargate API Project Structure - how to exclude node_modules from dist.zip

### ISSUE THREAD

**Issue by mgill404** [aws-amplify/amplify-category-api#2045]
### Amplify CLI Version

12.8.2

### Question

I've created an API with the following commands

```
amplify add api
>> Rest
>> API Gateway + AWS Fargate (Container-based) 
>> Provide a friendly name for your resource to be used as a label for this category in the project: containerABC123
>>  What image would you like to use ? Custom (bring your own Dockerfile or docker-compose.yml) 
```

I then place my Remix Shopify app code within the src folder of the API
```
// Remix app lives here
project_root/amplify/backend/api/containerABC123/src/
```

I will run the project locally to prepare some code changes, and when this happens node_modules is populated inside of this folder.

Then when I run `amplify push api`, I get an error that the lambda is larger than 250 MB.

I realized this is due to the node_modules being bundled in dist.zip. If I removed node_modules from my src folder, everything works well.

I'm curious if there's an automatic way to exclude node_modules from the `amplify push` upload.

**Comment by mgill404** [comment]
For some more context:

My amplify project doesn't have a frontend. The frontend is served from this Fargate API.

The API src folder is the main part of the repo.


Many people online suggest making a copy of your code inside or API src folder. This doesn't sit right with me.

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
