### ISSUE TITLE
Unable to add Custom GraphQL Transformers due to incomplete ToDo

### ISSUE THREAD

**Issue by craig-at-metashield-io** [aws-amplify/amplify-category-api#2077]
### How did you install the Amplify CLI?

npm -g

### If applicable, what version of Node.js are you using?

v18.17.1

### Amplify CLI Version

12.8.2

### What operating system are you using?

macOs Sonoma 14.0

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

nope

### Describe the bug

When adding a custom GraphQL transformer via the `transform.config.json` file, such as:
```
    "transformers": [
      "./graphql-validation-transformer"
    ]
```
it fails when i try to `amplify push` stating:
```
Custom Transformers' should implement TransformerProvider interface
```

searching through the codebase, i find this cracker in `transformer-options-v2.ts` lines 315-319:
```
      if (typeof CustomTransformer === 'object') {
        // Todo: Use a shim to ensure that it adheres to TransformerProvider interface. For now throw error
        // return CustomTransformer;
        throw new Error("Custom Transformers' should implement TransformerProvider interface");
      }
```
added 5 months ago by @alharris-at - it appears this Todo is still outstanding.

### Expected behavior

I expect it to correctly load and execute the transformer

### Reproduction steps

1. create a custom transform
2. add it to the `transform.config.json` file
3. `amplify push -y`

### Log output

<details>

```
# Put your logs below this line
> amplify push 
✔ Successfully pulled backend environment staging from the cloud.

    Current Environment: staging
    
┌──────────┬────────────────────────┬───────────┬───────────────────┐
│ Category │ Resource name          │ Operation │ Provider plugin   │
├──────────┼────────────────────────┼───────────┼───────────────────┤
│ Api      │ XXXXXXXX               │ Update    │ awscloudformation │
├──────────┼────────────────────────┼───────────┼───────────────────┤
│ Api      │ XXXXXXXX               │ No Change │ awscloudformation │
├──────────┼────────────────────────┼───────────┼───────────────────┤
│ Auth     │ XXXXXXXX               │ No Change │ awscloudformation │
├──────────┼────────────────────────┼───────────┼───────────────────┤
│ Storage  │ XXXXXXXX               │ No Change │ awscloudformation │
├──────────┼────────────────────────┼───────────┼───────────────────┤
│ Hosting  │ XXXXXXXX               │ No Change │ awscloudformation │
├──────────┼────────────────────────┼───────────┼───────────────────┤
│ Function │ XXXXXXXX               │ No Change │ awscloudformation │
├──────────┼────────────────────────┼───────────┼───────────────────┤
│ Function │ XXXXXXXX               │ No Change │ awscloudformation │
└──────────┴────────────────────────┴───────────┴───────────────────┘
✔ Are you sure you want to continue? (Y/n) · yes
🛑 Custom Transformers' should implement TransformerProvider interface

```

</details>

### Additional information

The documentation around creating custom transformers is painfully absent.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by sundersc** [comment]
@craig-at-metashield-io Are you exporting an instance of the custom transformer as default? If so, can you try exporting the custom transformer class instead?

**Comment by craig-at-metashield-io** [comment]
good morning @sundersc - thanks, i have managed to work around this issue.
