### ISSUE TITLE
nested resolvers by id possible? 

### ISSUE THREAD

**Issue by ryanSoftwareEngineer** [aws-amplify/amplify-category-api#2110]
### Amplify CLI Version

12.4.0

### Question

Just quick question I'm using a query to get nested items and I want to get a child item from another table where userId == my user id. 

 I only want to get a single nestedItem that belong to me and the parent item (which is a single item but the parent item can have many nestedItems from different users)

 So i got something like this 
```
 items {
        id
        nestedItems(filter: { userId: { eq: $userId} }) {
          items {
            id
          }
        }
}
```

 my model for nestedItems has an index on **userId**  will this filter access the index when getting the record?

lets say there are 1000+ nestedItems with same parent but different userId's .... will this still always return the nestedItems where a nestedItem has a userId or is it possible it'll return nothing because the filtered items weren't in the first 100 limit? 

if thisis the case, is there a way to specify the nested resolver as listNestedItesByUserId  instead of listNestedItems something like

```
items {
  id 
  nestedItemsByUserId(userId: $userId) {
     items {.... 
```

thank you in advance!

**Comment by phani-srikar** [comment]
Hi @ryanSoftwareEngineer, since you want to get the child item and the connected parent and each parent can have multiple children, your use-case can be achieved using a `hasMany - belongsTo` relationship between the 2 models. This automatically creates a GSI that is used to effectively query the connected records.

**Comment by ryanSoftwareEngineer** [comment]
@phani-srikar thank you for your response, in a dynamic list where I need to get a variable number of  child records based on parent records how can I use bidirectional relationship here?

lets say I'm trying to query for parent records for the most recent items so im querying ParentByIdAndCreatedat  and it returns items { id } 

```
 items {
    id
    fields
}
```

in this query the parent returns 100 records and for each parent about half of them have a nested child item that belongs to my userId. So how can I query directly for those child items with 100 parentId's and userId is a single value?

**Comment by dpilch** [comment]
For example:

```graphql
type Foo @model {
  id: ID!
  name: String
  bar: [Bar] @hasMany
}

type Bar @model {
  id: ID!
  name: String
  foo: Foo @belongsTo
}
```

With the above schema `Foo` is the parent and `Bar` is the child. If want to find all of the `Bars` that belong to a given `Foo` but also further filter that based on some attribute of `Bar` I can use a query like below.

```graphql
query MyQuery {
  listBars(filter: {fooBarId: {eq: "7e0f0705-edf0-4b53-a856-ff1a934ed2b1"}, name: {le: "bar2"}}) {
    items {
      id
      name
      foo {
        name
        id
      }
    }
  }
}
```

`fooBarId` is created by the hasMany/belongsTo relationship.

This will give me all `Bars` that have a name less than or equal to `bar2` and that also belong to the `Foo` with ID `7e0f070...`.

**Comment by ryanSoftwareEngineer** [comment]
` 
 listBars(filter: {fooBarId: {eq: "7e0f0705-edf0-4b53-a856-ff1a934ed2b1"}, name: {le: "bar2"}}) {
`
 is it possible it'll return 0 results because the first 1000 Bars weren't eq and le to the params supplied? but in the next 1000 Bars a lot of them have those fooBarId and are le than bar2? 

i'm getting the parent by an id and I wanted to get child by id so that i dont have that situation . Chat gpt told me that amplify filter will perform a  scan and that the situation is possible.

**Comment by dpilch** [comment]
When the hasMany/belongsTo relationship is established a GSI with `fooBarId` as the partition key is created. When using listBars with a filter on the fooBarId a query is preformed on the GSI.

**Comment by ryanSoftwareEngineer** [comment]
yes! thank you!
