### ISSUE TITLE
'enum' ref has wrong types

### ISSUE THREAD

**Issue by erickriva** [aws-amplify/amplify-category-api#2114]
### Environment information

```plain text
System:
    OS: Windows 11 10.0.23590
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Memory: 13.21 GB / 23.91 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.11.0 - ~\AppData\Local\pnpm\pnpm.EXE
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: 0.5.5
    @aws-amplify/backend-cli: 0.9.1
    aws-amplify: 6.0.5
    aws-cdk: Not Found
    aws-cdk-lib: 2.111.0
    typescript: 5.3.2
```

### Description

Using following models:

```
import { a } from "@aws-amplify/backend";

const schema = a.schema({
  ChildGender: a.enum(["MALE", "FEMALE"]),

  Child: a.model({ id: a.id().required(), gender: a.ref("ChildGender") }),

  Pregnancy: a.model({ id: a.id().required(), children: a.hasMany("Child").arrayRequired().valueRequired() })
})
```

and requesting data with:
```
amplifyClient.models.Pregnancy.list({
    selectionSet: [
      "id",
      "children.id",
      "children.gender",
    ],
  })
```

Typescript shows no error, but a wrong type though. `Child` is typed as following:
```
{
    readonly id: string;
    readonly gender: {
        readonly authorization: {};
        readonly required: {};
        readonly [__auth]?: undefined;
        readonly [brand]: "ref";
    } | null;
}[]
```
in this case, `gender` property should be typed as `"MALE" | "FEMALE"`

**Comment by AnilMaktala** [comment]
Hey @erickriva , Thank you for bringing this issue to our attention. We were able to reproduce the problem by following the steps outlined in your report. We have logged this as a bug so our team can investigate further.

schema:
```
const schema = a.schema({
  Status: a.enum(["STARTED", "INPROGRESS", "COMPLETED"]),
  Todo: a
    .model({
      content: a.string(),
      status: a.ref("Status"),
    })
    .authorization([a.allow.owner(), a.allow.public()]),
  User: a
    .model({
      id: a.id().required(),
      name: a.string().required(),
      todos: a.hasMany("Todo").arrayRequired().valueRequired(),
    })
    .authorization([a.allow.public()]),
});

```


<img width="915" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/ca172bf3-4dd7-4b40-9c56-9cdf18befb5a">

**Comment by AnilMaktala** [comment]
I can repro with the latest version.
<img width="815" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/17a13e25-09e3-491d-9505-47486a54d812">

**Comment by iartemiev** [comment]
This bug is fixed in the latest versions of amplify-js and amplify-backend. 
Note that amplify-backend is only releasing new versions under the `beta` tag until the first major version release.

Please upgrade to the following versions in your project:
```json
"dependencies": {
    "aws-amplify": "^6.0.16",
    ...
  },
  "devDependencies": {
    "@aws-amplify/backend": "^0.13.0-beta.1",
    "@aws-amplify/backend-cli": "^0.11.2-beta.1",
    ...
  }
```

The enum type gets correctly resolved when using a custom selection set:
<img width="1303" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/29709626/adee9e09-22f8-40ab-8283-7a6585af7799">
