### ISSUE TITLE
How to fix circular dependency between resources error when I add a DataSource to the resolver.addToSlot method?

### ISSUE THREAD

**Issue by melbahysa** [aws-amplify/amplify-category-api#2116]
### Amplify CLI Version

12.3.0

### Question

I'm developing a custom transformer intended to log every Mutation in our system. Within this transformer, I'm utilizing the addToSlot method from the TransformerResolverProvider interface, as shown below:

```export interface TransformerResolverProvider {
  addToSlot: (
    slotName: string,
    requestMappingTemplate?: MappingTemplateProvider,
    responseMappingTemplate?: MappingTemplateProvider,
    dataSource?: DataSourceProvider,
  ) => void;
}
```
When i add the dataSource to this method like this:
```
const dataSource = ctx.api.host.getDataSource('LogTable') as DataSourceProvider;
resolver.addToSlot(
  'postUpdate',
  MappingTemplate.s3MappingTemplateFromString(
    requestMappingTemplate,
    `${anyResolver.typeName}.${anyResolver.fieldName}.{slotName}.{slotIndex}.req.vtl`
  ),
  MappingTemplate.s3MappingTemplateFromString(
    responseMappingTemplate,
    `${anyResolver.typeName}.${anyResolver.fieldName}.{slotName}.{slotIndex}.res.vtl`
  ),
  dataSource
);
```
           
I get this error in the build:
`Resource is not in the state stackUpdateComplete
Name: apiname (AWS::CloudFormation::Stack), Event Type: update, Reason: Circular dependency between resources: [model1, model2], IsCustomResource: false
`
The build only fails when I add the datasource parameter to this method and I can not figure out why. Am I setting the dataSource wrong?

**Comment by djorgji** [comment]
Hello Amplify Team,

We've concluded that incorporating these specific resolvers into a distinct stack to run after ConnectionStack. We're seeking guidance on how to seamlessly integrate these resolvers into the `postUpdate` slot while establishing them in a separate stack. Your expertise and assistance in this matter would be greatly appreciated. 

Thank you in advance for your support and insights.

**Comment by dpilch** [comment]
Is LogTable part of your GraphQL schema? If that is the case I think that is why you would see the circular dependency issue.

I'm not sure it will be possible to split the resolvers across different stacks. Have you considered using the CloudWatch logs emitted by AppSync?
