### ISSUE TITLE
Deployments fail due to disconnect from build and our s3 `Could not read cloudformation template at path`

### ISSUE THREAD

**Issue by priyapower** [aws-amplify/amplify-category-api#2133]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

20.6.1

### Amplify CLI Version

10.8.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug
⚠️ - If this issue doesn't belong to `amplify-cli` repo but instead a more appropriate repo, please let me know
* We have amplify ci/cd running
* Three backed environments: `dev`, `staging`, and `prod`
* Two hosting environments: `staging`, `prod`
* We also have a testing env and hosting env

After merging a safe PR to our `staging` environment we began seeing this set of errors:
```
2023-12-12T18:12:33.533Z [WARNING]: - Building resource storage/adamariebucket
2023-12-12T18:12:33.736Z [INFO]: [33mCould not read cloudformation template at path: /codebuild/output/src76562180/src/adamarie/amplify/backend/api/adamarie/build/cloudformation-template.json[39m
```

and 
```
2023-12-12T18:13:10.755Z [INFO]: 🛑 The following resources failed to deploy:
2023-12-12T18:13:10.758Z [INFO]: Resource Name: apiadamarie (AWS::CloudFormation::Stack)
                                 Event Type: update
                                 Reason: Parameters: [CreateAPIKey] do not exist in the template
                                 URL: https://console.aws.amazon.com/cloudformation/home?region=us-east-2#/stacks/arn%3Aaws%3Acloudformation%3Aus-east-2%3A886020249653%3Astack%2Famplify-adamarie-staging-151754%2F6c4cb130-6df3-11ee-ab72-029c65e1ea0d/events
2023-12-12T18:13:10.759Z [INFO]: 
2023-12-12T18:13:10.762Z [WARNING]: ✖ There was an error initializing your environment.
2023-12-12T18:13:10.764Z [INFO]: 🛑 Resource is not in the state stackUpdateComplete
2023-12-12T18:13:10.764Z [INFO]: Name: apiadamarie (AWS::CloudFormation::Stack), Event Type: update, Reason: Parameters: [CreateAPIKey] do not exist in the template, IsCustomResource: false
2023-12-12T18:13:10.765Z [INFO]: 
2023-12-12T18:13:10.765Z [INFO]: Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
2023-12-12T18:13:10.844Z [INFO]: 
2023-12-12T18:13:10.844Z [INFO]: Session Identifier: 65b7ff69-33a9-4ba8-9dba-d1637d638556
2023-12-12T18:13:10.875Z [ERROR]: !!! Build failed
```

1. We absolutely know that the resource exists on S3 - however, it's last update was from our previous deployment on 12/8
2. We confirmed a similar error on our testing environment which has no changes within the last 3 weeks
3. This looks like a disconnect from Amplify

### Expected behavior

That our github merge successfully builds and deploys via amplify

### Reproduction steps

1. Create a new dev branch
2. Make some change (in our case it was a test file update)
3. Create PR on GH pointing at our `staging` branch (which is connected to our `staging` hosting environment on Amplify)
4. Merge
5. Watch build on amplify
6. Build fails due to disconnect with `cloudformation-template.json`

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by palpatim** [comment]
Hi @priyapower I'm looking at this issue for the Amplify Data team. Thanks very much for the diagnostic report. I've been trying to reproduce the issue you're experiencing by creating a GraphQL API in CLI version 12.8.2, and then updating it and pushing it in 12.9.0, but I haven't had any luck reproducing so far. According to the diagnostic, I see that you've got the API protected with both user pools and an API key, but that the API key has an expiration of 7 days. I'm assuming that's a relatively recent addition -- can you confirm whether this was something that you added in the same change that triggered the error, or was this added previous to the 12.9.0 upgrade?

**Comment by palpatim** [comment]
Hi @priyapower,

We've successfully reproduced one error: the "missing datasource" error was due to a bug in our support for `@auth` directives on root types (that is, types with no `@model` directive). We're working on a fix for that now. 

We've been unsuccessful reproducing the `Parameters: [CreateAPIKey] do not exist in the template` error though, so we would still appreciate if you could confirm that you were not attempting to add a new API key, but rather pushing a change unrelated to authorization modes.

**Comment by priyapower** [comment]
@palpatim - some additional context
* We did not upgrade our cli version
* Our app has cli version `10.4.1`
* Our engineers have anything between 10.4.1 and 12.8.2
* On Friday, we had a successful deployment
* No changes were made over the weekend
* On Tuesday, someone updated a cypress test
  * No amplify updates were made
  * No auth updates were made
  * No API key updates were made
* They merged their test update to our branch with automatic deployments
* This build failed. Continuously. With `Could not read cloudformation template at path: /codebuild/output/src76562180/src/adamarie/amplify/backend/api/adamarie/build/cloudformation-template.json` and `Parameters: [CreateAPIKey] do not exist in the template`
* We confirmed that our S3 bucket did indeed exist
* Luckily, our devOps eng was able to find a workaround for us that forces the amplify.yml file to use 12.8.2 and not 12.9
* To reiterate - we never attempted any upgrades

**Comment by palpatim** [comment]
Thanks for the additional context and confirmation, @priyapower. We're continuing to investigate the CreateAPIKey error

**Comment by palpatim** [comment]
@priyapower Please do run `amplify diagnose --send-report` using the environment that was experiencing the failures. Let us know the 

Some more questions regarding your setup:

> * We have amplify ci/cd running
> * Three backed environments: dev, staging, and prod
> * Two hosting environments: staging, prod
> * We also have a testing env and hosting env

* Are your three backend environments (dev, staging, prod) are different branches of the same codebase, or totally separate repos?
* Are your two hosting environments (staging, prod) connected to the same backend? If so, which one?
* What does "We also have a testing env and hosting env" mean? That you have separate backend environments for testing & hosting? Separate branches?

Thanks!

**Comment by priyapower** [comment]
@palpatim 
1. We originally saw this on our `staging` hosting environment build within backend, so I ran diagnose within our `staging` backend env: Project Identifier: ef2f0ce6e1363b2bcb65ad9d5c45e760. However, I will call out that we checked this error/behavior on one of our "trash" environments/hosting-environments and saw the exact same set of errors
1. Same repo, different branches
1. Our staging hosting env points to `staging` backend; our main (production) hosting env points to `prod` backend
1. "What does "We also have a testing env and hosting env" mean? That you have separate backend environments for testing & hosting? Separate branches?" - sorry, we have a trash backend and hosting environment where we were testing some possible configs. It is called `jz/aws_amplify_automation` and this is where we tested the same deployment failure
1. Our package.json pulls from 10.4.1 for amplify-cli (at the time of error); while not particular to this context, just thought i would share
1. Our theory is that the hosting environment backend deployment was using 12.9 (whatever is the latest) for amplify cli and by forcing it to use the older 12.8 version, we no longer saw the errors 🤷🏾‍♀️ - so we thought something might be up with 12.9 🤷🏾‍♀️

**Comment by palpatim** [comment]
Thanks for the updated diagnostic, we'll take a look.

There is definitely a bug in 12.9.0 related to `@auth` rules on types without `@model` annotations--that's what was causing the `Cannot find datasource type for model <modelName1>` error you mentioned. We've fixed that in https://github.com/aws-amplify/amplify-category-api/pull/2136 and are preparing a hotfix.

However we're unable to reproduce the missing CreateAPIKey parameter condition in our testing. We've looked through the code and aren't able to identify a condition that is causing that.

**Comment by palpatim** [comment]
@priyapower Thanks for your patience as we've investigated this. We have released CLI version 12.10.0, which I've confirmed compiles your schema without the `Cannot find datasource type for model` errors that were generated previously. Can you see if this version works as expected for you?

We have been unable to reproduce the missing CreateAPIKey parameter condition, and our review of the code leads us to believe this is not a regression in the latest version. If that issue is still blocking your deployments after you test with 12.10.0, we'll need to keep investigating with you to find out what about your project is triggering the error.

**Comment by priyapower** [comment]
@palpatim - thanks for following up. I have no idea what to tell you about the `CreateAPIKey` parameter chaos - hopefully no one else runs into that too

We were not planning on updated to anything later than 12.8 for now, but I will follow up with you after talking with the squad on whether we want to move to 12.10.0

**Comment by palpatim** [comment]
@thanhnguyen195 you also reported this issue -- are you continuing to experience on 12.10.0?

**Comment by palpatim** [comment]
Closing this issue. @priyapower if you do encounter a deployment error when you upgrade, please open a new GitHub issue. We don't have good visibility into comments on old issues.
