### ISSUE TITLE
`No api-key configured` error when trying to add API Key

### ISSUE THREAD

**Issue by oyangjo** [aws-amplify/amplify-category-api#2134]
### Amplify CLI Version

12.9.0

### Question

I am trying to add API_KEY as another way to authenticate. But running into the issue where whenever I try to get a different user with API_KEY, I get an error saying `Errors:  [Error: No api-key configured]`

I did `amplify update api` and added additional auth with API_KEY and `amplify push` afterwards, but still no use.
```
? Select a setting to edit Authorization modes
? Choose the default authorization type for the API Amazon Cognito User Pool
Use a Cognito user pool configured as a part of this project.
? Configure additional auth types? Yes
? Choose the additional authorization types you want to configure for the API (Press <space> to select, <a> to toggle all, <i> t
o invert selection)
❯◉ API key
 ◉ IAM
 ◯ OpenID Connect
 ◯ Lambda
```

I suspect that my `aws-exports.js` is not being updated properly. Because in cloud, I can query with API Key using AWS AppSync. However, locally, I am not able to do so with `amplify mock`.

Should I hand-edit the `aws-exports.js`? What are some ways that I can fix this issue?

schema.graphql
```
type User 
  @model 
  @auth(
    rules: [
      { allow: owner }
      { allow: public, operations: [read], provider: apikey}
    ]
  ) {
  id: ID!
  username: String!
  email: String!
  bio: String
}

```

My aws-exports.js
```
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "region",
    "aws_cognito_identity_pool_id": "identity_pool_id",
    "aws_cognito_region": "region",
    "aws_user_pools_id": "user_pools_id",
    "aws_user_pools_web_client_id": "user_pools_web_client_id",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "aws_user_files_s3_bucket",
    "aws_user_files_s3_bucket_region": "region",
    "aws_appsync_graphqlEndpoint": "aws_appsync_graphqlEndpoint",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "API1",
            "endpoint": "endpoint1",
            "region": "region"
        },
        {
            "name": "API2",
            "endpoint": "endpoint2",
            "region": "region"
        },
        {
            "name": "name",
            "endpoint": "endpoint",
            "region": "region"
        }
    ]
};


export default awsmobile;
```

Some resources that I've checked:
- https://stackoverflow.com/questions/71006168/amplify-api-graphql-unable-to-change-local-api-key-with-the-one-generated-onli
- https://github.com/aws-amplify/amplify-cli/issues/3802

**Comment by AnilMaktala** [comment]
Hey @oyangjo, We're currently actively working on this problem. In the meantime, as a temporary solution, could you revert to the previous 12.8.2 version and inform us if that resolves the issue?

**Comment by palpatim** [comment]
@oyangjo I'm working on this issue for the Amplify Data team. You shouldn't need to edit anything in your `aws-exports.js` file -- that is generated as an output by the CLI if everything is successful. You then consume that file in your frontend app code. Please do let us know if reverting to 12.8.2 fixes the issue for you. We've moved the `@latest` tag back to 12.8.2 so any new installs of the CLI should revert you. You can verify the current version with `amplify version`.

**Comment by palpatim** [comment]
@oyangjo 

There is a typo in your schema: `apikey` should be `apiKey`. Can you correct that and try the `amplify push` again, and see if the `aws-exports.js` file is updated?

**Comment by sundersc** [comment]
A value is required for `aws_appsync_apiKey` key in `aws-export.js` file for the api key authorization to work. Due to some issue, it looks like `aws-exports.js` file was not updated after deployment. Could you force another API deployment using the below command, it should add the missing api key to the `aws-exports.js` file.

```amplify api gql-compile --force && amplify push -y```

**Comment by oyangjo** [comment]
Thanks for all the useful comments. Unfortunately, the suggested fixes did not work. 

Here are some steps that I followed.
1. Run `npm install -g @aws-amplify/cli`, not my `amplify -v` is `12.8.2`
2. `amplify update api` by resetting to only have Cognito User Pools Auth
3. `amplify api gql-compile --force && amplify push -y`
4. `amplify update api` to add API Key and IAM as additional auth
5. Edit local Schema to include `{ allow: public, operations: [read], provider: apiKey }`
6. `amplify api gql-compile --force && amplify push -y`

I am still getting the error `Errors:  [Error: No api-key configured]`

While I was running all the steps above, my `aws-exports.js` did not get updated at all. 

And it is the same case where in cloud, using AppSync to query data is always the expected behavior. However, locally, it seems like api-key does not get recognized.

**Comment by palpatim** [comment]
@oyangjo - Reverting your version of Amplify isn't likely to help. As you noted, you've already downgraded to the previous stable version 12.8.2, which hasn't helped, so we think there's something else going on.

> It is the same case where in the cloud, using AppSync to query data is always the expected behavior. However, locally, it seems like api-key does not get recognized.

Do you mean you're able to query your API in the AppSync console using API Key authentication? If so, that confirms that the API key deployment is working as expected, and it's just the local **aws-exports.js** file that isn't being updated.

Can you confirm that you're app is using the correct **aws-exports.js** file? The Amplify CLI writes the file to your app's **/src/** directory: **/src/aws-exports.js**. If you moved the file at some point, then the Amplify CLI may be writing the file at the old location but the file your app is using may not be the updated one.

We can also confirm that the API key is being registered locally by looking at your **amplify/backend/amplify-meta.json** file to see if there is an `apiKeyConfig` key. For example, in the app I used trying to reproduce your issue, the relevant section looks like this:

```json
"apiKeyConfig": {
  "apiKeyExpirationDays": 30,
  "apiKeyExpirationDate": "2024-01-12T23:02:08.044Z",
  "description": ""
}
```

**Comment by oyangjo** [comment]
Thanks for the detailed comment.

I realized that my project had two `aws-exports.js` files. One in root directory; the other one in `/src`. After deleting the one in the root directory and updating some references, I was able to get the expected behavior.

Thank you for all the help!

**Comment by palpatim** [comment]
There is! https://docs.amplify.aws/javascript/tools/cli/reference/files/

Glad we were able to solve the issue.
