### ISSUE TITLE
You must create an AppSync API in your project before adding a graphql datasource. Please use "amplify api add" to create the API

### ISSUE THREAD

**Issue by fpstidston** [aws-amplify/amplify-category-api#214]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
`amplify api add-graphql-datasource`

**Amplify CLI Version** 
4.41.2

**What AWS Services are you utilizing?**
Attempting to Aurora Serverless to connect to MySQL database

**Provide additional details e.g. code snippets**
The instruction is to run `amplify api add` which I have done
I have also followed a tutorial instructing me to run `amplify add api`
Both seemed to do the same thing so I have two api set-ups and probably need to delete one
Running the instructed command does not alleviate the error which prevents me from selecting the cluster region and connecting my datasource. This could be a bug

**Comment by josefaidt** [comment]
Closing in favor of the RFC for GraphQL on RDS https://github.com/aws-amplify/amplify-category-api/issues/815
