### ISSUE TITLE
Amplify push api throws error 403 with rds

### ISSUE THREAD

**Issue by ginuxone** [aws-amplify/amplify-category-api#2145]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.16.0

### Amplify CLI Version

12.10.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes

### Describe the bug

Whenever i try to run `amplify push api` command it returns an error `Unable to retrieve layer mapping from https://amplify-rds-layer-resources.s3.amazonaws.com/sql-layer-versions/eu-south-1 with status code 403.` But i'm not using rds at all

### Expected behavior

i was expecting to push my schema update to the cloud

### Reproduction steps

amplify push api

### Log output

<details>

```
# Put your logs below this line


```
 Unable to retrieve layer mapping from https://amplify-rds-layer-resources.s3.amazonaws.com/sql-layer-versions/eu-south-1 with status code 403.

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Update:
I was able to reproduce the issue using the following steps 

1. `amplify init` -> select region as `eu-south-1`
2. `amplify add api`
it should fail with the following 
![image](https://github.com/aws-amplify/amplify-category-api/assets/87995712/f58a29ab-40c6-4f3a-b32c-34f4380c6034)

The error did not occur when running push with app in region such as `us-east-1`

**Comment by ykethan** [comment]
Hey @ginuxone, the Amplify team has rolled back Amplify CLI v12.10.0 to v12.8.2 which should be the latest now. Could you retry running `amplify push ` with v12.8.2?

**Comment by ginuxone** [comment]
hey @ykethan I'll give it a try tomorrow at work! and let you know

**Comment by ginuxone** [comment]
@ykethan Yes! It's working now! 
Thanks for the support!
I'll close the issue
