### ISSUE TITLE
Nested customType are not supported

### ISSUE THREAD

**Issue by ubiqart** [aws-amplify/amplify-category-api#2147]
### Environment information

```plain text
System:
    OS: macOS 13.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 229.59 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: Not Found
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: Not Found
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: ^0.6.0 => 0.6.0 
    @aws-amplify/backend-cli: ^0.9.1 => 0.9.1 
    aws-amplify: ^6.0.5 => 6.0.5 
    aws-cdk: Not Found
    aws-cdk-lib: ^2.110.1 => 2.110.1 
    typescript: ^5.3.2 => 5.3.2
```

### Description

Unable to nest custom type.

const schema = a.schema({
  Prompt: a.customType({
    text: a.string().required(),
    weight: a.integer().required()
  }),
  Configuration: a.customType({
    prompts: a.ref('Prompt').required(),
...

prompts type is not recognized.

error TS2322: Type 'RefType<SetTypeSubArg<RefTypeArgFactory<"Prompt">, "required", true>, "required", undefined>' is not assignable to type 'ModelField<ModelFieldTypeParamOuter, CustomTypeAllowedModifiers, any>'.
  Property 'default' is missing in type 'Omit<{ required(): RefType<SetTypeSubArg<SetTypeSubArg<RefTypeArgFactory<"Prompt">, "required", true>, "required", true>, "required", undefined>; authorization<AuthRuleType extends Authorization<...>>(rules: AuthRuleType[]): RefType<...>; }, "required"> & { ...; } & { ...; }' but required in type 'Omit<{ required(): ModelField<string | number | boolean | object | any[] | Date | ModelFieldTypeParamInner[], CustomTypeAllowedModifiers, undefined>; array(): ModelField<...>; default(value: ModelFieldTypeParamOuter): ModelField<...>; authorization<AuthRuleType extends Authorization<...>>(rules: AuthRuleType[]): Mod...'.

**Comment by AnilMaktala** [comment]
Hey @ubiqart, Thank you for highlighting this. We've successfully replicated the issue, thus marking it as a bug for the team to further assess.

<img width="1219" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/76c15a30-e4ab-47b4-8810-548915aa8469">

**Comment by gamegeniusio** [comment]
I'm having this issue as well. Another scenario to check is that this doesn't work even if the nested type is a model instead of a customType. See my example below.

```
const schema = a.schema({
  Player: a.model({
    id: a.string()
  }),
  Team: a.customType({
    id: a.string(),
    name: a.string(),
    alias: a.string(),
    players: a.ref('Player')
  }),
  Games: a
    .model({
      id: a.string(),
      year: a.float(),
      game_type: a.string(),
      week_num: a.float(),
      status: a.string(),
      scheduled: a.string(),
      home: a.ref('Team'),
      away: a.ref('Team'),
    })
    .authorization([a.allow.owner()]),
});
```

**Comment by chrisbonifacio** [comment]
It seems nested custom types are supported in Gen 1.

I was able to compile and deploy the schema in Gen 1

```graphql
type Prompt {
  text: String!
  weight: Int!
}

type Configuration {
  prompt: Prompt!
}
```

**Comment by iartemiev** [comment]
This has now been fixed. 
Please upgrade to the following amplify dependencies to start using this feature:
```json
"dependencies": {
    "aws-amplify": "^6.0.19",
    ...
},
"devDependencies": {
    "@aws-amplify/backend": "^0.13.0-beta.4",
    "@aws-amplify/backend-cli": "^0.12.0-beta.4",
    ...
}
```

**Comment by gamegeniusio** [comment]
This is great thanks, I wound up using Gen1 but I would love to switch back to Gen2 soon. Thanks for fixing this. @iartemiev
