### ISSUE TITLE
 Export with name gk6zgmp6wngkfalelzmkus2y7i:GetAtt:ClientGroupsDataSource:Name is already exported by stack

### ISSUE THREAD

**Issue by vanhungbkcbg1** [aws-amplify/amplify-category-api#2150]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.21.3

### Amplify CLI Version

8.4.0

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I am using cli only, I don't change anything manually

### Describe the bug

I just change schema.grapql file and run amplify push, it show ma an error  **Export with name gk6zgmp6wngkfalelzmkus2y7i:GetAtt:ClientGroupsDataSource:Name is already exported by stack**

### Expected behavior

it shouldn't be an error, I should be able push success

### Reproduction steps

I have tried to reproduce this error by creating sample application with same configuration however the issue is not able to reproduce on that application 

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

 whenever I do any kind of changes on my schema and doing the push I got this error on different tables, I also have found this existing issue 2242
To resolve this error I tried below steps
- amplify checkout 
- amplify api gql-compile
- made some changes in schema.graphql file
- amplify api gql-compile
- amplify push -y

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by sundersc** [comment]
@vanhungbkcbg1 - Could you update the node to 18.x and the CLI version to the latest (12.10.0) and give a try? Let us know if you run into any issue.

**Comment by vanhungbkcbg1** [comment]
Hi, currently my application is using amplify version 8.4.0 to deploy, I am working in large project, it having about 200 resources so is there any problem if I change to latest version ?

**Comment by sundersc** [comment]
Are you using Transformer version 1? If so, we recommend to migrate to v2. Test the migration in a safe test environment before promoting to production. Migration instructions can be found here.
https://docs.amplify.aws/react/tools/cli/migration/transformer-migration/#pageMain

CLI v12.10.0 supports Transformer V1 as well. So you can continue to use Transformer V1 if you are not ready for migration at this time.

Looking at the error message, it looks like there is a conflict in CFN export name. Are you using multiple amplify environments? You can also try creating a new amplify environment using `amplify env add` and try `amplify push -y` to determine if the issue is isolated to an environment.

**Comment by vanhungbkcbg1** [comment]
Hi Sudersc
I have tried to create new environment in difference account but I can reproduce this error, I also have provided our source code to aws supporter for them can have more dig, but they said they did reproduce this error as well

**Comment by vanhungbkcbg1** [comment]
Hi team.
after I upgrated amplify to lates version( 12.1.0), I still met this error, the issue is impacting my production deployment pipeline
please arrange your time to have call with me asap, I need to resolve the issue asap
I am availabe from 9am - 8pm in UTC+7

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
