### ISSUE TITLE
cloudformation: UPDATE_ROLLBACK_FAILED

### ISSUE THREAD

**Issue by vuphan888** [aws-amplify/amplify-category-api#2154]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

10.2.3

### What operating system are you using?

window

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

When I got the error, I didn't take any manual action

### Describe the bug

When performing amplify push, I receive error: UPDATE_ROLLBACK_FAILED. I checked cloudformation and saw this reason: "Resource handler returned message: "No resolver found. (Service: AppSync, Status Code: 404, Request ID: a2f31bc4-bd9c-432c-bf66-31b8cdbf9288)" (RequestToken: 2ec825eb-c582-d07c-cfc1-3ec09d4c7c4e, HandlerErrorCode: NotFound)". I don't know where to check the resolver to see what's missing. If anyone knows the reason, please help me. Your enthusiasm is my happiness.

### Expected behavior

I hope that amplify push can be performed normally

### Reproduction steps

- amplify add function
- code log
- amplify push

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [x] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi @vuphan888, Could you please attempt an 'amplify push' after reverting the schema changes to the previous successful version and inform me if this resolves the issue?

**Comment by vuphan888** [comment]
> Hi @vuphan888, Could you please attempt an 'amplify push' after reverting the schema changes to the previous successful version and inform me if this resolves the issue?
h @AnilMaktala , i try revert to previous successful and amplify push but i still get error 
![Screenshot from 2023-12-22 09-54-58](https://github.com/aws-amplify/amplify-category-api/assets/92079313/9672a97f-9493-41dc-9cb3-94ce059aab27)
I understand that only when the status is rollback_complete in the cloudformation can I perform an amplify push, is that correct?

**Comment by AnilMaktala** [comment]
Are you encountering the `update_rollback_failed` error still? Can you confirm, please?

**Comment by vuphan888** [comment]
@AnilMaktala yes. i still get error update_rollback_failed. Because it interrupted the development process for too long. I deleted the app and created a new one. Thank you so much

**Comment by AnilMaktala** [comment]
Hey @vuphan888, Thank you for the feedback. Since this issue appears to be isolated to your specific environment, we will go ahead and close it for now. However, if you continue experiencing the same problem, please don't hesitate to leave a comment which will allow us to reopen the ticket. We are always happy to provide additional support.
