### ISSUE TITLE
How to filter nested objects in Amplify GraphQL

### ISSUE THREAD

**Issue by jojemapa** [aws-amplify/amplify-category-api#2159]
### Amplify CLI Version

12.10.0

### Question

I'm using `Amplify GraphQL`. ("aws-amplify": "^6.0.9")

In my `schema.graphql` I have two models:

    type Customer @model {
      id: ID!
      name: String!
      email: String!
      image_url: String!
      invoices: [Invoice] @hasMany
    }
    
    type Invoice @model {
      id: ID!
      customer: Customer! @belongsTo
      amount: Int!
      status: String!
      date: String!
    }

That generate me two queries.

The **first query** is ok for me, i can filter the `Customer model` by **email**, and `Invoice model` by **status**.

    listCustomers(filter: { email: { ne: "lee@robinson.com" } }) {
        items {
            name
            email
            image_url
            invoices(filter: { status: { eq: "paid" } }) {
                items {
                    amount
                    status
                    date
                }
            }
        }
    }

But the **second query** don't allow me to **filter**

    listInvoices(filter: { status: { eq: "paid" } }) {
        items {
            amount
            status
            date
            customer {
                name
                email
                image_url
            }
    
        }
    }

I want to add one **filter in the customer**, i tried this code:

    listInvoices(filter: { status: { eq: "paid" } }) {
        items {
            amount
            status
            date
            customer(filter: { email: { eq: "johndoe@gmail.com" } }) {
                name
                email
                image_url
            }
    
        }
    }

But i get the following error:

    Validation error of type UnknownArgument: Unknown field argument filter @ 'listInvoices/items/customer'

Make a filter in customer using the **listInvoices query** is **possible** ?

**Comment by AnilMaktala** [comment]
Hey @jojemapa, Thank you for bringing this up. Please take a look at [this](https://docs.amplify.aws/javascript/build-a-backend/graphqlapi/data-modeling/#relationships-to-a-model-with-a-composite-primary-key) section of the documentation and inform us if it addresses your concern.

**Comment by sundersc** [comment]
@jojemapa - You are using 1:N relationship (A customer has many invoices and an Invoice belongs to a customer). So in this case, the field 'invoices' on model 'Customer' is an array, that's why you are able to filter on this field. However the field `customer` on model `Invoice` is a single value, so there is no filter on this field.

If you are looking to filter the invoices based on customer email, then I recommend you add a field `customerEmail` to the `Invoice` model and add a GSI on that field. It should generate a query to filter by customer email id.

**Comment by jojemapa** [comment]
Hey there, thanks for your answers @AnilMaktala @sundersc.

I've update my schema and it works using the example of the link .

`schema.graphql`
 
 ```
type Customer @model @searchable {
  customerId: ID! @primaryKey(sortKeyFields: ["email"])
  name: String!
  email: String!
  image_url: String!
  invoices: [Invoice] @hasMany(indexName: "byCustomer", fields: ["customerId", "email"])
}

type Invoice @model @searchable {
  invoiceId: ID! @primaryKey(sortKeyFields: ["status"])
  customer: Customer @belongsTo(fields: ["customerId", "customerEmail"])
  customerId: ID! @index(name: "byCustomer", sortKeyFields: ["customerEmail"])
  customerEmail: String!
  amount: Int!
  status: String!
  date: String!
}
```

And this is my `listInvoices` query now:

```
listInvoices(
    filter: { status: { eq: "paid" }, customerEmail: { eq: "steph@dietz.com" } }
) {
    items {
        amount
        status
        date
        customer {
            name
            email
            image_url
        }
    }
}
```

I think is ok, its work, but look the `createInvoce` **mutation**

```
createInvoice(
    input: {
        invoiceId: "uuid by hand xd"
        customerId: "mmmmm"
        customerEmail: "mmmmm"
        amount: 100
        status: "paid"
        date: "today xD"
    }
) {
    status
    date
    createdAt
    updatedAt
}
```

Now I have to enter additional data such as the `customerEmail` and `ID` manually in code (This doesn't matter much)..

_That's ok ? 
Should it be like that?_ 
**Or is there a better way to use just the `customerId` to create an `invoice` and assign the customer email automatically or something?**

My question would now be **resolved**, but I have that doubt, **thank you**.
