### ISSUE TITLE
🛑 Your GraphQL Schema is using "@key" directive from an older version of the GraphQL Transformer. Visit https://docs.amplify.aws/cli/migration/transformer-migration/ to learn how to migrate your GraphQL schema.

### ISSUE THREAD

**Issue by 20uon0073** [aws-amplify/amplify-category-api#2161]
### Amplify CLI Version

12.10.0

### Question

🛑 Your GraphQL Schema is using "@key" directive from an older version of the GraphQL Transformer. Visit https://docs.amplify.aws/cli/migration/transformer-migration/ to learn how to migrate your GraphQL schema.

i facing this error  when i updated schema 
My schema is attached below 

type User
  @model
  @auth(rules: [{ allow: owner, operations: [create, read, update, delete] }])
{
  id: ID! @primaryKey
  username: String!
  email: String!
  orders: [Order] @hasMany(indexName: "byUser")
  car: Car @hasOne
}

type Car
  @model
  @auth(rules: [{ allow: owner, operations: [create, read, update, delete] }])
  @key(name: "byUser", fields: ["userId"])
{
  id: ID! @primaryKey
  type: String!
  latitude: Float
  longitude: Float
  heading: Float
  isActive: Boolean
  orders: [Order] @hasMany(indexName: "byCar")
  userId: ID!
  user: User @belongsTo(fields: ["userId"])
}

type Order
  @model
  @key(name: "byUser", fields: ["userId"])
  @key(name: "byCar", fields: ["carId", "createdAt"])
  @auth(rules: [{ allow: owner, operations: [create, read, update, delete] }])
{
  id: ID! @primaryKey
  createdAt: String!
  
  type: String!
  status: String

  originLatitude: Float!
  originLongitude: Float!

  destLatitude: Float!
  destLongitude: Float!

  userId: ID!
  user: User @belongsTo(fields: ["userId"])

  carId: ID!
  car: Car @belongsTo(fields: ["carId"])
}

**Comment by AnilMaktala** [comment]
Hey @20uon0073 👋, Thanks for raising this issue.we are working on reproducing the issue. Could you please run below command and send us the project identifier 
`amplify diagnose --send-report`.

 please refer [here](https://docs.amplify.aws/cli/reference/diagnose/)

**Comment by 20uon0073** [comment]
using this command it generate folowing  Zip Files 
[report-1704181475409.zip](https://github.com/aws-amplify/amplify-category-api/files/13807970/report-1704181475409.zip)

**Comment by 20uon0073** [comment]
and this is My schema  @AnilMaktala 
and i send You Report file above 


`type User @model {
  id: ID!
  username: String!
  email: String!

  orders: [Order] @connection(keyName: "byUser", fields: ["id"])
  car: Car @connection(fields: ["id"])
}

type Car @model
  @key(name: "byUser", fields: ["userId"]) {
  id: ID!
  type: String!
  latitude: Float,
  longitude: Float,
  heading: Float,
  isActive: Boolean

  orders: [Order] @connection(keyName: "byCar", fields: ["id"])

  userId: ID!
  user: User @connection(fields: ["userId"])
}

type Order @model
  @key(name: "byUser", fields: ["userId"])
  @key(name: "byCar", fields: ["carId", "createdAt"]) {
  id: ID!
  createdAt: String!

  type: String!
  status: String,

  originLatitude: Float!
  oreiginLongitude: Float!

  destLatitude: Float!
  destLongitude: Float!

  userId: ID!
  user: User @connection(fields: ["userId"])

  carId: ID!
  car: Car @connection(fields: ["carId"])
}

type Subscription {
  onOrderUpdated(id: ID!): Order @aws_subscribe(mutations: ["updateOrder"])
  onCarUpdated(id: ID!): Car @aws_subscribe(mutations: ["updateCar"])
}`

**Comment by phani-srikar** [comment]
Hi @20uon0073, can you check your feature flags in `amplify/cli.json` file and ensure the following ones have these defaults if you want to compile a project using `V1` GraphQL transformers:
```
"useexperimentalpipelinedtransformer": false,
"transformerversion": 1,
```
