### ISSUE TITLE
How to resolve 'Too Many Files Open' Error During Amplify Push

### ISSUE THREAD

**Issue by Arpisrinivas** [aws-amplify/amplify-category-api#2162]
### Amplify CLI Version

12.10.0

### Question

I'm facing an issue when I use 'amplify push'—I keep getting an error saying 'too many files open.' It gets stuck while uploading files and eventually shows this error. How can I fix this problem, and what causes it?

![image](https://github.com/aws-amplify/amplify-cli/assets/111382734/f81362fe-b620-4f08-a365-f0d6c2a67a86)

**Comment by AnilMaktala** [comment]
Hey @Arpisrinivas, Could you confirm whether these files open in the IDE or if your local app is still running?

**Comment by Arpisrinivas** [comment]
Hey Anil,
 I didn't run my application when I executed 'amplify push'.

**Comment by AnilMaktala** [comment]
Hey @Arpisrinivas, 
Thank you for confirming. Please proceed with the following steps and inform me if it resolves your issue:

1. Remove the `build` folder in `/amplify/backend/api/WildflowerGraphQLAPI` directory.
2. Execute `amplify build`.
3. Perform `amplify push`.

**Comment by AnilMaktala** [comment]
Hey @Arpisrinivas, Have you had an opportunity to test the suggested steps?
