### ISSUE TITLE
[Gen2] using backend.data.resources does not modify the resources 

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-category-api#2163]
### Amplify CLI Version

Gen2

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

```
System:
    OS: macOS 13.6.3
    CPU: (8) arm64 Apple M1
    Memory: 136.64 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.18.0 - ~/.local/share/nvm/v18.18.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.local/share/nvm/v18.18.0/bin/npm
    pnpm: 7.26.2 - /opt/homebrew/bin/pnpm
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: ^0.7.0 => 0.7.0 
    @aws-amplify/backend-cli: ^0.9.2 => 0.9.2 
    aws-amplify: ^6.0.9 => 6.0.9 
    aws-cdk: Not Found
    aws-cdk-lib: Not Found
    typescript: ^5.3.3 => 5.3.3 
```

using the following in `backend.ts` does not modify the resources/tables nor prints the console logs. tried different resources but the deploy does not trigger a cfn deploy. This worked on previous version of the packages

```
Object.values(backend.data.resources.cfnResources.cfnTables).forEach(
  (table) => {
    console.log("FOO");
    console.log(table);
    table.deletionProtectionEnabled = true;
    console.log("BAR");
    console.log(table);
  }
);
```

while using the following does work

```
backend.auth.resources.cfnResources.cfnUserPool.deletionProtection = "ACTIVE";
console.log(backend.auth.resources.cfnResources.cfnUserPool.deletionProtection);
```
related to https://github.com/aws-amplify/amplify-backend/pull/805

### Expected behavior

allow modifying cfn resources 

### Reproduction steps

1. create a gen 2 app
2. try modifying underlying resources in `backend.ts`

```
Object.values(backend.data.resources.cfnResources.cfnTables).forEach(
  (table) => {
    console.log("FOO");
    console.log(table);
    table.deletionProtectionEnabled = true;
    console.log("BAR");
    console.log(table);
  }
);
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ideen1** [comment]
Following as I also have this issue. (Just with modifying grantWriteData)

**Comment by AnilMaktala** [comment]
Hey @ideen1, Please check the alternative mentioned [here](https://github.com/aws-amplify/amplify-category-api/issues/2137#issuecomment-1858372302) and let us know if it resolves your issue.

**Comment by AnilMaktala** [comment]
it seems to be dupilcate of #2137

**Comment by ideen1** [comment]
@AnilMaktala It doesn't seem to be a duplicate because the answer in the other issue states to use `amplifyDynamoDbTables1` rather than `tables`. However, the attributes are completely different between these two, and therefore you can not get `tableName` from `amplifyDynamoDbTables`.

**Comment by ykethan** [comment]
@ideen1 you should be able to get the table names using `const tableNames = Object.keys(backend.data.resources.amplifyDynamoDbTables);`.

**Comment by ideen1** [comment]
That works to get the Name of the Schema Model, however I am trying to find the name of the deployed resource to use as a lambda env variable, for example.

**Comment by ykethan** [comment]
@ideen1 thanks for pointing that out i did run into this as well. One workaround that i was able to use the following tap into the dynamoDBConfig to get the names at deploy time.

```
const tbs = Object.values(backend.data.resources.cfnResources.cfnDataSources);
const tables = tbs
  .map((tb) => {
    if (tb.dynamoDbConfig && "tableName" in tb.dynamoDbConfig) {
      return tb.dynamoDbConfig.tableName;
    } else {
      console.log("No tableName found for this item");
      return null;
    }
  })
  .filter((tableName) => tableName !== null);
```

**Comment by ideen1** [comment]
Thanks @ykethan, I think this is definitely getting on the right path. The code you recommended gave me this output:
`[ undefined, '${Token[TOKEN.408]}', '${Token[TOKEN.486]}' ]`

The thing that comes up is how would you determine which one corresponds to a specific table you are looking for? For example when assigning this to an Env variable, we may want to get the deployed name of the "Todo" table and not an array of all tables in the project. Will update this if I find an efficient way to filter without string logic.

**Comment by AnilMaktala** [comment]
Hey @ideen1, The current suggested workaround is utilizing the model name in the filter expression to obtain the correct table name. However, we are planning a feature on the roadmap to provide a more accessible method for accessing these table names.

**Comment by ykethan** [comment]
Closing this issue as we will continue tracking it at https://github.com/aws-amplify/amplify-category-api/issues/2137. Please subscribe to the linked issue for further updates.
