### ISSUE TITLE
Unable to access the created Dynamo DB tables from data

### ISSUE THREAD

**Issue by ubiqart** [aws-amplify/amplify-category-api#2167]
### Environment information

```plain text
System:
    OS: macOS 11.7.10
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 618.46 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.18.2 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: Not Found
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: ^0.7.0 => 0.7.0 
    @aws-amplify/backend-cli: ^0.9.2 => 0.9.2 
    aws-amplify: ^6.0.5 => 6.0.5 
    aws-cdk: Not Found
    aws-cdk-lib: ^2.110.1 => 2.110.1 
    typescript: ^5.3.2 => 5.3.2
```

### Description

Hello,

I am not able to retrieve DynamoDB generated tables in data module.

`const backend = defineBackend({
  auth,
  data
});

console.log(backend.data.resources.tables)`

tables is undefined!

Any idea?

**Comment by AnilMaktala** [comment]
Hey @ubiqart, Did you get an opportunity to verify the suggestion mentioned above?

**Comment by malaquf** [comment]
Hi, a wrapper can be obtained from AmplifyDynamoDbTableWrapper, however this interface is very limited and it's not possible, for example, to retrieve basic info as the streaming ARN from it. Another example, is the lack of possibility to grant access like present in ITable. e.g.: table.grantStreamRead(lambda)

**Comment by AnilMaktala** [comment]
Hey, we are closing this issue as we have updated our docs on how to retrieve these table names. Please refer to this docs section for more details: https://docs.amplify.aws/gen2/build-a-backend/data/override-resources/#customize-amplify-generated-resources-for-data-models
