### ISSUE TITLE
GraphQL Schema Design for Social Application in Permissions for DynamoDB and S3

### ISSUE THREAD

**Issue by oyangjo** [aws-amplify/amplify-category-api#2171]
### Amplify CLI Version

12.8.2

### Question

Happy New Year! 

I am currently designing a social app that allows users to have multiple levels of access rights for their posts.

Currently, I am modeling the schema so that users can only access their own posts, see code: 
```
type User 
  @model 
  @auth( rules: [{ allow: owner }] ) {
  id: ID!
  username: String!
  email: String!
  posts: [Posts] @manyToMany(relationName: "UserPostMap")
}

type Post 
  @model
  @auth(rules: [{ allow: owner }]) {
  id: ID!
  image_url: String!
  name: String
  accessList: [String]
  users: [User] @manyToMany(relationName: "UserPostMap")
}
```

Now, I wish to evolve the above structure so that users can specify certain users accessing which post. I will introduce a field called `accessList` within Post. The goal of `accessList` is allowing certain users to access this post. For example, if I only have @emma on the `accessList`, only @emma and I can access this post.

However, I quickly ran into a couple of issues: 
1. When I am in my account, I won't be able to check if @emma's posts are available to me, because `accessList` is within Post that is under `owner` permission which only @emma could access
2. Each Post will have an image that is associated in S3 storage. The current S3 image is stored in `application_name/private/us-east-2:user_id`, which, again, I won't have access to @emma's images. 

I wonder if implementing `accessList` is the best way to go about this problem? Or is there a better way to approach this?

**Comment by AnilMaktala** [comment]
Hey @oyangjo, Thank you for bringing this up. Please review the user group-based data access described [here](https://docs.amplify.aws/javascript/build-a-backend/graphqlapi/customize-authorization-rules/#user-group-based-data-access) and confirm if it aligns with your specific use case.

**Comment by oyangjo** [comment]
@AnilMaktala
Thanks for the suggestion. I've seen this. And, I'm pretty sure group-based data access is not suitable, because there is a limit to the number of cognito groups. That means there will be a limit to my number of posts.

**Comment by oyangjo** [comment]
Thanks @dpilch! That's a really good suggestion. I do have another follow-up question.

Do models with `ownerField` auth role inherit the permissions? For example, if we have a `Folder` with `ownerField` auth role, and `Folder` has `manyToMany` relationship with `Post`, see below.

```
type Folder 
  @model
  @auth(rules: [{ allow: owner, ownerField: "accessList", operations: [read] }]) {
  id: ID!
  name: String
  accessList: [String]
  post: [Post] @manyToMany(relationName: "folderPostMap")
}

type Post 
  @model
  @auth(rules: [{ allow:? }]) {
  id: ID!
  image_url: String!
  name: String
  folder: [Folder] @manyToMany(relationName: "folderPostMap")
}
```

1. Let's say I have a folder with multiple posts in it. If I change the `accessList` for that folder, does the permission get propagated down to all the posts that are in the folder? 
2. If so, what should the auth role of `Post` be?

**Comment by dpilch** [comment]
The auth role will not propagate down to `Post`. Your best option is probably to replicate `accessList` to the `Post` model and add add `@auth(rules: [{ allow: owner, ownerField: "accessList", operations: [read] }])` to the `Post` model. Then use a custom resolver to update `Post.accessList` when `Folder.accessList` is modified.

See here for some additional discussion: https://github.com/aws-amplify/amplify-category-api/issues/135

**Comment by oyangjo** [comment]
Yes that makes sense.

If I want a specific post to be completely public (able to be accessed by all users), is there a wild card symbol to allow all emails or usernames?

**Comment by dpilch** [comment]
For that use case I would add an additional dynamic auth rule for groups. 

https://docs.amplify.aws/javascript/tools/cli-legacy/auth-directive/#dynamic-group-authorization

Something like:

```
{ allow: groups, groupsField: "groupsCanAccess", operations: [read] }
```

```
groupsCanAccess: ['AllUsers']
```

Then add all of your users to the `AllUsers` group. https://docs.amplify.aws/react/build-a-backend/auth/user-group-management/

**Comment by oyangjo** [comment]
Yes that makes a lot of sense. I think `groupsField` is the solution here. 

For Amplify, is there a way to add all users to `AllUsers` Cognito Group? Also, when new users are added to the application, how can we automatically add them to the Cognito Group? 

I found this solution on StackOverflow: https://stackoverflow.com/questions/43021748/aws-cognito-how-to-assign-user-to-a-user-group-when-user-signs-up

**Comment by oyangjo** [comment]
Another issue that I realized is other users will not be able to access `folderPostMap` in dynamoDB

For example, If John has access to both Jill's `FolderA` and `PostA`, when John queries `FolderA` from dynamoDB, the relationship of `PostA` will not show up. 

How do I find the relationship of all the posts associated with `FolderA` based on John's account?

**Comment by dpilch** [comment]
Sorry for the slow response @oyangjo. Were you able to figure out this issue?
