### ISSUE TITLE
Unable to access the created ITables after `defineData`

### ISSUE THREAD

**Issue by m-arrieta-r** [aws-amplify/amplify-category-api#2184]
### Description

When trying to access the tables after constructing them, no tables are defined:
```typescript
import { defineBackend } from '@aws-amplify/backend';
import { auth } from './auth/resource.js';
import { data } from './data/resource.js';

const backend = defineBackend({
  auth,
  data,
});
console.log('tables', backend.data.resources.tables);
// tables {}
```
The error only occurred when using Amplify. When I tried with CDK directly, everything was okay [Reference](https://gist.github.com/marnutux/f22b06dc8398babfa1f04c61daf36b0b#file-amplify-stack-example-ts-L30)

Related threads:
- https://github.com/aws-amplify/amplify-category-api/issues/2137
- https://discord.com/channels/705853757799399426/1191670590319362078
- https://discord.com/channels/705853757799399426/1190515212323926076/1190515212323926076
### Environment information

```plain text
Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.18.2/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.9.2 - ~/Library/pnpm/pnpm
  npmPackages:
    @aws-amplify/backend: ^0.7.0 => 0.7.0 
    @aws-amplify/backend-cli: ^0.9.2 => 0.9.2 
    aws-amplify: ^6.0.10 => 6.0.9 
    aws-cdk: 2.110.1 => 2.110.1 
    aws-cdk-lib: 2.110.1 => 2.110.1 
    typescript: ^5.3.3 => 5.3.3
```

**Comment by AnilMaktala** [comment]
Hey @marnutux, We are looking into this and let you know if there is any workaround.

**Comment by dpilch** [comment]
The table name is here: `backend.data.resources.amplifyDynamoDbTables.<model>.resource._cfnProperties.tableName`. However `resource` is private currently. I see no issue changing this to public or adding an accessor method though.

**Comment by ykethan** [comment]
Closing this issue as we will continue tracking it at https://github.com/aws-amplify/amplify-category-api/issues/2137. Please subscribe to the linked issue for further updates.
