### ISSUE TITLE
Give a Lambda function access to RDS

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-category-api#219]
**Is your feature request related to a problem? Please describe.**
In Amplify there is an option [to connect your RDS database](https://docs.amplify.aws/cli/graphql-transformer/relational) to the GraphQL API. After doing that parameters for the RDS database are added to the Amplify project to the API category, but there is no way to let functions have access to the RDS database.

**Describe the solution you'd like**
An ability to give Lambda functions access to RDS using `amplify function update`. The cloudformation template for the function should receive the parameters for RDS such as the secret ARN, the cluster ARN, and the database name (which exist as parameters for the API category).

**How can this be done**
The API cloudformation template receives these properties as parameters - 
```
"rdsRegion": {
    "Type": "String",
    "Description": "The region that the RDS Cluster is located in."
},
"rdsClusterIdentifier": {
    "Type": "String",
    "Description": "The ARN identifier denoting the RDS cluster."
},
"rdsSecretStoreArn": {
    "Type": "String",
    "Description": "The ARN for the Secret containing the access for the RDS cluster."
},
"rdsDatabaseName": {
    "Type": "String",
    "Description": "The name of the database within the RDS cluster to use."
}
``` 
You could add these to the `Outputs` object, and this way we could transfer these to lambda functions, the same way you pass `GraphQLAPIIdOutput` to create the table names in the cloudformation template of lambda functions,
this can be done manually, but you have to edit the compiled cloudformation template for the API, meaning that when you update your API you have to run `amplify api gql-compile` and then edit the cloudformation with the outputs so that it will output the RDS keys, and then push without compiling with `amplify push -no-gql-override`

**Describe alternatives you've considered**
This can be done manually but it's frustrating doing that to every Lambda function, and many people do not know how to do that.

**Additional context**
This shouldn't be hard to implement, as all of these parameters exist, and there is already functionality for adding permissions to a function, so this should just extend that functionality

**Comment by renebrandel** [comment]
In terms providing access to the database via IAM policies, that should be addressed as part of this: https://github.com/aws-amplify/amplify-cli/issues/7792

We could consider the additional workflows based on the new RFC for SQL support: https://github.com/aws-amplify/amplify-category-api/issues/815

**Comment by chrisbonifacio** [comment]
Closing this as this is now possible using the `AmplifyGraphqlApi` CDK construct to connect to existing SQL/PostgreSQL databases.

For full details on the workflow please refer to our documentation:
https://docs.amplify.aws/javascript/build-a-backend/graphqlapi/connect-api-to-existing-database/#pageMain

Given that the new support for connecting to RDS databases is CDK-based, this should be possible by simply creating a function using the AWS CDK, assign it to the RDS instance's security group to allow communication between them.

Here's an example of how might look:

```ts
// Assuming default vpc and security groups

 const vpc = ec2.Vpc.fromLookup(this, "defaultVpc", { isDefault: true });

    const defaultSG = ec2.SecurityGroup.fromLookupByName(
      this,
      "defaultSecurityGroup",
      "default",
      vpc
    );

    const amplifySqlApi = new AmplifyGraphqlApi(this, "SqlBoundApi", {
      apiName: "MySqlBoundApi",
      definition: AmplifyGraphqlDefinition.fromFilesAndStrategy(
        [path.join(__dirname, "schema.sql.graphql")],
        {
          name: "MySQLSchemaDefinition",
          dbType: "MYSQL",
          vpcConfiguration: {
            vpcId: vpc.vpcId,
            securityGroupIds: [defaultSG.securityGroupId],
            subnetAvailabilityZoneConfig: [
              // list of { subnetId, availabilityZone }
            ],
          },
          dbConnectionConfig: {
            hostnameSsmPath: "/amplify-rds-app/host",
            portSsmPath: "/amplify-rds-app/port",
            usernameSsmPath: "/amplify-rds-app/username",
            passwordSsmPath: "/amplify-rds-app/password",
            databaseNameSsmPath: "/amplify-rds-app/database",
          },
        }
      ),
      authorizationModes: {
        defaultAuthorizationMode: "API_KEY",
        apiKeyConfig: {
          expires: cdk.Duration.days(30),
        },
      },
    });

    // If not already configured, allow incoming traffic from other resources in the same security group as the RDS instance

    defaultSG.addIngressRule(defaultSG, ec2.Port.tcp(3306));

    const myFunction = new lambda.Function(this, "myFunction", {
      functionName: "myFunction",
      code: lambda.Code.fromAsset(path.join(__dirname, "handlers/myFunction")),
      handler: "index.handler",
      runtime: lambda.Runtime.NODEJS_18_X,
      // Create Lambda within in the same VPC as the RDS instance and Security Group.
      vpc,
      securityGroups: [defaultSG],
      // For db credentials, add additional permissions to allow the Lambda to retrieve secrets from SSM Parameter Store
    });
```
