### ISSUE TITLE
[Gen 2]support for array of custom fields

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-category-api#2193]
### Describe the feature you'd like to request

support for array on a custom field type in Gen 2

for example:
```
a.schema({
 Location: a.customType({
 lat: a.float(),
 long: a.float()
 }),

Post: a.model({ 
 location: a.ref('Location').array(),
 content: a.string(),
}
```

### Describe the solution you'd like

`.array()` on say `a.ref('Location')`

### Describe alternatives you've considered

none

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by alexwhb** [comment]
I would love to see this as well.

**Comment by iartemiev** [comment]
This has now been implemented. 
Please upgrade to the following amplify dependencies to take advantage of this feature:
```json
"dependencies": {
    "aws-amplify": "^6.0.19",
    ...
},
"devDependencies": {
    "@aws-amplify/backend": "^0.13.0-beta.4",
    "@aws-amplify/backend-cli": "^0.12.0-beta.4",
    ...
}
```

**Comment by alexwhb** [comment]
@iartemiev Soooo awesome!!! thank you guys for your hard work. I'm loving Amplify Gen 2.

**Comment by TextuarySolid45** [comment]
I found a work around where you can do something like this using the .ref function
```
a.schema({
  Location: a.customType({
      lat: a.float(),
      long: a.float(),
  }),

  Post: a.model({
    locations: a.ref('Location').array(),
    content: a.string(),
  }),

});
```

**Comment by anni1236012** [comment]
+1 This is an important feature to have

**Comment by mgreiner79** [comment]
I am unclear. is it possible to model arrays of custom types?
for example, if i want:
{
  "title": "my quiz",
  "questions": [
      {
         "question": "what is the capital of France?",
         "answer": "Paris"
      },
     {
         "question": "what is the capital of Germany?",
         "answer": "Berlin"
      },
  ]
}

Can i do this?
`const schema = a.schema({
  Quiz: a
    .model({
      title: a.string(),
      questions: a.customType({
          question: a.string(),
          answers: a.string(),
        }).array()
    })
    .authorization((allow) => [allow.owner()]),
})
`

or do i need to use relationships like this?

`const schema = a.schema({
  Quiz: a.model(
      {
        quizId: a.integer(),
        title: a.string(),
        questions: a.hasMany('Question', 'questionId')
      }
    ).authorization((allow) => [allow.owner()]),
   Question: a.model(
       {
         question: a.string(),
         questionId: a.integer()
         quiz: a.belongsTo('Quiz', 'quizId')
       }
    )

})
`

**Comment by rajeshrah22** [comment]
> I am unclear. is it possible to model arrays of custom types?
> for example, if i want a model like this:
> ```
> {
>   "title": "my quiz",
>   "questions": [
>       {
>          "question": "what is the capital of France?",
>          "answer": "Paris"
>       },
>      {
>          "question": "what is the capital of Germany?",
>          "answer": "Berlin"
>       },
>   ]
> }
> ```
> 
> Can i do this?
> 
> ```
> const schema = a.schema({
>   Quiz: a
>     .model({
>       title: a.string(),
>       questions: a.customType({
>           question: a.string(),
>           answers: a.string(),
>         }).array()
>     })
>     .authorization((allow) => [allow.owner()]),
> })
> ```
> 
> or do i need to use relationships like this?
> 
> ```
> const schema = a.schema({
>   Quiz: a.model(
>       {
>         quizId: a.integer(),
>         title: a.string(),
>         questions: a.hasMany('Question', 'questionId')
>       }
>     ).authorization((allow) => [allow.owner()]),
>    Question: a.model(
>        {
>          question: a.string(),
>          questionId: a.integer()
>          quiz: a.belongsTo('Quiz', 'quizId')
>        }
>     )
> 
> })
> ```

It's been a while. Can you try it. Not sure if they have included this support.

**Comment by wm-gabriellopez** [comment]
I believe you can do this but you have to use a.ref('')

```
const schema = a.schema({
  Quiz: a.model(
      {
        quizId: a.integer(),
        title: a.string(),
        questions: a.ref('Question').array()
      }
    ).authorization((allow) => [allow.owner()]),
   Question: a.customType(
       {
         question: a.string(),
         questionId: a.integer()
       }
    )

})
```
