### ISSUE TITLE
Using Auth on RDS types

### ISSUE THREAD

**Issue by mjza** [aws-amplify/amplify-category-api#220]
Assume I have followed the following tutorial:

https://docs.amplify.aws/cli/graphql-transformer/relational

This will lead to have some types like 

```
type Customers {
  id: String!
  name: String!
  phone: String!
  email: String!
}
```

in my `schema.graphql` file. The question is how can I use `@auth` on this type?
If I use it, it will say, it needs `@model` and if I use `@model` then `amplify push` will try to generate a table in DynamoDB and not any more count it as a RDS table!

**Comment by akhilv77** [comment]
Hi @mjza 

Do you have any solution for restricting user access to RDS databases, please let me know, I am struck with the same issue.
I have tried auth rules to the type, but it has given me the same error as yours, I am looking for a workaround.

**Comment by mjza** [comment]
@akhilv77 I don't have any solution for it. I gave up that project.

**Comment by akhilv77** [comment]
@mjza Thank you for responding back.

**Comment by renebrandel** [comment]
This is now supported: https://docs.amplify.aws/react/build-a-backend/graphqlapi/connect-api-to-existing-database/#apply-authorization-rules
