### ISSUE TITLE
Enum field type is broken

### ISSUE THREAD

**Issue by iartemiev** [aws-amplify/amplify-category-api#2207]
### Amplify CLI Version

n/a

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Describe the bug

```ts
const schema = a.schema({
  Profile: a
    .model({
      favoriteFruit: a.enum(["Apple", "Banana"]),
    })
    .authorization([
      a.allow.owner(),
    ]),
});
```

```ts
const createdProfile = await client.models.Profile.create(contextSpec, {
  // error: Type 'string' is not assignable to type 'null | undefined'.
  favoriteFruit: 'Apple',
});
```

### Expected behavior

`favoriteFruit` field type should be:  `"Apple" | "Banana" | null | undefined`

### Reproduction steps

In the description

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by iartemiev** [comment]
Could not repro in a fresh gen2 app (`npm create amplify`). Will reach out to the requester tomorrow to troubleshoot.
```json
"dependencies": {
  "@aws-amplify/adapter-nextjs": "^1.0.13",
  "aws-amplify": "^6.0.13"
},
"devDependencies": {
  "@aws-amplify/backend": "^0.10.2",
  "@aws-amplify/backend-cli": "^0.9.7",
  "typescript": "^5.3.3"
}
```
<img width="1534" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/29709626/304b11ef-3101-49fc-99e2-993d74e53eff">

**Comment by johnpc** [comment]
Yes - this is fixed in the latest versions. What fixed it for me was `npm i @aws-amplify/backend-cli@^0.9.7`. Previously was on `@aws-amplify/backend-cli` version `^0.9.2`. I works now! 🎉  Thanks!
