### ISSUE TITLE
Removing API deleted dynamoDB data

### ISSUE THREAD

**Issue by jknapp25** [aws-amplify/amplify-category-api#223]
I am troubleshooting another amplify issue and I deleted my API to try setting it up again and that deleted all my dynamo DB data without warning.

My wife had already created a bunch of new posts on her brand new blog I built her and now I have to let her know that's all gone. Very unhappy customer here.

**Comment by renebrandel** [comment]
We're now displaying additional warnings for destructive changes. Closing this as completed.
