### ISSUE TITLE
GraphQL server-side filtering on list query is broken 

### ISSUE THREAD

**Issue by oyangjo** [aws-amplify/amplify-category-api#2241]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

10.2.0

### Amplify CLI Version

12.8.2

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Haven't made any changes

### Describe the bug

When using the filter function in queries.list, the returning objects have variables that don't satisfy the filter criteria.

In the example below, I am expecting all objects with `black` and `apple`. 

```
const myStuff = await API.graphql({
        query: queries.listmyStuffs,
        variables: {
          limit: 1000,
          filter: {
            and: [
              { color: { eq: "black" } },
              { brand: { eq: "apple" } }
            ]
          },
        },
      });
```

However, I am getting objects that have more than that. The filter function is not working correctly. 

### Expected behavior

With this example:
```
const myStuff = await API.graphql({
        query: queries.listmyStuffs,
        variables: {
          limit: 1000,
          filter: {
            and: [
              { color: { eq: "black" } },
              { brand: { eq: "apple" } }
            ]
          },
        },
      });
```

Only return objects with `color=black` and `brand=apple`

### Reproduction steps

1. Create schema with `myStuff` with variables `color` and `brand` (both strings)
2. Populate lots of different data
3. Call `queries.listMyStuff` with filters `{ color: { eq: "black" } }` and `{ brand: { eq: "apple" } }`

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by sundersc** [comment]
Hey @oyangjo, could you provide additional information to reproduce the error?
- Provide the schema for `myStuff` model.
- Share the definition of `queries.listMyStuff` variable.
- Also share some information on what are the incorrect records showing up on the query result.

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
