### ISSUE TITLE
Support for "extends" or subtypes

### ISSUE THREAD

**Issue by ideen1** [aws-amplify/amplify-category-api#2251]
### Environment information

```plain text
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 187.77 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: Not Found
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: ^0.10.3 => 0.10.3 
    @aws-amplify/backend-cli: ^0.9.5 => 0.9.5 
    aws-amplify: ^6.0.9 => 6.0.9 
    aws-cdk: Not Found
    aws-cdk-lib: ^2.110.1 => 2.110.1 
    typescript: ^5.3.3 => 5.3.3
```

### Description

Amplify Gen 1 and the GraphQL schema file supported having an extends or disjoint subtype tables where multiple tables could share the same base attributes. This would also create a query so that we could query the base type but view results from all subtype tables.

 I have not been able to find ay way to do this in Gen 2, including using TypeScript types. Does this exist or is it on the roadmap? The only alternative I see is to create one large table that has all values from subtypes combined into one. The problem with this approach is that type safety won't be enforced since you can have any combination of the optional subtype fields.

**Comment by AnilMaktala** [comment]
Hey @ideen1 , Thank you for bringing this to our attention. At the moment, we haven't implemented support for this feature in Gen 2. Therefore, I'm categorizing this as a feature request for the team.

**Comment by renebrandel** [comment]
@ideen1  - checking in. Do you mind attaching a schema. Given in Gen 2 everything is a TypeScript, you can simply reassign the common bits and pieces into a variable:

```ts
const commonFields = {
  test: a.string()
}

const schema = a.schema({
  ModelOne: a.model({ ...commonFields, newField: a.string() }),
  ModelTwo: a.model({ ...commonFields, anotherField: a.string() }),
})
```

**Comment by ideen1** [comment]
Yeah that approach would work. Only downside is that can not query the "base type" and have all subtype returned as part of the results. (We would need to run separate queries for each subtype and combine the results)

My schema looks like the following: 

```
  export type IRecord = {
  id: string;
  firstName: string;
  lastName: string;
  reviewedByPhysician: string;
  preparedByTechnician: string;
  processedDataURL?: string | null;
  finalizedReportURL?: string | null;
  status: TestStatus | any;
  createdAt: string;
  updatedAt: string;
};

export type IRecordA = IRecord & {
  reviewNotes: string;
};

export type IRecordB = IRecord & {
  demoList: string[];
};
```

In addition, is there a way to create a model based off of a TypeScript type or enum?  For example, if I already have all types defined in a file and want the backend data to match those types. I tried creating a model by iterating over the type but that did not seem to work.
