### ISSUE TITLE
RDS: The 'NaN' value is being returned as the nextToken when a filter limit is applied to queries generated for the index (pagination)

### ISSUE THREAD

**Issue by AnilMaktala** [aws-amplify/amplify-category-api#2257]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

1.5.6

### What operating system are you using?

Max

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No Manual changes made

### Describe the bug

The 'NaN' value is being returned as the nextToken when a filter limit is applied to queries generated for the index.

### Expected behavior

Should return the correct `nexttoken` value.

### Reproduction steps

1. Connect to RDS MySQL DB with the following schema.
      ```type Person @refersTo(name: "person") @model {
        id: ID! @primaryKey
        alias: String! @index(name: "PersonsByAlias", queryField: "PersonsByAlias")
        name: String!
        email: String
        status: Status
        sixManagerAlias: String
        isManager: Boolean
        isBizOps: Boolean
        Plan: Plan! @hasOne(references: ["id"])
        Manager: Person @hasOne(references: ["id"])
        Organization: Organization @hasOne(references: ["id"])
        personPlanId: ID!
          @index(
            name: "PersonsByPlan"
            queryField: "PersonsByPlan"
            sortKeyFields: ["personOrganizationId"]
          )
        personManagerId: ID
          @index(
            name: "PersonsByManager"
            queryField: "PersonsByManager"
            sortKeyFields: ["personPlanId"]
          )
        personOrganizationId: ID!
          @index(
            name: "PersonsByOrganization"
            queryField: "PersonsByOrganization"
            sortKeyFields: ["personManagerId"]
          )
      }
      ```
3.  Deploy the schema and  goto Appsync conslole and run query PersonsByPlan and add limit filter and verify the nextoken value.
4. Returning "TmFO" ( Base64  vlaue: Nan)

![image](https://github.com/aws-amplify/amplify-category-api/assets/3206171/b6edf5d5-f702-48fd-a989-71eea8dd74da)

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by palpatim** [comment]
We have a fix for this making its way through our deployment pipelines now.

**Comment by AnilMaktala** [comment]
I've tested the recent fixes in the application and can confirm that the reported issues have now been resolved.

**Comment by AnilMaktala** [comment]
reopened the issue as list queries are failing.

**Comment by palpatim** [comment]
We will resolve the `list` query issue, ensure we have test coverage on all paginated operations, and expedite a release for this.
