### ISSUE TITLE
ResolverExecutionLimitReached

### ISSUE THREAD

**Issue by andre-scheffer** [aws-amplify/amplify-category-api#226]
**Describe the bug**
I have been facing the following problem for two days.

**Initial Situation**

I have a model with an @key directive:

``` gql
type Foo
  @model
  @key(name: "ByCreatedAt", fields: ["sortDummy", "createdAt"], queryField:"entriesByCreatedAt")
  @auth(rules: [
    { allow: owner }
  ]) 
{
  id: ID!  
  sortDummy: String!
  bar: String!
  owner: String
  createdAt: AWSTime
  bar2: AWSJSON
  bar3: SomeModel1 @connection(name: "Connection1")
  bar4: SomeModel2 @connection(name: "Connection2")
}
```

``amplify codegen`` created the following method:

```ts
async EntriesByCreatedAt(
    sortDummy?: string,
    createdAt?: ModelStringKeyConditionInput,
    sortDirection?: ModelSortDirection,
    filter?: ModelFooFilterInput,
    limit?: number,
    nextToken?: string
  ): Promise<EntriesByCreatedAtQuery> {
```

In the angular component I load the data as follows:

```ts
await this.apiService.EntriesByCreatedAt(
      "DUMMY",
      undefined,
      ModelSortDirection.DESC,
      this.filter,
      this.limit,
      nextToken
    );
```

So far everything has worked wonderfully. Even with several hundred entries. The use of the nextToken was also not a problem.

**Error**

For two days now I have had the following error:

![image](https://user-images.githubusercontent.com/48789566/101686160-f799e580-3a68-11eb-8c35-dfbaf1eb2fc4.png)

To be found by Google or within GitHub: "ResolverExecutionLimitReached" and "Resolver invocation limit reached"

In addition, the error message delivers a strange number of items with:

![image](https://user-images.githubusercontent.com/48789566/101686417-4f385100-3a69-11eb-9d12-5417acfaec3a.png)

It gets even stranger when I have less than 90 entries. Then the "ResolverExecutionLimitReached" error does not appear. But if I instead set the limit to 100, for example, then only 35 entries will be returned. If I set the limit to 10, only 5 entries will be returned. Occasionally very crooked quantities are delivered. But as soon as there are more than 90 entries in the database, the error "ResolverExecutionLimitReached" described above definitely occurs.

**What did I do to fix the error?**

I rolled back the Amplify versions to 4.37.1 which it definitely worked with. In the meantime I hadn't changed anything in this coding. The bug was still there. So I think something is wrong in the Amplify backend.

**Amplify CLI Version**
4.38.2 --> But as described above, the error also appears under 4.37.1

**To Reproduce**
See above

**Expected behavior**
As before, the entries should be delivered sorted in descending order according to CreatedAt.

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: v14.15.0

**Comment by bob-lee** [comment]
@josefaidt not sure what you mean by `DataStore`, the issue was found on our web frontend which is making a GraphQL query (custom query implemented on nodejs Lambda). I could also reproduce the error by running a query that is used by the custom query) on Amplify console as I mentioned above.

**Comment by rafaelfaria** [comment]
This literally JUST started to happen to me. I only have 262 items in the table. I would love to understand why this actually happen and how to solve it.

**Comment by GitHubPhongNguyen** [comment]
> This literally JUST started to happen to me. I only have 262 items in the table. I would love to understand why this actually happen and how to solve it.

@rafaelfaria do your query have mapping data same ?
`items{
   id
   name
   itemsMapping {
       items {
           id
           ...
       }
   }
}`
if one item in table have 100 items mapping other table, then 1 query maximum 1000 Resolvers executed in a single request. that mean if query have >= 1000 items mapping one single query then we have error.
hope this helful

**Comment by alharris-at** [comment]
Adding to some of the comments elsewhere on here. This error appears to arise when too many individual AppSync resolvers are executed within a single request context, which is likely to happen with nested or deeply nested queries.

e.g.

```graphql
query ListAllBlogPostsWithComments {
  listBlogs {
    items {
      id
      title
      description
      author
      posts {
        items {
          id
          title
          content
          comments {
            items {
              id
              content
              author
            }
            nextToken
          }
        }
        nextToken
      }
    }
    nextToken
  }
}
```

In this case, if my app has 10 blogs, with 10 posts each, with 10 comments, I'm effectively going to be invoking 10^3 + 10^2 + 10^1 + 10^0 (I think there's a nice way to represent that, but forget offhand) resolvers, and bumping into the 1k resolver limit. This is known as the N+1 problem in GraphQL, and there are a few strategies to work around it.

One approach to workaround this proposed by AppSync is to use request batching - https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-lambda-resolvers.html#advanced-use-case-batching, https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-batch.html

However, with an Amplify app and @hasMany or @connection - it is likely more reasonable to perform smaller, bounded queries (or less deeply nested queries) to avoid this issue.

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
