### ISSUE TITLE
🛑 Stack:arn:aws:cloudformation:eu-north-1:284830548330:stack/amplify-ridygo-staging-164349/a1f32970-9456-11ee-954c-0ee577700a

### ISSUE THREAD

**Issue by 20uon0073** [aws-amplify/amplify-category-api#2266]
### Amplify CLI Version

12.10.0

### Question

✅ GraphQL schema compiled successfully.

Edit your schema at E:\FYP\RidyGo\server\amplify\backend\api\ridygo\schema.graphql or place .graphql files in a directory at E:\FYP\RidyGo\server\amplify\backend\api\ridygo\schema
/ Building resource api/ridygo⚠️ WARNING: owners may reassign ownership for the following model(s) and role(s): User: [owner],
 Car: [owner], Order: [owner]. If this is not intentional, you may want to apply field-level authorization rules to these fields. To read more: https://docs.amplify.aws/cli/graphql/authorization-rules/#per-user--owner-based-data-access.
| Building resource api/ridygo✅ GraphQL schema compiled successfully.

Edit your schema at E:\FYP\RidyGo\server\amplify\backend\api\ridygo\schema.graphql or place .graphql files in a directory at E:\FYP\RidyGo\server\amplify\backend\api\ridygo\schema
? Do you want to update code for your updated GraphQL API Yes
? Do you want to generate GraphQL statements (queries, mutations and subscription) based on your schema types?
This will overwrite your current graphql queries, mutations and subscriptions Yes

Deploying resources into staging environment. This will take a few minutes. ⠴
Deploying root stack RidyGo [ ---------------------------------------- ] 0/4
Deploying api ridygo [ ---------------------------------------- ] 0/8
🛑 Stack:arn:aws:cloudformation:eu-north-1:284830548330:stack/amplify-ridygo-staging-164349/a1f32970-9456-11ee-954c-0ee577700aDeploying resources into staging environment. This will take a few minutes. ⠧
Deploying root stack RidyGo [ ---------------------------------------- ] 0/4
Deploying api ridygo [ ---------------------------------------- ] 0/8

Session Identifier: 05b5d94a-388a-4a13-a8ef-ad44e7ed5683

**Comment by AnilMaktala** [comment]
Hey @20uon0073, Could you please clarify what is the issue here?

**Comment by 20uon0073** [comment]
when I updated graph Ql schema 
and write amplify Push then 
no error issues comes and terminate sate the screenshot is here 

`/ Building resource api/ridygo✅ GraphQL schema compiled successfully.

Edit your schema at E:\ridygocm\server\amplify\backend\api\ridygo\schema.graphql or place .graphql files in a directory at E:\ridygocm\server\amplify\backend\api\ridygo\schema

Deploying resources into staging environment. This will take a few minutes. ⠸
Deploying root stack RidyGo [ ---------------------------------------- ] 0/4
Deploying auth ridygo84f06440 [ ---------------------------------------- ] 0/6
Deploying api ridygo [ ---------------------------------------- ] 0/6
Deploying resources into staging environment. This will take a few minutes. ⠴
Deploying root stack RidyGo [ ---------------------------------------- ] 0/4
Deploying auth ridygo84f06440 [ ---------------------------------------- ] 0/6
Deploying api ridygo [ ---------------------------------------- ] 0/6
Deploying function ridygo9aeebaf4 [ ---------------------------------------- ] 0/5

Session Identifier: 58db1425-0023-4a5c-8f22-4c6e81a8f97b`

**Comment by AnilMaktala** [comment]
Hey @20uon0073, Could you please attempt `amplify push` again after adding a space in the schema.graphql file?

**Comment by 20uon0073** [comment]
yes i  again changed schema
But still it shows same 

 `/ Building resource api/ridygo✅ GraphQL schema compiled successfully.

Edit your schema at E:\ridygocm\server\amplify\backend\api\ridygo\schema.graphql or place .graphql files in a directory at E:\ridygocm\server\amplify\backend\api\ridygo\schema

Deploying resources into staging environment. This will take a few minutes. ⠸
Deploying root stack RidyGo [ ---------------------------------------- ] 0/4
Deploying auth ridygo84f06440 [ ---------------------------------------- ] 0/6
Deploying api ridygo [ ---------------------------------------- ] 0/6
Deploying resources into staging environment. This will take a few minutes. ⠴
Deploying root stack RidyGo [ ---------------------------------------- ] 0/4
Deploying auth ridygo84f06440 [ ---------------------------------------- ] 0/6
Deploying api ridygo [ ---------------------------------------- ] 0/6
Deploying function ridygo9aeebaf4 [ ---------------------------------------- ] 0/5

Session Identifier: 58db1425-0023-4a5c-8f22-4c6e81a8f97b

**Comment by AnilMaktala** [comment]
Hi @20uon0073 , we are working on reproducing the issue. Could you please run below command and send us the project identifier. 
 `amplify diagnose --send-report`. please refer [here](https://docs.amplify.aws/cli/reference/diagnose/)

**Comment by 20uon0073** [comment]
[report-1707924425430.zip](https://github.com/aws-amplify/amplify-category-api/files/14281654/report-1707924425430.zip)

Project report attached here

**Comment by 20uon0073** [comment]
[report-1707924425430.zip](https://github.com/aws-amplify/amplify-category-api/files/14281654/report-1707924425430.zip)

Project report

**Comment by AnilMaktala** [comment]
Thank you for providing the report. We will work on reproducing the issue and let you know.

**Comment by dpilch** [comment]
I wasn't able to reproduce this issue. Are you certain there were no other error messages?

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
