### ISSUE TITLE
Lambda PutItemCommand on model which has 2 sortKeyFields is not creating index entry 

### ISSUE THREAD

**Issue by itechevo** [aws-amplify/amplify-category-api#2301]
### Description

I have model:

```
type UserMatch @model @auth(rules: [{allow: owner}, {allow: private, provider: userPools, operations: [read]}]) {
    id: ID!
    userId: ID!
    @index(name: "byUserId", sortKeyFields: ["matchType", "updatedAt"], queryField: "userMatchesByUserId")
    @index(name: "byUserIdAndMatchedUserId", sortKeyFields: ["matchedUserId"], queryField: "userMatchesByUserIdAndMatchedUserId")
    matchedUserId: ID!
    matchType: MatchType
    user: User @hasOne(fields :["userId"])
    matchedUser: User @hasOne(fields: ["matchedUserId"])
    updatedAt: AWSDateTime!
}
```

And a lambda function which writes to this model:

```
async function createMatchEntry(userId, matchedUserId) {

  try {

    var newMatchType = "XXX";

    var id =  uuid.v1();

    var input = {
      "Item": {
        "id": {
          "S": id,
        },
        "userId": {
          "S": userId
        },
        "matchedUserId": {
          "S": matchedUserId
        },
        "matchType": {
          "S": newMatchType
        },
        "createdAt": {
           "S": new Date().toISOString()
        },
        "updatedAt": {
           "S": new Date().toISOString()
        }

      },
      "ReturnConsumedCapacity": "TOTAL",
      "TableName": userMatchTable
    };

    await dynamodbClient.send(new PutItemCommand(input));

  } catch (error) {
     console.error('Error:', error);
     throw error;
  }

  return false;
}
```
The above works and I see entry in DB. But unable to query using GraphQL on the indexes with 2 sortKeyFields. The below query just returns empty items.

```
userMatchesByUserId(userId: "1234", matchTypeUpdatedAt: {beginsWith: {matchType: XXX}}) {
    items {
      matchType
    }
  }
```

But query works on the one sortKeyFields index, so this query works:

```
userMatchesByUserIdAndMatchedUserId(userId: "1234", matchedUserId: {eq: "4321"}) {
    items {
      matchType
    }
  }
``` 

This only happens when inserting via lambda, if I insert using AppSync, indexes are created correctly and query works. Any idea why lambda PutItemCommand in not behaving same as AppSync mutation?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

0.6.12

### Deployment Method

Amplify CLI

**Comment by dpilch** [comment]
Hi @itechevo, what is the use case to put items directly in the DynamoDB instead of using the AppSync API?

**Comment by dpilch** [comment]
For this use case I would recommend using a custom resolver to preform this logic. https://docs.amplify.aws/javascript/build-a-backend/graphqlapi/custom-business-logic/

**Comment by itechevo** [comment]
@dpilch Thanks, I never considered using AppSync API in lambda functions, it makes sense for this use case. I have tried and it's working.
