### ISSUE TITLE
Support @hasMany configures a default secondary index in gen2

### ISSUE THREAD

**Issue by sevenkkk** [aws-amplify/amplify-category-api#2312]
### Describe the feature you'd like to request

This is the implementation of v6：
```
type Post @model {
  id: ID!
  title: String!
  comments: [Comment] @hasMany(indexName: "byPost", fields: ["id"])
}

type Comment @model {
  id: ID!
  postID: ID! @index(name: "byPost", sortKeyFields: ["content"])
  content: String!
}
```
Use a.hasMany() in gen2：
 ```
 Post: a
    .model({
      title: a.string().required(),
      comments: a.hasMany('Comment'),
    }),
  Comment: a
    .model({
      content: a.string(),
      postID: a.id(),
    })
    .secondaryIndexes([
      a.index('postID').name('byPost').sortKeys(['content']).queryField('commentsByPostIDByContent'),
    ]),

```
I want to implement the default use of the default index for byPost

### Describe the solution you'd like

Support associated attributes

### Describe alternatives you've considered

no

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by AnilMaktala** [comment]
Hey @sevenkkk, Thank you for your request. We will label this as a feature request for the team to review in more detail.

**Comment by renebrandel** [comment]
Hi @sevenkkk - we're actually rethinking relationships all up in our Gen 2 experience. There are a few edits that we want to apply as part of the workflow:
- for hasOne/belongsTo relationships, we'll move the source of truth to a single table rather than distributed throughout two tables
- all relationsihps (hasOne, hasMany, and manyToMany) will allow you to query from both sides of the relationship i.e. we'll enforce `belongsTo` as a requirement.
- all updates to the relationship will happen through the related model (i.e. where the belongsTo is setup)

while we're making these updates, I wanted to clarify your use case more. Is it primarily the fact that you want to setup multiple relationships between the same models and/or want to customize the field / index in which the relationship info is stored?

**Comment by sevenkkk** [comment]
@renebrandel Hello! I have a table that needs to describe the management relationship between fathers and sons, and here is the model I have defined:
```
GenreTag: a
    .model({
      code: a.string().required(),
      name: a.string().required(),
      order: a.string().required(),
      displayFields: a.string().array(),
      isEnabled: a.boolean().default(true),
      tags: a.hasMany('GenreTag'),
    })
    .secondaryIndexes([
      a.index('genreTagTagsId').sortKeys(['order']).queryField('genreTagsByParentIdByOrder'),
    ])
```
<img width="425" alt="截屏2024-03-05 12 41 56" src="https://github.com/aws-amplify/amplify-category-api/assets/74165239/82047cd6-dc0f-4fd5-b508-aa6cdd914859">

My requirement is to retrieve categories starting from the root and for each level, sort them based on the order field.
Client requests to retrieve categories, where ROOT represents the top level:

```
const res = await userPoolClient.models.GenreTag.genreTagsByParentIdByOrder({
			genreTagTagsId: 'ROOT',
		});
		if (res) {
			const tags = await res.data[0].tags();
		}
``` 
When calling tags(), I understand that it's using the gsi-GenreTag.tags index, which doesn't provide the desired sorting. Is it possible to use a custom index, such as genreTagTagsId, for sorting purposes?

**Comment by renebrandel** [comment]
Hi @sevenkkk - we've got a task on our backlog to support sort direction for the sortKey fields. So yes, you are on the right track with using secondary indexes.

The sort direction on the sort keys is available in the underlying GraphQL API but not exposed to the client code `client.models....`. You can work around this limitation for now by generating the raw GraphQL queries / mutations; then calling `client.graphql(...)`.

**Comment by sevenkkk** [comment]
Hi~ @renebrandel -
Yes, the current solution is to call client.graphql(...) to control the direction and wait for the client to support sortKey.

Also, I think binding @hasMany to a custom index is another topic. For getting "Has Many" relationships you can follow a custom index, I'm not sure if this is planned (including client-side).
Or is there any other plan to solve my above problem (without using client.graphql(...))

**Comment by AakashKB** [comment]
@renebrandel can you please share an example of making such a call via client.graphql? I am unable to find in docs.

**Comment by AnilMaktala** [comment]
Hey @sevenkkk, The latest version now includes support for sorting in custom indexes. Please verify in the latest version and let us know.
