### ISSUE TITLE
Better control over IAM resources re-using roles/policies or require policy boundaries

### ISSUE THREAD

**Issue by mhorbul** [aws-amplify/amplify-category-api#2332]
### Amplify CLI Version

12.10.1

### Question

I want to gain better control over IAM Roles and Policies while using amplify + appsync.
The IAM role gets created for every DynamoDB Table defined by the @model directive in the schema file. The code is [here](https://github.com/aws-amplify/amplify-category-api/blob/main/packages/amplify-graphql-transformer-core/src/transformation/sync-utils.ts#L46C10-L46C27)

There are two issues with this approach:
1. I ended up with >2K auto-generated roles as I have multiple environments and multiple DDB tables for each environment.
2. As a DevOps, I have no control over IAM resources managed by Amplify (developer).

Can a pre-defined IAM role be reused, or can the IAM Policy boundary for the auto-generated role be specified?

**Comment by AnilMaktala** [comment]
Hi @mhorbul, Thank you for bringing this up. While we don't support the utilization of pre-defined IAM roles, you do have the option to establish IAM permissions boundaries for roles that are generated. For further information, please refer the [IAM Permissions Boundary](https://docs.amplify.aws/javascript/tools/cli/project/permissions-boundary/) section in our documentation and let us know if you have any further questions.
