### ISSUE TITLE
subscriptions not working with auth rules

### ISSUE THREAD

**Issue by ryanSoftwareEngineer** [aws-amplify/amplify-category-api#2344]
### Amplify CLI Version

v6

### Question

i recently migrated from react native v5 to v6 is to set auth rules for subscriptions but it's not working for me. 

I have a schema for a "message" type 

```
type Message
  @model
  @auth(
    rules: [
      {
        allow: owner
        ownerField: "editors"
        operations: [create, read, delete]
      }
      { allow: private, operations: [create] }
    ]
  )
  @aws_cognito_user_pools {
  id: ID!
  text: String
  createdAt: String
  authorId: ID!
  chatRoomId: ID! 
  editors: [String]
}
```

and i try to set up a sub in a useFocusEffect 

     const variables = {
        filter: {
          chatRoomId: { eq: chatroomid },
         // i tried adding owner here as well 
        },
      };
        const subscription = API.graphql({
          query: onCreateMessage,
          variables: variables,
          // @ts-ignore
        }).subscribe({
          next: async (eventData) => {...}

subscriptions won't fire at all nor will they throw an error.

If i add " read " on private permissions` " { allow: private, operations: [create, read] }"`  then it works. 

However i only want users in the editors string to have read access as it could be a private group chat. This works with regular calls to get messages but not subscriptions. 
 
 i tried passing in authToken it doesn't help.

**Comment by phani-srikar** [comment]
Hi @ryanSoftwareEngineer, in the schema you've shared, you're using `@aws_cognito_user_pools` AppSync Auth directive explicitly on the Amplify's `@model` type. Is there a reason to have that since it's not necessary in the user input schema.

**Comment by ryanSoftwareEngineer** [comment]
> Hi @ryanSoftwareEngineer, in the schema you've shared, you're using `@aws_cognito_user_pools` AppSync Auth directive explicitly on the Amplify's `@model` type. Is there a reason to have that since it's not necessary in the user input schema.

I removed it and ran amplify push. I'm still seeing the same behavior.   

in the legacy cli there was a requirement to pass in owner https://docs.amplify.aws/javascript/tools/cli-legacy/auth-directive/#authorizing-subscriptions. Is that still necessary? if you have changed owner field should it be owner or editors?  is there documentation for authorizing subscriptions in the latest version? I wasn't able to find any. 

i've tried passing both username and sub from cognito user to the editors field. 

message record  in dynamodb: 
```
{
  "id": {
    "S": "4e150b20-a0e7-4815-850c-8d0b27773a1d"
  },
  "authorId": {
    "S": "4e80c0ed-e753-4509-9be3-5b8da3aab2db"
  },
  "chatRoomId": {
    "S": "8b7e6ba2-228a-4578-b73d-d2c32d674084"
  },
  "createdAt": {
    "S": "2024-03-18T20:21:14.390Z"
  },
  "editors": {
    "L": [
      {
        "S": "9f9ba468-4688-459d-a06a-7d96a7e12a35"  <- i've tried the cognito sub and the username here 
      },
      {
        "S": "d0615ec2-f874-43ed-b302-2ee55f7f40a9"
      }
    ]
  },
  "text": {
    "S": "But it doesn’t work"
  },
  "updatedAt": {
    "S": "2024-03-18T20:21:14.390Z"
  },
  "__typename": {
    "S": "Message"
  }
}
```

**Comment by ryanSoftwareEngineer** [comment]
I used amplify to remove api `amplify remove api` pushed the changes, then added the api back without the @aws_cognito_user_pools in my schema and it works now!!! 

It seems like the resolver has the same code but it's working now.

**Comment by vishal2develop** [comment]
I assume if you are using aws cognito autorization mode in amplify v6, then you should be using JWT token as well.

In v6 access to JWT token  has changed as compared to v5.

To get JWT token in v6 - 

`const {tokens} = await fetchAuthSession();`
`const jwtToken = tokens?.accessToken.toString() || '';`

Making this change in my code got my subscriptions working again

**Comment by dayton-bobbitt** [comment]
@vishal2develop do you mind providing more information about what you mean by this? I'm having the same issue as @ryanSoftwareEngineer and haven't been able to fix it. The subscription seems to work fine when creating my table using `allow.authenticated()` but doesn't work when I use `allow.owner()`.

Where are you importing `fetchAuthSession` and what are you doing with the `jwttoken` you create to fix this problem?

**Comment by vishal2develop** [comment]
In my setup, I used the fetchAuthSession method inside my AuthContextProvider to fetch and store the JWT token. This token is then passed down to the components through React Context. Components that need to make authorized GraphQL subscriptions can access the JWT token from this context.

**A child component accessing my provider values:**

```
const Client = ({children}: IClient) => {
  const {userJwtToken} = useAuthContext();

  // Using useMemo so that a new Apollo client is not created on every re-render
  const client = useMemo(() => {
    const jwtToken = userJwtToken || '';

    const auth: AuthOptions = {
      type: appSyncConfig.aws_appsync_authenticationType as AUTH_TYPE.AMAZON_COGNITO_USER_POOLS,
      jwtToken: jwtToken,
      // jwtToken: async () => token, // Required when you use Cognito UserPools OR OpenID Connect. token object is obtained previously
      // credentials: async () => credentials, // Required when you use IAM-based auth.
    };
    const link = ApolloLink.from([
      createAuthLink({url, region, auth}),
      createSubscriptionHandshakeLink({url, region, auth}, httpLink),
    ]);

    return new ApolloClient({
      link,
      cache: new InMemoryCache({typePolicies}),
    });
  }, [userJwtToken]);
  return <ApolloProvider client={client}>{children}</ApolloProvider>;
};
```
### `allow.owner` vs `allow.authentucated`

- I feel`allow.authenticated()` only requires that the user is authenticated, without verifying ownership of specific records
- `allow.owner()` enforces that the user must be the owner of the item they are trying to access or modify. For this to work, the JWT token needs to be properly included in requests so that the server can verify the user’s identity and ownership.
