### ISSUE TITLE
Selection set returns incomplete data (Gen2)

### ISSUE THREAD

**Issue by MKlaeui** [aws-amplify/amplify-category-api#2368]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

20.10.0

### Amplify CLI Version

@aws-amplify/backend-cli@0.12.0-beta.6 @aws-amplify/backend@0.13.0-beta.6

### What operating system are you using?

Chromebook/Linux

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

none

### Describe the bug

Selection Set returns unexpected data when querying custom types and arrays. Also, cannot retrieve foreign keys of many-to-many tables. I'm assuming reading the key from the "other side" table (part) would take longer and cost more.

### Expected behavior

1) a.string().required().array().required() should return string[] and not string[][]
2) custom type should return the data elements, not "array, authorization, required"
3) foreign key of many-to-many table should be available rather than having to query the "other side" just to get the id 

### Reproduction steps

1. const schema = a.schema({

  ExperienceEnum: a.enum(['Great', 'Ok', 'Mediocre', 'Lousy']),

  AlphabetEnum: a.enum(['A', 'B', 'C', 'D']),

  Address: a.customType({
    street: a.string(),
    city: a.string(),
  }),

  CustomerDetails: a.customType({
    address: a.ref('Address'),
    since: a.datetime().required(),
  }),

  Verbiage: a.customType({
    name: a.ref('AlphabetEnum').required(),
    paragraphs: a.string().required().array().required(),
  }),

  Part: a
    .model({
      name: a.string().required(),
      orders: a.hasMany('CustomerPart'),
    })
    .authorization([a.allow.owner(),]),

  Customer: a
    .model({
      name: a.string().required(),
      verbiage: a.ref('Verbiage').required().array().required(),
      orders: a.hasMany('CustomerPart'),
    })
    .authorization([a.allow.owner(),]),

  CustomerPart: a
    .model({
      customerDetails: a.ref('CustomerDetails'),
      experience: a.ref('ExperienceEnum'),
      customer: a.belongsTo('Customer'),
      part: a.belongsTo('Part'),
    })
    .authorization([a.allow.owner(),]),

});
3. ```
const { data: customerSet } = await client.models.Customer.list({
      selectionSet: ['id', 'name', 'verbiage.*', 'orders.*', /* orders.partOrdersId, */ 'orders.part.id']
    });
```
4. `const paragraphs = customerSet[0].verbiage[0]?.paragraphs;  // string[][] instead of string[]`
5. `const customerDetails = customerSet[0].orders[0].customerDetails;   // {array, authorization, required} instead of { address, since}`
6.     `const partId = customerSet[0].orders[0].partOrdersId; //  partOrdersId does not exist`

### Project Identifier

_No response_

### Log output

<details>

```
# Put your logs below this line

```

</details>


### Additional information

_No response_

### Before submitting, please confirm:


- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by chrisbonifacio** [comment]
Hi @MKlaeui thanks for raising this issue and providing reproduction steps. We've reproduced internally and marked as a bug for further investigation by the team.

**Comment by MKlaeui** [comment]
Thanks for this update. This looks great. One thing that I noticed as still off (and wasn't in my original example) is that an **optional** array of custom types return a single instance or null instead of an array or null. For example, if I changed the Customer model to "verbiage: a.ref('Verbiage').required().array()," I get back verbiage | null instead of verbiage[] | null
