### ISSUE TITLE
[Gen2] Cannot deploy apps with field level authorization rules

### ISSUE THREAD

**Issue by ujjwol05** [aws-amplify/amplify-category-api#2372]
### Environment information

```plain text
System:
  OS: macOS 14.4
  CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Memory: 37.95 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn: 1.22.11 - /usr/local/bin/yarn
  npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.13.0-beta.9
  @aws-amplify/backend-cli: 0.12.0-beta.10
  aws-amplify: 6.0.21
  aws-cdk: 2.133.0
  aws-cdk-lib: 2.133.0
  typescript: 5.4.2
AWS environment variables:
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
No CDK environment variables
```

### Description

I've added field level authorization for all fields including required fields, It still complains saying 

> InvalidDirectiveError: When using field-level authorization rules you need to add rules to all of the model's required fields with at least read permissions. Found model "Addresses" with required fields ["id","streetNumber","streetName","suburb","postcode","country","createdAt","updatedAt"] missing field-level authorization rules.

This is my model definition
```
Addresses: a
        .model({
            id: a.id()
                .authorization([
                    a.allow.public().to(['read']),
                    a.allow.specificGroups(['user']).to(['create', 'read']),
                    a.allow.specificGroups(['admin'])
                ]),
            unitNumber: a.string()
                .authorization([
                    a.allow.public().to(['read']),
                    a.allow.specificGroups(['user']).to(['create', 'read']),
                    a.allow.specificGroups(['admin'])
                ]),
            streetNumber: a.string()
                .required()
                .authorization([
                    a.allow.public().to(['read']),
                    a.allow.specificGroups(['user']).to(['create', 'read']),
                    a.allow.specificGroups(['admin'])
                ]),
            streetName: a.string()
                .required()
                .authorization([
                    a.allow.public().to(['read']),
                    a.allow.specificGroups(['user']).to(['create', 'read']),
                    a.allow.specificGroups(['admin'])
                ]),
            suburb: a.string()
                .required()
                .authorization([
                    a.allow.public().to(['read']),
                    a.allow.specificGroups(['user']).to(['create', 'read']),
                    a.allow.specificGroups(['admin'])
                ]),
            postcode: a.integer()
                .required()
                .authorization([
                    a.allow.public().to(['read']),
                    a.allow.specificGroups(['user']).to(['create', 'read']),
                    a.allow.specificGroups(['admin'])
                ]),
            state: a.ref('States')
                .authorization([
                    a.allow.public().to(['read']),
                    a.allow.specificGroups(['user']).to(['create', 'read']),
                    a.allow.specificGroups(['admin'])
                ]),
            country: a.string()
                .required()
                .authorization([
                    a.allow.public().to(['read']),
                    a.allow.specificGroups(['user']).to(['create', 'read']),
                    a.allow.specificGroups(['admin'])
                ]),
            createdAt: a.datetime()
                .required()
                .authorization([
                    a.allow.public().to(['read']),
                    a.allow.specificGroups(['user']).to(['create', 'read']),
                    a.allow.specificGroups(['admin'])
                ]),
            updatedAt: a.datetime()
                .required()
                .authorization([
                    a.allow.public().to(['read']),
                    a.allow.specificGroups(['user']).to(['create', 'read']),
                    a.allow.specificGroups(['admin'])
                ])
        })
        .authorization([
            a.allow.public().to(['read']),
            a.allow.specificGroups(['user']).to(['create', 'read']),
            a.allow.specificGroups(['admin'])
        ])
```

**Comment by ujjwol05** [comment]
@ykethan Thank you for your time. I think it's my bad. It appears that the model level authentication for the other model in my code base was incorrect. There was a 1-to-many relation with another model in the code base. Despite this, the error message received was irrelevant. I'm closing this for now, but it would be beneficial to have the correct error message in the future.

**Comment by chrisbonifacio** [comment]
Hi @ujjwol05 👋 thanks for raising this issue!

I'm curious which models and/or relationships in the schema were causing the field auth error message so that we can reproduce it and improve the messing?

**Comment by AzharRaeisi** [comment]
> Hey,👋 thanks for raising this! Tried reproducing the issue with the following in sandbox but did not run into this error message,
> 
> ```graphql
> const schema = a.schema({
>   States: a.enum(["NSW", "VIC", "QLD", "SA", "WA", "TAS", "NT", "ACT"]),
>   Addresses: a
>     .model({
>       id: a
>         .id()
>         .authorization([
>           a.allow.public().to(["read"]),
>           a.allow.specificGroups(["user"]).to(["create", "read"]),
>           a.allow.specificGroups(["admin"]),
>         ]),
>       unitNumber: a
>         .string()
>         .authorization([
>           a.allow.public().to(["read"]),
>           a.allow.specificGroups(["user"]).to(["create", "read"]),
>           a.allow.specificGroups(["admin"]),
>         ]),
>       streetNumber: a
>         .string()
>         .required()
>         .authorization([
>           a.allow.public().to(["read"]),
>           a.allow.specificGroups(["user"]).to(["create", "read"]),
>           a.allow.specificGroups(["admin"]),
>         ]),
>       streetName: a
>         .string()
>         .required()
>         .authorization([
>           a.allow.public().to(["read"]),
>           a.allow.specificGroups(["user"]).to(["create", "read"]),
>           a.allow.specificGroups(["admin"]),
>         ]),
>       suburb: a
>         .string()
>         .required()
>         .authorization([
>           a.allow.public().to(["read"]),
>           a.allow.specificGroups(["user"]).to(["create", "read"]),
>           a.allow.specificGroups(["admin"]),
>         ]),
>       postcode: a
>         .integer()
>         .required()
>         .authorization([
>           a.allow.public().to(["read"]),
>           a.allow.specificGroups(["user"]).to(["create", "read"]),
>           a.allow.specificGroups(["admin"]),
>         ]),
>       state: a
>         .ref("States")
>         .authorization([
>           a.allow.public().to(["read"]),
>           a.allow.specificGroups(["user"]).to(["create", "read"]),
>           a.allow.specificGroups(["admin"]),
>         ]),
>       country: a
>         .string()
>         .required()
>         .authorization([
>           a.allow.public().to(["read"]),
>           a.allow.specificGroups(["user"]).to(["create", "read"]),
>           a.allow.specificGroups(["admin"]),
>         ]),
>       createdAt: a
>         .datetime()
>         .required()
>         .authorization([
>           a.allow.public().to(["read"]),
>           a.allow.specificGroups(["user"]).to(["create", "read"]),
>           a.allow.specificGroups(["admin"]),
>         ]),
>       updatedAt: a
>         .datetime()
>         .required()
>         .authorization([
>           a.allow.public().to(["read"]),
>           a.allow.specificGroups(["user"]).to(["create", "read"]),
>           a.allow.specificGroups(["admin"]),
>         ]),
>     })
>     .authorization([
>       a.allow.public().to(["read"]),
>       a.allow.specificGroups(["user"]).to(["create", "read"]),
>       a.allow.specificGroups(["admin"]),
>     ]),
> });
> 
> export type Schema = ClientSchema<typeof schema>;
> 
> export const data = defineData({
>   schema,
>   authorizationModes: {
>     defaultAuthorizationMode: "userPool",
> 
>     // API Key is used for a.allow.public() rules
>     apiKeyAuthorizationMode: {
>       expiresInDays: 30,
>     },
>   },
> });
> ```
> 
> I'm going to transfer this over to our API repository for better assistance 🙂

I am curious how could I use "identityPool" for guest user?
```
Post: a
    .model({
title: a.string(),
      content: a.string(),
    }).authorization((allow) => [allow.owner(),
  allow.guest().to(['read']),
  ])
```

**Comment by binarycombinatrix** [comment]
having the same issue here it says, 
When using field-level authorization rules you need to add rules to all of the model's required fields with at least read permissions. Found model "Video" with required fields ["partitionKey","sortKey","type"] missing field-level authorization rules. Please help...

import { type ClientSchema, a, defineData } from "@aws-amplify/backend";

const schema = a.schema({
  Comment: a.customType({
    content: a.string().required(),
    username: a.string().required(),
    dp: a.string().required(),
    dn: a.string().required(),
  }),
  Video: a
    .model({
      partitionKey: a
        .string()
        .required()
        .authorization((allow) => [
          allow.publicApiKey().to(["read"]),
          allow.owner(),
        ]),
      sortKey: a
        .string()
        .required()
        .authorization((allow) => [
          allow.publicApiKey().to(["read"]),
          allow.owner(),
        ]), ////video title or username   + uuidv1
      type: a
        .string()
        .required()
        .authorization((allow) => [
          allow.publicApiKey().to(["read"]),
          allow.owner(),
        ]), ///specify type to avoid confusion
      category: a.string(), /// category which is partition key for video entry
      debate: a.json().array(), ///debate of the video
      description: a.string(), ///channel or video description
      url: a.string(), ///video url
      thumbnail: a.string(), ///video thumbnail
      dp: a.string(), ///user dp can store in both cases,
      comment: a
        .ref("Comment")
        .array()
        .authorization((allow) => [allow.authenticated()]), ///only in case of video
      dn: a.string(), //display name
      username: a.string(),
    })
    .identifier(["partitionKey", "sortKey"])
    .authorization((allow) => [
      // allow.publicApiKey(),
      allow.publicApiKey().to(["read"]),
      // Allow signed-in user to create, read, update,
      // and delete their __OWN__ posts.
      allow.owner(),
    ]),
});

export type Schema = ClientSchema<typeof schema>;

export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: "apiKey",
    // API Key is used for a.allow.public() rules
    apiKeyAuthorizationMode: {
      expiresInDays: 30,
    },
  },
});
