### ISSUE TITLE
Gen 2 - Not Authorized to access **** on type Query

### ISSUE THREAD

**Issue by kekami** [aws-amplify/amplify-category-api#2422]
### Environment information

```plain text
System:
  OS: macOS 14.4
  CPU: (10) arm64 Apple M1 Max
  Memory: 63.53 MB / 32.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 18.20.0 - ~/.nvm/versions/node/v18.20.0/bin/node
  Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.0/bin/yarn
  npm: 10.5.0 - ~/.nvm/versions/node/v18.20.0/bin/npm
  pnpm: 8.15.3 - /opt/homebrew/bin/pnpm
NPM Packages:
  @aws-amplify/backend: 0.13.0-beta.15
  @aws-amplify/backend-cli: 0.12.0-beta.17
  aws-amplify: 6.0.27
  aws-cdk: 2.135.0
  aws-cdk-lib: 2.135.0
  typescript: 5.4.3
AWS environment variables:
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
No CDK environment variables
```

### Description

Hello, I'm playing around with Gen 2 and have encountered an issue that I've been unable to resolve. Trying to set up a custom query using a lambda. I receive the following error both on the client and appsync console.

```
{"listStripeInvoices": null} [{"data": null, "errorInfo": null, "errorType": "Unauthorized", "locations": [[Object]], "message": "Not Authorized to access listStripeInvoices on type Query", "path": ["listStripeInvoices"]}]
```

The invoice resolve runs but it seems to throw sometime after the resolver returns the data. And I don't understand why. I've tried using `a.allow.private()` as well, and also tried chaining the ref `a.ref('StripeInvoice').array().authorization([a.allow.public()])` with authorization as well.

Any idea?

Setup:
```
# resource.ts
const schema = a
  .schema({
    StripeInvoice: a.customType({
      id: a.id().required(),
      object: a.string().required(),
      account_country: a.string(),
    }),

    listStripeInvoices: a
      .query()
      .returns(a.ref('StripeInvoice').array())
      .handler(a.handler.function(invoiceHandler))
      .authorization([a.allow.public()]),
  });
```

```
# invoiceHandler
export const handler: Schema['listStripeInvoices']['functionHandler'] =
  async () => {
    const invoices = await stripe.invoices.list();
    return invoices.data;
  };

```

```
# client query
 const { data, errors } = await client.queries.listStripeInvoices({
        authMode: 'userPool',
      });
```

**Comment by blipps199** [comment]
I'm having a similar issue. I have a postgres database that I generated a Schema for via the ampx commands found in the gen 2 docs. I can query this schema just fine via the Amplify console API playground but when I try to query via the react front end I get not authorized errors `Not Authorized to access listTests on type Query`. I've tried several things from adding authMode as userPool and identityPool. I've tried adding authorization to the generatedSwlSchema before combining the schema with my original schema... `const testSchema = generatedSqlSchema.authorization(allow => [allow.guest()]);`. I've also added authMode to the query itself and in the generateClient with no luck, `const response = await client.models.test.list({authMode: 'userPool'});`. I'm not really sure what else to do.

**Comment by ethoman** [comment]
I'm also having the exact same issue! Adding a lambda invocation should not be this hard, we've spent hours debugging this

**Comment by jdmonm** [comment]
I also have a similar problem, but I'm actually copying and pasting the example code from the documentation, it doesn't work anyway. 

<img width="467" alt="Screenshot 2024-10-26 at 1 16 42 AM" src="https://github.com/user-attachments/assets/114bc759-6e10-4944-bd75-ab61f09db9ce">

**Comment by anicarrr** [comment]
In my case i solved it by pushing the schema again after adding a lambda function, seems like a bug, just change anything in your schema and push it again.

**Comment by reactnetau** [comment]
Did anyone find a solution to this problem.

I'm getting Unauthorized on a return type

PaymentIntent: a.mutation()
  .arguments({ amount: a.integer() })
  .returns(a.ref('PaymentIntentReturnType'))
  .authorization(allow => [allow.authenticated()])
  .handler(a.handler.function(createPaymentIntentFunction)),

**Comment by mnai01** [comment]
How is this closed? Its an active bug

**Comment by Lychas** [comment]
can confirm, still an active bug.

2025-08-12T23:00:57.425Z	26c30fb4-457d-421c-9b13-62f0c30f7045	ERROR	Excel data validation failed: [
  {
    path: [ 'checkIfExcelDataValid', 'isError' ],
    data: null,
    errorType: 'Unauthorized',
    errorInfo: null,
    locations: [ [Object] ],
    message: 'Not Authorized to access isError on type checkIfExcelDataValidResponse'
  },
  {
    path: [ 'checkIfExcelDataValid', 'errorMessage' ],
    data: null,
    errorType: 'Unauthorized',
    errorInfo: null,
    locations: [ [Object] ],
    message: 'Not Authorized to access errorMessage on type checkIfExcelDataValidResponse'
  }
] undefined

**Comment by a-yoshino-irt** [comment]
I got a similar problem from yesterday. The under Log is that.
I tried delete sandbox and created. But cannot resolved.

AppSync Response
```
{
    "data": {
        "listM_manufacturings": null
    },
    "errors": [
        {
            "path": [
                "listXXXXX"
            ],
            "data": null,
            "errorType": "Unauthorized",
            "errorInfo": null,
            "locations": [
                {
                    "line": 2,
                    "column": 3,
                    "sourceName": null
                }
            ],
            "message": "Not Authorized to access listXXXXX on type Query"
        }
    ]
```

The same AppSync can execute [Function](https://docs.amplify.aws/react/build-a-backend/functions/set-up-function/).
So I think it's suspicious only [Data Resource](https://docs.amplify.aws/react/build-a-backend/data/set-up-data/)...

I think I've implemented it correctly...
````
a.query()
.arguments()
.returns(a.ref('XXXXXXType'))
.authorization(allow => [allow.authenticated()])
`````
.handler(a.handler.function(createPaymentIntentFunction)),
