### ISSUE TITLE
Adding custom query with function handler results in a broken lambda data source

### ISSUE THREAD

**Issue by kekami** [aws-amplify/amplify-category-api#2427]
### Environment information

```plain text
System:
  OS: macOS 14.4
  CPU: (10) arm64 Apple M1 Max
  Memory: 176.13 MB / 32.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 18.20.0 - ~/.nvm/versions/node/v18.20.0/bin/node
  Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.0/bin/yarn
  npm: 10.5.0 - ~/.nvm/versions/node/v18.20.0/bin/npm
  pnpm: 8.15.3 - /opt/homebrew/bin/pnpm
NPM Packages:
  @aws-amplify/backend: 0.13.0-beta.15
  @aws-amplify/backend-cli: 0.12.0-beta.17
  aws-amplify: 6.0.23
  aws-cdk: 2.127.0
  aws-cdk-lib: 2.127.0
  typescript: 5.4.3
AWS environment variables:
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
No CDK environment variables
```

### Description

The following schema results in a lambda data source with a faulty function arn that seems to be based on the query field name + args.

```
fetchStripePaymentSheet: a
      .query()
      .arguments({
        customerId: a.string().required(),
        invoiceId: a.string().required(),
      })
      .returns(
        a.customType({
          ephemeralKey: a.string().required(),
          paymentIntentClientSecret: a.string().required(),
        })
      )
      .authorization([a.allow.public()])
      .handler(a.handler.function(stripePaymentSheetHandler)),
```

![Screenshot 2024-04-05 at 16 15 15](https://github.com/aws-amplify/amplify-backend/assets/24361798/3dc79671-a592-4714-93e2-7eaa4dfa36b2)

**Comment by kekami** [comment]
It also looks like the lambda function has the default physical id as name and arn. Which doesn't match with the name that the AppSync data source maps to.

**Comment by AnilMaktala** [comment]
Hey @kekami, Thank you for reporting this. We can replicate the issue by following the steps provided in the description. Hence, marking this as a bug for the team to evaluate further.

<img width="1165" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/93ad65dc-f670-4da7-82c5-57e7ebecb136">

**Comment by kekami** [comment]
Hi @AnilMaktala, I debugged the issue and found the cause for it. Unfortunately the bug is in `@aws-amplify/data-schema` which seems to not be publicly available and this I can provide a pull request.

The issue is due to the fact that each custom function overwrites the definition of the previous one. The fix is pretty simple. In `@aws-amplify/data-schema` there is a `SchemaProcessor`, when it iterates over all the top level types one of the else clauses need to be changed as follow:

```diff
         else if (isCustomOperation(typeDef)) {
                const { typeName: opType } = typeDef.data;
                const { gqlField, models, jsFunctionForField, lambdaFunctionDefinition, customSqlDataSourceStrategy, } = transformCustomOperations(typeDef, typeName, mostRelevantAuthRules, databaseType, getRefType);
                - lambdaFunctions = lambdaFunctionDefinition
                + lambdaFunctions = {
                   ...lambdaFunctions,
                   ...lambdaFunctionDefinition
                }
                // snip for brevity    
            }
```

This should resolve https://github.com/aws-amplify/amplify-category-api/issues/2417 as well

Could you make sure this gets into the right hands? And is there a particular reason `@aws-amplify/data-schema` isn't in the public reposityory?

**Comment by iartemiev** [comment]
This is fixed in the latest version of `amplify-backend` and amplify JS.

Please upgrade the following packages:
```json
"dependencies": {
  "aws-amplify": "^6.2.0",
   ...
},
"devDependencies": {
  "@aws-amplify/backend": "^1.0.0",
  "@aws-amplify/backend-cli": "^1.0.0",
  ...
}
```
