### ISSUE TITLE
graphql list vs sync

### ISSUE THREAD

**Issue by ErikHochweller** [aws-amplify/amplify-category-api#2434]
### Amplify CLI Version

10.7.3

### Question

I have a table called surfaces, and when i run a list on it i get less results than when i run sync on it, f.e.

query MyQuery {
  listSurfaces(filter: {inquiryID: {eq: "48da725a-a7ae-4e91-a6c9-afdb03251138"}}) {
    items {
      inquiryID
    }
  }
}
i get no results, but when i run it with sync i get 3 results.

the same would be true tomorrow or next week. Why is the data not synced?

**Comment by palpatim** [comment]
Hey @ErikHochweller, thank you for reaching out. Could you provide us the following information. 

1. Project identifier output when running `amplify diagnose --send-report`
2. As @ykethan asked, does this still happen on the latest version of Amplify CLI ([12.10.3](https://www.npmjs.com/package/@aws-amplify/cli/v/12.10.3))?
3. Does this happen only on clients, or also from the AppSync query console? If only on clients, what client are you using, and what version?

**Comment by palpatim** [comment]
(Repasting the resolver above with code formatting)

```vtl
## [Start] List Request. **
#set( $args = $util.defaultIfNull($ctx.stash.transformedArgs, $ctx.args) )
#set( $limit = $util.defaultIfNull($args.limit, 500) )
#set( $ListRequest = {
  "version": "2018-05-29",
  "limit": $limit
} )
#if( $args.nextToken )
  #set( $ListRequest.nextToken = $args.nextToken )
#end
#if( !$util.isNullOrEmpty($ctx.stash.authFilter) )
  #set( $filter = $ctx.stash.authFilter )
  #if( !$util.isNullOrEmpty($args.filter) )
    #set( $filter = {
  "and":   [$filter, $args.filter]
} )
  #end
#else
  #if( !$util.isNullOrEmpty($args.filter) )
    #set( $filter = $args.filter )
  #end
#end
#if( !$util.isNullOrEmpty($filter) )
  #set( $filterExpression = $util.parseJson($util.transform.toDynamoDBFilterExpression($filter)) )
  #if( $util.isNullOrEmpty($filterExpression) )
    $util.error("Unable to process the filter expression", "Unrecognized Filter")
  #end
  #if( !$util.isNullOrBlank($filterExpression.expression) )
    #if( $filterExpression.expressionValues.size() == 0 )
      $util.qr($filterExpression.remove("expressionValues"))
    #end
    #set( $ListRequest.filter = $filterExpression )
  #end
#end
#if( !$util.isNull($ctx.stash.modelQueryExpression) && !$util.isNullOrEmpty($ctx.stash.modelQueryExpression.expression) )
  $util.qr($ListRequest.put("operation", "Query"))
  $util.qr($ListRequest.put("query", $ctx.stash.modelQueryExpression))
  #if( !$util.isNull($args.sortDirection) && $args.sortDirection == "DESC" )
    #set( $ListRequest.scanIndexForward = false )
  #else
    #set( $ListRequest.scanIndexForward = true )
  #end
#else
  $util.qr($ListRequest.put("operation", "Scan"))
#end
#if( !$util.isNull($ctx.stash.metadata.index) )
  #set( $ListRequest.IndexName = $ctx.stash.metadata.index )
#end
$util.toJson($ListRequest)
## [End] List Request. **
```

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
