### ISSUE TITLE
Graphql schema @auth only update first two item to vtl template

### ISSUE THREAD

**Issue by ucfangyiwang** [aws-amplify/amplify-category-api#2439]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.16.1

### Amplify CLI Version

12.10.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

```
signupMember(
    input: SignupMemberRequest!
  ): SignupMembeResponse!
    @function(name: "signupMember-${env}")
    @auth(
      rules: [
        { allow: private, provider: iam }
        {
          allow: groups
          groups: ["admin", "super-admin", "L0", "L1", "L2", "L3", "L4", "L5"]
        }
      ]
    ) 
```
this is my schema  when i do amplify push the vtl template is 

```
#if( $util.authType() == "User Pool Authorization" )
  #if( !$isAuthorized )
    #set( $staticGroupRoles = [{"claim":"cognito:groups","entity":"admin"},{"claim":"cognito:groups","entity":"super-admin"}] )
    #foreach( $groupRole in $staticGroupRoles )
      #set( $groupsInToken = $util.defaultIfNull($ctx.identity.claims.get($groupRole.claim), []) )
      #if( $groupsInToken.contains($groupRole.entity) )
        #set( $isAuthorized = true )
        #break
      #end
    #end
  #end
#end
```
it only give first two group permissions . our function not working only "admin" and "super-admin" can access the function. the template not match the schema.

### Expected behavior

check and fix the bug

### Reproduction steps

amplify push then check the appsync 

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hey @ucfangyiwang, Thank you for raising this. I am not able to reproduce the issue using the schema provided. can you please try running `amplify api gql-compile` and let us know if it resolves your issue.

Here is the generated VTL:
```
## [Start] Field Authorization Steps. **
#set( $isAuthorized = false )
#if( $util.authType() == "API Key Authorization" )

#end
#if( $util.authType() == "IAM Authorization" )
  #if( !$isAuthorized )
    #if( ($ctx.identity.userArn == $ctx.stash.authRole) || ($ctx.identity.cognitoIdentityPoolId == $ctx.stash.identityPoolId && $ctx.identity.cognitoIdentityAuthType == "authenticated") )
      #set( $isAuthorized = true )
    #end
  #end
#end
#if( $util.authType() == "User Pool Authorization" )
  #if( !$isAuthorized )
    #set( $staticGroupRoles = [{"claim":"cognito:groups","entity":"admin"},{"claim":"cognito:groups","entity":"super-admin"},{"claim":"cognito:groups","entity":"L0"},{"claim":"cognito:groups","entity":"L1"},{"claim":"cognito:groups","entity":"L2"},{"claim":"cognito:groups","entity":"L3"},{"claim":"cognito:groups","entity":"L4"},{"claim":"cognito:groups","entity":"L5"}] )
    #foreach( $groupRole in $staticGroupRoles )
      #set( $groupsInToken = $util.defaultIfNull($ctx.identity.claims.get($groupRole.claim), []) )
      #if( $groupsInToken.contains($groupRole.entity) )
        #set( $isAuthorized = true )
        #break
      #end
    #end
  #end
#end
#if( !$isAuthorized )
$util.unauthorized()
#end
$util.toJson({"version":"2018-05-29","payload":{}})
## [End] Field Authorization Steps. **

```

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
