### ISSUE TITLE
I want to customize the table between many to many data model.

### ISSUE THREAD

**Issue by rnrnstar2** [aws-amplify/amplify-category-api#2450]
### Environment information

```plain text
System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M2 Pro
  Memory: 157.41 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.5.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 9.8.0 - /usr/local/bin/npm
  pnpm: 8.15.5 - ~/Library/pnpm/pnpm
NPM Packages:
  @aws-amplify/backend: Not Found
  @aws-amplify/backend-cli: Not Found
  aws-amplify: Not Found
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: Not Found
AWS environment variables:
  AWS_PROFILE = cloudteam
  AWS_DEFAULT_PROFILE = cloudteam
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

Teams and members are connected many to many.
A table called TeamMembers is created.
There is a use case where you want to edit this table when implementing functions such as granting privileges to members.
what should I do?

Also, I don't know how to get the id of teamMember with amplify gen2.
```
const { data: teamMembers } = await member.teams();
const teamMembers: {
     member: (options?: {
         ...;
     }) => SingularReturnValue<...>;
     team: (options?: {
         ...;
     }) => SingularReturnValue<...>;
}[]
```

**Comment by AnilMaktala** [comment]
Hi @rnrnstar2, Thank you for bringing this up. I don't believe there is native support for this use case, but I will check with the team to see if there are any workarounds available.

**Comment by AnilMaktala** [comment]
Hey @rnrnstar2, Thank you for patience. You can achieve your use-case by using `hasMany` and `belongsTo` on Join tables. Please refer to [Modeling relationships section](https://docs.amplify.aws/gen2/build-a-backend/data/data-modeling/relationships/) of docs for more details.

**Comment by rnrnstar2** [comment]
Thank you for updating.
It worked fine.
