### ISSUE TITLE
AppSync max @auth rules size? -> Invalid FilterExpression: Expression size has exceeded the maximum allowed size;

### ISSUE THREAD

**Issue by biller-aivy** [aws-amplify/amplify-category-api#2451]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

21.6.2

### Amplify CLI Version

12.10.3

### What operating system are you using?

macOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

none

### Describe the bug

I added some new auth rules, than I get the error in AppSync Console and FE App. 

```
type User
  @model
  @auth(
    rules: [
      { allow: private, provider: iam }
      {
        allow: owner
        identityClaim: "username" # explicit use of username
      }
      { allow: groups, groupsField: "authorized_create", operations: [create, read] }
      { allow: groups, groupsField: "authorized_read", operations: [read] }
      { allow: groups, groupsField: "authorized_update", operations: [update, read] }
      { allow: groups, groupsField: "authorized_delete", operations: [delete, read] }
      { allow: owner, identityClaim: "username", ownerField: "authorized_read", operations: [read] }
    ]
  ) {
  id: ID!
  owner: ID!
  authorized_create: [ID]
  authorized_read: [ID]
  authorized_update: [ID]
  authorized_delete: [ID]
}
```

Error: Invalid FilterExpression: Expression size has exceeded the maximum allowed size;

region: eu-central-1
appID: d36kyjopucs8j3 

### Expected behavior

7 rules should work without exceeding the limit of 4kb?!

### Reproduction steps

add more rules to a table

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hey @biller-aivy, Thank you for providing additional details. Looks like the issue seems to be resolved on your end. Can we close this issue?
