### ISSUE TITLE
Where is the definitions for GraphQL directives?

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-category-api#246]
My editor(PHPStorm) shows errors on the schema file because it can't find any [definitions](https://docs.amplify.aws/cli/graphql-transformer/directives#definition-2) for GraphQL directives that amplify provides. 

I'm wondering if there is a command that can extract all the definitions to a file, so I could stop copying them by hand from the doc page. 

**Amplify CLI Version** 

4.29.2

**Comment by renebrandel** [comment]
https://docs.amplify.aws/react/tools/cli/graphqlapi/directives-reference/#pageMain

typically on the bottom of each page linked, you'll find the GraphQL definition.
