### ISSUE TITLE
CloudFormation stuck in updating DynamoDB table after backend update

### ISSUE THREAD

**Issue by cabcookie** [aws-amplify/amplify-category-api#2488]
### Environment information

```plain text
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 1.23 GB / 32.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn: undefined - undefined
  npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.13.0
  @aws-amplify/backend-cli: 0.12.0
  aws-amplify: 6.0.28
  aws-cdk: 2.137.0
  aws-cdk-lib: 2.137.0
  typescript: 5.4.5
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

I upgraded from beta.3 to these package versions:
@aws-amplify/backend: 0.13.0
@aws-amplify/backend-cli: 0.12.0

Now, I had to update my schemas as the `.manyToMany` doesn't exist anymore. My code changes are as a subset below. I merged the changes into my staging branch and linked it in my Gen2 Amplify environment as a separate branch. Now, the deployment times out after 30 minutes as the CloudFormation update gets stuck and finishes after 60 minutes due to changes in a nested stack. The update of the ProjectActivityTable started at 2024-04-23 11:44:06 UTC+0200 and finished at 2024-04-23 12:32:20 UTC+0200. Why does it take such a long time?

I was giving up already but while I was writing this issue it finally finished the changes. 4 tables were affected by it and delayed the deployment.

As the deployment failed in Amplify I had to redeploy the change and this time it was much quicker.

I had to change this:
```typescript
const schema = a.schema({
  Activity: a
    .model({
      owner: a.string().authorization([a.allow.owner().to(["read", "delete"])]),
      notes: a.string(),
      forProjects: a.manyToMany("Projects", { relationName: "ProjectActivity" }),
      ...
    })
    .authorization((allow) => [allow.owner()]),
  Projects: a
    .model({
      owner: a.string().authorization([a.allow.owner().to(["read", "delete"])]),
      project: a.string().required(),
      activities: a.manyToMany("Activity", { relationName: "ProjectActivity" }),
      ...
    })
    .authorization((allow) => [allow.owner()]),
});
```

to this:
```typescript
const schema = a.schema({
  ProjectActivity: a
    .model({
      owner: a
        .string()
        .authorization((allow) => [allow.owner().to(["read", "delete"])]),
      activityId: a.id(),
      activity: a.belongsTo("Activity", "activityId"),
      projectsId: a.id(),
      projects: a.belongsTo("Projects", "projectsId"),
    })
    .authorization((allow) => [allow.owner()]),
  Activity: a
    .model({
      owner: a
        .string()
        .authorization((allow) => [allow.owner().to(["read", "delete"])]),
      notes: a.string(),
      forProjects: a.hasMany("ProjectActivity", "activityId"),
      ...
    })
    .authorization((allow) => [allow.owner()]),
  Projects: a
    .model({
      owner: a
        .string()
        .authorization((allow) => [allow.owner().to(["read", "delete"])]),
      project: a.string().required(),
      activities: a.hasMany("ProjectActivity", "projectsId"),
      ...
    })
    .authorization((allow) => [allow.owner()]),
});
```

**Comment by cabcookie** [comment]
I dove a little deeper into what is happening. So, let me explain the issue in more detail:

I am using AWS Amplify Generation 2 (Gen2) for managing a GraphQL API schema, which auto-generates DynamoDB tables based on this schema. Previously, Amplify Gen2 supported automatic creation of tables for many-to-many (n:n) relationships with appropriate indexes. For instance, if I defined a **`Project`** table and an **`Activity`** table, where each **`Activity`** could belong to multiple **`Project`s** and vice versa, Amplify Gen2 would automatically generate an intermediate **`ProjectActivity`** table with **`activityId`** and **`projectId`** fields. Each field had an index (**`byActivity`** and **`byProject`**).

To implement this, I simply had to define the relationships in my schemas as follows:
- In the **`Project`** schema: `"activities: a.manyToMany("Project", {relationName: "ProjectActivity"})"`
- In the **`Activity`** schema: `"projects: a.manyToMany("Activity", {relationName: "ProjectActivity"})"`

However, in the latest version of Amplify Gen2, this automatic handling has been deprecated. Now, I need to explicitly define the **`ProjectActivity`** schema myself and manage the relationships using **`.belongsTo`** and **`.hasMany`**. This change also involves deleting the existing indexes and creating new ones named **`gsi-Activity.projects`** and **`gsi-Project.activities`**. This index re-creation process is not only time-consuming (approximately one hour) but has also failed to complete successfully. Furthermore, because the existing indexes are deleted before the new ones are created, the rollback process takes an additional hour. During this time, the table lacks functional indexes, significantly impacting the performance of the application.

I am currently unable to determine why the index creation is failing. I need assistance in resolving this issue to avoid extensive downtime and performance degradation.

**Comment by cabcookie** [comment]
One question I have is why deleting the existing indexes before creating the new ones?

**Comment by cabcookie** [comment]
Further investigation has revealed a potential issue with the index re-creation process in Amplify Gen2. It appears that the re-creation of the indexes, which takes a significant amount of time, is causing the step function to time out. This results in a FAILED state, despite the indexes being successfully created afterward. This issue surfaced during a rollback triggered by CloudFormation. I confirmed that all indexes in DynamoDB are as they were prior to the new deployment attempt. However, the CloudFormation stack is now in a "UPDATE_ROLLBACK_FAILED" state.

This situation is particularly concerning because it prevents me from redeploying my changes through Amplify. The system returns the following error: "Error [ValidationError]: Stack: arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/amplify-xxxxxxxxxxxxxx-main-branch-xxxxxxxxxx/fbb56210-c337-11ee-bdc6-0e8eacfb1d5d is in UPDATE_ROLLBACK_FAILED state and cannot be updated."

This is occurring in my production environment, which is critical. Any assistance or insights into resolving this issue would be greatly appreciated.

**Comment by AaronZyLee** [comment]
It is expected for index update on a existing table consuming a long time. This is a limitation for DynamoDB that any `UpdateTable` operation for GSIs is only allowed for one per API call. If you use the `AWS::DynamoDB::Table` in your CFN template, your deployment will fail as the CFN only allows for one index update per operation. The Gen2 uses a custom resource instead to bypass this limitation to allow for multiple GSI updates within one deployment. However, there is still a hard limitation of 1 hour for the total deployment time in CFN, which means the limit can be exceeded for too many index updates.

In your case, the GSI is updated based on the template difference. Since the old ones never exists in the template, those old indexes will be deleted first. The DynamoDB does not support a direct rename of an existing index but only delete and recreate, which adds more time to this kind of operations. This is also not allowed in current `AWS::DynamoDB::Table` but is bypassed in Gen2.

In the sandbox mode, we are using the strategy of dropping and recreate table when index change is detected. This is because `CreateTable` can includes multiple GSIs and calling `DeleteTable` then `CreateTable` is much faster than doing update table operation in place.

Still this issue reminds us to make some warnings on not to include too many index updates within one deployment.

For the duplicate execution, I suggest you can try again after 2 hours for the state machine to timeout to see if you can have a successful rollback afterwards

**Comment by AaronZyLee** [comment]
Also a follow up question, could you provide your region for the deployment? The DynamoDB APIs may have different runtimes based on regions.

**Comment by cabcookie** [comment]
Region is us-east-1. My understanding is the aim of amplify is to abstract away the implementation challenges. Users will not know this limitation of DDB and are also not aware that a schema change results in index creation. Therefore, I believe it is important to inform the user that certain schema changes will take time (on the Gen2 deployment UI) and trigger automatic retries after CFN or the state machine are timing out. Now, I need to dive very deep into the way Amplify implements things to understand how to fix the stack. 

> For the duplicate execution, I suggest you can try again after 2 hours for the state machine to timeout to see if you can have a successful rollback afterwards

What exactly should I try again?
You can also reach me on Slack. My alias is carskoch@

**Comment by cabcookie** [comment]
I did not find a way to re-run the existing state machine execution so I created a new execution with the same payload. The Lambda that is executed by the state machine returns an error that CloudFormation is not responding to the success message. So, I continued the rollback operation in CloudFormation. It wants to execute a state machine with a specific execution ID which already exist so CloudFormation fails as well. How can I link CloudFormation to the new execution ID of the state machine instead of the old one? Or is there another way to rescue the stack?

**Comment by AaronZyLee** [comment]
Update on this: talked with customer offline and the rollback issue was finally resolved by deleting the state machine and recreate the same one with the same ARN and config. 

As for a long term happy path, we need to introduce the `WaitCondition` into the CFN template to bypass that 1 hour limit, which is a feature for improvement after Gen2 GA.

Will close this issue for now. Please feel free to reopen if there are any unresolved issues.
