### ISSUE TITLE
Inserting an item with Graphql and also getting an error

### ISSUE THREAD

**Issue by Themrpie** [aws-amplify/amplify-category-api#2491]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

12.11.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

For some reason when I insert an object in my table it works well but I also get an error message. 
And when I query a particular object I get the same error. Hopefully somebody can see what I'm doing wrong. I'm using graphql from amplify.

The problem is being cause by the category field of Service, because when I remove it or change it to a String in the schema everything goes well.

I also noted that when I query a particular service I get the same error. I don't know why.

### Expected behavior

I should not get an error

### Reproduction steps

Create app with
`npx create-expo-app appname -t expo-template-blank-typescript`
install amplify with these instructions:
[https://docs.amplify.aws/react-native/start/getting-started/setup/#create-a-new-project](url)

Use the schema included in this post.
Record an object using the function included in this post.

### Project Identifier

90e248fdd5b64aad8ace95f42eba4110

### Log output

<details>

```
# Put your logs below this line
"Cannot return null for non-nullable type: 'AWSDateTime' within parent 'Category' (/createService/category/createdAt)" "Cannot return null for non-nullable type: 'AWSDateTime' within parent 'Category' (/createService/category/updatedAt)

```

</details>

### Additional information

This is my schema:
```
type Category @model 
  @auth(rules: [{ allow: public, operations: [read, update, create] }, { allow: owner, operations: [read, update, create] }]) {
  id: ID!
  name: String!
  services: [Service] @hasMany
}
type Service @model 
  @auth(rules: [{ allow: public, operations: [read] }, { allow: owner }]) {
  id: ID!
  category: Category @belongsTo
  title: String!
  description: String!
  price: Int!  
  seller: Seller @hasOne  
}
```

And this is how I'm recording into the db:
```
const addJob = async() => {
        // const cardId = uuid();
        setLoading(true);
        const jobDetails: CreateServiceInput = {
            title: data.title,
            description: data.description,
            price: parseInt(data.price),
            sellerServicesId: userID,
            categoryServicesId: 'e4322408-91f1-7076-0e4f-e5a81dt602b6' 
        }
        try {
            const response = await client.graphql({
                query: createService,
                variables: { input: jobDetails},
                
            })
            console.log('response: ', response);
            // navigation.navigate('HomeScreen', {msg:'added'});
        } catch (error : any) {
            console.log('error: ', error)
            // Alert.alert(error?.message)
        } finally {
            setLoading(false);
        }       
      }
```

Codegen auto generates this function thats being used by addJob function:
```
[Unable to insert an item with Graphql](https://stackoverflow.com/questions/78369304/unable-to-insert-an-item-with-graphql)
```

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by phani-srikar** [comment]
Hi @Themrpie, can you check that the `Category` record with id `e4322408-91f1-7076-0e4f-e5a81dt602b6` that the `Service` belongs to, has `createdAt` and `updatedAt` fields set by querying it?
