### ISSUE TITLE
Amplify Graphql API error

### ISSUE THREAD

**Issue by manjumallesh1** [aws-amplify/amplify-category-api#2503]
Hi,

We are facing the following error after recent Amplify push. There is no data returned from Appsync Graphql APIs. 

query MyQuery {
  listBatteryTypes {
    items {
      id
    }
  }
}

Response

{
  "data": {
    "listBatteryTypes": null
  },
  "errors": [
    {
      "path": [
        "listBatteryTypes"
      ],
      "data": null,
      "errorType": "MappingTemplate",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Value for field '$[operation]' not found."
    }
  ]
}

**Comment by biller-aivy** [comment]
@manjumallesh1 i guess the team needs more info. 
Which version of the cli? 

Maybe you could post your generated resolver?

**Comment by AnilMaktala** [comment]
Hi  @manjumallesh1 👋,  thanks for raising this issue.we are working on reproducing the issue. Could you please run below command and send us the report .
`amplify diagnose --send-report`.
please refer [here](https://docs.amplify.aws/cli/reference/diagnose/)

**Comment by manjumallesh1** [comment]
@AnilMaktala  - thanks for looking into this

CLI version 12.11.1

Project Identifier: edc573327dd31dc69d57250ee36b5cfb

**Comment by manjumallesh1** [comment]
> @manjumallesh1 i guess the team needs more info. Which version of the cli?
> 
> Maybe you could post your generated resolver?

## [Start] Get Request template. **
#set( $GetRequest = {
  "version": "2018-05-29",
  "operation": "Query"
} )
#if( $ctx.stash.metadata.modelObjectKey )
  #set( $expression = "" )
  #set( $expressionNames = {} )
  #set( $expressionValues = {} )
  #foreach( $item in $ctx.stash.metadata.modelObjectKey.entrySet() )
    #set( $expression = "$expression#keyCount$velocityCount = :valueCount$velocityCount AND " )
    $util.qr($expressionNames.put("#keyCount$velocityCount", $item.key))
    $util.qr($expressionValues.put(":valueCount$velocityCount", $item.value))
  #end
  #set( $expression = $expression.replaceAll("AND $", "") )
  #set( $query = {
  "expression": $expression,
  "expressionNames": $expressionNames,
  "expressionValues": $expressionValues
} )
#else
  #set( $query = {
  "expression": "id = :id",
  "expressionValues": {
      ":id":     $util.parseJson($util.dynamodb.toDynamoDBJson($ctx.args.id))
  }
} )
#end
$util.qr($GetRequest.put("query", $query))
#if( !$util.isNullOrEmpty($ctx.stash.authFilter) )
  $util.qr($GetRequest.put("filter", $util.parseJson($util.transform.toDynamoDBFilterExpression($ctx.stash.authFilter))))
#end
$util.toJson($GetRequest)
## [End] Get Request template. **

**Comment by phani-srikar** [comment]
@manjumallesh1, since the error looks very much like [this other issue](https://github.com/aws-amplify/amplify-category-api/issues/2507) where you described that you have manually deleted and re-added the DDB table, can you confirm that this  started happening after you took those actions?

**Comment by AnilMaktala** [comment]
Hey @manjumallesh1, Are you still experiencing this issue?

**Comment by manjumallesh1** [comment]
Hi Anil,

We were able to resolve the issue. Thanks!
________________________________
