### ISSUE TITLE
Self-referencing relationships gives error, hasMany self referencing

### ISSUE THREAD

**Issue by MarlonJD** [aws-amplify/amplify-category-api#2534]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v21.5.0

### Amplify CLI Version

1.0.1

### What operating system are you using?

MacOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

When I try to create self-referenced models, it gives error:

Model:

```
Task: a
  .model({
    content: a.string(),
    parentId: a.id(),
    parent: a.belongsTo('Task', "parentId"),
    children: a.hasMany('Task', "parentId"),
  }).authorization((allow) => [allow.guest()]),
```

Error on `npx ampx sandbox`

```
Failed to instantiate data construct
Caused By: Uni-directional relationships are not supported. Add a @belongsTo field in Task to match the @hasMany field Task.children

Resolution: See the underlying error message for more details.
```

### Expected behavior

It should work properly, it was working before update

### Reproduction steps

Create Task model with these:

```
Task: a
  .model({
    content: a.string(),
    parentId: a.id(),
    parent: a.belongsTo('Task', "parentId"),
    children: a.hasMany('Task', "parentId"),
  }).authorization((allow) => [allow.guest()]),
```

and try to generate models `npx ampx sandbox`

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi @MarlonJD, Thank you for raising this. We can replicate the issue by using the Schema in the description. Hence, Marking this as a bug for the team to evaluate further.

<img width="979" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/e968c791-d353-4bb8-a665-f8b76fdc0011">

**Comment by MarlonJD** [comment]
Here are the more info about the versions, thanks @JonasRothSwinx for clarification about this.

```The new versions, where this relationship caused issues:
"@aws-amplify/backend": "^0.13.4"
"@aws-amplify/backend-cli": "^0.12.1"

The previously working beta:

"@aws-amplify/backend": "^0.13.0-beta.20",
"@aws-amplify/backend-cli": "^0.12.0-beta.22",
```

BTW, It seems it's related to gen2 amplify-backend repo, is this good idea to create issue on https://github.com/aws-amplify/amplify-backend ?

**Comment by AnilMaktala** [comment]
@MarlonJD This repository is the correct one for addressing this issue.

**Comment by MarlonJD** [comment]
PR #2533 should fix this issue, I'll close when it released, thanks!

**Comment by renebrandel** [comment]
Confirming this is released.
