### ISSUE TITLE
Feature Request: Ability to Disable Autogenerated GraphQL Queries and Mutations for Models in Gen 2

### ISSUE THREAD

**Issue by thomasoehri** [aws-amplify/amplify-category-api#2559]
### Describe the feature you'd like to request

In Gen 1, it was possible to disable specific autogenerated GraphQL queries and mutations for a model. For example, the following code snippet effectively disables all queries, mutations, and subscriptions for the Todo model:

```
type Todo @model(queries: null, mutations: null, subscriptions: { level: off }) {
  // fields
}
```

I would like to have a similar functionality in Gen 2, allowing us to disable autogenerated GraphQL queries, mutations, and subscriptions for individual models.

Consider a scenario where you have an `Organization` model and you need to add additional business logic to the autogenerated `createOrganization` mutation resolver. I would imagine that every project runs into the need to add additional business logic sooner or later other than simple demo apps. Right now the only way to do that would be to create a custom resolver that we need to name differently from the autogenerated one, so for example `customCreateOrganization`. Now we have our desired mutation resolver and business logic but when a developer looks at the schema there are two mutations that seemingly do the same thing, the `createOrganization` and `customCreateOrganization` mutations. You have to know you need to use the `customCreateOrganization` mutation otherwise you would obviously go for the `createOrganization` mutation. And here we are faced with another challenge: i need to enforce that you're only able to create organizations using the custom resolver because the custom business logic in there is essential. That means i need to somehow make it impossible to use the autogenerated `createOrganization` mutation using authorization rules, so that only the custom `customCreateOrganization` mutation can be used. I think you get the idea.

There are multiple possible solutions to this problem, which all of them were possible in Gen 1:
- Be able to override/extend the autogenerated queries/mutations like we were able to in Gen 1: https://docs.amplify.aws/gen1/javascript/build-a-backend/graphqlapi/custom-business-logic/#override-amplify-generated-resolvers
- Allow custom resolvers to be named the same as the autogenerated ones (in my case name the custom resolver `createOrganization` so that the autogenerated one is overwritten with the custom one
- Add the ability to explicitly disable queries/mutations for models so that i can create a custom resolver that is correctly named

At least for me this currently is a show-stopper when it comes to using Gen 2 for production apps, which is a shame because i really really like the new Gen 2 way of doing things. Currently, the need to fiddle with authorization rules to prevent the autogenerated resolvers from being used and still ending up with a complicated schema full of queries/mutations that can't be used as well as not-so optimal naming is not that nice.

### Describe the solution you'd like

I'd like to have a similar method in Gen 2 to disable specific autogenerated GraphQL queries, mutations, and subscriptions for any given model. This would provide the same level of control that was available in Gen 1.

Maybe it could look something like this:

```
Organization: a.model({
    id: a.id().required(),
    name: a.string().required()
  }).queries({ list: null, get: 'getOrganization' })
    .mutations({ create: null, update: null, delete: 'deleteOrganization' })
    .subscriptions({ level: 'off' })
```

### Describe alternatives you've considered

I've looked through the official documentation, GitHub issues, and discussions on Discord, but I haven't found any current method to achieve this in Gen 2.

### Additional context

I asked on Discord if this is possible and was told that it currently is not, and to create a feature request here: https://discord.com/channels/705853757799399426/1240329133301563452

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by AnilMaktala** [comment]
Hi @thomasoehri, Thank you for raising this. We are marking this as a feature request for the team to evaluate further.

**Comment by thomasoehri** [comment]
Another use-case i've had with Gen 1 apps where i've utilized the ability to disable autogenerated GraphQL queries and mutations was adding models that i didn't want to expose via the GraphQL API and exclusively use in the backend via custom resolvers. For example translation functionality where i've added a `OrganizationTranslation` model with all queries/mutations turned off:

```
type OrganizationTranslation
  @model(queries: null, mutations: null, subscriptions: { level: off }) {
  organizationID: ID! @primaryKey(sortKeyFields: ["languageCode"])
  languageCode: String!
  name: String
  introduction: AWSJSON
  introductionRaw: String
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}
``

This way i was able to look up and serve the translated version of an organization when someone called the `getOrganization` query using a custom resolver without exposing the OrganizationTranslation model in the API. How would you do that in Gen 2? The only thing i can think of is creating a DynamoDB table for `OrganizationTranslation` via the CDK but it would be way nicer to just be able to define the model in the schema without exposing any queries/mutations to the GraphQL API and having an overview of the entirety of the application from there. Giving permissions to the `OrganizationTranslation` model from functions and resolvers would be way nicer too instead of having to create everything custom through the CDK.

**Comment by MarlonJD** [comment]
It can also solve resource limit issue

**Comment by naedx** [comment]
Hi All. I'm also interested in this feature. I need to implement pipeline resolvers to enforce custom business logic.

At worst, not having the ability to disable (and/or override) the generated resolvers exposes applications to a **security risk** by allowing users to have access to the generated basic resolvers that could circumvent the implemented business logic. Developers creating custom resolvers may unknowingly be exposed to this. 

Working around it by creating the table in CDK means:

1. Developers are now responsible for all the resolvers (even if they only wanted to affect one operation)
2. By doing so we lose the benefit of the improved Gen2 DX.

**Comment by naedx** [comment]
We also need to be able to disable **Subscriptions** for the same reason.

**Comment by AnilMaktala** [comment]
Hey @thomasoehri,  One potential solution is to implement custom authorization, allowing you to block access to all queries and mutations. Let me know if this approach works for you. For instructions on setting up custom authorization, please refer to this [section](https://docs.amplify.aws/react/build-a-backend/data/customize-authz/custom-data-access-patterns/)

**Comment by naedx** [comment]
Hey @AnilMaktala , thanks for looking at this ! 

I'm also affected by this issue. In my case, using a lambda authorizer would be a last resort workaround while waiting for a solution as this would introduce unnecessary costs for the lambda service while still having a larger than necessary attack surface to monitor and maintain.

**Comment by thomasoehri** [comment]
Hi @AnilMaktala, thank you for addressing this!

Using authorization rules or implementing custom authorization only mitigates one aspect of the issue.
This way there still are a lot of queries & mutations in my GraphQL schema that are of no use, cause naming conflicts and above all complicate the developer experience. 

Not only do i need to write my usual authorization rules for my "wanted" custom queries/mutations, i also need to look after the unwanted, autogenerated ones.

A Gen 2 solution, similar to what we had in Gen 1, would resolve these issues.

```
type Todo @model(queries: null, mutations: null, subscriptions: { level: off }) {
  // fields
}
```

I'd be able to remove the autogenerated queries/mutations i don't need, create my custom ones, my schema would only contain queries/mutations that are actually usable, they would be named correctly and i wouldn't have to think about adding authorization rules / custom authorization logic to block access to unwanted queries/mutations.

**Comment by naedx** [comment]
I am currently exploring skipping `defineData()` and setting up my AppSync API with the [AmplifyData construct](https://constructs.dev/packages/@aws-amplify/data-construct/v/1.8.5?lang=typescript) instead to avoid having these dangling resolvers.

**Comment by thomasoehri** [comment]
Hi all, it now seems to be possible to disable automatically generated queries/mutations/subscriptions for models using `.disableOperations`, which is great news!

```
Organization: a.model({
    id: a.id().required(),
    name: a.string().required()
  })
  .disableOperations(["get", "create"])


// All operations that can be disabled:
export type DisableOperationsOptions = 'queries' | 'mutations' | 'subscriptions' | 'list' | 'get' | 'create' | 'update' | 'delete' | 'onCreate' | 'onUpdate' | 'onDelete';
```

I have just tested this and i'm able to disable the auto-generated query/mutation and replace it using my custom query/mutation which i'm now able to name correctly. No more duplicate queries/mutations, naming conflicts and using authorization rules to render unwanted auto-generated queries/mutations useless 😃 

Thanks to the Amplify team 👍
