### ISSUE TITLE
API Auth with Custom Groups

### ISSUE THREAD

**Issue by seang96** [aws-amplify/amplify-category-api#256]
**Describe the bug**
Custom groups lack the AuthRolePolicy generated in the API stack preventing these authed users from accessing what regular authed users can access. For example, Admin group can no longer perform subscriptions since their IAM role is different and lacks the AuthRolePolicy.

**Amplify CLI Version**
4.29.4

**To Reproduce**
Create a project with API AppSync with auth support with cognito as default, create Auth module with an admin group. Admin group users have a different IAM role that lacks permissions for the API.

**Expected behavior**
The group should inherit the policies from regular Auth users.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version. v12.16.3

**Additional context**
This can be problematic when using DataStore since it tries to pick auth methods based off of the auth transforms, if an IAM rule exists it will override from default auth provider of cognito. I think this is working as expected, just that the CLI does not give users in groups the same access of a regular authenticated user. Manually adding the policy to the Auth IAM role resolves the issue, but I would like a better solution.

Groups should have either the IAM role added automatically or for more advanced flows, if we could get the AuthRole policy as an output so we can use to create a custom resource to attach to groups on a as-needed basis.

**Comment by renebrandel** [comment]
Hi closing this out as we've multi-auth supprot since https://aws.amazon.com/blogs/mobile/aws-amplify-allows-you-to-mix-and-match-authorization-modes-in-datastore/
