### ISSUE TITLE
The DynamoDB BatchWriteItem limits apply and no condition expression can be provided.

### ISSUE THREAD

**Issue by sevenkkk** [aws-amplify/amplify-category-api#2561]
### Amplify CLI Version

 @aws-amplify/backend: 1.0.2   @aws-amplify/backend-cli: 1.0.3

### Question

`import { util } from '@aws-appsync/utils';

export function request(ctx) {
  const { authorId, postId } = ctx.args;
  return {
    operation: 'BatchDeleteItem',
    tables: {
      authors: [util.dynamodb.toMapValues({ authorId })],
      posts: [util.dynamodb.toMapValues({ authorId, postId })],
    },
  };
}`

Request error information based on documentation examples：
"User: arn:aws:sts::781146907752:assumed-role/CategoryIAMRolec8bbaa-lax54cmwzndbng7nzoddgslwiy-NONE/APPSYNC_ASSUME_ROLE is not authorized to perform: dynamodb:BatchWriteItem on resource: arn:aws:dynamodb:ap-northeast-1:781146907752:table/Category because no identity-based policy allows the dynamodb:BatchWriteItem action (Service: DynamoDb, Status Code: 400, Request ID: P68MQNI79F2DAEVM0R2JDPV82VVV4KQNSO5AEMVJF66Q9ASUAAJG)

Although I saw this prompt

【The DynamoDB BatchWriteItem limits apply and no condition expression can be provided.】

Please tell me what to do?

**Comment by sundersc** [comment]
For the first issue related to the `* is not authorized to perform: dynamodb:BatchWriteItem on resource:*`, the default IAM role created by Amplify has permission to `BatchWrite` and it is scoped down to a single table. You can find this IAM under AppSync API's datasources. Please take a look at the IAM policies and make sure it allows the below actions.

```json
         "Action": [
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
                "dynamodb:ConditionCheckItem",
                "dynamodb:DeleteItem",
                "dynamodb:DescribeTable",
                "dynamodb:GetItem",
                "dynamodb:GetRecords",
                "dynamodb:GetShardIterator",
                "dynamodb:PutItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:UpdateItem"
            ]
```

Also, your resolver will run against a single datasource. If you are running it against `AuthorTable` datasource, the IAM policy associated to that datasource will not have access to `posts` table.

For the second issue, condition expression is not allowed on batch write.
https://github.com/aws/aws-sdk-js/issues/4018

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
