### ISSUE TITLE
Resource is not in the state stackUpdateComplete

### ISSUE THREAD

**Issue by DrBallHard** [aws-amplify/amplify-category-api#2567]
I've encountered this a few times, and haven't found a solution for it yet. First few times, I believe the issue was with updating Amplify API. Checking in on Cloudformation, it were a couple of the model stacks that were unable to update. I ended up just creating a new enviornment and pushing the code there and things seem to be okay on that end for now. 
I tried adding Storage to my Amplify project and this resulted in the same error. This time if I check on Cloudformation, the 'UPDATE_ROLLBACK_COMPLETE' issue is happening with auth pool groups and auth. 

![Screenshot 2024-05-18 173531](https://github.com/aws-amplify/amplify-category-api/assets/11314211/83c17868-45d7-4eb7-98e6-1f851c127835)

I've attached screenshots of Cloudformation, and I also have the full error message from the cli, but am not sure if it's too sensitive to share. How do I resolve this issue as it pertains to adding storage as well as in general? I've come across the stackUpdateComplete several times and just don't know how to handle it.

**Comment by sundersc** [comment]
@DrBallHard - When you receive `Resource is not in the state stackUpdateComplete` error, usually the actual error is different and hidden somewhere in the stack events. Could you look at the failed stack events in CFN console and see if you can find any more details about the actual error?

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
