### ISSUE TITLE
groupsField ignored with Graphql

### ISSUE THREAD

**Issue by fistofzen** [aws-amplify/amplify-category-api#2582]
### Amplify CLI Version

12.12.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

Hello,
I have a type 
```
type Exercise @model  @auth(rules: [{ allow: groups, groupsField: "group" }]) {
...
...
group: String!
}
```
and I have a record on Exercises where the group is set to "Subscribed".

When I add or remove the user to the "Subscribed" I didnt see any change in the resultset.

### Expected behavior

Dynamic group authorization: When you want to restrict access to a set of user groups

### Reproduction steps

1 . Get list of items
2 . see the result where user is added to group.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hey  @fistofzen, The generated token includes the allowed groups at the time of login. Have you tried verifying it after logging out and then logging back in?

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
