### ISSUE TITLE
AWS Amplify Gen 2 Data Set field-level authorization rule

### ISSUE THREAD

**Issue by concavegit** [aws-amplify/amplify-category-api#2589]
### Amplify CLI Version

1.0.3

### Question

I have a schema like
```
const schema = a.schema({
  MyModel: a.model({
    // I would like this field to be read-only and not allow create
    myFirstField: a.enum(["a", "b"]),
    mySecondField: a.string()
}).authorization((allow) => [allow.owner().to(["create"])]);
```

However, `a.enum` does not support `.authorization`, so I don't think I can set a field-level authorization rule for `myFirstField`. Is that correct? If so, can we make this a feature request?

**Comment by concavegit** [comment]
Thanks @AnilMaktala, that works. Is defining `enumField` in the schema instead of directly in the model the expected usage pattern, or is this a workaround?

**Comment by AnilMaktala** [comment]
Hey @concavegit , Thanks for confirming. This is the recommended way to use it. However, I will review it with the team and provide an update here.

**Comment by concavegit** [comment]
Thanks AnilMaktala! I'll update my model accordingly.
