### ISSUE TITLE
Add Array Support to CustomType in Gen2 Data Model

### ISSUE THREAD

**Issue by imers** [aws-amplify/amplify-category-api#2590]
### Environment information

```plain text
n/a
```

### Description

**Problem**
Currently, the Gen2 data model supports customType or string array, but it does not support an array of customType. This limitation restricts the flexibility of the data models and complicates the design of schemas that require arrays of custom objects.

**Proposed Solution**
I would like the Amplify backend to support arrays of customType in the Gen2 data model. This enhancement will enable developers to define more complex and nested data structures directly within the schema.

**Alternatives**
Using JSON fields to store arrays of custom objects, which requires additional parsing and validation logic in the client-side code.
Creating multiple fields to simulate an array of custom objects, which is not scalable and increases schema complexity.
Additional context
Supporting arrays of customType will align the Gen2 data model with more advanced use cases and will greatly enhance the flexibility and power of the data modeling capabilities within Amplify. This feature will also reduce the need for workarounds that can introduce additional complexity and potential for errors.

Thank you for considering this feature request.

**Comment by chrisbonifacio** [comment]
Hi @imers , this should be implemented already. Have you tried setting the type like the `locations` field on this schema?

```ts
  Location: a.customType({
    lat: a.float().required(),
    long: a.float().required(),
  }),
  Todo: a
    .model({
      name: a.string().required(),
      description: a.string(),
      completed: a.boolean().default(false),
      locations: a.ref("Location").array(), // <-------
      type: a.ref("MyType").authorization((allow) => [allow.authenticated()]),
    })
    .authorization((allow) => [allow.publicApiKey()]),
```

**Comment by volludev** [comment]
> Hi @imers , this should be implemented already. Have you tried setting the type like the `locations` field on this schema?
> 
> ```ts
>   Location: a.customType({
>     lat: a.float().required(),
>     long: a.float().required(),
>   }),
>   Todo: a
>     .model({
>       name: a.string().required(),
>       description: a.string(),
>       completed: a.boolean().default(false),
>       locations: a.ref("Location").array(), // <-------
>       type: a.ref("MyType").authorization((allow) => [allow.authenticated()]),
>     })
>     .authorization((allow) => [allow.publicApiKey()]),
> ```
> 
> Unless you mean `a.customType().array()`? In which case using `a.ref("CustomType").array()` is an intentional design choice.

Hi @imers, for me the example that @chrisbonifacio posted works just fine. I actually have data added like that with a few different models linking to arrays of different customTypes. Maybe show an example of your schema?

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
