### ISSUE TITLE
Variable is already defined in class

### ISSUE THREAD

**Issue by TrekSoft** [aws-amplify/amplify-category-api#260]
If a user puts a property in their GraphQL schema in all caps the Java code generation creates a conflict between the ModelField variable name and the QueryField variable name because they are both named identically. This would be a breaking change to fix so perhaps we need to just document that we don't support all caps type fields but wanted to raise the issue here to discuss.

**Comment by josefaidt** [comment]
Closing as this issue is now resolved with https://github.com/aws-amplify/amplify-cli/pull/5500
