### ISSUE TITLE
AppSync  transform violates DynamoDB rules for sparse index for GSI

### ISSUE THREAD

**Issue by arkllc** [aws-amplify/amplify-category-api#262]
DynamoDB spec allows the GSI sort key to be null. The AppSync transform however forces it to be non-null. This was working fine until 4.18.0 but the bug was introduced thereafter. 

Please refer to DynamoDB documentation here - https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.html

Here is the section on the page -
"A global secondary index only tracks data items where its key attributes actually exist. For example, suppose that you added another new item to the GameScores table, but only provided the required primary key attributes.
Because you didn't specify the TopScore attribute, DynamoDB would not propagate this item to GameTitleIndex. Thus, if you queried GameScores for all the Comet Quest items, you would get the following four items. A similar query on GameTitleIndex would still return three items, rather than four. This is because the item with the nonexistent TopScore is not propagated to the index."

Also some other documentation here https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-indexes-general-sparse-indexes.html

**Amplify CLI Version**
Introduced in versions after 4.18.0

**Additional context**
I had created another [issue 4413](https://github.com/aws-amplify/amplify-cli/issues/4413) but there was no response for a long time. I am stuck until this is implemented hence I created another bug to help get attention.

All the details are in the issue link above.

**Comment by renebrandel** [comment]
Closing - confirming Ross' statements above.
