### ISSUE TITLE
[gen2] ampx generate schema-from-database fails to parse connection string

### ISSUE THREAD

**Issue by dhenze** [aws-amplify/amplify-category-api#2624]
### If applicable, what version of Node.js are you using?

v18.19.0

### Amplify CLI Version

`amplify version`: 12.10.1 (though irrelevant, isn't it?)

`npx ampx info` (partial output)
NPM Packages:
  @aws-amplify/backend: 1.0.3
  @aws-amplify/backend-cli: 1.0.4
  aws-amplify: 6.3.6
  aws-cdk: 2.145.0
  aws-cdk-lib: 2.145.0
  typescript: 5.4.5

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No, only created a RDS Postgres instance, connected to it via Cloud9 terminal and created the table structure for my application.

### Describe the bug

I followed the steps outlined in https://docs.amplify.aws/javascript/build-a-backend/data/connect-to-existing-data-sources/connect-postgres-mysql-database/#step-1---set-secrets-for-database-connection to generate a schema from database. 

Step 1: set the secret to the postgres connection string:
`npx ampx sandbox secret set SQL_CONNECTION_STRING` (
Note: the same connection string worked before already fine from the Cloud9 terminal with psql command

Step 2: generate the schema from the SQL;
`npx ampx generate schema-from-database --connection-uri-secret SQL_CONNECTION_STRING --debug`

Unfortunately this fails with the below error of not being able to parse the connection string. I have added observations from an initial investigation in the fields below (additional information)

```
npx ampx info
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M1
  Memory: 193.13 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn: 1.22.21 - /opt/homebrew/bin/yarn
  npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.3
  @aws-amplify/backend-cli: 1.0.4
  aws-amplify: 6.3.6
  aws-cdk: 2.145.0
  aws-cdk-lib: 2.145.0
  typescript: 5.4.5
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Expected behavior

I expected the schema file to be generated at the default path, but instead received an error as shown:

```
DatabaseUrlParseError: Unable to parse the database URL. Invalid URL
Resolution: Check if the database URL is correct and accessible.
[DEBUG] 2024-06-13T08:58:07.248Z: DatabaseUrlParseError: Unable to parse the database URL. Invalid URL
    at parseDatabaseUrl (file:///Users/danielhenze/workspace/event_survey/node_modules/@aws-amplify/schema-generator/lib/generate_schema.js:80:15)
    at SchemaGenerator.generate (file:///Users/danielhenze/workspace/event_survey/node_modules/@aws-amplify/schema-generator/lib/generate_schema.js:9:26)
    at Object.handler (file:///Users/danielhenze/workspace/event_survey/node_modules/@aws-amplify/backend-cli/lib/commands/generate/schema-from-database/generate_schema_command.js:43:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

<img width="1081" alt="Bildschirmfoto_2024-06-12_um_15 39 16" src="https://github.com/aws-amplify/amplify-category-api/assets/638964/9b4dd913-7fda-4ac5-a087-9f43b71d0a17">

### Reproduction steps

1. setup gen2 amplify project
2. Setup RDS instance 
3. Make it publically available
4. Set the connection string `npx ampx sandbox secret set SQL_CONNECTION_STRING` to something in format `postgres://user:password@my.rds.instance:5432/database`
5. Run `npx ampx generate schema-from-database --connection-uri-secret SQL_CONNECTION_STRING --debug`

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I have checked the code at /node_modules/@aws-amplify/schema-generator/lib/generate_schema.js:80:15 and found that it's decomposing the string using the URL class (I guess it is this one: https://nodejs.org/api/url.html#url). 
Reproduced the code calls in a Browser console and it does not seem to be working as intended as shown in this example (see missing details, e.g. username, password):

```
const parsedDatabaseUrl = new URL("postgres://user:password@localhost.host:5432/eventsurvey_dev");

parsedDatabaseUrl
URL {origin: 'null', protocol: 'postgres:', username: '', password: '', host: '', …}
hash: ""
host: ""
hostname: ""
href: "postgres://user:password@localhost.host:5432/eventsurvey_dev"
origin: "null"
password: ""
pathname: "//user:password@localhost.host:5432/eventsurvey_dev"
port: ""
protocol: "postgres:"
search: ""
searchParams: URLSearchParams {size: 0}
username: ""
```

Note: When I change the protocol from postgres to https everything is properly recognised and I do get the values properly assigned

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by sundersc** [comment]
@dhenze I ran the same script in node and see the URL values are parsed correctly.
![image](https://github.com/aws-amplify/amplify-category-api/assets/83315412/e104ca21-a0fe-41f7-8d0c-1c443bc6f808)

I also see that if I do the same in browser console, I get the same result as you. Looks like there is a difference in behavior between node and javascript modules.

The command is intended to be used in node environment. Can you run the parse in node env and see if it is parsing the values correctly?

**Comment by dhenze** [comment]
@sundersc I can confirm that the node version of the script does work as intended with my test string:

```
{
  engine: 'postgres',
  username: 'user',
  password: 'password',
  database: 'eventsurvey',
  host: 'some.rds.instance.aws.eu',
  port: 5432
}
```

Testing it with my RDS instance connection string though fails. 

So I started tinkering with it and got it working when I removed the two `#` contained in the password. I can reproduce the error consistently adding a `#` to the password. Actually any part of the string, but password is the only where I would see it being applied.

Failing connections sting: `postgres://postgres:passwith#@some.rds.instance.url:5432/eventsurveys`
Working connection string: `postgres://postgres:passwith@some.rds.instance.url:5432/eventsurveys`

**Comment by chrisbonifacio** [comment]
Ah, that's happened to me before with the autogenerated passwords. There's a setting on the rds instance that lets you exclude specific characters from the secret. If the password is going to include special characters it needs to be URL encoded in the connection string.

**Comment by dhenze** [comment]
@AnilMaktala thanks for your support and looking into it, helping me to look the right direction. 

I do disagree with the decision to close it as I see the workaround in changing a password and possibly weakening password policies as a defect still. The password was autogenerated by the managing RDS service using best practice password policies. I do see amplify as a tool to simplify the usage of AWS services, having to go and workaround other services feels not just counterintuitive, but potentially dangerous. By using libraries that force to downgrade our security measurements there is a theoretical potential to undermine a whole system, e.g. by intentionally supporting a reduced character set.

At the same I do understand you cannot maintain control over everything, but I wanted to leave this thought and am good either way. Could there be a workaround around this, by for example automatically escaping unsupported characters or at least creating a more meaningful error message so that the user has an easier time finding the root cause? For example the debug option could output the config object.

**Comment by sundersc** [comment]
@dhenze - There is no need to restrict the character set or change the password. URL encode the password component and use it in the connection string. From your example: instead of `passwith#`, use `passwith%23`.

```js
const encodedPassword = encodeURIComponent(password);
// password:        password#
// encodedPassword: password%23 
```
