### ISSUE TITLE
Amplify could not fetch data on SSR in Nuxt 3.

### ISSUE THREAD

**Issue by jewells07** [aws-amplify/amplify-category-api#2629]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.14.0

### Amplify CLI Version

12.12.2

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I wanted to fetch data on SSR in Nuxt 3. I have followed the AWS amplify Gen-2 Nuxt 3 document. 
(https://docs.amplify.aws/vue/build-a-backend/data/set-up-data/) & 
(https://docs.amplify.aws/vue/build-a-backend/server-side-rendering/nuxt/).
```
Amplify Data resource  schema:

  Todo: a
    .model({
      content: a.string(),
      isDone: a.boolean(),
    })
    .authorization((allow) => [allow.publicApiKey()]),

--------
Nuxt 3 : 

<template>
  <div>
    <h3>Todos</h3>
    <pre>{{ data }}</pre>
    <br />
    <pre>{{ error }}</pre>
  </div>
</template>

<script setup lang="ts">
const { data, error } = useAsyncData(async () => {
  const { data, errors } = await useNuxtApp().$Amplify.GraphQL.client.models.Todo.list();
  console.log('data', data);
  console.log('errors', errors);
  return data;
});
</script>

It gives the data on sever-side. It works fine.
```

When i add authentication 

```
Amplify Data resource  schema:

  Todo: a
    .model({
      content: a.string(),
      isDone: a.boolean(),
    })
    .authorization((allow) => [allow.authenticated()]),
   
--------
Nuxt 3 :  
    const { data, error } = useAsyncData(async () => {
  const { data, errors } = await useNuxtApp().$Amplify.GraphQL.client.models.Todo.list({
    authMode: 'userPool',
  });
  console.log('data2', data);
  console.log('errors', errors);
  return data;
});

It is not working on sever-side. Even when I'm logged in.
```
It force me to do this

```
....).authorization((allow) => [allow.authenticated(), allow.owner(), allow.group('Admin')]),
```

----**Note**---
It does not working on Sever side. It works when I change some code and save the file.

### Expected behavior

It should work in Sever side when i fetch the data

### Reproduction steps

![image](https://github.com/aws-amplify/amplify-category-api/assets/54440548/1b0cce3a-f683-4069-98ba-34a72ff6a2b7)
Here, you can see that on the server side, I don't get any data. After making changes to the code and saving the file, it shows the data.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hey @jewells07, Thanks for raising this. We have a followup question. When you say server side, are you referring AppSync console?  Also, did you wait till the sandbox to complete the deployment before verifying the changes?

**Comment by jewells07** [comment]
> Hey @jewells07, Thanks for raising this. We have a followup question. When you say server side, are you referring AppSync console? Also, did you wait till the sandbox to complete the deployment before verifying the changes?


Severe side rendering in Nuxt 3, that's what I meant. As in the screenshot, we can see we don't get data, and the model has authentication. but it works in onMounted (nuxt 3) but not in severe side rendering.

**Comment by chrisbonifacio** [comment]
Hi @jewells07 I don't think the `client.models` API will work on the server side. In the documentation, you might notice that the client configuration generates the client with the Schema like so:

```ts
// nuxt-amplify-gen2/plugins/01.amplify-apis.client.ts

const client = generateClient<Schema>();
```

But on the server, it is configured without the Schema:

```ts
// nuxt-amplify-gen2/plugins/01.amplify-apis.client.ts
const client = generateClient<Schema>();
```

So, if you are trying to use `client.models` on the server-side, please use `client.graphql` instead.

Let me know if that helps!

**Comment by jewells07** [comment]
```
const { data, error } = useAsyncData(async () => {
  const { data, errors } = await $Amplify.GraphQL.client.graphql({
    query: listTodo,
    authMode: 'userPool',
  });
  console.log('data', data);
  console.log('errors', errors);
  return { data, errors };
});
```
```
<template>
  <div>
    <h3>Todos</h3>
    <pre>{{ data }}</pre>
    <br />
    <pre>{{ error }}</pre>
  </div>
</template>
```

 I got an error: ```$Amplify.GraphQL.client.graphql is not a function```

**Comment by chrisbonifacio** [comment]
@jewells07 apologies for the delay, are you still experiencing this issue? I noticed you have another more recent issue so I'm curious if you were able to get unblocked on this one.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
