### ISSUE TITLE
add-graphql-datasource does not add FK table connections

### ISSUE THREAD

**Issue by cookmscott** [aws-amplify/amplify-category-api#264]
**Describe the bug**
Running `amplify api add-graphql-datasource` against an Aurora DB that includes tables with PKs and FKs, does not create or respect table relationships/connections. 

**Amplify CLI Version**
4.29.1

**To Reproduce**
Follow guide from Amplify Docs [here](https://docs.amplify.aws/cli/graphql-transformer/relational)

1. Create a `Customers` table with FK to `Orders`. 
2. Run `amplify api add-graphql-datasource`
3. Inspect graphql.schema and note there are no {tableName}Connections

**Expected behavior**
Comment below from cli makes it seem as if PK and FK's are respected 
https://github.com/aws-amplify/amplify-cli/blob/735f7efac6214c54537babeb1fdfab0a2f7a59b0/packages/graphql-relational-schema-transformer/src/__tests__/AuroraServerlessMySQLDBReader.test.ts#L84-L95

However, you can see that no connections on PK and FK are respected in the generated graphql.schema (or resolvers):
```
type Orders {
  id: Int!
  customerId: Int!
  orderDate: AWSDateTime
}
```

It is mentioned by contributors in other issues that adding PK and FK's to table will respect the table relationships:
* https://github.com/aws-amplify/amplify-cli/issues/3120#issuecomment-573221241
* https://github.com/aws-amplify/amplify-cli/issues/4417#issuecomment-636988540

However, running through the [Amplify Guide](https://docs.amplify.aws/cli/graphql-transformer/relational) with supplied tables only creates graphql schema with queries specific to individual tables (no relations or connections). 

**Additional context**
I've created a [issue to update documentation](https://github.com/aws-amplify/docs/issues/2431) to help make this more clear for users trying to use `add-graphql-datasource` to incorporate their Aurora backends in their Amplify projects. But it seems as if maybe this isn't supported at all by the CLI. 

FWIW, a relational database is relational! What good is it to have access to individual tables... If it's a CLI issue, I would love to get it resolved. If there are additional steps required to setup these relationships (like manually creating your own resolvers) the documentation should state this. `add-graphql-datasource` is not very usable for Aurora without a clear way to ensure table relationships and connections are respected.

**Comment by renebrandel** [comment]
Hi - Thanks for raising this. Unfortunately, we don't have any immediate updates on the GraphQL Transformer v1 at this point.

We are looking to address this via this RFC to better support relational data sources as an immediate priority with GraphQL Transformer v2.

I would love to get your thoughts and feedback on that: https://github.com/aws-amplify/amplify-category-api/issues/815

**Comment by chrisbonifacio** [comment]
Closing this as the way to model relationships has changed with the `AmplifyGraphqlApi`'s support for connecting to existing SQL/PostgreSQL databases.

For more information, please refer to our documentation:

https://docs.amplify.aws/javascript/build-a-backend/graphqlapi/connect-api-to-existing-database/#pageMain

For more context, when generating a GraphQL schema from a SQL/PostgreSQL database schema as mentioned in the docs linked above, we do not use the foreign keys to generate relationships between tables.

If the database schema shows an index on a foreign-keyed field, we’ll use that index to generate an `@index directive` for that field in the graphql schema and associated queries.
