### ISSUE TITLE
How to remove the _version field from my schema and code?

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-category-api#2642]
### Amplify CLI Version

12.12.2

### Question

A looooot time ago we had DataStore running within our app until I ripped it out and burned it with fire. One of the left overs of that is I had _version fields on every model type and my mutations all needed to include the latest version every time.

Lately I've been questioning about how we can strip out the _version fields. As far as I know without DataStore being in the mix nothing else uses them of note but AppSync will honour the mutations only if the latest _version is included.

How can I go about safely removing the _version field from all my models and telling AppSync to not worry about it in my mutations?

**Comment by PeteDuncanson** [comment]
Found this doc https://docs.aws.amazon.com/appsync/latest/devguide/conflict-detection-and-sync.html which mentions the "tombstone" fields we use for deleted content (I like being able to pull back deleted content if needed).

Wonder if there is a way to keep that without needing the _version field?

Could be I could live without the _delete field too, just like that safety net!

Is it as simple as just unchecking this toggle per table? I suspect its not...

![image](https://github.com/aws-amplify/amplify-category-api/assets/1674590/7bef93f1-0d56-425e-8c39-c9d4b08e469a)

**Comment by AnilMaktala** [comment]
Hey @PeteDuncanson, thanks for raising this. You may try `amplify update api` and select **disable conflict detection** and see if it resolves your issue. Please test in the lower env before trying it in production environment.

**Comment by chrisbonifacio** [comment]
To add onto @AnilMaktala's answer, if you're working on a Gen 1 app I would recommend against making changes to Amplify generated/managed resources in the console. Best to make those changes using the Amplify CLI to avoid stack drift which can get quite difficult to resolve depending on the changes made.
