### ISSUE TITLE
[Gen2] model datetime type can not be used as sortKeys of secondaryIndexes

### ISSUE THREAD

**Issue by hangoocn** [aws-amplify/amplify-category-api#2657]
### Environment information

```plain text
System:
  OS: Windows 10 10.0.19045
  CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz 
  Memory: 15.16 GB / 31.84 GB
Binaries:
  Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
  npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.0
  @aws-amplify/backend-cli: 1.0.1
  aws-amplify: 6.2.0
  aws-cdk: 2.140.0
  aws-cdk-lib: 2.140.0
  typescript: 5.4.5
AWS environment variables:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
No CDK environment variables
```

### Data packages

```plain text
├─┬ @aws-amplify/backend-cli@1.0.1
│ └─┬ @aws-amplify/schema-generator@1.0.0
│   └── @aws-amplify/graphql-schema-generator@0.8.4
└─┬ @aws-amplify/backend@1.0.0
  └─┬ @aws-amplify/backend-data@1.0.0
    └── @aws-amplify/data-construct@1.8.1
```

### Description

What I want to do is to sort results by `createdAt`, so below is what I did:

Create a model with `datetime` field and add a secondaryIndex like this:
```
 Message: a
    .model({
      roomId: a.id().required(),
      createdAt: a.datetime(),
      content: a.string().required(),
    })
    .secondaryIndexes(index => [index('roomId').sortKeys(['createdAt']).queryField('listByDate')])
    .authorization(allow => [
      allow.owner(),
    ]),
```
then run the query in the app:
```
client.models.Message.listByDate({ roomId }, { sortDirection: 'DESC' }
```

It will then show error `Validation error of type UnknownType: Unknown type ModelAWSDateTimeKeyConditionInput`.

I also noticed two patterns when testing it in sandbox:
1. It is consistently reproducable when first remove other field like `content` from model, wait sandbox rebuild, then add it back
2. If now change `createdAt` type to string, it will start to work, and then you change it back to `datetime`, it also work.
3. Then you repeat step 1 above, it starts to not work again.

It always have the error when deploy to non-sandbox env.

I am not sure if this is correct way of sorting result by create time in gen 2, but this was what used to work in gen 1.

**Comment by chrisbonifacio** [comment]
I noticed you might not be using the latest versions of the `amplify` packages. Can you upgrade `aws-amplify`, `@aws-amplify/backend`, and `@aws-amplify/backend-cli` to `latest` and see if that resolves the issue?

**Comment by hangoocn** [comment]
Hi @chrisbonifacio , I have upgraded my packages to below:
```
System:
  OS: Windows 11 10.0.22631
  CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
  Memory: 15.67 GB / 31.84 GB
Binaries:
  Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
  npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.3
  @aws-amplify/backend-cli: 1.0.4
  aws-amplify: 6.3.8
  aws-cdk: 2.140.0
  aws-cdk-lib: 2.140.0
  typescript: 5.4.5
AWS environment variables:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
No CDK environment variables
```

but still able to see the same error, "Validation error of type UnknownType: Unknown type ModelAWSDateTimeKeyConditionInput"

The error is not always reproducable even on my side, but I can reproduce most of time.

May I know if 'ModelAWSDateTimeKeyConditionInput' is an expected type? I want to have a try to debug on the amplify source code

**Comment by chrisbonifacio** [comment]
can you check and share the version of `@aws-amplify/data-schema` and `@aws-amplify/data-schema-types` in your dependencies (or node_modules)?

**Comment by hangoocn** [comment]
I checked they are:
`@aws-amplify/data-schema`: 1.0.0
`@aws-amplify/data-schema-types`: 1.0.0

Even I install the latest of these files:
 "@aws-amplify/backend": "^1.0.4", 
 "@aws-amplify/backend-cli": "^1.1.0",

**Comment by chrisbonifacio** [comment]
You should be able to update them by running:

```shell
npm update @aws-amplify/data-schema @aws-amplify/data-schema-types
```

**Comment by hangoocn** [comment]
Thanks @chrisbonifacio it works!
