### ISSUE TITLE
Get data from another table in custom mutation

### ISSUE THREAD

**Issue by jewells07** [aws-amplify/amplify-category-api#2674]
### Environment information

```plain text
System:
  OS: Windows 11 10.0.22631
  CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Memory: 419.57 MB / 7.91 GB
Binaries:
  Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
  npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  pnpm: 9.3.0 - ~\AppData\Local\pnpm\pnpm.EXE
NPM Packages:
  @aws-amplify/backend: 1.0.3
  @aws-amplify/backend-cli: 1.0.4
  aws-amplify: 6.3.6
  aws-cdk: 2.145.0
  aws-cdk-lib: 2.145.0
  typescript: 5.4.5
AWS environment variables:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
No CDK environment variables
```

### Data packages

```plain text
nuxt-app@ D:\Todo\Todo
├─┬ @aws-amplify/backend-cli@1.0.4
│ └─┬ @aws-amplify/schema-generator@1.0.0
│   └── @aws-amplify/graphql-schema-generator@0.8.6
└─┬ @aws-amplify/backend@1.0.3
  └─┬ @aws-amplify/backend-data@1.0.2
    └── @aws-amplify/data-construct@1.8.5
```

### Description

Im using custom mutation with handler.

In **`data/resource.ts`**
```javascript
CreatingTodo: a.mutation()
  .arguments({
    content: a.string().required(),
  })
  .returns(a.ref('Todo'))
  .handler([
    a.handler.custom({
      entry: './Todo/createTodo.js',
      dataSource: a.ref('Todo'),
    }),
  ])
  .authorization((allow) => [allow.authenticated()]);
  ``` 
  
  In **`data/Todo/createTodo.js`**
```javascript
import { util } from '@aws-appsync/utils';
import * as ddb from '@aws-appsync/utils/dynamodb';

function getUserId(otherTableId) {
  const result = ddb.get({
    key: { id: otherTableId },
    tableName: 'OtherTable',
  });
  console.log('otherTableId', otherTableId);
  if (!result || !result.Item) {
    return 'null';
  }
  return result.Item.userId;
}

export function request(ctx) {
  const userId = getUserId(ctx.otherTable.id);
  const item = {
    ...ctx,
    userId,
    __typename: 'Todo',
  };
  const key = { id: util.autoId() };
  return ddb.put({ key, item });
}

export function response(ctx) {
  return ctx.result;
}
```
I am encountering an issue where it consistently returns **`'null'`**. How can I retrieve the userId from another table in a custom mutation? Additionally, I attempted to throw an error using **`return new Error('System not found');`**, but it did not work. I also tried adding async/await, but it appears to be unsupported. I attempted 
```javascript 
export function request(ctx) {
const userId = getUserId(ctx.otherTable.id);
if(!userId)
return util.appendError('Unable to get user ID', 'Invalid', {
      statusCode: 500,
    });
    }
    ....
    } 
   
export function response(ctx) { 
    if (ctx.error) {
    if (error) {
      return util.appendError(error.message, error.type, result, null);
    }
  }
  return result
  }
 ```
 but that did not resolve the issue either, which led me to add **`'null'`** as a string.

I have granted the necessary permissions for AppSync logs, but I do not see any logs in CloudWatch. I have explored every possible solution that I am aware of, but the problem persists.

**Comment by jewells07** [comment]
In this function

```javascript
function getUserId(otherTableId) {
  const result = ddb.get({
    key: { id: otherTableId },
    tableName: 'OtherTable',
  });
  console.log('otherTableId', otherTableId);
  if (!result || !result.Item) {
    return 'null';
  }
  return result.Item.userId;
}
```

 Actually it is a JavaScript resolver, not lambda

**Comment by dpilch** [comment]
Ah, makes sense. I don't think `@aws-appsync/utils/dynamodb` offers the functionality to set the `tableName` in `ddb.get`. I don't see this feature documented. I can check with the AppSync team to see if they offer this feature.

**Comment by jewells07** [comment]
Yes, I have tried using **`__typename: 'OtherTable'`**, and it does not work either. How can we perform CRUD operations on the other table within this mutation handler (JavaScript resolver)?

**Comment by dpilch** [comment]
The resolver can only be attached to a single data source. You will need to use a pipeline resolver to use multiple data sources. https://docs.aws.amazon.com/appsync/latest/devguide/pipeline-resolvers-js.html

It would look something like this:

```typescript
.handler([
  a.handler.custom({
    entry: './OtherTable/getUserID.js',
    dataSource: a.ref('OtherTable'),
  }),
  a.handler.custom({
    entry: './Todo/createTodo.js',
    dataSource: a.ref('Todo'),
  }),
])
```

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
