### ISSUE TITLE
Argument Type Error in Array Field

### ISSUE THREAD

**Issue by jewells07** [aws-amplify/amplify-category-api#2682]
### Amplify CLI Version

12.12.2

### Question

// Model
```javascript
Todo: a.model({
  content: a.string(),
  tags: a.string().array(),
})
```
// Nuxt 3 code.
I have created a plugin and can use $Amplify by following the steps in [this document](https://docs.amplify.aws/vue/build-a-backend/server-side-rendering/nuxt/#set-up-amplify-server-context-utility). **`Note`**: the link may redirect to Gen 1, but please check for Gen 2.
```javascript
  const { data, errors } = await $Amplify.GraphQL.client.models.Todo.get(
    {
      id: '123456',
    },
    {
      selectionSet: ['tags'],
      authMode: 'userPool',
    },
  );

  const isTag = data.tags.includes('SPORTS');
```
The following code displays the type error: **`Argument of type 'string' is not assignable to parameter of type 'string[]'.`** When I hover over data, I see **`readonly tags: string[][];`**. Why does it show a 2D array when I have **`tags: ['SPORTS', 'TECH', 'MARKETING']`**?

**Comment by chrisbonifacio** [comment]
Hi @jewells07 I was not able to reproduce this issue with the given schema and code snippet.

Here's a screenshot of the type when I hover over `data.tags`

![CleanShot 2024-07-11 at 00 22 22](https://github.com/aws-amplify/amplify-category-api/assets/16952986/273a16ba-bcb5-437c-b096-d2a0cd7eba5d)

And here's my [reproduction app](https://github.com/chrisbonifacio/nuxt-amplify-gen2/tree/issue2682) - the code is on the `issue2682` branch

I did run into some errors around types, not the exact one you ran into. I had to uninstall the `Vetur` extension in VSCode, restarting VSCode (not just extensions), and making sure all my amplify packages were up to date by running the following commands:

```sh
npm i @aws-amplify/backend@latest @aws-amplify/backend-cli@latest 
```

and 

```sh
npm update @aws-amplify/data-schema
```

**Comment by chrisbonifacio** [comment]
/
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
