### ISSUE TITLE
Real-Time Data Issue with Modeling Relationships

### ISSUE THREAD

**Issue by jewells07** [aws-amplify/amplify-category-api#2686]
### Amplify CLI Version

12.12.2

### Question

I'm trying to get real-time data using **`observeQuery`**. I have a **`Chat`** model that has a relationship with a **`Message`** model. However, I'm unable to fetch the real-time data when I use **`observeQuery`** on the **`Chat`** model. If I add **`observeQuery`** on the **`Message`** model, I can fetch the data, but this isn't ideal because the Message model contains a very large amount of data. Is there a way to effectively use **`observeQuery`** on the Chat model to get all related messages without dealing with the **`Message`** model's data?

I'm using **`Nuxt 3`**.

**`NOT WORKING`** 👇 
```javascript
$Amplify.GraphQL.client.models.Chat.observeQuery({
    filter: {
      id: { eq: chatId },
    },
    selectionSet: [
      'messages.id',
      'messages.content',
    ],
    authMode: 'userPool',
  }).subscribe({
    next: ({ items }) => {
      allMessages.value = [...items[0].messages];
    },
  });
```
**`WORKING`** 👇 
```javascript
$Amplify.GraphQL.client.models.Message.observeQuery({
    filter: {
      chatId: { eq: chatId },
    },
    selectionSet: ['id', 'content'],
    authMode: 'userPool',
  }).subscribe({
    next: ({ items }) => {
      allMessages.value = [...items];
    },
  });
```

**Comment by dpilch** [comment]
This may be expected and related to https://github.com/aws-amplify/amplify-category-api/issues/2609.

Please see the updates to the following docs:
* https://docs.amplify.aws/gen1/javascript/build-a-backend/graphqlapi/subscribe-data/ 
* https://docs.amplify.aws/gen1/javascript/tools/cli/reference/feature-flags/#subscriptionsInheritPrimaryAuth

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
