### ISSUE TITLE
Unable to override an autogenerated pipeline resolver

### ISSUE THREAD

**Issue by jguipi** [aws-amplify/amplify-category-api#2692]
### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v22.2.0

### Amplify CLI Version

12.12.4

### What operating system are you using?

mac os 14.5 (23F79)

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no manual change were made

### Describe the bug

This schema is generating an autogenerated pipeline resolver that I'm unable to override using the `amplify/backend/api/myapi/override.ts` 

schema.graphql 

```graphql
type User
  @model() {
  id: ID!
  firstname: String!
  lastname: String
  Children: [Child]
    @hasMany(indexName: "byUser", fields: ["id"])
}

type Child
  @model() {
  id: ID!
  firstname: String!
  lastname: String!
  userID: ID
    @index(name: "byUser")
  User: User
}
```

It seems like the key `User.Children` autogenerate, a resolver that I'm unable to override.

Override.ts
```js
  const getChild = resources.models['Child'];
  const getChild2 = resources.models['User'];

  console.log(getChild)
  const getChildResolvers =
    getChild.resolvers['queryGetChildResolver'].pipelineConfig['functions'];
  getChild.resolvers['queryGetChildResolver'].pipelineConfig = {
    functions: [
      function_1,
      function_2,
      function_3,
      ...getChildResolvers,
    ],
  };
```

When I log the following, I'm unable to see the autogenerated pipeline resolver in the data structure:
```
const getChild = resources.models['Child'];
or 
const getChild = resources.models['User'];
```

On the other hand, when I look at the AWS UI I'm able to see the autogenerated function 

<img width="648" alt="Captura de pantalla 2024-07-05 a la(s) 10 43 51 a m" src="https://github.com/aws-amplify/amplify-category-api/assets/11049349/619eaadd-0ef3-4d40-9387-8f9f7bc8e84e">
<img width="1514" alt="Captura de pantalla 2024-07-05 a la(s) 10 43 56 a m" src="https://github.com/aws-amplify/amplify-category-api/assets/11049349/8aa38f22-68b5-4fa8-8b1a-90b4d3cd5cb9">

---

<img width="1732" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/11049349/6d7e0edd-4230-43e3-a491-4504a6c6deb8">
<img width="1633" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/11049349/5abde441-8146-44bc-a6f4-823bfe70734d">

### Expected behavior

Being able to override the pipeline resolver that was automatically generated by amplify 

### Reproduction steps

1. Add this schema 
2. Push it to amplify
3. Create an override.ts file and try to override the autogenerated function

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by jguipi** [comment]
As extra detail, I already copied the autogenerated resolver into the right path 

From: amplify/backend/api/DevApi/build/resolvers
To : amplify/backend/api/DevApi/build/tsconfig.resource.json

<img width="463" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/11049349/e7a41558-d7a6-40b8-b3a8-22c2cd5b9479">

**Comment by AnilMaktala** [comment]
Hi @jguipi, Thanks for bringing this up. To override the resolvers, you need to copy the autogenerated resolver from `amplify/backend/api/<resource_name>/build/resolvers/` to `amplify/backend/api/<resource_name>/resolvers/`. The naming convention in the screenshot is expected for relationship tables. Please let us know if you still encounter any issues.

**Comment by jguipi** [comment]
> Hi @jguipi, Thanks for bringing this up. To override the resolvers, you need to copy the autogenerated resolver from `amplify/backend/api/<resource_name>/build/resolvers/` to `amplify/backend/api/<resource_name>/resolvers/`. The naming convention in the screenshot is expected for relationship tables. Please let us know if you still encounter any issues.

That was already done, but when I try to add the code in the `override.ts` to override the pipeline resolver that fonction is not there.

As shown above, I was not able to found the function in either of those model:

```javascript
const getChildModel= resources.models['Child'];
const getUserModel = resources.models['User'];

console.log(getChildModel)
console.log(getUserModel)

```

getChildModel return 

<img width="894" alt="image" src="https://github.com/user-attachments/assets/129320d5-a2b4-4607-ab0d-b71fd7fce368">

getUserModel return 

<img width="460" alt="image" src="https://github.com/user-attachments/assets/cd3e17d5-1ad1-4845-93e3-8bd4d864615b">

There is no mention of that autogenerated function

**Comment by AnilMaktala** [comment]
Hi @jguipi, Could we arrange a call to explore this issue in detail?

**Comment by AnilMaktala** [comment]
Hey @jguipi, Are you still experiencing this issue?

**Comment by jguipi** [comment]
> Hi @jguipi, Could we arrange a call to explore this issue in detail?

Hi !
That would be great since I’m still facing the same issue. 

sorry I’m currently on vacation and I don’t have my laptop. Can we have a call when I come back ? After August 10th.

**Comment by jguipi** [comment]
Let me know when you're available. I'm free from 3 PM Montreal time almost every day.  (7 PM UTC) 

https://juwrl.setmore.com/j

**Comment by AnilMaktala** [comment]
Hey @jguipi , 
Are you on Discord? If so, could you please share your [Discord](https://discord.com/invite/amplify) username with me?

**Comment by jguipi** [comment]
> Hey @jguipi , Are you on Discord? If so, could you please share your [Discord](https://discord.com/invite/amplify) username with me?

Sure 

discord: j.g7636

**Comment by AnilMaktala** [comment]
@jguipi Thanks for sharing your username. I’ll connect with you on Discord.

**Comment by palpatim** [comment]
Hi @jguipi,

I believe the configurations you're looking for are exposed under the `ConnectionStack` key of `resources.models`. In your sample schema, it looks like the pipeline you want is under `userChildrenResolver`


```ts
import { AmplifyApiGraphQlResourceStackTemplate, AmplifyProjectInfo } from '@aws-amplify/cli-extensibility-helper';
import { CfnResolver } from 'aws-cdk-lib/aws-appsync';

export function override(resources: AmplifyApiGraphQlResourceStackTemplate, amplifyProjectInfo: AmplifyProjectInfo) {
  console.log('\n### resources.models:', JSON.stringify(Object.keys(resources.models)));
  // ### resources.models: ["User","Child","ConnectionStack"]

  console.log('\n### resources.models[ConnectionStack].resolvers:', JSON.stringify(Object.keys(resources.models['ConnectionStack']?.resolvers)));
  // ### resources.models[ConnectionStack].resolvers: ["userChildrenResolver","childUserResolver"]

  const model = resources.models['ConnectionStack']!;
  const resolvers = model.resolvers!;
  const getResolver = resolvers['userChildrenResolver']!;

  console.log('### original pipelineConfig', JSON.stringify(getResolver.pipelineConfig));
  // ### original pipelineConfig {"functions":["${Token[TOKEN.725]}"]}

  const pipelineConfig = getResolver.pipelineConfig!;
  const functions = (pipelineConfig as CfnResolver.PipelineConfigProperty).functions;
  getResolver.pipelineConfig = {
    functions: [
      'pipelinefn1-dev',
      'pipelinefn2-dev',
      ...functions
    ]
  };

  console.log('### updated pipelineConfig', JSON.stringify(getResolver.pipelineConfig));
  // ### updated pipelineConfig {"functions":["pipelinefn1-dev","pipelinefn2-dev","${Token[TOKEN.725]}"]}
}
```

Hope this helps

**Comment by jguipi** [comment]
Thank you for the reply ! I'll try this out during the weekend

**Comment by jguipi** [comment]
The solution worked! Thank you all for your help! In the end, the autogenerated pipeline was stored in resources.models['ConnectionStack'].

Hopefully it will help other people !
