### ISSUE TITLE
Unidirectional @hasOne relationships

### ISSUE THREAD

**Issue by ErlendHer** [aws-amplify/amplify-category-api#2704]
### Environment information

```plain text
-
```

### Description

Similar to what is possible in Amplify gen 1, we would like to have unidirectional `@hasOne` relationships so that we're not forced to create bidirectional 1-1 relations

**Comment by AnilMaktala** [comment]
Hey @ErlendHer, Thanks for bringing this up. I understand that Amplify Gen2 creates bidirectional relationships by default. To better understand your situation, could you please elaborate on your use case for unidirectional @hasOne? What issues are you currently facing with the existing bidirectional approach?

**Comment by phani-srikar** [comment]
Hi @ErlendHer, thanks for your feedback. The updated experience was designed as such to make the location of connected field uniform across `@hasMany` and `@hasOne` kind of relationships. Like you mentioned, if one has a use-case that doesn't require them to get the connection item, they can skip the connected field from the selection set.
