### ISSUE TITLE
Get ApiId or Table Name in custom handler

### ISSUE THREAD

**Issue by godrimcom** [aws-amplify/amplify-category-api#2708]
### Environment information

```plain text
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Pro
  Memory: 153.83 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.12.0 - ~/.nvm/versions/node/v20.12.0/bin/node
  Yarn: undefined - undefined
  npm: 10.5.0 - ~/.nvm/versions/node/v20.12.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.0
  @aws-amplify/backend-cli: 1.0.1
  aws-amplify: 6.3.8
  aws-cdk: 2.140.0
  aws-cdk-lib: 2.140.0
  typescript: 5.4.5
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

I'm using amplify gen 2 and I added a custom handler in my schema:
```
deleteTickets: a
    .mutation()
    .arguments({
      ids: a.id().array(),
    })
    .returns(a.json())
    .authorization((allow) => [allow.authenticated()])
    .handler(
      a.handler.custom({
        dataSource: a.ref('Ticket'),
        entry: './handlers/tickets/deleteTickets.js',
      })
    ),
```

this is my handler:
```
export function request(ctx) {
  const { ids } = ctx.args

  return {
    operation: 'BatchDeleteItem',
    tables: {
      TABLE_NAME: ids.map((id) => util.dynamodb.toMapValues({ id })),
     // How can I access the table name? in ctx. This is the actual table name Ticket-ruzu7wa7dzcbflfe2qpamijr5a-NONE
    },
  }
}

export function response(ctx) {
  if (ctx.error) {
    util.error(ctx.error.message, ctx.error.type)
  }
  return ctx.result || {}
}
```
I just want to do a BatchDeleteItem operation. This should be a basic operation, please help

**Comment by AnilMaktala** [comment]
Hey @godrimcom, "Thank you for bringing this up. Could you please clarify if you have already reviewed the relevant [documentation](https://docs.amplify.aws/react/build-a-backend/data/connect-to-existing-data-sources/connect-external-ddb-table/#batchdeleteitem) on this topic?"

**Comment by chrisbonifacio** [comment]
Hi @godrimcom At the moment there is no way, at least that I'm aware of, to access and pass the table name to a resolver without incurring a "circular dependency" error. You may have to hard code the table name and pass it as an environment variable.

ex:

```ts
backend.data.resources.cfnResources.cfnGraphqlApi.environmentVariables = {
  PHONENUMBER_TABLE:
    // replace with your own table name
    `PhoneNumber-md4n36jl7za7xi4mie3cs3wyey-NONE`,
};
```

we are working on a way to make the DDB tables accessible

**Comment by andrew-clark-dev** [comment]
Hi @chrisbonifacio , just checking that you know you can access the table name from the data resources.
So
`
const { tables } = backend.data.resources

backend.data.resources.cfnResources.cfnGraphqlApi.environmentVariables = {
  TODO_TABLE: tables['Todo'],
};`

**Comment by chrisbonifacio** [comment]
@andrew-clark-dev Hey, that works! Didn't know you could do that. Thanks!

**Comment by thomasoehri** [comment]
> @andrew-clark-dev Hey, that works! Didn't know you could do that. Thanks!
> 
> ```ts
> backend.sharpFunction.resources.cfnResources.cfnFunction.environment = {
>   variables: {
>     TODO_TABLE: backend.data.resources.tables["Todo"].tableName,
>   },
> };
> ```
> 
> ![CleanShot 2024-10-10 at 14 56 38@2x](https://private-user-images.githubusercontent.com/16952986/375508667-85af6248-1e3a-4d9c-b3c9-fa281fe96101.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDAyNjcsIm5iZiI6MTcyODYzOTk2NywicGF0aCI6Ii8xNjk1Mjk4Ni8zNzU1MDg2NjctODVhZjYyNDgtMWUzYS00ZDljLWIzYzktZmEyODFmZTk2MTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA5NDYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NmVkNTFjNjZlZmFiNGEwMmI2MjM0NTgzM2UxZDQwYWU3Yjc3NTk5OGZmYTY2MzNiZjYyNWEwNGJmZjZjZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zNlKUppoV1dUVeZ84_cCyj5OQa8B7wWnNJP48h_igik)

That does not work for me, i'm still getting a circular dependency error.

**Comment by bemoi0607** [comment]
I add having the same problem getting a circular dependency , did you solve it?

**Comment by Solomko2** [comment]
I have circular dependency too!

**Comment by milosevicd** [comment]
try this:

`backend.sharpFunction.addEnvironment("TODO_TABLE", backend.data.resources.tables["Todo"].tableName);`

**Comment by milosevicd** [comment]
The solution for **circular dependency** is to make the lambda function belong to the same resource group as the data models. Do this in defineFunction():

`  resourceGroupName: "data",`

(I'm not sure where exactly to put this for custom GraphQL resolvers, but it should be similar)

**Comment by ujjwol05** [comment]
@milosevicd  
```TS2353: Object literal may only specify known properties, and resourceGroupName does not exist in type FunctionProps```
It seems that FunctionProps is missing resourceGroupName

**Comment by milosevicd** [comment]
@ujjwol05, are you using the latest Amplify version? 
I have it working well for me, and it's also documented here: https://aws-amplify.github.io/amplify-backend/types/_aws_amplify_backend_function.FunctionProps.html

**Comment by milosevicd** [comment]
@ujjwol05, I'm not sure about this, but could be that the schedules needs to be in the same group as well. It seems like Amplify auto generates a **schedule** for each lambda that has a cron schedule set up. You could try to get to those schedules and their properties and set them to belong to the same group.
