### ISSUE TITLE
Delete mutation not rorking --- owners cannot delete their own record

### ISSUE THREAD

**Issue by tszchung019** [aws-amplify/amplify-category-api#2742]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.11.1

### Amplify CLI Version

12.12.3

### What operating system are you using?

Windows 11

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I tried to run a delete mutation on AWS AppSync to test if my API works, it seems that I can create a record with @auth with the tokens but it failed to delete the object I just created. I confirmed the owner of the record is the same as the one who is trying to delete the same record but it returned **"Not Authorized to access deleteBlog on type Mutation"** which is very strange. 

![image](https://github.com/user-attachments/assets/2fca239f-5dba-4314-a2ff-32f82c5286ed)

![image](https://github.com/user-attachments/assets/e4976ea0-6a1b-4048-b182-59698326876d)

Provided my schema in **Reproduction steps** section. Is there any misconfiguration I had made? Thank you.

### Expected behavior

The mutation should allow owners of the record to delete their own records.

### Reproduction steps

1. Create the GraphQL schema as below:
type Blog @model @auth(rules: [{ allow: public, operations: [read] }, { allow: owner, operations: [create, update, delete] }]) {
  id: ID!
  name: String!
  summary: String
  imgPath: String
  posts: [Post] @hasMany @auth(rules: [{ allow: public, operations: [read] }])
}
2. 

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by tszchung019** [comment]
I can tell it is a bug since I looked at the schema at AppSync, under type Mutation, the label @aws_cognito_user_pools should be added given the schema I pushed. (I did not provide my entire schema in my post). Interestingly, if I define another table like this:

```
type Project @model @auth(rules: [{ allow: owner, operations: [read, create, update, delete] }]) {
  id: ID!
  name: String!
  description: String!
  completion: Float
  status: Boolean
  user: User @belongsTo
}
```

AppSync is able to generate the schema correctly. May I know is that relevant?

![image](https://github.com/user-attachments/assets/e0c9c24e-32b0-4cea-ac78-57b1218f5b16)

**Comment by AnilMaktala** [comment]
Hi @tszchung019   👋 Thanks for raising this issue. We are working on reproducing the issue. Could you please run below command and send us the report `amplify diagnose --send-report`. please refer [here](https://docs.amplify.aws/cli/reference/diagnose/)

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
