### ISSUE TITLE
Newer versions of Amplify CLI not creating the IAM policy properly for DynamoDB datasource

### ISSUE THREAD

**Issue by call2shadab** [aws-amplify/amplify-category-api#2750]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

Node v20.11.1

### Amplify CLI Version

Amplify v12.12.6

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

NA

### Describe the bug

Amplify CLI v12.12.6 is not generating the correct IAM permissions policy in case of overrides being defined for DynamoDB datasource. This results in IAM AccessDenied Error when the DynamoDB datasource is accessed via the AppSync API. Refer to the below replication steps.

Testing with previous version of Amplify CLI (`v12.10.1`), the correct permissions policy is being generated for the changed name and associated with the role.

Additionally, the newer versions pops up warning about the usage of `iam` in `@auth` and requires us to change this to `identityPool`, however, the [documentation](https://docs.amplify.aws/gen1/javascript/build-a-backend/graphqlapi/customize-authorization-rules/#authorization-strategies) is not updated and still suggests to use `iam`.

### Expected behavior

The correct permissions policies should be generated and associated with the role.

### Reproduction steps

1. In Amplify Gen1 application, add the GraphQL API with `IAM` authorization using Amplify CLI `v12.12.6`.
2. Run `amplify override api`.
3. Define the following override in `override.js` to change the table name of the DynamoDB table as below:

```
resources.models["Todo"].modelDDBTable.tableName = `Todo-dev`;
```
4. Push the changes and check the IAM role associated with the AppSync API under datasource section.
5. The role would not have permissions for the changed DynamoDB table name. Role would only contain the policy named `DynamoDBAccess`, which has inline permissions for only the auto-generated table name and not the override one. This results in AccessDenied error.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by adamgogacz** [comment]
Any idea when (version) this bug was introduced?

**Comment by AnilMaktala** [comment]
Hi @call2shadab, Thanks for bringing this up. Could you try rolling back to version `v12.12.3` and let me know if it resolves the issue?

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
