### ISSUE TITLE
How to order results of list() method using Amplify Gen2 data client

### ISSUE THREAD

**Issue by jaimeardp** [aws-amplify/amplify-category-api#2789]
### Environment information

```plain text
System:
  OS: Windows 11 10.0.22631
  CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
  Memory: 607.32 MB / 15.73 GB
Binaries:
  Node: 20.16.0 - C:\Program Files\nodejs\node.EXE
  Yarn: undefined - undefined
  npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.4
  @aws-amplify/backend-cli: 1.1.1
  aws-amplify: 6.4.0
  aws-cdk: 2.149.0
  aws-cdk-lib: 2.149.0
  typescript: 5.5.3
AWS environment variables:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
No CDK environment variables
```

### Description

Hi, I've started using Amplify Gen2, and its documentation offers the Amplify Data Client to read data from DynamoDB tables. I've successfully used the list and get functions. However, when I attempt to sort the results of the list function, it seems that sortDirection filters the results instead of ordering the rows. For example 

When I don't use sortDirection, it returns rows.

```
import { generateClient } from "aws-amplify/data";
import type { Schema } from "../../../../amplify/data/resource";
const client = generateClient<Schema>();

        const {data: posts, errors} = await client.models.BlogPosts.list({ 

          filter: {
            pk: {
              beginsWith: 'POST#',

            },
          },
          limit: 10,
        });
```

But if i use with sortDirection params equal to DESC or ASC like this: return ZERO rows

```
import { generateClient } from "aws-amplify/data";
import type { Schema } from "../../../../amplify/data/resource";
const client = generateClient<Schema>();

        const {data: posts, errors} = await client.models.BlogPosts.list({ 
          filter: {
            pk: {
              beginsWith: 'POST#',
            },
          },
          limit: 10,
          sortDirection: 'DESC',
        });
```

My model base is

```
    BlogPosts: a
      .model({
        id: a.id().required(),
        pk: a.string().required(),
        sk: a.string().required(),
        postId: a.id().required(),
        title: a.string().required(),
        imageUrl: a.string().required(),
        imageUrlAbs: a.string(),
        preview: a.string(),
        content: a.string(),
        tags: a.string().array(),
        category: a.string(),
        createdAt: a.datetime().required(),
        updatedAt: a.string(),
      })
      .identifier(["id", 'createdAt'])
      .secondaryIndexes((index) => [index("createdAt")])
```
I aim to replicate this query in DynamoDB using the Amplify Data Client.

```
select * from blogs where pk like 'POST#%'  order by createdAt desc limit 3
```

Maybe this feature of order rows in based a one column not exists in this version de Amplify Gen 2 data client?

**Comment by chrisbonifacio** [comment]
Hi @jaimeardp it looks like your table's primary key is a composite key that consists of a combination of the `id` and `createdAt` fields. This seems fine, but your secondary index uses `createdAt` as the primary key.

You won't be able to sort by createdAt on the `list` query because it performs a Scan. I think what you need to do is adjust your GSI to use a different field as the primary key to "bucket" or group records together and make `createdAt` the sort key. You should then have access to a query like this:

```ts
    client.models.BlogPosts.listBlogPostsByPkAndCreatedAt(
      {
        someField: "POST#",
      },
      {
        filter: {
          pk: {
            beginsWith: "POST#"
          }
        },
        sortDirection: "DESC",
        limit: 3,
      }
    );
```

Let me know if that helps!

**Comment by jaimeardp** [comment]
Hi @chrisbonifacio thanks so much for u help, now works as i expected!. What you said is correct, i change GSI to 

```
    BlogPosts: a
      .model({
        pk: a.string().required(),
        sk: a.string().required(),
        postId: a.id().required(),
        title: a.string().required(),
        imageUrl: a.string().required(),
        imageUrlAbs: a.string(),
        preview: a.string(),
        content: a.string(),
        tags: a.string().array(),
        category: a.string(),
        createdAt: a.datetime(),
        updatedAt: a.string(),
        type: a.string().required(),
      })
      .identifier(["pk", 'createdAt'])
      .secondaryIndexes((index) => [index("type").sortKeys(["createdAt"])])
      .authorization((allow) => [allow.publicApiKey()]),
```

Now my request is like:

```
        const {data: posts, errors} = await client.models.BlogPosts.listBlogPostsByTypeAndCreatedAt(
          {type: 'post'},
          {
            filter: {
              pk: {
                beginsWith: 'POST#',
              },
            },
            limit: 4,
            sortDirection: 'DESC',
        });
```

I've only found one similar example.

```
const { data, errors } =
  await client.models.Customer.listCustomerByAccountRepresentativeIdAndName({
    accountRepresentativeId: "YOUR_REP_ID",
    name: {
      beginsWith: "Rene",
    },
  });
```

 I hope the Amplify team can provide more in-depth documentation on this topic, particularly regarding the limitations and complexity of functions like list(). For instance, I'm interested in implementing SQL-like "ranking" operations using partition by, and I'd like to understand how this would work within the current Data Client of amplify gen2. 

Maybe I'm overthinking this and should just use functions for complex cases ?

**Comment by Nischit007** [comment]
export const getChatMessage = (receiverId, senderId) => async (dispatch) => {
  dispatch({ type: GET_CHAT_MESSAGE_REQUEST });
  try {
    const client = generateClient();

    const result = await client.models.MessageChats.list(
      {
        filter: {
          or: [
            { recieverId: { eq: receiverId }, senderId: { eq: senderId } },
            { recieverId: { eq: senderId }, senderId: { eq: receiverId } }
          ]
        },
        sort: { field: " created_at", direction: "DESC" },  
        limit: 3,
      }
    );

    console.log(" Fetched Messages:", result?.data);

    dispatch({ type: GET_CHAT_MESSAGE_SUCCESS, payload: result?.data });
  } catch (error) {
    console.error(" Error Fetching Messages:", error.message);
    dispatch({ type: GET_CHAT_MESSAGE_FAILURE, payload: error.message });
  }
};



import { type ClientSchema, a, defineData } from "@aws-amplify/backend";

export const MessageChats = () => {
  return a
    .model({
      // foriegn key field in Notes Table
      owner: a.string().required(), // Tenant ID to determine ownership
      message: a.string().required(),
      senderId: a.string().required(),
      recieverId:a.string().required(),
      // isDelete:a.integer().array(),
      isSeenByReciever:a.boolean().default(false),
      // Timestamps
      created_at: a.datetime().default(new Date(Date.now()).toISOString()),
    })
    .authorization((allow) => [allow.owner().identityClaim("given_name")]);
};


not able to sort it by desc with respect to create

**Comment by reachmesagar** [comment]
> sort: { field: " created_at", direction: "DESC" },

hora munnu
