### ISSUE TITLE
Allow functions to have additional policies

### ISSUE THREAD

**Issue by ignaciolarranaga** [aws-amplify/amplify-category-api#279]
**Is your feature request related to a problem? Please describe.**
I have a custom function that is creating documents in a DynamoDB table and I want to add some additional information from predictions (language and entities from AWS Comprehend actually).

Specifically I have something like:
```
type Mutation {
  createTodoCustom(input: CreateTodoCustomInput!): Todo @function(name: "createTodoCustom-${env}")
}
```

And I want `createTodoCustom` to be able to do something like this:
```
const comprehend = new AWS.Comprehend();
const params = {
  Text: 'Text to translate',
};
const languageResponse = await comprehend.detectDominantLanguage(params).promise();
...
```

I know I can go and touch the function after deployed or touch the CloudFormation template also but this will be override every time I touch something related to the function configuration.
I did try to add predictions to the project and later add permissions for predictions to the function but this doesn't work. It does make sense though. I guess because predictions is for the frontend not for the backend (thinking at loud).

**Describe the solution you'd like**
The CloudFormation template to not be override but smartly adjusted.

**Describe alternatives you've considered**
For predictions access from a lambda function the best solution will be:
1) if I add permissions for a lambda function to access predictions, then the CloudFormation template gets correctly updated.

A more general approach (that probably solve similar issues) can be:
2) To allow extensions to the CloudFormation template or 
3) A smarter update of the CloudFormation template (i.e. replace/adjust only what it is necessary) so it is not fully override.

**Comment by renebrandel** [comment]
Supported now: https://docs.amplify.aws/react/build-a-backend/functions/set-up-function/#access-existing-aws-resource-from-lambda-function
