### ISSUE TITLE
@searchable similarity search

### ISSUE THREAD

**Issue by fistofzen** [aws-amplify/amplify-category-api#2793]
### Amplify CLI Version

12.10.3

### Question

How can we search an item with similarity in graphql @searchable ? For example, How user can search apple with aple. 
İs it possible ?

Regards

**Comment by AnilMaktala** [comment]
Hey @fistofzen, Thank you for bringing this up. Are you referring to fuzzy search as outlined in the OpenSearch documentation here: https://opensearch.org/docs/latest/query-dsl/term/fuzzy/?

**Comment by fistofzen** [comment]
Hello,
Yes Anil. How can we do that in graphql?

**Comment by AnilMaktala** [comment]
Hey @fistofzen, unfortunately, the fuzzy search feature is not natively supported out of the box. However, you can explore the option of overriding the resolver and writing a custom Lambda function to achieve this functionality. For reference, you can refer the following documentation:

https://docs.amplify.aws/gen1/react/build-a-backend/graphqlapi/modify-amplify-generated-resources/

https://docs.amplify.aws/gen1/react/build-a-backend/graphqlapi/modify-amplify-generated-resources/#example---configure-opensearch-streaming-function-name
