### ISSUE TITLE
@auth rule requiring multiple group membership

### ISSUE THREAD

**Issue by flashbackzoo** [aws-amplify/amplify-category-api#28]
**Which Category is your question related to?**

API (GraphQL)

**Amplify CLI Version**

8.2.0

**Additional details**

Is it possible to have auth rules requiring users belong to multiple groups? For example "allow users who are in 'Tenant N' **AND** 'Editor' groups".

Our models are currently similar to this:

```graphql
type MyModel
  @model
  @auth(rules: [
    { allow: owner },
    { allow: groups, groupsField: "tenantID" },
  ])
{
  id: ID!
  tenantID: String!
}
```

This has worked up until now, allowing anyone in the tenant to CRUD the record. But now we're introducing groups e.g. 'Editor' and need to add these new groups to our auth rules.

Given we have a dynamic `tenantID`, using static group auth doesn't work for us:

```graphql
type MyModel
  @model
  @auth(rules: [
    { allow: groups, groups: ["SomeDynamicTenantId", "Editor"] }
  ])
{
  id: ID!
  tenantID: String!
}
```

Because tenantID is a dynamic value, we need to continue using dynamic group auth, for example:

```graphql
type MyModel
  @model
  @auth(rules: [
    { allow: owner },
    { allow: groups, groupsField: "tenantID" },
    { allow: groups, group: "Editor" },
  ])
{
  id: ID!
  tenantID: String!
}
```

But this doesn't work because it's an **OR**, saying "allow anyone in the tenant **OR** anyone with the 'Editor' group". This would allow editors from other tenants, which isn't what we want.

Updating our models to use single dynamic group auth field doesn't work either:

```graphql
type MyModel
  @model
  @auth(rules: [
    { allow: owner },
    { allow: groups, groupsField: "allowGroups" },
  ])
{
  id: ID!
  allowGroups: [String] # ['SomeDynamicTenantId', 'Editor']
}
```

Because this an **OR** too, saying "allow anyone in the tenant **OR** anyone with the 'Editor' group".

Are there any other options, aside from a custom authenticator, to require multiple group membership?

**Comment by ykethan** [comment]
Hello @flashbackzoo, Thank you for reaching out and apologize for the delay in a response. On diving deep, I would be suggest utilizing `identityClaim` containing custom id as the attribute. For example:

```graphql
type MyModel
  @model
  @auth(rules: [
    { allow: owner, ownerField: "companyId", identityClaim: "custom:company_id" },
    { allow: groups, groupsField: "allowGroups" },
  ])
{
  id: ID!
  allowGroups: String!
  companyId: String!
}
```
here we can utilize the `companyid` and `allowgroups` required fields to create a AND requirement. Please do let us know this help your case, we would be happy in diving deeper.
additionally, I wanted to mention the github issue: https://github.com/aws-amplify/amplify-cli/issues/317.  Which outlines the feature request currently open for combining Owner/Groups rules for Multi-Tenant Apps.

**Comment by flashbackzoo** [comment]
Hi @ykethan thanks for getting back to me. That makes sense, I'll try your suggestion today and let you know it goes :)

**Comment by flashbackzoo** [comment]
Hmmm I'm getting "Unauthorized" errors after making this change but I can't see why.

My model is now:

```graphql
type MyModel
  @model
  @auth(rules: [
    { allow: owner, ownerField: "tenantID", identityClaim: "custom:tenant_id" },
  ])
{
  id: ID!
  tenantID: String!
}
```

The group rule has been removed so I know it's an issue with the custom claim.

I have a pre token generation function which adds the custom claim (simplified):

```js
const aws = require('aws-sdk');

exports.handler = async (event) => {
  event.response = {
    claimsOverrideDetails: {
      claimsToAddOrOverride: {
        'custom:tenant_id': 'MY_UNIQUE_TENANT_ID',
      },
    },
  };
};
```

And I can confirm the claim is successfully added by logging the user token on the client side:

```js
import { Auth } from 'aws-amplify';

const user = await Auth.currentAuthenticatedUser();

console.log(user.signInUserSession.idToken.payload['custom:tenant_id']); // 'MY_UNIQUE_TENANT_ID'
```

Am I missing a step?

**Comment by flashbackzoo** [comment]
Managed to get a little bit further, making `tenantID` optional on the model allows the item to be created in DynamoDB, so the authorisation issue I was having creating items is resolved (previously the tenant id was pulled from user token and passed as an input with the GraphQL request).

But when I look at the created item, the `tenantID` value is incorrect, it's `___xamznone____` rather than the expected `custom:tenant_id` value. Digging into the `.vtl` that value seems to be a fallback, used when the claim is null.

```vtl
## [Start] Authorization Steps. **
$util.qr($ctx.stash.put("hasAuth", true))
#set( $isAuthorized = false )
#if( $util.authType() == "API Key Authorization" )

#end
#if( $util.authType() == "User Pool Authorization" )
  #if( !$isAuthorized )
    #set( $authFilter = [] )
    #set( $role0 = $util.defaultIfNull($ctx.identity.claims.get("custom:tenant_id"), "___xamznone____") )
    #if( $role0 != "___xamznone____" )
      $util.qr($authFilter.add({"tenantID": { "eq": $role0 }}))
    #end
    #if( !$authFilter.isEmpty() )
      $util.qr($ctx.stash.put("authFilter", { "or": $authFilter }))
    #end
  #end
#end
#if( !$isAuthorized && $util.isNull($ctx.stash.authFilter) )
$util.unauthorized()
#end
$util.toJson({"version":"2018-05-29","payload":{}})
## [End] Authorization Steps. **
```

**Comment by flashbackzoo** [comment]
Seems to be this issue https://github.com/aws-amplify/amplify-js/issues/3326

Sending the id token (where custom claims are added by the the pre token generation function) seems to work.

@ykethan is this what you would recommend?

**Comment by ykethan** [comment]
Hey @flashbackzoo, Glad to hear that you were able to implement the custom identity claim. From the information provided the implementation appears to be correct. Currently a Github issue: https://github.com/aws-amplify/amplify-category-api/issues/64 is being tracked for the `___xamznone____` value.
Please do reach to us if you are facing any issues.

**Comment by ykethan** [comment]
Hey @flashbackzoo, checking in to see if you would require any assistance with the issue.

**Comment by flashbackzoo** [comment]
All good @ykethan thanks for your help

**Comment by Crusade1337** [comment]
> 

from my understanding, this would not result in an AND requirement. Either the owner (which matches the field comanyID) OR  users who have the specific String value of the allowGroups field in their Cognito groups have access. 

I don't see how this would result in an AND requirement. Maybe you could clarify how that would work since i'm currently looking into how to best handle such a AND requirement and don't see any option to do it with directives other than to have an Admin group for each Tenant and save this Admin Group in each model and then use dynamic group authorization.

Im looking forward to any hints or comments
