### ISSUE TITLE
How to create multiple batch mutations

### ISSUE THREAD

**Issue by pjsandwich** [aws-amplify/amplify-category-api#2834]
### Amplify CLI Version

12.12.6

### Question

Which of these are the correct way to create more than one batch mutation with a custom cdk resolver?

```
type Mutation {
  batchCreateTodo(todos: [BatchCreateTodo]): [Todo]
}

type OtherMutation {
...
}
```

Or

```
type Mutation {
  batchCreateTodo(todos: [BatchCreateTodo]): [Todo]
  someOtherBatch(things: [BatchCreateThings]): [Things]
}
```

I see that the `typeName` field should be `Query | Mutation | Subscription`:
```
const resolver = new appsync.CfnResolver(this, 'batchCreateToDo', {
      apiId: apiIdRef,
      fieldName: 'batchCreateToDo',
      typeName: 'Mutation', // Mutation type
      requestMappingTemplate: requestVTL,
      responseMappingTemplate: responseVTL,
      dataSourceName: 'ToDoTable', // DataSource name
    });
```

But how should an additional batch mutation be added to the schema and does the `typeName` or the resolver code need to be adjusted in a certain way on the existing toDo resolver or the new resolver?

**Comment by AnilMaktala** [comment]
Hey @pjsandwich, Thank you for raising this. Yes, you can create multiple batch mutations using the same approach as `batchCreateToDo`, with the `TypeName` always being `Mutation` in this case. Below is a sample code snippet for `BatchCreateThings`.

```
type Mutation {
  batchCreateTodo(todos: [BatchCreateTodo]): [Todo]
  someOtherBatch(things: [BatchCreateThings]): [Things]
}

const thingsresolver = new appsync.CfnResolver(this, 'someOtherBatch', {
      apiId: apiIdRef,
      fieldName: 'someOtherBatch',
      typeName: 'Mutation', // Mutation type
      requestMappingTemplate: requestVTL,
      responseMappingTemplate: responseVTL,
      dataSourceName: 'ThingsTable', // DataSource name
    });
```

**Comment by pjsandwich** [comment]
Thank you @AnilMaktala , I will try this out and get back to you here

**Comment by pjsandwich** [comment]
This works! Thanks @AnilMaktala
