### ISSUE TITLE
Codegen does not produce compilable typescript queries.ts

### ISSUE THREAD

**Issue by nogeek** [aws-amplify/amplify-category-api#2962]
### How did you install the Amplify CLI?

brew

### If applicable, what version of Node.js are you using?

22.9.0

### Amplify CLI Version

12.13.0

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no none

### Describe the bug

https://github.com/aws-amplify/amplify-category-api/issues/1960 same issue at this

### Expected behavior

https://github.com/aws-amplify/amplify-category-api/issues/1960 -> exactly the same issue

### Reproduction steps

https://github.com/aws-amplify/amplify-category-api/issues/1960 reproduce this same issue

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

n/a

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi  @nogeek 👋 thanks for raising this issue. We are working on reproducing the issue. Could you please run below command and send us the project identifier by running `amplify diagnose --send-report`. 
please refer [here](https://docs.amplify.aws/cli/reference/diagnose/)

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
