### ISSUE TITLE
OpenSearch Circular dependency

### ISSUE THREAD

**Issue by 1024cainiao** [aws-amplify/amplify-category-api#2967]
### Amplify CLI Version

12.13.0

### Question

Describe the bug
I refer to the following official documents for configuration
[https://docs.amplify.aws/react/build-a-backend/data/custom-business-logic/search-and-aggregate-queries/](document)，
Steps 1-3 are successful, step 4 fails, execute npx ampx sandbox, the console prompt is as follows
<img width="960" alt="image" src="https://github.com/user-attachments/assets/8553657d-b569-4ac6-a40e-719500e98368">

Expected Behavior
It should not result in a circular dependency

Below is my repository link
[https://github.com/1024cainiao/amplify-vite-react-template](repository)

**Comment by AnilMaktala** [comment]
Hi @1024cainiao,  Thank you for raising this. The link seems to be redirecting me to the same `category-api` repository. Could you please provide the correct repo link or share your `backend.ts` file so I can better understand the issue?

**Comment by 1024cainiao** [comment]
Hi @AnilMaktala I re-edited the link

Describe the bug
I refer to the following official documents for configuration
[https://docs.amplify.aws/react/build-a-backend/data/custom-business-logic/search-and-aggregate-queries/](https://docs.amplify.aws/react/build-a-backend/data/custom-business-logic/search-and-aggregate-queries/)，
Steps 1-3 are successful, step 4 fails, execute npx ampx sandbox, the console prompt is as follows
image

Expected Behavior
It should not result in a circular dependency

Below is my repository link
[https://github.com/1024cainiao/amplify-vite-react-template](https://github.com/1024cainiao/amplify-vite-react-template)

**Comment by AnilMaktala** [comment]
Hi @1024cainiao, Thanks for sharing the repo. After reviewing the backend.ts file, I noticed that at line 50, you're creating a new open-search-stack, which is leading to a circular dependency error. Try modifying it as shown below and let me know if that resolves the issue.
```
const openSearchStack = Stack.of(backend.data);
```

<img width="730" alt="image" src="https://github.com/user-attachments/assets/adc9abb2-61b0-4005-8374-80bf7042dc61">

**Comment by 1024cainiao** [comment]
Hi @AnilMaktala, Thanks for your answer. Modified according to your description and the problem is solved.

**Comment by AnilMaktala** [comment]
@1024cainiao, Thanks for confirming. I'm glad to hear the issue has been resolved. I'll go ahead and close it now.
