### ISSUE TITLE
Got null data in subscription callback if data is changed inside a lambda function

### ISSUE THREAD

**Issue by nam-truong-le** [aws-amplify/amplify-category-api#2974]
### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

20

### Amplify CLI Version

1.2.9

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

I follow this [Grant Lambda function access to API and Data](https://docs.amplify.aws/react/build-a-backend/data/customize-authz/grant-lambda-function-access-to-api/) to update data inside a lambda function.

My subscription in UI is triggered but it gets null data:

<img width="527" alt="Bildschirmfoto 2024-10-22 um 16 25 40" src="https://github.com/user-attachments/assets/209b6dfc-e0be-4c8e-b025-44f584c47e5f">

### Expected behavior

The callback in the UI should get data.

### Reproduction steps

* Change data in lambda using sth similar to this:
```typescript
  const { errors: updateApplicationErrors } = await client.graphql({
    query: updateApplication,
    variables: {
      input: {
        id: applicationId,
        status: ApplicationStatus.PAID,
        refundLink,
        paidAt: new Date().toISOString(),
        paymentMethod: PaymentMethod.PAYPAL,
      },
    },
  });
```

* subscribe for data update in UI:
```typescript
useEffect(() => {
    const sub = client.models.Application.onUpdate({
      selectionSet: [...SELECTION],
      authMode: "userPool",
    }).subscribe({
      next: function (application) {
        dispatch(updateApplication(application));
      },
      error: (err) => {
        const { errors } = err;
        console.error("Error update applications triggered by default update", err);
        dispatch(setApplications([]));
        dispatch(setError(errors.map((e: any) => e.message).join("\n\n\n")));
      },
    });
    return () => sub.unsubscribe();
  }, [dispatch]);
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by chrisbonifacio** [comment]
Hi @nam-truong-le can you provide the selection set of the outgoing mutation that is meant to trigger the subscription? I'm curious to see what fields the mutation returns and what fields the subscription is expecting. There might be some conflict between them that is potentially causing an error that makes it seem like the data is `null`.

You can verify this by checking the network tab, filtering for `WS` and checking the incoming messages. You should be able to see what data and/or errors were returned from the subscription.

**Comment by nam-truong-le** [comment]
This is my selection set:


```typescript
const SELECTION = [
  "id",
  "number",
  "status",
  "billingItems.*",
  "summary.*",
  "data.*",
  "data.applicants.*",
  "data.billing.*",
  "data.options.*",
  "paymentLink",
  "secret",
  "createdAt",
  "updatedAt",
  "paidAt",
  "paymentMethod",
] as const;
```

**Comment by nam-truong-le** [comment]
> were you able to check the subscription messages in the network logs?

I will try.

> Maybe try removing the relational fields

I don't have relational fields, they are just custom types.

**Comment by nam-truong-le** [comment]
I do see data in WS message:

<img width="632" alt="Bildschirmfoto 2024-10-29 um 06 35 33" src="https://github.com/user-attachments/assets/996a3ec5-c26e-48c7-a624-785355e59ed7">

**Comment by chrisbonifacio** [comment]
@nam-truong-le can you check the outgoing mutation and what fields are in its selection set, then compare that to the fields the subscription has in its selection set? please share them as well.

curious to see if there is a mismatch between them. the mutation selection set should be at least a subset of the subscription's.

**Comment by nam-truong-le** [comment]
I return full object in mutation and the select set is a sub set of it.

**Comment by chrisbonifacio** [comment]
@nam-truong-le are you able to share what those look like for us to reproduce the issue more accurately?

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
