### ISSUE TITLE
Multiple GSI deploy using CDK construct

### ISSUE THREAD

**Issue by jimjiminyjimjim** [aws-amplify/amplify-category-api#3003]
### Amplify CLI Version

12.2.5

### Question

We're having problems deploying multiple GSI changes/creations using the CDK construct. Amplify CLI does this iteratively, and there are examples of using Lambda to create the GSIs but I don't think this would work alongside the graphql-api-contruct?

It does become a problem with multiple devs working on the project if we need to sync up work that contains multiple GSIs that have already been deployed iteratively to one region, and then we need to deploy to another region a different dev is working in as you can't really back track all the iterative index deploys.

Is there a way to do this with the CDK construct?

**Comment by sundersc** [comment]
@jimjiminyjimjim CDK construct uses a custom resource to deploy DynamoDB GSIs. It doesn't require iterative deployment, multiple index updates can be made in a single stack update. During deployment, it looks at the current table definition, then decides whether to create/update/drop a GSI. Could you explain the problem you are running into with an example?

**Comment by jimjiminyjimjim** [comment]
Here's a part of my schema:

`
type ProductGroup
  @model
  @auth(
    rules: [
      { allow: public, provider: identityPool, operations: [read] }
      { allow: groups, groups: ["admin"] }
      { allow: private, provider: identityPool }
    ]
  ) {
  id: ID!
  name: String
  description: String
  type: ProductGroupType @index(name: "byType", queryField: "productGroupByType",  sortKeyFields: ["partnerId"])
  partnerId: ID @index(name: "byPartner", queryField: "productGroupByPartner", sortKeyFields: ["type"])
  productParentId: ID @index(name: "byProductParent", queryField: "productGroupByParentProduct", sortKeyFields: ["type"])
  productParentVersion: Int
  partner: Partner @belongsTo(fields: ["partnerId"])
  productParent: Product @hasOne(fields: ["productParentId", "productParentVersion"])
  products: [Product] @manyToMany(relationName: "productGroupProducts")
}
`

if I add or remove multiple indexes for instance like this by adding byName and byDescription in one deploy:

`
type ProductGroup
  @model
  @auth(
    rules: [
      { allow: public, provider: identityPool, operations: [read] }
      { allow: groups, groups: ["admin"] }
      { allow: private, provider: identityPool }
    ]
  ) {
  id: ID!
  name: String @index(name: "byName")
  description: String @index(name: "byDescription")
  type: ProductGroupType @index(name: "byType", queryField: "productGroupByType",  sortKeyFields: ["partnerId"])
  partnerId: ID @index(name: "byPartner", queryField: "productGroupByPartner", sortKeyFields: ["type"])
  productParentId: ID @index(name: "byProductParent", queryField: "productGroupByParentProduct", sortKeyFields: ["type"])
  productParentVersion: Int
  partner: Partner @belongsTo(fields: ["partnerId"])
  productParent: Product @hasOne(fields: ["productParentId", "productParentVersion"])
  products: [Product] @manyToMany(relationName: "productGroupProducts")
}
`


I get this error:

12:57:12 AM | UPDATE_FAILED        | AWS::DynamoDB::Table                | ProductGroupTable59D4B7C7
Resource handler returned message: "Cannot perform more than one GSI creation or deletion in a single update" (RequestToken: d515adda-a0ba-c80f-ef1d-8aad26c5bb53, HandlerErrorCode: InvalidRequest)

**Comment by sundersc** [comment]
I think you may be using the default table provisioning strategy which relies on DynamoDB constructs to manage the tables. DynamoDB constructs [do not support more than one GSI creation or deletion in a single stack update](https://repost.aws/questions/QUVnJDNa8mSLiocehq8VWthQ/cloudformation-deployment-issue-error-with-dynamodb-gsi-updates). In order to use Amplify Table manager, the model provisioning strategy must be explicitly set as shown below.

```ts
definition: AmplifyGraphqlDefinition.fromString(schema, {
   dbType: 'DynamoDB',
   provisionStrategy: 'AMPLIFY_TABLE'
}),
```

Refer to the corresponding helper definition [here](https://github.com/aws-amplify/amplify-category-api/blob/main/packages/amplify-graphql-api-construct/src/amplify-graphql-definition.ts#L29).

**Comment by jimjiminyjimjim** [comment]
Great thanks for pointing me towards this, is there any documentation other than the construct hub that would point out that this would be a feature of that provision strategy? 

Also now I've changed it, some of my current constructs are struggling to find the tableRefs if I use something like this:

`const tableRef = api.resources.cfnResources.cfnTables
`

as the cfnTables is an empty object. Will it need ripping down and starting again if I change the provisionStrategy? Or do I need to change my construct refs?

**Comment by AnilMaktala** [comment]
Hey @jimjiminyjimjim, Please remember changing the default PROVISIONG POLICY may result in loss of data. Please ensure to take a backup of data and enable delete protection before changing the provisioning policy.  

You can access the table map by using `api.resources.cfnResources.amplifyDynamoDbTables`.
