### ISSUE TITLE
RFC - Simplified @connection directive

### ISSUE THREAD

**Issue by anthonymoretti** [aws-amplify/amplify-category-api#305]
**Is your feature request related to a problem? Please describe.**

Using `@connection` with `keyName` is complex and using it with `name` requires extra naming work and its deletion behavior can be ambiguous. I've thought of a different approach that may be simpler, not sure.

**Describe the solution you'd like**

Maybe something like:

`@connection(reverseProperty: String!, propagateDeletion: Boolean!)`

And possibly a convenience directive:

`@connection(propagateDeletion: Boolean!)`

The term `reverseProperty` could also be `inverseProperty`, but either would make sense I think.

With this approach you don't need to think about:
- Keys
- Foreign key placement
- Ownership semantics like "belongs to" vs "has one"
- Naming connections or keys

Multiplicity and optionality are specified in the normal way (`[]`, `!`), and many-to-many relationships can either be explicit (using `[]` at both ends) or implicit (using two one-to-many relationships like can be done now).

I think it might make the model easier to reason about too. I haven't worked through it thoroughly or anything, just curious what people think.

Example:
```
type PhoneCall @model {
  id: ID!
  caller: Person! @connection(reverseProperty: "callerOf", propagateDeletion: false)
  callee: Person! @connection(reverseProperty: "calleeOf", propagateDeletion: false)
}

type Person @model {
  id: ID!
  name: String!
  callerOf: [PhoneCall!] @connection(reverseProperty: "caller", propagateDeletion: true)
  calleeOf: [PhoneCall!] @connection(reverseProperty: "callee", propagateDeletion: true)
}
```

**Comment by renebrandel** [comment]
Closing this out as we've tried to vastly simplify the relationship directives and separated them out by use cases "hasOne", "hasMany", "belongsTo", and "manyToMany" https://docs.amplify.aws/cli/graphql/data-modeling/#setup-relationships-between-models
