### ISSUE TITLE
CDK construct can't change and deploy a resolver if changed from @function to custom appsync JS resolver

### ISSUE THREAD

**Issue by jimjiminyjimjim** [aws-amplify/amplify-category-api#3057]
### Amplify CLI Version

12.2.5

### Question

Following on from this issue  #3003  - I can now deploy multiple GSI changes iteratively with the CDK construct. Thanks to @AnilMaktala and @sundersc 

The only issue now that seems to cause problems for multiple devs deploying their changes is if a resolver has been created with the `@function` and attached a lambda, then a dev changes this in the schema and replaces with a custom appsync JS resolver, we get the following error:

12:57:01 PM | CREATE_FAILED      
Resource already exists: arn:aws:appsync:us-west....
HandlerErrorCode: AlreadyExists)

In order to deploy we have to remove the `@function` code, deploy the Appsync api stack, then add our new appsync resolver to the schema and then deploy again.

This is a problem for the committing to a pipeline that deploys live as we'd need to deploy twice to switch changes live?

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
