### ISSUE TITLE
GraphQL: @auth on a single field gives write on all fields, delete on all entries

### ISSUE THREAD

**Issue by stelcheck** [aws-amplify/amplify-category-api#308]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

AppSync/GraphQL

**Amplify CLI Version** 

4.18.1

**What AWS Services are you utilizing?**

AppSync, DynamoDB, Cognito, S3

**Provide additional details e.g. code snippets**

Ref: https://docs.amplify.aws/cli/graphql-transformer/directives#combining-authorization-rules

Given the following GraphQL schema:

```graphql
type Post
  @model
  @auth(
    rules: [
      { allow: public, provider: iam, operations: [read] },
      { allow: private, provider: iam, operations: [read] }
    ]
  ) {
  id: ID!
  title: String!
  content: String
  viewCount: Int @auth(
    rules: [
      { allow: private, provider: iam, operations: [update] }
    ]
  )
}
```

I expect I should be able to mutate only the viewCount, but I am able to both mutate other fields and delete records. I don't know if this is a bug or it's supposed to work like this, but I was a bit surprised (scared?) when I found that out.

I'm assuming I misunderstood the documentation; isn't there a way to have a record be read-only, but still allow for updates on a single field?

**Comment by renebrandel** [comment]
closing this as in Transformer v2, we've moved to a deny-by-default authorization principle and we enforce the iam' unauthrole name in the AppSync resolver.
