### ISSUE TITLE
Enable/Disable DynamoDBStreams through Amplify CLI

### ISSUE THREAD

**Issue by zerox92** [aws-amplify/amplify-category-api#310]
I want to disable/disable DynamoDBStreams - but can't see where I should set this up in my Amplify project. DynamoDbStreams are enabled by default when I create an api.

**Amplify CLI Version**

4.20.0

I can see the api//build/stacks/

.json has a specification for Streams `StreamSpecification`. I can't see where I can put this in as a default value so that they are enabled/disabled at will.

Is there any way to add a new property to` amplify/backend/api/<api-name>/parameters.json` to achieve this?

**Comment by renebrandel** [comment]
Closing this out as we support this feature here: https://docs.amplify.aws/cli/usage/lambda-triggers/#as-a-part-of-the-graphql-api-types-with-model-annotation
