### ISSUE TITLE
@auth with Aurora serverless endpoints

### ISSUE THREAD

**Issue by sirceljm** [aws-amplify/amplify-category-api#334]
**Which Category is your question related to?**

Api

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.16.1

**What AWS Services are you utilizing?**

Api, DynamoDb, Cognito, Storage

**Provide additional details e.g. code snippets**

I have a project where I successfully generated DynamoDB tables with @auth directive in the graphql.schema file. I would also like to include some tables from my Aurora Serverless DB cluster like described in the docs: https://aws-amplify.github.io/docs/cli-toolchain/graphql#relational-databases I can access the data from the table but I haven't seen anywhere how to define `@auth` permissions in this case.

Does amplify cli support this right now? Do I need to write custom resolvers?

**Comment by renebrandel** [comment]
Hi - Thanks for raising this. We are looking to address this as an immediate priority via an upcoming release to GraphQL Transformer v2.

I would love to get your thoughts and feedback on the RFC with the details: https://github.com/aws-amplify/amplify-category-api/issues/815

**Comment by chrisbonifacio** [comment]
Closing this is as, while it's not currently possible to mix DynamoDB and Aurora datasources in an Amplify GraphQL Schema, it is possible to create a GraphQL schema for Aurora databases and the `@auth` directive to allow access to tables.

For more information on connecting to an Aurora or any SQL/PostgreSQL database, please refer to our documentation:
https://docs.amplify.aws/javascript/build-a-backend/graphqlapi/connect-api-to-existing-database

For mixing datasources, please track this feature request: https://github.com/aws-amplify/amplify-category-api/issues/2182
