### ISSUE TITLE
DataStore - support for String type id fields

### ISSUE THREAD

**Issue by mdwt** [aws-amplify/amplify-category-api#340]
I have a model which has a `id` field of type `String` instead of `ID`.

This causes the following error when running `amplify codegen models` (v4.13.4):
 
```
Error: id field on SettingDefinition should be of type ID
```

```
type SettingDefinition @model 
@key(fields: ["id"])
{
  id: String!
  ...
}
```

Is there a specific reason why only the ID type is supported for IDs in DataStore - or why a String ID will not work?

**Comment by davetbo-amzn** [comment]
I just hit this one as well. Any word on why DataStore doesn't support  pre-existing unique strings as IDs? There's no sense adding an artificial ID field if my data already has a unique key.

**Comment by renebrandel** [comment]
Hey - closing this out as we've launched this feature: https://aws.amazon.com/blogs/mobile/new-announcing-custom-primary-key-support-for-amplify-datastore/
