### ISSUE TITLE
Subscriptions with optional parameters only work as a filters on specific values 

### ISSUE THREAD

**Issue by rduhard** [aws-amplify/amplify-category-api#342]
**Describe the bug**
Codegen, for both iOS and Android, doesn't allow for subscriptions with optional parameters to be omitted, only for them to be nil. According to this: https://docs.aws.amazon.com/appsync/latest/devguide/real-time-data.html#argument-null-value-has-meaning, sending "null" vs not sending the param at all is treated differently. One filters on a null value, the other does not filter at all. Currently we are unable to achieve the latter because it is always sent as a nil value, and we're unable to omit the filter param altogether with the given API.

**Amplify CLI Version**
4.13.2

**To Reproduce**

1. Create a subscription that takes in 1 or more optional parameters
2. run codegen to generate API.swift
3. See that only one version of the subscription is generated that takes in optional params, which default to nil if not provided
4. When subscribing via the `subscribe` method, the `variables` object is passed to the server as `[param1: null]`

**Expected behavior**
Multiple subscription models that would allow for passing in both filter on nil and no filter at all. We would like to both filter on specific values (something or nil) and also to not filter i.e. 

1. `give me all messages with id="1"`
2. `give me all messages with id=null`
3. `give me all messages`

Currently we can only accomplish 1. and 2. but not 3. with the generated subscription model
My assumption is that for this to work, we'd need to generate more than one subscription model ( # of optional params ^ 2 ) as opposed to a single one that takes in optional values. This would allow for all 3 cases above to both be feasible. 

**Screenshots**
Schema definition
```
onDeleteMessage(messageThreadId: ID, messageId: ID): Message
	@aws_subscribe(mutations: ["deleteMessage"])
```

![image](https://user-images.githubusercontent.com/5777653/74383771-d5d6c000-4dbd-11ea-904f-54acf76579e9.png)
This is the code generated for a subscription that takes in 2 optional parameters. The problem is the `variables` property is always defined for both params, so there is no option provided to not filter on one or both of those params, only to filter on those parameters being a specific value (including the value nil).

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v13.3.0

**Additional context**

**Comment by sundersc** [comment]
@rduhard @Sedriq GraphQL API supports server side filtering now. You can use the filter argument instead of having an argument for each field you want to filter.
https://docs.amplify.aws/cli/graphql/data-modeling/#server-side-filtering-for-subscriptions
