### ISSUE TITLE
createdAt, updatedAt and id should not be required on inputs / mutations

### ISSUE THREAD

**Issue by malcomm** [aws-amplify/amplify-category-api#346]
**Note**: This is a blocker.

**Describe the bug**

Given the following sample schema:

```
type Foo
  @model
  @key(fields: ["id", "updatedAt"])
{
  id: ID!,
  updatedAt: AWSDateTime!
```

In order to create/update a Foo, I am required to supply an ```updatedAt```:
```
    const input: UpdateFooInput = {
      id: this.foo.id,
      updatedAt: moment().toISOString()
    };
```
```
    const input: CreateFooInput = {
      updatedAt: moment().toISOString()
    };
```

```createAt``` and ```updatedAt``` should not be required. I'm OK with them being optional, but I can see an argument for them to be treated as special and not messed with at all.

**Amplify CLI Version**

4.13.1

**To Reproduce**

Create a model with above primary index with a sort key.

**Expected behavior**

```createAt``` and ```updatedAt``` should not be required.

**Additional context**
aws-amplify/amplify-cli#401 
aws-amplify/amplify-cli#3347

**Comment by renebrandel** [comment]
This issue is addressed now. Given this schema:
```graphql
type Note @model @auth(rules: [
  { allow: public, operations: [read] },
  { allow: owner }]) {
  id: ID! @primaryKey(sortKeyFields: ["createdAt"])
  title: String
  content: String @index
  createdAt: AWSDateTime!
}
```

The mutation request went through:
![image](https://github.com/aws-amplify/amplify-category-api/assets/4989523/098e3f24-163b-417e-8e43-5cf5461bc227)
