### ISSUE TITLE
Changes in production

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-category-api#348]
Hi,

If I understood correctly, new attributes for objects in a graphql.schema do not change ancient saved objects, but what happens if we make errors by removing attributes ?

Is there a warning message to prevent deleting old objects ?

**Comment by renebrandel** [comment]
Closing this out as there a few paths forward now on this issue:
- Multi environment workflows: https://docs.amplify.aws/cli/teams/sandbox/
- Destructive update prevention: https://docs.amplify.aws/cli/graphql/overview/#iterating-on-your-data-model-using-the-graphql-schema
