### ISSUE TITLE
Code generator does not generate proper code for timestamps when using Aurora

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-category-api#354]
**Describe the bug**
When using `TIMESTAMP(0)` or `TIMESTAMP(3)` in the SQL database, codegen interprets that as AWSTimestamp, which seems right, but the problem is that when using `"SELECT * FROM User"`, all TIMESTAMP fields are printed like:
`"2019-12-19 16:59:09.966"`
Because of that, the mapping fails. with:
`"Can't serialize value (/loggedUser/dob) : Unable to serialize `2019-12-19 16:59:09.966` as a valid timestamp. Ensure that the value provided is an Integer that lies within the limits specified in this scalar's description."`

I found a workaround to fix this temporally, basically, doing this:
SELECT cast(UNIX_TIMESTAMP(dob) as unsigned) as dob FROM User WHERE user = "whatever"

That's working, but the problem is that I cannot use `"SELECT * FROM User"` in the velocity templates, which is very annoying, especially when you add new fields and you have to modify several templates. This is prone to error.

How to fix that? I don't that, but the second issue is exactly the same as this ticket?
https://github.com/aws-amplify/amplify-cli/issues/3049

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

**To Reproduce**
Just use Aurora serveless as a data source and generate the API using amplify command line tool.
Make sure you use TIMESTAMP(0) in your entities.
Now, call a method from API.swift that uses an entity with timestamp.  It will fail with the error mapping I said above. 

**Expected behavior**
The code generation should generate code that fixes this issue automatically. How? To be honest, I don't know. I think the trick is in the "SELECT *" part.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v13.2.0

**Additional context**
The "SELECT * FROM..." issue is the same as:
https://github.com/aws-amplify/amplify-cli/issues/3049

**Comment by renebrandel** [comment]
Hi - Thanks for raising this. We are looking to address this as an immediate priority via an upcoming release to GraphQL Transformer v2.

I would love to get your thoughts and feedback on the RFC with the details: https://github.com/aws-amplify/amplify-category-api/issues/815

**Comment by chrisbonifacio** [comment]
Closing this as it is not reproducible on the current feature support for connecting to existing SQL/PostgreSQL databases using the AmplifyGraphqlApi CDK construct.

Here's the SQL schema I used to reproduce the issue

```sql
create table datatypes
(
    id           varchar(255)   not null
        primary key,
    `char`       char(128)      null,
    `varchar`    varchar(255)   null,
    `tinytext`   tinytext       null,
    text         text           null,
    `mediumtext` mediumtext     null,
    `longtext`   longtext       null,
    geometry     geometry       null,
    point        point          null,
    linestring   linestring     null,
    `tinyint`    tinyint        null,
    `smallint`   smallint       null,
    `mediumint`  mediumint      null,
    `int`        int            null,
    `bigint`     bigint         null,
    `float`      float          null,
    `double`     double         null,
    `decimal`    decimal(10, 5) null,
    date         date           null,
    datetime     datetime       null,
    timestamp    timestamp      null,
    time         time           null,
    year         year           null,
    `binary`     binary(128)    null,
    `varbinary`  varbinary(128) null,
    `tinyblob`   tinyblob       null,
    `blob`       blob           null,
    `mediumblob` mediumblob     null,
    `longblob`   longblob       null,
    bit          bit            null,
    json         json           null,
    geometrycollection geomcollection null,
    polygon      polygon        null,
    multipoint   multipoint     null
);

create table posts
(
    id              varchar(40)          not null
        primary key,
    title           varchar(255)         null,
    content         varchar(255)         not null,
    published       tinyint(1) default 0 not null,
    blog_id         varchar(255)         not null,
    published_date  datetime             null,
    last_changed_at timestamp            null
);

```

which maps to the following GraphQL Schema when using codegen:

```graphql
type Datatype
  @refersTo(name: "datatypes")
  @model
  @auth(rules: [{ allow: public }]) {
  id: String! @primaryKey
  char: String
  varchar: String
  tinytext: String
  text: String
  mediumtext: String
  longtext: String
  geometry: String
  point: String
  linestring: String
  tinyint: Int
  smallint: Int
  mediumint: Int
  int: Int
  bigint: Int
  float: Float
  double: Float
  decimal: Float
  date: AWSDate
  datetime: AWSDateTime
  timestamp: AWSDateTime
  time: AWSTime
  year: Int
  binary: String
  varbinary: String
  tinyblob: String
  blob: String
  mediumblob: String
  longblob: String
  bit: Int
  json: AWSJSON
  geometrycollection: String
  polygon: String
  multipoint: String
}

type Post @refersTo(name: "posts") @model @auth(rules: [{ allow: public }]) {
  id: String! @primaryKey
  title: String
  content: String!
  published: Int @default(value: "0")
  blogId: String! @refersTo(name: "blog_id")
  publishedDate: AWSDateTime @refersTo(name: "published_date")
  timestamp: AWSDateTime
}
```

Please note that `bool` is implemented by the `tinyint` SQL type and you can use `1` or `0` as the values for `true` or `false` respectively.

manually mapping the graphql type to Boolean also works.

Here's the mutation I attempted

```graphql
mutation MyMutation {
  createDatatype(input: {timestamp: "2021-10-21T07:21:25.803Z", int: 1, text: null}) {
    text
    int
    timestamp
  }
  createPost(input: {blogId: "1", content: "Test Post", published: 0}) {
    published
  }
}
```

And the response

```json
{
  "data": {
    "createDatatype": {
      "text": null,
      "int": 1,
      "timestamp": "2021-10-21T07:21:26.000Z"
    },
    "createPost": {
      "published": 0
    }
  }
}
```
