### ISSUE TITLE
Ability to use GraphiQL to connect to AppSync

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-category-api#370]
**Is your feature request related to a problem? Please describe.**
There are multiple `@searchable` directives in my project's schema so using `amplify mock` has many limitations for my local dev. 

**Describe the solution you'd like**
I'd like to be able to launch a local GraphiQL to connect to AppSync instead of using the AppSync console.
 
**Describe alternatives you've considered**
Building it myself.

**Comment by AnilMaktala** [comment]
Hey @kldeb, Apologies for the incredible delay in the response.  We have implemented this feature. Please refer [here](https://aws.amazon.com/blogs/mobile/new-improved-data-management-in-amplify-studio/) for more details.
