### ISSUE TITLE
AWSDateTime scalar is not currently supported by RDS datetime type

### ISSUE THREAD

**Issue by MaximumCrash** [aws-amplify/amplify-category-api#386]
**Describe the bug**
This is more of an issue with AppSync and RDS, I've already put in a ticket with them and the feature/bug ticket has been put in with the Amazon team. But I thought it'd be good to alert this community on this particular issue. 

When pulling in an RDS datasource and a table has a column of a datetime type, the graphql-transformer applies the AppSync scalar AWSDateTime (as expected). The issue however is that the format of AWSDateTime **(YYYY-MM-DDThh:mm:ss.sssZ)** conflicts with the expected MySQL format of Datetime types **(YYYY-MM-DD HH:MM:SS.sss)**.

My temporary solution is to change all AWSDateTime scalars to strings and use the MySQL datetime format.

**To Reproduce**
1. Create an RDS cluster, database, and simple table with a column that has a datetime type. 
2. Create a javascript project with amplify. 
3. Add a RDS datasource (MySQL 5.6 Aurora Serverless)
5. See the graphql.schema with AWSDatetime scalars (as expected)
6. Try running a mutation to create a record in the RDS datasource using the expected AWSDateTime format. 
7. See the error returned from RDS

**Expected behavior**
My hope was that RDS datetimes would support the AWSDateTime format out the box, but this is an internal conflict between services.

**Comment by renebrandel** [comment]
Hi - Thanks for raising this. We are looking to address this as an immediate priority via an upcoming release to GraphQL Transformer v2.

I would love to get your thoughts and feedback on the RFC with the details: https://github.com/aws-amplify/amplify-category-api/issues/815

**Comment by chrisbonifacio** [comment]
Closing this as the API generated by AmplifyGraphqlApi seems to have addressed this issue.

Here is an example of a mutation using the same datetime value that reproduced the following error: `RDSHttp:{"message":"Database error code: 1292. Message: Data truncation: Incorrect datetime value: '2021-10-21T07:21:25.803Z' for column 'modified' at row 1"`

![CleanShot 2024-02-02 at 18 11 23](https://github.com/aws-amplify/amplify-category-api/assets/16952986/4461f802-aadd-4643-8bdc-280602e3b71e)

GraphQL Schema:

```graphql
type Post @refersTo(name: "posts") @model @auth(rules: [{ allow: public }]) {
  id: String! @primaryKey
  title: String
  content: String!
  published: Int @default(value: "0")
  blogId: String! @refersTo(name: "blog_id")
  publishedDate: AWSDateTime @refersTo(name: "published_date")
}
```
MySQL Schema

```sql
create table posts
(
    id             varchar(40)          not null
        primary key,
    title          varchar(255)         null,
    content        varchar(255)         not null,
    published      tinyint(1) default 0 not null,
    blog_id        varchar(255)         not null,
    published_date datetime             null
);
```
