### ISSUE TITLE
more than one add-graphql-datasource per api

### ISSUE THREAD

**Issue by oste** [aws-amplify/amplify-category-api#388]
I think it would be amazing if `add-graphql-datasource` supported the ability to add more than one database to a single API. Currently, I am able to add a second datasource but push fails with `The following resource(s) failed to create: [RelationalDatabaseAccessRole].` error.

Since @ashwindevendran worked on the intial feature I was wondering if you can provide more details on if this is currently possible with a workaround or what it would take to make this possible. Definitely interested in helping out where I can. Thanks!

**Comment by renebrandel** [comment]
This is now supported in our new CDK-based integration for MySQL/PostgreSQL databases. https://docs.amplify.aws/react/build-a-backend/graphqlapi/connect-api-to-existing-database/
