### ISSUE TITLE
Support for dynamic groups subscriptions with @auth 2.0

### ISSUE THREAD

**Issue by rawadrifai** [aws-amplify/amplify-category-api#389]
**Is your feature request related to a problem? Please describe.**
This related to https://github.com/aws-amplify/amplify-cli/issues/1043
Subscriptions auth is not sophisticated enough to support a generic use case, a messenger like Slack. The reason is lack of support for Dynamic groups in the 2.0 update for the cli. 

Take a very simple use case. A user inserts a message record in the messages table. The message is directed at a channel. The members of the channel are dynamic and may change anytime. Subscriptions should be aware of who belongs in the channel.

Static groups cannot possibly support a use case like this. Every message comes with different permissions, depending whether it's a channel message, a conversation, a group conversation, etc. I tried to design it with static groups, it's just impossible.

**Describe the solution you'd like**
Subscriptions should support dynamic groups.
For the developer it should be as simple as:
```
onCreateMessage.subscribe($filter)
```
If there is no filter, it sends events for all messages that the user subscribing is authorized to see. Mimic what is done for queries. Same behavior. *** If I can read it, I should get an event. ***

If a filter is provided, it applies additional filtering on an attribute provided in the filter. 

**Describe alternatives you've considered**
I am considering using the owner field instead with an array of strings. So every message would contain all of the users that are authorized to see it. That is of course very inefficient but it's the only thing possible today.

**Additional context**
I think Amplify will render itself unusable if dynamic groups are not support by subscriptions auth. We are trying to push for the best for the framework. We are too deep in it now to change frameworks, so we hope you would support this as soon as possible.

**Comment by djorgji** [comment]
Hi. Any updates to this feature implementation? Thanks.

**Comment by maziarzamani** [comment]
So it's been some years now. Any updates on this issue?

**Comment by sundersc** [comment]
Dynamic group auth is supported for subscriptions now. Refer the blog for more details.
https://aws.amazon.com/blogs/mobile/new-real-time-multi-group-app-with-aws-amplify-graphql-build-a-twitter-community-clone/

**Comment by brendjuan** [comment]
Any updates on support in DataStore?
