### ISSUE TITLE
Support field-level values with @auth

### ISSUE THREAD

**Issue by CodySwannGT** [aws-amplify/amplify-category-api#394]
**Is your feature request related to a problem? Please describe.**
We run into the problem a lot where the owner of an object should be able to update the status to one value but not the other.

For example, a ticket listing. The owner of the ticket should be able to change the status to "ACTIVE" and "INACTIVE" but not "SOLD"

Same thing for a counter cache. Again, using a ticket listing, the owner should be able to set bidCount to 0 but not to anything else when creating the listing

**Describe the solution you'd like**
I'd like the @auth transform to support a list of allowable values

**Describe alternatives you've considered**
To get around this, we have to write a bunch of custom resolvers and mutations.

I.e. buyListing, updateListingToInactive, or implement DynamoDB streams to set default values, as is the case with bidCount

**Comment by AnilMaktala** [comment]
Hey @CodySwannGT, Apologies for the incredible delay in the response. This feature was supported by field level auth rules. Please refer [here](https://docs.amplify.aws/cli/graphql/authorization-rules/#field-level-authorization-rules) for more info.
