### ISSUE TITLE
Specify claims group field in auth directive

### ISSUE THREAD

**Issue by RossWilliams** [aws-amplify/amplify-category-api#403]
**Is your feature request related to a problem? Please describe.**
I need to use claims information in addition to the cognito groups to apply authentication rules. I would like to specify the identifyField for groups in a similar manner as exists for owners.
While I could overload the owner rule to have many owners, it produces ugly code that is hard to audit.

**Describe the solution you'd like**

graphql-auth-transformer/src/resources.ts has a TODO comment:
// TODO: Enhance cognito:groups to work with non cognito based auth.
There may be a straightforward way to allow this by overloading setUserGroups to take an optional "identityField" string.

I would like the setUserGroups function to take an optional "identityField" string to override "cognito:groups" as the claim to check against.

**Describe alternatives you've considered**
I could use the preToken Lambda to overload "cognito:groups" claim information, but I'd rather keep these systems separate and be clear what claims come from cognito user pools and what comes from other sources.

**Additional context**
Attached is a patch file based on 54a8d that accomplishes the basics with ~12 lines changed. You may want to consider a name other than identityField if you don't want to overload terminology
[patch.txt](https://github.com/aws-amplify/amplify-cli/files/3433378/patch.txt)

**Comment by AnilMaktala** [comment]
Hey @RossWilliams , Apologies for the incredibly late response. Wanted to make sure that the future readers see the resolution.
We have implemented this feature. Please refer [here](https://docs.amplify.aws/cli/graphql/authorization-rules/#configure-custom-identity-and-group-claims) for more details.
