### ISSUE TITLE
 Region choice issue while running the command "amplify api add-graphql-datasource"

### ISSUE THREAD

**Issue by tonykimisinthehouse** [aws-amplify/amplify-category-api#406]
** Which Category is your question related to? **
Configuration for a new project.

** What AWS Services are you utilizing? **
Cognito, RDS, etc

** Provide additional details e.g. code snippets **
The new project will run on us-west-3 region.
I already created my serverless aurora in us-west-2, but there is no way to other region other than us-east-1.

Did I do something wrong or is there any reasons?

**Comment by renebrandel** [comment]
our new integration supports any MySQL/PostgreSQL database reachable behind a VPC or outside of a VPC. https://docs.amplify.aws/react/build-a-backend/graphqlapi/connect-api-to-existing-database/
