### ISSUE TITLE
Support subdirs into API/resolvers

### ISSUE THREAD

**Issue by gurobokum** [aws-amplify/amplify-category-api#411]
**Is your feature request related to a problem? Please describe.**
I would like to build complex graphql and custom resolvers and store them into subfolders. Right now when I try to push resolvers tree(I use custom `AppSync::Resolver` with right template location) I get 
```
EISDIR: illegal operation on a directory, read  
``` 

**Describe the solution you'd like**
Generate list of resolvers through fs tree traversal, https://github.com/aws-amplify/amplify-cli/blob/a61237ff51a26fbf93ee423b43a34d89c06acf57/packages/graphql-transformer-core/src/util/amplifyUtils.ts#L234
I can provide `PR` if needs

**Comment by AnilMaktala** [comment]
Hey @gurobokum , Apologies for the incredibly late response. Wanted to make sure that the future readers see the resolution.
We handed over the control from resource management to customer to implement this in graphql transformer version V2. Please refer [here](https://docs.amplify.aws/cli/graphql/custom-business-logic/#vtl-resolver) for more details.
