### ISSUE TITLE
GraphQL relationship with RDS Aurora 

### ISSUE THREAD

**Issue by danielphung90** [aws-amplify/amplify-category-api#414]
** Which Category is your question related to? **
GraphQL schema

** What AWS Services are you utilizing? **
Appsync

** Provide additional details e.g. code snippets **
What I wanna do is link the type into another type after generate the schema from RDS aurora serverless 
Is there any way to do that or I need to create the resolver file by myself ?

**Comment by renebrandel** [comment]
https://docs.amplify.aws/react/build-a-backend/graphqlapi/connect-api-to-existing-database/ you can now generate a GraphQL schema based on any MySQL/PostgreSQL database and also add relationship fields.
