### ISSUE TITLE
amplify add api requires "Provide a custom type name"

### ISSUE THREAD

**Issue by oste** [aws-amplify/amplify-category-api#418]
**Describe the bug**
When using the `amplify add api` command it asks for `Provide a custom type name`. This is not always necessary. I immediately followed up with `amplify api add-graphql-datasource` to add a aurora serverless data source. This results in unnecessary Dynamo db tables being created and extra schema added.

**Expected behavior**
Option to skip Dynamo table creation.

**Comment by renebrandel** [comment]
This issue should be addressed in your new integration with MySQL / PostgreSQL https://docs.amplify.aws/react/build-a-backend/graphqlapi/connect-api-to-existing-database/
