### ISSUE TITLE
GraphQL Codegen max_length directive - Input validation

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/amplify-category-api#419]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when users abuse my API and circumvent my form validation by manually triggering API calls.
To be honest that didn't happen yet, but it could.

**Describe the solution you'd like**
It would be cool to be able to restrict API access by max length of the data similar to how `@auth` restricts on an owner basis.

E.g.

```graphql
type Blog @model {
  id: ID!
  name: String! @max_length(100)
  posts: [Post] @connection(name: "BlogPosts") @max_length(1000)
}
```

Would result in requests that have longer name throwing an error. And each blog could only have a thousand posts (which would be bad UX, but its just an example 😄 ).

**Describe alternatives you've considered**
The only alternative I could think of would be to write custom resolvers that check the length of the data in the `.req.vtl` template.

**Comment by josefaidt** [comment]
Closing in favor of tracking existing feature request for field validation https://github.com/aws-amplify/amplify-category-api/issues/447
