### ISSUE TITLE
Error in GQL Compile re Many-to-Many Detection

### ISSUE THREAD

**Issue by nagey** [aws-amplify/amplify-category-api#435]
**Describe the bug**
When setting up a reflexive belongs-to connection, the order of the fields can trick the compiler into thinking that it's a many-to-many connection.

**To Reproduce**
If you create a model like so:
```
type Task @model @searchable @versioned {
  id: ID!
  blockedBy: Task @connection(name: "BlockedBy")
  blocks: [Task] @connection(name: "BlockedBy")
```
the compiler will work fine.

However, if you change the order of `blocks` and `blockedBy` the compiler will think that it's a many-to-many and throw an error. 

This model, for example, will not compile:
```
type Task @model @searchable @versioned {
  id: ID!
  blocks: [Task] @connection(name: "BlockedBy")
  blockedBy: Task @connection(name: "BlockedBy")
```

**Expected behavior**
Distinguish between many-to-many connections and belongs-to connections properly regardless of field order.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.4
 - Amplify Version 1.1.4

**Smartphone (please complete the following information):**
n/a

**Comment by renebrandel** [comment]
Hi - we've addressed this issue in the GraphQL Transformer v2 now with more explicit relationships directives. Both of the following schemas work and compile as expected:

```graphql
type Task @model @auth(rules: [{ allow: public }]) {
  blockedBy: Task @belongsTo
  blocks: [Task] @hasMany
}
```

```graphql
type Task @model @auth(rules: [{ allow: public }]) {
  blocks: [Task] @hasMany
  blockedBy: Task @belongsTo
}
```
