### ISSUE TITLE
in single schema a second query and mutation section is ignored by schema compiler

### ISSUE THREAD

**Issue by ryanhollander** [aws-amplify/amplify-category-api#436]
**Describe the bug**
in single schema a second query and mutation section is ignored by schema compiler.

**To Reproduce**

create schema.graphql:
===

type A@model(queries: null, mutations: null) { id: ID!, name: String }
type B@model(queries: null, mutations: null) { id: ID!, name: String }
type Mutation {
   createA(id: ID!): A
}
type Query {
   getA(id: ID!): A
}
type Mutation {
   createB(id: ID!): B
}

===
**Expected behavior**
Since this isn't valid the compiler should throw an error, instead it just ignores the extra entries. It would be better if it merged them, but I think the correct behavior is to throw an error so the programmer can correct the file. 

Thank You.

**Comment by renebrandel** [comment]
This is resolved as part of GraphQL Transformer v2. We now through this error:
```
🛑 Schema validation failed.

There can be only one type named "Mutation".

GraphQL request:7:6
6 | type B@model(queries: null, mutations: null) { id: ID!, name: String }
7 | type Mutation {
  |      ^
8 | createA(id: ID!): A

GraphQL request:13:6
12 | }
13 | type Mutation {
   |      ^
14 | createB(id: ID!): B
```

**Comment by ryanhollander** [comment]
Thanks @renebrandel - does that include support for the "extend" keyword?
