### ISSUE TITLE
Allow configure auth types for REST API using CLI

### ISSUE THREAD

**Issue by HuiSF** [aws-amplify/amplify-category-api#464]
### Is this feature request related to a new or existing Amplify category?

api

### Describe the feature you'd like to request

Today Amplify CLI doesn't support configuring auth type for a REST API path. 

<img width="775" alt="image" src="https://user-images.githubusercontent.com/10602282/169394759-02c98d8c-68fb-49f2-8e23-97f8f78ddc80.png">

In Amplify native platform libraries documentation (e.g. [amplify-ios](https://docs.amplify.aws/lib/restapi/authz/q/platform/ios/)), it instructs to manually modify generated amplify configuration files to use other auth types for a REST API other than the default IAM. This is working, but the pain point is there is no way to persist this manual change, every time when run `amplify push` or `amplify pull` the manual change will be reverted back to the default IAM config.

As a developer, I want to use CLI to configure auth types for a REST API path I added, like the way that how I configure auth types for of a GraphQL API. And I want this configuration to be persisted, that I don't need to manually modify amplify configuration file.

### Describe the solution you'd like

1. `amplify add api` and `amplify update api` should provide a path to configure auth types for a REST API path

### Describe alternatives you've considered

Manually modify amplify configuration file following https://docs.amplify.aws/lib/restapi/authz/q/platform/ios/

### Additional context

Original customer issue aws-amplify/amplify-category-api#466

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Hey @HuiSF :wave: thanks for raising this! While you can leverage [REST API overrides](https://docs.amplify.aws/cli/restapi/override/) to add and persist Cognito authorizers, etc., it makes sense to have this support for additional auth mechanisms out-of-the-box. 

Marking this issue as a duplicate feature request of the issues below:

- feature request for REST API Cognito authorizer https://github.com/aws-amplify/amplify-category-api/issues/345
- feature request for general expansion of REST API auth https://github.com/aws-amplify/amplify-category-api/issues/438

**Comment by josefaidt** [comment]
Closing in favor of tracking existing requests
