### ISSUE TITLE
Updating an "enum" field through lambda does not work.

### ISSUE THREAD

**Issue by rafaelfaria** [aws-amplify/amplify-category-api#49]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.22.0

### Amplify CLI Version

8.0.2

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes mad

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

I have my whole application setup and working 100%.

I have a schema (which I will describe in its section) where I have a few fields, as well as a couple of enum fields.

I'm using React + typescript so, in the front-end, everything works fine. I am able to call graphql and create and update without any dramas.

Frontend example (uses typescript)
```js
    const { data } = await API.graphql(
      graphqlOperation(createUser, { input: { name: 'Rafael', email: 'rafael@gmail.com', membership: Membership.GOLD  } })
    ) as CreateUserResult;
```

The issue is, that now I need to make updates to the same model in the backend through a lambda. So I create the lambda function, added the graqphl auth, and the methods to make the graphql call in the backend. 
So far so good, I made a couple of tests, and I am able to update different models using mutations. HOWEVER, when a mutation has ENUM properties, I cannot make it work. 

In the backend I do not use typescript, so I can't use enums, since enums is really a translation of strings, I tried to send strings, and it wouldn't throw any error, it would just do NOT update.

```js
   await graphQLRun(createUser, { input: { name: 'Rafael', email: 'rafael@gmail.com', membership: 'GOLD' } });
```
PS: graphQLRun is the method I call for all my lambdas to make calls to graphql.

I have no idea what else to try.  This sounds to me like a bug since the value should really be translated to a string anyway, we should be able to just send a string to the enum property and this should work.

### Expected behavior

I should be able to just use a string as the value and it should've worked.

### Reproduction steps

1. Create the schema below
2. Create a new function
3. Create methods to send graphql requests
4. In the lambda, send a mutation request that contains an enum value but uses a string
5. Nada! Does not update.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type User @model(subscriptions: null)
  @auth(
    rules: [
      { allow: owner, ownerField: "username" }
      { allow: private, operations: [read, update], provider: iam },
      { allow: groups, groups: ["Admin"] }
    ]
  )
{
  id: ID!
  email: String!
  name: String!
  membership: Membership!
}



enum Membership {
  ADMIN
  BRONZE
 SILVER
GOLD
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @rafaelfaria just wanted to follow up here and see if you were still experiencing this?

**Comment by rafaelfaria** [comment]
@josefaidt It seems to be working now. We can close the thread.

**Comment by duranmla** [comment]
I am having the same exact problem with the `Membership` use case:

I do have a file to "abstract" my requests like so:

```js
const https = require('https')
const AWS = require('aws-sdk')
const urlParse = require('url').URL
const appsyncUrl = process.env.API_SOL_GRAPHQLAPIENDPOINTOUTPUT
const region = process.env.REGION
const endpoint = new urlParse(appsyncUrl).hostname.toString()

exports.requestAppSync = async ({ variables, query, operationName }) => {
  console.log(`@appSync ${operationName} with`, {
    variables,
    query,
    operationName,
  })
  const req = new AWS.HttpRequest(appsyncUrl, region)

  req.method = 'POST'
  req.path = '/graphql'
  req.headers.host = endpoint
  req.headers['Content-Type'] = 'application/json'
  req.body = JSON.stringify({
    query,
    operationName,
    variables,
  })

  const signer = new AWS.Signers.V4(req, 'appsync', true)
  signer.addAuthorization(AWS.config.credentials, AWS.util.date.getDate())

  const response = await new Promise((resolve, reject) => {
    const httpRequest = https.request({ ...req, host: endpoint }, (result) => {
      let data = ''

      result.on('data', (chunk) => {
        data += chunk
      })

      result.on('end', () => {
        resolve(JSON.parse(data.toString()))
      })
    })

    httpRequest.write(req.body)
    httpRequest.end()
  })

  console.log(`@appSync ${operationName} resolved`, response)

  if (response.errors && response.errors.length > 0) {
    throw new Error(`@appSync ${operationName}: ${response.errors[0].message}`)
  }

  // operation name with first character to lowercase
  const gqlResultName = `${operationName[0].toLowerCase()}${operationName.slice(1)}`
  console.log(`@appSync ${operationName} return`, response.data[gqlResultName])
  return response.data[gqlResultName]
}

const crypto = require('@aws-crypto/sha256-js')
const { defaultProvider } = require('@aws-sdk/credential-provider-node')
const { SignatureV4 } = require('@aws-sdk/signature-v4')
const { HttpRequest } = require('@aws-sdk/protocol-http')
const fetch = require('node-fetch')
const { Request } = require('node-fetch')
const { Sha256 } = crypto

exports.requestAppSyncV2 = async ({ variables, query }) => {
  console.log(`@appSync V2 with`, {
    variables,
    query,
  })

  const endpoint = new URL(appsyncUrl)
  const signer = new SignatureV4({
    credentials: defaultProvider(),
    region,
    service: 'appsync',
    sha256: Sha256,
  })

  const requestToBeSigned = new HttpRequest({
    method: 'POST',
    headers: {
      host: endpoint.host,
    },
    hostname: endpoint.host,
    body: JSON.stringify({
      query,
      variables,
    }),
    path: endpoint.pathname,
  })

  const signed = await signer.sign(requestToBeSigned)
  const request = new Request(endpoint, signed)

  let body
  let response

  response = await fetch(request)
  body = await response.json()

  console.log(`@appSync V2 resolved`, response, body)

  if (body.errors && body.errors.length > 0) {
    throw new Error(`@appSync V2: ${body.errors[0].message}`)
  }

  console.log(`@appSync V2 return`, body.data)

  return body.data
}
```

And as I am working with Stripe subscriptions, membership receives a stripe subscription Id in a web-hook event and status update in another web-hook event. Like so: `customer.subscription.created`, `customer.subscription.updated` for subscription ID update and then `payment_intent.succeeded` for the status update.

```js
    case 'customer.subscription.created':
    case 'customer.subscription.updated':
      const stripeSubscriptionId = event.data.object.id
      const trackingId = `subscription-${event.data.object.customer}`
      // THIS WORKS!!
      await updateMembershipByTrackingId(trackingId, {
        stripeSubscriptionID: stripeSubscriptionId,
      })
      break

    case 'payment_intent.succeeded':
    try {
        let order
        const trackingId = `subscription-${event.data.object.customer}`
        ...

        if (product.type === 'MEMBERSHIP') {
          // THIS GETS EXECUTED BUT IT DOES NOT WORK
          await updateMembershipByTrackingId(trackingId, {
            status: 'ACTIVE',
          })
        }
```

As you can see I am using the same method in two different times and the first works but the later does not.

```js
const updateMembershipByTrackingId = async (trackingId, membershipData) => {
  const membership = (
    await findByAttribute({
      attrName: 'trackingID',
      attrValue: trackingId,
      table: 'Membership',
    })
  )[0]

  const response = await updateMembership({
    id: membership.id,
    ...membershipData,
  })

  return response
}
```

**Comment by duranmla** [comment]
@rafaelfaria do you remember what you have done to arrive to a working state here?
