### ISSUE TITLE
After migration from V1 to V2 Groups failing  in search resolvers.

### ISSUE THREAD

**Issue by n-francky** [aws-amplify/amplify-category-api#504]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.7.0

### Amplify CLI Version

8.2.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no manual changes made

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

After a migration from v1 to v2 and changing our schema to meet the requirements from the official document [GraphQL Transformer v1 to v2 migration](https://docs.amplify.aws/cli/migration/transformer-migration/). 
Then while testing we noticed that we were not able to search all records a user had rights to, users could only see records that they own/ created. 

After a long day of debugging and try to find what went wrong. We noticed that the auto generated VTLs for the auth.req (Query.searchReceivers.auth.1.req.vt) was missing the `.keyword` when setting our groups.
e.g: Before:
```#set( $group1 = {
  "terms_set": {
      "groupsCanRead": { 
          "terms":       $util.defaultIfNull($ctx.identity.claims.get("cognito:groups"), ["___xamznone____"]),
          "minimum_should_match_script": {
              "source": "1"
      }
    } 
```

Then by creating a custom resolver and adding the `.keyword` like this. it started working.

```#set( $group1 = {
  "terms_set": {
      "groupsCanRead.keyword": { <---- added the missing keyword
          "terms":       $util.defaultIfNull($ctx.identity.claims.get("cognito:groups"), ["___xamznone____"]),
          "minimum_should_match_script": {
              "source": "1"
      }
    }
```

### Expected behavior

To be able to search and retrieve all the records that the user owns and has rights to.

### Reproduction steps

1. Model with owner and group auth rules
2. Amplify push api
3. Search for records using the rules

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Receiver
  @model
  @auth(
    rules: [
      { allow: owner, ownerField: "creatorId" }
      { allow: groups, groupsField: "groupsCanRead", operations: [read] }
      { allow: groups, groupsField: "groupsCanUpdate", operations: [update] }
      { allow: groups, groupsField: "groupsCanDelete", operations: [delete] }
      { allow: groups, groupsField: "admins" }
    ]
  )
  @searchable {
  id: ID!
.......
}

```

</details>

### Log output

<details>

```
# Put your logs below this line

```

</details>

**Comment by n-francky** [comment]
hello @ykethan  Any updates on this?

**Comment by phani-srikar** [comment]
Please upgrade your version of CLI and re-open if the issue still exists.
