### ISSUE TITLE
Imported AppSync API not recognized by Amplify Hosting automated aws-exports file generation for backend build

### ISSUE THREAD

**Issue by samburton4655** [aws-amplify/amplify-category-api#506]
Hey all, I am deploying an application using Amplify Hosting. It utilizes storage, auth, and an AppSync API. However, this API was created by a separate amplify project and thus was imported into my current project via amplify add codegen --apiId xxxxx. By running this in my local aws-exports I have:

    "aws_appsync_graphqlEndpoint": "https://xxxxxxxxxxxxxxxx.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "xxxxxxxxxxxxxxxx"

which allows for local builds (npm start) to use the API. I am also able to run amplify codegen to generate any necessary local files. However, when I deploy my application using Amplify Hosting, this imported API is not added as part of the backend build. Upon looking through my backend build logs it seems that only my storage and auth resources are getting "recognized" by Amplify when it "auto-detects" my backend resources and automatically generates my aws-exports file for the build. My website builds fine, it just can't use the API because "no graphql endpoint is provided". 

Can anyone provide insight into how this can be fixed? Is it a bug? Any help is appreciated!

Edit for more clarification: All resources are sitting in the same AWS account, but the API was created by an entirely different Amplify App via the CLI then imported into my current app via the CLI as well.

**Comment by samburton4655** [comment]
Does anyone have any input on this? I can't figure out a way to connect my application to the AppSync API without hard coding an API key into the app. How can I have imported AppSync API endpoint information generated inside my aws-config file on backend deployment? Or is there a workaround I'm missing that doesn't require hard coding the API key?

**Comment by ykethan** [comment]
Hello @samburton4655, thank you for reaching out. The aws-config files when utilizing a API key will be public to view. Please refer to https://docs.amplify.aws/cli/reference/files/#aws-exportsjs. Additionally, please refer to our documentation here on reusing an existing API: https://docs.amplify.aws/lib/graphqlapi/create-or-re-use-existing-backend/q/platform/js/#using-apikey

**Comment by odafeaggreh** [comment]
hello @ykethan the second link you sent now leads to a 404 page. I would appreciate the help as I am having this same problem at the moment.

**Comment by AaronZyLee** [comment]
Since the API is imported from existing resource, it will not update the config during a normal `amplify push`. However, you can still use `amplify push --force` to update both backend meta and aws config files in this scenario.
