### ISSUE TITLE
Amplify Mock - Failed to get credentials: Rate exceeded Failed to get credentials: Rate exceeded

### ISSUE THREAD

**Issue by MeghTrivedi** [aws-amplify/amplify-category-api#51]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

curl

### If applicable, what version of Node.js are you using?

v12.13.0

### Amplify CLI Version

7.6.26

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made. 

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

When running amplify mock, this error always occurs:

`Failed to get credentials: Rate exceeded
`

### Expected behavior

amplify mock should run. 

### Reproduction steps

1. run amplify mock in appropriate repo? 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I usually have to delete the mock DB file manually and then run amplify mock a few times to get it running.

**Comment by josefaidt** [comment]
Hey @localsecurity-emily would you mind posting the last few (about 5) commands you used prior to receiving the throttling errors? I have not been able to reproduce this with many `@function` directives in my GraphQL schema and running `amplify mock api` -- specifically reproducing the `describeStack` logs we see in your output above.

**Comment by localsecurity-emily** [comment]
Hey @josefaidt, I am not getting any useful output within my `~/.amplify/logs` it is just:

```
2022-05-20T15:46:05.436Z|info : amplify mock mock
2022-05-20T15:46:05.507Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
```

Within my terminal I get:

```
amplify mock api
GraphQL schema compiled successfully.

Edit your schema at ***/schema.graphql or place .graphql files in a directory at ***/schema
Mock does not handle CloudFormation resource of type AWS::IAM::ManagedPolicy. Skipping processing resource AuthRolePolicy01.
Mock does not handle CloudFormation resource of type AWS::IAM::ManagedPolicy. Skipping processing resource AuthRolePolicy02.
Mock does not handle CloudFormation resource of type AWS::IAM::ManagedPolicy. Skipping processing resource AuthRolePolicy03.
Mock does not handle CloudFormation resource of type AWS::IAM::ManagedPolicy. Skipping processing resource AuthRolePolicy04.
Mock does not handle CloudFormation resource of type AWS::IAM::ManagedPolicy. Skipping processing resource AuthRolePolicy05.
Mock does not handle CloudFormation resource of type AWS::IAM::ManagedPolicy. Skipping processing resource AuthRolePolicy06.
Mock does not handle CloudFormation resource of type AWS::IAM::ManagedPolicy. Skipping processing resource AuthRolePolicy07.
Mock does not handle CloudFormation resource of type AWS::IAM::ManagedPolicy. Skipping processing resource AuthRolePolicy08.
Mock does not handle CloudFormation resource of type AWS::IAM::ManagedPolicy. Skipping processing resource AuthRolePolicy09.
Mock does not handle CloudFormation resource of type AWS::IAM::ManagedPolicy. Skipping processing resource AuthRolePolicy10.
Mock does not handle CloudFormation resource of type AWS::IAM::ManagedPolicy. Skipping processing resource AuthRolePolicy11.
Mock does not handle CloudFormation resource of type AWS::IAM::ManagedPolicy. Skipping processing resource AuthRolePolicy12.
Mock does not handle CloudFormation resource of type AWS::IAM::ManagedPolicy. Skipping processing resource AuthRolePolicy13.
Mock does not handle CloudFormation resource of type AWS::IAM::ManagedPolicy. Skipping processing resource AuthRolePolicy14.
Failed to get credentials: Rate exceeded
Failed to get credentials: Rate exceeded
```

**Comment by localsecurity-emily** [comment]
It also might be worth noting I upgraded to `8.2.0` this morning

**Comment by josefaidt** [comment]
Hey @localsecurity-emily apologies for the delay here, do you have multiple auth role's configured in your application? Would you mind sending your `amplify/` directory as a zip archive to amplify-cli@amazon.com?

**Comment by localsecurity-emily** [comment]
@josefaidt sorry for the delay, the zip has been sent

**Comment by josefaidt** [comment]
Hey @localsecurity-emily apologies for the delay, I have not been able to successfully reproduce this behavior. Is there anything running in the background or using the same credentials elsewhere that could potentially be causing the rate exceeded exception?

**Comment by localsecurity-emily** [comment]
None that I am aware of, all of the developers on our team are experiencing this issue. It seems to have happened after we switched environments (i.e. pulled develop again after pulling staging)

**Comment by josefaidt** [comment]
Hey @localsecurity-emily :wave: I also wanted to mention when this occurs again would you mind running `amplify diagnose` and reply with the newly created project identifier? This will allow us to better understand the context of your workflow and how this impacts mock 🙂

**Comment by localsecurity-emily** [comment]
👋 @josefaidt, I would say that `amplify pull` probably gets run, on average, about 4 times per day across our entire team. I ran `amplify pull` and then `amplify diagnose` for you this morning. I am not certain the zip sent to I have also emailed them to amplify-cli@amazon.com

**Comment by localsecurity-emily** [comment]
Hey @josefaidt, I'm not sure if it generates a project identifier? Prior to being given the option to send the zip, the output is:
`/var/folders/8l/rct6k90x5x3c3ty17rsh7rdw0000gn/T/LocalSecurityApp/report-1657735876097.zip`

Yes, we run `amplify pull` to sync builds.

**Comment by AnilMaktala** [comment]
Hey @localsecurity-emily 👋, are you still experiencing this issue?

**Comment by AnilMaktala** [comment]
Hey @localsecurity-emily 👋,  Just want to follow up, are you still experiencing this?

**Comment by AnilMaktala** [comment]
Hi @localsecurity-emily 👋, Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
