### ISSUE TITLE
Error trying to fix the schema

### ISSUE THREAD

**Issue by rafaelfaria** [aws-amplify/amplify-category-api#535]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

8.4

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

none

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

I made some changes to my schema, and by mistake, a semi-colon end up on one of the fields.

When I tried to push, i got an error, however, after I fixed, i tried to push again, and despite not being there anymore I keep getting the error

```
🛑 Your GraphQL schema is invalid. Update the schema to use proper syntax and try again.
✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: /
Syntax Error: Cannot parse the unexpected character ";".

GraphQL request:383:58
382 |
383 |     createdByUsername: String  @index(name: "byUsername");
    |                                                          ^
384 |     createdBy: User @belongsTo(fields: ["tokenAddress"])
```

The ';' has been fixed, and it's not in the schema anymore, but I still can't push it to the cloud anymore.

### Expected behavior

I expected to keep pushing to the cloud without any issues. Specially after fixing my schema.

### Reproduction steps

1. Create a schema, push to the cloud
2. Add a ';' to the end of any field of the model
3. push to the cloud again (you would get an error)
4. fix it
5. Try to push to the cloud and you should get the error.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @rafaelfaria :wave: apologies for the delay here! Are you still experiencing this issue?

**Comment by rafaelfaria** [comment]
@josefaidt Not really. I actually had to rebuild my whole project. Luckily we are still in development, but it took me hours to bring everything back and recover backups etc.

I think the bug still happens. Maybe a better approach would be validating the schema before doing anything else. This is a very simple thing that could be validated before continuing at all, shouldn't cause someone to have to rebuild EVERYTHING..

Thoughts?

**Comment by josefaidt** [comment]
Hey @rafaelfaria ah glad to hear you're up and running despite the rough experience. And I think that's valid! There is an active feature request to improve the push experience with GraphQL, in that the schema that is validated at the beginning of `push` is the schema that is shipped with the update.

**Comment by josefaidt** [comment]
Hey @rafaelfaria I'm going to close this issue for now, however the team is working on a solution to prevent these issues from occurring again 🙂
