### ISSUE TITLE
Amplify V2 @auth allow public provider iam returns unauthorized when using Appsync Graphql Queries

### ISSUE THREAD

**Issue by madahatter** [aws-amplify/amplify-category-api#544]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

17.3.1

### Amplify CLI Version

7.6.13

### What operating system are you using?

macOS Monterey Apple M1 Chip

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth, function, api

### Amplify Commands

Not applicable

### Describe the bug

I have a React-Native project where I'd like to have unauthenticated users create an Item in my User table so I can store temporary data until they sign up.  I am creating a user in the table as soon as they open the App, prior signing up using Cognito.  The goal for this allows users to store some temporary data and once they sign up, I will assign the user to the Cognito user.

In order to achieve this, I wanted to allow unauthenticated users the capability of creating and updating their own item in my user table.  I think that I am supposed to be using a public IAM to create the user, however I may be wrong, since I am new to Amplify.

The problem I am getting is that when I push my project and go to test it in Appsync, creating/listing a user returns unauthorized.  I have selected AWS Identity and Access Management as my authorization provider and the result is as follows:
...
"Not Authorized to access listUsers on type ModelUserConnection" or "Not Authorized to access createUser on type User"
...

I have also tried to create an unauthrole in identity providers by adding an inline policy to the iam role:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "appsync:GraphQL"
            ],
            "Resource": [
                "arn:aws:appsync:us-east-1:<myaccountid>:apis/<myappid>types/Query/fields/listUsers"
            ]
        }
    ]
}

### Expected behavior

I would like to be able to create a User and query that user on my user table that can store data without the user being signed in to a Cognito user, but I'd like to have enough security that only my app with amplify is capable of writing to the table.  I don't want to have the user sign up to do this.  Once the user is signed up, the balance of the information will be populated to the table.

### Reproduction steps

Project git:(main) ✗ amplify add api
? Select from one of the below mentioned services: GraphQL
? Here is the GraphQL API that we will create. Select a setting to edit or conti
nue Authorization modes: API key (default, expiration time: 7 days from now)
? Choose the default authorization type for the API Amazon Cognito User Pool
Using service: Cognito, provided by: awscloudformation
 
 The current configured provider is Amazon Cognito. 
 
 Do you want to use the default authentication and security configuration? Manua
l configuration
 Select the authentication/authorization services that you want to use: User Sig
n-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage feature
s for images or other content, Analytics, and more)
 Provide a friendly name for your resource that will be used to label this categ
ory in the project: projectjan27ccb00d0fccb00d0f
 Enter a name for your identity pool. projectjan27ccb00d0f_identitypool_ccb00d0f
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) Yes
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Provide a name for your user pool: projectjan27ccb00d0f_userpool_ccb00d0f
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Email
 Do you want to add User Pool Groups? Yes
? Provide a name for your user pool group: Admin
? Do you want to add another User Pool Group Yes
? Provide a name for your user pool group: Owner
? Do you want to add another User Pool Group Yes
? Provide a name for your user pool group: Employee
? Do you want to add another User Pool Group Yes
? Provide a name for your user pool group: User
? Do you want to add another User Pool Group No
✔ Sort the user pool groups in order of preference · Admin, Owner, Employee, User
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email
 entry at registration)
 Specify an email verification subject: Project Code Verification
 Specify an email verification message: Code: {####}
 Do you want to override the default password policy for this User Pool? No
 Warning: you will not be able to edit these selections. 
 What attributes are required for signing up? Email
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? 
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? No
✅ Successfully added auth resource projectjan27ccb00d0fccb00d0f locally

? Configure additional auth types? Yes
? Choose the additional authorization types you want to configure for the API IA
M
? Here is the GraphQL API that we will create. Select a setting to edit or conti
nue Continue
? Choose a schema template: Objects with fine-grained access control (e.g., a pr
oject management app with owner-based authorization)
GraphQL schema compiled successfully.

✔ Do you want to edit the schema now? (Y/n) · no
✅ Successfully added resource projectjan27 locally

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type User 
  @model
  @auth(
    rules: [
      { allow: groups, groups: ["Admin"] }
      { allow: owner, ownerField: "id"} 
      { allow: public, provider: iam, operations: [create, read]}
    ]
  ) 
  {
  id: ID!
  active: Boolean
  rcId: String
  oneSignalId: String
  verified: Boolean
  firstName: String 
  lastName: String 
  email: String 
  phone: String 
  language: String
  items: [Items] @hasMany
  itemHistory: [ItemHistory] @hasMany 
}

```

</details>

### Log output

<details>

```
# Put your logs below this line
{
  "data": {
    "createUser": null
  },
  "errors": [
    {
      "path": [
        "createUser"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 6,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access createUser on type User" 
    }
  ]
}

```

</details>

### Additional information

Thank you in advance.  I have been really trying to figure this out all week.

**Comment by SaileshKumar** [comment]
@josefaidt

I also just tried the custom-roles fix and pushed, no luck.
My file looks like this:

```
{
  "adminRoleNames": ["<IAM_USER_NAME>", "<IAM_USER_NAME>", "<IAM_USER_NAME>", "<IAM_USER_NAME>", "<IAM_USER_NAME>"]
}
```

It doens't need to be the ARN or something right?

**Comment by sundersc** [comment]
@SaileshKumar The resolvers use `contains` operator, so just giving the role name is adequate. If you are running into any issue, you could also try one of the options mentioned in the linked comments.

https://github.com/aws-amplify/amplify-category-api/issues/100#issuecomment-1129353024
https://github.com/aws-amplify/amplify-category-api/issues/100#issuecomment-1159378850

**Comment by SaileshKumar** [comment]
> @SaileshKumar The resolvers use `contains` operator to match the IAM role name, so just giving the role name is adequate. If you are running into any issue, you could also try one of the options mentioned in the linked comments.
> 
> [#100 (comment)](https://github.com/aws-amplify/amplify-category-api/issues/100#issuecomment-1129353024) [#100 (comment)](https://github.com/aws-amplify/amplify-category-api/issues/100#issuecomment-1159378850)

The option linked worked great! Thank you.
