### ISSUE TITLE
Adding an owner auth rule does not add an owner in the schema

### ISSUE THREAD

**Issue by adrian-santos** [aws-amplify/amplify-category-api#549]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

8.3.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

auth

### Amplify Commands

Not applicable

### Describe the bug

```graphql
type Note @model @auth(rules: [{ allow: owner }]){
    id: ID!
    name: String!
    description: String
    image: String
}
```

It's supposed to list the todos of user (owner), when I run the code, it's null. Response was unauthorized

Use Case: Just need different users to be able to CRUD their own todos using allow: owner

### Expected behavior

It's supposed to list the todos of user (owner)

### Reproduction steps

Add an `@auth(rules: [{ allow: owner }])` to any schema, even just a normal to do list, then fetch is using a simple UI. After logging in, you can see an **unauthorized** response

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Note @model @auth(rules: [{ allow: owner }]){
    id: ID!
    name: String!
    description: String
    image: String
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @adrian-santos :wave: thanks for raising this! I was not able to reproduce this using Amplify CLI 8.5.0, can you try upgrading your CLI and re-push with a small update to your API resource?

```graphql
type Todo @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  name: String!
  owner: String
  description: String
}
```

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/5033303/173661774-56a20611-13f1-4c8f-aeb7-db850adafa72.png">

**Comment by adrian-santos** [comment]
@josefaidt - upgraded my amplify cli. it's working now
