### ISSUE TITLE
StackMapping changes getting reverted for pushed resolver functions

### ISSUE THREAD

**Issue by lazpavel** [aws-amplify/amplify-category-api#550]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.19.1

### Amplify CLI Version

8.5.0

### What operating system are you using?

macOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

`transform.conf.json` StackMapping entries gets reverted for already pushed resources. 
doc link: https://docs.amplify.aws/cli/graphql/override/#place-appsync-resolvers-in-custom-named-stacks

This makes impossible to fix the issue when the resources were once successfully pushed but at a later time changes in the functions makes the nested stack go over the 100000 bytes limit.

As a workaround once can completely remove the resolver function, execute `amplify push`, add the resolver function back and map it to a new nested stack and execute `amplify push` again

Code method that is reverting the `StackMapping` content can be found here: https://github.com/aws-amplify/amplify-category-api/blob/6c2880f31fc2ea1245c2b1e04805e08faceb7b46/packages/graphql-transformer-core/src/util/amplifyUtils.ts#L160-L220

### Expected behavior

StackMapping definitions needs to be reflected in generated nested stack template even after the resources were once pushed.

### Reproduction steps

1. amplify add api
2. set schema to
```
type Test @model {
  id: ID!
  name: String!
}
```
3. add `StackMapping` to `transform.cont.json`
```
    "StackMapping": {
        "UpdateTestResolver": "CustomTestStack",
        "CreateTestResolver": "CustomTestStack",
        "ListTestResolver": "CustomTestStack",
        "GetTestResolver": "CustomTestStack"
    }
```
5. run `amplify push`
6. update `transform.conf.json` `StackMapping` to
```
    "StackMapping": {
        "UpdateTestResolver": "CustomTestStack",
        "CreateTestResolver": "CustomTestStack",
        "ListTestResolver": "UpdateTestStack",
        "GetTestResolver": "UpdateTestStack"
    } 
```
8. running `amplify api gql-compile` or `amplify push` will revert the `StackMapping` content

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>
type Test @model {
  id: ID!
  name: String!
}

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by phani-srikar** [comment]
I've tried to reproduce this using the latest `10.7.3` version of CLI and did not run into this issue. Using `amplify api gql-compile` successfully generates the newly added `UpdateTestStack` stack and removes the Get and List resolvers from the `CustomTestStack` stack. However, I ran into another issue that we're tracking where if we move the resolvers between 2 CFN stacks, it causes a race condition during deploy causing the stack updates to fail. Refer to this [comment](https://github.com/aws-amplify/amplify-category-api/issues/32#issuecomment-1158329437)
