### ISSUE TITLE
Update CDK version for cdk 1.x latest

### ISSUE THREAD

**Issue by akshbhu** [aws-amplify/amplify-category-api#553]
### Is this feature request related to a new or existing Amplify category?

api

### Is this related to another service?

amplify-cli

### Describe the feature you'd like to request

Stems from the GH issue : https://github.com/aws-amplify/amplify-js/issues/987

Related CLI Issue: https://github.com/aws-amplify/amplify-cli/issues/10561

Cognito released an attribute in userpool UserAttributeUpdateSettings to have users old emails backwards compatible till they verify the new emails login.

### Describe the solution you'd like

- Upgrade cdk to 1.x latest

### Describe alternatives you've considered

- Needs cdk version increment to support the property

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by ykethan** [comment]
Closing this in support for CDK v2.
