### ISSUE TITLE
Cannot successfully update amplify 7->8, get "could not get resource X"

### ISSUE THREAD

**Issue by eettaa** [aws-amplify/amplify-category-api#560]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.18.1

### Amplify CLI Version

7.6.21 -> 8.5.0

### What operating system are you using?

Ubuntu 18.04.5 LTS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Lambdas are deployed into a VPC via "vpc config" updates in *-cloudformation-template.json.  However, this is longstanding/has not previously had a bad interaction with `amplify mock api` or `amplify push`

### Amplify Categories

auth, function, api

### Amplify Commands

init

### Describe the bug

I have a fully deployed production app using @aws-amplify/cli@7.6.21

I cannot seem to successfully update this to use 8.x.x

Steps (run on my local machine)
1) `npm i -g @aws-amplify/cli@8.x.x` // installs 8.5.0
2) `amplify init` // init to default, preexisting environment
3) `git status` // shows that things in amplify/hooks are updated, which I don't understand. I have custom hooks so am inclined to revert these changes, but the problem persists whether or not I change these files
4) `amplify status` // all categories say "no update"
5) `amplify mock api` // FAILS with `Failed to start API Mock endpoint Error: Could not get resource [NAME]`

... where NAME is a type annotated with @model in my schema.graphql
Notable things about this type are:
- It implements an interface (also declared in the schema.graphql file)
- It has a standard "owner" auth rule (`@auth(rules: [{ allow: owner }])`)
- It uses a GSI on the owner field as well, so it is queryable by owner: `  owner: String! @index(name: "byOwner", queryField: "NAMEbyOwner")`
- One of its fields has an @hasOne annotation

If I add step 2.5 of amplify env pull --restore, the problem still persists.
If I fully delete my mock_data directory before running `amplify mock api`, the problem persists.
If I create a new amplify environment using amplify@8.5.0, with `amplify env add bumpbug`, the problem persists
If I revert back to the old CLI (s/8/7 in step 1) everything works again.
I get a warning "⚠️ The maximum number of apps that you can create with Amplify in this region has likely been reached: " with a link to aws quotas, but I am well under the quota.

I'd prefer not to dump my full schema/cloudformation/etc on a public forum, but I am interested in resolving this/providing any information needed.

Thanks!
Thank you!!

### Expected behavior

Bumping amplify versions doesn't affect results of `amplify mock api`

### Reproduction steps

(Please see above description... I am not sure how to repro this outside of my setup).

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by eettaa** [comment]
Thank you so much for your prompt response! I don't think I would be able to resolve this on my own :)
>are you able to run amplify api gql-compile without error?

Yes, this works just fine with both amplify versions

>are there any further customizations applied to the API? (overrides, custom transformer, stack mapping, etc.)

I believe the answer is no
Then only custom changes to my entire project are:
- My lambdas have a "VpcConfig" configuration in their `-cloudformation-template.json` file
- I have added point in time recovery to our tables by following [these](https://github.com/aws-amplify/amplify-cli/issues/4163) instructions (basically just adding a param in `amplify/backend/api/<api-name>parameters.json`
- I have secondary  (IAM-based)  auth setup for the API, and some of my lambdas have access to my api via custom ["admin roles"](https://github.com/aws-amplify/amplify-category-api/issues/140#issuecomment-1129353912) 

>do you see a stack with the name of the model that cannot be found in amplify/backend/api/<name>/build/stacks/Todo.json

Yes, I have a file like `amplify/backend/api/<apiname>/build/stacks/<modelname>.json`.  It is largely unintelligible to me but does not immediately appear different from all the other json files for my other models in the same directory.

-------------------------

I also created a new amplify project following exactly your reproduction steps.  For this new project, everything works just fine, although when I run `amplify init` I still get a warning like "⚠️ The maximum number of apps that you can create with Amplify in this region has likely been reached:" with no number following the colon.   I definitely have less than 25 apps in the region (the limit per the [quota page](https://docs.aws.amazon.com/general/latest/gr/amplify.html#service-quotas-amplify))


So unfortunately it seems like this may be an idiosyncratic problem to my project.  I definitely still need to solve it and am happy to run any more commands/do any more investigation.  Does the "circular dependency" error when redeploying in cloud add any clues? I couldn't find any relevant issues on github...

I really appreciate your help!

**Comment by josefaidt** [comment]
> Does the "circular dependency" error when redeploying in cloud add any clues?

We recently received https://github.com/aws-amplify/amplify-category-api/issues/554, however I do not believe that would effect our ability to mock.

For additional context, would you mind sending us your `schema.graphql` file to amplify-cli@amazon.com?

**Comment by eettaa** [comment]
Hi, in redacting my schema for the requested email, I was able to generate a toy example that repros the problem for me which I can share for everyone :).

In this schema, a Member owns Cars and has tasks to wash their cars. The WashCarTask object also links to a specific car.  here is the schema:
```
type Member @model @auth(rules: [{ allow: owner }])
{
  owner: String! @primaryKey

  ### IF I REMOVE THIS SECONDARY INDEX FROM MEMBER, EVERYTHING WORKS!!!  BUT WHY???
  secondaryIndex: String @index(name: "bySecondaryIndex", queryField: "memberBySecondaryIndex")

  washCarTasks: [WashCarTask] @hasMany(indexName: "byOwner", fields: ["owner"])

  cars: [Car] @hasMany(indexName: "byOwner", fields: ["owner"])

}

type WashCarTask @model @auth(rules: [{ allow: owner }]) {
  id: ID! @primaryKey
  owner: String! @index(name: "byOwner", queryField: "washCarTaskByOwner")

  carId: ID!
  car: Car @hasOne (fields: ["carId"])
}

type Car @model @auth(rules: [{allow: owner}]) {
  carId: ID! @primaryKey
  owner: String @index(name: "byOwner", queryField: "carByOwner")
}
```
Note that there seems to be something going on with Member's secondary index- removing that line solves the problem, although I do not understand why.

For me on amplify 8.5.0, `amplify api gql-compile` succeeds, but `amplify mock api` yields "Failed to start API Mock endpoint Error: Could not get resource WashCarTask"

On amplify@7.6.21, this mocks just fine.

**Comment by eettaa** [comment]
Hi @josefaidt, thanks for your help last week!
I wanted to circle back here to make sure you saw this toy example/we can start diagnosing it.  As of now it seems like this may actually be a generic bug in Amplify 8, not just a bizarre idiosyncrasy with my config (phew!)
Thanks again!

**Comment by eettaa** [comment]
Thanks! Glad I'm not going crazy :)
Is there any idea about when this might be fixed? As-is, my prod stack is now stuck at amplify@7.6.21 and I have no idea why.
Thank you Amplify team for all your help!

**Comment by eettaa** [comment]
Hi @josefaidt @ykethan, I hope you all had a great weekend!
Is there anything I can do to facilitate the resolution of this bug?  
As-is, my prod stack is now stuck at amplify@7.6.21 and I have no idea why.
Please let me know if there is any workaround I could use and/or if I can help you guys debug.

Thank you!!

**Comment by eettaa** [comment]
Hi @josefaidt @ykethan and anyone else on the amplify team that may be able to help here.

Are there any updates to this bug? I am beginning to face issues related to being frozen out of amplify CLI updates.  For example, Node12 lambda deprecation does not mix well with Amplify 7, which uses cognito auth functions that run on Node 12.I need to be able to update my CLI to have it correctly build for node 16.

Thank you!

**Comment by eettaa** [comment]
Adding some additional debugging notes for posterity:
Initial state: prod environment with prod data stored, toy schema as described above, all deployed/deployable via cli@7.6.21
As noted above, it seems like the critical problem is related to the secondary index on the member object.  I tried the following workflows as workarounds.

# Create a new environment, push it, update cli, push it again
This approach loses all production data but would preserve the schema.
- with cli@7, mock and push succeed for the new environment.
- Then I update to cli@latest (9.2.x)
- Mock fails with "“Failed to start API Mocking. Running cleanup tasks.”
- Push *succeeds* 

# Delete secondary index, push, bump to cli@9, push, add secondary index back, push
This approach would preserve data.  But it doesn't work.
- Mock/push commands work with cli@7
- Then I remove the secondary index (but not the schema field- just the @index annotation)
- Mock works
- push works
- Bump to cli@9.2.x
- mock works
- push works
- Then I add the secondary index annotation back in
- mock fails (same error)
- push fails with circular dependency error (same as always)

**Comment by AaronZyLee** [comment]
@eettaa I am able to reproduce the issue and finally find a temporary method to solve the issue. The root cause is due to the order of generating the the nested stacks based on your schema provided. Since in the `Member` type the `owner` field is defined as the primary key, its auth appsync function is different from other types. For the queryField defined in Member index, it finally reference a auth appsync function behind it, which is the `WashCarTask` in this case.

The circular dependency is also due to this problem.

To fix this for both `mock api` and `amplify push`, you just need to put the `Member` type behind other types. After that, you can rerun `amplify mock api` and `amplify push` and you should see the command succeed.
```GraphQL
type WashCarTask @model @auth(rules: [{ allow: owner }]) {
  id: ID! @primaryKey
  owner: String! @index(name: "byOwner", queryField: "washCarTaskByOwner")
  carId: ID!
  car: Car @hasOne(fields: ["carId"])
}

type Car @model @auth(rules: [{ allow: owner }]) {
  carId: ID! @primaryKey
  owner: String @index(name: "byOwner", queryField: "carByOwner")
}

type Member @model @auth(rules: [{ allow: owner }]) { ## ------> this is moved from the beginning of the doc
  owner: String! @primaryKey
  secondaryIndex: String
    @index(name: "bySecondaryIndex", queryField: "memberBySecondaryIndex")
  washCarTasks: [WashCarTask] @hasMany(indexName: "byOwner", fields: ["owner"])
  cars: [Car] @hasMany(indexName: "byOwner", fields: ["owner"])
}
```
In the meantime, we also notice that the order here should not have impact on the generated CFN stack template, which is an unexpected behavior. We will work on a new approach for this process to prevent this situation as an enhancement.
