### ISSUE TITLE
Resource is not in the state stackUpdateComplete

### ISSUE THREAD

**Issue by ataibarkai** [aws-amplify/amplify-category-api#563]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v17.2.0

### Amplify CLI Version

8.5.1

### What operating system are you using?

macOS 12.3.1

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth, custom, storage, function, api, hosting

### Amplify Commands

push

### Describe the bug

This issue is similar to the one described in https://github.com/aws-amplify/amplify-category-api/issues/92

The bottom line is that 20-30 mins into a `amplify push` attempt, I get the following error:
```
["Index: 1 State: {\"deploy\":\"waitingForDeployment\"} Message: Resource is not in the state stackUpdateComplete"]
```

Upon push
I have a GQL schema that was in a stable condition.
Then, 

### Expected behavior

Push should succeed

### Reproduction steps

1. Had a stable amplify environment working well, including a GraphQL API. All of the relations on it were manually created with a join table, index references, etc. None used the v2 GQL transformer automatic relations like `@hasMany` and `@manyToMany` .

2. Added 2 new fields on a `SignupCode` object (pushed one at a time):
   - usersToAutomaticallyFollow [User] @hasMany
   - usersWhoAutomaticallyFollowNewMembers: [User] @hasMany

3. Immediately after pushing the above, realized what I need is a @manyToMany relationship. Replaced the above with the fields commented out in the attached schema.

4. Added `enableIterativeGSIUpdates: true` flag (since pushing push the 2 removal  + 2 insertion operations above in a single step failed).

5. Consistently getting the failure above on `push` attempts.

Tried:
- `amplify push --iterative-rollback`
- `amplify push --forcePush --yes`
- deleting deployment-state.json from the bucket
- Undoing all changes, all at once and one at a time.

None of these approaches worked. Got the same error in the same spot.

Then I tried `amplify env pull ENV_NAME --restore`, and the subsequent push DID succeed.

However it takes me back into a state with the following fields, which I need to get rid of.
```
   - usersToAutomaticallyFollow [User] @hasMany
   - usersWhoAutomaticallyFollowNewMembers: [User] @hasMany
```

Further push operations bring back the same issue.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type SignupCode
  @model(subscriptions: {level: off})
  @searchable
  @auth(rules: [
    {allow: public, operations: [read]},
    {allow: private, operations: [read]},
    {allow: private, provider: iam, operations: [create, read, update, delete]}
  ])
{
  codeName: String! @primaryKey
  createdAt: AWSDateTime!

  // ...

  # just added before the issue surfaced. Have no data associated with them.
  usersToAutomaticallyFollow: [User] @hasMany
  usersWhoAutomaticallyFollowNewMembers: [User] @hasMany
 
  # trying to transition the above into the following
  # usersToAutomaticallyFollow: [User] @manyToMany(relationName: "SignupCodeUsersToAutomaticallyFollowAssociation")
  # usersWhoAutomaticallyFollowNewMembers: [User] @manyToMany(relationName: "SignupCodeUsersAutomaticallyFollowNewMembersAssociation")
}


type User @model(subscriptions: {level: off})
@searchable
@auth(rules: [
  {allow: owner, ownerField: "sub", identityClaim: "sub", operations: [read, update]},
  {allow: public, operations: [read]},
  {allow: private, operations: [read]},
  {allow: private, provider: iam, operations: [create, read, update, delete]}
]) {
  sub: String! @primaryKey

  // ...

  # trying to transition to the following
  # automaticallyFollowedIn: [SignupCode] @manyToMany(relationName: "SignupCodeUsersToAutomaticallyFollowAssociation")
  # automaticallyFollowsNewMembersIn: [SignupCode] @manyToMany(relationName: "SignupCodeUsersAutomaticallyFollowNewMembersAssociation")
}


```

</details>

usersToAutomaticallyFollow: [User] @hasMany
  usersWhoAutomaticallyFollowNewMembers: [User] @hasMany

### Log output

<details>

```
```

</details>

**Comment by ataibarkai** [comment]
Hi @josefaidt @alharris-at , created a new issue for this per your request

**Comment by ataibarkai** [comment]
Some updates:

I am not entirely sure how / what's changed but I was able to resolve this issue.

The key progress was made through `amplify env pull ENV_NAME --restore` which allowed me to try things incrementally again.
I was able to remove the 2 'offending' fields, by remove one at a time and then pushing.
   - usersToAutomaticallyFollow [User] @hasMany
   - usersWhoAutomaticallyFollowNewMembers: [User] @hasMany

Then I tried adding the `@manyToMany` fields, but those still gave issue. (the error was similar but I am not certain if it was identical to the one encountered prior).
I tried creating the relations manually (by creating the respective join tables), and it worked.

**Comment by AnilMaktala** [comment]
Hey @ataibarkai 👋, Just want to follow up on this. Are you still experiencing this issue?

**Comment by AnilMaktala** [comment]
Hi @ataibarkai  👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
