### ISSUE TITLE
Helping with an API model 

### ISSUE THREAD

**Issue by rafaelfaria** [aws-amplify/amplify-category-api#566]
I am trying to get an idea of how to model my data.

Context: I am trying to create an app that would take someone to create a TEAM, and then associate users to this team. 
Within this Team, I can create Tournaments, which within each tournament and. would be able to add the position of each user had in it.

The restriction here is that I would like the users to ONLY be able to see all the teams they are associated with, as well as each of the events that are associated with each of the teams.

I started the following idea, but not sure how to restrict the users of the teams to only see the teams they are associated to. Any help is welcome.

```
type User @model
  @auth(
    rules: [
      { allow: private, operations: [read, update], provider: iam },
      { allow: groups, groups: ["Admin"] }
    ]
  )
{
  username: ID!
  name: String!
  photo: String
}
type Team @model
  @auth(
    rules: [
      { allow: owner },
      { allow: private, operations: [read, update], provider: iam },
      { allow: groups, groups: ["Admin"] }
    ]
  )
{
  id: ID!
  name: String!
  users: [User] @hasMany
  tournament: [Tournament] @hasMany(indexName: "byTournament", fields: ["id"])
}

type Tournament @model
  @auth(
    rules: [
      { allow: owner },
      { allow: private, operations: [read, update], provider: iam },
      { allow: groups, groups: ["Admin"] }
    ]
  )
{
  id: ID!
  name: String
  date: AWSDate!
  totalPrize: Float
  leaderboard: [TornamentLeaderboard]

  teamID: ID! @index(name: "byTournament")
  team: Team @belongsTo(fields: ["teamID"])
}

type TornamentLeaderboard {
  place: Int!
  userID: String!
  prize: Float
}
```

**Comment by josefaidt** [comment]
Hey @rafaelfaria :wave: thanks for raising this and apologies for the delay! Similar to how you've set up the tournament model with `@belongsTo` pointing to the team, is it feasible to also add this relationship on the user?

```graphql
type User @model
  @auth(
    rules: [
      { allow: private, operations: [read, update], provider: iam },
      { allow: groups, groups: ["Admin"] }
    ]
  ) {
  username: ID!
  name: String!
  photo: String
  teamID: ID! @index(name: "byUser")
  team: Team @belongsTo(fields: ["teamID"])
}
```

**Comment by josefaidt** [comment]
This would also be a great question to ask in our [community Discord server](https://discord.gg/amplify)!
