### ISSUE TITLE
subscription filter owner in the backend

### ISSUE THREAD

**Issue by Quetzalfir** [aws-amplify/amplify-category-api#567]
**Which Category is your question related to?** subscriptions filters

**Amplify CLI Version** 

8.5.0

**What AWS Services are you utilizing?**
AWS AppSync (api), Amazon Cognito (auth), Amazon DynamoDB (storage), Lambda

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
I have and app that has suscriptions to data that is sensitive, I could filter the data from my front-end in the subscription by the owner id, but this could be cheated very easy putting another user id and start to receive data thta is no target to him.

Im calling the APPSYNC API from a Lambda, I have succesfully set all the flow and I receive the subscritions from the lambda calls, Im using an IAM Role for access the API through the lambda So I don have any info of the current cognito user in the lambda, I'm just relying in the value of the `owners: [String]` field. 

For currently the users of my app are receiving the notifications of the suscriptions, even if they are not in the list of owners

So, Is there any way I can filter in the backend the owner, or someway that I can secure more the data of the subscritions?

```
type Notification @model
@auth( rules: [
  { allow: owner, ownerField: "owners" },
  { allow: public, provider: iam, operations: [read] }
])
{
  id: ID!
  title: String!
  owners: [String]
  type: String!
}
```

Also, if I want to filter this by just one owner, could I pass a single user id to the suscription? or is not posible to filter just one owner among the array of owners

**Comment by dylan-westbury** [comment]
I am looking how to do this also.

Our use case is when messages are sent between users, we only want the users of that conversation to receive that message.
```
# ****************************************************************************
# MESSAGE
# ****************************************************************************
 type Message
   @model(mutations: { create: "createMessage", update: "updateMessage" })
   @auth(rules: [
     { allow: groups, groups: ["Users"] } <-- we need to do this to make the subscription work
     { allow: owner, operations: [read, create], ownerField: "users" }
     { allow: private, provider: iam }
   ]) {
     conversationId: ID! @index(name: "messagesByConversation", sortKeyFields: ["createdAt"], queryField: "messagesByConversation")
     text: String
     attachments: [S3Upload]
     users: [String]!
     createdBy: String!
     createdAt: AWSDateTime!
     updatedAt: AWSDateTime
}
```

@josefaidt is there any way we can achieve as of current? Cheers

**Comment by dylan-westbury** [comment]
https://github.com/aws-amplify/amplify-category-api/pull/551 I think this may enable filtering by array of strings for owner

**Comment by josefaidt** [comment]
Hey @dylan-westbury and @Quetzalfir :wave: apologies for the delay here but as @dylan-westbury pointed out support for AppSync's runtime filtering is under active development and would enable workflows such as what is described here!

**Comment by sundersc** [comment]
@Quetzalfir - You can use server side filtering feature to achieve this. When you establish a subscription connection on a model contains only owner rule, you will receive only the data you have access to.
https://docs.amplify.aws/cli/graphql/data-modeling/#server-side-filtering-for-subscriptions

However it is not possible to filter on fields used for auth rules. You can still write the same data to another field and use that to filter data.

**Comment by tonydatw** [comment]
> I am looking how to do this also.
> 
> Our use case is when messages are sent between users, we only want the users of that conversation to receive that message.
> 
> ```
> # ****************************************************************************
> # MESSAGE
> # ****************************************************************************
>  type Message
>    @model(mutations: { create: "createMessage", update: "updateMessage" })
>    @auth(rules: [
>      { allow: groups, groups: ["Users"] } <-- we need to do this to make the subscription work
>      { allow: owner, operations: [read, create], ownerField: "users" }
>      { allow: private, provider: iam }
>    ]) {
>      conversationId: ID! @index(name: "messagesByConversation", sortKeyFields: ["createdAt"], queryField: "messagesByConversation")
>      text: String
>      attachments: [S3Upload]
>      users: [String]!
>      createdBy: String!
>      createdAt: AWSDateTime!
>      updatedAt: AWSDateTime
> }
> 
> # ****************************************************************************
> # SUBSCRIPTIONS
> # ****************************************************************************
>  type Subscription {
>    onCreateMessageForConversation(conversationId: ID!): Message @aws_subscribe(mutations: ["createMessage"])
>  }
> ```
> 
> @josefaidt is there any way we can achieve as of current? Cheers

Hi Dylan, i am experiencing your same issue right now, subscribed messages are visible in ALL chat rooms, but i just want them to be visible in that specific room. I have already tried passing a filter argument but no success, maybe because i am using an older version of Amplify (2021)? If so, which library should i update? Thanks in advance

**Comment by dylan-westbury** [comment]
Hi @tonydatw 

AppSync's runtime filtering was still in development and I could not find a way to achieve subscribe messages for users of the message / chat only. 

For our use case we only had 2 people in a chat, a sender and a receiver of the message. 

As a solution for our use case we added a property "receiver" to the model Message and created a subscription for this property. That way the person designated to receive the message would be notified in real time.

I haven't since looked into how we could achieve messaging for multiple users, nor have I looked at server side filtering subscriptions as posted above

**Comment by josefaidt** [comment]
Hey @dylan-westbury apologies for the delay here! Are you still experiencing this?

**Comment by AnilMaktala** [comment]
Hi 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment and provide us with the information our team had previously asked for. This way, we can reopen the issue and provide you with better assistance.

Thank you!
