### ISSUE TITLE
Create mutation breaks when a "protected" createdAt field is used with a composite sort key

### ISSUE THREAD

**Issue by naedx** [aws-amplify/amplify-category-api#572]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

8.5.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth, api

### Amplify Commands

Not applicable

### Describe the bug

The pipeline resolver terminates with `"message": "Unauthorized on [status#createdAt]"`

(This works as expected when the protected key is not part of a composite.)

### Expected behavior

The create mutation should succeed on the basis that permission is allowed to set `status`, and `createdAt` is auto generated and set by the server-side code. 

### Reproduction steps

1. Create a new amplify project
2. Add category auth with default options
3. Add category api with cognito auth and the schema below.
4. Execute a `createBlog` mutation using the MyMutation below

MyMutation:

<details>

```graphql


mutation MyMutation {
  createBlog(input: {name: "Awesome Blog", status: published}) {
    id
    name
    description
    owner
    updatedAt
    createdAt
    status
  }
}

```

</details>

Response: 

<details>

```

{
  "data": {
    "createBlog": null
  },
  "errors": [
    {
      "path": [
        "createBlog"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Unauthorized on [status#createdAt]"
    }
  ]
}

```
</details>

### GraphQL schema(s)

<details>

```graphql

type Blog 
  @model(timestamps: { createdAt: "createdAt", updatedAt: "updatedAt" })
  @auth(rules: [
    { allow: owner, operations: [create, read, update, delete] }
    { allow: groups, groupsField: "groups", operations: [read, update, delete] }
  ])
{
  id: ID! 

  name: String! 
    @index(name: "byNameCreatedAt", sortKeyFields: ["createdAt"])
    @index(name: "byNameByStatusByCreatedAt", sortKeyFields: ["status", "createdAt"])

  description: String @default(value: "Powered by Foo Bar Blogs")

  posts: [Post] @hasMany(indexName: "byPost", fields: ["id"])

  createdAt: AWSDateTime!
    @auth(rules: [
      { allow: owner, operations: [read] }
      { allow: groups, groupsField: "groups", operations: [read, update, delete] }
    ])

  status: BlogStatus
}

enum BlogStatus
{
  published
  unpublished
}

type Post 
  @model 
  @auth(rules: [
    { allow: owner, operations: [create, read, update, delete] }
    { allow: groups, groupsField: "groups", operations: [read, update, delete] }
  ])
{
  id: ID!
  postID: ID! @index(name: "byPost", sortKeyFields: ["title"])
  title: String!
  rating: Int
  content: String
}


```

</details>

### Related 

This is the same use case as https://github.com/aws-amplify/amplify-category-api/issues/252. 

### Relevant resolvers

1. Mutation.createBlog.preAuth.1.req.vtl: Line 25 `$util.qr($ctx.args.input.put("status#createdAt","${mergedValues.status}#${mergedValues.createdAt}"))` adds the composite key to the _input_ which has to later be validated.

<details>

```javascript

## [Start] Merge default values and inputs. **
#set( $mergedValues = $util.defaultIfNull($ctx.stash.defaultValues, {}) )
$util.qr($mergedValues.putAll($util.defaultIfNull($ctx.args.input, {})))
## [End] Merge default values and inputs. **
## [Start] Validate create mutation for @index 'byNameByStatusByCreatedAt'. **
#set( $hasSeenSomeKeyArg = false )
#set( $keyFieldNames = ["status", "createdAt"] )
#foreach( $keyFieldName in $keyFieldNames )
#if( $mergedValues.containsKey("$keyFieldName") ) #set( $hasSeenSomeKeyArg = true ) #end
#end
#foreach( $keyFieldName in $keyFieldNames )
  #if( $hasSeenSomeKeyArg && !$mergedValues.containsKey("$keyFieldName") )
    $util.error("When creating any part of the composite sort key for @index 'byNameByStatusByCreatedAt', you must provide all fields for the key. Missing key: '$keyFieldName'.")
  #end
#end
## [End] Validate create mutation for @index 'byNameByStatusByCreatedAt'. **
#if( $util.isNull($ctx.stash.metadata.dynamodbNameOverrideMap) )
  $util.qr($ctx.stash.metadata.put("dynamodbNameOverrideMap", {
  "status#createdAt": "statusCreatedAt"
}))
#else
  $util.qr($ctx.stash.metadata.dynamodbNameOverrideMap.put("status#createdAt", "statusCreatedAt"))
#end
#if( $hasSeenSomeKeyArg )
  $util.qr($ctx.args.input.put("status#createdAt","${mergedValues.status}#${mergedValues.createdAt}"))
#end
{}

````

</details>

2. Mutation.createBlog.auth.0.req.vtl: Then validates the `$ctx.args.input.*` fields against `#set( $ownerAllowedFields0 = ["id","name","description","posts","status"] )`

<details>

```javascript

## [Start] Authorization Steps. **
$util.qr($ctx.stash.put("hasAuth", true))
#set( $inputFields = $util.parseJson($util.toJson($ctx.args.input.keySet())) )
#set( $isAuthorized = false )
#set( $allowedFields = [] )
#if( $util.authType() == "User Pool Authorization" )
  #if( !$isAuthorized )
    #set( $ownerEntity0 = $util.defaultIfNull($ctx.args.input.owner, null) )
    #set( $ownerClaim0 = $util.defaultIfNull($ctx.identity.claims.get("sub"), "___xamznone____") )
    #set( $currentClaim1 = $util.defaultIfNull($ctx.identity.claims.get("username"), $util.defaultIfNull($ctx.identity.claims.get("cognito:username"), "___xamznone____")) )
    #set( $ownerClaim0 = "$ownerClaim0::$currentClaim1" )
    #set( $ownerClaimsList0 = [] )
    $util.qr($ownerClaimsList0.add($util.defaultIfNull($ctx.identity.claims.get("sub"), "___xamznone____")))
    $util.qr($ownerClaimsList0.add($util.defaultIfNull($ctx.identity.claims.get("username"), $util.defaultIfNull($ctx.identity.claims.get("cognito:username"), "___xamznone____"))))
    #set( $ownerAllowedFields0 = ["id","name","description","posts","status"] )
    #set( $isAuthorizedOnAllFields0 = false )
    #if( $ownerClaim0 == $ownerEntity0 || $ownerClaimsList0.contains($ownerEntity0) )
      #if( $isAuthorizedOnAllFields0 )
        #set( $isAuthorized = true )
      #else
        $util.qr($allowedFields.addAll($ownerAllowedFields0))
      #end
    #end
    #if( $util.isNull($ownerEntity0) && !$ctx.args.input.containsKey("owner") )
      $util.qr($ctx.args.input.put("owner", $ownerClaim0))
      #if( $isAuthorizedOnAllFields0 )
        #set( $isAuthorized = true )
      #else
        $util.qr($allowedFields.addAll($ownerAllowedFields0))
      #end
    #end
  #end
#end
#if( !$isAuthorized && $allowedFields.isEmpty() )
$util.unauthorized()
#end
#if( !$isAuthorized )
  #set( $deniedFields = $util.list.copyAndRemoveAll($inputFields, $allowedFields) )
  #if( $deniedFields.size() > 0 )
    $util.error("Unauthorized on ${deniedFields}", "Unauthorized")
  #end
#end
$util.toJson({"version":"2018-05-29","payload":{}})
## [End] Authorization Steps. **

``` 
</details>

**Comment by naedx** [comment]
Instead of setting the composite keys on the `$ctx.args.input` could we use a separate variable in the stash (eg. $ctx.stash.setValueOverrides) ? This could then be merged in as the last step in mergedValues to ensure that these values prevail and allow them to bypass the user authorization check on those fields: 

```javascript


#set( $mergedValues = {} )

$util.qr($mergedValues.putAll($util.defaultIfNull($ctx.stash.defaultValues, {})))

## copy the values from input **
$util.qr($mergedValues.putAll($util.defaultIfNull($args.input, {})))

## copy the values from setValues **
$util.qr($mergedValues.putAll($util.defaultIfNull($ctx.stash.setValueOverrides, {})))


```
 
This would also be useful when slotting in a custom _init_ resolver. It would serve the case where the developer wishes to define values that are set regardless of what is specified in the input. If the developer sets these on `$ctx.stash.defaultValues` then the input values could clobber them. If they are set on `$ctx.args.input` then they are subject to the user's authorization to set the value. More concretely, this could be used to create a resolver to set `createdBy` to the identity value of the user when they do not have permissions to manipulate this value.

**Comment by ykethan** [comment]
Hello @naedx, Thank you for reaching out to us. I was hoping to see if if could provide us some information into your use case here.
Additionally, could you let us know if you could add a create operation for the owner rule on the createdAt field and test the operation.

**Comment by AnilMaktala** [comment]
Hi @naedx 👋, Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
