### ISSUE TITLE
amplify push time increased by 5-7 minutes after upgrade to graphql transformer v2

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-category-api#576]
### Is this feature request related to a new or existing Amplify category?

api

### Describe the feature you'd like to request

I just upgraded our backend to transformer v2, and amplify push is noticeably slower. Looking at my deployment times in AWS Amplify, they have increased by 5-7 minutes. 

### Describe the solution you'd like

Faster amplify pushes. 

### Describe alternatives you've considered

Use AWS Amplify's skip backend / frontend build features when no changes there. 

### Additional context

I know there were previous tickets similar to this (https://github.com/aws-amplify/amplify-cli/issues/1190) but it seems now the situation is worse due to the addition of pipeline resolvers I presume. 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Hey @hisham apologies for the delay here, but this is likely due to the change to deploy using [pipeline resolvers](https://docs.aws.amazon.com/appsync/latest/devguide/pipeline-resolvers.html) rather than unit resolvers.

**Comment by AnilMaktala** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
