### ISSUE TITLE
hasOne creates the right mutation, however API doesn't reflect it

### ISSUE THREAD

**Issue by rafaelfaria** [aws-amplify/amplify-category-api#579]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

8.5.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

I tried to create a relationship between 2 tables so I could get the information from one another, however, when I generate the code, the mutations.ts have the proper code, with the one-to-one relationship, however, the API.ts does not contain that property, so when using the mutation generated in a lambda function, it throws the following error `The variables input contains a field name 'createdBy' that is not defined for input object type 'UpdateTradeInput' `.

### Expected behavior

The expected behaviour was to be able to save into the table and not getting an error?

### Reproduction steps

1. created the schema
2. created a lambda function
3. use a graphql request from lambda to call the mutation
4. returns error

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

type User @model
  @auth(
    rules: [
      { allow: owner, ownerField: "username" }
      { allow: private, operations: [read, update], provider: iam },
      { allow: groups, groups: ["Admin"] }
    ]
  )
{
  username: String! @primaryKey
  email: String!
  name: String!
  initials: String
  photo: String
}


type Trade @model
  @auth(
    rules: [
      { allow: private, provider: iam },
      { allow: owner, operations: [create] }
      { allow: groups, operations: [read, update, delete], groups: ["Admin"] }
    ]
  )
  {
    id: ID!
    title: String
  
    createdByUsername: String
    createdBy: User @hasOne(fields: ["createdByUsername"])
}

```
</details>

### API.ts

<details>

```
export type UpdateTradeInput = {
  id: string,
  title?: string | null,
  createdByUsername?: string | null,
};
```

</details>

### mutations.ts

<details>

```
export const updateTrade = /* GraphQL */ `
  mutation UpdateTrade(
    $input: UpdateTradeInput!
    $condition: ModelTradeConditionInput
  ) {
    updateTrade(input: $input, condition: $condition) {
      id
      title
      createdByUsername
      createdBy {
        username
        email
        name
        initials
        photo
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
      owner
    }
  }
`;
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @rafaelfaria :wave: thanks for raising this! As we begin to look at this issue can you share an example of how you're using the generated type with the API call in your Lambda? From the error it sounds like we may be passing `createdBy` along with the other defined properties

**Comment by AnilMaktala** [comment]
Hi @rafaelfaria 👋,  Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
