### ISSUE TITLE
How to use a non @model type in v2 transformer

### ISSUE THREAD

**Issue by SaileshKumar** [aws-amplify/amplify-category-api#586]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

API

**Amplify CLI Version**

8.0.3

**What AWS Services are you utilizing?**

Amplify, Cognito, AppSync, DynamoDB, OpenSearch, Lambda

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

I have a schema that has a variety of subjects, classes, teachers, etc. They are all models and the amplify migrate api function converted them quite nicely.

However, I have one custom implementation that I'm having trouble porting over to the new v2 transformer.

I have a custom query:

`browseAllContent: BrowseAllConnection @aws_api_key @aws_cognito_user_pools @function(name: "getBrowseAllContent-${env}")`

And the idea was to have a function to get a list to display in a "browse all" page. To have the schema compile, I had to have this typed so I did the following:

```
type BrowseAllConnection @model @auth(rules: [{allow: public, operations: [read]}, {allow: private, operations: [read]}]) {
  items: [BrowseAllSubjectClassConnection]
}

type BrowseAllSubjectClassConnection {
  subject: Subject
  classes: [Class]
  teachers: [Teacher]
}
```

However this can't push with this error:

`CREATE_FAILED               GraphQLAPITransformerSchema3CB2AE18                         AWS::AppSync::GraphQLSchema Wed Jun 22 2022 15:06:26 GMT-0400 (Eastern Daylight Time) Schema Creation Status is FAILED with details: Found 2 problem(s) with the schema: The input value type 'ClassInput' is not present when resolving type 'BrowseAllSubjectClassConnectionInput' [@3211:1]. The input value type 'TeacherInput' is not present when resolving type 'BrowseAllSubjectClassConnectionInput' [@3211:1].`

How can I replicate this type of data model in the v2 transformer?

**Comment by ykethan** [comment]
Hello @SaileshKumar, Thank you for reaching out I was able to replicate the error using the following schema on v2.

```graphql
type BrowseAllConnection @model @auth(rules: [{allow: public, operations: [read]}, {allow: private, operations: [read]}]) {
  items: [BrowseAllSubjectClassConnection]
}

type BrowseAllSubjectClassConnection {
  subject: Subject
  classes: [Class]
  teachers: [Teacher]
}

type Subject{
  id: ID!
  decp: String
}

type Class {
  id: ID!
  decp: String
  
}

type Teacher {
  id: ID!
  decp: String
}


type Browse @model @auth(rules: [{allow: public, operations: [read,update,delete]}, {allow: private, operations: [read,update,delete]}]){
Id: ID!
browseAllContent: BrowseAllConnection @function(name: "testfuncgql-${env}")
}
```
I was able to mitigate the error by removing the `@model @auth` from the Class and Teacher types. Passing a model type on a non model type resulted in the error. I was able to successfully push the following schema.
```graphql
type BrowseAllConnection @model @auth(rules: [{allow: public, operations: [read]}, {allow: private, operations: [read]}]) {
  items: [BrowseAllSubjectClassConnection]
}

type BrowseAllSubjectClassConnection {
  subject: Subject
  classes: [Class]
  teachers: [Teacher]
}

type Subject{
  id: ID!
  decp: String
}

type Class @model @auth(rules: [{allow: public, operations: [read,update,delete]}, {allow: private, operations: [read,update,delete]}]){
  id: ID!
  decp: String
  
}

type Teacher @model @auth(rules: [{allow: public, operations: [read,update,delete]}, {allow: private, operations: [read,update,delete]}]) {
  id: ID!
  decp: String
}


type Browse @model @auth(rules: [{allow: public, operations: [read,update,delete]}, {allow: private, operations: [read,update,delete]}]){
Id: ID!
browseAllContent: BrowseAllConnection @function(name: "testfuncgql-${env}")
}
```

On running a `amplify api gql-compile` the schema compiled successfully in both the cases. Hence, marking this as a bug for further improvements.

**Comment by ykethan** [comment]
Note: on testing the schema in transformer v1 both the schemas pushed successfully and no errors were displayed on gql-compile.

**Comment by SaileshKumar** [comment]
@ykethan I'm not sure if that's entirely what I want, since I also have queries like listClasses, listTeachers etc that need auth

**Comment by josefaidt** [comment]
Hey @SaileshKumar :wave: what is the motivation for not using `@model` on the non-model types wrapping model types? Have you looked into porting the custom connection tables to using the new relational directives? https://docs.amplify.aws/cli/graphql/data-modeling/#setup-relationships-between-models

**Comment by josefaidt** [comment]
Adding a p2 label specifically for adding guards around running `amplify api gql-compile` with this use case
