### ISSUE TITLE
One of our Open Search Queries is no longer returning any results

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-category-api#597]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.5

### Amplify CLI Version

9.0.0

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No.

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

Recently our Open Search Instance lost all of its data. We re-populated the data using the python script provided by Amplify - which has worked for us before when initially populating the Open Search instance. 

Two of our indices are returning data via the AppSync search queries, but one is not. I've double-checked that the correct variables were used when populating the data. 

analyticsevent | 13436 | 4.46 MiB | 90 | properties | 0
-- | -- | -- | -- | -- | --
participant | 707 | 769.09 KiB | 365 | properties | 0
resource | 1271 | 2.66 MiB | 240 | properties | 0

[analyticsevent](https://us-east-1.console.aws.amazon.com/esv3/home?region=us-east-1#opensearch/domains/amplify-opense-1dy8j8h2tuyjp/indices/analyticsevent)	
13436
4.46 MiB
90
properties	
0
[participant](https://us-east-1.console.aws.amazon.com/esv3/home?region=us-east-1#opensearch/domains/amplify-opense-1dy8j8h2tuyjp/indices/participant)	
707
769.09 KiB
365
properties	
0
[resource](https://us-east-1.console.aws.amazon.com/esv3/home?region=us-east-1#opensearch/domains/amplify-opense-1dy8j8h2tuyjp/indices/resource)	
1271
2.66 MiB
240
properties	
0

The problematic index is `resource`. 

The others are working as expected.

The example below is from the AppSync console:

```graphql
query MyQuery {
  searchResources {
    nextToken
    total
  }
  searchParticipants {
    nextToken
    total
  }
  searchAnalyticsEvents {
    nextToken
    total
  }
}

```
```json
{
  "data": {
    "searchResources": {
      "nextToken": null,
      "total": 0
    },
    "searchParticipants": {
      "nextToken": "WyJkOGI4MjZhMi1jMxxxUtYWY3Ny1hOGJkZDY2Y2E0NmUiXQ==",
      "total": 707
    },
    "searchAnalyticsEvents": {
      "nextToken": "WyJmZTMwN2Y3ZS1lxxxQ2NDgtOTBhOC1iZGNkNDViYzg4MWIiXQ==",
      "total": 10000
    }
  }
}
```

It's also worth noting that we have enabled CloudWatch logs for our Open Search instance and no errors are being reported. There is no error when running the AppSync query either, just no data being returned. We had data returned before the indexed data in Open Search was dropped. 

Any help with this would be greatly appreciated. 

Thank you in advance! 

### Expected behavior

All Open Search indices to return items. 

### Reproduction steps

1. As above.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
Hey @kylekirkby, Thank you for reaching out. I was hoping to see if you could test a sample query(not on appsync) on the opensearch domain and check if any data being returned for the index. Please refer to https://docs.aws.amazon.com/opensearch-service/latest/developerguide/searching.html for additional information.
could you provide us the resolver mapping templates used for the effected index.

**Comment by kylekirkby** [comment]
> Hey @kylekirkby, Thank you for reaching out. I was hoping to see if you could test a sample query(not on appsync) on the opensearch domain and check if any data is being returned for the index. Please refer to https://docs.aws.amazon.com/opensearch-service/latest/developerguide/searching.html for additional information. could you provide us with the resolver mapping templates used for the affected index?

Hi @ykethan,

A colleague did this yesterday and was successfully receiving results via the Open Search dashboard. However, the AppSync console in AWS was not receiving anything.

I've since removed the custom search resolvers for the Resource index and run `amplify push`. Now we are seeing results in the AppSync console. The weird thing is that the custom resolvers were working... We suspect that an Amplify deployment since we initially deployed the custom resolvers has subsequently broken things. We are unsure how. We needed the custom search resolvers to get the date sorting working correctly.

**Comment by kylekirkby** [comment]
@ykethan - so I've figured out the root cause.

My initial custom search resolver was using an index path like:

```
#set( $indexPath = "/resource/doc/_search" )
```

I checked the index path for the Amplify generated search resolvers and it was actually:

```
#set( $indexPath = "/resource/_search" )
```

Updating my custom resolver to use `/resource/_search` fixed my issue. 

So I'm guessing at some point the index path has changed and that caused our custom resolvers to stop working..?

**Comment by ykethan** [comment]
Hello @kylekirkby, thank you for the information. On testing the searchable directive with the CLI version 9.0.0 and 7.6.25. i observed the vtl template generated contained the index as `#set( $indexPath = "/<model>/_search"` 

![image](https://user-images.githubusercontent.com/87995712/176456556-3fe99d15-2633-4d09-bb44-a37a4e5119b4.png)

**Comment by ykethan** [comment]
Glad to hear that you are back up and running. Please do let us know if you require any assistance, I would be happy in diving deeper.

**Comment by kylekirkby** [comment]
@ykethan - thank you!
