### ISSUE TITLE
Rotate GraphQL API Key with a command

### ISSUE THREAD

**Issue by SaileshKumar** [aws-amplify/amplify-category-api#598]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.18.1

### Amplify CLI Version

8.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I have many lambdas that have API as a dependency. Thus when I try to upgrade an API key, I can't just use the CreateAPIKey functionality in parameters.json. When I do I get tons of:

"Output 'GraphQLAPIKeyOutput' not found in stack"

in the output.

What seems to work, is manually removing the references to GraphQLAPIKeyOutput in the backend-config.json, and then pushing with CreateAPIKey 0. After that, revert the changes and push again.

There seems to be also a similar issue for lambdas with dynamodb triggers, I think I have to remove some references there as well from the cloudformation tempaltes.

### Expected behavior

Should be able to use CreateAPIKey to manually update the api key.

### Reproduction steps

Haven't tried in empty directory, but basically:

1) Have expired API key
2) Have lambdas with API dependency
3) Try to push with CreateAPIKey 0, see failure because APIKeyOutput doesn't exist

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Transferring to amplify-category-api to address rotating API keys without two pushes (CreateAPIKey 0, push, CreateAPIKey 1, push) to mitigate effect where the API Key CFN output is not available for dependent resources (i.e. Lambda's)

**Comment by fly1030** [comment]
Hey I'm seeing the same error after I updated my API key expired and trying the same procedures as mentioned in the repro steps. I did also try to manually edit backend-config.json and *-cloudformation-template.json by removing the api dependencies, but I still can't work it around. @josefaidt do you have any other suggestions that might help? Been stuck on this for quite some time

**Comment by josefaidt** [comment]
Hey @fly1030 :wave: can you try the command noted in this comment to see if that mitigates the issue? https://github.com/aws-amplify/amplify-category-api/issues/598#issuecomment-1167738761

**Comment by josefaidt** [comment]
Hey @fly1030 :wave: let's continue this conversation on #636 to keep the workarounds relevant to the original issue (and I think you've captured a lot of great details in your description for the immediate issue)

**Comment by phani-srikar** [comment]
Please follow this comment for a work-around https://github.com/aws-amplify/amplify-category-api/issues/636#issuecomment-1425671171, closing this in favor of that issue.
