### ISSUE TITLE
Add 'X-Ray Tracing' support for GraphQL API

### ISSUE THREAD

**Issue by heitorlessa** [aws-amplify/amplify-category-api#599]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.** 

AppSync [now supports X-Ray Tracing](https://aws.amazon.com/blogs/mobile/graphql-observability-appsync-xray/) and the CLI doesn't support that yet.

**Describe the solution you'd like**
* **New APIs**: `amplify add api` to support tracing
* **Existing APIs**: `amplify update api` to support enabling tracing

**Describe alternatives you've considered**
Considered creating a custom resource in a custom stack as part of Amplify CLI deployment, however that brings operational and maintenance cost.

**Additional context**
* What this enables customers to do: https://aws.amazon.com/blogs/mobile/graphql-observability-appsync-xray/
* CloudFormation Support for this feature: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-xrayenabled

**Comment by josefaidt** [comment]
Hey folks in the thread :wave: I wanted to pop in and note our documentation page showcasing how to enable X-Ray tracing for your GraphQL API's using overrides https://docs.amplify.aws/cli/graphql/override/#customize-amplify-generated-appsync-graphql-api-resources

**Comment by AnilMaktala** [comment]
Hey @heitorlessa, This use case can be achieved using the mechanism mentioned my josef above. Hence, we are closing the issue.
