### ISSUE TITLE
Is backfill still needed for composite sort keys in transformer v2? 

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-category-api#604]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
api 

**Amplify CLI Version**
9.0.0

**What AWS Services are you utilizing?**
Appsync

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
In the legacy transformer, having more than one sort key came with caveat of having to do manual backfills. See https://docs.amplify.aws/cli-legacy/graphql-transformer/key/#evolving-apis-with-key. 

> "If adding an @key with 3 or more fields, you will need to back-fill the new composite sort key for existing data. With a @key(fields: ["email", "status", "date"]), you would need to backfill the status#date field with composite key values made up of each object's status and date fields joined by a #. You do not need to backfill data for @key directives with 1 or 2 fields."

While in the [latest documentation](https://docs.amplify.aws/cli/graphql/data-modeling/), this is not mentioned. Can you clarify if this limitation still exists if I have two or more sortKeyFields for an index?

**Comment by hisham** [comment]
Thanks, I didn't see that. Might be helpful to put that note where sortKeys are discussed in https://docs.amplify.aws/cli/graphql/data-modeling/#setup-database-tables or in https://docs.amplify.aws/cli/graphql/schema-evolution/. 

Also there's a typo: "You do not need to backfill data for @index directives with **none of one** sort key fields."

**Comment by ykethan** [comment]
Hey @hisham, Thank you for pointing that. We will work on rectifying this.

**Comment by ykethan** [comment]
https://github.com/aws-amplify/docs/pull/4425/
Adding PR link for reference

**Comment by josefaidt** [comment]
Closed due to docs PR merge 🎉
