### ISSUE TITLE
Dynamic group auth cannot share a field with an index

### ISSUE THREAD

**Issue by ChapterSevenSeeds** [aws-amplify/amplify-category-api#61]
### Before opening, please confirm:

- [x] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

14.19.1

### Amplify CLI Version

7.6.26

### What operating system are you using?

Windows 11

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes as far as I know.

### Amplify Categories

api

### Amplify Commands

codegen, publish, push

### Describe the bug

Given a simple tenant/user authorization based workflow with AWS Cognito, consider the following schema:

```graphql
type Todo
@model
@auth(rules: [{allow: groups, groupsField: "tenant", operations: [create, read, update, delete]}])
{
  id: ID!
  tenant: ID! @index(name: "todosByTenant", sortKeyFields: ["title"], queryField: "todosByTenant")
  title: String!
  body: String!
}
```

Both `amplify api gql-compile` and `amplify codegen` work fine. A subsequent `amplify push` also works. The `Todo` table gets created with the proper secondary index. However, when querying the `todosByTenant` index, authorization forever fails. This is what my query looks like:
```graphql
query GetTodos {
  todosByTenant(tenant: "my-tenant") {
    items {
      id
    }
  }
}
```

The query errors out with the following response message: "Not Authorized to access todosByTenant on type ModelTodoConnection". I have found that a workaround is to write the schema like this:
```graphql
type Todo
@model
@auth(rules: [{allow: groups, groupsField: "tenant", operations: [create, read, update, delete]}])
{
  id: ID!
  tenant: ID!
  tenantName: String! @index(name: "todosByTenant", sortKeyFields: ["name"], queryField: "todosByTenant")
  title: String!
  body: String!
}
```
Only when the schema is written like this does the same query above return the Todos associated with my tenant. This was not an issue with GraphQL Transformer V1. The issue also occurs if the `groupsField` for the `@auth` directive is the primary key of the table. Is this behavior expected? In case you're wondering, the reason we don't just use the `listTodos` query is because, if the table is large enough with sparse tenants, we may have to paginate through multiple empty responses in order to get at least one item back from the table. 

### Expected behavior

Querying by the `todosByTenant` index in the first schema example shown in the bug description does not cause an unauthorized error. It should return the todos associated with that tenant. 

### Reproduction steps

1. Start a new Amplify project.
2. Add some basic Cognito auth to said project.
3. Create a GraphQL API for the project.
4. Place the first example schema in the bug description into your schema.
5. Push all changes to the cloud.
6. Attempt to query by the `todosByTenant` index.

### GraphQL schema(s)

```graphql
type Todo
@model
@auth(rules: [{allow: groups, groupsField: "tenant", operations: [create, read, update, delete]}])
{
  id: ID!
  tenant: ID! @index(name: "todosByTenant", sortKeyFields: ["title"], queryField: "todosByTenant")
  title: String!
  body: String!
}
```

### Log output

```
Not Authorized to access todosByTenant on type ModelTodoConnection
```

### Additional information

Each Cognito user has a custom field called `custom:tenant` which specifies what tenant to which the user pertains. With this, we also have a pre token generation lambda function integrated into Cognito which will place this tenant and the user's role into the cognito groups portion of the access token. The payload of the JWT token that is passed along to Appsync calls is decoded like so (with some redactions): 

```jsonc
{
  "cognito:groups": [
    "my-tenant",
    "Admin"
  ],
  "username": "my-username",
  "exp": 1649343139,
  // ...other JWT token fields
}
```

**Comment by naedx** [comment]
I'm also interested in a solution to this due to my related problem.

For the moment, [I've resorted to creating a field to hold the same information I need](https://github.com/aws-amplify/amplify-category-api/issues/495#issuecomment-1152936439) . But it requires extra care to make sure the value is being set consistently, everywhere, including resolver overrides just to set this value.

**Comment by Gzing** [comment]
Facing this issue on the latest amplify, not sure if there are any workarounds where we do not need to create a separate field and duplicate the data.

**Comment by olivertang** [comment]
Facing this issue as well - can we **please** get this fixed soon? We have a workaround that's causing some us to inherit some tech debt

**Comment by dkwong** [comment]
Facing the same issue as others have, would love an update on ETA.

**Comment by Kokonaut** [comment]
+1. Also dealing with this issue.

**Comment by naedx** [comment]
I'm still waiting for it as well.

**Comment by naedx** [comment]
I'm on version 10.3.0 now and it _appears_ to me that the issue is fixed. 

Does anyone else have the same experience with this?

**Comment by naedx** [comment]
Sorry guys. False alarm. The issue still persists. 


:(

**Comment by MtthwBrwng** [comment]
I'm also having this issue CLI version `10.2.3`, current workaround is duplicating a field specifically for tenant.

**Comment by biller-aivy** [comment]
Any update here?

**Comment by alharris-at** [comment]
Hi folks, unfortunately no update here. This is currently not prioritized against other items, but if anybody is willing to propose a change, we'd be happy to discuss merging a fix. It's worth noting that authorization changes require some additional internal scrutiny, so if you have a proposal, I'd recommend writing it up and submitting a PR w/ the design before moving onto implementation, so we can circle up internally and review.
