### ISSUE TITLE
How to design a schema.graphql and use amplify mock API to return a custom getAll method 

### ISSUE THREAD

**Issue by sboland-terem** [aws-amplify/amplify-category-api#612]
**Which Category is your question related to?**
Mocking API.

**Amplify CLI Version**
Version 9.0.0

**What AWS Services are you utilizing?**
Amplify, AppSync.

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
I am using Amplify in a simple use case to mock an existing frontend.   I have a cutdown schema.graphql as follows:

```
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } }

schema {
  query: Query
}

type Query {
  getAirports: [Airport]
}

type Airport @model {
  id: Int! @primaryKey 
  code: String!
  city: String!
  country: String!
}
```
The getAirports query is intended to return all the airports.    I run ```amplify mock api``` and it generates all the resolvers 
for getAirport, getAirports and listAirports.

When I navigate to http://localhost:20002, I can see the option to use ```getAirports```, however it returns null even when data is present in the mocked database.   The response is:

```
{"data":null,"errors":[{"message":"Cannot return null for non-nullable field Query.getAirports.","locations":[{"line":2,"column":3}],"path":["getAirports"]}]}
```

```listAirports``` generates all the data, however, I want a separate ```getAirports``` which returns all objects.

**Comment by sboland-terem** [comment]
@josefaidt - When I run `amplify mock api` it automatically generates the resolvers for the new query `getAirports`.  For example, in the directory amplify/backend/resolvers there are files 
`Query.getAirports.req.vtl `and `Query.getAirports.res.vtl `.    This is what the first one looks like:

```
## [Start] Get Request template. **
#set( $GetRequest = {
  "version": "2018-05-29",
  "operation": "Query"
} )
#if( $ctx.stash.metadata.modelObjectKey )
  #set( $expression = "" )
  #set( $expressionNames = {} )
  #set( $expressionValues = {} )
  #foreach( $item in $ctx.stash.metadata.modelObjectKey.entrySet() )
    #set( $expression = "$expression#keyCount$velocityCount = :valueCount$velocityCount AND " )
    $util.qr($expressionNames.put("#keyCount$velocityCount", $item.key))
    $util.qr($expressionValues.put(":valueCount$velocityCount", $item.value))
  #end
  #set( $expression = $expression.replaceAll("AND $", "") )
  #set( $query = {
  "expression": $expression,
  "expressionNames": $expressionNames,
  "expressionValues": $expressionValues
} )
#else
  #set( $query = {
  "expression": "id = :id",
  "expressionValues": {
      ":id":     $util.parseJson($util.dynamodb.toDynamoDBJson($ctx.args.id))
  }
} )
#end
$util.qr($GetRequest.put("query", $query))
#if( !$util.isNullOrEmpty($ctx.stash.authFilter) )
  $util.qr($GetRequest.put("filter", $util.parseJson($util.transform.toDynamoDBFilterExpression($ctx.stash.authFilter))))
#end
$util.toJson($GetRequest)
## [End] Get Request template. **
```

So from your link, it suggests I can create a custom resolver.  However, it appears that the mock api does this already.  Can you clarify this?  And I'm unclear why the resolver above returns null even with data in the `mock-data/dynamodb/fake_us-fake-1.db`?  The listAirports resolver works though.

**Comment by josefaidt** [comment]
Hey @sboland-terem thank you for clarifying! Yes, for custom queries and mutations we will need to write a resolver to return the data, which can be accomplished via VTL templates or a Lambda function.

> When I run `amplify mock api` it automatically generates the resolvers for the new query `getAirports`.  In one case I thought I saw files amplify/backend/resolvers there are files 
`Query.getAirports.req.vtl `and `Query.getAirports.res.vtl `.    

Can you confirm whether you continuously experience this? I was not able to reproduce this behavior using the provided schema. 

The CLI will generate resolvers for the auto-generated queries and mutations such as `getAirport`, `listAirports`, etc.
