### ISSUE TITLE
--allow-destructive-graphql-schema-updates showing - Message: No updates are to be performed

### ISSUE THREAD

**Issue by dylan-westbury** [aws-amplify/amplify-category-api#629]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

sudo npm install -g @aws-amplify/cli --unsafe-perm=true

### If applicable, what version of Node.js are you using?

v16.13.1

### Amplify CLI Version

9.1.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Deleted deployment-state.json a few times here and there due to some states amplify push would get stuck in.

### Amplify Categories

api

### Amplify Commands

push, Not applicable

### Describe the bug

For some AppSync schema models, its not possible to re-create **some** when attempting to change the primary key. In my case removing a custom primary key. 

I was able to re-create a simple model that had no connections, not tied to any custom mutations or was a lambda function dependency. 

For a more complicated model, I'm not able to recreate that has custom mutations and lambda function dependencies.

### Expected behavior

Models should always re-create when calling --allow-destructive-graphql-schema-updates

### Reproduction steps

**1. Create model** 
* Create schema with a custom primary key
* Remove default create and delete mutations from schema
* Create custom create and delete lambda functions and add the model as dependency 
* Add custom mutations to schema that link model with lambda function

![Screen Shot 2022-07-07 at 1 34 58 pm](https://user-images.githubusercontent.com/16129043/177685390-c6edf255-9f78-481b-927e-8182a5ff1f5d.png)

![Screen Shot 2022-07-07 at 1 32 26 pm](https://user-images.githubusercontent.com/16129043/177685144-480d2672-3404-46fb-820f-63f69ec9eca4.png)

![Screen Shot 2022-07-07 at 1 32 57 pm](https://user-images.githubusercontent.com/16129043/177685160-19d96aeb-9991-4f57-82cd-1d816e09a731.png)

**2. Remove custom primary key from schema - amplify push - as expected does not work** 
![Screen Shot 2022-07-07 at 1 38 00 pm](https://user-images.githubusercontent.com/16129043/177685573-993f6d26-7518-419e-bfec-aa9a1b07481d.png)

**3. Remove custom primary key from schema - amplify push --allow-destructive-graphql-schema-updates OR  amplify api rebuild --allow-destructive-graphql-schema-updates - does not work** 

![Screen Shot 2022-07-07 at 1 35 25 pm](https://user-images.githubusercontent.com/16129043/177686932-1dbf38ac-213a-4a4a-ad75-82f4d7eafde6.png)

<img width="631" alt="Screen Shot 2022-07-07 at 1 49 22 pm" src="https://user-images.githubusercontent.com/16129043/177686861-e2a23140-284a-4477-91f3-3eeccae8b493.png">

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
# ****************************************************************************
# ADMIN
# ****************************************************************************
type Admin
  @model(subscriptions: null, mutations: { create: null, update: "updateAdmin", delete: null })
  @auth(rules: [
    { allow: groups, groups: ["SuperAdmins"], operations: [create, update, read, delete] }
    { allow: groups, groups: ["Admins"], operations: [read] }
    { allow: owner, operations: [read, update] }
  ]) {
    # userId: ID! @primaryKey
    country: String!
    firstName: String!
    lastName: String!
    email: AWSEmail!
    phone: AWSPhone
    role: AdminRole
    hasAccessed: Boolean
    createdBy: ID
    createdAt: AWSDateTime
    updatedAt: AWSDateTime
}

# ****************************************************************************
# MUTATIONS
# ****************************************************************************
 type Mutation {
   createAdminItem(input: CreateAdminInput): Admin @function(name: "TemplateCreateAdmin-${env}")
   deleteAdminItem(input: DeleteAdminInput): Admin @function(name: "TemplateDeleteAdmin-${env}")
 }

```

</details>

### Project Identifier

e2e641d97a6320f5f38e4746bc43a19c

### Log output

<details>

```
# Put your logs below this line

2022-07-07T03:40:42.730Z|error : amplify-provider-awscloudformation.push-resources.run([{"resourcesToBeCreated":[],"resourcesToBeUpdated":[{"service":"AppSync","providerPlugin":"[***]rmation","dependsOn":[{"category":"auth","resourceName":"[***]eAuth","attributes":["UserPoolId"]}],"output":{"authConfig":{"defaultAuthentication":{"authenticationType":"AMAZON_COGNITO_USER_POOLS","userPoolConfig":{"userPoolId":"[***]ateAuth"}},"additionalAuthenticationProviders":[]},"GraphQLAPIIdOutput":"[***]xxxxx","GraphQLAPIEndpointOutput":"https://xxxxxx.appsync-api.us-east-1.amazonaws.com/graphql"},"providerMetadata":{"s3TemplateURL":"https://s3.amazonaws.com/amplify-template-dev-xxxxxxxx-deployment/amplify-cfn-templates/api/cloudformation-template.json","logicalId":"[***]ateAPI"},"lastPushTimeStamp":"2022-07-07T03:38:03.744Z","lastPushDirHash":"Yud0uc8aWfuOFw0KnHD/VVNEO98=","resourceName":"[***]teAPI","category":"api"}],"resourcesToBeSynced":[],"resourcesToBeDeleted":[],"rootStackUpdated":true,"tagsUpdated":false,"allResources":[{"service":"AppSync","providerPlugin":"[***]rmation","dependsOn":[{"category":"auth","resourceName":"[***]eAuth","attributes":["UserPoolId"]}],"output":{"authConfig":{"defaultAuthentication":{"authenticationType":"AMAZON_COGNITO_USER_POOLS","userPoolConfig":{"userPoolId":"[***]ateAuth"}},"additionalAuthenticationProviders":[]},"GraphQLAPIIdOutput":"[***]agrusfay6cy","GraphQLAPIEndpointOutput":"https://xxxxxx.appsync-api.us-east-1.amazonaws.com/graphql"},"providerMetadata":{"s3TemplateURL":"https://s3.amazonaws.com/amplify-template-dev-xxxxxx-deployment/amplify-cfn-templates/api/cloudformation-template.json","logicalId":"[***]ateAPI"},"lastPushTimeStamp":"2022-07-07T03:38:03.744Z","lastPushDirHash":"Yud0uc8aWfuOFw0KnHD/VVNEO98=","resourceName":"[***]teAPI","category":"api"}]}])
DeploymentError: ["Index: 0 State: {\"deploy\":\"deploying\"} Message: No updates are to be performed."]

</details>


### Additional information

Haven't found a work around to resolve, could maybe create new env for now but haven't tried yet.

**Comment by josefaidt** [comment]
Hey @dylan-westbury :wave: thanks for raising this! In your screenshot in step 2 it shows the warning with `amplify push`? Are you able to then re-run push with the destructive updates flag? It does appear something goes awry after that failed attempt and modifying the schema again, however I'm a bit confused by the steps. Was the primary key added along with the model & api creation or was this added with the edits (after previously pushing without a custom primary key)

**Comment by dylan-westbury** [comment]
Hi @josefaidt 

Yes so after step 2 I push with the destructive updates flags. Also had to do an amplify pull --restore each time then re-do the remove of custom primary key as the env gets into a weird state. 

<img width="1131" alt="Screen Shot 2022-07-07 at 8 21 28 pm" src="https://user-images.githubusercontent.com/16129043/177886379-af08e55d-fa93-49c4-aaab-4381bfe88e4f.png">

So the model was originally created with a custom primary key (userId), but as the graphql server expects the userId to be generated on the client side, we are trying to remove the custom primary key where the issue is occurring.

We were able to push the destructive updates for 1 model, but not this one. I assume because lambda functions depends on it (create, update, delete permissions, etc).

**Comment by josefaidt** [comment]
Hey @dylan-westbury apologies for the delay here. Although I was not able to reproduce this issue it appears you have found a workaround? 

>  but as the graphql server expects the userId to be generated on the client side, we are trying to remove the custom primary key where the issue is occurring.

Can you clarify this piece? Are you referring to the generated code in the `src/` directory?

> We were able to push the destructive updates for 1 model, but not this one. I assume because lambda functions depends on it (create, update, delete permissions, etc).

Do you have the following feature flag set in your `cli.json` by chance? 

```json
"appsync": {
      "generategraphqlpermissions": true
    },
```

**Comment by dylan-westbury** [comment]
Hi @josefaidt ,

We just created a new environment as a work around, so we no longer have the issue.

Essentially we had assigned a custom @PrimaryKey to a model. When we removed it to allow the model to auto-generate, were facing this issue. 


Yes we do have it set.

```
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true,
      "securityenhancementnotification": false,
      "showfieldauthnotification": false,
      "usesubusernamefordefaultidentityclaim": true,
      "usefieldnameforprimarykeyconnectionfield": false,
      "enableautoindexquerynames": false
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true,
      "forcealiasattributes": false,
      "useenabledmfas": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "latestregionsupport": {
      "pinpoint": 1,
      "translate": 1,
      "transcribe": 1,
      "rekognition": 1,
      "textract": 1,
      "comprehend": 1
    },
    "project": {
      "overrides": true
    }
  },
  "debug": {
    "shareProjectConfig": false
  }
}
```
