### ISSUE TITLE
amplify push failed with the "A deployment is in progress" error

### ISSUE THREAD

**Issue by bipinparmar** [aws-amplify/amplify-category-api#638]
> amplify -v
5.4.0

My amplify project manages the dynamodb tables. Up until today, whenever I added or changed schema, the push worked. Today something went wrong. I have googled and tried many solutions but with no success. 

> ampliy push
A deployment is in progress.
If the prior rollback was aborted, run:
"amplify push --iterative-rollback" to rollback the prior deployment
"amplify push --force" to re-deploy

> amplify push
["Index: 0 State: {\"deploy\":\"deploying\"} Message: Stack:arn:aws:cloudformation:us-west-2:611452414879:stack/amplify-statsweb-dev-151014-apistats-VWR5V9BO4131/7eb5c9a0-2a17-11ec-900f-06c939e0aa2d is in UPDATE_ROLLBACK_FAILED state and can not be updated."]
An error occurred during the push operation: ["Index: 0 State: {\"deploy\":\"deploying\"} Message: Stack:arn:aws:cloudformation:us-west-2:611452414879:stack/amplify-statsweb-dev-151014-apistats-VWR5V9BO4131/7eb5c9a0-2a17-11ec-900f-06c939e0aa2d is in UPDATE_ROLLBACK_FAILED state and can not be updated."]

> amplify push --force
["Index: 0 State: {\"deploy\":\"deploying\"} Message: Stack:arn:aws:cloudformation:us-west-2:611452414879:stack/amplify-statsweb-dev-151014-apistats-VWR5V9BO4131/7eb5c9a0-2a17-11ec-900f-06c939e0aa2d is in UPDATE_ROLLBACK_FAILED state and can not be updated."]
An error occurred during the push operation: ["Index: 0 State: {\"deploy\":\"deploying\"} Message: Stack:arn:aws:cloudformation:us-west-2:611452414879:stack/amplify-statsweb-dev-151014-apistats-VWR5V9BO4131/7eb5c9a0-2a17-11ec-900f-06c939e0aa2d is in UPDATE_ROLLBACK_FAILED state and can not be updated."]

I also deleted the deployment-state.json and then tried amplify push. It did not work

On the CloudInformation page, I clicked "continue update rollback" for the parent stack of "7eb5c9a0-2a17-11ec-900f-06c939e0aa2d". It did not work.

Any ideas on how I can resolve the issue?

**Comment by josefaidt** [comment]
Hey @bipinparmar :wave: thanks for raising this and apologies for the delay here! I see you're using an older version of the CLI. Do you also experience this issue after upgrading the CLI to the latest version?

**Comment by bipinparmar** [comment]
I did upgrade to the latest version of the CLI by running "amplify upgrade". I did it again and still the issue for the "amplify push --force" command

? Are you sure you want to continue? Yes
⠦ Waiting for previous deployment to finish✖ An error occurred when pushing the resources to the cloud

["Index: 1 State: {\"preRollback\":\"previousDeploymentReadyCheck\"} Message: Resource is not in the state stackUpdateComplete"]
An error occurred during the push operation: ["Index: 1 State: {\"preRollback\":\"previousDeploymentReadyCheck\"} Message: Resource is not in the state stackUpdateComplete"]

**Comment by konnofuente** [comment]
i have the same problem on my side amplify push force not working after changing my shema.graphql

**Comment by josefaidt** [comment]
Hey @bipinparmar and @konnofuente apologies for the delay here, could you describe the type of changes you were making to the GraphQL schema prior to the original failed push attempt? Were these changes to a primary key? 

This second message, `previousDeploymentReadyCheck` appears to be caused by another running deployment or a stray `deployment-state.json` file in the deployment bucket.

As a follow up question, would you mind posting the project identifier returned from executing `amplify diagnose --send-report`?

**Comment by bipinparmar** [comment]
Hi @josefaidt , thank you for responding to my issue. I was not changing the primary key. When I run the diagnose command, I get an error:
$ amplify diagnose --send-report
The Amplify CLI can NOT find command:  diagnose

I see a list of command below the error and diagnose is not one of them

**Comment by bipinparmar** [comment]
Hi @josefaidt , amplify push excited with the following error:
GraphQL schema compiled successfully.

Edit your schema at /Users/bipin/Projects/stats-web/amplify/backend/api/stats/schema.graphql or place .graphql files in a directory at /Users/bipin/Projects/stats-web/amplify/backend/api/stats/schema
A deployment is in progress.
If the prior rollback was aborted, run:
"amplify push --iterative-rollback" to rollback the prior deployment
"amplify push --force" to re-deploy

amplify push --force exited with the following error
⠹ Waiting for previous deployment to finish✖ An error occurred when pushing the resources to the cloud

["Index: 1 State: {\"preRollback\":\"previousDeploymentReadyCheck\"} Message: Resource is not in the state stackUpdateComplete"]
An error occurred during the push operation: ["Index: 1 State: {\"preRollback\":\"previousDeploymentReadyCheck\"} Message: Resource is not in the state stackUpdateComplete"]

**Comment by bipinparmar** [comment]
I am just going to create a new amplify project and start from scratch.
