### ISSUE TITLE
Cannot access ModelConnection with auth rules

### ISSUE THREAD

**Issue by OlgaMaslova** [aws-amplify/amplify-category-api#641]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.2

### Amplify CLI Version

9.1.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Nothing

### Amplify Categories

auth

### Amplify Commands

Not applicable

### Describe the bug

For configurated auth rules cannot retrieve the results of a query list from AppSync console (IAM).
`
{
  "data": {
    "listSpaces": null
  },
  "errors": [
    {
      "path": [
        "listSpaces"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access listSpaces on type ModelSpaceConnection"
    }
  ]
}
`

### Expected behavior

The query returns the result.

### Reproduction steps

1. Create model with following auth rules:
`@auth(rules: [{ allow: public, operations: [read], provider: iam },
  { allow: private, provider: userPools }])`

2. Configurate api auth:
`
"defaultAuthType": {
      "mode": "AMAZON_COGNITO_USER_POOLS",
      "cognitoUserPoolId": "***"
    },
    "additionalAuthTypes": [
      {
        "mode": "AWS_IAM"
      }
`
3. Go to AppSync console and choose auth type : IAM.
4. Choose Query "listSpaces".
query MyQuery {
  listSpaces {
    items {
      id
    }
  }
}

### GraphQL schema(s)

<details>

```graphql
type Space @model
@aws_iam
@aws_cognito_user_pools
@auth(rules: [{ allow: public, operations: [read], provider: iam },
  { allow: private, provider: userPools }])
{
  id: ID! @primaryKey
  name: String!
  addresses: String
  annexes: String
  tags: [String]
  latitude: Float
  longitude: Float
  metadata: String
  level: LevelStatus
  deletedAt: AWSTimestamp
  properties: [Property] @hasMany(indexName: "bySpace", fields: ["id"])
  zones: [Zone] @hasMany(indexName: "bySpace", fields: ["id"])
  constructionYear: String
  classEnergyConsumption: String
  classGes: String
  status: SpaceStatus
  guestLink: String
}


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

All configurations were performed with cli (amplify add auth, amplify update api...).

**Comment by ykethan** [comment]
Hello @OlgaMaslova, Thank you for reaching. By default the IAM on AppSync console will throw an unauthorized error as AppSync console will need explicit permission to allow this. This is to ensure we allow least privilege access. Please refer to https://docs.amplify.aws/cli/graphql/authorization-rules/#use-iam-authorization-within-the-appsync-console on how to add these permissions.

**Comment by OlgaMaslova** [comment]
@ykethan , thanks, I saw this section indeed. However, I tried with auth and unauth role. Did not work... 
Which roles should I  put in order to test both : public and private auth rules? Thanks!

What I tried:
`{
    "adminRoleNames": ["amplify-apiname-ENV-*****-unauthRole"]
  }`

**Comment by ykethan** [comment]
Hey @OlgaMaslova, could you please try adding your `IAM_USER` name in the `adminRoleNames` and test the API on AppSync console. I was able to test this in my application by adding my IAM user name.
You can find the IAM user name in you console by clicking on the profile name present at the right side top of the screen.

**Comment by OlgaMaslova** [comment]
@ykethan still Unauthorized with:
`{
    "adminRoleNames": ["arn:aws:iam::AppID:user/myIAM"]
  }`

**Comment by ykethan** [comment]
@OlgaMaslova, not the ARN just the name of the IAM user.

**Comment by ykethan** [comment]
Hey @OlgaMaslova, I tested the following schema in my Amplify application.

```graphql
type Space @model
@auth(rules: [{ allow: public, operations: [read], provider: iam },
  { allow: private, provider: userPools }])
{
  id: ID!
  name: String!
  addresses: String
  annexes: String
  tags: [String]
  latitude: Float
  longitude: Float
  metadata: String
  level: LevelStatus
  deletedAt: AWSTimestamp
  properties: [Property] @hasMany(indexName: "bySpace", fields: ["id"])
  zones: [Zone] @hasMany(indexName: "bySpace", fields: ["id"])
  constructionYear: String
  classEnergyConsumption: String
  classGes: String
  status: String
  guestLink: String
}

type LevelStatus @model
@auth(rules: [{ allow: public, operations: [read], provider: iam },
  { allow: private, provider: userPools }])
{
  id: ID!
  name: String!

}

type Property @model
@auth(rules: [{ allow: public, operations: [read], provider: iam },
  { allow: private, provider: userPools }])
{
  id: ID! 
  name: String!
  spaceID: ID! @index(name: "bySpace")
}

type Zone @model
@auth(rules: [{ allow: public, operations: [read], provider: iam },
  { allow: private, provider: userPools }])
{
  id: ID!
  name: String!
  spaceID: ID! @index(name: "bySpace")
}

```
added the custom-roles.json 
![image](https://user-images.githubusercontent.com/87995712/179264815-c22e24fd-8878-4ff3-8d87-c686b3a373fd.png)

and pushed my application.

Then on my AppSync console I performed the list query.

![image](https://user-images.githubusercontent.com/87995712/179265016-cced9e96-f13f-4331-b86d-1c39f0d432b9.png)

Could you please let us know if the models(LevelStatus, Property, Zone ) currently being added to the Space Model currently do have auth rules added to access IAM.

**Comment by OlgaMaslova** [comment]
@ykethan found it! it was a typo in the file name of "custom_roles". 
Thanks a lot for your time. It works now.
