### ISSUE TITLE
How do I use a custom GraphQL Lambda Authorizer with Congito users?

### ISSUE THREAD

**Issue by demilp** [aws-amplify/amplify-category-api#651]
I need to create Accounts and each account has multiple users that can access it. I have been using Cognito groups with groups auth rule in the GraphQL schema, but that has a limit of 50 groups.
To do this I have to create some custom auth logic, but doesn't seem to be that straight forward. For starters I need to verify the JWT, and for that I need to get the UserPoolId.

```
const {
    authorizationToken,
    requestContext: { apiId, accountId },
  } = event;
  verifier = verifier || CognitoJwtVerifier.create({
    userPoolId: (await new CognitoIdentityServiceProvider().listUserPools({ MaxResults: 999 }).promise()).UserPools
      .find(pool => pool.Name === appName-${process.env.ENV}).Id,
    tokenUse: "access",
    clientId: apiId,
  });
```

The issue with this code is that the lambda function doesnt have permissons to list user pools.

Apart of that, I understand that I would then need to parse the GraphQL request to get what data source and item it is being queried.

Isn't there a more straight forward way I am missing?

**Comment by josefaidt** [comment]
Hey @demilp apologies for the delay here! Were you able to find a solution to this?

**Comment by phani-srikar** [comment]
Closing due to in-activity.
