### ISSUE TITLE
@auth on custom queries and resolvers without @model

### ISSUE THREAD

**Issue by zirkelc** [aws-amplify/amplify-category-api#652]
My question is related to the following issues, but these are quite old and already closed:

https://github.com/aws-amplify/amplify-cli/issues/2711
https://github.com/aws-amplify/amplify-cli/pull/3590
https://github.com/aws-amplify/amplify-cli/issues/2540
https://github.com/aws-amplify/amplify-cli/issues/2701

I want to use the `@auth` directive on custom queries that are resolved by a Lambda via `@function`. 

```graphql
type Query {
  getNode(identity: ID!): NodeRecord
    @function(name: "graphql-${env}-resolver")
    @auth(rules: [
      { allow: private }
    ])
}

type NodeRecord {
  node: GraphNode!
}

type GraphNode {
  identity: ID!
  labels: [String!]!
  properties: AWSJSON!
}
```
After `amplify api gql-compile` I get the following compiled schema
```graphql
type Query {
  getNode(identity: ID!): NodeGraphRecord @aws_iam @aws_cognito_user_pools
}
````

When I test `getNode` query via the AppSync Console I get the following an error: 
`Unauthorized: Not Authorized to access node on type NodeRecord`

I guess that happens because the `@auth` on `getNode` query does not propagate down to the return type `NodeRecord`. If I add the same `@auth` also on the type, I get the following error Amplify: 
`Types annotated with @auth must also be annotated with @model.`

From browsing through the issues, the only workaround currently is to use `@auth` on Query fields (like I did) and additionally add `@aws_iam` and `@aws_cognito_user_pools` to the return type and all of its fields. See comment https://github.com/aws-amplify/amplify-cli/issues/2701#issuecomment-595340476

Could someone from the Amplify team explain if that's still the only workaround? Will it be possible to use `@auth` on non-model types any time soon? 

I would also suggest to add this limitation to the documentation on the [Authorization rules](https://docs.amplify.aws/cli/graphql/authorization-rules/).

**Which Category is your question related to?**
API (GraphQL) and Auth
**Amplify CLI Version**
7.6.22

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
AppSync, Cognito User Pools, IAM

**Comment by no8gerrard** [comment]
Hello @zirkelc.  
I have the same problem you had in this issue.  
Thanks to your question, now i know that i can't use auth for non-model types.  
Could you please share how you finally solved this problem?

**Comment by no8gerrard** [comment]
> 

I'm sorry that notification by mention...  
I solved my problem by writing the type as below.  
```
type NodeRecord @aws_cognito_user_pools {
  node: GraphNode!
}
```

**Comment by morepe** [comment]
Fell into the same issue. I followed the instructions here: https://docs.amplify.aws/cli/graphql/custom-business-logic/.
However in the example that the are using just a string instead of an object is returned. In my opinion its just a bad documentation. 
On the whole website its not described at all, that you need to use something else than @auth when writing custom resolver.

**Comment by josefaidt** [comment]
Hey @zirkelc :wave: apologies for the delay here. Are you still experiencing this? Were you able to verify user access?

**Comment by jawwadturabi** [comment]
I'm experiencing this issue as well when I write something like this it's not working at all.

`addBADetails(input: BADetailsInput!): BADetails! 
    @function(name: "UserQueries-${env}") 
    @auth(rules: [{ allow: owner, ownerField: "userId" }])`

**Comment by phani-srikar** [comment]
@jawwadturabi dynamic owner based authorization is not supported on custom queries/mutations.
