### ISSUE TITLE
Self relation in graphql v2

### ISSUE THREAD

**Issue by IsmetGlumcevic** [aws-amplify/amplify-category-api#654]
I can't get children of parent category? It is empty array. Here is my schema:

    `type Category
      @model
      @auth(
      rules: [
        { allow: groups, groups: ["Admin"] }
        { allow: owner, operations: [create, update, delete, read] }
        {  allow: private, operations: [read] }
        { allow: public, operations: [read] }
    ]
    ) {
    id: ID!
    parentID: ID!
    title: String!
    order: Int
    type: String! @index(name: "categoriesByOrder", queryField: "categoriesByOrder", sortKeyFields: ["order"])
    parent: Category @belongsTo(fields: ["parentID"])
    children: [Category] @hasMany
    articles: [Article] @hasMany(indexName: "byCategory", fields: ["id"])
    }`

 I try to make categories with nested subcategories. Is this schema good for this situation?

Which Category is your question related to?
Graphql API

Amplify CLI Version
5.1.1

**Comment by christianMisch** [comment]
This feature would solve my issue to model a User who can have other User entities as friends. Otherwise I have to model a  many to many relationship. 

`type User @model {
    id: ID!
    name: String
    friends: [Friend!] @manyToMany(relationName: "UserFriends")
}`

`type Friend @model {
    id: ID!
    name: String
    friends: [User!] @manyToMany(relationName: "UserFriends")
}`

**Comment by josefaidt** [comment]
Hey @IsmetGlumcevic and @christianMisch :wave: thanks for raising this and apologies for the delay! This looks similar to another issue where [there was a suggestion](https://github.com/aws-amplify/amplify-category-api/issues/728#issuecomment-1213594756) to break the self-relation out to a separate table. This would also help define the depth of the nested categories.

**Comment by christianMisch** [comment]
Hi @josefaidt that is actually a very smart solution to break down the many to many relationship into a separate table. I haven't implemented it yet but in my opinion it looks legit. I used that pattern to manually implement many to many for some other table. Thanks for the input.
