### ISSUE TITLE
Performing an inner join on `@searchable`-generated OpenSearch instances (by running SQL commands or otherwise)

### ISSUE THREAD

**Issue by ataibarkai** [aws-amplify/amplify-category-api#655]
**Which Category is your question related to?**
API (GraphQL)

**Amplify CLI Version**
8.0.3

**What AWS Services are you utilizing?**
Relevant here: @model (DynamoDB) and @searchable (OpenSearch) directives on the GraphQL API (AppSync) 

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

The OpenSearch instance (/cluster) backing the `@searchable` directive on the GraphQL API supports running SQL query against the data, including inner joins (e.g. see [here](https://opensearch.org/docs/latest/search-plugins/sql/complex/)).
I have confirmed this using the Kibana dashboard for my OpenSearch instance.
I am trying to take advantage of this functionality in production to facilitate certain API queries relying on an inner JOIN operation.

Before I get further: Is it possible to perform an inner join across 2 indices using the standard @searchable-generated queries on the GraphQL API? If it is possible, I would strongly prefer this approach.

_Assuming it is not possible:_
What is the best way to facilitate this behavior? The tricky part is essentially this:
**how can you run a SQL query against the `@searchable`-generated OpenSearch instance from an amplify-generated lambda function?**

Which can be broken down into:
(1) reference the relevant OpenSearch instance/domain from the lambda function
(2) configure the OpenSearch fine-grained access control instance to provide the lambda function with the required permission.

This could be an extremely powerful feature in many stacks so hopefully a resolution for this can make it into the wiki.

**Comment by AnilMaktala** [comment]
Hi 👋, This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.

Thank you!
