### ISSUE TITLE
Setting custom header in the response of a graphql lambda resolver

### ISSUE THREAD

**Issue by pedramp20** [aws-amplify/amplify-category-api#656]
Is it possible to set a custom HTTP header in the response of a graphql lambda resolver?

**Comment by josefaidt** [comment]
Hey @pedramp20 :wave: thanks for raising this and apologies for the delay! Were you able to find a solution to this? What is the use case for adding an additional header from the Lambda resolver?

**Comment by phani-srikar** [comment]
Closing this due to in-activity.
