### ISSUE TITLE
Not Authorized to access getUser on type User

### ISSUE THREAD

**Issue by parad0x96** [aws-amplify/amplify-category-api#670]
**Please describe which feature you have a question about?**
Allow access to AppSync via ec2.
**Provide additional details**
I have a django project deployed on ElasticBeanstalk (couple of EC2 instances)  that updates data in Amplify using an AppSync client with boto3, I'm not able to access AppSync although I have admin authorizations to use every resource and action of any AppSync resource.
**What AWS Services are you utilizing?**
AWS AppSync
**Provide additional details e.g. code snippets**
```
def make_client():
    headers = {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
    }
    # Initiate a BOTO3 session
    session = boto3.session.Session(region_name=settings.CONFIG['region'])
    # Get credentials
    credentials = session.get_credentials().get_frozen_credentials()
    auth = AWS4Auth(
        credentials.access_key,
        credentials.secret_key,
        session.region_name,
        'appsync',
        session_token=credentials.token,
    )
    # Create a GraphQL client
    transport = RequestsHTTPTransport(url=settings.CONFIG['GRAPHQL_ENDPOINT'],
                                      headers=headers,
                                      auth=auth)
    client = Client(transport=transport,
                    fetch_schema_from_transport=True)
    return client

 def test_mutation():
     client = make_client()
     params = {'id': 1235, 'state': 'DONE!'}
     resp = client.execute(gql(update_appsync_obj),
                           variable_values=json.dumps({'input': params}))
     return resp

test_mutation()
```
The error i'm getting:
```
{'path': ['getUser'], 'data': None, 'errorType': 'Unauthorized', 'errorInfo': None, 'locations': [{'line': 2, 'column': 3, 'sourceName': None}], 'message': 'Not Authorized to access getUser on type User'}
```
While using the API KEY I can confirm that I am authorized.
I'm using Amplify Flutter (latest version with transformer V2).
I have this as @auth in my AppSync Schema.
```

type User @model @aws_cognito_user_pools @aws_iam @auth(rules: [{ allow: owner ,ownerField: "phone_number", operations: [create,read,update]}, { allow: public, provider: iam },{ allow: public , provider: apiKey}]){
    id: ID! @primaryKey
    email: String!
    phone_number: String!
```

**Comment by ykethan** [comment]
Hello @parad0x96, On utilizing the following schema and code I was able to use IAM based authorization to perform an AppSync query.

Schema.graphql
```graphql
type User @model @auth(rules: [{ allow: owner ,ownerField: "phone_number", operations: [create,read,update]}, { allow: public, provider: iam },{ allow: public , provider: apiKey}]){
    id: ID! @primaryKey
    email: String!
    phone_number: String!
}

```

Lambda function code.
```py
import requests
import os
import boto3
from requests_aws_sign import AWSV4Sign

session = boto3.session.Session()
    credentials = session.get_credentials()
    region = session.region_name or 'us-east-1'
    appsyncendpoint =  os.environ['API_<APP NAME>_GRAPHQLAPIENDPOINTOUTPUT']
    print('appsyncendpoint: ' + appsyncendpoint)

    query = """query MyQuery {
  listUsers {
    items {
      id
      phone_number
      updatedAt
    }
  }
}
"""
    print('query: ' + query)
    endpoint  = appsyncendpoint
    payload = {'query': query}
    headers = {'Content-Type': 'application/json'}

    auth=AWSV4Sign(credentials, region, 'appsync')

    try:
        response = requests.post(
            endpoint,
            auth=auth,
            json=payload,
            headers=headers
        ).json()
        if 'errors' in response:
            print('Error attempting to query AppSync')
            print(response['errors'])
        else:
            return response
    except Exception as exception:
        print('Error with Query')
        print(exception)

    return None

```
output:
![image](https://user-images.githubusercontent.com/87995712/179851540-5ec0ed45-40af-4d6f-ba74-bd872985f47d.png)

**Comment by sundersc** [comment]
@parad0x96 - In GraphQL v2, auth directive looks for specific IAM role names to match. Considering your usecase, could you try chaning the IAM auth rule to `private` and add the role arn or prefix to the custom-roles.json file?

Docs:
https://docs.amplify.aws/cli/graphql/authorization-rules/#use-iam-authorization-within-the-appsync-console

If you are using Lambda Execution role - https://github.com/aws-amplify/amplify-category-api/issues/100#issuecomment-1129353024
If you are testing through AppSync console - https://github.com/aws-amplify/amplify-category-api/issues/100#issuecomment-1159378850

**Comment by parad0x96** [comment]
> Hello @parad0x96, On utilizing the following schema and code I was able to use IAM based authorization to perform an AppSync query.
> 
> Schema.graphql
> 
> ```graphql
> type User @model @auth(rules: [{ allow: owner ,ownerField: "phone_number", operations: [create,read,update]}, { allow: public, provider: iam },{ allow: public , provider: apiKey}]){
>     id: ID! @primaryKey
>     email: String!
>     phone_number: String!
> }
> ```
> 
> Lambda function code.
> 
> ```python
> import requests
> import os
> import boto3
> from requests_aws_sign import AWSV4Sign
> 
> session = boto3.session.Session()
>     credentials = session.get_credentials()
>     region = session.region_name or 'us-east-1'
>     appsyncendpoint =  os.environ['API_<APP NAME>_GRAPHQLAPIENDPOINTOUTPUT']
>     print('appsyncendpoint: ' + appsyncendpoint)
> 
>     query = """query MyQuery {
>   listUsers {
>     items {
>       id
>       phone_number
>       updatedAt
>     }
>   }
> }
> """
>     print('query: ' + query)
>     endpoint  = appsyncendpoint
>     payload = {'query': query}
>     headers = {'Content-Type': 'application/json'}
> 
>     auth=AWSV4Sign(credentials, region, 'appsync')
> 
>     try:
>         response = requests.post(
>             endpoint,
>             auth=auth,
>             json=payload,
>             headers=headers
>         ).json()
>         if 'errors' in response:
>             print('Error attempting to query AppSync')
>             print(response['errors'])
>         else:
>             return response
>     except Exception as exception:
>         print('Error with Query')
>         print(exception)
> 
>     return None
> ```
> 
> output: ![image](https://user-images.githubusercontent.com/87995712/179851540-5ec0ed45-40af-4d6f-ba74-bd872985f47d.png)

This is because you are using the IAM user who created the amplify project :)

**Comment by parad0x96** [comment]
> > @parad0x96 - In GraphQL v2, auth directive looks for specific IAM role names to match. Considering your usecase, could you try chaning the IAM auth rule to `private` and add the role arn or prefix to the custom-roles.json file?
> > Docs: https://docs.amplify.aws/cli/graphql/authorization-rules/#use-iam-authorization-within-the-appsync-console
> > If you are using Lambda Execution role - [#100 (comment)](https://github.com/aws-amplify/amplify-category-api/issues/100#issuecomment-1129353024) If you are testing through AppSync console - [#100 (comment)](https://github.com/aws-amplify/amplify-category-api/issues/100#issuecomment-1159378850)
> 
> I was able to fix it by explicitly adding the EC2 role name in the `custom-roles.json` files , the ARN didn't work for me .

@sundersc For the lambda should I add the role name of the lambda in `custom-roles.json` file ? because the generated permissions by Amplify didn't grant me access to AppSync API although I can see that I have permissions in the lambda execution role in IAM.

**Comment by parad0x96** [comment]
@sundersc  by adding the lambda execution role name to the `custom-roles.json` I can confirm that it is working properly, but I think the transformer V2 should be tweeked because this a workaround and wouldn't scale with more lambdas and iam users dynamically.

**Comment by ykethan** [comment]
Hello @parad0x96, glad to hear that adding the Lambda function role name in `custom-roles.json` mitigated the issue. Thank you for the suggestion. I will be closing the issue, please do reach out to us again.
