### ISSUE TITLE
@hasOne/@belongsTo with @primaryKey and sort key not working

### ISSUE THREAD

**Issue by Simon-PumpAndUp** [aws-amplify/amplify-category-api#690]
Hello 

I have the following (simplified) schema:

```
type Party @model
@auth(rules: [
  { allow: owner },
]) {
  id: ID
  hashKey: Int! @primaryKey(sortKeyFields: ["rangeKey"])
  rangeKey: String! @index(name: "byRangeKey", queryField: "partyByRangeKey")
}

type ChatRoom @model
@auth(rules: [
  { allow: owner },
]) {
  id: ID!
  party: Party @hasOne
}
```

In my models everything is alright, I have a Party object in ChatRoom. 

In AppSync / dynamodb, the normal behaviour is that the V2 transformer materializes this relationship with the field field: **chatRoomPartyId**. 

As stated in the documentation: 

> A @ hasOne relationship always uses a reference to the primary key of the related model, by default id unless overridden with the [@primaryKey directive](https://docs.amplify.aws/cli/graphql/data-modeling/#configure-a-primary-key).

So here I expect to have chatRoomPartyRangeKey & chatRoomPartyHashKey but have **chatRoomPartyId**.

I tried in my graphql mutation to use both id and hashKey but the relationship is never made. 

Is this a bug or am I wrong defining my schema?

Thanks!

Edit: 
Also, I tried defining the field myself using @hasOne(fields: ["partyHashKey", "partyRangeKey"] after referencing these.
But, whatever I do I get: <partyId || partyRangeKey || partyHashKey>field is not of type Int
Same behaviour with the directive belongsTo.

**Comment by josefaidt** [comment]
Hey @Simon-PumpAndUp :wave: thanks for raising this! As we begin to look at this can you clarify your use case? After each of the records are created, was there an additional mutation executed to create the relationship (i.e. linking `Party` to `Chatroom` by ID or vice-versa)?

**Comment by Simon-PumpAndUp** [comment]
Hi Josef, 

I'm working on a real time chat in flutter where I can have 1o1 and group chats. 

I'm not linking the ChatRoom to the party because when I tried with the ID as PK with a test case it linked both tables with one mutation. So here I expect the party to be linked back while I create a ChatRoom. 

My test case is this: 

```
type ChatRoom @model
@auth(rules: [
  { allow: owner },
]) {
  id: ID!
  messages: [Message] @hasMany
}

type Message @model
@auth(rules: [
  { allow: owner },
]) {
  id: ID!
  chatroomId: ID @index(name: "byChatRoom", queryField: "messagesByChatRoom")
  chatroom: ChatRoom @belongsTo(fields: ["chatroomId"])
}
```

```
mutation CreateMessage($input: CreateMessageInput!) {
  createMessage(input: $input) {
    id
    chatRoomMessagesId
    chatroomId
  }
}
```

And it works: I can see the messages related to a chat room and the chatroom of a message. Also I noticed I have to input twice the ID in order to be able to have an index and the relationship. It feels a bit redundant and I expected **(fields: ["chatroomId"])** to avoid this but with or without same behavior.  

Hope it gives you a better picture, otherwise let me know. 

Cheers

**Comment by Simon-PumpAndUp** [comment]
@josefaidt any update please? This is quite urgent as my deadline is getting closer.

**Comment by josefaidt** [comment]
Hey @Simon-PumpAndUp thank you for that information and to clarify further, the issue you're experiencing is the redundant mutations to link and create the relationship? Unfortunately this is currently the intended behavior albeit a bit redundant as you have noted.

**Comment by Simon-PumpAndUp** [comment]
Hey @josefaidt with this model Party / ChatRoom, the link in ChatRoom is represented with id and rangeKey whereas it should be hashKey and rangeKey. That's it.

**Comment by josefaidt** [comment]
Hey @Simon-PumpAndUp :wave: apologies for the delay here, does the behavior change when you create the `@hasMany` relationship by specifying the `indexName` for the index created in the related model?

```
@hasMany(indexName: "byPost", fields: ["id"])
```
https://docs.amplify.aws/cli/graphql/data-modeling/#belongs-to-relationship

**Comment by Simon-PumpAndUp** [comment]
Hi @josefaidt, no worries I ended up removing all connections since it is far from being usable in a real use case. 

I might have missed this `indexName` property indeed. But I would expect the @hasOne to make the proper link using the primary key defined in the model like: 
`hashKey: Int! @primaryKey(sortKeyFields: ["rangeKey"])`

**Comment by AnilMaktala** [comment]
Hi @Simon-PumpAndUp 👋, are you still experiencing this issue?
