### ISSUE TITLE
Cannot run amplify mock graphql with lambda auth at local

### ISSUE THREAD

**Issue by phuocduy1988** [aws-amplify/amplify-category-api#693]
Dear Developer,
I am happy to use amplify cli service.
However I was quite sad because I cannot run amplify mock graphql with lambda auth at local. I hope to be able to use it someday.

**Comment by josefaidt** [comment]
Hey @phuocduy1988 :wave: thanks for raising this! Would you mind porting this to our [bug template](https://github.com/aws-amplify/amplify-category-api/issues/new?assignees=&labels=&template=1.bug_report.yaml) to gather additional context around the issue you're experiencing?
