### ISSUE TITLE
manyToMany autogenerated table with extra fields

### ISSUE THREAD

**Issue by leonardocfor** [aws-amplify/amplify-category-api#698]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
Unnecessary

```

</details>

### Describe the bug

Hi, 

I attempted as a test trying to add extra fields to the autogenerated table with a manyToMany connection. With previous version of the resolver, it was possible to add any fields as desired to the intermediate table when setting a many to many connection in schema.graphql but I don't see how to do it with the new resolver. I give an example of the current modeling: 

type User @model {
  id: ID!
   username: String!
  name: String!
  lastname: String!
  email: String!
  organizations: [Organization] @manyToMany(relationName: "UserOrganizations")
}

type Organization @model {
  id: ID!
  name: String! 
  users: [User] @manyToMany(relationName: "UserOrganizations")
}

With this approach, the table UserOrganizations will be created, but this table only accepts the fields userID and organizationID. 
I would like to be able to add extra fields to the autogenerated table UserOrganizations, e.g.  the status field, to represent the status an User is within an Organization as shown as follows:

mutation MyMutation {
  createUserOrganizations(input: {
    userID:"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    organizationID: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    status: "Active"
  }) {
    id
  }
}

But I'm receiving the following error of course: 

 "message": "Validation error of type WrongType: argument 'input' with value 'ObjectValue{objectFields=[ObjectField{name='userID', value=StringValue{value='xxxxxxxxxxxxxxxxxxx'}}, ObjectField{name='organizationID', value=StringValue{value='xxxxxxxxxxxxxxxxxxxxxxxx'}}, ObjectField{name='status', value=StringValue{value='Active'}}]}' contains a field not in 'CreateUserOrganizationsInput': 'status' @ 'createUserOrganizations'"

### Expected behavior

I can't find in the documentation how to add extra parameters to the manyToMany relation beyond "relationName", so I would like to ask how could I add for example the mentioned status field to the autogenerated table, if that it is possible via editing somehow the schema.graphql or otherwise if there is a way to set up this use case. 

Thank you so much !!

### Reproduction steps

Unnecessary

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
Hello @leonardocfor, Thank you for reaching out. Could you please provide us information into your use case to better understand this.

**Comment by leonardocfor** [comment]
Hi @ykethan thanks for your reply. I want to create a web app in which users can create or belong to multiple organizations. The user will have an status in each organization among other fields which are part of the relationship between the users and the organizations, therefore those fields should not be part of the User or Organization tables but rather of the UserOrganization table. The following snippet is how I would handle it with the previous  GraphQL Transformer:  

```
type User @model {
  id: ID!
  username: String!
  name: String!
  lastname: String!
  email: String!
  organizations: [UserOrganization] @connection(keyName: "byUser", fields: ["id"])
}

type Organization @model {
  id: ID!
  name: String!
  users: [UserOrganization] @connection(keyName: "byOrganization", fields: ["id"])
}

type UserOrganization {
  @key(name: "byUser", fields: ["userID", "organizationID"])
  @key(name: "byOrganization", fields: ["organizationID", "userID"]) {
  id: ID!
  userID: ID!
  organizationID: ID!
  user: User @connection(fields: ["userID"])
  organization: Organization @connection(fields: ["organizationID"])
  status: String
}
```

Now. with the GraphQL Transformer V2, this is how far I can get

```
type User @model {
  id: ID!
  username: String!
  name: String!
  lastname: String!
  email: String!
  organizations: [Organization] @manytomany(relationName: "UserOrganizations")
}

type Organization @model {
  id: ID!
  name: String!
  users: [User] @manytomany(relationName: "UserOrganizations")
}
```

Which will autogenerate the table UserOrganizations, but as you see I can not add fields like status as I could do with the previous version of the resolver

**Comment by leonardocfor** [comment]
Hi @ykethan, I was wondering if you saw my previous response.

**Comment by AaronZyLee** [comment]
The `@manyToMany` does not support adding the customized fields for now. But it can be still achieved by using v2 relational directives (`@hasMany` and `@belongsTo`) as following:
```GraphQL
type User @model {
  id: ID!
  username: String!
  name: String!
  lastname: String!
  email: String!
  organizations: [UserOrganization] @hasMany(indexName: "byUser", fields: ["id"])
}

type Organization @model {
  id: ID!
  name: String!
  users: [UserOrganization] @hasMany(indexName: "byOrganization", fields: ["id"])
}

type UserOrganization {
{
  id: ID!
  userID: ID! @index(sortKeyFields:["organizationID"])
  organizationID: ID! @index(sortKeyFields:["userID"])
  user: User @belongsTo(fields: ["userID"])
  organization: Organization @belongsTo(fields: ["organizationID"])
  status: String
}
```

**Comment by leonardocfor** [comment]
Nice, very similar as it was done with version 1. I appreciate it man !! @AaronZyLee

**Comment by sabreena-kp** [comment]
@AaronZyLee I tried the same schema design, but the query not returning User or Organization details in the 'user' and 'organization' keys respectively for the type UserOrganization
@belongsTo is not working .

type UserOrganization @model{
{
  id: ID!
  userID: ID! @index(sortKeyFields:["organizationID"])
  organizationID: ID! @index(sortKeyFields:["userID"])
  user: User @belongsTo(fields: ["userID"])
  organization: Organization @belongsTo(fields: ["organizationID"])
  status: String
}

user and organization values are null here.

**Comment by juri-diener** [comment]
> @leonardocfor The `@manyToMany` does not support adding the customized fields for now. But it can be still achieved by using v2 relational directives (`@hasMany` and `@belongsTo`) as following, which is equivalent to `@manyToMany`:
> 
> ```graphql
> type User @model {
>   id: ID!
>   username: String!
>   name: String!
>   lastname: String!
>   email: String!
>   organizations: [UserOrganization] @hasMany(indexName: "byUser", fields: ["id"])
> }
> 
> type Organization @model {
>   id: ID!
>   name: String!
>   users: [UserOrganization] @hasMany(indexName: "byOrganization", fields: ["id"])
> }
> 
> type UserOrganization @model{
> {
>   id: ID!
>   userID: ID! @index(sortKeyFields:["organizationID"])
>   organizationID: ID! @index(sortKeyFields:["userID"])
>   user: User @belongsTo(fields: ["userID"])
>   organization: Organization @belongsTo(fields: ["organizationID"])
>   status: String
> }
> ```

Can someone help Mei want the same to achieve but get an error: Index byUser does not exist for model UserOrg

type User @model @auth(rules: [{ allow: private }]) {
  id: ID!
  name: String
  email: String
  bio: String
  profileImg: String
  orgs: [UserOrg] @hasMany(indexName: "byUser", fields: ["id"])
  groups: [Group] @manyToMany(relationName: "GroupUser")
}

type Org
  @model
  @auth(
    rules: [
      { allow: private, operations: [read] }
      { allow: groups, groups: ["Admins"] }
    ]
  ) {
  id: ID! @primaryKey(sortKeyFields: ["userID"])
  name: String!
  street: String!
  zip: String!
  city: String!
  phoneNumber: String
  userID: ID!
  state: String!
  description: String
  long: String
  lat: String
  groups: [Group] @hasMany(indexName: "byOrg", fields: ["id"])
  users: [UserOrg] @hasMany(indexName: "byOrgU", fields: ["id"])
}

type UserOrg @model @auth(rules: [{ allow: private }]) {
  id: ID!
  userID: ID! @index(sortKeyFields: ["orgID"])
  orgID: ID! @index(sortKeyFields: ["userID"])
  user: User @belongsTo(fields: ["userID"])
  org: Org @belongsTo(fields: ["orgID"])
  role: String
}

**Comment by rickyadriell** [comment]
> @leonardocfor The `@manyToMany` does not support adding the customized fields for now. But it can be still achieved by using v2 relational directives (`@hasMany` and `@belongsTo`) as following, which is equivalent to `@manyToMany`:
> 
> ```graphql
> type User @model {
>   id: ID!
>   username: String!
>   name: String!
>   lastname: String!
>   email: String!
>   organizations: [UserOrganization] @hasMany(indexName: "byUser", fields: ["id"])
> }
> 
> type Organization @model {
>   id: ID!
>   name: String!
>   users: [UserOrganization] @hasMany(indexName: "byOrganization", fields: ["id"])
> }
> 
> type UserOrganization @model{
> {
>   id: ID!
>   userID: ID! @index(sortKeyFields:["organizationID"])
>   organizationID: ID! @index(sortKeyFields:["userID"])
>   user: User @belongsTo(fields: ["userID"])
>   organization: Organization @belongsTo(fields: ["organizationID"])
>   status: String
> }
> ```

Is the adding fields supported now?
