### ISSUE TITLE
amplify api add-graphql-datasource creates resolvers with incorrect tablename capitalization

### ISSUE THREAD

**Issue by riacoding** [aws-amplify/amplify-category-api#70]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

17.2.0

### Amplify CLI Version

7.6.13

### What operating system are you using?

Mac 10.15.7

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No Manual Changes

### Amplify Categories

api

### Amplify Commands

add

### Describe the bug

After using the **amplify api add-graphql-datasource** command and selecting the Aurora serverless database. The generated resolvers on **amplify push** have incorrectly capitalized the RDS table name. The lower case table names have had the first letter capitalized in the resolver template. Querying from Appsync console is broken.

Given table in database 'customers' the resolver template Query.listCustomerss.req.vtl is created with -

```
{
  "version": "2018-05-29",
  "statements":   ["SELECT * FROM Customers"]
}
```

### Expected behavior

I would expect that the resolvers would use the capitalization of the database table names. 

### Reproduction steps

Follow steps in relational tutorial changing table names to lowercase

[https://docs.amplify.aws/cli-legacy/graphql-transformer/relational/](https://docs.amplify.aws/cli-legacy/graphql-transformer/relational/)

**amplify init**
**amplify add api** 
-blank schema

create RDS Aurora serverless Database with following table names:

```
USE MarketPlace;
CREATE TABLE customers (
  id int(11) NOT NULL PRIMARY KEY,
  name varchar(50) NOT NULL,
  phone varchar(50) NOT NULL,
  email varchar(50) NOT NULL
);
CREATE TABLE orders (
  id int(11) NOT NULL PRIMARY KEY,
  customerId int(11) NOT NULL,
  orderDate datetime DEFAULT CURRENT_TIMESTAMP,
  KEY `customerId` (`customerId`),
  CONSTRAINT `customer_orders_ibfk_1` FOREIGN KEY (`customerId`) REFERENCES `Customers` (`id`)
);
```

**amplify api add-graphql-datasource**
 -select previously created Aurora DB instance
**amplify push**
**amplify api console**
Unable to query and query returns Null
Changing table names to have first letter capitalized allows the Appsync console to work as expected.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by nsdhillon1** [comment]
Hi, any update on this issue?

**Comment by renebrandel** [comment]
Hi @riacoding / @nsdhillon1 - Thanks for raising this. Unfortunately, we don't have any immediate updates on the GraphQL Transformer v1 at this point. We are looking to address this via this RFC to better support relational data sources in the future with GraphQL Transformer v2. 

I would love to get your thoughts and feedback on that: https://github.com/aws-amplify/amplify-category-api/issues/815

**Comment by chrisbonifacio** [comment]
Closing this issue as the current feature support for SQL databases does not seem to have this issue. You can now map a `@model` to the correct table name using the `@refersTo` directive like so:

```graphql
type Post @model @refersTo(name: "posts") {
  id: String! @primaryKey
  title: String!
  content: String!
}
```

Please refer to our documentation on connecting an Amplify GraphQL API to existing SQL databases:

https://docs.amplify.aws/javascript/build-a-backend/graphqlapi/connect-api-to-existing-database/
