### ISSUE TITLE
Amplify Studio deployment fails after changing table name

### ISSUE THREAD

**Issue by chstrong** [aws-amplify/amplify-category-api#705]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1mptt8hqo6wak

### Region

us-east-1

### Environment name

staging

### Amplify CLI Version

9.1.0

### If applicable, what version of Node.js are you using?

v16.13.1

### What operating system are you using?

macOs Monterey Version 12.4 (M1 Chip)

### Browser type?

Chrome

### Describe the bug

In Amplify Studio I have created a new data model called "Posts" and deployed it.

I then however wanted to call it "Post" (singular). So I've changed the name in the field and deployed.

This resulted in the following error, during the deployment:

```
Embedded stack arn:aws:cloudformation:us-east-1:187343962510:stack/amplify-99thcloudblog-staging-55625-api99thcloudblog-BIPHMIMW8108/b97015f0-0595-11ed-8297-0a796557b527 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to create: [Post].
```

And:

```
Embedded stack arn:aws:cloudformation:us-east-1:187343962510:stack/amplify-99thcloudblog-staging-55625-api99thcloudblog-BIPHMIMW8108-Post-XGR3DX4RZNK/ae5bc430-0832-11ed-b386-120acb2ea075 was not successfully created: The following resource(s) failed to create: [ListPostResolver, SyncPostResolver].
```

![Screenshot 2022-07-20 at 10 24 57 PM](https://user-images.githubusercontent.com/6489758/180007567-2bb50eae-7dac-442c-b479-19099ac71283.png)

### Expected behavior

Update of Amplify services works over the web console, and also over the CLI, without having to delete the whole environment (which leaves clutter as not all services that were created get deleted and there is no reference).

### Reproduction steps

1. Create a new Amplify App
2. Open Amplify Studio
3. Create a table called "Posts" with fields "ID, title, content"
4. Deploy the table
5. Change the name of "Posts" to "Post"
6. Deploy again (now you'll get the error)

**Comment by chstrong** [comment]
Hi @adilahkb,

Thanks, much appreciated. Sorry if I've raised it in the wrong Github Repo. If you or one of your colleagues have time could you also look at the ones that I've raised in amplify hosting?

https://github.com/aws-amplify/amplify-hosting/

#2890, #2876 

Thanks a lot.

**Comment by josefaidt** [comment]
Hey @chstrong :wave: apologies for the delay here! Are you still experiencing this?

**Comment by chstrong** [comment]
Hi @josefaidt I don't know. I stopped using Amplify.
