### ISSUE TITLE
@auth for transformer v2 connections (@hasMany/@belongsTo)

### ISSUE THREAD

**Issue by iyz91** [aws-amplify/amplify-category-api#72]
**Which Category is your question related to?**
api

**Amplify CLI Version**
7.6.26

**What AWS Services are you utilizing?**
AppSync, DynamoDB

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
Consider three basic models below

```graphql
type User @model @auth(rules: [{allow: owner, ownerField: "id", operations: [read]}]) {
  id: ID!
  email: AWSEmail!
  someEditableProperty: @auth(rules: [{allow: owner, ownerField: "id", operations: [read, update]}])
  somethings: [UserSomethingJoin!] @hasMany(indexName: "byUser", fields: ["id"])
}

type UserSomethingJoin @model(queries: null) {
  id: ID!
  userId: ID! @index(name: "byUser", sortKeyFields: ["programId"])
  user: User! @belongsTo(fields: ["userId"])
  somethingId: ID! @index(name: "bySomething", sortKeyfields: ["userId"])
  something: Something! @belongsTo(fields: ["somethingId"])
}

type Something @model {
  id: ID!
  users: [UserSomethingJoin!] @hasMany(indexName: "byProgram", fields: ["id"])
}
```

The goal here is to have the user be able to only read their own records with one editable property they can edit, while having the record only accessible otherwise through the `UserSomethingJoin`. However, the schema seems to not authorize the connection, e.g. via `Something.users` called by a different user. One option would be to set `allow: private`, but this invalidates the requirements of having only the user be able to query their `User` item. What is the proper way to achieve these requirements using transformer v2? In transformer v1, this worked no problem for connections.

**Comment by josefaidt** [comment]
Hey @iyz91 :wave: apologies for the delay here!! Are you still experiencing this? Have you tried specifying an explicit join table with customized auth rules for your use case?

**Comment by josefaidt** [comment]
Hey @iyz91 :wave: are you still experiencing this?

**Comment by AnilMaktala** [comment]
Hi @iyz91  👋, Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
