### ISSUE TITLE
@auth rules not working

### ISSUE THREAD

**Issue by LeoReubelt** [aws-amplify/amplify-category-api#726]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.2

### Amplify CLI Version

9.2.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I changed the mapping templates for two mutations, a query, and a subscription in the console. The subscription is the same subscription that i am trying to add the custom resolver to. I also added a lambda resolver for a query. The Function was created in the cli. But it was set as the resolver in the console. The function was also modified in the console. None of these are on any of the types that are the subject of this issue.

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

When I create a type and add auth rules. The auth rules do not work. I have put an example type below but the auth rules don't work on any of the types that i have pushed recently. Auth rules on older types work. When I examine the mapping templates for the newer types, whose auth rules don't work, there is no static group authorization. And in the example below, users were able to perform all operations regardless of their group.

```
type UserChannelPermission
    @model
    @key(fields: ["userId"])
    @auth(
        rules: [
            { allow: groups, groups: ["externalUser"], operations: [read] }
            { allow: groups, groups: ["agent"], operations: [read] }
            { allow: groups, groups: ["engineer"], operations: [read] }
            { allow: groups, groups: ["superAdmin"], operations: [read] }
        ]
    ) {
    userId: ID!
    channelIds: [String!]!
}
```

This is the same project as another issue that I entered. I don't think they are related. But  just fyi...
https://github.com/aws-amplify/amplify-category-api/issues/725

### Expected behavior

@auth rules restrict or allow access based on group.

### Reproduction steps

I don't really know what to put here. The auth rules do not work on any type that I push. 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type UserChannelPermission
    @model
    @key(fields: ["userId"])
    @auth(
        rules: [
            { allow: groups, groups: ["externalUser"], operations: [read] }
            { allow: groups, groups: ["agent"], operations: [read] }
            { allow: groups, groups: ["engineer"], operations: [read] }
            { allow: groups, groups: ["superAdmin"], operations: [read] }
        ]
    ) {
    userId: ID!
    channelIds: [String!]!
}

```

</details>

### Project Identifier

I tried this. The project Identifier was not printed.

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @LeoReubelt :wave: thanks for raising this! From your schema I see you are using version 1 of our GraphQL Transformer (from `@key`). Version 2 of our transformer provides many enhancements to the existing at-auth directive, at-index, at-primaryKey, and also includes a few new relational directives such as hasMany or hasOne. We recommend migrating in order to leverage the enhancements, however will support v1 for security issues. Would you mind posting the auth resolver for this model? 

> I have put an example type below but the auth rules don't work on any of the types that i have pushed recently. Auth rules on older types work.

Can you provide more details around this note? When you say older types do you mean models you have pushed in the past vs models you've recently created?

**Comment by LeoReubelt** [comment]
Thanks @josefaidt. Upgrading our resolver is high on my list. The last project i did uses the v2 resolver. We just have to fit it in our timeline. Yes, what I meant is that objects pushed in the past have worked. All of those objects were initially pushed to another environment. And we cloned the environment that they were pushed to, making the environment that i am working on.

These are the resolver mappings for that one of the objects that doesn't work. Is that what you  want?

```
## [Start] Set default values. **
#set( $createdAt = $util.time.nowISO8601() )
## Automatically set the createdAt timestamp. **
$util.qr($context.args.input.put("createdAt", $util.defaultIfNull($ctx.args.input.createdAt, $createdAt)))
## Automatically set the updatedAt timestamp. **
$util.qr($context.args.input.put("updatedAt", $util.defaultIfNull($ctx.args.input.updatedAt, $createdAt)))
## [End] Set default values. **
## [Start] Set the primary @key. **
#set( $modelObjectKey = {
  "userId": $util.dynamodb.toDynamoDB($ctx.args.input.userId)
} )
## [End] Set the primary @key. **

## [Start] Prepare DynamoDB PutItem Request. **
$util.qr($context.args.input.put("__typename", "UserChannelPermission"))
#if( $modelObjectKey )
  #set( $condition = {
  "expression": "",
  "expressionNames": {},
  "expressionValues": {}
} )
  #foreach( $entry in $modelObjectKey.entrySet() )
    #if( $velocityCount == 1 )
      $util.qr($condition.put("expression", "attribute_not_exists(#keyCondition$velocityCount)"))
    #else
      $util.qr($condition.put("expression", "$condition.expression AND attribute_not_exists(#keyCondition$velocityCount)"))
    #end
    $util.qr($condition.expressionNames.put("#keyCondition$velocityCount", "$entry.key"))
  #end
#else
  #set( $condition = {
  "expression": "attribute_not_exists(#id)",
  "expressionNames": {
      "#id": "id"
  },
  "expressionValues": {}
} )
#end
#if( $context.args.condition )
  #set( $condition.expressionValues = {} )
  #set( $conditionFilterExpressions = $util.parseJson($util.transform.toDynamoDBConditionExpression($context.args.condition)) )
  $util.qr($condition.put("expression", "($condition.expression) AND $conditionFilterExpressions.expression"))
  $util.qr($condition.expressionNames.putAll($conditionFilterExpressions.expressionNames))
  $util.qr($condition.expressionValues.putAll($conditionFilterExpressions.expressionValues))
#end
#if( $condition.expressionValues && $condition.expressionValues.size() == 0 )
  #set( $condition = {
  "expression": $condition.expression,
  "expressionNames": $condition.expressionNames
} )
#end
{
  "version": "2018-05-29",
  "operation": "PutItem",
  "key": #if( $modelObjectKey ) $util.toJson($modelObjectKey) #else {
  "id":   $util.dynamodb.toDynamoDBJson($ctx.args.input.id)
} #end,
  "attributeValues": $util.dynamodb.toMapValuesJson($context.args.input),
  "condition": $util.toJson($condition)
}
## [End] Prepare DynamoDB PutItem Request. **
```

```
#if( $ctx.error )
$util.error($ctx.error.message, $ctx.error.type, $ctx.result)
#else
$util.toJson($ctx.result)
#end
```

**Comment by josefaidt** [comment]
Hey @LeoReubelt is this a customized resolver? Running through the reproduction steps here it does appear the groups appear as static values in the associated resolver. I'm also not seeing auth logic in the resolver posted above.

```
## [Start] Static Group Authorization Checks **
#set($isStaticGroupAuthorized = $util.defaultIfNull(
          $isStaticGroupAuthorized, false))
## Authorization rule: { allow: groups, groups: ["users"], groupClaim: "cognito:groups" } **
#set( $userGroups = $util.defaultIfNull($ctx.identity.claims.get("cognito:groups"), []) )
#set( $allowedGroups = ["users"] )
#foreach( $userGroup in $userGroups )
  #if( $allowedGroups.contains($userGroup) )
    #set( $isStaticGroupAuthorized = true )
    #break
  #end
#end
## Authorization rule: { allow: groups, groups: ["admins"], groupClaim: "cognito:groups" } **
#set( $userGroups = $util.defaultIfNull($ctx.identity.claims.get("cognito:groups"), []) )
#set( $allowedGroups = ["admins"] )
#foreach( $userGroup in $userGroups )
  #if( $allowedGroups.contains($userGroup) )
    #set( $isStaticGroupAuthorized = true )
    #break
  #end
#end
```

**Comment by LeoReubelt** [comment]
@josefaidt it is not custom. i get why it seems like it is though. i have pushed a ton of new types and never had a problem before. but everything i have pushed on the new environment has a resolver just like this one. as a sanity check, i pushed two new types last night. they both have the same resolver. at lest for create.

**Comment by LeoReubelt** [comment]
@josefaidt I cloned a new environment. It has the same parent as the environment the environment that is the subject of this issue. The @auth rules are working on the parent. But not either of the children. So maybe it has something to do with the new schema types that i am trying to push.

```
type UserChannelPermission
    @model
    @key(fields: ["userId"])
    @auth(
        rules: [
            { allow: groups, groups: ["externalUser"], operations: [read] }
            { allow: groups, groups: ["agent"], operations: [read] }
            { allow: groups, groups: ["engineer"], operations: [read] }
            { allow: groups, groups: ["superAdmin"], operations: [read] }
        ]
    ) {
    userId: ID!
    channelIds: [String!]!
}

type Channel
    @model
    @key(name: "byStateWorkflow", fields: ["stateWorkflowId", "channelName"])
    @auth(
        rules: [
            { allow: groups, groups: ["externalUser"], operations: [read] }
            { allow: groups, groups: ["agent"], operations: [read] }
            { allow: groups, groups: ["engineer"], operations: [read] }
            { allow: groups, groups: ["superAdmin"], operations: [read] }
        ]
    ) {
    id: ID!
    channelName: String
    channelUsers: [ChannelUserConnection!] @connection(keyName: "byChannel", fields: ["id"])
    stateWorkflowId: ID
    isDefaultChannel: Boolean
}

type Message
    @model
    @key(
        name: "byDateDummy"
        fields: ["dummyFieldUsedForSort", "createdAt"]
        queryField: "getMessagesByDateDummy"
    )
    @auth(
        rules: [
            { allow: groups, groups: ["externalUser"], operations: [] }
            { allow: groups, groups: ["agent"], operations: [] }
            { allow: groups, groups: ["engineer"], operations: [] }
            { allow: groups, groups: ["superAdmin"], operations: [] }
        ]
    ) {
    id: ID!
    channelId: ID!
    senderId: ID!
    channel: Channel @connection(fields: ["channelId"])
    sender: User @connection(fields: ["senderId"])
    createdAt: AWSDateTime!
    text: String
    fileKey: String
    hasBeenReadByIds: [ID!]
    dummyFieldUsedForSort: String
}

type ChannelUserConnection
    @model
    @key(name: "byChannel", fields: ["channelId", "userId"])
    @key(name: "byMember", fields: ["channelId", "userId"])
    @auth(
        rules: [
            { allow: groups, groups: ["externalUser"], operations: [read] }
            { allow: groups, groups: ["agent"], operations: [read] }
            { allow: groups, groups: ["engineer"], operations: [read] }
            { allow: groups, groups: ["superAdmin"], operations: [read] }
        ]
    ) {
    id: ID!
    channelId: ID!
    userId: ID!
    channel: Channel! @connection(fields: ["channelId"])
    user: User! @connection(fields: ["userId"])
}

type PaginatedMessages {
    messages: [Message!]!
    nextToken: String
}
```

**Comment by LeoReubelt** [comment]
One of my co-workers was able to push a test object. His @auth rules worked fine.

**Comment by LeoReubelt** [comment]
@josefaidt if i add an auth rule with no users in it, it works.  Not sure that is a good way to do it. But for now, I guess it will do.

type UserChannelPermission
    @model
    @key(fields: ["userId"])
    @auth(
        rules: [
            { allow: groups, groups: ["externalUser"], operations: [read] }
            { allow: groups, groups: ["agent"], operations: [read] }
            { allow: groups, groups: ["engineer"], operations: [read] }
            { allow: groups, groups: ["superAdmin"], operations: [read] }
            { allow: groups, groups: ["theAntiGroup"], operations: [create, update, delete] }
        ]
    ) {
    userId: ID!
    channelIds: [String!]!
}
