### ISSUE TITLE
Security message comes up when running Amplify Push, adding space to schema.graphql

### ISSUE THREAD

**Issue by Jesmaster** [aws-amplify/amplify-category-api#729]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

9.2.1

### What operating system are you using?

Ubunutu Mate

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made.

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

Every time I run `amplify push` on my machine it pops up the following question right away:

`This version of Amplify CLI introduces additional security enhancements for your GraphQL API. The changes are applied automatically with this deployment. This change won't impact your client code. Continue? (Y/n)`

If I answer no then the command ends immediately.

If I answer yes then it modifies my schema.graphql file in `amplify/backend/api/[project-name]` by adding an extra space to the last line in the file. This causes `amplify push` to always think there is a change even though there aren't any.

### Expected behavior

`amplify push` should not be asking the security question every time I run it and it should not be modifing my schema.grapql file.

### Reproduction steps

- Run amplify push
- Security message comes up
- Answer yes to it
- Check `amplify/backend/api/[project-name]/schema.graphql`

### GraphQL schema(s)

```
# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules

#input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

# Naming rules follows:
# https://graphql-rules.com/rules/naming

# AppSync Scalar Type def:
# https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html

# Misc
# Subscription type not available - https://github.com/aws-amplify/amplify-cli/issues/5554

# ** For visible, add all users to group members, and add member to groups attribute when we want to make visible


type Score @model @auth(rules:[
    {allow: owner, operations: [read, create, update, delete]},
    {allow: groups, groups: ["Admin"], operations: [read, create, update, delete]},
    {allow: groups, groupsField: "groups", operations: [read]}
  ]) {
  id: ID!  
  groups: [String]
  name: String!
  profile: Profile! @belongsTo
  derivesFromId: ID @index(name: "byDerivesFromId", queryField: "scoreByDerivesFromId")
  scoreData: AWSJSON
  publicScore: PublicScore @hasOne
  groupScore: GroupScore @hasOne  
  editable: Boolean!
  visible: Boolean!
  shareable: Boolean!
  community: Boolean
  completed: Boolean
  groupVisible: Boolean @default(value: "false")
  #profileId: ID @index(name: "byProfile", queryField: "scoreByProfileId")
}


type PublicScore @model @auth(rules:[
    {allow: public, provider: iam, operations: [read]},
    {allow: owner,  operations: [read, create, update, delete]},
    {allow: groups, groups: ["Admin"], operations: [read, create, update, delete]},
    {allow: groups, groupsField: "groups", operations: [read]}
  ]) {
  id: ID!
  groups: [String]
  name: String!
  derivesFromId: ID @index(name: "byDerivesFromId", queryField: "publicScoreByDerivesFromId")
  score: Score @belongsTo
  scoreId: ID! @index(name: "publicScoreByScoreId", queryField: "listPublicScoresByScoreId")
  scoreData: AWSJSON
  editable: Boolean! 
  visible: Boolean!
}

type CommunityScore @model @searchable @auth(rules:[
    {allow: private, provider: iam, operations: [read]},
    {allow: owner,  operations: [read, create, update, delete]},
    {allow: groups, groups: ["Admin"], operations: [read, create, update, delete]}
  ]) {
  id: ID!
  groups: [String]
  name: String!
  scoreId: ID!
  profileId: ID!
  profileName: String!
  scoreData: AWSJSON
  editable: Boolean!
  visible: Boolean!
  featured: Boolean!
  sortProfileName: String
  sortName: String
  sortTimestamp: AWSTimestamp
}

type GroupScore @model @searchable @auth(rules:[
    {allow: owner,  operations: [read, create, update, delete]},
    {allow: groups, groups: ["Admin"], operations: [read, create, update, delete]}
    {allow: groups, groupsField: "groups", operations: [read]},
    {allow: private, provider: iam, operations: [read, update]}
  ]) {
  id: ID!
  groups: [String]
  name: String!
  derivesFromId: ID @index(name: "byDerivesFromId", queryField: "groupScoreByDerivesFromId")
  score: Score @belongsTo
  scoreId: ID!
  profileId: ID
  profileName: String
  scoreData: AWSJSON
  editable: Boolean!
  visible: Boolean!
  featured: Boolean!
  completed: Boolean @default(value: "false")
  groupVisible: Boolean @default(value: "false")
  class: Class @belongsTo
  archived: Boolean @default(value: "false")
}

type Profile @model @auth(rules:[
    {allow: owner, operations: [read, create, update, delete]},
    {allow: private, operations: [read, update], provider: iam},
    {allow: groups, groups: ["Admin"], operations: [read, create, update, delete]}
  ]) {
  id: ID!  
  groups: [String] # e.g. class101_admin (teacher group)
  name: String! @index(name: "profileByName", queryField: "listProfilesByName")
  capabilities: AWSJSON
  isDefault: Boolean
  archived: Boolean @default(value: "false")
  class: Class @belongsTo
  account: Account @belongsTo
  user: User @belongsTo
  scores: [Score] @hasMany
  owner: ID
}

type Class @model @searchable @auth(rules:[
    {allow: owner, operations: [read, create, update, delete]},
    {allow: private, operations: [read, update], provider: iam},
    {allow: groups, groups: ["Admin"], operations: [read, create, update, delete]},
    {allow: groups, groupsField: "groups", operations: [read]}
  ]) {
  id: ID!  
  groups: [String] # e.g. class101_admin (teacher group)
  name: String!
  account: Account @belongsTo
  profiles: [Profile] @hasMany
  groupScores: [GroupScore] @hasMany
  studentInvitations: [StudentInvitation] @hasMany
  archived: Boolean
  organization: Organization @belongsTo
  owner: ID
}

type EducatorInvitation @model @searchable @auth(rules:[
    {allow: owner, operations: [read, create, update, delete]},
    {allow: public, provider: iam, operations: [read]},
    {allow: private, operations: [read, update], provider: iam},
    {allow: groups, groups: ["Admin"], operations: [read, create, update, delete]},
    {allow: groups, groupsField: "groups", operations: [read]}
]) {
  id: ID!
  groups: [String]
  firstName: String!
  lastName: String!
  email: String!
  accepted: Boolean!
  organization: Organization! @belongsTo
  educatorUserId: String
  lastResend: AWSTimestamp
}

type StudentInvitation @model @searchable @auth(rules:[
    {allow: owner, operations: [read, create, update, delete]},
    {allow: public, provider: iam, operations: [read]},
    {allow: private, operations: [read, update, delete], provider: iam},
    {allow: groups, groups: ["Admin"], operations: [read, create, update, delete]},
    {allow: groups, groupsField: "groups", operations: [read]}
]) {
  id: ID!
  groups: [String]
  firstName: String!
  lastName: String!
  email: String!
  class: Class! @belongsTo
  accepted: Boolean!
  studentUserId: String
  lastResend: AWSTimestamp
  owner: ID
}

type User @model @auth(rules:[
    {allow: owner, operations: [read, create, update, delete]},
    {allow: groups, groups: ["Admin"], operations: [read, create, update, delete]}
  ]) {
  id: ID!
  email: String # email address
  groups: [String] # e.g. class101_admin (teacher group)
  name: String
  profiles: [Profile] @hasMany
  account: Account! @belongsTo
  #userprofiles: [Profile] @hasMany(indexName: "byUser", fields: ["id"])  
}

enum AccountType {
  INDIVIDUAL,
  STUDENT,
  EDUCATOR,
  EDUCATOR_ADMIN,
  EVENT,
  SUPPORT,
  ADMIN
}

type Account @model @auth(rules:[
    {allow: owner, operations: [read, create, update, delete]},
    {allow: private, operations: [read, update], provider: iam},
    {allow: groups, groups: ["Admin"], operations: [read, create, update, delete]},
    {allow: groups, groupsField: "groups", operations: [read, create, update, delete]}
  ]) {
  id: ID!  
  groups: [String] # e.g. class101_admin (teacher group)
  accountType: AccountType!
  master: Account @hasOne
  user: User @hasOne
  profiles: [Profile] @hasMany
  classes: [Class] @hasMany
  plan: [Plan] @hasMany
  owner: ID
}

type Organization @model @auth(rules:[
    {allow: owner, operations: [read, create, update, delete]},
    {allow: groups, groups: ["Admin"], operations: [read, create, update, delete]},
    {allow: groups, groupsField: "groups", operations: [read]},
    {allow: public, operations: [read], provider: iam},
    {allow: private, operations: [read, update], provider: iam}
  ]) {
  id: ID!
  groups: [String]
  capabilities: AWSJSON!
  email: String!
  name: String!
  seatLimit: Int!
  educatorInvitations: [EducatorInvitation] @hasMany
  classes: [Class] @hasMany
  accepted: Boolean @default(value: "false")
}

type Transaction @model @auth(rules:[
    {allow: owner, operations: [read, create, update, delete]},
    {allow: groups, groups: ["Admin"], operations: [read, create, update, delete]}
  ]) {
  id: ID!
  groups: [String]
  plan: Plan @belongsTo
  stripeSessionId: String
  stripeCustomerId: String
  stripeSubscriptionId: String @index(name: "transactionByStripeSubscriptionId", queryField: "listTransactionsByStripeSubscriptionId")
}
  
type Plan @model @auth(rules:[
    {allow: owner, operations: [read, create, update, delete]},
    {allow: groups, groups: ["Admin"], operations: [read, create, update, delete]}
  ]) {
  id: ID!  
  groups: [String]
  transaction: Transaction @hasOne
  account: Account! @belongsTo
  offering: Offering! @belongsTo
  startDate: AWSDate!
  endDate: AWSTimestamp
  active: Boolean!
  owner: ID
}


# plans[] should be safe since plan doesn't allow private/public access
type Offering @model @auth(rules:[
    {allow: public, provider: iam, operations: [read]},
    {allow: private, operations: [read]},
    {allow: groups, groups: ["Admin"], operations: [read, create, update, delete]}
  ]) {
  id: ID!  
  groups: [String]
  name: String!
  description: String
  plans: [Plan] @hasMany
  durationDays: Int
  price: String
  isDefault: Boolean
  enabled: Boolean!
  visible: Boolean!
  contentUrl: AWSURL
  iframeContentUrl: AWSURL
  capabilities: AWSJSON
  retiredDate: AWSDate
  scoreLimit: Int
  seatLimit: Int
  schoolLimit: Int
  stripePriceId: String
}

type Content @model @auth(rules:[
    {allow: public, provider: iam, operations: [read]},
    {allow: private, operations: [read]},
    {allow: owner, operations: [read, create, update, delete]},
    {allow: groups, groups: ["Admin"], operations: [read, create, update, delete]}
  ]) {
  id: ID!  
  groups: [String]
  key: String!
  value: String  
  description: String
}

```

### Project Identifier

ac895a5559739afefbcfcfd55884c9e4

**Comment by OLTApp** [comment]
After upgrading CLI due to 9.2.1, I was trying to create a new stack in a new region (may not be relevant) and I had issues with amplify push error out during "Uploading files ...." stage.

As a work around.....

I just manually removed the entry "securityEnhancementNotification": false," and ran amplify push. The command added the same line back at the end of the "features.graphqltransformer" section inside cli.json instead of the middle of the section then it started working... meaning creating stacks for my new env successfully.

Not sure positing of the new feature option inside cli.json was a problem.... if I make any sense...

**Comment by alharris-at** [comment]
Hi @OLTApp - I don't believe your issue is related here. The `uploading files` step should be divorced from the process @Jesmaster is talking about.

@Jesmaster - the additional space added to your schema is intended to trigger a push of your API, as you have described. Once you have pushed to the backend the notification will cease.

**Comment by Jesmaster** [comment]
@alharris-at the problem I'm having is I am continuing to recieve the notification every time I push it is continuing to add an extra space at the end every time. I've already done several successful pushes after confirming the security message and it is still continuing to ask me and add the extra space causing the push command to think I've modified the schema file when I haven't.

**Comment by GuillermoRivero** [comment]
Im having exact the same problem of @Jesmaster Amplify thinks there are scheme changes after each build and force me to accept the message: "This version of Amplify CLI introduces additional security enhancements for your GraphQL API. The changes are applied automatically with this deployment. This change won't impact your client code. Continue?" It have been more than 20 builds and the message already appears. Someone knows how to solve this?

**Comment by jeffstahlin** [comment]
any updates on this? I've been experiencing this for the last month, possibly a bit more, despite upgrading the CLI every time an update was released. I'm currently on the latest version at the time of writing,  10.4.0. It's really slowing down progress when working on back-end code (lambda's mainly).

**Comment by belfortf** [comment]
I'm also having this problem. Any workaround ?

**Comment by csmcallister** [comment]
I, too, am receiving this message on every single `amplify push`. I accept each and every time, but the fact that the prompt keeps reappearing makes me think that this security change is not actually being implemented.

**Comment by belfortf** [comment]
This is super annoying. I am currently testing a lambda function with lambda layers, so I cannot debug it locally. This means that every time I want to push the lambda to the backend, my entire graphql backend is rebuilt, which takes 10 min. There must be a workaround. I will try to delete the cli and install it again.

**Comment by belfortf** [comment]
I've tried to reinstall the CLI, upgrade it, etc and I always have the same error, exactly like Jesmaster. Is there any workaround ?

**Comment by belfortf** [comment]
I've found a workaround that works for me. I have manually locked schema.graphql on the os level. Now whenever I amplify push there's an error message but amplify proceeds with the building (in my case of a lambda function). From 10 minutes with every build I went to 1. I'd still love a proper solution though.

**Comment by sundersc** [comment]
@Jesmaster @belfortf The warning message is supposed to pop up only if any of the resolvers contain older version of amplify generated VTL code. Do you have any custom resolvers in `amplify/backend/api/<api_name>/resolvers` folder?

Please run `amplify diagnose` and share the project identifier.

**Comment by sundersc** [comment]
Would it be possible to submit the error report using `amplify diagnose`? You may get this error if any of those custom resolvers contain statements which could fail silently on exceptions.

**Comment by belfortf** [comment]
Hi @sundersc , here's my project identifier: 555ae3a5ba049f0a064d5cb63e68b053 . As far as I know we didn't create any custom resolver. Thanks a lot for your help.

**Comment by csmcallister** [comment]
> Would it be possible to submit the error report using `amplify diagnose`? You may get this error if any of those custom resolvers contain statements which could fail silently on exceptions.

Thank you @sundersc. I just ran `amplify diagnose` and sent the report. Project identifier is `d1f895eecb12b66970fe92b4719cfd0a`

**Comment by sundersc** [comment]
Thanks for sharing the project ID. I'm able to reproduce the issue with the schema from the project identifier `555ae3a5ba049f0a064d5cb63e68b053`. Looking into it.

**Comment by sundersc** [comment]
PR #1182 should address this issue. You will see the message on the first push after upgrade because it looks at your current resolver folder but the warning should go away on the next push. 

To avoid the warning on first push after upgrade, you can run the `amplify api gql-compile` first, this will generate the resolvers and then run `amplify push`.

**Comment by jeffstahlin** [comment]
@sundersc I've updated the aws-amplify package in my project to 5.0.11 but the problem persists. I did try ```amplify api  gql-compile```  before the first push, but the message still showed.  It still shows even after the first push is complete. Was there anything else that needed to be updated other than the aws-amplify package perhaps?

**Comment by sundersc** [comment]
This hasn't been released yet. This fix will be included in @aws-amplify/cli (CLI tool for provisioning and deploying backends not to be confused with aws-amplify which is a JS library).

**Comment by jeffstahlin** [comment]
@sundersc  there have been two updates to the Amplify CLI which I upgraded via the terminal command ```amplify upgrade```.  I just wanted to know if you can confirm if the mentioned fix has been included already as I am still having the same issue. I have two other Amplify projects, initialised nearly a year later than this one, and this issue does not affect them so I am trying to find out if there is something wrong in my config or if the fix you mentioned will be a possible solution.

**Comment by sundersc** [comment]
Could you run `amplify version` and confirm the version? If you are on 10.7.1 or higher, please run `amplify diagnose` and share the project identifier.

**Comment by sundersc** [comment]
@belfortf @csmcallister - Could you check this with the latest CLI version and let me know in case of any issues.

**Comment by csmcallister** [comment]
> @belfortf @csmcallister - Could you please check this with the latest CLI version and let me know in case of any issues.

Apologies for the delay. I was on version 10.6.2. If I run `amplify status`, I see "No Change" for every category, as expected. But then running `amplify push` lists the need for an "Update" operation to the Api category, which introduces the familiar message of "This version of Amplify CLI introduces additional security enhancements for your GraphQL API. The changes are applied automatically with this deployment. This change won't impact your client code. Continue?". I then have to wait ~10 minutes for a no-op update to occur.

Upgrading to `10.7.3` with `amplify upgrade` and then verifying that with a subsequent `amplify version` results in the same behavior, even when I run `amplify push` additional times. 

FWIW, based on [your earlier comment](https://github.com/aws-amplify/amplify-category-api/issues/729#issuecomment-1387546109), I removed all of my custom resolvers in the `amplify/backend/api/<api-name>/resolvers` directory and replaced them with a custom cdk resource as documented [here](https://docs.amplify.aws/cli/graphql/custom-business-logic/#vtl-resolver). I also don't have any legacy v1 features in my graphql schema (running `amplify migrate api` tells me as much).

**Comment by sundersc** [comment]
My apologies. I just found out that Amplify CLI didn't pull this change yet. I'm looking into it.

**Comment by jeffstahlin** [comment]
@sundersc I can confirm that with CLI 10.8.1 I am not getting the security message anymore when running `amplify push`. What a huge relief to finally have this resolved. After updating to the latest version of the CLI I saved the schema.graphql file so that VSCode formats the file (basically removes the trailing spaces) and then ran `amplify api gql-compile` and then did an `amplify push`. Not only did the security message not get displayed but after the update the schema.graphql file didn't contain any trailing spaces. I can't express how relieved I am to have this fixed, waiting 10 mins each time I pushed backend code that I couldn't even test locally was a serious killer, was really close to migrating the whole project to the SST framework in order to get around just this single issue.

**Comment by belfortf** [comment]
Hi @sundersc, I can also confirm that I don't see the error anymore, I didn't have to do anything else like @jeffstahlin. Thanks a lot.

**Comment by csmcallister** [comment]
Oh joy! I upgraded the amplify cli to 10.8.1 and no longer have this issue! However, I did have it on my first `amplify push` despite my API having no changes. After that, I deleted the empty resolvers directory at `amplify/backend/api/<api_name>/resolvers` and pushed again. After that, no more security message with subsequent pushes 🎉
