### ISSUE TITLE
BigInt: Unable to stringify response body

### ISSUE THREAD

**Issue by zirkelc** [aws-amplify/amplify-category-api#733]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm -g

### Amplify CLI Version

9.2.1

### What operating system are you using?

macOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None

### Amplify Categories

api

### Amplify Commands

push, Not applicable

### Describe the bug

BigInt is not supported by Amplify / AppSync

My API has a function that returns an object that is going to be stringified by AppSync:

```gql
type Query {
  bigInt(msg: String): AWSJSON
    @function(name: "bigint-function")
```

The actual Lambda function returns an object with two BigInts (primitive type and BigInt wrapper obejct):

```ts
export const bigInt: AppSyncResolverHandler<any, string> = async (event, context) => {

  const bigIntPrimitive = 9007199254740991n;
  const bigIntObj = BigInt(9007199254740991);

  return { event, bigIntPrimitive, bigIntObj };
};
```

When I run this query on the AppSync console, it throws the following error:

```json
{
  "data": {
    "bigInt": null
  },
  "errors": [
    {
      "path": [
        "bigInt"
      ],
      "data": null,
      "errorType": "Lambda:Unhandled",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Unable to stringify response body"
    }
  ]
}
``` 

Lambda logs the following error to CloduWatch:
```json
{
    "errorType": "Error",
    "errorMessage": "Unable to stringify response body",
    "stack": [
        "Error: Unable to stringify response body",
        "    at _trySerializeResponse (/var/runtime/RAPIDClient.js:212:11)",
        "    at RAPIDClient.postInvocationResponse (/var/runtime/RAPIDClient.js:49:22)",
        "    at complete (/var/runtime/CallbackContext.js:25:12)",
        "    at done (/var/runtime/CallbackContext.js:52:7)",
        "    at succeed (/var/runtime/CallbackContext.js:56:5)",
        "    at /var/runtime/CallbackContext.js:98:16"
    ]
}
```

I'm guess this issue is due to the case that `bigint` is not supported by `JSON.stringify` and requires some special handling: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#use_within_json

### Expected behavior

BigInt should be serialized into a `string` on the backend by AppSync and deserialized back into a `bigint` on the frontend by Amplify API library

### Reproduction steps

1. deploy GraphQL schema
2. deploy Lambda function
3. execute GraphQL query on AppSync console

**Comment by josefaidt** [comment]
Hey @zirkelc :wave: it appears `JSON.stringify()` is unable to stringify a `BigInt`, however we can instead return `bigIntObj.toString()`. Can you see if this works for you?

**Comment by zirkelc** [comment]
@josefaidt this will only work if the API return type is defined as `String`. However, if the API should return an object, we have to use `AWSJSON` and this will implicitly call `JSON.stringify()` on the returned object. 

BigInt is not seriazable into JSON by default, as stated on the [MDN doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#use_within_json):

> Using [JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) with any BigInt value will raise a TypeError, as BigInt values aren't serialized in JSON by default. However, JSON.stringify() specifically leaves a backdoor for BigInt values: it would try to call the BigInt's toJSON() method. (It doesn't do so for any other primitive values.) 

Patching the `toJSON()` function to the BigInt prototype should resolve this issue:
```js
BigInt.prototype.toJSON = function () {
  return this.toString();
};
```

But this has to be done on the runtime level, so I guess within your **RAPIDClient.js** library.

**Comment by alharris-at** [comment]
It appears this issue is entirely within the lambda runtime, so I'd recommend updating function code to return literals which AppSync is able to serialize. (either a Long, or manually as a string, and deserialized in your client application).

Closing this issue.
