### ISSUE TITLE
Ho

### ISSUE THREAD

**Issue by LeoReubelt** [aws-amplify/amplify-category-api#740]
I am working on a messaging app using AWS AppSync. 

I have the following message type...

```
    type Message
        @model
        @auth(
            rules: [
                { allow: groups, groups: ["externalUser"], operations: [] }
            ]
        ) {
        id: ID!
        channelId: ID!
        senderId: ID!
        channel: Channel @connection(fields: ["channelId"])
        createdAt: AWSDateTime!
        text: String
    }
```

And I have a subscription onCreatemessage. I need to filter the results to only channels that the user is in. So I get a list of channels from a permissions table and add the following to my response mapping template.

```
    $extensions.setSubscriptionFilter({
        "filterGroup": [
            {
               "filters" : [
                    {
                        "fieldName" : "channelId",
                        "operator" : "in",
                        "value" : $context.result.channelIds
                    }
               ]
            }
        ]
    })
    
    $util.toJson($messageResult)
```

And it works great. But if a user is in more than 5 channels, I get the following error. 

    {
        "message": "Connection failed: {"errors":[{"message":"subscription exceeds maximum value limit 5 for operator `in`.","errorCode":400}]}"
    }

So how can I filter with more than 5 channels.

**Comment by josefaidt** [comment]
Hey @LeoReubelt :wave: thanks for raising this and apologies for the delay here!! It appears this is a limitation of AppSync where we are not able to exceed 5 values for the `in` operator. Could it be possible to instead leverage a combination of Cognito custom attributes and [owner auth](https://docs.amplify.aws/cli/graphql/authorization-rules/#per-user--owner-based-data-access) with a custom identity claim to achieve similar results without the constraint? Or perhaps if you feel you will not exceed a limit of 500 channels, could Cognito User Pool Groups with [group authorization](https://docs.amplify.aws/cli/graphql/authorization-rules/#user-group-based-data-access) be an option?

```graphql
type Todo @model  @auth(rules: [
  { allow: owner },
  { allow: owner, identityClaim: "custom:channels", ownerField: "channels" }
]) {
  // ...
  channels: [String]
}
```

**Comment by LeoReubelt** [comment]
thanks for the suggestions @josefaidt.  i have to look into the first option (cognito custom attributes, owner auth, custom identity claim). a limit of 500 channels will not work.
