### ISSUE TITLE
Error when compiling pipeline functions from v 8.1.0 onwards

### ISSUE THREAD

**Issue by eliecer2000** [aws-amplify/amplify-category-api#746]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v16.14.0

### Amplify CLI Version

v9.2.1

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I have followed the steps described here.
[Here](https://docs.amplify.aws/cli/graphql/custom-business-logic/#extend-amplify-generated-resolvers)

![image](https://user-images.githubusercontent.com/27373195/185471325-da8d2ad4-0361-42cb-b0e3-e8d0e0caa7b2.png)

Yes, when I use version 8.0.3 it works fine, but any function after that does not work, neither with the complete models nor with OpenSearh since it does not detect the Query.search<models>.

Causing problems when executing a query or mutation in AppSync as the pipelines do not work correctly, I have created a project from scratch with the default GraphQL template for testing and it has the same error. 

In the first image you can see how all the phases of the pipeline function look like, this is with version 8.0.3.

![image](https://user-images.githubusercontent.com/27373195/185469963-fa8d80cc-3411-4b5f-b24b-28ed27f33ea3.png)

Now with version 9.2.1, you see the lack of them.

![image](https://user-images.githubusercontent.com/27373195/185470181-d6bbfcbb-45f0-4b77-aceb-8de49c3d1351.png)

Sorry for the language but English is not my native language.

### Expected behavior

All pipelines are expected to be created.

### Reproduction steps

amplify push

### GraphQL schema(s)

<details>

```graphql
# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @hasMany
}

type Post @model {
  id: ID!
  title: String!
  blog: Blog @belongsTo
  comments: [Comment] @hasMany
}

type Comment @model {
  id: ID!
  post: Post @belongsTo
  content: String!
}



```

</details>

### Project Identifier

Project Identifier: e28a0550a9a33d87907b77391449cd76

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by eliecer2000** [comment]
Hi @josefaidt , do you have information if this can be resolved?

I am thinking of checking the CLI, just not which classes are invoked to create the pipeline Functions.

I have tried to read the code but with no good results.

If you have any information please let me know.

Thanks.

**Comment by josefaidt** [comment]
Hey @eliecer2000 thanks for raising this and so sorry about the delay!! Are you still experiencing this issue?

**Comment by eliecer2000** [comment]
Hello, the problem still persists.
I have not been able to upgrade my CLI.

Regards.

**Comment by josefaidt** [comment]
Hey @eliecer2000 are the resolvers getting copied properly to the `build/resolvers` directory and they are not linked to the pipeline?

**Comment by phani-srikar** [comment]
Hey, we recommend you upgrade your CLI version and check if it resolves your issue. Are there any reasons why you don't want to upgrade?

**Comment by AnilMaktala** [comment]
Hi @eliecer2000 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment and provide us with the information our team had previously asked for. This way, we can reopen the issue and provide you with better assistance.

Thank you!
