### ISSUE TITLE
Cookies set in the response of a custom rest API are not stored in browser

### ISSUE THREAD

**Issue by pedramp20** [aws-amplify/amplify-category-api#762]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

REST API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i7-6650U CPU @ 3.20GHz
    Memory: 4.53 GB / 15.92 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Fitoo\web-app\node_modules\.bin\yarn.CMD
    npm: 7.16.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 94.0.4606.81
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.30)
  npmGlobalPackages:
    @angular/cli: 9.0.5
    @aws-amplify/cli: 6.3.1
    @ionic/cli: 6.17.1
    amplify-category-video: 3.9.1
    amplify-cli: 1.0.0
    amplify-slow-table-create: 1.0.0
    bootstrap: 4.3.1
    bower: 1.8.8
    eslint-plugin-unused-imports: 1.1.1
    eslint: 7.23.0
    expo-cli: 4.1.0
    generator-aspnet-spa: 0.1.3
    generator-aspnetcore-spa: 1.0.0
    grunt: 1.0.4
    json-server: 0.14.2
    n: 2.1.11
    native-run: 1.5.0
    node: 13.10.1
    npm: 7.16.0
    redis-cli: 1.4.0
    stable: 0.1.8
    typescript: 3.6.3
    webpack: 2.6.1
    windows-build-tools: 5.0.0
    wscat: 2.2.1
    yarn: 1.22.10
    yo: 2.0.2
```

</details>

### Describe the bug

I am trying to control who can access my content using cloudfront signed cookies (I am aware of signed urls and it does not work for me as I need to support iOS/Safari). Every required component from s3, cloudfront, api gateway to token generator function are implemented and tested. The only issue that I am facing right now is getting the browser to store the cookies. 

The Cloudfront and the api gateway have  custom domains (cdn.mydomain.com) and (api.mydomain.com) respectively. When the calls are intercepted (using postman) I can confirm that the right cookies are returned and when attached to the call to the cdn I get 200 (using postman). However, in browser, I need to use amplify API library to make the call to the api. To set a cookie with CORS, I need to set `withCredentials`  flag when making the request. 

```
    await API.post("myapi", "/xxxx", {
      headers: {
        withCredentials: "true"
      },
      body: { content },
    })
```

But I keep getting the following error (if I dont add withCredentials header. I get 200 but the cookies are not stored)

```
Access to XMLHttpRequest at 'https://api.mydomain.com/xxxx' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field withcredentials is not allowed by Access-Control-Allow-Headers in preflight response.
```
I have tried to add the header to allowed headers in the api gateway integration (CloudFormation)

``
"x-amazon-apigateway-integration": {
									"responses": {
										"default": {
											"statusCode": "200",
											"responseParameters": {
												"method.response.header.Access-Control-Allow-Methods": "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'",
												"method.response.header.Access-Control-Allow-Headers": "'<<<HERE>>>>,Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'",
												"method.response.header.Access-Control-Allow-Origin": "'*'"
											}
										}
									},
``

my function uses express. CORS is enabled and headers are handled accordingly 
```
app.use(function (request, res, next) {
  const allowedOrigins = ['http://localhost:3000', 'xxxxxxxx'];
  const origin = request.headers.origin;
  if (allowedOrigins.includes(origin)) {
    res.setHeader('Access-Control-Allow-Origin', origin);
  }
  res.header('Access-Control-Allow-Headers', '*');
  res.header('Access-Control-Allow-Credentials', 'true');
  res.header('Access-Control-Allow-Methods', 'GET,HEAD,OPTIONS,POST,PUT');
  //intercept the OPTIONS call so we don't double up on calls to the integration
  if ('OPTIONS' === request.method) {
    res.send(200);
  } else {
    next();
  }
});
````
But no success. It is very frustrating and any help would be very appreciated.

### Expected behavior

When calling api with credentials, the cookies to be set and stored in the browser and consequently being able to call the cloudfront and get 200 response.

### Reproduction steps

Create a rest api using amplify
use express with api gateway integration

Enable Cors as follows:

```
// Enable CORS for all methods
app.use(function (request, res, next) {
  const allowedOrigins = ['http://localhost:3000', 'xxxx'];
  const origin = request.headers.origin;
  if (allowedOrigins.includes(origin)) {
    res.setHeader('Access-Control-Allow-Origin', origin);
  }
  res.header('Access-Control-Allow-Headers', '*');
  res.header('Access-Control-Allow-Credentials', 'true');
  res.header('Access-Control-Allow-Methods', 'GET,HEAD,OPTIONS,POST,PUT');
  //intercept the OPTIONS call so we don't double up on calls to the integration
  if ('OPTIONS' === request.method) {
    res.send(200);
  } else {
    next();
  }
});
```

Set response cookies as follows:

```
app.post('/xxx', async (req, res) => {
  const cookies = await signPath(req.body.content);
  Object.keys(cookies).map((cookieName) => {
    res.cookie(cookieName, cookies[cookieName], { path: "/", domain: ".mydomain.com", sameSite: "None", secure: true });
  })
  res.json({ body })
});
```

Call the API and check if the browser stores the returned cookies in response

P.s. This could very much be a CLI issue.

**Comment by josefaidt** [comment]
Hey @pedramp20 :wave: thanks for raising this! I noticed `withCredentials` is being placed in the request's `headers`, but does this work with `withCredentials` outside of the headers? (This may not be required if we are calling this API from the same domain)

```ts
await API.post("myapi", "/xxxx", {
  withCredentials: true,
  body: { content },
})
```

For reference, the REST API module uses [axios](https://www.npmjs.com/package/axios) under the hood.
