### ISSUE TITLE
We updating the multiple primary and index key that time we are facing the many issues. 

### ISSUE THREAD

**Issue by selva-harivara** [aws-amplify/amplify-category-api#766]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

9.2.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

We are not changing the manual changes in cloud resources.

### Amplify Categories

auth, api

### Amplify Commands

push

### Describe the bug

We updating the multiple primary and index key from existing schema that time we are facing the many issues.  We are can able to push schema to cloud. Also we tried both the comments. 
 1.  amplify push --allow-destructive-graphql-schema-updates
 2.  amplify push --force

### Expected behavior

An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: /
["Index: 0 State: {\"deploy\":\"waitingForDeployment\"} Message: Resource is not in the state stackUpdateComplete"]

### Reproduction steps

Existing schema:  I have used primary key as userId.
```
type FormData
  @model
  @auth(
    rules: [
      { allow: owner, operations: [create, update, read] }
    ]
  ) {
  id: ID!
  fullName: String!
  gender: String!
  userId: ID! @primaryKey
  relationship: String! 
}

Updated schema:  I have changed the primary key as relationship.

type FormData
  @model
  @auth(
    rules: [
            { allow: owner, operations: [create, update, read] }
    ]
  ) {
  id: ID!
  fullName: String!
  gender: String!
  userId: ID! 
  relationship: String!  @primaryKey
}
```
I have tried two amplify comment but i am facing some issues.

1.  amplify push --allow-destructive-graphql-schema-updates
 2.  amplify push --force
 
 
 Error : 
 
 An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: /
["Index: 0 State: {\"deploy\":\"waitingForDeployment\"} Message: Resource is not in the state stackUpdateComplete"]

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @selva-harivara :wave: thanks for raising this! To better understand the context of the issue, would you mind posting the project identifier output from `amplify diagnose --send-report`. Also, do you have a `deployment-state.json` file in your application's deployment bucket?

**Comment by selva-harivara** [comment]
This is my project Project Identifier: 2bfa67a605d594cf5361986c5c85a3b9

deployment-state.json : 
{
  "version": "1",
  "startedAt": "2022-08-26T09:13:13.937Z",
  "finishedAt": "2022-08-26T09:23:44.100Z",
  "status": "FAILED",
  "currentStepIndex": 0,
  "steps": [
    {
      "status": "ROLLING_BACK",
      "previousMetaKey": "amplify-appsync-files/aa0a81a1c758a3ab546f34609decc5d64351a87e/states/initial-stack/deployment-meta.json"
    },
    {
      "status": "WAITING_FOR_DEPLOYMENT"
    }
  ]
}

**Comment by selva-harivara** [comment]
Hey@josefaidt i am waiting for your reply.

**Comment by josefaidt** [comment]
Hey @selva-harivara apologies for the delay, thank you for sending over that information! Can you try deleting the stray `deployment-state.json` file? There's an active bug where this file is not cleaned up after a failed push attempt. Do you remember what the error was with the original push attempt?

**Comment by selva-harivara** [comment]
Still i can't able to fix this issue. I just change the primary key from same schema  id to   userRefId: ID! @primaryKey.
i am facing the below issues. 

Push comment : 

amplify push --allow-destructive-graphql-schema-updates

✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: /
["Index: 0 State: {\"deploy\":\"waitingForDeployment\"} Message: Resource is not in the state stackUpdateComplete"]

✅ Report saved: /var/folders/86/bpm08zk969j_xn4wb52y4cf00000gn/T/loka/report-1662210962754.zip

✔ Done

Project Identifier: 2bfa67a605d594cf5361986c5c85a3b9

**Comment by selva-harivara** [comment]
i Just run the below comment. I got the below error. 
Push comment :

amplify push 

✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: /
Editing the primary key of a model requires replacement of the underlying DynamoDB table.
This update will replace table(s) [tableName]
ALL EXISTING DATA IN THESE TABLES WILL BE LOST!
If this is intended, rerun the command with '--allow-destructive-graphql-schema-updates'.

✅ Report saved: /var/folders/86/bpm08zk969j_xn4wb52y4cf00000gn/T/loka/report-1662212918668.zip

✔ Done

Project Identifier: 2bfa67a605d594cf5361986c5c85a3b9

**Comment by selva-harivara** [comment]
Can you try deleting the stray deployment-state.json file - Yes i tried this step as well. I got the same error only.

 An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: /
["Index: 0 State: {"deploy":"waitingForDeployment"} Message: Resource is not in the state stackUpdateComplete"]

**Comment by josefaidt** [comment]
Hey @selva-harivara apologies for the delay here. Are you still experiencing this issue? Were you able to update the primaryKey?

**Comment by AnilMaktala** [comment]
Hi @selva-harivara 👋, Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
