### ISSUE TITLE
@manyToMany model not implementing identityClaim fields

### ISSUE THREAD

**Issue by Shiftrdw** [aws-amplify/amplify-category-api#770]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.18.1

### Amplify CLI Version

9.0.0

### What operating system are you using?

windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

After implementation of the owner authorization strategy (i.e \<sub\>::\<username\>), the @manyToMany model does not automatically implement the field level authorization. this is my appsync model: (See GraphQL Schema Dropdown)

The picture below shows behaviour before and after. (bottom 2 is before, top 2 is after implementation of \<sub\>::\<username\>). 

![image](https://user-images.githubusercontent.com/50456402/187223282-93192ccf-0034-489b-a94c-ecae7debef4b.png)

### Expected behavior

the new authorization model automatically addresses field level authorization

### Reproduction steps

1. amplify push -y

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Worker
  @model
  @auth(
    rules: [
      { allow: public, provider: apiKey },
      { allow: owner, ownerField: "tenantId", identityClaim: "custom:tenantId" }
    ]
  ) {
    id: ID! 
    userId: ID! @index(name: "byUserId", queryField: "workerByUserId")
    user: User @hasOne(fields: ["userId"]) 
    active: Boolean
    roles: [Role] @manyToMany(relationName: "WorkerRoles")
    tenantId: ID @default(value: "${ctx.identity.claims['custom:tenantId']}") @index(name: "byTenantId", queryField: "workerByTenantId")
    dummy: Boolean
  }

type Role
  @model
  @auth(
    rules: [
      { allow: public, provider: apiKey },
      { allow: owner, ownerField: "tenantId", identityClaim: "custom:tenantId" } 
    ]
  ) {
    id: ID! 
    name: String!
    color: String!
    tenantId: ID @default(value: "${ctx.identity.claims['custom:tenantId']}") @index(name: "byTenantId", queryField: "roleByTenantId")
    workers: [Worker] @manyToMany(relationName: "WorkerRoles")
  }

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @Shiftrdw :wave: thanks for raising this and apologies for the delay! To better understand the context of the issue can you provide a bit more detail around the motivation for the default value on the owner auth field?

```
{ allow: owner, ownerField: "tenantId", identityClaim: "custom:tenantId" }
```

with owner authorization, the `tenantId` field should automatically be populated when a record is created.

> automatically addresses field level authorization

To clarify, are you referring to the authorization on the join table?

**Comment by Shiftrdw** [comment]
Hi @josefaidt. Thank you for your response.

`{ allow: owner, ownerField: "tenantId", identityClaim: "custom:tenantId" }`

The purpose of the authorization field was to allow a tenant access to the particular @model
The custom cognito attribute is handled by another lambda upon confirmation of a tenant admin. 

with regards to the owner authorization, the tenantId field that i referred to was in the join table. In previous amplify versions,
you would have to manually define the join table with @connection but i understand that the newer method simplifies the process. 

However, the owner field authorization was not automatically updated when a record is created. Sometimes, it does and sometimes it does not, although my amplify configuration has been the same throughout.

**Comment by josefaidt** [comment]
Hey @Shiftrdw apologies for the delay here, are you still experiencing this issue? Upon reading further I noticed you have an `@default` directive on this `tenantId`, which will be autopopulated by the specified auth rule

**Comment by AnilMaktala** [comment]
Hey @Shiftrdw, Are you still experiencing this issue?

**Comment by Shiftrdw** [comment]
Not anymore
