### ISSUE TITLE
Is it possible to use AppSync enhanced filtering?

### ISSUE THREAD

**Issue by dylan-westbury** [aws-amplify/amplify-category-api#776]
**Which Category is your question related to?**

AppSync 

**Amplify CLI Version**
9.2.1

**What AWS Services are you utilizing?**
AppSync / Cognito

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
Is it possible to use AppSync enhanced filtering? (AWS AppSync service backend filtering)

https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-enhanced-filtering.html

I saw a PR for https://github.com/aws-amplify/amplify-category-api/pull/551 , however I can't work out if it's possible to implement or now.

**Comment by josefaidt** [comment]
Hey @dylan-westbury :wave: thanks for raising this! This feature for runtime filtering is under active development 🙂
