### ISSUE TITLE
API request filtered by the "_deleted" field from DataStore

### ISSUE THREAD

**Issue by sebboe** [aws-amplify/amplify-category-api#78]
### Is this feature request related to a new or existing Amplify category?

api

### Is this related to another service?

DataStore

### Describe the feature you'd like to request

I would like to be able to filter my API requests using the "_deleted" field generated by DataStore to avoid fetching deleted data when fetching from the API (GraphQL). The field is not present in the generated in the API FilterInput model.

Example request (not working):
```
    const flights = this.apiService.ListFlights({_deleted: {ne:true}}).then((evt) => {
      let flights = evt.items;
      return flights
    });
```
Generated FilterInput (_deleted not present):
```
export type ModelFlightFilterInput = {
  id?: ModelIDInput | null;
  and?: Array<ModelFlightFilterInput | null> | null;
  or?: Array<ModelFlightFilterInput | null> | null;
  not?: ModelFlightFilterInput | null;
};
```

### Describe the solution you'd like

Adding the _deleted field in the generated API FilterInput model.

### Describe alternatives you've considered

Filtering after fetching all the data.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by bergmorten** [comment]
Any update on this feature request. I'm often get in situation where I want to filter out _deleted items?

The same issue is aslo relevant for _createdAt or _updatedAt is not in the filter model...

**Comment by orome** [comment]
Any update on this? Seems like a pretty essential feature.

**Comment by GabiVeks** [comment]
Any update on this feature request. I'm often get in situation where I want to filter out _deleted items?

**Comment by lien-dkseo** [comment]
+1

**Comment by RikiZimbakov** [comment]
+1

**Comment by efingal** [comment]
I am trying to add the _deleted filter in my schema.graphql (there are two files with this name).  Regardless of where I put it, I see it being removed by the initial fetch phase of 'amplify push'.  Is there something I am missing?

**Comment by danyalxahid** [comment]
> I am trying to add the _deleted filter in my schema.graphql (there are two files with this name). Regardless of where I put it, I see it being removed by the initial fetch phase of 'amplify push'. Is there something I am missing?

Having the same problem which adding _Deleted field in the filter input and when i mock graphql it gets removed.

Anyone has a workaround for this? Other than disabling Conflict resolution.

**Comment by lKrayola** [comment]
+1

**Comment by Dennis-Dekker** [comment]
+1, especially for updatedAt.

**Comment by jdanielsyeah** [comment]
> ```graphql
> _deleted: ModelBooleanInput
> ```

Do we do this in the AppSync console? Or should this be done somewhere in the front-end files?

**Comment by nathankopp** [comment]
+100000000

Why hasn't this been implemented yet?  Seems very simple.  Just add _deleted, _updatedAt, and _createdAt to the generated Input schema types.

**Comment by orome** [comment]
> Why hasn't this been implemented yet? Seems very simple. Just add _deleted to the generated Input schema types.

This makes me worry a bit about whether Amplify has a future. This should have been fixed long ago.

**Comment by zxcvbnmmohd** [comment]
Ahhh, need this asapppppp, +01000001 01010111 01010011

Seems to work with the createdAt and updatedAt but not deletd, might as well add the version too!

**Comment by rajczi** [comment]
@josefaidt This has been an open request for nearly a year and seems pretty strait forward.  Why isn't there a codegen parameter to tell it to include the managed fields like `_deleted`, `_ttl`, `_updatedAt`, `_createdAt`, etc.

**Comment by orome** [comment]
@rajczi  Amplify is a disaster. Recently I had a "push" (they really shouldn't call it that) abort and completely corrupt my backend. As a result, I can no longer push or pull and the only solution is to get on a call with "support" and manually editing the backend files with their devs in an attempt to restore a coherent state. I can only recommend urgently to anyone using Amplify: find another tool!

**Comment by MorFix** [comment]
This is now available in [Amplify CLI v12.0.1](https://github.com/aws-amplify/amplify-cli/releases/tag/v12.0.1)!

**Comment by renebrandel** [comment]
Closing as this has been released.

**Comment by osehmathias** [comment]
Linking this issue as this was not resolved. 

https://github.com/aws-amplify/amplify-js/issues/12933
