### ISSUE TITLE
CI cannot build for environment, currently can't deploy to live

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-category-api#780]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

v10.0.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Nope

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

this started today and initially I hoped it was a blip but its recurring and I can't seem to get past it.

Seems my live environment is stuck in "UPDATE_ROLLBACK_FAILED" state. This might be a compounded problem as I've tried pushing a few times to clear it but this latest one was after lunch so its had a good hour to clear itself down yet still I'm getting this latest error.

"There was an error initializing your environment.
Error [ValidationError]: Stack:arn:aws:cloudformation:eu-west-1:<Some numbers>:stack/amplify-franchisemanager-prod-123456/<Some GUID> is in UPDATE_ROLLBACK_FAILED state and can not be updated"

I'm unsure how to unstick this one. As a result I currently cannot deploy to live.

When this first happened this morning I tried upgrading the CLI and amplify itself within our project. Still getting error though.

### Expected behavior

Pushing to git triggers a successful build. Alternatively the ROLLBACK clears itself.

### Reproduction steps

Not really sure...

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by PeteDuncanson** [comment]
I'm trying a trick. Going to redeploy the last good build (which is the one that is currently up) and see if that unsticks it then I'll do a fresh push to github and see if that goes through. Long shot but I think something similar seems to have worked for dev earlier, that is the only thing I can think we've done different really

**Comment by parvusville** [comment]
@PeteDuncanson Would you mind sharing the post which you successfully used to clear he UPDATE_ROLLBACK_FAILED state? I'm also stuck with similar issue #781

**Comment by PeteDuncanson** [comment]
@parvusville oops, you know I thought I already had, cut and paste error clearly!

It was this one: https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-stack-cleanup-stuck/

Thanks for the nudge, not like me to not leave some breadcrumbs for others to follow if I've found an answer. Good luck :)
