### ISSUE TITLE
Can't update using the GUI or CLI

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-category-api#786]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.8.0

### Amplify CLI Version

9.2.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

On the lambda function there is an environment variable that is the dynamodb table

### Amplify Categories

api

### Amplify Commands

env, push

### Describe the bug

I see that there has been a migration to Transformer v2, I don't know if this is what's causing the issue. Two things:

### Issue 1
On the GUI I can't deploy any change because it says:

`cannot push Amplify environment "dev" due to missing Lambda function environment variable values. Rerun 'amplify push' without '--yes' to fix. - Function ___redacted___ is missing values for environment variables: USERTABLE`

> Note that I have done `amplify push` without the -y multiple times from the cli and has been successful, for example just adding a space to the schema or renaming a variable this succeeds. 
> Also locally when I push, the environment variable is set

![image](https://user-images.githubusercontent.com/34192856/188281112-31bb4181-ef65-420e-ae9c-cc3c6ee81d44.png)

### Issue 2
When I try to update multiple tables on the `schema.graphql` locally, I get the following message:

```
Following resources failed

Resource Name: SyncAnalyticsResolver (AWS::AppSync::Resolver)
Event Type: create
Reason: Only one resolver is allowed per field. (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException; Request ID: ___redacted___; Proxy: null)


Resource Name: ListAnalyticsResolver (AWS::AppSync::Resolver)
Event Type: create
Reason: Only one resolver is allowed per field. (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException; Request ID: ___redacted___; Proxy: null)
```

What's the solution? Also if possible how can I migrate that schema to v2?

Thank you

### Expected behavior

- I can update the schema using the GUI
or
- Using the CLI no matter how many tables I update at the same time

### Reproduction steps

For issue 1, just make any change on the gui and hit deploy
For issue 2, delete 1 table

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

type User @model @auth(rules: [{allow: owner, ownerField: "id"}]) {
  id: ID!
  email: String
  createdAt: String
  name: String
  age: Int
  wallets: [Wallet] @connection(name: "UserWallets")
  portfolios: [Portfolio] @connection(name: "UserPortfolios")
}

# Keeps track of various parts of the Portfolio in-app to be restored in multiple devices
type Portfolio @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  chainsAllowedInTotalBalance: AWSJSON                  # Instead of scanning for all blockchains everytime app lunches, only scan for these chains updated when a new wallet is added
  user: User @connection(name: "UserPortfolios")
}

type Wallet @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  address: String!
  walletName: String
  # totalBalance: Float
  chainsWithBalance: AWSJSON  # Stores chains in which wallet has some balance
  userEnabledChains: AWSJSON  # Which chains the user wants to scan for that wallet
  user: User @connection(name: "UserWallets")
}

type Analytics @model @auth(rules: [{allow: owner}]) {
  id: ID!
  UserAnalytics: User @connection
}

type Protocols @model @auth(rules: [{allow: private}]) {
  id: ID!
  name: String
  imgUrl: String
  currentROI: Float
  websiteUrl: String
  contractsList: AWSJSON
  oldContractsList: AWSJSON
  description: String
}

type HistoricalCoinsValue @model @auth(rules: [{allow: private}]) {
  id: ID!
  name: String
  coingeckoId: String
}
```

</details>

### Project Identifier

0ec5cc59002a8341d909bccd947278a9

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
Hey @afern247, could you provide us your use case for adding multiple resolvers and the resolvers currently being added here.

**Comment by josefaidt** [comment]
Hey @afern247 :wave: as a follow up question, have you enabled the improved pluralization feature flag? Does this issue also occur if models such as `Analytics` are written as singular `Analytic`?

**Comment by afern247** [comment]
> Hey @afern247, could you provide us your use case for adding multiple resolvers and the resolvers currently being added here.

You lost me there, what do you mean resolvers? I was reading a little bit and this seems like a util to migrate when you want to change the schema?

**Comment by afern247** [comment]
> Hey @afern247 👋 as a follow up question, have you enabled the improved pluralization feature flag? Does this issue also occur if models such as `Analytics` are written as singular `Analytic`?

Are you referring to this? `model.pluralName = "Analytics"`?

That's what I get on the code and I manually have to change it to this:

`model.syncPluralName = "Analytics"`

What would be the migration steps?

**Comment by afern247** [comment]
Ok so I simulated the same schema using V2 of the transformer.

**This is the new Schema:**
<details>

```graphql

type User @model @auth(rules: [{ allow: owner, ownerField: "id" }]) {
  id: ID!
  email: String
  createdAt: String
  name: String
  age: Int
  Wallets: [Wallet] @hasMany(indexName: "byUser", fields: ["id"])
  Portfolios: [Portfolio] @hasMany(indexName: "byUser", fields: ["id"])
}

"""
Keeps track of various parts of the Portfolio in-app to be restored in multiple devices
"""
type Portfolio @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  chainsAllowedInTotalBalance: AWSJSON                  # Instead of scanning for all blockchains everytime app lunches, only scan for these chains updated when a new wallet is added
  userID: ID! @index(name: "byUser")
}

type Wallet @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  address: String!
  walletName: String
  # totalBalance: Float
  chainsWithBalance: AWSJSON  # Stores chains in which wallet has some balance
  userEnabledChains: AWSJSON  # Which chains the user wants to scan for that wallet
  userID: ID! @index(name: "byUser")
}

type Analytics @model @auth(rules: [{ allow: owner }]) {
  id: ID!
}

type HistoricalCoinsValue @model @auth(rules: [{allow: private}]) {
  id: ID!
  name: String
  coingeckoId: String
}
```

</details>

 and I get the following error:

![image](https://user-images.githubusercontent.com/34192856/190774122-1cf4af01-3d39-49f1-b6e1-2d02419bce1f.png)

I went to the link suggested and it litterally says to replace the old `@connection` with the new directives.

So here's where I am, I have the right migration Schema, I push it and gives error. What's the process for migrating this thing? You guys are not making it too easy it seems :/

# Need some help

@ykethan @josefaidt

**Comment by afern247** [comment]
@josefaidt any update on this?

**Comment by afern247** [comment]
Here's my cli.json

```
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": true,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": false,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "project": {
      "overrides": true
    }
  }
}
```
I see a lot of resolvers under the folder you mentioned, none added by me, I think they were autogenerated:

![image](https://user-images.githubusercontent.com/34192856/192627828-922423bc-c6f5-4520-a673-0e6a50e64123.png)

Based on this info what's the next step? @ykethan

**Comment by ykethan** [comment]
hey @afern247, thank you for confirming this. wanted to check in to see if you ran `amplify migrate api` to migrate the GraphQL API?  This should add the flags in your cli.json when you are migrating from transformer version v1 to v2. Please refer to https://docs.amplify.aws/cli/migration/transformer-migration/#changes-that-amplify-cli-will-auto-migrate-for-you for additional information. 
If you run the migrate command I would suggest checking the cli.json file to ensure the flags have been added.

**Comment by afern247** [comment]
I did it:

![image](https://user-images.githubusercontent.com/34192856/193470963-d0b1657c-6310-4665-8858-c9548de9ebec.png)

Once I do that here's what I get:

> You are using the deprecated parameterization of @connection which cannot be automatically migrated

Then once I try to change those connections, we go back to square 1 [above](https://github.com/aws-amplify/amplify-category-api/issues/786#issuecomment-1249835279)

What's the solution here?

**Comment by ykethan** [comment]
hey @afern247, 

>You are using the deprecated parameterization of @connection which cannot be automatically migrated

the warning message occurs when we utilize the @connection which is being deprecated in favor of more explicit directives detailing the relation’s semantics: `@hasOne, @hasMany, @belongsTo, @manyToMany`

I understand that on modifying the `@connection` directive to the new relation semantics the cli throws the error provided in the second screenshot. could you confirm if the cli.json has the new flags added after running the migrate command?
if no, could you please copy the cli.json file provided on the comment https://github.com/aws-amplify/amplify-category-api/issues/786#issuecomment-1259591872 and run `amplify api gql-compile` to check if the errors persist.
Please refer to https://docs.amplify.aws/cli/migration/transformer-migration/ for additional information.

**Comment by afern247** [comment]
> hey @afern247,
> 
> > You are using the deprecated parameterization of @connection which cannot be automatically migrated
> 
> the warning message occurs when we utilize the `@connection` which is being deprecated in favor of more explicit directives detailing the relation’s semantics: `@hasOne, @hasMany, @belongsTo, @manyToMany`
> 
> I understand that on modifying the `@connection` directive to the new relation semantics the cli throws the error provided in the second screenshot. could you confirm if the cli.json has the new flags added after running the migrate command? if no, could you please copy the cli.json file provided on the comment [#786 (comment)](https://github.com/aws-amplify/amplify-category-api/issues/786#issuecomment-1259591872) and run `amplify api gql-compile` to check if the errors persist. Please refer to https://docs.amplify.aws/cli/migration/transformer-migration/ for additional information.

After I do `amplify migrate api` it doesn't add the new transformer flag to the cli, as a matter of fact, the cli file is not modified at all, what happens is that it creates a new file called: `cli-inputs.json` with this content:

```
{
  "version": 1,
  "serviceConfiguration": {
    "serviceName": "AppSync",
    "defaultAuthType": {
      "mode": "AMAZON_COGNITO_USER_POOLS",
      "cognitoUserPoolId": "authRoad2Crypto"
    },
    "additionalAuthTypes": [
      {
        "mode": "API_KEY",
        "expirationTime": 30,
        "keyDescription": "api key description"
      },
      {
        "mode": "AWS_IAM"
      }
    ],
    "conflictResolution": {
      "defaultResolutionStrategy": {
        "type": "AUTOMERGE"
      }
    },
    "apiName": "Road2CryptoGraphQlAPI"
  }
}
```

After copy your cli.json and do `amplify api gql-compile` with the schema to not have those `@connection` and use the new ones, I get: `GraphQL schema compiled successfully`

If I do `amplify status` it says: `GraphQL transformer version: 2`

So I went and did `amplify push` and it pushed successfully ✅

It seems to be migrated now. Thank you @josefaidt

**Comment by afern247** [comment]
Well issues there are, for example my code now complains about those connections of not being a model and being a String or something like that, I guess I have to play around with it and see what's the proper way to set it up.

I'm also seeing this warning now that I was not seeing before:

![image](https://user-images.githubusercontent.com/34192856/194372052-df46a620-f7b9-448d-95a6-4eb33b411604.png)

This is how I have setup the model:

```
type User @model @auth(rules: [{allow: owner, ownerField: "id"}]) {
...
}

type Wallet @model @auth(rules: [{allow: owner}]) {
...
}
```

I was checking the docs and it's declared how it says on the docs. So what is this warning about then? @josefaidt @ykethan

**Comment by josefaidt** [comment]
@afern247 this warning is about having a model-level owner auth rule, where the `owner` field is left without a field-level auth rule to deny owners from `update`-ing their record, which a malicious actor could change the ownership of that record to another user

**Comment by afern247** [comment]
How can I prevent such thing? What's the parameter to indicate there? @josefaidt

**Comment by josefaidt** [comment]
There's a small example in that docs link https://docs.amplify.aws/cli/graphql/authorization-rules/#per-user--owner-based-data-access

<img width="743" alt="image" src="https://user-images.githubusercontent.com/5033303/194390922-23492d5d-9594-4728-a034-20edb6ed78ec.png">

**Comment by afern247** [comment]
Perfect, thank you very much for all your help @josefaidt . I'm happy with the result, I think we can close it
