### ISSUE TITLE
Delete DynamoDB table when user is deleted

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-category-api#795]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
API Service

**Amplify CLI Version**
9.2.1

**What AWS Services are you utilizing?**
Auth, DynamoDB and Lambda Functions

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

Recently Amplify introduced an option to be able to delete the user, how can I setup a lambda function so when the current logged in user hits the button `delete account`, the lambda function deletes the table that reference that user? I have a User table with the same id as the auth user.

Is there any trigger for this? I see we have a post verification signup trigger (which is what I'm using to create the dynamodb table):

```
Do you want to configure Lambda Triggers for Cognito? Yes
Which triggers do you want to enable for Cognito?  Post Confirmation
```

Do we have anything like this for deletion? If not how can I implement it?

**Comment by josefaidt** [comment]
Hey @afern247 :wave: using the [Admin Queries API](https://docs.amplify.aws/cli/auth/admin/#admin-queries-api) as a template, you can build a custom `deleteUser` flow that executes the Cognito action and your custom action, where in this case you are looking to delete a corresponding DynamoDB table

**Comment by afern247** [comment]
I was able to delete the user data using `Amplify.DataStore.delete(User.self, withId: user.id) { result in` however it seems this approach requires that I delete each model manually, so:

`User` model
`Analytics` model
`UserPortfolio` model
...

How can I delete the `User` model and trigger an automatic delete for the rest of the models whos owner is that `User`?

**Comment by josefaidt** [comment]
Hey @afern247 apologies for the delay here!!! Although it's delayed I wanted to follow up. In addition to the earlier recommendation to use the Admin API template, you will need to fetch each model (including the nested models) and delete each one manually as we do not currently support a sort of "cascading" delete. In short you will want to:

1. send a request to some API that performs the delete
2. fetch associated models (User, Wallet, Portfolio)
3. delete the user from cognito
4. delete the associated models individually:
	```graphql
	mutation DELETE_USER_DATA {
		deleteUser(id: $userId) { id }
		deleteWallet(id: $walletId) { id }
		deletePortfolio(id: $portfolioId) { id }
	}
 	```

**Comment by afern247** [comment]
I don't think an admin query is the way to go. Since the user owns the data, I can delete it before loging out the user (theoretically right?). Here's the sample schema:

```
# The "owner" of a User is allowed to create, read, update, and delete their own user data
type User @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  email: String
  createdAt: String
  owner: String @auth(rules: [{ allow: owner, operations: [read, delete] }]) # To prevent an owner from reassigning their record to another user
}
```

and here's what I'm trying to do:

```
func deleteUser() async -> (didSucceed: Bool, errorMessage: String) {
        var errorMessage = ""
        
        // Retrieve your User using Amplify.API.query
        if let user = await getUser().user {
            do {
                let result = try await Amplify.API.mutate(request: .delete(user))
                switch result {
                case .success:
                    print("✅ Successfully deleted user")
                    return (true, errorMessage)
                    
                case .failure(let error):
                    ...
                }
            } catch let error as APIError {
                ...
            } catch(let error) {
                ...
            }
        } else {
            ...
        }
        
        return (false, errorMessage)
    }
```

I have the authorization rule to be Cognito, but when I try to delete that User schema which the same user created I get:

`Got failed result with GraphQL service returned a successful response containing errors: [Amplify.GraphQLError(message: "Conflict resolver rejects mutation.", locations: Optional([Amplify.GraphQLError.Location(line: 2, column: 3)]), path: Optional([Amplify.JSONValue.string("deleteUser")]), extensions: Optional(["errorType": Amplify.JSONValue.string("ConflictUnhandled"), "data": Amplify.JSONValue.object(["email": Amplify.JSONValue.string("example@example.com"), "id": Amplify.JSONValue.string("1f322307-4193-4e32-b0f6-934302a23625"), "owner": Amplify.JSONValue.null, "__typename": Amplify.JSONValue.string("User"), "updatedAt": Amplify.JSONValue.string("2023-04-15T19:53:57.498Z"), "age": Amplify.JSONValue.null, "name": Amplify.JSONValue.null, "createdAt": Amplify.JSONValue.string("2023-04-15T19:53:57.498Z")]), "errorInfo": Amplify.JSONValue.null]))]`

**Comment by afern247** [comment]
Updated:

Based on [this docs](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/ios/#configure-api), it seems that GraphQL doesn't support conflict resolution:

![image](https://user-images.githubusercontent.com/34192856/232334222-f55a3d9c-8e4d-4888-ba67-ee149e0f8f7c.png)

So if I delete for example the User data with GraphQL I get that conflict error. If I delete it with DataStore it deletes it from Amplify Studio data but not from the DynamoDB area that GraphQL uses...

If I remove conflict resolution I'm risking old/outdated data + I can't see the data on Amplify Studio...

Can you please advice @josefaidt

**Comment by josefaidt** [comment]
Hey @afern247 apologies for missing the `DataStore` callout earlier in the thread. While it is not typically suggested to mix DataStore and `API.graphql`/POST calls to AppSync, you will need to pass the current `_version` manually. 

With the setup noted above you will want to include the current `_version` in order to update, and if this model is "deleted" (i.e. `_deleted === true`) it will still show up in DynamoDB. If you would like to remove this record altogether you can enable TTL https://docs.amplify.aws/cli/storage/override/#customize-amplify-generated-s3-resources

**Comment by afern247** [comment]
Alright, I'll try it out if not create a lambda for it. Thanks jose
