### ISSUE TITLE
Environment stuck

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-category-api#798]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.8.0

### Amplify CLI Version

9.2.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

"No manual changes made"

### Amplify Categories

api

### Amplify Commands

env, push

### Describe the bug

The environment is stuck, it doesn't finish updating or at least skip that update:

![image](https://user-images.githubusercontent.com/34192856/190047296-0f4b17d0-3acd-4a00-ae63-5ee3a048663a.png)

I get the error:

`Embedded stack arn:aws:cloudformation:us-east-123:stack/amplify-myapp-dev-123-apimyappGraphQlAPI-123 was not successfully updated. Currently in UPDATE_ROLLBACK_FAILED with reason: The following resource(s) failed to update: [Protocols, Portfolio, Wallet, User]. `

I tried going to the resource page:

![image](https://user-images.githubusercontent.com/34192856/190047522-12d254fc-cdaf-4b7b-a3e9-1d7fbc1027d7.png)

and tapping on the resource that failed, then continue update rollback:

![image](https://user-images.githubusercontent.com/34192856/190047618-ee798205-3446-41ab-b592-79ef3562907a.png)

![image](https://user-images.githubusercontent.com/34192856/190047993-b1f4066a-9d25-43ca-9b3e-ed562751cd0a.png)

and after that finishes I get the same error...

Also if I tried to make any update on the terminal I get the following:

![image](https://user-images.githubusercontent.com/34192856/190051279-45814cd4-b4d6-4005-bae8-b02e894a8ae5.png)

How can I unstuck this?

### Expected behavior

working

### Reproduction steps

I think it was because I'm using the AppSync transformer v1 and I tried to update more than 1 model in the schema at the same time that had the keyword `@connection` . Not sure if this is the cause.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

type User @model @auth(rules: [
    { allow: owner, ownerField: "id" }
  ]) {
  id: ID!
  email: String
  createdAt: String
  name: String
  age: Int
  wallets: [Wallet] @connection(name: "UserWallets")
  portfolios: [Portfolio] @connection(name: "UserPortfolios")
}

"""
Keeps track of various parts of the Portfolio in-app to be restored in multiple devices
"""
type Portfolio @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  chainsAllowedInTotalBalance: AWSJSON                  # Instead of scanning for all blockchains everytime app lunches, only scan for these chains updated when a new wallet is added
  user: User @connection(name: "UserPortfolios")
}

type Wallet @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  address: String!
  walletName: String
  # totalBalance: Float
  chainsWithBalance: AWSJSON  # Stores chains in which wallet has some balance
  userEnabledChains: AWSJSON  # Which chains the user wants to scan for that wallet
  user: User @connection(name: "UserWallets")
}

type Analytics @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  UserAnalytics: User @connection
}

type Protocols @model @auth(rules: [{allow: private}]) {
  id: ID!
  name: String
  imgUrl: String
  currentROI: Float
  websiteUrl: String
  contractsList: AWSJSON
  oldContractsList: AWSJSON
  description: String
}

type HistoricalCoinsValue @model @auth(rules: [{allow: private}]) {
  id: ID!
  name: String
  coingeckoId: String
}
```

</details>

### Project Identifier

Project Identifier: 0ec5cc59002a8341d909bccd947278a9

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @afern247 :wave: thanks for raising this! From the CloudFormation console do you see any drift from the "Detect Drift" and "View Drift Result" buttons? Were there any manual changes made in the console to your API or underlying DynamoDB resources?

Also, do you also experience this issue in a new environment?

**Comment by afern247** [comment]
Hi, yes I see some drifts, what does it mean? See image below.

![image](https://user-images.githubusercontent.com/34192856/192113353-27adb110-ce2f-441a-94b9-99164d86c1ec.png)

Some points that might help to find what's going on:
- The same issue happens across all env. because they are all the same in terms of configuration (different resources)
- I have an environment variable name
- I create an inline policy following these instructions:

1. Click on Permissions in the lambda function and click the link under Execution role. Here we'll be giving permission to our lambda function to interact with our DynamoDB.
2. Click on "Add inline policy" and select JSON to only allow DynamoDB Put action.

Here's where it's located:

![image](https://user-images.githubusercontent.com/34192856/192113588-5d8a5e31-8ab7-42d4-bca3-e0c8674174e2.png)

It looks like this:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "dynamodb:PutItem"
            ],
            "Resource": "DYANMODB_USER_ARN_GOES_HERE"
        }
    ]
}
```

Any thoughts? @josefaidt

**Comment by afern247** [comment]
Any update on this? @josefaidt

**Comment by josefaidt** [comment]
Hey @afern247 apologies for the delay, instead of manually modifying the execution role can you try adding this to the `custom-policies.json` file in your function's directory? https://docs.amplify.aws/cli/function/#access-existing-aws-resource-from-lambda-function

**Comment by josefaidt** [comment]
We are tracking the drift issues with the auth/unauth roles in another issue, and it should not block deployments. What were the errors in CloudFormation from the original failed update? Are you able to chunk out the changes (e.g. add one new relationship, push, observe if successful/failed)?

**Comment by josefaidt** [comment]
Hey @afern247 to add on to my message above, what were the schema changes prior to receiving this issue?

**Comment by afern247** [comment]
> Hey @afern247 apologies for the delay, instead of manually modifying the execution role can you try adding this to the `custom-policies.json` file in your function's directory? https://docs.amplify.aws/cli/function/#access-existing-aws-resource-from-lambda-function

How would I write this into the `.json`? I was looking at the link you gave me and they don't really mention how to add new fields or where, this is how my postconfirmation lambda `.json` looks (mine doesn't say custom-policies.json, am I looking at the wrong one?):

![image](https://user-images.githubusercontent.com/34192856/194184178-fd812838-c48e-4924-a876-e1ef6e8022b7.png)

I guess it would be something similar to `PolicyDocument` on the picture above? But how do I structure it to be like the rule I need, is the first letter (PolicyDocument) any title I give it to or how does it work? You understand my question? Like what's the order and the meaning of th structure.

**Comment by afern247** [comment]
> We are tracking the drift issues with the auth/unauth roles in another issue, and it should not block deployments. What were the errors in CloudFormation from the original failed update? Are you able to chunk out the changes (e.g. add one new relationship, push, observe if successful/failed)?

It was when I tried to update multiple `@connection` at the same time. This was the very first error:

![image](https://user-images.githubusercontent.com/34192856/194185349-639b9dc5-51c9-43ad-be9b-15742bbbd6cd.png)

**Comment by afern247** [comment]
> Hey @afern247 to add on to my message above, what were the schema changes prior to receiving this issue?

Well, I was modeling how the prod schema would be and did some changes, but I think I had reverted most. Right now this is the difference between prod and dev, prod being the one on the left:

![image](https://user-images.githubusercontent.com/34192856/194186122-d83fb858-687b-4b54-8394-19270b9b97a4.png)

Is this what you meant? @josefaidt
