### ISSUE TITLE
amplify-appsync-simulator $util.epochMillisToISO8601 does not work

### ISSUE THREAD

**Issue by tbartley** [aws-amplify/amplify-category-api#803]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

16

### Amplify CLI Version

2.5.1 (@aws-amplify/amplify-appsync-simulator only)

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

N/A

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

@aws-amplify/amplify-appsync-simulator $util.epochMillisToISO8601 does not work when passed the result of another simulated $util method. For example:

  #set($nowEpochMs = $util.time.nowEpochMilliSeconds())
  #set($nowISO8601 = $util.time.epochMilliSecondsToISO8601($nowEpochMs))

The value of nowISO8601 is not as expected. This seems to occur because in the implementation of epochMilliSecondsToISO8601 is a simple call to `return moment(dateTime).toISOString();` where `dateTime` is expected to be a number. The above VTL results in dateTime being a JavaInteger instead.

### Expected behavior

The VTL

```
  #set($nowEpochMs = $util.time.nowEpochMilliSeconds())
  #set($nowISO8601 = $util.time.epochMilliSecondsToISO8601($nowEpochMs))
```
should result in `nowISO8601` being set correctly.

### Reproduction steps

Have VTL

  #set($nowEpochMs = $util.time.nowEpochMilliSeconds())
  #set($nowISO8601 = $util.time.epochMilliSecondsToISO8601($nowEpochMs))

and use amplify-appsync-simulator to verify that nowISO8601 is not set correctly.

This Jest test should pass:

```typescript
    it('should convert ms to iso8601 correctly', () => {
      const template = `
      #set($nowEpochMs = $util.time.nowEpochMilliSeconds())
      #set($nowISO8601 = $util.time.epochMilliSecondsToISO8601($nowEpochMs))

      {
        "version": "2018-05-29",
        "payload": {
          "nowEpochMs": $util.toJson($nowEpochMs),
          "nowISO8601": $util.toJson($nowISO8601)
        }
      }`

      const velocity = new VelocityTemplate(
        { content: template },
        new AmplifyAppSyncSimulator(),
      )

      const renderContext: AppSyncVTLRenderContext =
      const rendered = velocity.render(
         { arguments: {}, source: {} },
        executionContext, // Can provide the value we use here if necessary but its not relevant to the test
        resolveInfo, // Can provide the value we use here if necessary but its not relevant to the test
      )

      expect(rendered.result.payload.nowEpochMs).toEqual(
        new Date(rendered.result.payload.nowISO8601).getTime(),
      )
    })
```

### GraphQL schema(s)

N/A

### Project Identifier

N/A

### Log output

N/A

**Comment by tbartley** [comment]
May have miss filed my issue or PR but this PR addresses the issue I believe: https://github.com/aws-amplify/amplify-cli/pull/11032

**Comment by phani-srikar** [comment]
Hi @tbartley! Thanks for reaching out and putting together a fix. Before I take a look at the PR, one quick background on the `appsync-simulator` package is that it's only used for local mocking of your API via `amplify mock api`. Does this behavioral limitation occur when you `amplify push` your resolvers to AppSync as well or just when you use local mocking?

**Comment by tbartley** [comment]
No - we see the times correctly converted at the service without any changes. We've been using appsync for a while now and somewhat embarrassingly only discovered this simulator recently so we're busy retrofitting unit tests to all our VTL and noticed this behaviour.
