### ISSUE TITLE
Android GraphQL API: Unable to use multiple auth modes when API Name not passed in function call

### ISSUE THREAD

**Issue by sang2412** [aws-amplify/amplify-category-api#816]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

10.0.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth, api

### Amplify Commands

Not applicable

### Describe the bug

In an Android app using GraphQL API, when a function call is made for a mutation and the optional field - 'api name' is not passed as an argument, then we are not able to use multiple auth modes. Is this expected behavior? 

### Expected behavior

When the 'api name' is not passed as an argument, Amplify should automatically attempt the authorization with each authorization type until one succeeds (or they all fail).

### Reproduction steps

1. Configure a GraphQL API for an Android app. Use Cognito User Pools as the primary authorization mode and IAM as the additional authorization mode.

2. Configure the schema to add a Todoo type with the following auth rules - 

type Todoo @model @auth(rules: [
{ allow: public, provider: iam, operations: [create, read, update, delete] },
{ allow: owner, provider: userPools, operations: [create, read, update, delete] }
]) { ........ } 

3. From the Android app, try to make a function call for a mutation as follows - 

Amplify.API.mutate(
                        ModelMutation.create(myTodoo),
                        response -> Log.i("AuthQuickStart11",  response.toString()),
                        error -> Log.e("AuthQuickStart11", "Create failed " + error.toString())
                );

Note - Do not include the optional field - 'api name' as an argument in this call. 

4. Check if the mutation takes place for both authorizations - user pools & IAM 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
related to https://github.com/aws-amplify/amplify-category-api/issues/814 muti auth modes not getting filled in amplifyconfiguration file. Closing this to prevent any miscommunications.
