### ISSUE TITLE
Reassign ownership warning prevail on join tables

### ISSUE THREAD

**Issue by duranmla** [aws-amplify/amplify-category-api#854]
**Which Category is your question related to?**
Amplify API

**Amplify CLI Version**
10.2.1

**Situation**

I have an schema that looks like:

```graphql
type Profile
  @model
  @auth(
    rules: [
      { allow: public, operations: [read], provider: apiKey }
      { allow: owner }
      { allow: private, operations: [read] }
    ]
  ) {
  id: ID!
  owner: String
    @auth(
      rules: [
        { allow: owner, operations: [read, delete] }
        { allow: public, operations: [read], provider: apiKey }
      ]
    )
  bio: String
  # ... other attrs
  companies: [Company] @manyToMany(relationName: "ProfileCompanyConnection")
}

type Company
  @model
  @auth(
    rules: [
      { allow: private, operations: [create, read, update] }
      { allow: public, operations: [read], provider: apiKey }
    ]
  ) {
  id: ID!
  # ...other attrs
  profiles: [Profile] @manyToMany(relationName: "ProfileCompanyConnection")
}
```

The amplify console keep showing me:

"WARNING: owners may reassign ownership for the following model(s) and role(s): ProfileCompanyConnection: [owner], ProfileProfessionConnection: [owner]. If this is not intentional, you may want to apply field-level authorization rules to these fields. To read more: https://docs.amplify.aws/cli/graphql/authorization-rules/#per-user--owner-based-data-access"

As you can see I have already did what the doc suggests for owner reassign on the Profile model, nonetheless, how I suppose to proceed on the join table as it is created by amplify and it is not under my control?

**Comment by josefaidt** [comment]
Hey @duranmla :wave: thanks for raising this! As you have noted this warning is coming from the auto-generated join table, which to mitigate we would need to construct our own join table. However, I also noticed the owner is not being set when manually creating the connection, using the following set of operations

```graphql
mutation CREATE_COMPANY {
  createCompany(input: {
    
  }) {
    id
  }
}

mutation CREATE_PROFILE {
  createProfile(input: {
    bio: "my profile"
  }) {
    id
    owner
  }
}

mutation CREATE_CONNECTION {
  createProfileCompanyConnection(input: {
    companyID:"02b033a3-dc43-4ac8-8c49-705337cad019"
    profileID:"e45ed916-141b-4bf2-aa8c-6ab6b9c67375"
  }) {
    id
    profileID
    companyID
  }
}

query LIST_ALL {
  listProfileCompanyConnections {
    items {
      profileID
      profile {
        id
        owner
      }
      companyID
      owner
    }
  }
}
```

```json
{
  "data": {
    "listProfileCompanyConnections": {
      "items": [
        {
          "profileID": "e45ed916-141b-4bf2-aa8c-6ab6b9c67375",
          "profile": {
            "id": "e45ed916-141b-4bf2-aa8c-6ab6b9c67375",
            "owner": "josef"
          },
          "companyID": "02b033a3-dc43-4ac8-8c49-705337cad019",
          "owner": null
        }
      ]
    }
  }
}
```

As mentioned the workaround will be to create the join table manually, although I will continue to investigate this with the team

**Comment by duranmla** [comment]
I was hitting with a doubt about this again and I didn't realize you answer me. Apologize for the delay @josefaidt . One thing to also add here is that I am having "issues" when trying to delete an entry from the join table as I got Unauthorized requests, information for you folks:

- Join table entries are being created with a owner set to null
- As profile has companies and companies has many profiles when I try to detach a company from a user by `DataStore.delete(<ProfileCompanyConnectionModel>)` it fails.

I have updated my profile model between other things to also allow **delete** which is not what I like but it solves the issue:

```graphql
type Profile
  @model
  @auth(
    rules: [
      { allow: public, operations: [read], provider: apiKey }
      { allow: private, operations: [read] }
      { allow: private, provider: iam }
      { allow: owner, operations: [read, update, delete] }
    ]
  ) {...}
  
type Company
  @model
  @auth(
    rules: [
      { allow: private, operations: [create, read, update] }
      { allow: public, operations: [read], provider: apiKey }
    ]
  ) {...}
  ```
  
In any case, I guess you are right for now the approach is to manual create the join table. **Is there any documentation to understand how to create manually the join table?** I am not sure where to place those mutations and queries @josefaidt .

**Comment by josefaidt** [comment]
Hey @duranmla no worries! Since the auth rules are merged we are authenticating with Cognito and the owner is not being set (due to the `private` Cognito auth rule)

This line from the `createProfileCompany` auth slotted resolver sets `isAuthorized` to `true`
```
#if( $util.authType() == "User Pool Authorization" )
  #set( $isAuthorized = true )
```

<details><summary>full resolver</summary>

```
## [Start] Authorization Steps. **
$util.qr($ctx.stash.put("hasAuth", true))
#set( $inputFields = $util.parseJson($util.toJson($ctx.args.input.keySet())) )
#set( $isAuthorized = false )
#set( $allowedFields = [] )
#if( $util.authType() == "API Key Authorization" )
$util.unauthorized()
#end
#if( $util.authType() == "IAM Authorization" )
$util.unauthorized()
#end
#if( $util.authType() == "User Pool Authorization" )
  #set( $isAuthorized = true )
  #set( $ownerEntity0 = $util.defaultIfNull($ctx.args.input.owner, null) )
  #set( $ownerClaim0 = $util.defaultIfNull($ctx.identity.claims.get("sub"), null) )
  #set( $currentClaim1 = $util.defaultIfNull($ctx.identity.claims.get("username"), $util.defaultIfNull($ctx.identity.claims.get("cognito:username"), null)) )
  #if( !$util.isNull($ownerClaim0) && !$util.isNull($currentClaim1) )
    #set( $ownerClaim0 = "$ownerClaim0::$currentClaim1" )
    #if( !$isAuthorized )
      #set( $ownerClaimsList0 = [] )
      $util.qr($ownerClaimsList0.add($util.defaultIfNull($ctx.identity.claims.get("sub"), null)))
      $util.qr($ownerClaimsList0.add($util.defaultIfNull($ctx.identity.claims.get("username"), $util.defaultIfNull($ctx.identity.claims.get("cognito:username"), null))))
      #set( $ownerAllowedFields0 = ["id","profileID","companyID","profile","company"] )
      #set( $isAuthorizedOnAllFields0 = true )
      #if( $ownerClaim0 == $ownerEntity0 || $ownerClaimsList0.contains($ownerEntity0) )
        #if( $isAuthorizedOnAllFields0 )
          #set( $isAuthorized = true )
        #else
          $util.qr($allowedFields.addAll($ownerAllowedFields0))
        #end
      #end
      #if( $util.isNull($ownerEntity0) && !$ctx.args.input.containsKey("owner") )
        $util.qr($ctx.args.input.put("owner", $ownerClaim0))
        #if( $isAuthorizedOnAllFields0 )
          #set( $isAuthorized = true )
        #else
          $util.qr($allowedFields.addAll($ownerAllowedFields0))
        #end
      #end
    #end
  #end
#end
#if( !$isAuthorized && $allowedFields.isEmpty() )
$util.unauthorized()
#end
#if( !$isAuthorized )
  #set( $deniedFields = $util.list.copyAndRemoveAll($inputFields, $allowedFields) )
  #if( $deniedFields.size() > 0 )
    $util.error("Unauthorized on ${deniedFields}", "Unauthorized")
  #end
#end
$util.toJson({"version":"2018-05-29","payload":{}})
## [End] Authorization Steps. **
```

</details>

Which this can be fixed via https://github.com/aws-amplify/amplify-category-api/pull/580, and setting the `populateownerfieldforstaticgroupauth` feature flag to `true`, which will ultimately generate a block of logic in this same resolver that sets the owner value if available.

```
 #if( $isAuthorized && $util.isNull($ownerEntity0) && !$ctx.args.input.containsKey("owner") )
      $util.qr($ctx.args.input.put("owner", $ownerClaim0))
    #end
```

---

To create an explicit join table we can use the following schema as an example (apologies in advance for the odd field naming convention on the join table 😷 )

```graphql
type Company @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  address: [CompanyAddress] @hasMany
}

type Address @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  company: [CompanyAddress] @hasMany
}

type CompanyAddress @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  company: Company @belongsTo
  address: Address @belongsTo
}
```

And using the following sequence of mutations, we can create the join record manually

```graphql
mutation CREATE_COMPANY {
  createCompany(input: {
    
  }) {
    id
  }
}

mutation CREATE_ADDRESS {
  createAddress(input: {
    
  }) {
    id
  }
}

mutation CREATE_COMPANYADDRESS {
  createCompanyAddress(input: {
    companyAddressId:"8d7002e2-1355-43bb-83bb-654be0406aa4",
    addressCompanyId:"6ea83def-cd22-46db-a2b6-b7278237114e",
  }) {
    id
  }
}

query LIST {
  listCompanyAddresses {
    items {
      id
      owner
      company {
        id
        owner
      }
      address {
        id
        owner
      }
    }
  }
}
```

ultimately querying

```json
{
  "data": {
    "listCompanyAddresses": {
      "items": [
        {
          "id": "874b7a23-a5bf-47ae-ac0c-387abd9925dc",
          "owner": "josef",
          "company": {
            "id": "8d7002e2-1355-43bb-83bb-654be0406aa4",
            "owner": "josef"
          },
          "address": {
            "id": "6ea83def-cd22-46db-a2b6-b7278237114e",
            "owner": "josef"
          }
        }
      ]
    }
  }
}
```

**Comment by duranmla** [comment]
Oh! got it, I completely forgot of that pattern we can use in order to create a join table manually. And now I also understand what you mean with the _"sequence of mutations, we can create the join record"_ (you are using AppSync to illustrate how the new join table will be used).

I guess I was tired before and I couldn't grasp the concepts you were explaining. Thanks for the time and your reply. I will mark this as close because it seems perfectly fine we go with the manual join table when we need more granular control over records.
