### ISSUE TITLE
add explanation message for API Key creation prompt on `amplify push`

### ISSUE THREAD

**Issue by clintfoster** [aws-amplify/amplify-category-api#86]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.1

### Amplify CLI Version

7.6.23

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Yes, but only as a workaround after repeatedly deleting the API category from my app and starting over in various attempts to get the CLI to stop prompting for API key information. 

At one point I deleted the entire Amplify app and started over. That didn't work either.

The workaround I eventually adopted is described below.

### Amplify Categories

api

### Amplify Commands

add

### Describe the bug

`add api` has a bug when answering the following prompt after selecting `GraphQL`:

>? Choose the default authorization type for the API Amazon Cognito User Pool

My choice:
>Use a Cognito user pool configured as a part of this project.
>? Configure additional auth types? No

For the above interaction the CLI starts off suggesting `API key` as the default authorization type, presenting a list to choose a different one. I chose `Cognito user pool`, as shown above. Then I answered the standard prompts regarding my schema, and the CLI exited normally.

Later, when calling `api push` I mysteriously received the following prompt:
>API key configuration
>? Enter a description for the API key: 

There was no way to avoid answering it, so I entered a dummy description.

Next, it prompted for the key duration, from `1` to `365`. Oddly, it crashed when I specified `1` (apparently a different bug). 

After deleting the API category and starting over a few times I learned it will proceed if I specify a duration of `100`.

### Expected behavior

When choosing `Cognito user pool` for GraphQL API authentication it should not be required to also create an API key.

### Reproduction steps

- `amplify init`
- `add auth`
- Follow prompts to create Cognito User Pool
- `amplify push`
- `amplify add api`

See bug description at this point. In the past it was possible to create a GraphQL API without configuring an API key. This is no longer possible.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I found a possible **workaround** (although I'm still checking whether it resulted in any problematic side effects);

1. During `amplify push` answer the unwanted prompts for API key creation.
2. Then stop at the following prompt: `Do you want to generate code for your newly created GraphQL API (Y/n)`
3. Search the `amplify` directory and remove all entries related to `ApiKey`.
4. Answer the prompt, allowing the push to resume.

It completes without obvious errors (and does not add the ApiKey references back to the local files). But I noticed the following message at the end:

>GraphQL API is configured to use API_KEY authentication, but API Key deployment is disabled, don't forget to create one.

I will update this section if I am unable to use Cognito User Pool tokens to work with the API.

**Comment by renebrandel** [comment]
Closing this as we've addressed the issue either in Studio today, which offers a web UI as well as. In Gen 2, we're offering a code-first approach to configure these things a bit more clearly.
