### ISSUE TITLE
Need to allow operations on primary key when using field auth rules

### ISSUE THREAD

**Issue by clemracpro** [aws-amplify/amplify-category-api#863]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

10.0.0

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth

### Amplify Commands

Not applicable

### Describe the bug

We have a GraphQL model created in an Amplify App with Cognito User Pool for Auth.

I have a schema for storing tickets. The owner of the ticket, and the SuperAdmin group have all permissions. A connected user can only read the ticket, add a vote, add a comment.

So I set the schema to authorize by default only Read to connected user :
![image](https://user-images.githubusercontent.com/107876376/194566334-67081ece-c516-4db1-a16f-e21b78e2bbe9.png)

And added all permissions for Votes and Comments :
![image](https://user-images.githubusercontent.com/107876376/194566536-01d9f1ce-1a6c-4bf1-9faa-bcdeb23dd4c0.png)

If I now run a GraphQL request to update the Vote or Comment field, I have an Unauthorized error on field ID.

If I want this to work, I need to add Update permission on ID field :
![image](https://user-images.githubusercontent.com/107876376/194566940-28171203-22cc-4b9c-98ae-5d92a5936077.png)

Is this a bug ? Or is there a better way to do this ?

Thanks a lot for your future reply :)

### Expected behavior

I want to be able to run an Update request without changing the Auth rules of the primary key.

### Reproduction steps

1. Create a similar schema linked to a Cognito User Pool.
2. Create a ticket as a superadmin
3. Try to add a vote as a private user

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @clemracpro :wave: thanks for raising this and apologies for the delay here! Are you still experiencing this issue? What is the motivation for including a field-level auth rule on the primary key attribute?

**Comment by AnilMaktala** [comment]
Hi @clemracpro 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment and provide us with the information our team had previously asked for. This way, we can reopen the issue and provide you with better assistance.

Thank you!
