### ISSUE TITLE
@Searchable On GraphQL Trans v2 is not working 

### ISSUE THREAD

**Issue by etsPro** [aws-amplify/amplify-category-api#865]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

graphql

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
10.2.1
**What AWS Services are you utilizing?**

graphql

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

Hello .. I'm trying to use @searchable directive for GraphQL Transformer v2 with @searchable but can't receiving the error "Resource is not in the state stackUpdateComplete" in the "SearchableStack" step while executing amplify push .. attached is my schema and the screen shot of the error 
<img width="683" alt="Screen Shot 2022-10-08 at 7 54 55 AM" src="https://user-images.githubusercontent.com/115335231/194689160-3b219103-9e55-41d5-9b26-8eccc7688531.png">
<img width="1280" alt="Screen Shot 2022-10-08 at 7 10 21 AM" src="https://user-images.githubusercontent.com/115335231/194689163-51057bfe-d55e-4011-a097-ef0f24eb255b.png">

**Comment by etsPro** [comment]
After further testing .. here is some additional info :

apparently the above reported issue has to do with the chosen region for deployment , when I repeated the whole thing for region us-east-1 it worked .. 

but When I do it for another region like me-south-1  ....from the error message it seems a failure in provisioning the the new OpenSearch Domain in me-south-1 region ..

**Comment by etsPro** [comment]
hello .. two weeks since the first post... any feedback here ?

**Comment by etsPro** [comment]
Guys .. is there a problem here ? is Open Search working in certain Regions only ?

**Comment by da45** [comment]
what about pricing with @searchable ?

**Comment by etsPro** [comment]
more than 2 months with 0 comments from the support guys ! .. this is impressive !!

**Comment by josefaidt** [comment]
Hey @etsPro :wave: apologies for the delay here, but thank you for raising this!! If you visit the AWS CloudFormation console and inspect the "Events" for the failed stack, do you see a specific error? Perhaps the OpenSearch instance type is not available in your target region.

Can you try a different instance type for this region? https://docs.amplify.aws/cli-legacy/graphql-transformer/config-params/#elasticsearchinstancetype

**Comment by etsPro** [comment]
wow .. I'm impressed . .. so you guys actually look at our messages and only reply if you see the level of frustration reached a certain mark ..Ok now I understand 

about the above suggestion, sure I will check it out within 2- 3 months as my time allows ..

**Comment by josefaidt** [comment]
Hey @etsPro are you still experiencing this?

**Comment by enleet** [comment]
Hi .. I didn't test recently .. I will check and let you know

**Comment by phani-srikar** [comment]
Hi, I cannot reproduce the issue on my end. Could you please re-open this if you're still facing the issue? Thanks.
