### ISSUE TITLE
Sorting does not work for updatedAt/createdAt using search* Gql Queries

### ISSUE THREAD

**Issue by michaetto** [aws-amplify/amplify-category-api#87]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.19.0

### Amplify CLI Version

7.6.23

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

elasticsearchVersion = "OpenSearch_1.1"  by override.ts

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

Fields createdAt and updatedAt are AWSDateTime in api which results in date type in OpenSearch cluster type mapping.
It means they are non-keyword types, and that's the reason sorting on them does not work in search* GQL Queries.
Overwriting Query.search*.req.vtl template and adding them manually to $nonKeywordFields solves the problem.

### Expected behavior

Amplify generates Query.search*.req.vtl with updatedAt/createdAt in $nonKeywordFields or solves buggy sorting on those fields in another way.

### Reproduction steps

1. Run search* GQL Query trying to sort by updatedAt/createdAt.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by danyalxahid** [comment]
Any update on this?
