### ISSUE TITLE
Lambda authorizer not getting data from DynamoDB table's record

### ISSUE THREAD

**Issue by leonardocfor** [aws-amplify/amplify-category-api#886]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

8.4.0

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

custom, api

### Amplify Commands

Not applicable

### Describe the bug

Hi,

I'm trying to implement multi-user access to records belonging to a different owner by using custom-based authentication via AWS Lambda for a table in my schema (**Team table** bellow). The idea is that the table has a set of Cognito-authorized users (**members field** of type AWSJSON) and once a query,mutation,subscription is made, the Lambda function will check if the requesting user has been authorized and therefore proceed with delivering the data. I've been testing it as follows: 

```bash
const teamID = 'xxxxxxxxxxxxxxxxxxxxxxx'
const ddb = new AWS.DynamoDB({apiVersion: '2012-10-08'});
  const params = {
    TableName: 'Team-xxxxxxx',
    Key: {
      id: {
        S: teamID      
      }
    }
  };
  // Call DynamoDB to read the item from the table
  ddb.getItem(params, (err, data) => {
    if (err) {
      console.log("Error", err);
    } else {
      console.log("Success", data);
    }
  });
```
Unfortunately, it seems that this piece of code is simply not being executed because nothing is printed, no data, no error. For testing purposes, I gave the lambda a full-access policy for DynamoDB with the same results. Can you provide assistance ? 

Thank you,

### Expected behavior

Obtain the data from the Team table's record to check for the members field and respond accordingly

### Reproduction steps

Unnecessary

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Team
  @model
  @auth(
    rules: [
      { allow: owner }
      { allow: custom }
    ]
  ){
  id: ID!
  name: String!
  members: AWSJSON
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by leonardocfor** [comment]
Hi guys, any help would be really appreciated

**Comment by chrisbonifacio** [comment]
Hi @leonardocfor :wave: 

some follow up questions: 

1. Can you explain the flow or order of things you expect to happen starting from the client to the lambda authorizer and then where you expect the response data to come from? The Lambda should only responsible for determining the user is authorized to continue with the request or not, the data that is returned by AppSync would come from the resolver.

2. What is the shape of your `members` AWSJON values?

3. Depending on what your use case is, are there limitations to the `owner` auth rules we support, such as static or dynamic owner lists, that you felt you had to use a JSON list of users?

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!

**Comment by leonardocfor** [comment]
Hi @chrisbonifacio and @MatthewChon, I apologize for the delay in my response. Following, I answer your questions:

@chrisbonifacio:

**1. Can you explain the flow or order of things you expect to happen starting from the client to the lambda authorizer and then where you expect the response data to come from? The Lambda should only responsible for determining the user is authorized to continue with the request or not, the data that is returned by AppSync would come from the resolver.**

The lambda is supposed to connect with DynamoDB (this is what it doesn't work) to check the `members` field in the table `team` and do the following:

1. The `authorizationToken` received from AppSync will include the user's ID. The lambda is to check if the user's ID exists as a key in the AWSJSON `members` field. 
2. If the user's ID exists in the `members` field, the lambda will check the specific permissions said user has over the table `Team`'s fields and specify accordingly the `deniedFields` field in the response for AppSync
3. If the user's ID does not exist in the `members` field, then simply deny the access to the `Team`'s record. 

Note: I understand this adds extra latency because of the need to get the record data from the DynamoDB table

**2. What is the shape of your members AWSJON values?**

Main keys in `members` field are authorized user's IDs. Per each user's ID, a list of denied fields in table Team

**3. Depending on what your use case is, are there limitations to the owner auth rules we support, such as static or dynamic owner lists, or even Cognito User Pool Groups, that you felt you had to use a JSON list of users?**

What I want to acheive, I believe it can be done via a list of owners as currently supported (I believe with Amplify version 10.3.1, even real time subscriptions are also allowed)  but the lambda approach will potentially have a finer grain access per field. 

@MatthewChon

Please correct me if I'm wrong but both static and dynamic groups authorization will not work because I believe those are related to Cognito and not to a specific team within the database.


@chrisbonifacio, @MatthewChon, I have an extra question regarding a similar issue. Consider a table that has many records, before a new user who is to be allowed for those records, joins the app. If using a list of owners for that table, does that mean that all previous records before the user joins, need to be updated to include the new user's ID in the list of owners ? I believe this to be the case, so I'm wondering if there is more scalable alternative? This concern also led me to consider lambda-based authentication with direct interaction between the lamdba function and DynamoDB before responding to AppSync, e.g. having another table that specifies this "global" permits over other tables and with that approach avoid needing to update all records in a table. 

I appreciate your help guys,

**Comment by MatthewChon** [comment]
Currently we don’t yet have support for federated auth (i.e. joining multiple dynamodb tables in order to perform a access lookup). However, the alternative to what you are trying to accomplish is to use the group authorization rule. The group authorization rule will allow you control the group’s CRUD operations and data flow of each group.
```graphql
type Team
  @model
  @auth(
    rules: [
      { allow: groups, groupFields: [“adminGroup”], operations: [create, read, update, delete] },
      { allow: groups, groupFields:[“subscriberGroup”], operations: [create, read] },
    …
    ]
  ){
  id: ID!
  name: String!
  adminGroup: [String!]
  subscriberGroup: [String!]
}
```
This will create two columns in the table, adminGroup that allows all CRUD operations, and subscriberGroup, which will limit the user’s in the group to create and read.

**Comment by leonardocfor** [comment]
Hi  @MatthewChon, thank you for your reply. This approach will not allow me to have fine-grain access per field. However, regarding your suggestion, I have two questions: 

- What should be placed for example in the adminGroup field? User's IDs or ... ?
- Please see my previous question in the last comment: 
I have an extra question regarding a similar issue. Consider a table that has many records, before a new user who is to be allowed for those records, joins the app. If using a list of owners for that table, does that mean that all previous records before the user joins, need to be updated to include the new user's ID in the list of owners ? I believe this to be the case, so I'm wondering if there is more scalable alternative? This concern also led me to consider lambda-based authentication with direct interaction between the lamdba function and DynamoDB before responding to AppSync, e.g. having another table that specifies this "global" permits over other tables and with that approach avoid needing to update all records in a table.

Thank you

**Comment by leonardocfor** [comment]
Hey guys, any update ? Thank you

**Comment by alharris-at** [comment]
Hi @leonardocfor, for the case you're describing, if you wish new users to have access to all data, then group owners might be a better fit for you. E.g. when a user signs up you add them to some group based on their role, then grant that group access to records via owner-based records https://docs.amplify.aws/cli/graphql/authorization-rules/#user-group-based-data-access

Additionally, if you do need finer-grained access, and wish to implement your own behavor, you can write custom appsync resolver functions which run after the data is loaded to add your own business logic (in this case `postDataLoad` is probably the right lifecycle state if you need to make per-record decisions https://docs.amplify.aws/cli/graphql/custom-business-logic/#extend-amplify-generated-resolvers.
