### ISSUE TITLE
Problem with bidirectional "hasOne" relationship

### ISSUE THREAD

**Issue by caesarisme** [aws-amplify/amplify-category-api#89]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
AppSync graphql

**Amplify CLI Version**
7.6.23

**What AWS Services are you utilizing?**
AppSync, Dynamodb

I have 2 models:
`
  type ParkingPlace
    @model
    @auth(
      rules: [
        { allow: public, provider: apiKey }
        { allow: private, operations: [read] }
        { allow: groups, provider: userPools, groups: ["Admin"] }
      ]
    ) {
    id: ID!
    isAvailable: Boolean!
    ticket: Ticket @hasOne(fields: ["ticketId"])
    ticketId: ID
  }

  type Ticket
    @model
    @auth(
      rules: [
        { allow: public, provider: apiKey }
        { allow: owner, ownerField: "owner", operations: [read] }
        { allow: groups, provider: userPools, groups: ["Admin"] }
      ]
    ) {
    id: ID!
    parkingPlace: ParkingPlace @belongsTo(fields: ["parkingPlaceId"])
    parkingPlaceId: ID
    owner: String!
    expiresAt: AWSDateTime
  }
`

After creating a Ticket with given 'parkingPlaceId'
1. The 'ticketId' field of 'ParkingPlace'  does not get filled
2. 'ticket' field is always null when I try to query 'listParkingPlaces'

`
listParkingPlaces(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        ticketId
        ticket {
          id
          expiresAt
          owner
        }
      }
      nextToken
    }
`

**Comment by SurajMothilal** [comment]
This is still an issue. Any update on this?

For the below two models, creating a profile for a user does not form the correct relationship. When I query for the user and drill down into the response, profile is null

This works if I change the `hasOne` to `hasMany` But that is just incorrect relationship declaration

type FireProfile @model {
  id: ID!
  targetYear: Int!
  fireType: String!
  targetYearlyExpense: String
  targetPortfolioValue: Float
  user: User @belongsTo
}

type User @model {
  id: ID!
  firstName: String!
  lastName: String
  accounts: [Account] @hasMany
  profile: FireProfile @hasOne
  dateOfBirth: AWSDate!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

**Comment by Simoneth** [comment]
same here...`hasMany` works not `hasOne` with `belongsTo`. 

What the hell are you doing? Everytime I push my edited schema I spend money!

**Comment by AnilMaktala** [comment]
Hi @caesarisme, We apologize for the delay in our response. After verifying with the latest CLI version, we were able to observe the expected results for the hasone relationship. We kindly request you to upgrade to the latest CLI version and try again. 

``` 
type Blog @model {
  id: ID!
  name: String!
  posts: Post @hasOne
}

type Post @model {
  id: ID! @primaryKey
  title: String!
  blog: Blog @belongsTo
}
```

<img width="1018" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/4689d9e4-a309-4524-aa8b-bca4514f176d">


<img width="1303" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/b06e8c4e-0253-447a-9098-01b15bcf4907">

**Comment by AnilMaktala** [comment]
Hi 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment and provide us with the information our team had previously asked for. This way, we can reopen the issue and provide you with better assistance.

Thank you!
