### ISSUE TITLE
amplify push throws caniuse-lite is outdated warning

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-category-api#896]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

10.2.3

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

Amplify cli throws the following error on each push

```
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```
possibly related to the graphql browser explorer

### Expected behavior

Not throw expired package warning on the cli.

### Reproduction steps

1. amplify init
2. amplify add function (any category is fine as well)
3. amplify push
Observe error

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ninjz** [comment]
I seem to be experiencing this issue now with the latest CLI version 10.4.1

**Comment by alex-coda-13** [comment]
No news on this ? When I do `amplify push` I get the same warning even with the latest version of amplify CLI

**Comment by palpatim** [comment]
This no longer appears to be happening at least as of 12.12.4
