### ISSUE TITLE
OpenSearch instance created with non-saveable security configuration

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-category-api#901]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.16

### Amplify CLI Version

10.3.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

I am experimenting with the searchable directive. 

I'd like Kibana dashboard access to my OpenSearch instance. 

So I'm editing the security configuration accordingly (would be helpful if amplify cli configures that out of the box for us). 

But I can't save my configuration unless Access policy has a restrictive policy. This is regardless if I touch anything else in the "Edit security configuration" screen. 

I get the error "Add at least one policy element." And if I put a simple policy, I get "To protect domains with public access, a restrictive policy or fine-grained access control is required.". 

So what policy should I put?

![CleanShot 2022-10-18 at 19 07 31@2x](https://user-images.githubusercontent.com/81853/196574462-7d20daf7-dc6d-4526-8387-024726e8ce66.png)

### Expected behavior

Amplify cli should fill this policy out with a default that is appropriate

### Reproduction steps

Use the searchable directive in a graphql api, and try to save the "Edit security configuration" screen in the created opensearch instance. 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hisham** [comment]
Related stackoverflow question for serverless: https://stackoverflow.com/questions/64426133/deployment-of-servless-app-fails-enable-fine-grained-access-control-or-apply-a

So how does amplify cli manage to create an OpenSearch instance with an unspecified domain level access policy?

**Comment by ykethan** [comment]
Hey @hisham, amplify api overrides supports modifying the access policy using the attributes `resources.opensearch.OpenSearchDomain.accessPolicies` in CDK. Please refer to https://docs.amplify.aws/cli/graphql/override/#customize-amplify-generated-resources-for-searchable-opensearch-directive.

> how does amplify cli manage to create an OpenSearch instance with an unspecified domain level access policy?
 
on diving into the Opensearch cloudformation documentation, the `AccessPolicies` attribute is not a required attribute. Please refer to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#aws-resource-elasticsearch-domain-properties providing additional information. 

Additionally, I was able to find the following documentation providing information on accessing a Opensearch from a Dashboard client.
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/dashboards.html#dashboards-access

**Comment by ykethan** [comment]
Hey @hisham , following up on this issue. Please do let us know if you require any assistance.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Please feel free in reaching out to us again.

**Comment by hisham** [comment]
Thanks @ykethan , you answered my question.
