### ISSUE TITLE
OpenSearch cluster health is yellow

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-category-api#905]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.6

### Amplify CLI Version

10.3.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

I used ```@searchable``` directive which creates OpenSearch stack. 

I did a backfill which resulted in adding 288 entries to OpenSearch. 

The Cluster Health is now yellow. AWS Support says it's because: 

> I would like to inform that single node cluster becomes a single point of failure and does not enable the replicas to get allocated and can result in yellow state as observed in your case. As you might know primary and replica shards cannot be assigned on same node. 
> 
> Single-node clusters always initialize with a yellow cluster status because there is no other node to which Amazon OpenSearch can assign a replica. To achieve green cluster status, you can increase your node count.

I could increase node count through the console. But what's best way to do it via amplify cli overrides.ts / cloudformation? 

Also why doesn't amplify cli use more than one node to begin with? 

I'm not very familiar with OpenSearch so more documentation / explanations are needed. Thanks! 

### Expected behavior

Cluster Health should be green. 

### Reproduction steps

Use searchable directive, and I believe any cluster created will be in yellow status. 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
Hey @hisham, thank you for reaching. As you have pointed out, we can increase the node count using the api override functionality. Please refer to https://docs.amplify.aws/cli/graphql/override/#customize-amplify-generated-resources-for-searchable-opensearch-directive providing an example.

> why doesn't amplify cli use more than one node to begin with?

As this would prevent users from accruing cost from an additional node while bring able to modify the instance according to their use case using functionality such as override.

**Comment by hisham** [comment]
I see ok thanks. In this case we'd only want to increase node count in prod environment. But there's no ready-made access to the environment name in overrides.ts that I see (related to https://github.com/aws-amplify/amplify-cli/issues/9063)

**Comment by ykethan** [comment]
Hey @hisham, thank you for the information. Overriding a OpenSearch domain in a specific environment is currently not supported workflow. On diving deeper into the custom CDK option I was unable to find a workaround on making modifications on a imported OpenSearch instance. The AWS CLI does support making updates to a domain but this would require additional testing in a test environment and to test for any unintended behaviors. https://docs.aws.amazon.com/cli/latest/reference/opensearch/update-domain-config.html

**Comment by ykethan** [comment]
Hey @hisham , following up on this issue. Please do let us know if you require any assistance.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Please feel free in reaching out to us again.
