### ISSUE TITLE
Using `allow:public` and `allow:owner` together

### ISSUE THREAD

**Issue by jdanielsyeah** [aws-amplify/amplify-category-api#911]
**Which Category is your question related to?**
API (GRAPHQL) - Authorization Rules
**Amplify CLI Version**
v2
**What AWS Services are you utilizing?**
`amplify add api`, `amplify add auth`

**Provide additional details e.g. code snippets:**
**EDIT:** I think I might understand now. The below permits public access to read 'Todo' on other apps. For example, in my app where I have Cognito sign-in set up, it won't have any effect. But I might have another app without Cognito sign-in, in which case it would permit the visitor to read the Todo data. Is that right?
At the beginning of the [API (GRAPHQL) Authorization rules docs](https://docs.amplify.aws/cli/graphql/authorization-rules/), there is an example provided:
```graphql
type Todo @model @auth(rules: [
  { allow: public, operations: [read]},
  { allow: owner }
]) {
  content: String
}
```

I'm struggling to understand why anyone would need both `allow:public` and `allow:owner`. I understand that `public` uses the API key behind the scenes, and that `owner` uses Cognito User Pools. If I sign into my Amplify app and try to get my Todo items then the call is successful; however, if I remove the `{ allow: public, operations: [read]},` I get the same results, making the `  { allow: owner }` line redundant.

If I remove the `  { allow: public, operations: [read]},` and just leave `  { allow: owner }`, then I get an error: `Not Authorized to access listTodos on type Query`

My experience is that `allow: public` only works until I add Cognito User Pools with `amplify update auth`. Then it stops working, making `allow:owner` redundant once Cognito has been added. 

I'm guessing I've got something wrong, or else the example provided is non-sensical?

**Comment by ykethan** [comment]
Hey @jdanielsyeah, Thank you for reaching out. 
When utilizing `{ allow: public, operations: [read]},{ allow: owner }` the `allow: public` along side the use case highlighted by you, also allow users to call a GraphQL API from a Lambda function or NodeJS as a use case. Please refer to https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js/ providing an example. 

> If I remove the { allow: public, operations: [read]}, and just leave { allow: owner }, then I get an error: Not Authorized to access listTodos on type Query

Curious on this, does this issue occur on your Client side(Frontend application)? if yes, does the GraphQL API resource created utilize API key as a default authentication type? 
When calling a GraphQL API using `API.graphql(graphqlOperation(createTodos))` (for example) will utilize the default authentication type. If you require the application to use Cognito as a authentication type as `{ allow: owner }` has create access, we can utilize the example provided here: https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/js/#using-amplify-graphql-client to set a `authMode`.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
