### ISSUE TITLE
Field not found in a Match table

### ISSUE THREAD

**Issue by gmako6** [aws-amplify/amplify-category-api#917]
So I was pushing a local updated schema and unfortunately failed to give this information

? Are you sure you want to continue? Yes
🛑 user2ID is not a field in Match

This is the code and the error I got
<img width="716" alt="Screen Shot 2022-10-24 at 6 12 57 AM" src="https://user-images.githubusercontent.com/37672372/197442035-3484ce6c-d85a-4a9c-a62f-c7c439b7973c.png">

and here I the scheme I created was amplify
![Screen Shot 2022-10-24 at 6 13 19 AM](https://user-images.githubusercontent.com/37672372/197442161-829b6347-8db9-4bb9-936e-548e030b08ea.png)

any help please?

**Comment by AnilMaktala** [comment]
Hey @gmako6 👋, Please try changing the field name from ["user2ID"] to ["User2ID"] in graphql schema (line number 10).

**Comment by gmako6** [comment]
Wow ....work misspelling. Thank you, everyone

<img width="706" alt="Screen Shot 2022-10-29 at 2 45 21 AM" src="https://user-images.githubusercontent.com/37672372/198751229-2d968ace-6530-40b0-82bf-fbbdf5998a8d.png">
