### ISSUE TITLE
GraphQL Queries stopped working all of a sudden

### ISSUE THREAD

**Issue by dubiella** [aws-amplify/amplify-category-api#918]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

10.3.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Nothin was done! GraphQL stop to work around 17h UTC

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

GraphQL  stop to get the query... nothing was done...
They stop around 17UTC 21-Oct

I try manually test get the query using the AWS AppSync Online interface.
a this is when get weird!

I do my fetch using sortDirection: ASC (Was working fine!) now stop!
![image](https://user-images.githubusercontent.com/2163718/197307453-207b3448-7338-46d9-93ff-d92dcf86b3fa.png)
I'm receiving 0 item!

Now look what happen when i change to sortDirection: DESC
![image](https://user-images.githubusercontent.com/2163718/197307502-574628fd-8b92-448c-929a-363334362731.png)

I get my list!

I really my list in ASC !

### Expected behavior

I expect to have my in ASC  as well ... was working before
![image](https://user-images.githubusercontent.com/2163718/197307502-574628fd-8b92-448c-929a-363334362731.png)

### Reproduction steps

1. Go to GraphQL
2. query sortDirection: ASC nothing happen
3. query sortDirection: DESCnothing happen - i got the list

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by AnilMaktala** [comment]
Hi @dubiella  👋 thanks for raising this issue.we are working on reproducing the issue, Could you please run below command and send us the report amplify diagnose --send-report

**Comment by AnilMaktala** [comment]
Hi @dubiella, Are you still experiencing this issue??

**Comment by Bhavika-Gianey** [comment]
Hii @dubiella, I tried to reproduce the issue and found that the query functions are working correctly. 
The schema used is :
 ```graphql
 type CatRequest @model @auth(rules: [{ allow: owner }]){
  id: ID!
  name: String!
  status: String
  type: String! @index(name: "CatRequestByDate", queryField: "CatRequestByDate", sortKeyFields: ["createdAt"])
  createdAt : String!
 }
```

Using the above model, the queries will work correctly

- The ASC sort: 
![asc](https://user-images.githubusercontent.com/63343906/222703044-d85eaa25-08b5-410d-bf5f-0e85f51087f1.PNG)

- The DESC sort:
![desc](https://user-images.githubusercontent.com/63343906/222703158-1201ace6-9bef-4986-b6e9-7dd61d1f3234.PNG)

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!

**Comment by QuantumStatic** [comment]
I am facing the exact same issue however, I don't know how to reproduce it, since it's code taken from [official docs](https://docs.amplify.aws/javascript/build-a-backend/graphqlapi/query-data/) but suddenly all I am getting is `Unhandled Promise Rejection`

I did run the diagnose command:
`Project Identifier: 9490f6e494d7caf7b17f4a9f98c9f6f5`
[report-1701850668667.zip](https://github.com/aws-amplify/amplify-category-api/files/13578362/report-1701850668667.zip)
