### ISSUE TITLE
Amplify ElasticSearch Domain stuck in "Upgrading" state

### ISSUE THREAD

**Issue by whunter** [aws-amplify/amplify-category-api#920]
Hi, my group has an ElasticSearch domain (created via Amplify) that has been stuck in the "Upgrading" state for about 3 days. I ran the "Pre-Upgrade Check from 6.2 to 6.8" tool and it has never completed. It just says "In progress (33.33%)" It seems like all of the options are disabled until the upgrade is complete so I guess we're stuck for now?

Anyone know how to resolve this?

Version: Elasticsearch 6.2
Service software version: R20211203-P2
t2.medium.elasticsearch

**Comment by AnilMaktala** [comment]
Hi @whunter 👋, are you still experiencing this issue? If yes, please run the command "amplify diagnose --send--report" and send us the report.
