### ISSUE TITLE
How to set the data source on a pipeline resolve fn

### ISSUE THREAD

**Issue by gxxcastillo** [aws-amplify/amplify-category-api#924]
**Which Category is your question related to?**
API

**Amplify CLI Version**
10.3.0

**What AWS Services are you utilizing?**
Appsync

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
I've been able to [extend amplify generated VTL resolvers](https://docs.amplify.aws/cli/graphql/custom-business-logic/#extend-amplify-generated-resolvers), however, how would I go about assigning their "data source"?

In my use case, my vtl resolver is doing a batch write and returning a bunch of IDs, I'm then creating a postUpdate resolver that takes one of those IDs and does a GetItem with it.  Up until now, I've had to manually go through the appsync UI to accomplish this each time I push to a new environment and it would be great to have way to do that in the code.

**Comment by ykethan** [comment]
Hey @gxxcastillo, thank you for reaching out. This workflow is currently not supported. The feature is currently being tracked here: https://github.com/aws-amplify/amplify-category-api/issues/69. Please feel free in subscribing to the issue for any further updates.

**Comment by gxxcastillo** [comment]
The solution proposed here https://github.com/aws-amplify/amplify-cli/issues/9623#issuecomment-1023528618, which involves using override.ts to manually set the value of `models.{ModelName}.appsyncFunctions.{ResolverName}.dataSourceName` solved this for me.
