### ISSUE TITLE
Using Amplify DataStore with AwsAppSync client

### ISSUE THREAD

**Issue by fzy-spyro** [aws-amplify/amplify-category-api#937]
Hello, 
 
  I am creating mobile application that is supposed to use existing resources on AWS servers (Cognito, AppSync with GraphQL, etc).   As all backend resources are already created and ready, I decided to use Amplify iOS library to connect to them and followed https://docs.amplify.aws/lib/auth/existing-resources/q/platform/ios/ instructions. 
  
 I’ve configured the app to use library via SPM and implemented auth using Cognito and I am able to perform all sign-in/signup operations without issues. 
 
   Now I am adding support for backend storage via AppSync and I’d like to be able to use DataStore for offline mode.   When looking into AWS AppSync console it tells me to integrate it via: `amplify add codegen --apiId ABCD` command which generates `API.swift` file.     After looking into `API.swift` file contents I see that is uses https://github.com/awslabs/aws-mobile-appsync-sdk-ios which seems to not be a part of Amplify SDK and does not look like it is compatible with DataStore.   
   
   This leads me to a question - how can I use existing AppSync GraphQL API (generated in this `API.swift` file) with Amplify DataStore?  Is there a way to somehow import existing GraphQL schema into Amplify app and use it with DataStore? If so, how can this be achieved?    
   
   What I tried so far is to use https://github.com/awslabs/aws-mobile-appsync-sdk-ios to talk to GraphQL and it works but from what I see is that it does not support offline mode which I need in my app.

**Comment by fzy-spyro** [comment]
Hey, 
I was just wondering if there is any update on the above

**Comment by fzy-spyro** [comment]
No, still having the same issue with that particular setup. 

What I did instead is moved away from "pure" AppSync which was generating `API.swift` file and started using Amplify DataStore instead and then the codegen works. Sadly this is not ideal though because not everyone can do that kind of transition and it would be great if using DataStore with AwsAppSyncClient was supoprted.

**Comment by phani-srikar** [comment]
Hi @fzy-spyro, if you want to use DataStore, you would need to use `amplify add api` and provide your schema. We do not have an import flow for API plugin yet. The `amplify add codegen --apiId ABCD` command works for any AppSync API but is intended to be used only for statements and frontend types generation and not with DataStore.
