### ISSUE TITLE
GraphQL Transformer Migration Process leads to NONE_DS and stackUpdateComplete errors

### ISSUE THREAD

**Issue by emmafass** [aws-amplify/amplify-category-api#95]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.16.0

### Amplify CLI Version

7.6.22

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

auth, storage, function, api

### Amplify Commands

push

### Describe the bug

I am working on the migration from GraphQL Transformer v1 to v2. I ran `amplify migrate api` and fixed any issues so that the schema compiled properly. 

I then tried to `amplify push`. I first ran into the `Data source with name NONE_DS already exists` issue. I found aws-amplify/amplify-cli#9200 and followed the steps given by @sundersc 

- Update the schema to V1 schema and do amplify push, wait for it to complete.
- Go to AppSync console and open the api. For all the functions using NONE_DS datasource, manually change it to NONE.
- Delete the NONE_DS datasource.
- Update the schema to v2 and push again.

I found that this solution would cause `amplify push` to run for a while and create some new Functions in my AppSync console, but inevitably it would error out with the same NONE_DS error. The new functions created in the AppSync console would still have the NONE_DS data source. I would have to keep repeating the steps given by @sundersc over and over.

I have about 73 models, so maybe those steps work for people with smaller schemas.

I eventually hit a point where `amplify push` would give me `An error occurred during the push operation: ["Index: 4 State: {\"deploy\":\"waitingForDeployment\"} Message: Resource is not in the state stackUpdateComplete"` errors. 

Even after trying the `amplify pull` method of reverting things back and starting again, I continued to get errors like `An error occurred during the push operation: ["Index: 4 State: {\"deploy\":\"waitingForDeployment\"} Message: Resource is not in the state stackUpdateComplete","Index: 0 State: {\"rollback\":\"waitingForRollback\"} Message: Resource is not in the state stackUpdateComplete"]`

I am currently stuck here.

****

### Expected behavior

That I can run `amplify migrate api` and `amplify push` successfully.

### Reproduction steps

Explained above.

For more context, at one point I attempted to use DataStore in my application. I then decided against it, ran `amplify update api`, and disabled conflict detection.

### GraphQL schema(s)

My GraphQL schema is in multiple files under a /schema folder. I will zip it and send it to amplify-cli@amazon.com as suggested by @sundersc

**Comment by renebrandel** [comment]
Hi - I'm closing this issue out as there hasn't been further reports and the most recent comments indicated that the deletion and recreate was feasible and resolved the issues subsequently. Please @-mention me to request a re-open if this still occurs.
