### ISSUE TITLE
GraphQL API schema build should fail when specifying an `ownerField` that does not exist on the model (case-sensitive)

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-category-api#957]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

18

### Amplify CLI Version

10.4.0

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

When specifying an owner field in an auth rule to a field that does not exist on the model (case-sensitive), the CLI should fail and exit the push attempt.

```graphql
type Invoice
  @model
  @auth(
    rules: [
      {
        allow: owner
        ownerField: "storeID"
        operations: [create, read, update, delete]
      }
      { allow: owner, ownerField: "customerID", operations: [read] }
    ]
  ) {
  id: ID!
  items: [String]
  storeID: ID!
  # note bad capitalization for "customerID"
  customerId: ID!
}
```

### Expected behavior

see above

### Reproduction steps

1. `amplify init -y`
2. `amplify add api` > specify Cognito User Pools as the auth mechanism
3. add schema with invalid `ownerField`
4. `amplify push -y`
5.  observe successful push
6. observe unable to successfully use auth rule in AppSync console

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Invoice
  @model
  @auth(
    rules: [
      {
        allow: owner
        ownerField: "storeID"
        operations: [create, read, update, delete]
      }
      { allow: owner, ownerField: "customerID", operations: [read] }
    ]
  ) {
  id: ID!
  items: [String]
  storeID: ID!
  # note bad capitalization for "customerID"
  customerId: ID!
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ncarvajalc** [comment]
# Findings
I believe that there is a bug related with this issue. When looking at the codebase, I found the function in charge of adding the owner fields to the schema:
https://github.com/aws-amplify/amplify-category-api/blob/8a6fd849e2af25ecab46dfea1b6b5511dcf5750b/packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts#L1040-L1053
The function first gets all of the existing fields and then compares it with the ownerFields from the `{ allow: owner }` and { allow: owner, ownerField: "customOwnerField"} rule. In case the only rule is `{ allow: owner }`, then `owner` is added as a new field as expected. The thing that is not consistent is when `{ allow: owner, ownerField: "customOwnerField" }` is used. In case `"customOwnerField"` is not defined in the schema, it will be added as an owner field and uploaded to AppSync, regardless of not being defined in the schema. This is not consistent with the [docs](https://docs.amplify.aws/cli/graphql/authorization-rules/#public-data-access), as they show in every example that the field has to be added explicitly in the schema.

The following examples are found in the Amplify docs:
```graphql
type Todo @model @auth(rules: [{ allow: owner, ownerField: "author" }]) {
  content: String                             #^^^^^^^^^^^^^^^^^^^^
  author: String # record owner information now stored in "author" field
}
```
```graphql
type Todo @model @auth(rules: [{ allow: owner, ownerField: "authors" }]) {
  content: String
  authors: [String]
}
```
They show that the field has to be defined in the schema. 

By allowing non defined fields in the schema as ownerFields the developer looses control of what the field can do, such as making the field not null or using it as a list of owners.

Also, some implemented features such as warning the developer of ownership modification do not consider the fields which are not defined in the schema.

The following example illustrates this issue:

Consider the following schema:
```graphql
type Invoice
  @model
  @auth(
    rules: [
      {
        allow: owner
        ownerField: "storeID"
        operations: [create, read, update, delete]
      }
      {
        allow: owner
        ownerField: "customerId"
        operations: [create, read, update, delete]
      }
    ]
  ) {
  id: ID!
  items: [String]
  storeID: ID!
  # note correct capitalization for "customerId"
  customerId: ID!
}
```
Notice that `customerId` is correctly spelled. When compiling the schema the following warning is raised:
![image](https://user-images.githubusercontent.com/66692533/204339326-5eb8692c-d49a-44e7-9db7-9cccd510aab4.png)

Now consider this other schema:
```graphql
type Invoice
  @model
  @auth(
    rules: [
      {
        allow: owner
        ownerField: "storeID"
        operations: [create, read, update, delete]
      }
      {
        allow: owner
        ownerField: "customerID"
        operations: [create, read, update, delete]
      }
    ]
  ) {
  id: ID!
  items: [String]
  storeID: ID!
  # note bad capitalization for "customerID"
  customerId: ID!
}
```
Now the following warning is raised:
![image](https://user-images.githubusercontent.com/66692533/204339646-0ffab374-aec5-4216-a835-995fdf1e18ee.png)

Notice that the newly created `customerID` field is not present in the warning, eventhough it is present in AppSync:
![image](https://user-images.githubusercontent.com/66692533/204340019-e795ea6c-5d8b-45cd-873b-377d54b3ba06.png)
  
The reason I raise this is to consider the prevention of not defined fields to be added as ownerFields. This could cause breaking changes for users who are using not defined fields as owner fields but this would be consistent with the docs and with the warnings related to reassigning ownership. Will send a PR with this changes.

**Comment by alharris-at** [comment]
Given Input Schema:
```gql
type Invoice
  @model
  @auth(
    rules: [
      {
        allow: owner
        ownerField: "storeID"
        operations: [create, read, update, delete]
      }
      { allow: owner, ownerField: "customerID", operations: [read] }
    ]
  ) {
  id: ID!
  items: [String]
  storeID: ID!
  # note bad capitalization for "customerID"
  customerId: ID!
}
```

We'll generate shape 
```gql
type Invoice {
  id: ID!
  items: [String]
  storeID: ID!
  customerId: ID!
  customerID: ID!
}
```

But this is working as expected.

I'm not aligned that there's necessarily anything not working here. Marking as a feature request.
