### ISSUE TITLE
Amplify should support multiple API Keys

### ISSUE THREAD

**Issue by AndreasEK** [aws-amplify/amplify-category-api#97]
I just stumbled upon this. Why does the limitation to a single API Key exist? The web console does allow for multiple API Keys, and also the referenced security documentation does not say anything about api keys. 

https://github.com/aws-amplify/amplify-cli/blob/b0ff0223ba5196295a00ba18c321b6ff57f9f0ac/packages/amplify-graphql-transformer-core/src/graphql-api.ts#L304

**Comment by renebrandel** [comment]
Hi - we're closing this as this feature isn't getting much traction. You can optionally add additional authorization mode configurations via the our CDK overrides `amplify override api`. By default, we still want to limit the excessive usage of API keys and do recommend to use IAM (via identity pool's unauthenticated role) for public data authorization.
