### ISSUE TITLE
Update the error message when using multi-auth rules with subscriptions enabled

### ISSUE THREAD

**Issue by abdallahshaban557** [aws-amplify/amplify-category-api#971]
### Is this feature request related to a new or existing Amplify category?

api

### Describe the feature you'd like to request

When setting up models that have multi-auth rules at the model and field level, and there are required fields that are added to the model, all the auth rules need to be added to the required fields so that deployments can be successful to the Amplify backend. The message shown after stopping the push and update to the backend is not clear.

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/17932473/200683508-efb2d2dc-920c-4a9a-a63f-efede923b14d.png">

### Describe the solution you'd like

Update the message to clarify that you need to add all the Auth rules on the model/fields to the required fields - with at least read permission to enable a successful update and push to your backend.

### Describe alternatives you've considered

N/A

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Hey @abdallahshaban557 :wave: thanks for raising this! I, too, found myself a bit confused by this messaging, and would enjoy an included snippet or two along with a docs links for the suggestions. Marking this as a feature request and we will evaluate this further with the team 🙂
