### ISSUE TITLE
Local push isn't working anymore

### ISSUE THREAD

**Issue by rafaelfaria** [aws-amplify/amplify-category-api#972]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.17.0

### Amplify CLI Version

10.4.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

This started happening out of the blue, I can't really understand or think of how to replicate it.
I tried to deploy my environment locally and this started to happen.

I used to deploy using the following command `amplify push --forcePush --yes`
I went to try today and I keep getting this message now:

```
Deployment failed.
Deploying api GraphQLAPI [ ==-------------------------------------- ] 1/23
	GraphQLAPITransformerSchema3C… AWS::AppSync::GraphQLSchema    UPDATE_COMPLETE
Deploying function CreateStripeCheckoutSession [ ----------------------------------
	LambdaFunction                 AWS::Lambda::Function          UPDATE_FAILED
Deploying function WebhookPayments [ ---------------------------------------- ] 0/5
	AmplifyResourcesPolicy         AWS::IAM::Policy               CREATE_FAILED
^[[A
Rolled back (4 of 3)
🛑 ["Index: 2 State: {\"deploy\":\"waitingForDeployment\"} Message: Resource is not in the state stackUpdateComplete"]


Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
```

Is anyone able to help me? I can't get past this. Can't really get help on the troubleshooting page or can't find anything about it.

I would appreciate any help since I can't deploy through the console (https://github.com/aws-amplify/amplify-cli/issues/11292) and now I can't deploy manually. I'm 100% blocked now, thinking of alternatives from amplify because this is really slowing me down :/

### Expected behavior

Make the proper deploy of my changes to the cloud

### Reproduction steps

Run `amplify push --forcePush --yes` and this is happening.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by marcvberg** [comment]
Could you give a little more detail? Which categories are you deploying, what are the contents of your `amplify/cli.json`, and when you're looking at the error messages in cloudformation you should scroll down until the first error message that appeared, the screenshot above shows the recovery stages of the rollback but it doesn't show the error that occurred to cause it.

If you're willing, you may also send your `amplify` folder to amplify-cli@amazon.com

**Comment by rafaelfaria** [comment]
Hi @marcvberg 

I end up destroying my env and recreating again. Luckily this was only on my dev, it could've been pretty bad if this was prod I can close this for now and I will re-open if happens again. 

If this helps with anything in the future here is cli.json content.

```
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true,
      "securityenhancementnotification": false,
      "showfieldauthnotification": false,
      "usesubusernamefordefaultidentityclaim": true,
      "usefieldnameforprimarykeyconnectionfield": false,
      "enableautoindexquerynames": false,
      "respectprimarykeyattributesonconnectionfield": false,
      "shoulddeepmergedirectiveconfigdefaults": false,
      "populateownerfieldforstaticgroupauth": false
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true,
      "forcealiasattributes": false,
      "useenabledmfas": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "latestregionsupport": {
      "pinpoint": 1,
      "translate": 1,
      "transcribe": 1,
      "rekognition": 1,
      "textract": 1,
      "comprehend": 1
    },
    "project": {
      "overrides": true
    }
  },
  "debug": {
    "shareProjectConfig": false
  }
}```
