### ISSUE TITLE
Resolver is not updated to include Lambda Authorization rule

### ISSUE THREAD

**Issue by littlefeatheradmin** [aws-amplify/amplify-category-api#976]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

19

### Amplify CLI Version

10.4.0

### What operating system are you using?

ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

auth, api

### Amplify Commands

codegen

### Describe the bug

I have added a custom authorization rule to a model using `@auth(rules: [ {allow: custom} ])` but that is not reflected in the corresponding auth resolver for the model so the call to the model using AWS_LAMBDA authMode always return 401. I have both run a `amplify push` and `amplify codegen`. If I add the authorization rule manually to the resolver in AppSync console, like shown in the block below, then the call returns successfully.   

```vtl
#if( $util.authType() == "Lambda Authorization" )
  #return($util.toJson({}))
#end
```

### Expected behavior

Query to authenticate using lambda authorizer

### Reproduction steps

1. setup the project without lambda authorizer
2. create a model
3. amplify push
4. add lambda authorizer
5.

**Comment by Bhavika-Gianey** [comment]
> ### Before opening, please confirm:
> * [x]  I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
> * [x]  I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
> * [x]  I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
> * [x]  I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
> * [x]  I have removed any sensitive information from my code snippets and submission.
> 
> ### How did you install the Amplify CLI?
> npm
> 
> ### If applicable, what version of Node.js are you using?
> 19
> 
> ### Amplify CLI Version
> 10.4.0
> 
> ### What operating system are you using?
> ubuntu
> 
> ### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.
> No
> 
> ### Amplify Categories
> auth, api
> 
> ### Amplify Commands
> codegen
> 
> ### Describe the bug
> I have added a custom authorization rule to a model using `@auth(rules: [ {allow: custom} ])` but that is not reflected in the corresponding auth resolver for the model so the call to the model using AWS_LAMBDA authMode always return 401. I have both run a `amplify push` and `amplify codegen`. If I add the authorization rule manually to the resolver in AppSync console, like shown in the block below, then the call returns successfully.
> 
> ```velocity
> #if( $util.authType() == "Lambda Authorization" )
>   #return($util.toJson({}))
> #end
> ```
> 
> ### Expected behavior
> Query to authenticate using lambda authorizer
> 
> ### Reproduction steps
> 1. setup the project without lambda authorizer
> 2. create a model
> 3. amplify push
> 4. add lambda authorizer
> 
> ### GraphQL schema(s)
> _No response_
> 
> ### Log output
> _No response_
> 
> ### Additional information
> _No response_

Hii @littlefeatheradmin, I tried reproducing your issue. I created a public authorization mode for my Graphql schema and switched it off to the custom mode. On creating a custom mode, you will be asked to create a lambda function for the custom authorization; follow the prompts in the CLI to create one. We can check the auth mode in the resolver folder inside the build folder. The resolver folder contains multiple files. We can check the applied authorization modes by clicking on any of the files and seeing the auth modes for different queries and mutations.
![pp](https://user-images.githubusercontent.com/63343906/233703046-10398fe1-c2a1-4e71-a989-0ed818c117eb.PNG)

**Comment by AnilMaktala** [comment]
Hi @littlefeatheradmin 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment and provide us with the information our team had previously asked for. This way, we can reopen the issue and provide you with better assistance.

Thank you!
