### ISSUE TITLE
Apply `AND` operator with @searchable match query type

### ISSUE THREAD

**Issue by dhruvbansal2** [aws-amplify/amplify-category-api#997]
### Amplify CLI Version

9.2.1

### Question

Hello! 

I'm interested in modifying the ```operator``` advanced filter for my search query. The search query was generated using the @searchable amplify directive. 

Match: https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/#match

More specifically, we want to change operator to "and"
```
GET _search
{
  "query": {
    "match": {
      "title": {
        "query": "wind",
        "fuzziness": "AUTO",
        "fuzzy_transpositions": true,
        "operator":  "or",
        "minimum_should_match": 1,
        "analyzer": "standard",
        "zero_terms_query": "none",
        "lenient": false,
        "prefix_length": 0,
        "max_expansions": 50,
        "boost": 1
      }
    }
  }
}
``` 

I have tried the following with no luck
```
query SearchPosts {
  searchPosts(filter: { title: { match: "Stream Neftlix", operator: "AND" }}) {
    items {
      id
      title
    }
  }
}
```

Is this behavior supported? If not, are there any work arounds to achieve the same functionality?

**Comment by josefaidt** [comment]
Hey @dhruvbansal2 :wave: thanks for raising this! Have you manually migrated the searchable instance to use OpenSearch? The Amplify CLI will create an ElasticSearch instance, which the docs describe a different flow https://www.elastic.co/guide/en/elasticsearch/reference/7.10/query-dsl.html

Additionally, we have a list of supported search operations in our documentation which describe usage of `and`, `or`, and `not`: https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#supported-search-operations

**Comment by dhruvbansal2** [comment]
Hi @josefaidt, we are also on the ElasticSearch engine (i.e. we haven't manually migrated) - I referenced the wrong documentation. 

Looking at what you linked above, we are looking to achieve the following for ```match``` full-text queries
```
operator
(Optional, string) Boolean logic used to interpret text in the query value. Valid values are:

OR (Default)
For example, a query value of capital of Hungary is interpreted as capital
OR of OR Hungary.
AND
For example, a query value of capital of Hungary is interpreted as capital
AND of AND Hungary.
```
https://www.elastic.co/guide/en/elasticsearch/reference/7.10/query-dsl-match-query.html#match-field-params

Essentially, we have a single search field that we want to search against using the AND operator. 

```
searchField = "Joe Juice | California | Netflix"

query SearchData {
  searchModel(filter: { searchField: { match: "Joe Netflix", operator: "AND" }}) {
    items {
      id
      searchField
    }
  }
}
```

Ideally, we want the query to return all records that have Joe AND Netflix. Additionally, the searchQuery will be dynamic (user inputs this) so [nesting](https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#nested-search-conditions-and-or-not) doesn't seem like it will work in this situation?

**Comment by AnilMaktala** [comment]
Hi @dhruvbansal2 👋 , Please modify your query as shown below. I notice the intended results; please let us know if you require any further information.

```javascript
query SearchData {
  searchModel(filter: {and: {searchField: {match: "Joe Netflix"}}}) {
    items {
      id
      searchField
    }
  }
}
```
<img width="973" alt="image" src="https://user-images.githubusercontent.com/3206171/219414551-219d1720-458a-4633-833c-99923d730cbf.png">

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
